### ISSUE TITLE
unable to view live cameras,snapshots working fine

### ISSUE THREAD

**Issue by tarunprakashsingh** [dgreif/ring#1003]
Log attached... 

7/22/2022, 12:34:56 PM HOOBSRingPreparing Live Stream for Front Door
7/22/2022, 12:34:57 PM HOOBSRingStream Prepared for Front Door (0.525s)
7/22/2022, 12:34:57 PM HOOBSRingActivating stream for Front Door (0.809s)
7/22/2022, 12:34:57 PM HOOBSRingiceConnectionStateChange: completed
7/22/2022, 12:34:58 PM HOOBSRingStopped Live Stream for Front Door
7/22/2022, 12:34:58 PM HOOBSRingconnectionStateChange: closed
7/22/2022, 12:34:58 PM HOOBSRingiceConnectionStateChange: closed
7/22/2022, 12:35:00 PM HOOBSERROR[HOOBS 7533@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Front Door' was slow to respond!
7/22/2022, 12:35:07 PMHOOBS starting

**Comment by NickRivait** [comment]
Same

**Comment by dgreif** [comment]
#1005 is a good issue to follow for this
