### ISSUE TITLE
no live view but snapshots work

### ISSUE THREAD

**Issue by Fish2** [dgreif/ring#1004]
# Bug Report

### Describe the Bug
no live view in home app 

```[7/23/2022, 7:18:17 PM] [Ring] Activating stream for Front Door (0.867s)
[7/23/2022, 7:18:17 PM] [Ring] iceConnectionStateChange: completed
[7/23/2022, 7:18:17 PM] [Ring] connectionStateChange: connecting
[7/23/2022, 7:18:17 PM] [Ring] iceConnectionStateChange: new
[7/23/2022, 7:18:17 PM] [Ring] iceConnectionStateChange: checking
[7/23/2022, 7:18:17 PM] [Ring] Activating Session
[7/23/2022, 7:18:17 PM] [Ring] Streaming active for Front Door (1.254s)
[7/23/2022, 7:18:17 PM] [Ring] iceConnectionStateChange: new
[7/23/2022, 7:18:17 PM] [Ring] iceConnectionStateChange: connected
[7/23/2022, 7:18:18 PM] [Ring] Received stream data from Front Door (1.735s) 
```

### To Reproduce
open live view in he home app 

### Expected behavior
live view should display with in about 5s 

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
    "refreshToken": "xxx",
    "hideLightGroups": false,
    "hideDoorbellSwitch": false,
    "hideCameraSirenSwitch": false,
    "hideInHomeDoorbellSwitch": false,
    "hideAlarmSirenSwitch": false,
    "hideUnsupportedServices": true,
    "cameraStatusPollingSeconds": 20,
    "cameraDingsPollingSeconds": 1,
    "locationModePollingSeconds": 0,
    "platform": "Ring"

```

### Environment
 - OS: ubuntu 22.04
 - Node.js: v16.16.0
 - NPM: 8.11.0
 - homebridge-ring:  v11.0.7
 - homebridge: v1.5.0

**Comment by databoy01** [comment]
I have the same issue and from what it looks like the same versions of software.

**Comment by metalshark** [comment]
Again same versions, the same issue.

It seems to be initialising the RTP stream to localhost:

`From Ring (Front Door): Output #0, rtp, to 'rtp://127.0.0.1:51359?pkt_size=188':`

**Comment by Fish2** [comment]
Update: very odd I haven't changed anything in my setup and now working again

**Comment by Noddley** [comment]
Yea I have just finished moving all my homebridge off my pi to my home server but in that time the live view but snap shots work do you guys have any workaround

**Comment by metalshark** [comment]
> Yea I have just finished moving all my homebridge off my pi to my home server but in that time the live view broke but snap shots work do you guys have any workaround

Install alternative version and pick v11.0.6.

**Comment by dgreif** [comment]
Closing in favor of #1005. This is a HOOBS only issue as far as I can tell

**Comment by raiubreaksthings** [comment]
Sorry to be posting everywhwere, but this issue seems to be back. It does occur in hoobs and homebridge. This includes the most recent version of the plug in as well as the beta.

**Comment by tsightler** [comment]
@raiubreaksthings i would ask you not to just be sorry but to stop doing it.  It serves zero purpose to post this on multiple issues on the same project and it very annoying to maintainers. One post is plenty.

**Comment by databoy01** [comment]
No issue with mine as an FYI. Just verified and all cameras work perfectly.

**Comment by databoy01** [comment]
Although I stopped using HOOBS and now just use Homebridge. Seems to be much better and very stable. HOOBS might be the issue, as it always seemed to me that they had more issues than the people using Homebridge. Suggest you try that route also.

**Comment by raiubreaksthings** [comment]
> No issue with mine as an FYI. Just verified and all cameras work perfectly.

What version of homebridge and plug in are you on? 



> Although I stopped using HOOBS and now just use Homebridge. Seems to be much better and very stable. HOOBS might be the issue, as it always seemed to me that they had more issues than the people using Homebridge. Suggest you try that route also.

I was using homebridge when the issue first came up. I switched to hoobs and same issue is present.

**Comment by databoy01** [comment]
v1.6.1 Homebridge 
homebridge-ring v11.8.1

hope this helps ya.
