### ISSUE TITLE
Streaming on HOOBS not working since 11.0.7

### ISSUE THREAD

**Issue by databoy01** [dgreif/ring#1005]
# Bug Report

### Describe the Bug
Upgrade to 11.0.7 I am not able to see any live streams of any of my cameras. The hoobs doesn’t show any errors and you can see the attempt, but home app doesn’t see the stream. Says it’s offline. If I use the ring app I see everything perfectly.  

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
Live stream that isn’t shown. 

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

```

7/25/2022, 1:45:47 AMRing BridgeRingPreparing Live Stream for XXXXXXX
7/25/2022, 1:45:47 AMRing BridgeRingStream Prepared for XXXXXXX (0.33s)
7/25/2022, 1:45:47 AMRing BridgeRingActivating stream for XXXXXXX (0.386s)
7/25/2022, 1:45:48 AMRing BridgeRingiceConnectionStateChange: completed
7/25/2022, 1:45:48 AMRing BridgeRingStopped Live Stream for XXXXXXX
7/25/2022, 1:45:48 AMRing BridgeRingconnectionStateChange: closed
7/25/2022, 1:45:48 AMRing BridgeRingiceConnectionStateChange: closed
7/25/2022, 1:45:50 AMRing BridgeERROR[Ring Bridge 0F18@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'XXXXXXX' was slow to respond!
7/25/2022, 1:45:57 AMRing Bridge starting
7/25/2022, 1:46:02 AMRing BridgeLoaded plugin 'homebridge-ring'

```

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

### Environment
<!-- ✍️edit: -->
- Hoobs version 4.2.8
- node 16.16.0
- homebridge version 1.5.0

**Comment by databoy01** [comment]
I will add this above, but wanted to comment that this is what I’m seeing.  The bridge drops and shuts down and restarts every time I try a live stream in the home app.  I replaced camera name for “ XXXXXXX”


7/25/2022, 1:45:47 AMRing BridgeRingPreparing Live Stream for XXXXXXX
7/25/2022, 1:45:47 AMRing BridgeRingStream Prepared for XXXXXXX (0.33s)
7/25/2022, 1:45:47 AMRing BridgeRingActivating stream for XXXXXXX (0.386s)
7/25/2022, 1:45:48 AMRing BridgeRingiceConnectionStateChange: completed
7/25/2022, 1:45:48 AMRing BridgeRingStopped Live Stream for XXXXXXX
7/25/2022, 1:45:48 AMRing BridgeRingconnectionStateChange: closed
7/25/2022, 1:45:48 AMRing BridgeRingiceConnectionStateChange: closed
7/25/2022, 1:45:50 AMRing BridgeERROR[Ring Bridge 0F18@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'XXXXXXX' was slow to respond!
7/25/2022, 1:45:57 AMRing Bridge starting
7/25/2022, 1:46:02 AMRing BridgeLoaded plugin 'homebridge-ring'

**Comment by Ehreckk** [comment]
Having the exact same issue here. Commenting to follow thread.

**Comment by databoy01** [comment]
Unfortunately, I don’t see much use of GitHub for this though….  No one ever updates or lets you know anything.  They usually just close the issue as resolved…. Since this is one of many, I’d guess it is a universal problem with this software. I knew what I was getting into when I bought the device, although sadly I just don’t understand why create a platform for issues and then just ignore it.

**Comment by dgreif** [comment]
@databoy01 I do read the issues and take care of them when I have time, but I haven't had a lot of free time recently.  The main problem with issues like this one is that they are very hard to replicate.  Ring has added a lot of cameras over the last few years, and has drastically changed how they handle streaming from the cameras.  It's hard to pin down the exact issue because there are so many variables.

Looking at this issue thread specifically, I see most of you are on HOOBS.  Based on the logs, it seems like HOOBS might be ending the stream before it has a chance to start. If you have a fairly small setup, it might be worth trying simple homebridge instead of HOOBS to see if it works there

**Comment by cleanev** [comment]
Not sure if others find this in their logs, however manually restarted Ring plugin and each of the entries are doubled in logs see example below 
```8/1/2022, 11:30:10 AMringbridge stopping
8/1/2022, 11:30:15 AMRing Bridge starting
8/1/2022, 11:30:15 AMRing Bridge starting
8/1/2022, 11:30:22 AMRing BridgeLoaded plugin 'homebridge-ring'
8/1/2022, 11:30:22 AMRing BridgeLoaded plugin 'homebridge-ring'
8/1/2022, 11:30:22 AMRing BridgeLoading 1 platforms...
8/1/2022, 11:30:22 AMRing BridgeLoading 1 platforms...
8/1/2022, 11:30:22 AMRing BridgeRingConfiguring cached accessory Device hex - Name
8/1/2022, 11:30:22 AMRing BridgeRingConfiguring cached accessory Device hex - Name
8/1/2022, 11:30:22 AMRing BridgeRingConfiguring cached accessory Device hex - Name1
8/1/2022, 11:30:22 AMRing BridgeRingConfiguring cached accessory Device hex - Name1
8/1/2022, 11:30:22 AMRing BridgeRingConfiguring cached accessory Device hex - Name2
8/1/2022, 11:30:22 AMRing BridgeRingConfiguring cached accessory Device hex - Name2
.....
.....
.....
.....
8/1/2022, 11:30:22 AMRing BridgeBridge is running on port 52826.
8/1/2022, 11:30:22 AMRing BridgeBridge is running on port 52826.
8/1/2022, 11:30:23 AMRing BridgeRingFound the following locations:
8/1/2022, 11:30:23 AMRing BridgeRingFound the following locations:
8/1/2022, 11:30:23 AMRing BridgeRing  locationId: HEX code - Axxxxxxx
8/1/2022, 11:30:23 AMRing BridgeRing  locationId: HEX code - Axxxxxxx
8/1/2022, 11:30:23 AMRing BridgeRingCreating location socket.io connection - Axxxxxxx
8/1/2022, 11:30:23 AMRing BridgeRingCreating location socket.io connection - Axxxxxxx
8/1/2022, 11:30:24 AMRing BridgeRingRing connected to socket.io server
8/1/2022, 11:30:24 AMRing BridgeRingRing connected to socket.io server
8/1/2022, 11:30:24 AMRing BridgeRingConfiguring 4 cameras and 24 devices for location "Axxxxxxx" - locationId: HEX code
8/1/2022, 11:30:24 AMRing BridgeRingConfiguring 4 cameras and 24 devices for location "Axxxxxxx" - locationId: HEX code
8/1/2022, 11:30:24 AMRing BridgeConfiguration change
8/1/2022, 11:30:24 AMRing BridgeConfiguration change```

**Comment by dgreif** [comment]
@cleanev the double logging seems like a HOOBS issue.

I've released a new beta version (11.1.0-beta*) that adds a new `unbridgeCameras` option.  I'm interested to see if unbridging the cameras fixes this for any of you.

**Comment by cleanev** [comment]
@dgreif - thanks for the update. I will make a note with hoobs developer so they can fix this issue.
How do I get latest beta installed in Hoobs to test?
I checked from Hoobs front end and the only one update shows is still 11.0.7, while Ring is already at 11.0.7

**Comment by dgreif** [comment]
HOOBS is a bit restrictive on which versions they make available for install via the UI.  I'm honestly not sure how to install a beta version on HOOBS if you can't see it in the list.  Maybe ask HOOBS support?

**Comment by dgreif** [comment]
No problem! I haven't been super active on the project, so it's understandable that people are impatient when things are broken. 

Regarding the beta, did you turn on the `unbridgeCameras` setting? That will remove your current cameras and expose them as separate accessories that you can add to HomeKit.  Note, you will lose any associated settings and automations on the cameras

**Comment by databoy01** [comment]
@dgreif - I dont see any area to check that setting. Is it something I have to add in the configuration?  All the areas to add a check mark do not show anything labeled unbridgeCameras

**Comment by databoy01** [comment]
[
![](https://i.postimg.cc/0yWCwdGH/9620-FF3-B-4921-49-E7-A9-AC-49-BE96-E152-BC.jpg)
](url)

**Comment by dgreif** [comment]
@databoy01 you may have to add it to the config manually.  A new line with `"unbridgeCameras": true` should be all you need.  You may be on `beta.0` which didn't show the option, but I've added it in `beta.1` (not sure if HOOBS gives you this option for update yet as I released it this morning).

**Comment by owellsjr** [comment]
@dgreif I’ve upgrades to to 11.1.0 beta.0 and added the “unbridgeCameras”: true configuration. I noticed I had to add my cameras back to the Home app manually after that. I tried one and it made no difference. Snapshots still working. Live streaming does not. The error in the logs is the same. 

`https://github.com/dgreif/ring/tree/master/homeb`

**Comment by databoy01** [comment]
Didn’t work for me either… Still broken.

**Comment by aimbdd** [comment]
Hi, I have the sam issue on home-bridge, it broke all the cameras. terminal show no errors and acts like it started the stream.

**Comment by farhad-a** [comment]
> @databoy01 and @dgreif Based on some posts in the /hoobs sub in Reddit it would appear that removing and reinstalling the 11.0.7 plugin resolves the issue. We’ll see if that’s just temporary. But for the moment I’m able to live stream again.

Works after reinstall. All accessories have to be reconfigured.

**Comment by databoy01** [comment]
@farhad-a how did you get it to work?  I literally just started fully over. Formatted the SD card that runs my hoobs, redownloaded and flashed it using the etcher, updated the software after I restarted the hoobs as new.  After all updates, unplugged the unit and restarted it, then downloaded 11.0.7 and after linking it to my account, nothing shows, I don’t even see the cameras like I did with earlier releases. The HomeKit takes the scan in code and even there nothing on the home app. Even the “accessories” tab in the hoobs software, doesn’t show any devices. This is truly a mess. You’d think a fresh new start would fix it.  But nope. Are you sure you got it working?

**Comment by NickRivait** [comment]
Facebook group says Hoobs & DEV are in talks.

**Comment by dgreif** [comment]
That's correct.  @mkellsy from the HOOBS side is looking into the issue

**Comment by databoy01** [comment]
Hello Dusty @dgreif, Just out of curiosity, do you know how they are making out with a fix for this or even a possible timeframe for the fix?  Thanks again

**Comment by Noddley** [comment]
hi Yall I'm haveing the same issue but on home bridge I know there's still not a fix but is there any indication of a fix/patch soon because this started happing when i switched over from my PI to my server.

**Comment by aimbdd** [comment]
> hi Yall I'm haveing the same issue but on home bridge I know there's still not a fix but is there any indication of a fix/patch soon because this started happing when i switched over from my PI to my server.

Yeah, it’s not only a hoobs issue. Same with me here on home bridge.

**Comment by dgreif** [comment]
@aimbdd as far as I have heard, this is a HOOBS only issue.  You may be having some unrelated issues on homebridge. Would you mind opening a new issue and filling out the issue template?

**Comment by databoy01** [comment]
Mine works finally too…. Yay. Not sure what fixed it because nothing really changed and still no update on my side.

**Comment by NickRivait** [comment]
Mines not working still. 
![3348570C-1235-4C9E-BF13-D6CE2599F2A2](https://user-images.githubusercontent.com/75817378/184534567-ad8e12c4-3143-49df-84f3-90a24e9b91fa.jpeg)

**Comment by metalshark** [comment]
Am using HomeBridge on a Synology not HOOBS.

Issue started with 11.0.7 (although keep to use 11.1.0 due to unbridge mode being available for cameras.

Log of output when connecting:

```
[8/16/2022, 9:43:21 AM] [homebridge-ring] Preparing Live Stream for Front Door
[8/16/2022, 9:43:21 AM] [homebridge-ring] Stream Prepared for Front Door (0.625s)
[8/16/2022, 9:43:22 AM] [homebridge-ring] WebSocket connected for Front Door
[8/16/2022, 9:43:22 AM] [homebridge-ring] Activating stream for Front Door (0.761s)
[8/16/2022, 9:43:22 AM] [homebridge-ring] iceConnectionStateChange: completed
[8/16/2022, 9:43:22 AM] [homebridge-ring] connectionStateChange: connecting
[8/16/2022, 9:43:22 AM] [homebridge-ring] iceConnectionStateChange: new
[8/16/2022, 9:43:22 AM] [homebridge-ring] iceConnectionStateChange: checking
[8/16/2022, 9:43:22 AM] [homebridge-ring] Activating Session
[8/16/2022, 9:43:22 AM] [homebridge-ring] Streaming active for Front Door (1.501s)
[8/16/2022, 9:43:32 AM] [homebridge-ring] Return Audio (Front Door): Input #0, sdp, from 'pipe:':
  Metadata:
    title           : Talk
  Duration: N/A, bitrate: N/A

[8/16/2022, 9:43:32 AM] [homebridge-ring] Return Audio (Front Door):   Stream #0:0: Audio: opus, 48000 Hz, mono, s16
Stream mapping:
  Stream #0:0 -> #0:0 (opus (libopus) -> opus (libopus))

[8/16/2022, 9:43:32 AM] [homebridge-ring] From Ring (Front Door): Input #0, sdp, from 'pipe:':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Audio: opus, 48000 Hz, stereo, s16
Stream mapping:
  Stream #0:0 -> #0:0 (opus (libopus) -> opus (libopus))

[8/16/2022, 9:43:42 AM] [homebridge-ring] Return Audio (Front Door): pipe:: Connection timed out

[8/16/2022, 9:43:42 AM] [homebridge-ring] From Ring (Front Door): pipe:: Connection timed out

[8/16/2022, 9:43:42 AM] [homebridge-ring] Return Audio (Front Door): [libopus @ 0x55ecd7454740] No bit rate set. Defaulting to 96000 bps.

[8/16/2022, 9:43:42 AM] [homebridge-ring] Return Audio (Front Door): Output #0, rtp, to 'rtp://127.0.0.1:53685':
  Metadata:
    title           : Talk
    encoder         : Lavf59.16.100
  Stream #0:0: Audio: opus, 48000 Hz, stereo, s16, 96 kb/s
    Metadata:
      encoder         : Lavc59.18.100 libopus
size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

[8/16/2022, 9:43:42 AM] [homebridge-ring] From Ring (Front Door): Output #0, rtp, to 'rtp://127.0.0.1:57827?pkt_size=188':
  Metadata:
    encoder         : Lavf59.16.100
  Stream #0:0: Audio: opus, 24000 Hz, mono, s16, 24 kb/s
    Metadata:
      encoder         : Lavc59.18.100 libopus
size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

[8/16/2022, 9:43:42 AM] [homebridge-ring] connectionStateChange: closed
[8/16/2022, 9:43:42 AM] [homebridge-ring] From Ring (Front Door): stopped gracefully
[8/16/2022, 9:43:42 AM] [homebridge-ring] iceConnectionStateChange: closed
[8/16/2022, 9:43:42 AM] [homebridge-ring] Return Audio (Front Door): stopped gracefully
[8/16/2022, 9:43:50 AM] [homebridge-ring] Stopped Live Stream for Front Door
```

**Comment by dgreif** [comment]
127.0.0.1 is localhost, which is used for ffmpeg - this is normal. I think your issue is caused by failing WebRTC connections, which may be from the update to the `werift` dependency.  I'll get an update out as soon as a newer version of werift is available.

**Comment by metalshark** [comment]
Version 0.15.11 of werift came out 3 days ago if that's the version you were waiting for?

**Comment by dgreif** [comment]
@metalshark thanks for letting me know. Give 11.1.0 a try, which has the latest werift

**Comment by metalshark** [comment]
> @metalshark thanks for letting me know. Give 11.1.0 a try, which has the latest werift

Thank you trying, have updated but still snapshot only and no live video.

**Comment by NickRivait** [comment]
My Hoobs doesn't show a Ring update available. It is in Beta or released.

**Comment by metalshark** [comment]
It's released but unsure about HOOBS
![image](https://user-images.githubusercontent.com/146708/185798898-7d7df143-dbf5-41e6-99dd-510e870c1589.png)

**Comment by metalshark** [comment]
I've got full access to the file system on the Synology, can change/interrogate permissions and can monkey around with versions in the node_modules folder if there's anything you'd like diagnosis-wise or anything you like me to try.

**Comment by dgreif** [comment]
@NickRivait there are a lot of users on both. Homebridge is maintained by the same folks as hap (the underlying library for homebridge). HOOBS is built on top of these, and maintained by a separate group. If you aren't finding additional value in using HOOBS, homebridge with homebridge-config-ui-x is a really solid setup

**Comment by ab29316** [comment]
I have the same issue, however, reflashing my HOOBS has not fixed the live stream. I can see current thumbnails in the Apple Home app for my cameras, but when I click on a camera it goes to Not responding.

**Comment by dgreif** [comment]
Official solution from HOOBS is to uninstall/reinstall the Ring plugin if you are running into this issue. If you still have problems after that, please reach out to HOOBS support

**Comment by metalshark** [comment]
Worth re-opening issue #1004 then for those not using HOOBS?

**Comment by rocketis** [comment]
erased and started over many times with hoobs, two days ago switched home. Bridge has been working perfect ever since.

**Comment by rocketis** [comment]
> I have the same issue, however, reflashing my HOOBS has not fixed the live stream. I can see current thumbnails in the Apple Home app for my cameras, but when I click on a camera it goes to Not responding.

I am the same experience. I finally switched to Homebridge issues are gone streaming works fine.

**Comment by raiubreaksthings** [comment]
This issue is back. It is occurring with homebridge and hoobs. 

Happens in the most recent as of today as well as the beta version of the ring plugin. 

8/10/2023, 2:07:38 PMRing Bridge BetaRingPreparing Live Stream for Backyard
8/10/2023, 2:07:38 PMRing Bridge BetaRingStream Prepared for Backyard (0.208s)
8/10/2023, 2:07:38 PMRing Bridge BetaRingActivating stream for Backyard (0.264s)
8/10/2023, 2:07:38 PMRing Bridge BetaRingERRORRangeError: offset is out of bounds
8/10/2023, 2:07:38 PMRing Bridge BetaRingconnectionStateChange: closed
8/10/2023, 2:07:38 PMRing Bridge BetaRingiceConnectionStateChange: closed
8/10/2023, 2:07:41 PMRing Bridge BetaERROR[Ring Bridge Beta 1F1A@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Backyard' was slow to respond!
8/10/2023, 2:07:47 PMRing Bridge BetaERROR[Ring Bridge Beta 1F1A@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Backyard' didn't respond at all!. Please check that you properly call the callback!

**Comment by fgmnt** [comment]
Any update with this? Happening on 12.0.1
