### ISSUE TITLE
Please work on removing the fake motion sensors 🥹

### ISSUE THREAD

**Issue by MoTechnicalities** [dgreif/ring#1010]
# Bug Report

### Describe the Bug
 Please see issue #1001

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
@MoTechnicalities I work on this project in my free time, which is sparse. If you would like a change made more quickly, you are welcome to open a pull request and I will review it when I am able. Please do not open duplicate issues in hopes that it will get the work done more quickly.
