### ISSUE TITLE
Querying all motion events for a camera is limited to 100 events only

### ISSUE THREAD

**Issue by raleighlittles** [dgreif/ring#1011]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

When querying a list of motion events from a camera, only 100 are available, even if more events exist.

### To Reproduce
 - Create an `ApiClient`
 - Attempt to ...
 - See error

Query a list of events for a given camera. Only 100 events are returned, despite there being more available. Below is a code snippet that exercises this -- when ran, the code snippet prints that there are only 100 events for each camera.

```js
// Query all 'locations' for a ring account, and then get all cameras registered at each location
// Then, check each camera's events, and grab the URL associated with the video that was created for that event.
const locations = await ringApi.getLocations();

// Read in the configuration JSON file
let config = JSON.parse(fs.readFileSync("ring-config.json"))

for (var i = 0; i < locations.length; i++) {

  const cameraAtLocation = await locations[i].cameras;

  console.log(cameraAtLocation.length, " cameras found at current location");

  for (var j = 0; i < cameraAtLocation.length; j++) {

    const cameraName = cameraAtLocation[j].data.description;
    const cameraEvents = await cameraAtLocation[j].getEvents();

    console.log(cameraEvents.events.length, " events found for camera: ", cameraName);
```

### Expected behavior
 A clear and concise description of what you expected to happen.

ALL events will be returned, not just limited to 100.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

![image](https://user-images.githubusercontent.com/2137201/182056628-d79a8ade-6c5a-4b06-9981-4b0925492361.png)

### Additional context
 Add any other context about the problem here.

For context, I know that there are more than 100 events available because when I ran this script a month ago, it also printed that there were 100 events -- so either events are being deleted past 100, or the API isn't correctly querying all events correctly.

### Environment

 - OS: [e.g. Raspbian] Ubuntu 22.04 LTS x86_64
 - Node.js: [e.g. 12.14.1]  Now using node v16.16.0
 - NPM: [e.g 6.13.4]  npm v8.11.0
 - ring-client-api: [e.g 6.0.3]

**Comment by dgreif** [comment]
The 100 event limit is a default from the Ring api side.  You can override it by passing in options to this method, for example:

```ts
camera.getEvents({ limit: 200 })
```

From there, you can do pagination of results. I haven't tried this in a long time, but I think it's something like this:

```ts
camera.getEvents({ limit: 200, offset: 200 })
```

This would fetch 200 results, skipping over the most recent 200.  Given the infinite number of events that you could possibly be fetching, it's very standard for an API to use a pagination technique like this so that you don't requests a huge amount of data.

**Comment by raleighlittles** [comment]
Thanks for the clarification. I understand that this is probably a sane default of sorts, but IMHO it should be more clearly documented. @dgreif

**Comment by dgreif** [comment]
If you are using TypeScript, the types should at least give you some hints of what's available.  I hear you on the lack of docs though.  I don't have the API well documented as it's basically just a side-effect of what I needed to build for `homebridge-ring`.

**Comment by raleighlittles** [comment]
> The 100 event limit is a default from the Ring api side. You can override it by passing in options to this method, for example:
> 
> ```ts
> camera.getEvents({ limit: 200 })
> ```
> 
> From there, you can do pagination of results. I haven't tried this in a long time, but I think it's something like this:
> 
> ```ts
> camera.getEvents({ limit: 200, offset: 200 })
> ```
> 
> This would fetch 200 results, skipping over the most recent 200. Given the infinite number of events that you could possibly be fetching, it's very standard for an API to use a pagination technique like this so that you don't requests a huge amount of data.

@dgreif In this example, how do I (the caller) specifically know when I've reached the end of all available events? I would expect that, for example, if there were, say, 1000 events available, and I put in the request:

```
camera.getEvents({ limit: 100, offset: 950 })
```

I would receive only 50 events. However, this does _not_ seem to be the case. 
The API is always returning the amount of events I specify, until the offset reaches a number greater than the total number of events available.

**Comment by dgreif** [comment]
I'm honestly not sure 😄. This is a part of the Ring api I haven't spent much time with, and only set up basic calls for. Might require some investigation on your end to figure that bit out.
