### ISSUE TITLE
Motion Sensor and Notifications Not Working in Home App

### ISSUE THREAD

**Issue by larrysharon** [dgreif/ring#1015]
# Bug Report

### Describe the Bug
 Motion sensor on the Ring Elite Doorbell is not working, nor are the activity notifications for motion or the doorbell press. Both motion and notifications are working in the Ring app.

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 Upon detecting motion and/or pressing the doorbell, Home app should receive push notification.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Tried reinstalling the Ring plugin and resetting all home hubs.  It used to work before without any issues and just stopped recently.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

{
    "refreshToken": "XXX",
    "hideDoorbellSwitch": true,
    "platform": "Ring",
    "_bridge": {
        "username": "XXX",
        "port": 42430
    }
}

```

### Environment

 - OS: Ubuntu Focal Fossa
 - NPM: v16.16.0 
 - homebridge-ring: v11.0.7 
 - homebridge: 1.5

**Comment by dgreif** [comment]
This is a duplicate of #934. Please subscribe to that issue for updates
