### ISSUE TITLE
[Streaming]: Sound quality issue

### ISSUE THREAD

**Issue by pwnz0r69** [dgreif/ring#1019]
### Streaming Issue

Hello.
First of all, thank you for the dev of this homebridge plug in

All is working fine, but i have a very bad sound quality if i talk in my phone from the home app, the sound is very very bad on the ring doorbell. but i can hear very nice from my phone.
All is working good with the ring app.

What do you think ?

Thx

### Proposed Solution

.

### Environment

Homebridge

### What operating system are you on?

Linux

### Honesty Time

- [X] I swear this is worth your time!

**Comment by dgreif** [comment]
Thanks for reporting. This is a duplicate of #984, which I still have not found a root cause for.
