### ISSUE TITLE
Add Platform Block

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#102]
What does this button in the UI settings do?

**Comment by dgreif** [comment]
@adavison007 I assume that you are referring to the button in the settings popup for HOOBS/homebridge-config-ui-x:

![image](https://user-images.githubusercontent.com/3026298/62838946-e4d68d00-bc37-11e9-942d-08e1792c92a8.png)

If you click the button, it will add another Ring platform section to your homebridge config.  The second config would create a completely separate copy of the homebridge-ring plugin that could run in parallel with the first one.  This would be useful if you had multiple ring accounts, or if you had multiple locations and wanted to set some of the config options differently between locations.  For most users, this button can be ignored.

**Comment by adavison007** [comment]
@dgreif thanks for the explanation, much appreciated, I’ll use that when I’m rich and can afford a 2nd house :)
