### ISSUE TITLE
Not all Ring camera motion events are being received

### ISSUE THREAD

**Issue by jordanmerrick** [dgreif/ring#1025]
# Bug Report

### Describe the Bug
Not all motion events are being picked up by Homebridge for cameras. It's pretty inconsistent as sometimes it does work, but most of the time it does not. I have a Ring Doorbell 3 Plus and a mix of stick-up cams, indoor cams, and floodlight cams. _However_, motion detected by smart lights work fine—it's just cameras.

Ring is accurately sending motion alerts as I get the notification in the Ring app and can see the event history for cameras. But I most events are not appearing in the log and don't trigger activity notifications.

### To Reproduce
Trigger motion alerts for Ring cameras

### Expected behavior
Homebridge reports detection motion, e.g., 

```
[8/25/2022, 3:58:31 PM] [homebridge-ring] Front Door Detected Motion

```

### Screenshots/Logs

At time of writing, the last motion detection event for the doorbell was yesterday:

```
[8/25/2022, 3:58:31 PM] [homebridge-ring] Front Door Detected Motion
```

Ring reports several events today. 

![CleanShot 2022-08-26 at 17 34 00](https://user-images.githubusercontent.com/1397671/187007156-1bb7e08d-11dd-4f37-90d2-799afc2517d2.png)

No errors in the log, it's as though the event never made it to Homebridge. 
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
All cameras on Ring Edge. I've toggled Smart Alerts, motion alerts in the mobile app, and even reset one of the Ring cameras. Motion appears to work for a while if I reboot Homebridge, but eventually it stops receiving alerts from Ring.

### Homebridge Ring Config

Homebridge-ring v11.1.0

```
        {
            "refreshToken": "xxx",
            "unbridgeCameras": true,
            "hideLightGroups": true,
            "hideDoorbellSwitch": true,
            "hideCameraMotionSensor": false,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "avoidSnapshotBatteryDrain": false,
            "beamDurationSeconds": 9000,
            "debug": true,
            "_bridge": {
                "username": "",
                "port": 30813
            },
            "platform": "Ring"
        },
```

### Environment

 - OS: macOS Monterey 12.5
 - Node.js: 16.15.1
 - NPM: 8.12.1
 - homebridge-ring: 11.1.0
 - homebridge: 1.5.0

**Comment by dmkjr** [comment]
I've seen this across other Ring integrations as well.  I don't think it's specific to Homebridge.  I think it's Ring's API not sending the data.

**Comment by dgreif** [comment]
This is a duplicate of #934. Please subscribe to that issue for updates

**Comment by jordanmerrick** [comment]
I've been experiencing the same issue with dropped notifications with both Homebridge Ring and Scrypted. There was a post in the [Scrypted discord yesterday](https://discord.com/channels/882329362295316500/932852072024518726/1012745697977700482) about an update that uses a different implementation of push events that seems to be resolving this issue? 

I'm going to switch some cameras to Scrypted and see if it's any better. Hopefully this can help with the Homebridge plug-in.
