### ISSUE TITLE
v11.2.1 added battery indicators for Ring security system products, can these be toggled off?

### ISSUE THREAD

**Issue by eoddc5** [dgreif/ring#1029]
# Feature Request

### Description
updated to v11.2.1, battery indicator "lights" for ring security system (base station and keypad) just showed up - would rather make this an option in settings that can be hidden, as they are not required or necessary for me and they now always appear on the home main app page because theyre "lights"

### Describe the solution you'd like
make these togglable in settings , similar to other options

### Describe alternatives you've considered
no

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dgreif** [comment]
Just like every device in the plugin, you can hide these using the `hideDeviceIds` option. The id for each device is logged when homebridge starts. My default is to show _everything_ and let users hide the things they don't wan't/care about.
