### ISSUE TITLE
Seeing this again after it was fixed in the past. Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices..

### ISSUE THREAD

**Issue by onefish2** [dgreif/ring#1032]
Bug Report

Plugin version - 11.2.0 and 11.2.1

From Googling this, I saw that this was an issue in the past and it had been fixed. I have been seeing this frequently in the logs the past few days. It happens from a few minutes apart to 10 to 15 minutes apart or longer. Other than this error in the logs, everything works as expected.

Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...

**Comment by dgreif** [comment]
This indicates a failure to fetch from the Ring api, which is usually caused by a flaky network. If you aren't noticing any issues with the actual performance of the Ring plugin, you can safely ignore these

**Comment by zikronix** [comment]
im getting this same error and my network is fine, I do have 2fa setup on my ring account
