### ISSUE TITLE
Keypad and base station no longer hidden on homekit

### ISSUE THREAD

**Issue by brianjw** [dgreif/ring#1040]
# Bug Report

### Describe the Bug
 

A recent update removed the settings for hiding the Ring Alarm base station and keypad from homekit. Both are now showing as devices when they were previously hidden. 

### To Reproduce
N/A

### Expected behavior

The devices should be hidden and the settings should still be available to hide these devices.

**Comment by dgreif** [comment]
Just like every device in the plugin, you can hide these using the `hideDeviceIds` option. The id for each device is logged when homebridge starts. My default is to show _everything_ and let users hide the things they don't wan't/care about.

**Comment by jradwan** [comment]
Just a note, I had the same thing happen and I'm guessing it's due to the change of adding support for the keypad and base station brightness (they show up as lights now). I had to re-hide those devices.

**Comment by lion33319** [comment]
I get the problem that the lights of my alarm base station and the keypad keep turning off.
Even though I keep setting the brightness in the ring app, the next evening the lights are completely turned off. Is there an option in the plug-in menue to leave the lights turned on?

**Comment by dgreif** [comment]
@lion33319 they should not be turning off automatically. You may have an automation set up that is causing those to turn off
