### ISSUE TITLE
Ring StickUp Camera is split into multiple devices 

### ISSUE THREAD

**Issue by oilcan-productions** [dgreif/ring#1051]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...
When I add a Ring Stickup cam it shows up as 6 different accessories, all listed separately in the Homebridge UI
- Camera
- Microphone
- Battery
- Speaker/Siren
- Light
- Motion Sensor
- 
### To Reproduce
 - Add the plugin
 - login into Ring account
 - look at the Accessories screen

### Expected behavior
 A clear and concise description of what you expected to happen.
The camera to show up as one "Camera" device with 5 features
- Microphone
- Siren/Switch
- Motion Sensor
- IR light
- Battery

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.
![Homebridge bug](https://user-images.githubusercontent.com/77457397/190028290-a088b0d0-f903-4c27-9694-979d0a942431.png)
### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

        {
            "refreshToken": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "platform": "Ring",
            "alarmOnEntryDelay": true
        },

```

### Environment

 - OS: [e.g. Raspbian] Raspian
 - Node.js: [e.g. 12.14.1]  v16.17
 - NPM: [e.g 6.13.4]  8.15
 - homebridge-ring: [e.g 6.0.3] homebridge-ring v11.2.1
 - homebridge: [e.g. 0.4.50 or N/A] 1.5.0
 - hoobs: [e.g. 0.4.50 or N/A] N/A

**Comment by dgreif** [comment]
Do they show as a single device in the Home app? I think what you are experiencing is simply the default behavior of the homebridge-ui plugin

**Comment by oilcan-productions** [comment]
The camera, speaker and Battery are grouped in the Home app. That is correct. Microphone, Motion Sensor and IR light switch do not show up in the Home app but show up in the Homemanager app.

**Comment by dgreif** [comment]
In that case it sounds like everything is behaving as expected. If you would like to see them grouped in the homebridge-ui, I suggest you open a feature request on https://github.com/oznu/homebridge-config-ui-x
