### ISSUE TITLE
Ring Intercom + supported?

### ISSUE THREAD

**Issue by Spy-1** [dgreif/ring#1062]
will the new upcoming Ring Intercom + be supported by the plugin?

**Comment by dgreif** [comment]
This is the first I've heard of the intercom. Found this [video about it](https://www.youtube.com/watch?v=ru0H0xr8-0M). My guess is that it will _not_ work with the plugin by default, and this is a piece of hardware that I will personally have no use for and won't be able to test out. I'm also not sure that it will work well with HomeKit as there is no video stream - I think HomeKit cameras _require_ video. Happy to take a PR if someone gets it working, but I don't think I will be able to tackle this one.

**Comment by Dexwell** [comment]
> This is the first I've heard of the intercom. Found this [video about it](https://www.youtube.com/watch?v=ru0H0xr8-0M). My guess is that it will _not_ work with the plugin by default, and this is a piece of hardware that I will personally have no use for and won't be able to test out. I'm also not sure that it will work well with HomeKit as there is no video stream - I think HomeKit cameras _require_ video. Happy to take a PR if someone gets it working, but I don't think I will be able to tackle this one.

@dgreif I can think of two ways the Intercom could be supported by this plugin.

1. Expose a HomeKit `Door` or `Lock` accessory (according to user preference) which allows you to open your door/gate via the Ring Intercom using the Home app or Siri.
2. Allow two-way talk in the Home app by routing audio and simply setting the video stream to black or some other placeholder image.

Would be fantastic!
