### ISSUE TITLE
Is it possible to avoid the keypad and base brightness bulb to show on HomeKit?

### ISSUE THREAD

**Issue by rafacampoamor** [dgreif/ring#1069]
# Feature Request

### Description
When I go to sleep, I usually tell Siri to turn off all the lights. As the brightness of the base and the keypad are show as bulbs, Siri turns them off as well. I've tried to manage it via Home app by hiding these bulbs but Siri keeps turning them off. Is there any way to avoid them to show on HomeKit?

### Describe the solution you'd like
A posibilite to hide the brightness for base and keypad from HomeKit

### Describe alternatives you've considered
I've tried to hide those bulbs on Home app, but didn't work. In case there's no possibility for this improvement, I've thought of creating a new scene on Home app and a Shortcut for Siri for when I'm going to sleep.

**Comment by cantchooseaname8** [comment]
If you look at the logs for the ring Homebridge plugin, you’ll see the base station and keypad listed. There is a device ID listed by it. You can exclude specific devices with that ID and they won’t show up in HomeKit at all. I had the same the problem and this solved it for me. Now those lights are completely excluded and not brought into HomeKit.

**Comment by dgreif** [comment]
See https://github.com/dgreif/ring/issues/1040#issuecomment-1233514779
