### ISSUE TITLE
Add ability to hide brightness (light accessory) for Ring Alarm base station

### ISSUE THREAD

**Issue by michaelyork** [dgreif/ring#1075]
# Feature Request

### Description
Add ability to hide brightness (light accessory) for Ring Alarm base station. Today, there is no config option to allow for this.

### Describe the solution you'd like
Config option that allows users to hide the brightness (light) accessory for alarm base stations. Thank you!

### Describe alternatives you've considered
N/A

### Device data
N/A

**Comment by dgreif** [comment]
It's possible to hide them, see https://github.com/dgreif/ring/issues/1040#issuecomment-1233514779

**Comment by Rubenfer** [comment]
Hi @dgreif, it's possible to hide the light but not the accessory itself? I use it to check battery but now it's showing like a bulb.

**Comment by dgreif** [comment]
You would have to hide an individual "Service" from the accessory, which is not supported in the config today. That would be something that might be adopted at the homebridge level, but I don't plan to add it to the plugin as it just makes things way more complicated.
