### ISSUE TITLE
More Hide Needed

### ISSUE THREAD

**Issue by qoodanny** [dgreif/ring#1077]
# Feature Request

### Description
 A clear and concise description of the problem or missing capability...
Hide Base Station, Key Pad Light and Volume
Hide Accessories Battery
### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dgreif** [comment]
It's possible to hide them, see https://github.com/dgreif/ring/issues/1040#issuecomment-1233514779
