### ISSUE TITLE
JSON Config Issue With Ring and Denon Receiver

### ISSUE THREAD

**Issue by w00dy1981** [dgreif/ring#108]
Hi 

i am very new to getting homebridge to work via Mac for homekit compatibility of non homekit devices

Currently i have a config file that i found to control my Denon sound volume and i just bought a ring floodlight which id also like to add

i have played around in atom copying and pasting things nd checking in jsonlint which tells me is a valid json but when i then save it and try an run homebridge from terminal its throws a heap of errors and doesnt load the homebridge qr code

here is my json config that jsonlint says is valid, the email and password of my ring are mocked up for this example

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:51",
		"port": 51826,
		"pin": "031-45-154"
	},
	"description": "This is an example configuration file for homebridge denon plugin",
	"hint": "Always paste into jsonlint.com validation page before starting your homebridge, saves a lot of frustration",
	"accessories": [{
		"accessory": "marantz-volume",
		"name": "Stereo Volume",
		"host": "10.182.207.179:8080"
	}, {
		"platforms": [{
			"platform": "Ring",
			"email": "sfdhsfg",
			"password": "sfghsfgh"
		}]
	}]

}

**Comment by dgreif** [comment]
you have the `platforms` array _inside_ the `accessories` array.  It should look like this instead:

```json
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:51",
		"port": 51826,
		"pin": "031-45-154"
	},
	"description": "This is an example configuration file for homebridge denon plugin",
	"hint": "Always paste into jsonlint.com validation page before starting your homebridge, saves a lot of frustration",
	"accessories": [{
		"accessory": "marantz-volume",
		"name": "Stereo Volume",
		"host": "10.182.207.179:8080"
	}],
	"platforms": [{
		"platform": "Ring",
		"email": "sfdhsfg",
		"password": "sfghsfgh"
	}]
}
```

**Comment by dgreif** [comment]
I'm assuming that fixed it for you.  If you have continued issues with your `config.json`, I suggest you post on reddit `r/homebridge` or on homebridge slack
