### ISSUE TITLE
Panic Buttons Label

### ISSUE THREAD

**Issue by DerKoller-eu** [dgreif/ring#1086]
# Bug Report

### Describe the Bug
 Panic Buttons are shown as Panic Buttons in iOS 16 Home App, not labeled as burglar or fire Button.

### To Reproduce
 - Home App in iOS 16 or 16.1

### Expected behavior
 Buttons should be labeled as Burglar or Fire Button (as in Homebridge Devices)

### Screenshots/Logs

![F36A3BB8-1506-42AE-B128-5533C9794317](https://user-images.githubusercontent.com/27485112/199295053-a45bf2a0-5b0c-498b-a76f-41c757ef5836.png)

### Additional context
 -

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

            "hideAlarmSirenSwitch": true,
            "showPanicButtons": true,
            "platform": "Ring"

```

### Environment

 - OS: [Raspbian 11]
 - Node.js: [18.2.0] 
 - NPM: [8.19.2] 
 - homebridge-ring: [11.3.1]
 - homebridge: [1.5.1]
 - hoobs: [not used]

**Comment by dgreif** [comment]
I'm able to recreate this. It seems like this is a bug in iOS 16. The services (switches) are being labeled correctly by the code, but HomeKit is ignoring the individual labels and instead using the general accessory name. I'm not sure there is anything I can do to fix this, other than exposing two separate switches as individual accessories. I'd prefer not to do this as it would break any automations that users already have set up with these switches. For now, I think the best course is to wait and see if Apple fixes this in an update to iOS

**Comment by dgreif** [comment]
I don't think there is anything else I can do to fix this currently
