### ISSUE TITLE
Doorbell event and snapshot external URL hooks

### ISSUE THREAD

**Issue by piecedoorball** [dgreif/ring#1089]
# Feature Request

### Description
Option to have external URL hooks to notify on doorbell event and upload prefetch image using provided URL

### Describe the solution you'd like
3rd party integrations would benefit by providing end-point and getting notified on sign event and upload of an image so it can be used outside of HomeKit ecosystem.

**Comment by dgreif** [comment]
This sounds like a small package that someone else could easily build on top of the `ring-client-api` package, but isn't something I'm interested in adding to the core package.
