### ISSUE TITLE
Unable to Authenticate with Ring Servers

### ISSUE THREAD

**Issue by jianyu-li** [dgreif/ring#109]
Hey @dgreif , had a new error pop up today. Sorry for the screenshot,let me know if you need me to copy and paste the logs. 

![5C4EA595-7A28-4412-8B7F-E58F46FE5C94](https://user-images.githubusercontent.com/52750081/63403542-88404400-c394-11e9-9497-eecd48c8325b.jpeg)

**Comment by jianyu-li** [comment]
I switched back to my email and password and that seemed to fix it. Do the refresh tokens expire over time?

**Comment by dgreif** [comment]
@jianyu-li I’m glad you got it working. I haven’t had a refresh token expire yet, but it is entirely possible that they do. You should be able to generate another one and switch back to that instead of using email and password

**Comment by jianyu-li** [comment]
Thank you. I’ll report back and let you know if I can successfully generate a new one

**Comment by ifeign** [comment]
I think I'm having the same issue because I too have been using the 2fa token.. suddenly I can't connect to my cameras while I'm out of town. My house sitter kindly restarted my Apple TV and Raspberry Pi but no luck. I'll investigate once I return home.

**Comment by benfysh** [comment]
I had the same issue and can confirm that it was resolved for me by generating a new token. It seems that it expired after around three weeks for me at least.

**Comment by EarthRise626** [comment]
I had the same issue yesterday as well. Generating a new refresh token solved the issue for me.

**Comment by ifeign** [comment]
I believe this is happening to me, I'm out of town and all of a sudden this plugin stopped working. The official Ring app works fine. Will have to investigate when I get home.

**Comment by EarthRise626** [comment]
My refresh token has apparently already expired since generating a new one last evening. Is anyone else in this thread encountering that issue?

**Comment by dgreif** [comment]
My `refreshToken` expired yesterday as well.  Based on when we all had a conversation in #74, I'd say the refresh tokens have a life of ~25 days.  The best solution I can think of is having the Ring plugin actually overwrite the refresh token in the homebridge config.json file every time we get a new one.  That way you would always have an unexpired refresh token on hand.  The only time you would need to get a new one by hand is if you left homebridge _off_ for 25+ days.  I think this should be sufficient for the normal homebridge use-case.  Will get an update out when I am done with audio 😧

**Comment by jianyu-li** [comment]
You’re awesome @dgreif! You have the best plugin in town. Thanks for all your hard work

**Comment by dgreif** [comment]
v`5.6.1` will put a new refresh token in your homebridge `config.json` every time your auth credentials expire (about every hour I think).  Let's see how it's doing in 30 days 😂
