### ISSUE TITLE
Ring plug in states site unavailable for past 3 days

### ISSUE THREAD

**Issue by GOTDNRV** [dgreif/ring#1090]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...
Ring states site unavailable in log
### To Reproduce
 - Create an `ApiClient`
 - Attempt to ... install plugin
 - See error plug in will give error message site unavaliable

### Expected behavior
 A clear and concise description of what you expected to happen.
When installing site should request password

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.
Removed app an attempted to reinstall prior to coping log 
### Additional context
 Add any other context about the problem here.

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - ring-client-api: [e.g 6.0.3]

**Comment by smockle** [comment]
@GOTDNRV Have you replaced your refresh token by following the steps in https://github.com/dgreif/ring/wiki/Refresh-Tokens?

**Comment by dgreif** [comment]
Closing due to lack of response
