### ISSUE TITLE
Ring Chime Snooze switch does not set the chime to snooze

### ISSUE THREAD

**Issue by calebawilson** [dgreif/ring#1093]
# Bug Report

### Describe the Bug
Ring Chime Snooze switch does not set the chime to snooze

### To Reproduce
Refreshed Token
Restarted Homebridge
See logs that give no error but chime still operates

### Expected behavior
I have an eve button to trigger the snooze switch on home app. This works perfectly and Homebridge logs show the switch turning on with no errors, but the chime still operates. In the Ring app it does not show the chime snoozed.

### Screenshots/Logs
Switch log
<img width="629" alt="Screen Shot 2022-11-09 at 12 40 47 PM" src="https://user-images.githubusercontent.com/5022088/200903540-8d9ed51a-ae71-462f-b93e-8b24c09c565a.png">

separate start up error
<img width="1629" alt="Screen Shot 2022-11-09 at 12 39 45 PM" src="https://user-images.githubusercontent.com/5022088/200906200-73361842-fdb7-4391-9df8-ab99f7b29c81.png">

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
        {
            "refreshToken": " ",
            "locationIds": [
                " "
            ],
            "platform": "Ring"
        },

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment
<!-- ✍️edit: -->
 - OS: Raspbian GNU/Linux Bullseye (11)
 - Node.js: v18.12.0
 - NPM: 8.19.2
 - homebridge-ring: homebridge-ring v11.3.1 
 - homebridge: v1.5.1
 - hoobs: N/A

**Comment by dgreif** [comment]
I just tested this out and everything seems to be working as expected.


In the Ring logs, you should see something like `Chime snoozed for 24 hours`
In the Ring app, go to your chime, then chime snooze and you should see a countdown of how much longer the chime is snoozed

![image](https://user-images.githubusercontent.com/3026298/202861557-ad4d5391-19a4-474d-9d8b-015184bd8d28.png)

If your eve button is still not working, try triggering the snooze directly from the switch exposed by homebridge-ring (without using an automation). Does that make a difference?

**Comment by calebawilson** [comment]
I tried triggering the snooze switch directly in homebridge but still nothing.

I started redoing the setup piece by piece. What seemed to work was just removing the chime from everything reseting and reinstalling it. Once in home bridge again it completely worked. Sorry to bother you with this seems to be a Ring communication issue.

**Comment by dgreif** [comment]
Glad it's working! Thanks for jumping through all those hoops to get it figured out
