### ISSUE TITLE
Motion trigger not changing alarm state

### ISSUE THREAD

**Issue by solarbeat** [dgreif/ring#1094]
# Bug Report

### Describe the Bug
Ring motion detector does not trigger disarm of alarm system.

### To Reproduce
- Set automation where when motion is detected in the Ring motion sensor, the alarm is disarmed.
- Set Ring alarm system to armed
- Trigger motion sensor
- Alarm state should change to "Disarmed", but does not

### Expected behavior
Motion trigger should disarm alarm.

### Screenshots/Logs
Nothing is shown in the logs, no errors.

### Additional context
Other triggers work (geolocation, etc.) for changing alarm state, but not motion. Perhaps per #755, the motion is triggering the alarm then immediately disarming, but it does not show anything happening. Motion sensor is working/registering, and works to trigger other automations, like lights.

### Homebridge Ring Config
{
    "refreshToken": xx",
    "hideDoorbellSwitch": true,
    "hideCameraSirenSwitch": false,
    "hideAlarmSirenSwitch": true,
    "hideDeviceIds": [
        "xx",
        "xx"
    ],
    "platform": "Ring"
}

### Environment
 - OS: Raspbian GNU/Linux Bullseye (11)
 - Node.js: v18.12.0
 - homebridge-ring: homebridge-ring v11.3.1
 - homebridge: 1.5.1
 - hoobs: N/A

**Comment by dgreif** [comment]
I tested this with my Ring alarm and am able to successfully disarm the alarm using a motion sensor on the same system. When you arm the alarm, is the motion sensor in question set to trigger the alarm, or is it bypassed for the alarm mode you are using? If it is active and triggering the alarm, then it's possible things are getting into some sort of race condition. Mine was bypassed, so you might give that a try if you don't have it set that way already.

**Comment by solarbeat** [comment]
The motion sensor is bypassed, so it's not triggering the alarm. However, it just started working as expected again - no changes on my side, at all. No idea what it was then. Sorry for the wild goose chase.

**Comment by dgreif** [comment]
No problem, glad it's working!!
