### ISSUE TITLE
Use of Ring Partners Portal

### ISSUE THREAD

**Issue by steets250** [dgreif/ring#110]
I was wondering if you have considered applying for the Ring Partners program. It's accessible at [https://ring.com/partners](https://ring.com/partners). I don't know if they (Ring) would approve this project, but the site shows the potential ability to access APIs, webhooks and unique keys.

**Comment by dgreif** [comment]
@steets250 thanks for the recommendation!  I have already tried applying through the website and emailing the partners program, but have not received any response.  I emailed the Ring CEO/Founder asking for access to documentation, and his response was that its just not ready for outside visibility yet.  He said the partners program is extremely selective currently, so he was not optimistic that I would be given access.  At this point I think the community has already reverse engineered all endpoints that matter, so I don't see a huge need to gain additional documentation.  It would be nice to validate that we aren't doing anything stupid though 😄

**Comment by jamesg311** [comment]
@dgreif I'm curious if when you reached out to Jamie (CEO of Ring) did you give any indication that this is what you were working on? I'm wondering if they know of this plugin and they are purposefully letting it exist or just don't know about it and there is risk to have it shut down.

**Comment by dgreif** [comment]
@jamesg311 I did point him to the project and his response was "thanks for building so much cool stuff!".  I took that as a good sign that they wouldn't try to shut us down 😂.  In my mind, any project that encourages consumers to buy more Ring hardware should be a win from their perspective

**Comment by jamesg311** [comment]
That's super comforting to hear!
