### ISSUE TITLE
Add Ring Spotlight Cam Pro type to device list

### ISSUE THREAD

**Issue by alvinchen1** [dgreif/ring#1103]
# Feature Request

### Description
 Add support for newly released and shipping Spotlight Cam Pro type. https://ring.com/products/spotlight-cam-pro-battery
Camera showing up as "stickup_cam_longfin"
Also Spotlight Cam Plus also just released and shipping.  Didn't get one of those, so can't say what its name is showing up as.

### Describe the solution you'd like
 I am using the ring-client-api via https://github.com/tsightler/ring-mqtt and everything mostly appears to be working, except the camera model is "Unknown Model" and the battery is like the OG Spotlight Cam where there are two battery compartments.  Right now, I have two batteries in it, one at 100% and one at 29% (according to the Ring App), but the battery for the whole camera via the API is showing as 29% vs aggregating the two values to be 65%(?).  

### Describe alternatives you've considered
 No workarounds or alternatives needed right now, everything is basically working, just trying to submit a new model number for possible inclusion into the API.

**Comment by tsightler** [comment]
> ...and the battery is like the OG Spotlight Cam where there are two battery compartments. Right now, I have two batteries in it, one at 100% and one at 29% (according to the Ring App), but the battery for the whole camera via the API is showing as 29% vs aggregating the two values to be 65%(?).

This is really a ring-mqtt issue.  Right now ring-mqtt just reports whatever value is returned by the device health battery_percentage property.  As I don't even own a battery powered Ring camera, and I don't have much time to maintain ring-mqtt these days, it's just not something I've been able to take the time to work on a better solution for cameras with dual batteries.

**Comment by alvinchen1** [comment]
> > ...and the battery is like the OG Spotlight Cam where there are two battery compartments. Right now, I have two batteries in it, one at 100% and one at 29% (according to the Ring App), but the battery for the whole camera via the API is showing as 29% vs aggregating the two values to be 65%(?).
> 
> This is really a ring-mqtt issue. Right now ring-mqtt just reports whatever value is returned by the device health battery_percentage property. As I don't even own a battery powered Ring camera, and I don't have much time to maintain ring-mqtt these days, it's just not something I've been able to take the time to work on a better solution for cameras with dual batteries.

Interesting, because my old Spotlight camera had two batteries, and at some point I did notice that it went from 200% battery life to 100% so I assumed that the math got fixed!

**Comment by tsightler** [comment]
> > > ...and the battery is like the OG Spotlight Cam where there are two battery compartments. Right now, I have two batteries in it, one at 100% and one at 29% (according to the Ring App), but the battery for the whole camera via the API is showing as 29% vs aggregating the two values to be 65%(?).
> > 
> > 
> > This is really a ring-mqtt issue. Right now ring-mqtt just reports whatever value is returned by the device health battery_percentage property. As I don't even own a battery powered Ring camera, and I don't have much time to maintain ring-mqtt these days, it's just not something I've been able to take the time to work on a better solution for cameras with dual batteries.
> 
> Interesting, because my old Spotlight camera had two batteries, and at some point I did notice that it went from 200% battery life to 100% so I assumed that the math got fixed!

Probably at some point you switched from native HA integration to ring-mqtt as that is how it behaves.

**Comment by alvinchen1** [comment]
> > Interesting, because my old Spotlight camera had two batteries, and at some point I did notice that it went from 200% battery life to 100% so I assumed that the math got fixed!
> 
> Probably at some point you switched from native HA integration to ring-mqtt as that is how it behaves.

Haha, no, I've been a RING-MQTT from day one!  :)  No big deal, once we got this model in, I'll take a look at my battery stats trends and your code and see if I can figure out a good way we can work this out that make sense.  I think the camera will drain battery 1 then drain battery 2, but instead of making two battery entities, I think it might make sense to just average it, i.e. battery 1 = 50, battery 2 = 100, then battery HASS entity = 75.
