### ISSUE TITLE
Adding a camera

### ISSUE THREAD

**Issue by HOMESEERDUDE** [dgreif/ring#1112]
# Bug Report

I have been using my ring doorbell without an issue.  However, I added a 2nd camera and it work on my apple tv but doesnt show up in homekit on my ipad.  is there something i need to do?

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
You will need to reboot your homebridge server and then add the new camera to the Home app using the code in your homebridge logs

**Comment by HOMESEERDUDE** [comment]
Thank you for getting back to me. I use the main homebridge code or is it a
different code?

**Comment by HOMESEERDUDE** [comment]
Does this need to be on?

**Comment by dgreif** [comment]
It should be the same as your main homebridge code

**Comment by HOMESEERDUDE** [comment]
It wouldn't accept the code but it popped in layer last night. However,  it
doesn't pop up on my apple tv when it detects motion. I can call it up
manually and I can see the camera without a problem. Is there a setting in
hombridge or on the ring app?

**Comment by dgreif** [comment]
I think it's a setting on the Apple TV

**Comment by dgreif** [comment]
@HOMESEERDUDE were you able to get this working?

**Comment by HOMESEERDUDE** [comment]
I'm sorry, works great. I forgot to press send and it went to my draft
folder.

**Comment by HOMESEERDUDE** [comment]
Do you know how and where to enter this coding in hombridge for my kevo
lock?

**Comment by dgreif** [comment]
Is there Kēvo lock exposed via Ring? Or is it a separate integration?

**Comment by HOMESEERDUDE** [comment]
Kevo and ring don't work together anymore. I would love to use homebridge
and thought you might know how to do it

**Comment by dgreif** [comment]
You could check if Kevo has a separate homebridge plugin or direct HomeKit support. It's not something I have experience with though, sorry

**Comment by HOMESEERDUDE** [comment]
No problem. I was hoping you might know where to enter the script. I have
no idea. Your plugin was simple.
