### ISSUE TITLE
Motion not Triggering from Spotlight Cam in Home app

### ISSUE THREAD

**Issue by jackklink** [dgreif/ring#1113]
# Bug Report

### Describe the Bug
Recently, the motion trigger for my Spotlight Cam has stopped firing when motion is detected by the camera. The Ring app detects motion, but it is not passed to the HomeKit motion trigger. This has been going on for a month or so now. I've tried a few different things to reset/remedy this issue with no luck. The camera streams just find to HomeKit.

### To Reproduce
 - Setup a Spotlight Cam with Homebridge
 - Create motion in front of the camera
 - Monitor the HomeKit Motion Trigger for the camera and see that it does not activate-- ever.

### Expected behavior
Obviously, the motion trigger should be activating. It used to work just fine until a month or so ago. I have been using the motion trigger for a HomeKit automation for over a year and it only recently stopped working.

### BONUS BUG
Possibly related, I am also no longer able to get Doorbell notifications and HomePod announcements to trigger from my Ring Doorbell despite it all being turned on and the camera streaming just fine to HomeKit.

### Screenshots/Logs
A screen recording is available here:
https://www.dropbox.com/s/5r73iukdwr0ijxq/Ring%20Homebridge%20Bug.mov

### Homebridge Ring Config
```
{
            "refreshToken": "xxx",
            "unbridgeCameras": true,
            "hideCameraLight": true,
            "hideCameraSirenSwitch": true,
            "hideAlarmSirenSwitch": true,
            "platform": "Ring"
},
```

### Environment
 - OS: Raspbian GNU/Linux Buster (10)
 - Node.js: 16.14.0
 - NPM: 8.3.1
 - homebridge-ring: 11.6.0
 - homebridge: 1.5.1
 - hoobs: N/A

**Comment by dgreif** [comment]
Can you try 11.7.0 and see if this is still an issue?

**Comment by MoTechnicalities** [comment]
I'm now on: **homebridge-ring v11.7.1**

Still **no snapshot updates** for any of my 7 Ring cameras.
My other camera on **homebridge-camera-ffmpeg v3.1.4** updates regularly every 10 seconds.

**Comment by dgreif** [comment]
@MoTechnicalities you already opened https://github.com/dgreif/ring/issues/1124 regarding your snapshot issues. Please do not drop redundant requests on other issues. Putting the same thing multiple places will not get a fix out faster, it just makes the conversation much harder to track.

@jackklink I haven't heard back from you so I'm going to go ahead and close this issue

**Comment by jackklink** [comment]
> @jackklink I haven't heard back from you so I'm going to go ahead and close this issue

Hey sorry! I've been out of town for the holidays so I haven't been able to test to see if the issue is resolved. I will update here when I can! Thanks

**Comment by jackklink** [comment]
Ok so I've finally had a chance to do some testing and troubleshooting and I can confirm this issue is still occurring in v11.7.1

I've just finished trying starting fresh. I removed all my Ring accessories from HomeKit and Homebridge and added them back in fresh. The issue still exists...

- Doorbell does not ring on HomePods, iOS devices, or Apple TV
- Motion Sensors do not change state for either doorbell cam or spotlight cam

Thanks for any help you can provide.

**Comment by jackklink** [comment]
@dgreif Hey! Any updates on this? Not trying to rush. Just checking in. Thanks for all you do.

**Comment by dgreif** [comment]
@jackklink sorry, no updates yet. Haven't had much time to work on the plugin recently. Thanks for your patience!

**Comment by jackklink** [comment]
Just updated to v11.7.3 and still no ringing on HomePods or motion sensor triggers.

**Comment by dgreif** [comment]
@jackklink would you mind providing logs from homebridge around the time when you are triggering a doorbell ring and/or motion?

**Comment by jackklink** [comment]
I turned on Debug logs and rang the doorbell twice. Nothing showed in the Homebridge logs at all.

Here's the Ring related logs during boot of Homebridge...

`[4/20/2023, 11:15:15 AM] Loaded plugin: homebridge-ring@11.7.5
[4/20/2023, 11:15:15 AM] Registering platform 'homebridge-ring.Ring'
[4/20/2023, 11:15:18 AM] [Ring] Initializing Ring platform...
[4/20/2023, 11:15:19 AM] [Ring] Configuring cached accessory a1c301a9-4e78-4e65-9bbf-ea8b3bd64d23 Chime
[4/20/2023, 11:15:19 AM] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge 35ED) is running on port 51022.
[4/20/2023, 11:15:20 AM] [Ring] Found the following locations:
[4/20/2023, 11:15:20 AM] [Ring]   locationId: 4fc886a3-9113-4ddb-bab6-bebeeb03e43d - Los Angeles
[4/20/2023, 11:15:21 AM] [Ring] Location Mode: {"mode":"unset","lastUpdateTimeMS":1681943996883,"securityStatus":{},"readOnly":true,"notYetParticipatingInMode":[],"responseTimestamp":1682014521000}
[4/20/2023, 11:15:21 AM] [Ring] Configuring 1 cameras and 2 devices for location "Los Angeles" - locationId: 4fc886a3-9113-4ddb-bab6-bebeeb03e43d
[4/20/2023, 11:15:21 AM] [Ring] Configured camera c3bc3f83-7796-4414-925b-f1568bf4ed39 doorbell_scallop Front Door
[4/20/2023, 11:15:21 AM] Front Door 112B is running on port 33077.
[4/20/2023, 11:15:21 AM] Please add [Front Door 112B] manually in Home app. Setup Code: 820-73-159`

**Comment by jackklink** [comment]
My config:
`{
            "refreshToken": "******",
            "unbridgeCameras": true,
            "hideCameraLight": true,
            "hideCameraMotionSensor": true,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "debug": true,
            "platform": "Ring"
},`

**Comment by dgreif** [comment]
@jackklink thanks for your patience, and sorry it's taken me so long to get back to you on this. With some other recent notification issue, I think we have a good set of steps to fix the problems you are facing. Please follow [this troubleshooting guide](https://github.com/dgreif/ring/wiki/Notification-Troubleshooting) and let me know if that helps

**Comment by jackklink** [comment]
@dgreif Perfect! Thanks so much. This fixed it. I should've thought to try that.
