### ISSUE TITLE
Second Ring Video Doorbell not responding in Homekit when off WiFi Network

### ISSUE THREAD

**Issue by efloyd** [dgreif/ring#112]
First of all, thank you SO much for this plugin. I love it, and I think it works great!

I have 2 Ring Video Doorbell cameras version 2, with up-to-date firmware. 

One cam works great in Homebridge when my iPhone is both on and off the wifi network. However, the other camera only works when my phone is on the same wifi network. I receive the status message "Front Door Not Responding" in Home when I'm away, and when I try to view the cam, it tries for a few seconds, but then I receive "Camera Not Responding".

There's nothing about the settings, IP address or port forwarding that I can find that could be causing this. I set them both up exactly the same.

Here's what I've done thus far for troubleshooting:
1. Restarted the cam, my Raspberri Pi running Homebridge, my router and my 2 Apple TVs and 1 iPad that are serving as homekit hubs
2. Verified that I'm running latest version of the plugin
4. Removed the cam and added it back
5. Found the cam's AccessoryInfo.${uniqueId}.json file in the ~/.homebridge/persist directory, deleted it, restarted Homebridge and re-added the cam

Any help would be appreciated. Thanks!

**Comment by dgreif** [comment]
See #91.  Thanks for the details of what you have tried so far! This is definitely an annoying issue, and I faced it myself a few weeks ago.  In the end mine just started working again without doing anything special.  You can read through that other issue and try some of the suggestions there, but ultimately this is a bug with HomeKit, not with the ring plugin.  Wish I could help more, but this one is out of my hands.  Let me know if you find something specific that works!
