### ISSUE TITLE
Keypad and Ring Alarm Pro "light" hiding

### ISSUE THREAD

**Issue by Ben-Diehlci** [dgreif/ring#1123]
# Feature Request
Keypad and Ring Alarm Pro "light" hiding

### Description
I was wondering if it might be possible to hide the Ring Keypad lights and Ring Alarm Pro light from Apple Home kit. 

### Describe the solution you'd like
Just a check box with the other hide options

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by smockle** [comment]
You can use [`hideDeviceIds`](https://github.com/dgreif/ring/tree/main/packages/homebridge-ring#optional-parameters) to hide those lights. The device identifiers are logged when you start homebridge-ring.
