### ISSUE TITLE
Intercom Doorbell Switch

### ISSUE THREAD

**Issue by KoopaSenior** [dgreif/ring#1130]
# Feature Request

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dgreif** [comment]
Sorry, but there are no details in the body of your issue. You may want to check out #1083 for more info on what is supported for the Ring Intercom

**Comment by KoopaSenior** [comment]
There are comments - exactly where they should be according to the comment instructions. But tbh, I wondered while filling out the report why I shpuld place my idea inside a "comment"-section.

**Comment by Ju17091** [comment]
@KoopaSenior In the eve app, double or long presses can also be stored for automations.
These then also appear in the Home App

**Comment by dgreif** [comment]
The intercom does not actually detect double/long press, so there is no way to send those events to HomeKit for different automations. This is controlled by Ring, so unfortunately not something we can add in the plugin.
