### ISSUE TITLE
Battery status not updated

### ISSUE THREAD

**Issue by isibizi** [dgreif/ring#1139]
Hello,

when i change my battery from the intercom, i must restart the container to have an battery status update. I have waited some hours without change, only an restart helps.

**Comment by tsightler** [comment]
Curious, do you have any cameras or chimes?  If not, you probably need the fix from PR https://github.com/dgreif/ring/pull/1158.  Without this it's impossible to get updates from intercom devices in cases where a user doesn't also have cameras/chimes, even when updates are manually requested.

**Comment by dgreif** [comment]
@isibizi can you try the latest version? It includes the changes by @tsightler mentioned above.
