### ISSUE TITLE
Invalid Username or Password

### ISSUE THREAD

**Issue by mikemarconi** [dgreif/ring#1142]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 - Create an `ApiClient`
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - ring-client-api: [e.g 6.0.3]

**Comment by mikemarconi** [comment]
Dgreif -  I don't understand.  How do I get the plugin in to work.  It won't let me link my account.  Is there a way around this?

Mike

**Comment by dgreif** [comment]
You provided no information in your original issue, so I'm really not sure what issue you are running into. You should be able to provide your normal ring email/password, 2fa, and it should link without issues. If there are issues, please explain what they are.
