### ISSUE TITLE
Unable to connect to Ring servers

### ISSUE THREAD

**Issue by gopniq** [dgreif/ring#1144]
The ring servers can’t be reached by the ring plugin. See attached image. 

While I’m not certain but I suspect this to be the reason for not being able to live stream through the HomeKit app. Cameras work fine in the ring app itself. Also the snapshots every 10 seconds work fine. It’s just impossible to live stream the cameras. 

Homebridge 1.6.0
Plug-in 11.7.1

![7EE6E481-D2C0-4F59-95E2-22D4C0BF1E45](https://user-images.githubusercontent.com/122447632/214515108-30b1fd78-4b47-4560-b806-c33a313c7ee1.jpeg)

**Comment by gopniq** [comment]
Love this layout on mobile, sorry for that. 

But apparently an old bug is again surfacing where the ring servers can’t be reached by the plug-in.

**Comment by dgreif** [comment]
These errors are common if you have network/internet issues. I'd suggest restarting homebridge and see if they continue to happen

**Comment by gopniq** [comment]
I have restarted homebridge countless times without results. Did it again and now it seems to be working and the error comes a lot less frequently. Not sure what did the trick, because my raspberry pi is wired connected directly to my router on a gigabit network so shouldn’t be any issues there. I’m gonna keep an eye on it, thanks for now!

**Comment by hhunger2404** [comment]
[30/01/2023, 10:33:29] [homebridge-ring] Configuring cached accessory ee3ae909-ce40-4778-b08a-2675fc0e1c7a Haustür
[30/01/2023, 10:33:29] [homebridge-ring] Configuring cached accessory 56dcf407-5259-4507-8abf-3090bc8b1529 Garage
[30/01/2023, 10:33:29] [homebridge-ring] Configuring cached accessory 7b226174-97b4-4ded-93ba-ee15335ceb50 Garten
[30/01/2023, 10:33:30] Homebridge v1.6.0 (HAP v0.11.0) (homebridge-ring) is running on port 42105.
[30/01/2023, 10:33:32] [homebridge-ring] Found the following locations:
[30/01/2023, 10:33:32] [homebridge-ring]   locationId: 8578994b-eec7-4523-69e6-68bef4b94535 - 17c
[30/01/2023, 10:33:32] [homebridge-ring] Configuring 3 cameras and 4 devices for location "17c" - locationId: 8578994b-eec7-4523-69e6-68bef4b94535
[30/01/2023, 10:33:33] [homebridge-ring] Hidden accessory af4d7853-aebf-4d55-90c4-49fc0c5dcea4 chime_v2 Wohnzimmer Klingel 
[30/01/2023, 10:34:12] [homebridge-ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[30/01/2023, 10:35:35] [homebridge-ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/8578994b-eec7-4523-69e6-68bef4b94535.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[30/01/2023, 10:37:11] [homebridge-ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...


I have to join here. I have similar problem.
My internet connection is excellent. Restarting the router, the HB servers and the Homebridge have not achieved any change.

**Comment by dgreif** [comment]
What version of Node are you on?

**Comment by hhunger2404** [comment]
> What version of Node are you on?

18.13.0

**Comment by gopniq** [comment]
Came from 18.12.1 and updating to 18.13.0 now.

**Comment by hhunger2404** [comment]
Update. 
Activating ssh on the raspberry pi seems to do the trick. Don't know why, but so far no errors in the logs.

I used sudo hb-config to do it.

I'll keep you informed in case of changes.

**Comment by gopniq** [comment]
That unfortunately didn’t do the trick for me.

**Comment by tsightler** [comment]
Can you ping api.ring.com from the homebridge terminal?  I mean, the core error is very clear, the getaddrinfo ENOTFOUND is a basic error returned by the OS network stack when a name cannot be resolved.  This is almost definitely not a bug in ring-homebridge itself since the error is coming from such a basic level well below any code here.

**Comment by gopniq** [comment]
Yup no issue pinging that address from the Homebridge terminal.

**Comment by dgreif** [comment]
I agree with @tsightler, this is likely not an issue with the plugin. Looking at your original logs, there are several minutes between occurrences, which _might_ indicate things worked fine in between those requests. As I stated initially, this usually indicates some flakiness on your network, and isn't something we can really help debug.

**Comment by gopniq** [comment]
![E8B95F47-03E4-41C5-B192-92FF4C3453F3](https://user-images.githubusercontent.com/122447632/216777044-9baf8a2e-5ca6-4dec-a2b4-ab801cff9d7c.jpeg)

Maybe this helps? 2 of 3 camera’s worked okay but on the 3rd it even forced Homebridge to reboot.

**Comment by tsightler** [comment]
So here's one more possibility.  NodeJS does not do any native caching for DNS lookups and there's no caching in ring-client-api.  This leads to calls to ring-client-api performing LOTS of DNS lookups.  If you don't have a local caching DNS I've seen weird cases where some public DNS servers won't respond quickly enough to so many requests (probably some DDOS protection). 
 What DNS servers are you using for your homebridge install?

But again, the error is a simple DNS lookup error, so SOMETHING, has to be causing your system to fail these DNS lookups.  I'm just trying to offer some options that might help you determine why.  You can see clearly that the error is generated by the  node:dns, which is the NodeJS DNS code, and the error was returned by the OS, ENOTFOUND.  That can't be a bug in upper level code as those are low-level functions as the OS failed to resolve the IP address for the requested host.

**Comment by gopniq** [comment]
It was running on Avahi, but I can try to switch to Bonjour HAP. Other options are Ciao and systemd-resolved (experimental).

**Comment by tsightler** [comment]
The protocols you are asking about are all for mDNS i.e. local service discovery, as far as I know none of them having anything to do with external DNS lookups.

**Comment by gopniq** [comment]
Sorry my knowledge is on a bare minimum on this subject, I just flashed the image on my raspberry pi and installed multiple configs. It took me a whole night to get zigbee2mqtt running with sweat on my forehead for instance. 

I just can’t think of any flaws within my network since it is wired connected, apart from some firewall or other network securities on my modem preventing fluent communication.

**Comment by launchd** [comment]
I'm also having this issue, first time setting up homebridge but I don't see anything about a live camera feed after installing the plugin and linking my ring account

**Comment by dgreif** [comment]
Sorry this thread has gotten stale, but I don't think there is anything we can do from the plugin side. DNS issues are entirely unique to each users network and not easy to debug. Hopefully you are able to get this resolved on your end 🤞
