### ISSUE TITLE
Battery status notification

### ISSUE THREAD

**Issue by Drewbacca2** [dgreif/ring#1148]
# Feature Request

### Description
Use battery status as a trigger for automations

### Describe the solution you'd like
I’d like to be able to set up an automation when the battery status gets below a certain percent. I think that it would have to be set up as a sensor or something, but I’m not sure.

### Describe alternatives you've considered
Ring doesn’t send alerts outside the app, but I have to open it to see them. My doorbell usually runs out of battery for days before I realize it. It also notifies within the app at 30%, which is way too soon to change it.

**Comment by dgreif** [comment]
The homebridge plugin already supplies battery info to HomeKit. Triggering automations/alerts based on battery level would be a great feature, but is something that Apple should add to Home. I suggest you reach out to them and request the feature there.
