### ISSUE TITLE
Ring Cameras Not Loading

### ISSUE THREAD

**Issue by NickRivait** [dgreif/ring#1153]
# Bug Report

### Describe the Bug
 Error code in log around ring..

### To Reproduce
 - Create an `ApiClient`
 - Attempt to ...
 - See error

### Expected behavior
 Live Streams won't load, and gives error in photo. 

### Screenshots/Logs
 Added below. 

### Additional context
 Add any other context about the problem here.

### Environment

 - OS: [e.g.HOOBS 4.2.8]
 - Node.js: [e.g. 16.19p] 
 - NPM: [e.g ? ] 
 - ring-client-api: [11.7.1]

![image](https://user-images.githubusercontent.com/75817378/218143031-c6923d91-6855-4202-8cd8-a52b3442eb2a.jpeg)

**Comment by dgreif** [comment]
See https://github.com/dgreif/ring/issues/1145#issuecomment-1413962463
