### ISSUE TITLE
Ring Hoobs not showing any devices

### ISSUE THREAD

**Issue by imcl75** [dgreif/ring#1178]
# Bug Report

### Describe the Bug
 The hoobs ring plugin is not longer allowing me to see any of my ring devices in homekit / app.  I am running the latest version of hoobs, IOS beta, the plugin (11.7.2) etc.   This was working prior to recent update but unclear if hoobs or IOS beta or plugin update (or combination) has caused the failure.  I am running homebridge version 1.6 (via hoobs)node version 16.19.1.  In homebridge the ring bridge shows the plugin installed but zero transferred accessories - I have loads of ring devices, none are showing,

All other plugins and devices are working correctly.

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
Can you post your config (removing secrets)?
