### ISSUE TITLE
Streaming video only - ffmpeg was not found

### ISSUE THREAD

**Issue by itsgabraf** [dgreif/ring#118]
What does this mean? How do I fix it?

**Comment by d0n4v4nb3ck3r** [comment]
I don’t think you need too. If video is working and your not trying to do audio. Then you should be fine. It’s just let you know.

**Comment by dgreif** [comment]
https://github.com/dgreif/ring/wiki/FFmpeg - if you want audio to go with your video, you need to install ffmpeg with libfdk_aac.  If you don't care about audio, you can ignore it.
