### ISSUE TITLE
Question: Doorbell rings only once?

### ISSUE THREAD

**Issue by drheck** [dgreif/ring#1180]
When I press the doorbell several times in succession, i only hear it from the bell directly - the homepods only ring the first time.
Is this normal? Is it not possible to ring several times?

**Comment by dgreif** [comment]
There is a "debounce" period after you press the doorbell where the homebridge plugin prevents multiple events from being sent to HomeKit. This is to avoid accidentally sending the same event multiple times, and is expected behavior.
