### ISSUE TITLE
Failed to reach Ring server

### ISSUE THREAD

**Issue by jianyu-li** [dgreif/ring#1183]
# Bug Report

### Describe the Bug
 Receiving the following error in logs
Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...

### To Reproduce
 - Start Homebridge
 - See error

### Expected behavior
 No error

### Screenshots/Logs
 
![image](https://user-images.githubusercontent.com/52750081/224126499-b2f94a45-0f34-4612-84e1-1a8447c14e2e.png)

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

            "refreshToken": "",
            "hideLightGroups": true,
            "hideDoorbellSwitch": true,
            "hideCameraLight": true,
            "hideCameraMotionSensor": true,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "nightModeBypassFor": "all",
            "platform": "Ring"
```

### Environment

 - OS: Raspbian
 - Node.js: v18.12.1
 - NPM: 8.19.2
 - homebridge-ring: v11.7.2
 - homebridge: v1.6.0
 - hoobs: N/A

**Comment by rsuaver** [comment]
Was having the same issue since yesterday. I thought my HK automations broke (again) but then noticed these errors in Homebridge.

A reboot of Homebridge seems to have fixed the issue, but wonder if it'll happen again. My HB had been recently rebooted as I've been upgrading the underlaying system (OMV5 to OMV6) a few days ago.

**Comment by jianyu-li** [comment]
My errors have gone away as well. I'm going to go ahead and close this one for now
