### ISSUE TITLE
Can't click logon button in configuration

### ISSUE THREAD

**Issue by Highlander-bdj** [dgreif/ring#1184]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...
I'm trying to install the plugin on Hoobs.  When try to configure, and link an account the login button won't accept a click to continue.

### To Reproduce
Install ring plugin, click configure, click link account

### Expected behavior
 A clear and concise description of what you expected to happen.
account should link and provide refresh token

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

![image](https://user-images.githubusercontent.com/78763438/225114720-1a7f444a-2a85-49a3-88d3-53e95d954b19.png)

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian] Raspbian
 - Node.js: [e.g. 12.14.1]  16.9.1
 - NPM: [e.g 6.13.4]  9.6.1
 - homebridge-ring: [e.g 6.0.3] 11.7.2
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A] 4.3.0

**Comment by dgreif** [comment]
Please reach out to HOOBS support as they maintain the login flow for Ring within HOOBS
