### ISSUE TITLE
ffmpeg install error after updating

### ISSUE THREAD

**Issue by mannibis** [dgreif/ring#1189]
# Bug Report

### Describe the Bug
 ffmpeg module install error while trying to update homebridge-ring

### To Reproduce
 - Start Homebridge
 - Attempt to update homebridge-ring plugin
 - See error

### Expected behavior
 Successful update

### Screenshots/Logs
 USER: root
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-ring@11.7.4

[##################] / reify:rxjs: timing reifyNode:node_modules/homebridge-ring/node_
> ffmpeg-for-homebridge@0.1.4 install
> node install.js

node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module '/homebridge/node_modules/homebridge-ring/node_modules/ffmpeg-for-homebridge/install.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.13.0
npm ERR! code 1
npm ERR! path /homebridge/node_modules/homebridge-ring/node_modules/ffmpeg-for-homebridge
npm ERR! command failed
npm ERR! command sh -c -- node install.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2023-04-01T17_22_19_356Z-debug-0.log

Operation failed. Please review log for details.

### Additional context
 I checked the ffmpeg module github and it seems as if the most recent version is 0.1.0 but looking at the logs homebridge-ring is trying to install 0.1.4?

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: Docker via QNAP
 - Node.js: [e.g. 12.14.1]  v18.13.0
 - NPM: [e.g 6.13.4]  8.19.3
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by mannibis** [comment]
Seems to have fixed itself after re-trying to update tonight. thanks!

**Comment by mannibis** [comment]
So the ffmpeg-for-homebridge MODULE_NOT_FOUND error is happening again when trying to update to 11.7.5. Tried installing alternate version and 11.7.4 worked, so the issue seems to be happening every time there is an update. Did you hotfix 11.7.4 when I first reported this issue one version ago?

**Comment by dgreif** [comment]
I did not make any changes to 11.7.4. This install issue is specific to your system, and not something I can fix from the plugin side. I don't have any specific steps for you to fix it. Maybe uninstall/reinstall the plugin?

**Comment by mannibis** [comment]
Thanks for your response. So it worked again today. Such weird behavior. This happens during every update but if I try again 12 hours later the update process goes without a hitch. I won't re-open the issue again since it seems like time is the workaround.
