### ISSUE TITLE
ring-auth-cli returns error

### ISSUE THREAD

**Issue by mygrexit** [dgreif/ring#1192]
# Bug Report

### Describe the Bug

While requesting a token, the ring-auth-cli returns an error.

```
TypeError: Cannot use 'in' operator to search for 'error' in <html>
<head><title>406 Not Acceptable</title></head>
<body bgcolor="white">
<center><h1>406 Not Acceptable</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

```
at RingRestClient.getAuth (/homebridge/node_modules/homebridge-ring/lib/api/rest-client.js:151:119)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### To Reproduce
 - Do an ring-auth-cli
 - enter mail + password

**Comment by imcl75** [comment]
same too

**Comment by JamesHeathcote** [comment]
same issue

**Comment by RobVerhoeven00** [comment]
same here

**Comment by fate8383** [comment]
The same here

**Comment by praveenreddy854** [comment]
Same here.

**Comment by RobVerhoeven00** [comment]
it seems to be working again, I just reauthenticated and created the code again for homebridge.

**Comment by RobVerhoeven00** [comment]
oof, maybe a bit too early. it worked for a few minutes, and then camera's back to black, non responding. Back to previous state.

**Comment by antoine101009** [comment]
same :(

**Comment by imcl75** [comment]
My ring plugin for homebridge is now working (authentication works and so all devices show) however Scrypted ring plugin is not working still (authentication error unhandledRejection Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens). No code is received and code via authenticator also not working.

**Comment by imcl75** [comment]
spoke too soon.  issue persists.

[05/04/2023, 17:16:57] [homebridge-ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens

**Comment by CAVACO-PT** [comment]
same problem , folowing this !!!

**Comment by DEEJCUK** [comment]
same error after update

**Comment by rvmoldova** [comment]
> it seems to be working again, I just reauthenticated and created the code again for homebridge.

I had same thing, sometimes it randomly worked, thus cameras was blank.

**Comment by mplopez99** [comment]
Same issue - following this thread

**Comment by imcl75** [comment]
homebridge plugin seems to be working.  Scrypted is not - no 2FA code is generated / sent when log in to plugin.

sorry for duplication in logs:

linux arm #1613 SMP Thu Jan 5 11:59:48 GMT 2023
server version: 0.7.46
plugin version: @scrypted/ring 0.0.108
full
########################
4/6/2023, 6:21:21 PM
########################
node modules /server/volume/plugins/@scrypted/ring/node18-linux-arm-20230329
native dependencies (outdated) got socket.io-client

added 54 packages, and audited 55 packages in 9s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
native dependencies installed.
plugin loaded
discovery failure Error: refresh token, username, and password are missing.
    at Tr.tryLogin (/src/main.ts:111:19)
    at Tr.discoverDevices (/src/main.ts:155:20)
    at new Tr (/src/main.ts:68:14)
    at Object.onLoadZip (/server/node_modules/@scrypted/server/src/plugin/plugin-remote-worker.ts:325:38)
    at Object.loadZip (/server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:660:28)
    at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:734:37)
login success, trying discovery
login success, trying discovery
unhandledRejection Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at xt.getGrantData (/external/ring-client-api/packages/ring-client-api/rest-client.ts:186:11)
    at xt.getAuth (/external/ring-client-api/packages/ring-client-api/rest-client.ts:192:28)
    at xt.getAuth (/external/ring-client-api/packages/ring-client-api/rest-client.ts:223:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
unhandledRejection Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at xt.getGrantData (/external/ring-client-api/packages/ring-client-api/rest-client.ts:186:11)
    at xt.getAuth (/external/ring-client-api/packages/ring-client-api/rest-client.ts:192:28)
    at xt.getAuth (/external/ring-client-api/packages/ring-client-api/rest-client.ts:223:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by dgreif** [comment]
If you are having issues with Scrypted, please post on https://github.com/koush/scrypted/discussions/695. I do not maintain the Scrypted Ring plugin, so I can't help out with issues there.

For those using `homebridge-ring` or `ring-client-api` (which is used by `mqtt-ring`, this is the right place. I just tried to reproduce this issue, and I'm not seeing any issues on my end. Seems like there has been some back and forth from users on this thread about it working again. @mygrexit can you give it another try and see if things are working now? I'm guessing Ring change something and then reverted it.

**Comment by mplopez99** [comment]
Running HOOBS on a Pi 4B -install the Ring plugin as its own hub. Log in and verify with 2FA but still have the authentication error. response code 406. Not sure why it says plug in is not configured.

HOOBS VER= 4.3.0
Ring Ver = 11.7.4


log shows:

M Ring Bridge Loaded plugin 'homebridge-zing'
AM Ring Bridge Loading 1 platforms...
AM Ring Bridge Ring WARNING Plugin is not configured. Visit https://github.com/dgreit/zing/tree/main/packages /homebridge-ringthomebridge-configu
AM Ring Bridge Bridge is running on port 51856.
AM Ring Bridge Configuration change
AM Ring Bridge Loaded plugin 'homebridge-ring'
AM Ring Bridge Loading 1 platforms...
3 AM Ring Bridge Bridge is running on port 51856.
3 AM Ring Bridge Ring ERROR ETPError: Response code 406 (Not Acceptable)
8 AM Ring Bridge Ring ERROR
Request to https://api.ring.com/devices/vI/locations failed:
8 AM Ring Bridge Ring
ERROR
Error: Refresh token is not valid.
Unable to authenticate with Ring servers. See https://github.com/dgreif/ring/wiki/Re
18 AM Ring Bridge Ring
ERROR
Error connecting to APT
08 AM Ring Bridge Ring
ERROR
Error: Refresh token is not valid. Unable to authenticate with Ring servers.
See https://github.com/dgre1£/ring/wikí/Re:

HOOBS VER= 4.3.0
Ring Ver = 11.7.4

Any help would be greatly appreciated!

**Comment by dgreif** [comment]
I've updated the plugin with a potential fix. Y'all mind trying v`11.7.5`?

**Comment by mplopez99** [comment]
I can confirm that 11.7.5 works. I removed the bridge. Installed the plug in as a new bridge and everything worked. Thanks! I'll send over more beer money via PayPal. thanks!

**Comment by tsightler** [comment]
Hi @dgreif, I meant to post here yesterday that I was able to reproduce the issue and the PR above which added User-Agent seemed to correct it, however, I'm guessing your fix with a different header would also work.  I'll push out a build of ring-mqtt with the new ring-client-api and hopefully that will close the reports I have.  Thanks!

**Comment by fate8383** [comment]
Works! Thanks

**Comment by dgreif** [comment]
@tsightler thanks for the note. I'd prefer to stick to a more generic user agent if at all possible, so let me know if my current version fixes things for you

**Comment by tsightler** [comment]
Yep, I pushed out a new version today and tested it myself and also have confirmation from a couple of other users.  I think it's good.

**Comment by dgreif** [comment]
Wonderful, thanks @tsightler! I'm going to call this resolved then 😄

**Comment by imcl75** [comment]
Thanks
