### ISSUE TITLE
412 error when loading camera stream

### ISSUE THREAD

**Issue by JaviSoto** [dgreif/ring#1194]
# Bug Report

### Describe the Bug
Loading the live stream for any of my Ring cameras using the Home app times out and shows an error. The logs in HomeBridge tell us why.

### To Reproduce
 - Start Homebridge
 - Open Home app on any Apple device
 - Tap on any Ring camera

### Expected behavior
 - Stream starts.

### Screenshots/Logs
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/666807/230185147-4f870fe7-e0d7-4fd3-aef3-e176bf78e705.png">

```
[4/5/2023, 12:18:56 PM] [homebridge-ring] Preparing Live Stream for Front
[4/5/2023, 12:19:46 PM] [homebridge-ring] Preparing Live Stream for Front
[4/5/2023, 12:21:08 PM] [homebridge-ring] Request to https://api.ring.com/clients_api/doorbots/XXX/live_call failed with status 412. Response body: {"message":"RING_API_CALL_REQUEST_FAILURE"}
[4/5/2023, 12:21:08 PM] [homebridge-ring] Failed to prepare stream for Front (81.593s)
[4/5/2023, 12:21:08 PM] [homebridge-ring] HTTPError: Response code 412 (Precondition Failed)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1680722462590,
    socket: 1680722462591,
    lookup: 1680722462591,
    connect: 1680722462597,
    secureConnect: 1680722462721,
    upload: 1680722462721,
    response: 1680722468051,
    end: 1680722468052,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 0,
      tcp: 6,
      tls: 124,
      request: 0,
      firstByte: 5330,
      download: 1,
      total: 5462
    }
  }
}
```

### Additional context
- Snapshots are working. And the cameras do work using the Ring app.
- I thought maybe it was the latest v11.7.4 update which I just installed yesterday, but I tried downgrading to several previous versions and the issue is still there, so I imagine it may be something on Ring's end?

### Homebridge Ring Config
```
{
    "refreshToken": "XXX",
    "alarmOnEntryDelay": true,
    "hideCameraSirenSwitch": true,
    "hideAlarmSirenSwitch": true,
    "showPanicButtons": false,
    "avoidSnapshotBatteryDrain": true,
    "debug": true,
    "_bridge": {
        "username": "XXX",
        "port": XXX
    },
    "platform": "Ring"
}
```

### Environment
 - OS: Raspbian
 - Node.js: v18.14.2
 - NPM: 9.5.0
 - homebridge-ring: v11.7.4
 - homebridge: v1.6.0
 - hoobs: N/A

**Comment by Dababa26** [comment]
Pareil pour moi mais depuis la mise à jour iOS 16.4 avec nouvelle architecture, j’espère une solution du plugin Ring 🙌

**Comment by JaviSoto** [comment]
Ah, this must've been an issue on Ring's end, because things are working now, I didn't make any changes
