### ISSUE TITLE
How to get recording URL of event

### ISSUE THREAD

**Issue by BasvanH** [dgreif/ring#1195]
With ``camera.onNewNotification.subscribe()``, how can I get the recording URL of the ding or motion? In the event there's a ``streaming_data_hash``, can this be used in some way?

Thanks in advance!

**Comment by dgreif** [comment]
I haven't tested this recently, but I believe the following should work:


```ts
camera.onNewNotification.subscribe(async notification => {
  const dingId = notification.ding.id
  const recordingUrl = camera.getRecordingUrl(dingId)
  console.log('Recording URL', recordingUrl)
})
```
