### ISSUE TITLE
[Streaming]: Ring Battery Doorbell Plus

### ISSUE THREAD

**Issue by RadDip** [dgreif/ring#1198]
### Streaming Issue

I replaced my older Ring Doorbell 2nd Generation with a new Ring Battery Doorbell Plus and I can no longer stream the device in HomeKit.  I attempted to reauthenticate with a  new token and even deleted the device in HomeKit and re-added it.  

### Proposed Solution

Provide support for new Ring Battery Doorbell Plus.

### Environment

HOOBS

### What operating system are you on?

Mac

### Honesty Time

- [X] I swear this is worth your time!

**Comment by dgreif** [comment]
You are likely experiencing issues with codec negotiation. See https://github.com/dgreif/ring/wiki/Camera-Troubleshooting#hevc-code---legacy-video-mode
