### ISSUE TITLE
Error when sending request

### ISSUE THREAD

**Issue by abraham-mai** [dgreif/ring#1199]
Hi there,

for a few days now, I get the following error, when trying to open my door (with Ring Intercom). It has been working really well before. This is the error I get. Anyone else with the same issue?

Request to https://api.ring.com/commands/v1/devices/xxxx/device_rpc failed with status 422. Response body:  
[12/04/2023, 12:57:31] [homebridge-ring] HTTPError: Response code 422 (Unprocessable Entity)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1681297045550,
    socket: 1681297045552,
    lookup: 1681297045553,
    connect: 1681297045663,
    secureConnect: 1681297045797,
    upload: 1681297045797,
    response: 1681297051147,
    end: 1681297051149,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 1,
      tcp: 110,
      tls: 134,
      request: 0,
      firstByte: 5350,
      download: 2,
      total: 5599
    }
  }
}

**Comment by Lechucico** [comment]
Same error here. Happens randomly.

**Comment by dgreif** [comment]
To clarify, is the intercom open button sometimes working and sometimes not? Unfortunately I don't have an intercom to test with, so I likely won't be able to help track this down.
