### ISSUE TITLE
Check alarm status disarm/home/away?

### ISSUE THREAD

**Issue by qnguye** [dgreif/ring#120]
Is there a way to check the current status of the alarm? disarm/home or away. I run arm home multiple times during night hours and after awhile, my ring account trashed and no longer get notifications from phone app anymore.

**Comment by dgreif** [comment]
I'm a little confused what you are asking for.  Do you want to see the status via the homebridge plugin?  If so, the Home app (or any HomeKit app) should correctly reflect the current state of the alarm.  You should be able to set it once at night, and it won't disarm until you tell it to either via HomeKit or with the Ring app or keypad.

Regarding the Ring app getting messed up, I have a change that I am hoping will fix that issue, which I plan to publish some time this week

**Comment by qnguye** [comment]
I have cron job to arm home alarm every hour at night (in case if I forgot to arm it). I want to know if there is a way to check if it already armed, no need to arm again.

**Comment by dgreif** [comment]
You can do something like this:

```ts
async function ensureAlarmMode(location, desiredAlarmMode) {
  const secuirtyPanel = await location.getSecurityPanel(),
    currentAlarmMode = securityPanel.data.mode

  if (currentAlarmMode !== desiredAlarmMode) {
    await location.setAlarmMode(desiredAlarmMode)
  }
}

ensureAlarmMode('some') // for home
ensureAlarmMode('all') // for away
```

**Comment by qnguye** [comment]
there was a typo but this is exactly what i need. Thank you.
