### ISSUE TITLE
Activity Notifications are missing and/or will not enable. 

### ISSUE THREAD

**Issue by Excession420** [dgreif/ring#1202]
# Bug Report

### Describe the Bug
When going to Home app, with latest updates, there are no longer activity notifications available for ring camera’s. Additionally, with the Ring Doorbell camera, there is an activity notification that is available, but when trying to enable the button to display activity notifications, it disables after exiting the setting. 

### To Reproduce

1. Open Home app. 
2. Go to Home Settings
3. Go to Cameras & Doorbells
4. ISSUE 1: No ring camera’s appear except for the Doorbell. 
5. ISSUE 2: Click the doorbell camera. 
6. ISSUE 2 CONTINUED: Enable switch for Activity Notifications
7. ISSUE 2 CONTINUED: Back out of this menu and reopen the menu (the switch is defaults back to being off).

### Expected behavior
Activity notifications should be available (and functioning) for all types of cameras. 

### Screenshots/Logs
N/A

### Additional context
N/a

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

**"hideLightGroups": true,
"hideDoorbellSwitch": true,
"hideCameraLight": true,
"hideCameraMotionSensor"': true,
"hideInHomeDoorbellSwitch": true,
"hideUnsupportedServices": true,
"nightModeBypassFor"; "some",
"sendCameraMotionNotificationsToTv"; false,
"sendDoorbellMotionNotificationsToTv": true,
"showPanicButtons": false,
"hideAlarmSirenSwitch"; true,
"hideCameraSirenSwitch": true**

### Environment
<!-- ✍️edit: -->
 - OS: [e.g. Raspbian]
 - Node.js: [16.9.1]
 - homebridge-ring: [11.7.5]
 - homebridge: [1.6.0]
 - hoobs: [4.3.0]

**Comment by dgreif** [comment]
For your first issue, please run the [Data Discovery](https://github.com/dgreif/ring/wiki/Data-Discovery) tool and post the results here. This will allow me to see the number/type of cameras you expect to see in your Home app.

For issue 2, unfortunately this sounds like a Home App bug, and not something I can fix from the plugin. I suggest looking for iOS update and restarting your phone/home hub.

**Comment by Excession420** [comment]
I guess I should clarify - the camera's all appear in the home app. I have 7 Ring Stick-Up cameras. However, they do not appear in the notification section of the Home app. I have the latest software on my Apple devices. It used to work, where you can enable notifications on the Home app for all the Homebridge ring camera's to where they appear on the Apple TV, Apple Watch, and iPhone's (as in, when there is motion), however, when updating to the latest version on the Ring Bridge software on Hoobs, it went away.

**Comment by dgreif** [comment]
I noticed you have quite a few of the `hide*` settings turned on. I think the `hideDoorbellSwitch` and `hideCameraMotionSensor` settings are probably the reason you lost access to the notifications. Can you set those to `false` (or remove them), reboot, and then see if your settings come back?

**Comment by Excession420** [comment]
You got it - it was the “Hide Camera Motion Sensor” setting. It should have been unchecked. Thank you!

On May 13, 2023, at 1:18 PM, Dusty Greif ***@***.***> wrote:



I noticed you have quite a few of the hide* settings turned on. I think the hideDoorbellSwitch and hideCameraMotionSensor settings are probably the reason you lost access to the notifications. Can you set those to false (or remove them), reboot, and then see if your settings come back?
