### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by mschwartz** [dgreif/ring#1205]
# Bug Report

### Describe the Bug
I am unable to login anymore using npx -p ring-client-api ring-auth-cli

### To Reproduce
In addition to failing (406 error) I was getting exceptions where your code tries to use 'in' keyword.  I removed those tests and the code no longer throws the "can't do in of undefined" and now...

Error reported is:
```
responseData <html>
<head><title>406 Not Acceptable</title></head>
<body bgcolor="white">
<center><h1>406 Not Acceptable</h1></center>
<hr><center>nginx</center>
</body>
</html>

Error: Failed to fetch oauth token from Ring. Verify that your email and password are correct. (error: )
    at RingRestClient.<anonymous> (/home/mschwartz/gitlab/mschwartz/monorobo/node_modules/ring-client-api/lib/api/rest-client.js:182:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/mschwartz/gitlab/mschwartz/monorobo/node_modules/ring-client-api/lib/api/rest-client.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

### Expected behavior
Success, my login/password works in the ring app and on the ring.com site.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
I have been using this for a couple of years and have had to do the npx thing to login and get oauth code.  This is the first time it's failed.

### Environment

 - OS: linux
 - node v16.19.1
 - NPM: 8.19.2
 - ring-client-api: 9.24.0

**Comment by smockle** [comment]
@mschwartz This sounds similar to https://github.com/dgreif/ring/issues/1192, which was fixed in [version 11.7.5](https://github.com/dgreif/ring/releases/tag/ring-client-api%4011.7.5). You’re using version 9.24.0. Does the issue still repro if you update to the latest version?

**Comment by mschwartz** [comment]
I’ll give it a try.

**Comment by mschwartz** [comment]
It’s failing doing the npx command at the command line to get the initial authorization.

just FYI

**Comment by mschwartz** [comment]
Installing @latest worked!

Thanks, and sorry to bother you.
