### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by HOMESEERDUDE** [dgreif/ring#1209]
i am getting errors
[5/3/2023, 11:16:53 AM] [Ring] Fail
ed to reach Ring server at https://
app.ring.com/api/v1/mode/location/d
p9814-eb59-0. getaddrinfo EAI_AGAI
N app.ring.com. Trying again in 5
seconds
[5/3/2023, 11:16:55 AM] [Ring] Fail
ed to reach Ring server at https://
app.ring.com/api/v1/mode/location/d
p9814-eb59-0. getaddrinfo EAI_AGAI
N app.ring.com. Trying again in 5
seconds
[5/3/2023, 11:17:32 AM] [Ring] Fail
ed to reach Ring server at https://
app.ring.com/api/vl/mode/location/d
p9814-eb59-0. getaddrinfo EAI-AGAI
N app.ring.com. Trying again in 5
seconds.
[5/3/2023, 11:17:34 AM] [Ring] Fail
ed to reach Ring server at https://
app.ring.com/api/v1/mode/location/d
p9814-eb59-0. getaddrinfo EAI-AGAI
N app.ring.com. Trying again 

any help would be appriciated

thank you

# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
See https://github.com/dgreif/ring/issues/974#issuecomment-1171679441. `EAI_AGAIN` is a DNS lookup error, and is related to your networking setup or the server you are running homebridge on. It's not an issue with the plugin, so unfortunately there is nothing I can do.
