### ISSUE TITLE
Snapshot failed to refresh after 60 attempts

### ISSUE THREAD

**Issue by benfysh** [dgreif/ring#121]
On of my ring devices is now starting to receive the follow error in the logs and the associated camera tile is not being updated in the Home app. 

```
[2019-9-2 09:23:37] [Ring] Snapshot failed to refresh after 60 attempts
[2019-9-2 09:23:37] [Ring] 404 from endpoint https://api.ring.com/clients_api/snapshots/image/4997650
[2019-9-2 09:23:37] [Ring] Failed to retrieve snapshot for Back Door (47.85s).  The camera currently reports that is it online
[2019-9-2 09:23:37] [Ring] Error: Not found with response: no snapshot
    at RingRestClient.<anonymous> (/usr/lib/node_modules/homebridge-ring/lib/api/rest-client.js:218:27)
    at Generator.throw (<anonymous>)
    at rejected (/usr/lib/node_modules/homebridge-ring/lib/api/rest-client.js:5:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
[2019-9-2 09:24:05] [Ring] Snapshot for Back Door Requested
```

If I then tap into the live view the stream will load and then the last view when closing will become the snapshot however this will not refresh and the same error will be thrown in the logs. 

My other devices (one of which is in the same room) are working as expected (_except for one that only works locally. however I will raise a separate issue for that as it seems unrelated_).

**Comment by dgreif** [comment]
It sounds like the snapshots are not getting updated on the Ring server.  The plugin waits ~30 seconds for a new snapshot (checks every .5 seconds, thus 60 tries).  One thing you should check is whether or not that camera can fetch a new snapshot in the official Ring app.  When you open the Ring app to its main screen, all cameras should fetch a new snapshot and show up at roughly the same time.  If that particular camera isn't able to get a new snapshot in the Ring app, that would prove that it's something on Ring's end.  Let me know if/how long it takes for it to get a snapshot.  Which camera model is it?

**Comment by benfysh** [comment]
That seems to be the problem. The other three devices are updating more or less in sync in the official app whilst the one with the issue will only update after ‘going live’. 

It is one of three Floodlight cameras. 

I will raise it with Ring tomorrow and see what they say.

**Comment by dgreif** [comment]
Ok, good to know.  Please let me know if they figure out the issue.  I think one other person has reported similar issues so far

**Comment by EarthRise626** [comment]
My floodlight camera has historically been much more finicky than the Doorbell Cams. It’s not for a lack of WiFi connection strength, so my assumption is that it’s a quirk with the product.

**Comment by benfysh** [comment]
Spoke to ring and they amongst other things said:

>On Tue, Sep 3, 2019 at 9:29 AM <> wrote:
As I check the device here. It has an intermittent connection from the router so that's why you have this issue, As the Signal Strength( RSSI) is -63 the acceptable is -50 and below.
>
> On Tue, Sep 3, 2019 at 9:30 AM <> wrote:
Sometimes the snapshot on the ring application may not be updated it's because of a slow internet.

My internet is not exactly slow and one of my devices has worse RSSI and snapshots work fine ¯\_(ツ)_/¯ 
So I just ended up power cycling  all the cameras and that seems to have worked for now.

**Comment by dgreif** [comment]
Awesome, thanks for the update!
