### ISSUE TITLE
Ring Cameras "Stuck" in HomeKit

### ISSUE THREAD

**Issue by arrmo** [dgreif/ring#1211]
# Bug Report

### Describe the Bug
Rather than duplicate it all here, see a Homebridge discussion of the issue [here](https://github.com/homebridge/homebridge/issues/3360)? I reported this against Homebridge, but perhaps it's the plugin? Either way, I can't remove a plugin-added device 😞.

Thanks!

### To Reproduce
As outlined at the noted link

### Expected behavior
Also at the link 😉 

### Screenshots/Logs
Perhaps this one, shows that the ability to delete is missing?
![image](https://user-images.githubusercontent.com/8756384/236448420-430e4f3d-c8a7-44a3-878f-27b72b8731f0.png)

### Additional context
N/A

### Homebridge Ring Config
I have removed, re-added the plugin multiple times, to try to address. Right now it's removed (but still can't remove the devices). Re-add?

### Environment
 - OS: Ubuntu 22.04.2 LTS
 - Node.js: v18.16.0
 - NPM: 9.5.1
 - homebridge-ring: v11.7.5
 - homebridge: v1.6.1
 - hoobs: N/A

**Comment by dgreif** [comment]
Sorry to hear you are having trouble. Unfortunately if removing the plugin doesn't fix the issue, there isn't much I can do. You likely need to remove the files in your `persist`/`accessory` folder, but doing so can be tedious and dangerous if you don't want to lose the config for other plugins. I'm not an expert in this area, so I'd defer you back to the other thread you already have open on the homebridge repo.

**Comment by arrmo** [comment]
Got it, thanks!

FYI, the only solution I found was to remove the entire Homebridge (bridge) in HomeKit, remove ALL devices, start over 😞

**Comment by dgreif** [comment]
That's very unfortunate, but I'm glad you were able to get it resolved!
