### ISSUE TITLE
Ring-client-api not finding rest-client

### ISSUE THREAD

**Issue by Darrilla** [dgreif/ring#1224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

The issue is fully described in #1117

### To Reproduce

@dgreif I am still having this issue in version 11.7.1.

I tried the solution here:

import { RingRestClient } from 'ring-client-api/rest-client';

Burt when I try to build it:

src/index.ts(17,32): error TS2307: Cannot find module 'ring-client-api/rest-client' or its corresponding type declarations.

I can get the error to disappear if I use:

import { RingRestClient } from 'ring-client-api/lib/rest-client';

But then when I try to use my package in another application, it can't find it:

Error: Package subpath './lib/rest-client' is not defined by "exports" in ..../ring/node_modules/ring-client-api/package.json

But is is defined!

"./rest-client": "./lib/rest-client.js"

### Expected behavior

I need to use the rest-client for authentication. I should be able to use it. It stopped working when I tried to update from v11.3.1 to v11.5.2 and ultimately to v11.7.1

### OS

Linux

### Node.js Version

v19.9.0

### NPM Version

8.9.13

### ring-client-api

v11.7.1

### Operating System

macOS

**Comment by Darrilla** [comment]
As a work-around, if I manually change the package.json in my node_modules:

    "./rest-client": "./lib/rest-client.js",
    "./lib/rest-client": "./lib/rest-client.js"

Adding that last line allows everything to work for me. I still need to import this way:

import { RingRestClient } from 'ring-client-api/lib/rest-client';

**Comment by Darrilla** [comment]
I have a PR for this change:

https://github.com/dgreif/ring/pull/1226

**Comment by djm181** [comment]
You can import the original `ring-client-api/rest-client` correctly if you set `moduleResolution: "node16"` in your tsconfig.json. I don't think you'll need your PR after that. I'm using the rest-client directly with this approach.

**Comment by Darrilla** [comment]
Thank you so much. I will close my PR
