### ISSUE TITLE
No Devices Showing

### ISSUE THREAD

**Issue by willi7740** [dgreif/ring#1227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I added the plugin to my hoobs and linked my account. After setup, I have no devices showing. The only thing in my log is the authorization token.

### Expected behavior

to be able to see my ring alarm system.

### Homebridge Ring Config

```shell
hoobs
```

### OS

rasbarian

### Node.js Version

14.17.5

### NPM Version

4.7.1

### Homebridge/HOOBs Version

4.0.110

### Homebridge Ring Plugin Version

11.7.6

### Operating System

Raspbarian

**Comment by dgreif** [comment]
Sorry you are having issues, but there is not enough to go off of in this issue. Can you please attach some logs?

One common issue is that a Ring Alarm or Ring Lighting Bridge is on your account but not currently connected to internet/power.

**Comment by dgreif** [comment]
Closing due to lack of response
