### ISSUE TITLE
Doorbell button not working with Ring Intercom

### ISSUE THREAD

**Issue by stodla123** [dgreif/ring#1229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Unfortunately the switch that is exposed with Ring Intercom when someone presses the Doorbell does not work properly for me with homebridge-ring v11.7.6.

I was under the impression that is has worked before since i got HomeKit notifications before.

### Expected behavior

The button should trigger my automations but is does not.

### Relevant log output

```shell
no logs
```

### Homebridge Ring Config

```shell
{
    "refreshToken": "",
    "platform": "Ring",
    "_bridge": {
        "username": "",
        "port": 46372
    }
}
```

### Additional context

It is running as a child bridge in Homebridge [v1.6.1] on debian bullseye 11

Node.js Version | v18.16.0

### OS

debian 11 bullseye

### Node.js Version

v18.16.0

### NPM Version

npm --version 9.5.1

### Homebridge/HOOBs Version

 Homebridge [v1.6.1] 

### Homebridge Ring Plugin Version

v11.7.6.

### Operating System

debian 11 bullseye

**Comment by 7onnie** [comment]
I have this issue too.
Everything else (opening the door manually in Apple Home, and getting an „door unlocked“ from AppleHome when unlocking the door in the Ring App) works just fine, only the button stopped triggering my Automation (unlock door).

**Comment by dgreif** [comment]
Thanks for reporting. The root cause for this is related to Push Notifications not working. This issue is being tracked in #1218

**Comment by stodla123** [comment]
hello @dgreif  and first of all thank you for the fast reply!

after updating to version homebridge-ring v11.7.7 and then following the instructions stated in #1218 (re-login / re-auth)
i can report now that push-notifications are working for me again! THANK YOU!





since location has been discussed in above mentioned tread: i'm european (austria)
