### ISSUE TITLE
HOOBs Official Plugin Support?

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [dgreif/ring#123]
Would be nice if this would be an official plugin for HOOBs (HomeBridge Out Of the Box)

**Comment by adavison007** [comment]
@dgreif I'm running the Hoops beta, the ring plugin works fine other than snap shots (video does work) does not work on Spotlight Cam and Flood light cam

**Comment by adavison007** [comment]
> @dgreif I'm running the Hoops beta, the ring plugin works fine other than snap shots (video does work) does not work on Spotlight Cam and Flood light cam

Here's what the log says....

[Homebridge] [9/5/2019, 10:10:28 PM] [Ring] Failed to retrieve snapshot for Patio (44.749s).  The camera currently reports that is it online
[Homebridge] [9/5/2019, 10:10:28 PM] [Ring] Error: Not found with response: no snapshot
[Homebridge] at RingRestClient.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:231:27)
[Homebridge] at Generator.throw (<anonymous>)
[Homebridge] at rejected (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:6:65)
[Homebridge] at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by dgreif** [comment]
@adavison007 that is most likely an issue on Ring's end.  Try rebooting the camera.  Not sure why they are having so many snapshot issues lately.  Do the snapshots work for that camera in the Ring app?

**Comment by adavison007** [comment]
@dgreif Great question, just checked and the snapshots are not working in the ring app for those same two cameras! I'll need to pel a fuse to rest those cameras, stay tuned!

**Comment by adavison007** [comment]
> @adavison007 that is most likely an issue on Ring's end. Try rebooting the camera. Not sure why they are having so many snapshot issues lately. Do the snapshots work for that camera in the Ring app?

@dgreif So camera reboot fixed it! Thanks!

**Comment by d0n4v4nb3ck3r** [comment]
@adavison007 it works fine in the beta. But I have been talking to @dgreif about making it an official plugin for them. So that when you go to the plugin area of hoobs, you can find it quick and install it.

**Comment by dgreif** [comment]
This is being tracked over at https://github.com/hoobs-org/HOOBS/issues/97
