### ISSUE TITLE
No devices found and location looks to be wrong

### ISSUE THREAD

**Issue by husoseli15** [dgreif/ring#1235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I’ve been having this issue for about a year now, where ring stopped working completely with my home bridge. 

I’ve updated the node to the latest one (v18.16.0), I’ve also updated hkmebridge ring and also downgrading. I see the following in my log:

[07/06/2023,
00:25:01] [Ring] Found th
e following locations:
[07/06/2023, 00:25:01] [Ring]
locati
onId: (private location ID) - (city name)
[07/06/2023, 00:25:01] [Ring] Configur
ing O cameras and 0 devices for locati
"(City name) " - locationId: (private location id) 

one thing that is strange in this log is the city name that shows up. It’s showing a city name that i currently do not reside in. Not sure if this could be a root cause or not. I also don’t know where to update this city name. 

As I said, homebridge ring worked like a charm about a year ago. Apple TV integrated perfectly and I was able to see a live stream. Now, I cannot get any of it to work. Ring doesn’t show up in my HomeKit at all.

### Expected behavior

To have homebridge ring work with homekit

### Homebridge Ring Config

```shell
{
            "refreshToken": "prvi token",
            "platform": "Ring"
        }
```

### OS

Rasbian

### Node.js Version

V18.16.0

### NPM Version

9.4.0

### Homebridge/HOOBs Version

1.6.1

### Homebridge Ring Plugin Version

11.7.7

### Operating System

Rasbian

**Comment by dgreif** [comment]
@husoseli15 sorry you are having issues. There isn't much to go off of here, but I'm curious if maybe you are using a "shared" account to access your devices? The incorrect address and lack of devices all come directly from the Ring servers, so I'm not sure what the plugin could be doing to cross wires for you here.

**Comment by husoseli15** [comment]
Do you think doing a factory reset on ring could possibly fix the problem? 

It's not a shared ring. I purchased it new and I've only set it up in this location. What bothers me the most that this worker previously, maybe 4 generations ago on your ring module. No idea what's different now :/ I may wipe ring and try again. May even do a full homebridge reinstallation to see if anything changes. 

Is there anything that I can share/provide to you that'd help you troubleshoot?

**Comment by husoseli15** [comment]
Did a full wipe and reinstalled homebridge. All works now!
