### ISSUE TITLE
Doorbell unavailable outside home

### ISSUE THREAD

**Issue by benfysh** [dgreif/ring#124]
My doorbell shows as ‘No Response’ when I am not on my home WiFi network. This is for all aspects (button, motion sensor and camera). However, I do still get home app doorbell notifications (just with no image).

My three other devices (Floodlight cameras) all work as expected streaming and snapshots both home and away.

The same behaviour can be seen both on 4g and external WiFi networks. I am unable to post any logs as the device does not appear in the logs at all in this scenario.

**Comment by dgreif** [comment]
See #91.  This is a weird HomeKit/homebridge issue and unfortunately I don't know exactly what causes/solves it.  Let me know if you find something specific that works!

**Comment by benfysh** [comment]
Thanks, interestingly mine seems to be a partial (1 of 4) as opposed to complete camera unavailability as mentioned issue. I may try removing and then adding the doorbell again.

**Comment by efloyd** [comment]
I had the same issue, and resolved it by closing the Home app on all devices and rebooting all of my HomeKit hubs (all apple TVs and iPads).

**Comment by benfysh** [comment]
Hi, just to update on this. My doorbell started to work outside of home after iOS 13 was released and then stopped again. 

After some debugging it seems like it is not available when the Apple TV is acting as a hub only when one of my HomePods are. 

Not sure what the difference is between the two but hopefully this might help someone else who has the same issue.

**Comment by dgreif** [comment]
Hmm, that's really odd.  I'm running all of mine through an apple tv and it works great.  Maybe you were running a different software version on the apple tv that didn't play well with iOS 13 😕

**Comment by benfysh** [comment]
They are all on the latest version, maybe it’s a combination of HomePods and an Apple TV it doesn’t like 🤷🏼‍♂️ I will check again once they inevitably release the next .1 update

**Comment by dgreif** [comment]
@benfysh did you ever get this figured out?  Did later updates to your apple products sort it out?

**Comment by benfysh** [comment]
Hi @dgreif l have kept that Apple TV disabled from being a hub and haven’t seen the issue since. I have also bought the 4K model recently and that has successfully acted as a hub for all four cameras. 

I can enable the original one and see if it works with 13.3 if that helps?
