### ISSUE TITLE
No chime or TVOS notifications

### ISSUE THREAD

**Issue by dazza120** [dgreif/ring#1241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

So this was working before but has long since stopped but is becoming a bug bear since getting rid of the ring chimes seen as i have 6 minis and 5 OG HomePods. do we get no notifications because ring have done a subscription for notifications?

I no longer pay for ring as i have wired camera's everywhere but would still want the bell to actually chime inside having got rid of the ring chimes and just using the HomePods could this be the issue that people are experiencing with the HomePod chimes not working? I have un-Aurthuriesed the all my devices and also reinstalled the ring plug-in and also deleted and re-installed in HomeKit. This has still not enabled the chimes to work. But this is what i have noticed from the log, but i have also noticed that no doorbell notifications are being sent from the log.

11/06/2023, 11:25:40Ring BridgeRingERROR404 from endpoint https://api.ring.com/clients_api/doorbots/1199401/motions_subscribe
11/06/2023, 11:25:40Ring BridgeRingERRORSession hardware_id not found.  Creating a new session and trying again.
11/06/2023, 11:25:40Ring BridgeRingERROR404 from endpoint https://api.ring.com/clients_api/doorbots/1199401/subscribe
11/06/2023, 11:25:40Ring BridgeRingERRORSession hardware_id not found.  Creating a new session and trying again.

### Expected behavior

The HomePods to work as chimes again and TVOS to receive these push notifications

### OS

Hoobs 4.3

### Node.js Version

16.20

### NPM Version

unknown

### ring-client-api

11.8.0

### Operating System

Hoobs on pi3

**Comment by dgreif** [comment]
Would you mind following the steps in https://github.com/dgreif/ring/wiki/Notification-Troubleshooting and see if that fixes it?

**Comment by dazza120** [comment]
Hi mate firstly thank you for stepping up where a company that promised so much didn’t deliver thank you.

right I’ve tried all the steps repeatedly de authorising all devices it seems to include the browser as a device along with HomeKit or maybe it’s not the browser and just sees hoobs as a browser/computer.

I thought the issue might be the browser so in-authorised all and used chrome instead of safari. Then I even paid to see if it would work disabling all devices before adding it back to HomeKit but still no dice I even tried 5 different versions from 11 10 and 9 none of the versions made the chimes or TVOS work

**Comment by dazza120** [comment]
Hi no this is the only error I have today BridgeRingERRORFailed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
But I can view from HomeKit this is exactly the problem before with the software I could ding and see it on hoobs but now no motion or ding is showing on hoobs logs. But I do receive all of this on the ring app that’s why it’s been driving me insane because it sending out the commands but for some reason hoobs isn’t getting it and I’ve even taken polling to 1ms to see if it was a polling issue

**Comment by dazza120** [comment]
@dgreif any idea why it doesn’t like me! I’ve tried everything I know of to get it working

**Comment by dazza120** [comment]
Ok I’ll see how to update hoobs to the latest node

**Comment by dazza120** [comment]
Hi the  latest node  just messes hoobs up lost terminal had to reinstall hoobs, deleted all the devices from ring and then made sure this war the first thing in the ring account but it still doesn't not work. here is what i got when i first booted it.

16/06/2023, 13:27:24Ring Bridge starting
16/06/2023, 13:27:52Ring BridgeLoaded plugin 'homebridge-ring'
16/06/2023, 13:27:52Ring BridgeLoading 1 platforms...
16/06/2023, 13:27:52Ring BridgeRingWARNINGPlugin is not configured. Visit https://github.com/dgreif/ring/tree/main/packages/homebridge-ring#homebridge-configuration for more information.
16/06/2023, 13:27:53Ring BridgeBridge is running on port XXXXX.
16/06/2023, 13:28:12Ring BridgeConfiguration change
16/06/2023, 13:28:12ringbridge stopping
16/06/2023, 13:28:18Ring Bridge starting
16/06/2023, 13:28:26Ring BridgeLoaded plugin 'homebridge-ring'
16/06/2023, 13:28:26Ring BridgeLoading 1 platforms...
16/06/2023, 13:28:26Ring BridgeBridge is running on port XXXXX.
16/06/2023, 13:28:27Ring BridgeRingFound the following locations:
16/06/2023, 13:28:27Ring BridgeRing  locationId: XXXXXXXXXXXXXX
16/06/2023, 13:28:28Ring BridgeRingERROR404 from endpoint https://api.ring.com/clients_api/doorbots/1199401/subscribe
16/06/2023, 13:28:28Ring BridgeRingERRORSession hardware_id not found.  Creating a new session and trying again.
16/06/2023, 13:28:28Ring BridgeRingERROR404 from endpoint https://api.ring.com/clients_api/doorbots/1199401/motions_subscribe
16/06/2023, 13:28:28Ring BridgeRingERRORSession hardware_id not found.  Creating a new session and trying again.
16/06/2023, 13:28:28Ring BridgeRingConfiguring 1 cameras and 1 devices for location "XXXXXXXXXJ UK" - locationId: XXXXXXXXXX
16/06/2023, 13:28:28Ring BridgeRingAdding new accessory -XXXX-XXXX-XXXXXXXXXX  Front Door
16/06/2023, 13:28:28Ring BridgeConfiguration change
16/06/2023, 13:28:31Ring BridgeConfiguration change
16/06/2023, 13:28:35ringbridge stopping
16/06/2023, 13:28:40Ring Bridge starting
16/06/2023, 13:28:48Ring BridgeLoaded plugin 'homebridge-ring'
16/06/2023, 13:28:48Ring BridgeLoaded plugin 'homebridge-ring'
16/06/2023, 13:28:48Ring BridgeLoading 1 platforms...
16/06/2023, 13:28:48Ring BridgeLoading 1 platforms...
16/06/2023, 13:28:48Ring BridgeRingConfiguring cached accessory 52be6a00-XXXX-43f4-XXXX-XXXXXXXXXX Front Door
16/06/2023, 13:28:48Ring BridgeRingConfiguring cached accessory 52be6a00-XXXX-43f4-XXXX-XXXXXXXXXX Front Door
16/06/2023, 13:28:48Ring BridgeBridge is running on port 51836.
16/06/2023, 13:28:48Ring BridgeBridge is running on port 51836.
16/06/2023, 13:28:50Ring BridgeRingFound the following locations:
16/06/2023, 13:28:50Ring BridgeRingFound the following locations:
16/06/2023, 13:28:50Ring BridgeRing  locationId: gcpqwq-l0jj-0 - 69 Ingram Ave, Aylesbury HP21 9DJ, UK
16/06/2023, 13:28:50Ring BridgeRing  locationId: gcpqwq-l0jj-0 - 69 Ingram Ave, Aylesbury HP21 9DJ, UK
16/06/2023, 13:28:50Ring BridgeRingConfiguring 1 cameras and 1 devices for location "XXXXXXXXXXXX, UK" - locationId: XXXXXXXXXX
16/06/2023, 13:28:50Ring BridgeRingConfiguring 1 cameras and 1 devices for location "XXXXXXXXXXXX, UK" - locationId: XXXXXXXXXX
16/06/2023, 13:28:50Ring BridgeRingPruning unused service
16/06/2023, 13:28:50Ring BridgeRingPruning unused service
16/06/2023, 13:28:50Ring BridgeConfiguration change
16/06/2023, 13:28:50Ring BridgeConfiguration change

**Comment by dazza120** [comment]
Well i installed in on my unraid via a docker. I installed home bridge which gave the latest home bridge 1.6.1 and the node 
Up To Date 18.13.0
It still fails to ring and notify you on apple tv or via HomePods. the logs still don't show any polling via the log when the butt is pressed also all the ring registration has been deleted fo clean install

Homebridge v1.6.1 (HAP v0.11.1) (Homebridge B246) is running on port 51637.
[6/16/2023, 2:53:37 PM] [Ring] Found the following locations:
[6/16/2023, 2:53:37 PM] [Ring]   locationId: XXXXXXXXXXXXXXXXXXXX
[6/16/2023, 2:53:37 PM] [Ring] 404 from endpoint https://api.ring.com/clients_api/doorbots/1199401/motions_subscribe
[6/16/2023, 2:53:37 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[6/16/2023, 2:53:37 PM] [Ring] 404 from endpoint https://api.ring.com/clients_api/doorbots/1199401/subscribe
[6/16/2023, 2:53:37 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[6/16/2023, 2:53:37 PM] [Ring] Configuring 1 cameras and 1 devices for location "XXXXXXXxXXXXXXXXXXXXX
[6/16/2023, 2:53:37 PM] [Ring] Adding new accessory XXXXXXXXXXXXXXXXXXX1 lpd_v1 Front Door
[6/16/2023, 2:54:07 PM] [Ring] Preparing Live Stream for Front Door
[6/16/2023, 2:54:07 PM] [Ring] Stream Prepared for Front Door (0.52s)
[6/16/2023, 2:54:07 PM] [Ring] Activating stream for Front Door (0.796s)
[6/16/2023, 2:54:08 PM] [Ring] iceConnectionStateChange: completed
[6/16/2023, 2:54:08 PM] [Ring] connectionStateChange: connecting
[6/16/2023, 2:54:08 PM] [Ring] iceConnectionStateChange: new
[6/16/2023, 2:54:08 PM] [Ring] iceConnectionStateChange: checking
[6/16/2023, 2:54:08 PM] [Ring] Activating Session
[6/16/2023, 2:54:08 PM] [Ring] Streaming active for Front Door (1.192s)
[6/16/2023, 2:54:08 PM] [Ring] iceConnectionStateChange: new
[6/16/2023, 2:54:08 PM] [Ring] iceConnectionStateChange: connected
[6/16/2023, 2:54:08 PM] [Ring] connectionStateChange: connected
[6/16/2023, 2:54:08 PM] [Ring] Received stream data from Front Door (1.425s)
[6/16/2023, 2:54:12 PM] [Ring] Stopped Live Stream for Front Door
[6/16/2023, 2:54:12 PM] [Ring] connectionStateChange: closed
[6/16/2023, 2:54:12 PM] [Ring] iceConnectionStateChange: closed
[6/16/2023, 2:54:30 PM] [Ring] Preparing Live Stream for Front Door
[6/16/2023, 2:54:30 PM] [Ring] Stream Prepared for Front Door (0.507s)
[6/16/2023, 2:54:31 PM] [Ring] Activating stream for Front Door (0.973s)

**Comment by dazza120** [comment]
Homekit completley reset via apples HomeKit profile tool and still no notifications only taken 5 hours to add most of the devices back. This is soo annoying

**Comment by tsightler** [comment]
I think it's pretty clear that HomeKit wouldn't be the issue if you are not seeing events in the ring-homebridge log.  Looking at the logs you posted those 404 errors when attempting to subscribe to the device motion events seem pretty telling, do you see those messages every time you restart ring-homebridge?

Also, are you definitely using the primary Ring account for login?  I might suggest deleting the ring-homebridge account from Ring Control Center authorized devices, then stopping ring-homebridge, then go into the Ring app, disable motion detection complelely for a minute or so, then re-enable, the re-authenticate with ring-homebridge and see if these 404 errors go away.

I've not done any testing with non-paid accounts, is there any chance they've completely disabled push notifications for non-paying users and are only using polling?  What region are you in?

**Comment by dazza120** [comment]
@tsightler firstly thank you. So ive used a dedicated account and also the primary one without signing in via the ring app i have de- authorised all the associated devices. Right ive  de-authorised all the associated devices. Deleted the ring HomeKit. turned off motion and ring notifications deleted the ring app turned off the phone and rebooted, reinstalled the ring app turned off motion and bell press on the app rebooted my router. Downloaded the app still with ring motion and doorbell press disabled. I have paid for the month just to see if that was the issue but the ring app continued to give notification of motion and doorbell press without subs Im in the UK. Still not working, i have tried everything i can think of Here is my log

linux x64 #2 SMP PREEMPT_DYNAMIC Wed Nov 2 11:54:15 PDT 2022
server version: 0.39.0
plugin version: @scrypted/ring 0.0.110
full
########################
6/20/2023, 9:09:50 PM
########################
node modules /server/volume/plugins/@scrypted/ring/node18-linux-x64-20230608
native dependencies (up to date). got socket.io-client
plugin loaded
discovery failure Error: refresh token, username, and password are missing.
    at Mr.tryLogin (/src/main.ts:128:19)
    at Mr.discoverDevices (/src/main.ts:172:20)
    at new Mr (/src/main.ts:75:14)
    at Object.onLoadZip (/server/node_modules/@scrypted/server/src/plugin/plugin-remote-worker.ts:381:38)
    at Object.loadZip (/server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:660:28)
    at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:747:37)
TypeError: Cannot read properties of undefined (reading 'getAuth')
    at Mr.tryLogin (/src/main.ts:152:53)
    at Object.onPut (/src/main.ts:40:28)
    at t.StorageSettings.putSettingInternal (/src/storage-settings.ts:160:18)
    at t.StorageSettings.putSetting (/src/storage-settings.ts:145:21)
    at Mr.putSetting (/src/main.ts:168:37)
    at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:747:66)
    at RpcPeer.handleMessage (/server/node_modules/@scrypted/server/src/rpc.ts:688:18)
    at process.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-plugin-main.ts:33:47)
    at process.emit (node:events:513:28)
    at process.emit (node:domain:489:12)
unhandledRejection TypeError: Cannot read properties of undefined (reading 'getAuth')
    at Mr.tryLogin (/src/main.ts:152:53)
    at Object.onPut (/src/main.ts:40:28)
    at t.StorageSettings.putSettingInternal (/src/storage-settings.ts:160:18)
    at t.StorageSettings.putSetting (/src/storage-settings.ts:145:21)
    at Mr.putSetting (/src/main.ts:168:37)
    at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:747:66)
    at RpcPeer.handleMessage (/server/node_modules/@scrypted/server/src/rpc.ts:688:18)
    at process.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-plugin-main.ts:33:47)
    at process.emit (node:events:513:28)
    at process.emit (node:domain:489:12)
login success, trying discovery
unhandledRejection TypeError: Cannot read properties of undefined (reading 'getLocations')
    at Mr.discoverDevices (/src/main.ts:174:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Mr.clearTryDiscoverDevices (/src/main.ts:93:52)
login completed successfully with 2 factor code
login success, trying discovery
discovery completed successfully
########################
6/20/2023, 9:15:36 PM
########################
starting/refreshing stream
ring sdp v=0
o=Wantajobinstead? 1529310922 1529310923 IN IP4 
s=Wantajobinstead?
c=IN IP4 46.51.163.160
t=0 0
m=audio 47698 RTP/SAVPF 0
a=rtpmap:0 PCMU/8000
a=rtcp:45384 IN IP4 46.51.163.160
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:ddX9VK8YZ8y6IWHvYcX4RNmKROjxnQyxfszSL+5p
a=ptime:20
m=video 23618 RTP/SAVPF 99
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42801F
a=rtcp:38874 IN IP4 46.51.163.160
a=rtcp-fb:99 nack
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:Be4yoibTlYR//+D7R4RM63J4uLry6auNCbl71Wvu

proposed sdp v=0
o=Wantajobinstead? 1529310922 1529310923 IN IP4
s=Wantajobinstead?
c=IN IP4 127.0.0.1
t=0 0
m=audio 0 RTP/SAVPF 0
a=control:trackID=0
a=rtpmap:0 PCMU/8000
a=rtcp:45384 IN IP4 46.51.163.160
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:ddX9VK8YZ8y6IWHvYcX4RNmKROjxnQyxfszSL+5p
a=ptime:20
m=video 0 RTP/SAVPF 99
a=control:trackID=1
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42801F
a=rtcp:38874 IN IP4 46.51.163.160
a=rtcp-fb:99 nack
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:Be4yoibTlYR//+D7R4RM63J4uLry6auNCbl71Wvu

request headers OPTIONS rtsp://127.0.0.1:35581 RTSP/1.0
CSeq: 0
User-Agent: Scrypted
response headers RTSP/1.0 200 OK
Public: DESCRIBE, OPTIONS, PAUSE, PLAY, SETUP, TEARDOWN, ANNOUNCE, RECORD, GET_PARAMETER
CSeq: 0

request headers DESCRIBE rtsp://127.0.0.1:35581 RTSP/1.0
Accept: application/sdp
CSeq: 1
User-Agent: Scrypted
response headers RTSP/1.0 200 OK
Content-Base: rtsp://127.0.0.1:35581
Content-Type: application/sdp
CSeq: 1
Content-Length: 540

response body v=0
o=Wantajobinstead? 1529310922 1529310923 IN IP4
s=Wantajobinstead?
c=IN IP4 127.0.0.1
t=0 0
m=audio 0 RTP/SAVPF 0
a=control:trackID=0
a=rtpmap:0 PCMU/8000
a=rtcp:45384 IN IP4 46.51.163.160
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:ddX9VK8YZ8y6IWHvYcX4RNmKROjxnQyxfszSL+5p
a=ptime:20
m=video 0 RTP/SAVPF 99
a=control:trackID=1
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42801F
a=rtcp:38874 IN IP4 46.51.163.160
a=rtcp-fb:99 nack
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:Be4yoibTlYR//+D7R4RM63J4uLry6auNCbl71Wvu

request headers SETUP rtsp://127.0.0.1:35581/trackID=0 RTSP/1.0
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
CSeq: 2
User-Agent: Scrypted
response headers RTSP/1.0 200 OK
Session: 5d174132
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
CSeq: 2

request headers SETUP rtsp://127.0.0.1:35581/trackID=1 RTSP/1.0
Transport: RTP/AVP/TCP;unicast;interleaved=2-3
CSeq: 3
User-Agent: Scrypted
Session: 5d174132
response headers RTSP/1.0 200 OK
Session: 5d174132
Transport: RTP/AVP/TCP;unicast;interleaved=2-3
CSeq: 3

request headers PLAY rtsp://127.0.0.1:35581 RTSP/1.0
Range: npt=0.000-
CSeq: 4
User-Agent: Scrypted
Session: 5d174132
response headers RTSP/1.0 200 OK
RTP-Info: url=rtsp://127.0.0.1:35581/trackID=0,url=rtsp://127.0.0.1:35581/trackID=1
Range: npt=now-
Session: 5d174132
CSeq: 4

request headers TEARDOWN rtsp://127.0.0.1:35581 RTSP/1.0
CSeq: 5
User-Agent: Scrypted
Session: 5d174132
response headers RTSP/1.0 200 OK
Session: 5d174132
CSeq: 5

rtsp client ended
stopping ring sip session.
stopping ring sip session.
stopping ring sip session.
starting/refreshing stream
ring sdp v=0
o=Wantajobinstead? 1529310922 1529310923 IN IP4 
s=Wantajobinstead?
c=IN IP4 46.51.163.160
t=0 0
m=audio 40956 RTP/SAVPF 0
a=rtpmap:0 PCMU/8000
a=rtcp:33482 IN IP4 46.51.163.160
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:/bQkmixOFnGEN9OPFpX1a6Defx+OZUDupe9qCIbK
a=ptime:20
m=video 24194 RTP/SAVPF 99
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42801F
a=rtcp:50258 IN IP4 46.51.163.160
a=rtcp-fb:99 nack
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:9Em1gcbzK4RpHq0Rs4rZYnKL3kPDnfcIcRD68I3C

proposed sdp v=0
o=Wantajobinstead? 1529310922 1529310923 IN IP4
s=Wantajobinstead?
c=IN IP4 127.0.0.1
t=0 0
m=audio 0 RTP/SAVPF 0
a=control:trackID=0
a=rtpmap:0 PCMU/8000
a=rtcp:33482 IN IP4 46.51.163.160
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:/bQkmixOFnGEN9OPFpX1a6Defx+OZUDupe9qCIbK
a=ptime:20
m=video 0 RTP/SAVPF 99
a=control:trackID=1
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42801F
a=rtcp:50258 IN IP4 46.51.163.160
a=rtcp-fb:99 nack
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:9Em1gcbzK4RpHq0Rs4rZYnKL3kPDnfcIcRD68I3C

request headers OPTIONS rtsp://127.0.0.1:36291 RTSP/1.0
CSeq: 0
User-Agent: Scrypted
response headers RTSP/1.0 200 OK
Public: DESCRIBE, OPTIONS, PAUSE, PLAY, SETUP, TEARDOWN, ANNOUNCE, RECORD, GET_PARAMETER
CSeq: 0

request headers DESCRIBE rtsp://127.0.0.1:36291 RTSP/1.0
Accept: application/sdp
CSeq: 1
User-Agent: Scrypted
response headers RTSP/1.0 200 OK
Content-Base: rtsp://127.0.0.1:36291
Content-Type: application/sdp
CSeq: 1
Content-Length: 540

response body v=0
o=Wantajobinstead? 1529310922 1529310923 IN IP4
s=Wantajobinstead?
c=IN IP4 127.0.0.1
t=0 0
m=audio 0 RTP/SAVPF 0
a=control:trackID=0
a=rtpmap:0 PCMU/8000
a=rtcp:33482 IN IP4 46.51.163.160
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:/bQkmixOFnGEN9OPFpX1a6Defx+OZUDupe9qCIbK
a=ptime:20
m=video 0 RTP/SAVPF 99
a=control:trackID=1
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42801F
a=rtcp:50258 IN IP4 46.51.163.160
a=rtcp-fb:99 nack
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:9Em1gcbzK4RpHq0Rs4rZYnKL3kPDnfcIcRD68I3C

request headers SETUP rtsp://127.0.0.1:36291/trackID=0 RTSP/1.0
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
CSeq: 2
User-Agent: Scrypted
response headers RTSP/1.0 200 OK
Session: d0f857e6
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
CSeq: 2

request headers SETUP rtsp://127.0.0.1:36291/trackID=1 RTSP/1.0
Transport: RTP/AVP/TCP;unicast;interleaved=2-3
CSeq: 3
User-Agent: Scrypted
Session: d0f857e6
response headers RTSP/1.0 200 OK
Session: d0f857e6
Transport: RTP/AVP/TCP;unicast;interleaved=2-3
CSeq: 3

request headers PLAY rtsp://127.0.0.1:36291 RTSP/1.0
Range: npt=0.000-
CSeq: 4
User-Agent: Scrypted
Session: d0f857e6
response headers RTSP/1.0 200 OK
RTP-Info: url=rtsp://127.0.0.1:36291/trackID=0,url=rtsp://127.0.0.1:36291/trackID=1
Range: npt=now-
Session: d0f857e6
CSeq: 4

request headers TEARDOWN rtsp://127.0.0.1:36291 RTSP/1.0
CSeq: 5
User-Agent: Scrypted
Session: d0f857e6
response headers RTSP/1.0 200 OK
Session: d0f857e6
CSeq: 5

rtsp client ended
stopping ring sip session.
stopping ring sip session.
stopping ring sip session.

**Comment by tsightler** [comment]
That log is from Scrypted, which is an entirely different project.  It does use a significantly modified version of ring-client-api, but it's different enough that you should probably open issues with Scrypted on that projects Github, not here.

If you want help with ring-homebridge you'll need to provide ring-homebridge logs, ideally with a screenshot of the notification from the Ring app with the corresponding logs showing no events during that time with ring-homebridge.

**Comment by dazza120** [comment]
Sorry mate ive lost track ive tried so many hooks to get it to work. thinking it was hoobs ive literally been firming shots in the dark still the same log


 21:52:21Ring BridgeConfiguration change
20/06/2023, 21:52:21ringbridge stopping
20/06/2023, 21:52:26Ring Bridge starting
20/06/2023, 21:52:34Ring BridgeLoaded plugin 'homebridge-ring'
20/06/2023, 21:52:34Ring BridgeLoading 1 platforms...
20/06/2023, 21:52:34Ring BridgeBridge is running on port 51836.
20/06/2023, 21:52:35Ring BridgeRingFound the following locations:
20/06/2023, 21:52:35Ring BridgeRing  locationId: xxxxxxxxxxx, UK
20/06/2023, 21:52:36Ring BridgeRingERROR404 from endpoint https://api.ring.com/clients_api/doorbots/1199401/motions_subscribe
20/06/2023, 21:52:36Ring BridgeRingERRORSession hardware_id not found.  Creating a new session and trying again.
20/06/2023, 21:52:36Ring BridgeRingERROR404 from endpoint https://api.ring.com/clients_api/doorbots/1199401/subscribe
20/06/2023, 21:52:36Ring BridgeRingERRORSession hardware_id not found.  Creating a new session and trying again.
20/06/2023, 21:52:36Ring BridgeRingConfiguring 1 cameras and 1 devices for location "xxxxxxx, UK" - locationId: gcpqwq-l0jj-0
20/06/2023, 21:52:36Ring BridgeRingAdding new accessory 52be6a00-bd6a-43f4-8abb-c3218f009eb1 lpd_v1 Front Door
20/06/2023, 21:52:36Ring BridgeConfiguration change
20/06/2023, 21:52:36Ring BridgeConfiguration change
20/06/2023, 21:52:36ringbridge stopping
20/06/2023, 21:52:41Ring Bridge starting
20/06/2023, 21:52:49Ring BridgeLoaded plugin 'homebridge-ring'
20/06/2023, 21:52:49Ring BridgeLoading 1 platforms...
20/06/2023, 21:52:49Ring BridgeRingConfiguring cached accessory 52be6a00-bd6a-43f4-8abb-c3218f009eb1 Front Door
20/06/2023, 21:52:50Ring BridgeBridge is running on port 51836.
20/06/2023, 21:52:51Ring BridgeRingFound the following locations:
20/06/2023, 21:52:51Ring BridgeRing  locationId: xxxxxxxxxxxx, UK
20/06/2023, 21:52:51Ring BridgeRingConfiguring 1 cameras and 1 devices for location "xxxxxxxxxxx, UK" - locationId: gcpqwq-l0jj-0
20/06/2023, 21:52:51Ring BridgeRingPruning unused service
20/06/2023, 21:52:51Ring BridgeConfiguration change
20/06/2023, 21:52:53Ring BridgeConfiguration change

**Comment by tsightler** [comment]
For me those 404 errors are the clear standout in this log, but I don't have the slightest clue why they would exist.  Those are the endpoints for subscribing to events and 404 basically means they don't exist.  Unfortunately, I don't have any ideas how this could be the case as it's the exact URL used by the Ring app as far as I can tell.

**Comment by dazza120** [comment]
I have no clue either that’s why I paid for the account again to see if that was the issue but I’m loosing the will to live as not being able to hear anyone ring the doorbell is doing in my head. This is why I was thinking of killing it and getting a out of the box HomeKit job, but the annoying thing it’s a really good product but should have come with it natively I don’t know if I’ll ever forgive them for that as that made me pick them when they came out with the Pro.

**Comment by NickRivait** [comment]
I'm also having no notifications / but no errors from Ring in Hoobs

**Comment by dgreif** [comment]
Thanks for the follow up questions and debugging @tsightler!

The 404s in the logs are an expected error the first time you create a Refresh Token and run the plugin with it. A new refresh token does not have an associated "session", so trying to set notification preferences returns a 404 because the _session_ is "not found". The plugin will automatically create a session when this happens, and then it will re-send the notification preference change (`subscribe`). You should _not_ see these errors after you restart your server - if you are, then that would be a big clue!

@dazza120 I'm sorry this has been frustrating and consumed a lot of your time. Notifications are a very tricky piece, and something that Ring has made a lot of changes to recently. We've done our best to make them reliable and consistent, but I understand that some users are still experiencing issues. Hopefully we can get to the bottom of it, but I can't make any promises as every users environment is different.

**Comment by tsightler** [comment]
Ah, I didn't realize that ring-homebridge produces those errors during startup as I don't see the same behavior in ring-mqtt.

One of the most confusing things is that @dazza120 appeared to try Scrypted but it still didn't work, but I was pretty sure Scrypted re-implemented polling for events in the latest versions of the plugin so that would imply the issue is not related to push notification changes.  That being said, I don't follow Scrypted development closely.

If someone that is having issues would be willing to share their camera with my account I'd be open to testing if it's related somehow to the account vs the device.

**Comment by dgreif** [comment]
Great point @tsightler, last time I checked Scrypted was still using polling. I'm not sure if they pulled in any of the recent session changes needed for the data residency issues outside the US (this user appears to be in the UK), but that shouldn't make a difference within the first 24 hours.

@dazza120 have you followed the steps in https://github.com/dgreif/ring/wiki/Notification-Troubleshooting? In particular, deleting all your existing authorized devices before creating a new Refresh Token?

**Comment by dazza120** [comment]
@dgreif yes unfortunately it’s to of no avail, none of them seem to give any notification apart from the ring app itself

**Comment by dgreif** [comment]
@dazza120 sorry to hear that. Can you confirm whether or not you see the 404 errors in your logs after restarting your server? Or is it only on the first start after creating a Refresh Token?

**Comment by dazza120** [comment]
@dgreif hi thanks for the reply no I don’t see that error again here is that log

21/06/2023, 19:10:20ringbridge stopping
21/06/2023, 19:10:26Ring Bridge starting
21/06/2023, 19:10:34Ring BridgeLoaded plugin 'homebridge-ring'
21/06/2023, 19:10:34Ring BridgeLoading 1 platforms...
21/06/2023, 19:10:34Ring BridgeRingConfiguring cached accessory 52be6a00-bd6a-43f4-8abb-c3218f009eb1 Front Door
21/06/2023, 19:10:34Ring BridgeBridge is running on port 51836.
21/06/2023, 19:10:35Ring BridgeRingFound the following locations:
21/06/2023, 19:10:35Ring BridgeRing  locationId: xxxxxx
21/06/2023, 19:10:36Ring BridgeRingConfiguring 1 cameras and 1 devices for location "xxxxxxxx " - locationId: xxxxxxx
21/06/2023, 19:10:36Ring BridgeConfiguration change

**Comment by jmichas** [comment]
So, I was not getting TVOS notifications, what fixed it for me was following the wiki on notification troubleshooting. I guess I had a lot of authorized devices in my ring account. I removed most of them, then a created a new refresh token and apple tv notifications began working again. The cameras were always available on apple tv in home kit and streamed fine, only notifications stopped working.

**Comment by NickRivait** [comment]
Same Thank you,Nick ***@***.*** Jul 14, 2023, at 6:48 PM, jmichas ***@***.***> wrote:﻿
So, I was not getting TVOS notifications, what fixed it for me was following the wiki on notification troubleshooting. I guess I had a lot of authorized devices in my ring account. I removed most of them, then a created a new refresh token and apple tv notifications began working again. The cameras were always available on apple tv in home kit and streamed fine, only notifications stopped working.

**Comment by jmichas** [comment]
Also, as explained earlier, the initial restart of homebridge displayed the 404 errors for subscribing to motion in the logs AND on the Ring site, the device displayed as "Device name not found". After second restart, no 404 errors and Ring displayed the device as "homebridge-ring".

**Comment by ggogins** [comment]
Thanks @jmichas !  This also worked for me.  Removing unnecessary clients from Authorized Client Devices list, unlinking Ring account from plugin, rebooting, then re adding the Ring account, fixed the notifications.
Note that I experienced the notification issue and I always had a paid Ring account.

**Comment by 7onnie** [comment]
I have this as an recurring issue...
It just stops working after some time and i have to remove the device in the ring app and regenerate the token... but there is always only 1 device in my account.
Opening the door through apple home works fine. Just the ding notifications do stop working. Havent figured out when and why they stop working... i often notice it after a few weeks, but it may even have stopped working on the next day.

**Comment by dgreif** [comment]
For anyone landing on this issue, please follow the steps in sorry to hear you are having issues. We released a fix for notifications in v11.8.0, but you may still have to follow the steps in [this guide](https://github.com/dgreif/ring/wiki/Notification-Troubleshooting) to get them fully functionally again. Mind giving that a try?. We believe notifications are working again, but a lot of users may have lingering sessions on their account which need to be cleared out.
