### ISSUE TITLE
Live Stream never starts

### ISSUE THREAD

**Issue by mcritter86** [dgreif/ring#1246]
### Streaming Issue

When I try to start a live stream in the Apple Home app it just sits there spinning.  Below is what the HOOBS log says

### Proposed Solution

I don't know

### Environment

HOOBS

### What operating system are you on?

Mac

### Relevant log output

```shell
6/17/2023, 11:12:49 AMRing BridgeRingPreparing Live Stream for Front Door
6/17/2023, 11:12:49 AMRing BridgeRingStream Prepared for Front Door (0.549s)
6/17/2023, 11:12:49 AMRing BridgeRingActivating stream for Front Door (0.668s)
6/17/2023, 11:12:50 AMRing BridgeRingiceConnectionStateChange: completed
6/17/2023, 11:12:50 AMRing BridgeRingconnectionStateChange: connecting
6/17/2023, 11:12:50 AMRing BridgeRingiceConnectionStateChange: new
6/17/2023, 11:12:50 AMRing BridgeRingiceConnectionStateChange: checking
6/17/2023, 11:12:50 AMRing BridgeRingActivating Session
6/17/2023, 11:12:51 AMRing BridgeRingStreaming active for Front Door (2.048s)
6/17/2023, 11:12:51 AMRing BridgeRingiceConnectionStateChange: new
6/17/2023, 11:12:51 AMRing BridgeRingiceConnectionStateChange: connected
6/17/2023, 11:12:52 AMRing BridgeRingconnectionStateChange: connected
6/17/2023, 11:12:52 AMRing BridgeRingReceived stream data from Front Door (2.919s)
6/17/2023, 11:13:02 AMRing BridgeRingStopped Live Stream for Front Door
```

### Honesty Time

- [X] I swear this is worth your time!

**Comment by dgreif** [comment]
Which version of HOOBS are you on?

**Comment by mcritter86** [comment]
HOOBS v 4.3.0
Ring v 11.8.0

**Comment by toogle9** [comment]
Today I unbridged all three of the cameras (Ring Video Doorbell Pro 2, and 2 Ring Floodlight Cam Wired Pros) hoping that would make a difference, but unfortunately it does not appear to have.  I think the snapshots in the Home app may be ever so slightly quicker, but starting a stream on any of them fails 9+ times out of 10.  Every so often a stream will start, but it's very very rare.  Homebridge logs shows

[Ring] Preparing Live Stream for Front Door
[Ring] Stream Prepared for Front Door (0.343s)
[Ring] Activating stream for Front Door (0.482s)
[Ring] iceConnectionStateChange: completed
[Ring] connectionStateChange: connecting
[Ring] iceConnectionStateChange: new
[Ring] iceConnectionStateChange: checking
[Ring] Activating Session
[Ring] Streaming active for Front Door (1.465s)
[Ring] iceConnectionStateChange: new
[Ring] iceConnectionStateChange: connected
[Ring] iceConnectionStateChange: new
[Ring] connectionStateChange: disconnected
[Ring] iceConnectionStateChange: disconnected
[Ring] connectionStateChange: closed
[Ring] iceConnectionStateChange: closed
[Ring] Stopped Live Stream for Front Door

Running Homebridge 1.6.1 (oznu/homebridge:lates) on Synology Docker, with homebridge-ring plugin 11.8.0.  Prior to unbridging the cameras, I did generate a new refresh token to get a fresh login.  If I let a stream attempt continue it will eventually timeout with "No Response.  This camera is not responding".  At that point snapshots for that device no longer work until I close and reopen the Home app.  If I close the stream attempt before it fails, snapshots continue to work.   

Please advise if there are any other suggestions I can try.  Thank you.

**Comment by dgreif** [comment]
v12 has a bunch of streaming improvements. Please give it a try and open a new issue if you are still having problems
