### ISSUE TITLE
Plugin bumping Levinton Devices

### ISSUE THREAD

**Issue by lfiocco** [dgreif/ring#125]
Hello I just finished installing the plugin, on a fresh Ubuntu / Homebridge / VM machine. On the ring side everything working minus the live feed, I know how to fix this this but choose not to. I am ok with snap shots only. I notice whenever I boot the ring server, I loose connection to only Levinton dimmers and switches. Homebridge is the latest with the ports line in the json file.

Why only Levinton HomeKit devices? The devices ping, but go no responds in the home app. I rebooted everything including the Apple TV, btw iOS and TVOS are all 12.4.1

**Comment by dgreif** [comment]
I really can't say why it would do that to the Leviton switches.  HomeKit can be weird some times, but it shouldn't be due to anything I'm doing in the plugin.   Sorry you are having that issue, but I don't think there is anything I can do to help

**Comment by lfiocco** [comment]
I did some troubleshooting on this. I changed all the ports for all my Homebridge servers so they don't bump into each other. I got the same result. I even installed the plug in on an existing server and it still killed the Levinton devices. I have 3, and all three keep going offline when I load the ring plugin.

**Comment by dgreif** [comment]
Again, I'm really sorry to hear you are having this issue.  I can't think of anything going on in the plugin that would cause this to happen.  If you are able to pin something down in the code, I would be happy to take a PR.  Otherwise, there is nothing I can do to help you since I can't reproduce the issue myself
