### ISSUE TITLE
Suggestion for your documentation

### ISSUE THREAD

**Issue by jmporter34** [dgreif/ring#1251]
### Description

Regarding https://github.com/dgreif/ring/wiki/Refresh-Tokens
It states "The Easy Route
Install [homebridge-config-ui-x](https://www.npmjs.com/package/homebridge-config-ui-x), which will give you a UI through which you can enter your Ring credentials to get logged in. No command line required".

Installing config-ui-x is necessary, but not the complete solution.
It would be helpful if the doc mentioned that, after installing config-ui-x (or verifying that it's already installed), you have to click "Plugins" in the top menu, then click "Settings" in the Homebridge Ring area of the Plugins page.  I'm sure this is probably obvious after you've refreshed your token once or twice, but it took me a while to figure it out without those extra details being included in the doc.

Thanks again for making your plugin available, it lets me access all my Ring devices in Home Assistant, which they wouldn't be otherwise.

### Proposed solution

Please add the extra details.

**Comment by dgreif** [comment]
Thanks for the suggestion! Will take this into consideration 😄
