### ISSUE TITLE
This camera is in "Off" mode and cannot stream or record.

### ISSUE THREAD

**Issue by fancypants66** [dgreif/ring#1257]
### Streaming Issue

Added Ring Indoor Cam (2nd Gen) and camera is displaying as "Off" in HomeKit. Tapping for Live View displays the error "This camera is in Off mode and cannot stream or record". At this point I'm unsure if this is a (lack of) legacy streaming mode, or if it has to do with the new HomeKit Secure Video settings, or something else? Apologies in advance as I'm sure this has come up before but I was just unable to find a solution...

Notes:
- homebridge-ring v11.8.0
- Ring cameras are all set up in unbridged mode.
- 11 other Ring devices (older) are streaming without issue.
- Able to stream/view Indoor Cam in the Ring app and Ring website.
- Ring Indoor Cam (2nd Gen) has a privacy cover, it has been removed and verified camera in the "on" position.
- Mode Settings for Cameras are disabled in the Ring app.
- This is the first Ring camera I've added since upgrading to the new Home architecture (~April '23).
- Multiple homekit and hub reboots. Removed and Re-added Indoor Cam without any change.
- No logs in Homebridge as it's displaying as "Off" in the Home Cameras view and Home isn't attempting to start a stream.

### Proposed Solution

_I think it may have to do with the new Home architecture, so hoping there's a way to expose or set HomeKit video settings/recording options through this plugin?_
**EDIT: Issue appears to be specific to the Ring Indoor Cam (2nd Gen) and not with the new Home architecture (above)**

### Environment

Homebridge 1.6.1

### What operating system are you on?

Other

### Relevant log output

```shell
Synology DSM
```

### Honesty Time

- [X] I swear this is worth your time!

**Comment by fancypants66** [comment]
**_Update_**. Just added a Ring Indoor Cam (1st Gen) at it is working as expected. So the issue above appears to be specific to the Ring Indoor Cam (2nd Gen) - maybe something with the privacy cover, or maybe just the newer hardware? Would be interested if anyone else has gotten a Ring Indoor Cam (2nd Gen) to work.

**Comment by dgreif** [comment]
Thanks for the additional info about another camera working since your original issue. Would you mind posting a screenshot of the view when you see the "This camera is in Off mode and cannot stream or record" message? Curious to see if that's coming from HomeKit or from this project.

It's very possible that the camera has it's data set up in a new way, possibly because of the privacy cover. Running the [Data Discovery](https://github.com/dgreif/ring/wiki/Data-Discovery) tool and posting the results here would help diagnose if that's the case.

**Comment by arturlukosek** [comment]
I have noticed same issue here since update the plugin to version 12 and unbridge cameras. 
got two same cameras connected (Stick Up Cam Plug-in (3rd Gen)).One works fine but the other one has off status. I was looking in the ring app if there are any settings but without any results.

**Comment by arturlukosek** [comment]
@fancypants66 have you managed to get your camera streaming working?

**Comment by tsightler** [comment]
@arturlukosek Are you on using beta iOS/tvOS?  This issue just started cropping up on several homebridge camera projects out.  The message itself is from Homekit, not from anything in the project.  So far I haven't seen any fix for it except to remove and re-add the camera.

**Comment by arturlukosek** [comment]
@tsightler I don't use any beta. Does the re-adding camera solve the issue?

**Comment by arturlukosek** [comment]
@tsightler would you share would you mean by re adding the camera (ring or HB)? What I did so far is removed the camera from ring app and added again as same name (i kept recording data during this process) than I restarted the homebridge but still the same. I will try to remove the camera from HB and add again. In my case it is difficult as camera is more than 600km from the HB. Can't do both at the same time.
