### ISSUE TITLE
Support other audio encoder?

### ISSUE THREAD

**Issue by malmentm** [dgreif/ring#126]
I use the https://github.com/oznu/docker-homebridge and even though it supports ffmpeg it does not have the libfdk_acc codec. Is it possible to use another?

**Comment by dgreif** [comment]
The only other option with HomeKit is Opus. It's more widely supported by ffmpeg builds, but unfortunately I could not get it to work _well_ with this plugin.  It worked, but the audio would play for 1 second, then cut out for 1 second, then play, then cut out...trust me, I really didn't want to use libfdk_aac but there is no other option at this point.

If there are any audio encoding experts that see this, please let me know if you can help me tweak the Opus set up.

**Comment by malmentm** [comment]
@dgreif I understand :)
