### ISSUE TITLE
live streaming in Python?

### ISSUE THREAD

**Issue by jeroenterheerdt** [dgreif/ring#127]
Newbie here - I am trying to get the stream-example to work but it gets stuck after 'Starting Video...'. I do not see any output in the output directory.

The whole reason I am doing this is trying to find a way to expand the Home Assistant component for Ring with the livestreaming capability. Ideally I would like to implement this part of the API in Python - but for now I am first trying to get the example to work...
How can I debug this?

**Comment by jeroenterheerdt** [comment]
I got the example to work - looking for any help / suggestions on how to integrate this to Home Assistant which is based on Python.

**Comment by dgreif** [comment]
I've thought about home assistant a little bit, but I'm not very familiar with Python.  You will need to find a SIP library (if there is one), and then copy over the logic that I have in place for setting up the sip call.  I'm not sure how Home Assistant works with video, so you may or may not need to transcode the audio and video RTP before passing it to HA (which is what I use `ffmpeg` for, specifically just transcoding audio for HomeKit).

**Comment by jeroenterheerdt** [comment]
right - I am trying right now to do exactly that (unfortunately there is no sip library that I could find).

**Comment by dgreif** [comment]
If there isn't a SIP library, you can do it yourself using a TCP connection.  You just need to keep track of SIP state and building proper responses, which is what the node sip library is doing for me.  As for getting help, you best bet is going to be asking on the python-ring-doorbell repo.  Most of my users are using homebridge and don't have much/any programming experience.  I wish you luck!

**Comment by jeroenterheerdt** [comment]
thanks - I can work on the Python no problem - I am having trouble with the node bit :) trying to understand your code. All these things with Subject / BehaviorSubject, Promises... all new to me. where I am stuck is in getSipOptions - there you make a empty POST call to the vod endpoint and somehow you get SIP ports from it, but you do not do anything with the (empty) response from the POST to the vod endpoint. Can you explain how that part works?

**Comment by jeroenterheerdt** [comment]
right - I was trying to do that but keep getting empty responses from `dings\active`. Where in your code is the actual call being made? I would like to see which exact endpoint is being called and what the result is.

**Comment by dgreif** [comment]
https://github.com/dgreif/ring/blob/25c77105fea32c68adfb9170c4b48a4debbe0dcb/api/api.ts#L62 is where they get fetched. You need to create a session and include the hardware_id in the headers, which tells the ring servers which device wants dings so it knows which ones you have already fetched. I think the session stuff is already in the python library so you can look there, or in api/rest-client.ts in my repo. Having a session and including the harware_id header is critical and took me a long time to figure out.

**Comment by jeroenterheerdt** [comment]
Thanks, I will investigate further. Thanks for your help. I was able to get sip info now but I had to request the json for live streaming first through the Python library I am extending. Thanks for all your help and hard work so far! I will report back.

**Comment by jeroenterheerdt** [comment]
Hi @dgreif - I was able to make a quick and dirty solution wrapping your code in a Python call. I was not able to re-write everything you did in Python as it turned out to be quite hard. This hacky solution works, hopefully someone else will have time and skills to turn it into something pretty.
https://github.com/tchellomello/python-ring-doorbell/pull/133

**Comment by dgreif** [comment]
Just looked it over, glad you got something to work without a full rewrite!  Looks like you still have a ways to go before it could be used for live streaming in home assistant, but you are definitely getting closer.  I'm going to close this issue out since you have something working now 🏆

**Comment by jeroenterheerdt** [comment]
yep - thanks a lot for your help!
