### ISSUE TITLE
Failed to subscribe to motion events

### ISSUE THREAD

**Issue by lolgas** [dgreif/ring#1276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

On a fresh install of homebridge-ring, on restart it is unable to subscribe to motion events as noted in the homebridge logs:

> `[7/30/2023, 11:37:30 AM] [Ring] 404 from endpoint https://api.ring.com/clients_api/doorbots/313207225/motions_subscribe
>
> [7/30/2023, 11:37:30 AM] [Ring] Failed to subscribe Indoor Test to motion events
>
> [7/30/2023, 11:37:30 AM] [Ring] Error: Not found with response: {"status":404,"error":"Not Found"}
>     at RingRestClient.request (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:330:23)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)`

### Expected behavior

The api key is subscribed to motion events and user would subsequently receive events through homekit if subscribed.

### Homebridge Ring Config

```shell
{
    "refreshToken": "removed",
    "platform": "Ring"
}
```

### OS

Ubuntu LXC on Proxmox 7

### Node.js Version

v18.16.0

### NPM Version

Not sure where to find this

### Homebridge/HOOBs Version

v1.6.1

### Homebridge Ring Plugin Version

v11.8.1

### Operating System

Ubuntu LXC on Proxmox 7

**Comment by tsightler** [comment]
The 404 errors are normal on initial refresh token generation.  Do you still see those on subsequent reboots?  Can you please provide more complete logs?

**Comment by lolgas** [comment]
Very interesting.. I am pretty sure I was seeing it on subsequent reboots, but now it is not showing the error.
I am now getting some notifications from homekit for motion - but not every single time as I am from the Ring app. Is there a cooldown or limitation in push frequency from homekit that you know of?

**Comment by tsightler** [comment]
Can you provide an example of such an issue with corresponding logs and events in Ring event history?
