### ISSUE TITLE
Invalid Refresh Token

### ISSUE THREAD

**Issue by WillKrzy** [dgreif/ring#1277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I run  `npx -p ring-client-api ring-auth-cli` and get back  a token. I then try to use said token in a custom  javascript prgrram running locally. then this happens. This has been happening since 7/28 consistently
`
 Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/home/will/RING/node_modules/ring-client-api/lib/rest-client.js:140:15)
    at RingRestClient.getAuth (/home/will/RING/node_modules/ring-client-api/lib/rest-client.js:143:32)
    at RingRestClient.getAuth (/home/will/RING/node_modules/ring-client-api/lib/rest-client.js:184:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

I expect a valid refresh token

### To Reproduce

create refresh token. Try to use token. fail

### Expected behavior

Login success

### Relevant log output

```shell
Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/home/will/RING/node_modules/ring-client-api/lib/rest-client.js:140:15)
    at RingRestClient.getAuth (/home/will/RING/node_modules/ring-client-api/lib/rest-client.js:143:32)
    at RingRestClient.getAuth (/home/will/RING/node_modules/ring-client-api/lib/rest-client.js:184:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Additional context

I can see the device as authorized in the ring APP

### OS

Debian

### Node.js Version

v16.20.1

### NPM Version

8.19.4

### ring-client-api

^11.8.1

### Operating System

Debian

**Comment by tsightler** [comment]
I just walked through this process with no issues using a very simple test program that does nothing but connect and list locations, no issues.  You will likely need to post the code you are testing to have any hope of resolving the issue.

**Comment by WillKrzy** [comment]
my env file was named ring.env. This used to work by default, I suppose some change happened and it know exclusively reads .env file by default. It may be helpful to clarify this in documentation for others.

**Comment by tsightler** [comment]
I'm afraid I have no idea what ring.env is.  I'm not aware that ring-client-api will read any file by default, if you want to read in a configuration, your custom code will need to do it as the API does not maintain updated tokens.  I could not find any examples that use ring.env in this repository.  If you can help me better understand what you are referring to I'm happy to update anything that is unclear.

**Comment by tsightler** [comment]
Ah, maybe you are referring to API example which uses dotenv to read configuration from .env files?  I'm not aware of any changes there though, that file hasn't changed for 8 months.

**Comment by dgreif** [comment]
I did update the version of dotenv over the weekend, so it's possible there was a change within that dependency which caused it to no longer read from any random `*.env` and instead read only `.env` files. As far as I know, it's only _supposed_ to ready `.env` so maybe they just fixed a bug. Either way, I'm glad you found a solution and sorry for the headache!
