### ISSUE TITLE
Failed to reach ring server

### ISSUE THREAD

**Issue by tr1um9h** [dgreif/ring#1288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

My homebridge logo is full of failed to reach ring server I restarted the server and even refreshing token 

### Expected behavior

Reaches ring server 

### Screenshots

![IMG_4635](https://github.com/dgreif/ring/assets/55196968/c8e654bd-3bec-4174-aa70-127e34a52df5)

### Homebridge Ring Config

```shell
{
            "refreshToken": "",
            "unbridgeCameras": true,
            "hideCameraSirenSwitch": true,
            "hideAlarmSirenSwitch": true,
            "debug": false,
            "locationIds": [
                ""
            ],
            "platform": "Ring"
        }
```

### OS

Rasbian

### Node.js Version

18.16.1

### NPM Version

9.7.2

### Homebridge/HOOBs Version

v1.6.1

### Homebridge Ring Plugin Version

v11.8.1

### Operating System

Rasbian

**Comment by databoy01** [comment]
Have you tried deleting the plug in and reinstalling it and getting a new token?

**Comment by doncarajo** [comment]
Same issue. I recently updated nodejs, is that the issue?

**Comment by dgreif** [comment]
@tr1um9h these errors pop up in the logs when the plugin is unable to reach the Ring servers. This generally indicates an issue with your local network or internet connection. From the logs you posted, it's happening sporadically (several minutes between most of the occurrences), which further supports this idea. 

In general, you can just ignore these logs. They are here to let you know that requests are failing, but they don't actually need to be addressed unless the plugin fully stops functioning.
