### ISSUE TITLE
Disable light on Ring Alarm

### ISSUE THREAD

**Issue by burtherman** [dgreif/ring#1289]
### Description

Option to hide the Ring Alarm Pro being shown as a light. Not much use controlling the LED on the alarm box

**Comment by smockle** [comment]
You can use the [`hideDeviceIds` option](https://github.com/dgreif/ring/tree/main/packages/homebridge-ring#optional-parameters) to prevent the Ring Alarm Base Station from appearing in HomeKit. When you start Homebridge, the relevant device identifier is logged—look lines with `hub.redsky` or `hub.kili`.

You can still control the alarm from the Home app if you hide the base station. The alarm has a separate device type: `security-panel`.

**Comment by dgreif** [comment]
I agree with @smockle, your best bet is to simply hide the device (great idea!). I've tried to avoid adding new options for simple "hide this thing" requests as I don't want the list of options for the plugin to grow out of control. Let us know if you run into any issues with this approach.

**Comment by burtherman** [comment]
Ah ok thanks will look into that - obviously wouldn’t want to hide the actual alarm switch but sounds good if that won’t happen
