### ISSUE TITLE
Homebridge-ring upload screenshots Google drive

### ISSUE THREAD

**Issue by jreyn88** [dgreif/ring#130]
Is it possible to upload screenshots to Google drive much like homebridge-camera-ffmpeg?

**Comment by dgreif** [comment]
It's definitely possible, but wasn't something I had thought to do yet.  Do you have a specific use case for it?

**Comment by nicoh88** [comment]
+1

**Comment by dgreif** [comment]
Closing since there hasn't been any additional interest in this feature.  Feel free to comment if you are interested.

**Comment by woodgieboodgie** [comment]
would be interested indeed. pls consider adding as option as camera-ffmpeg makes it very simple to keep and access the pictures.. rather than them just appearing on 'notifications' for a few seconds.

**Comment by noahneumark** [comment]
> would be interested indeed. pls consider adding as option as camera-ffmpeg makes it very simple to keep and access the pictures.. rather than them just appearing on 'notifications' for a few seconds.

Yeah, it would be great to include snapshot upload.

**Comment by Orangetilt** [comment]
This was literally one of the first things I tried setting up after getting my ring working.
Please make it happen! A simple IFTTT integration would allow this quite easily.

**Comment by dgreif** [comment]
@Orangetilt see #290.  It's possible with Node-Red, so I don't plan to add it directly to the plugin.
