### ISSUE TITLE
Version 12.0.0 and 12.0.1 not functioning with iOS17

### ISSUE THREAD

**Issue by gregpa** [dgreif/ring#1317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I had an issue on 12.0.0 where none of my devices were coming through to the Home App.  I see them and can control them on the HOOBS accessory page, but they are not transferring to the app.  I tried updating to 12.0.1 and same issue. I am holding off trying to delete the bridge and re-install it as I have a bunch of automations, but will do so if there is no other option. Looking for advice. 

### Expected behavior

Use on Home App.

### Homebridge Ring Config

```shell
none available
```

### OS

iOS17

### Node.js Version

?

### NPM Version

?

### Homebridge/HOOBs Version

4.3.0

### Homebridge Ring Plugin Version

12.0.1

### Operating System

windows

**Comment by gregpa** [comment]
Had to delete the bridge and re-add it  (and do all my stupid automations again..) it came back

**Comment by dgreif** [comment]
Going to close this as it sounds like this has been resolved by re-adding the bridge
