### ISSUE TITLE
Missing method to query alarm state?

### ISSUE THREAD

**Issue by mikefelix** [dgreif/ring#132]
I've been trying to use your library to automate arming and disarming my Ring security alarm. I was happy to find:

location.armHome()
location.armAway()
location.disarm()

These are working! But am I missing something or is there no way to query the current state of the alarm in a location? I've looked around in the code and don't seem to see anything like that. Is it an oversight or is it not possible with their API?

**Comment by dgreif** [comment]
You can currently do something like this: 

```typescript
const securityPanel = await location.getSecurityPanel(),
    currentAlarmMode = securityPanel.data.mode

// currentAlarmMode will be 'all' | 'some' | 'none'
```

I'll add a `getAlarmMode` method to the location when I get a chance, that would definitely be helpful 😄

**Comment by dgreif** [comment]
ok, added `location.getAlarmMode()` in v`5.7.0` 😁

**Comment by mikefelix** [comment]
Awesome, thanks!
