### ISSUE TITLE
Intercom: unlock function returns 404

### ISSUE THREAD

**Issue by koichirose** [dgreif/ring#1320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Since a couple days ago, the [unlock function ](https://github.com/dgreif/ring/blob/main/packages/ring-client-api/ring-intercom.ts#L70) is returning the following error:
```
HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1696329795541,
    socket: 1696329795542,
    lookup: 1696329795545,
    connect: 1696329795563,
    secureConnect: 1696329795784,
    upload: 1696329795785,
    response: 1696329795958,
    end: 1696329795962,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 3,
      tcp: 18,
      tls: 221,
      request: 1,
      firstByte: 173,
      download: 4,
      total: 421
    }
  }
}
```

I first noticed the problem when it logged me out for some reason (I was getting `Error: Refresh token is not valid.  Unable to authenticate with Ring servers.`).
I performed the auth flow again, now I can successfully read the battery level with `intercom.batteryLevel`, but calling `intercom.unlock()` returns that 404.

I'm not sure how to discover the new URL, if it changed on Ring's side.

### Expected behavior

It should unlock the door.

### OS

Linux (node:18-alpine docker image)

### Node.js Version

v18.7.0

### NPM Version

8.15.0

### ring-client-api

12.0.1

### Operating System

Linux (node:18-alpine docker image)

**Comment by tsightler** [comment]
So far there are no other reports of this issue.  The fact that it occurred after an authentication issue makes me wonder if there is still some account specific behavior going on.  The 404 can also happen when the account does not have permissions to perform an action on the device as the API simply returns 404 because that function is not available to the account (basically, the API hides the endpoint).

Are you using the primary Ring account, or is it a secondary/shared account being used?  I know that Ring has been implementing changes with intercom around guest access so perhaps that has somehow changed this.  However, the fact that there haven't been any other reports in either this project, or ring-mqtt, so far, makes me lean toward being account specific for now.

Unfortunately, I don't have an intercom and I'm pretty sure @dgreif doesn't have one either, so we rely on users being willing to share their device with us or investigating the API on their own.

**Comment by koichirose** [comment]
@tsightler thank you for your reply. I am using the main account. No issues with the official app.
I'll try again, maybe with a secondary account and report back

**Comment by koichirose** [comment]
@tsightler I tried with my secondary account, but still get 404.
Any suggestions on how to debug this?

**Comment by tsightler** [comment]
Can you unlock the device via the Ring web UI?  If so, you can use developer tools to see what API call is being made to do this.  Perhaps it has changed with all of the updates Ring is doing to Intercom access.

**Comment by koichirose** [comment]
I tried, but my Intercom does not appear in the web app. All I see on my dashboard is some kind of splash page with links to get the apps / request support. I have no other Ring devices.
I looked around online and it seems that Intercom is only available on the native apps.
Debugging those is not that easy, I'd have to setup a proxy and capture the requests I guess.
Unlocking from the app works fine.

**Comment by tsightler** [comment]
Yes, you have to setup MITM proxy and install a custom version of the Ring app to disable certificate pinning.  I have this setup, but don't own an intercom.  If you would be willing to share you intercom with me I could investigate fairly quickly.

**Comment by koichirose** [comment]
Sure, I can give you access. Do you have a way not to unlock the door while testing though? I wouldn't want my door unlocked in the middle of the night. I'm GMT+2.
Do you have an email i can use?

Or I could use Android Studio, do I still need a custom apk?

**Comment by tsightler** [comment]
I can be aware of the time, but I'd have to unlock it at least a few times for sure.  If it's just a minor change, maybe just once.

If you'd like to use Andriod Studio and investigate yourself, no problem, I can even provide the APK with the certificate pinning removed, or you can do it yourself.  Feel free to reach out to me, my email address is the same as my Github username at gmail.

**Comment by tsightler** [comment]
Unfortunately, I don't see anything actionable here.  Everything you posted is that same as what was discovered in the initial implementation and it seems to work as expected.  I suppose you could try removing things like the command_timeout, origin, and issue_time parameters, and see if that creates the issue, but you are getting a 404 while I would expect that would simply generate an error response.

Based on this, I don't see anything wrong with the code and we still have not a single user of homebridge-ring, ring-mqtt or any other project that uses ring-client-api wit this issue so I have to believe it is somehow related to your specific setup.

I'm still willing to try to troubleshoot it if you can share the intercom, I'm happy to coordinate the time with you so it feels safe and the access is provided only for a limited time, but I'm not really sure what the problem could be.

**Comment by koichirose** [comment]
Update: today it just worked again. I didn't change anything on my side, so I guess it was something temporary related to my account.
