### ISSUE TITLE
Apple tvos17

### ISSUE THREAD

**Issue by Saulman2** [dgreif/ring#1323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

When ring motion is detected,  my apple tv with tvos 17 shows up on my TV as a snapshot. However,  I just bought another apple tv that had tvos16.5 and it works perfectly with live. In fact, if both tv's are on, the 16.5 is live and 17 is still a snapshot. I tried resetting the ring Tokin and cleared all devices in the ring app. 

Is there a special setting for tvos17?

### To Reproduce

It happens every time

### Expected behavior

See describe bug

### Homebridge Ring Config

```shell
,
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "refreshToken": "xxxx
```

### OS

Synology DSM

### Node.js Version

v18.15.0

### NPM Version

v7.22.0

### Homebridge/HOOBs Version

v1.6.1

### Homebridge Ring Plugin Version

v12.0.1

### Operating System

Synology

**Comment by Saulman2** [comment]
If you open a camera manually in tvos17, the camera comes up live without any issues

**Comment by tsightler** [comment]
This plugin can't influence the behavior of Apple devices.  In the end, this plugin simply exposes Ring cameras as Homekit cameras, it provides a handful of functions which the Home applications can call to perform actions like getting a snapshot or starting a live stream, that is all.  It is completely up to Apple to control how their applications behave, if there is a difference in behavior between 16.5 and 17, then that is up to choices Apple has made and only Apple can change the behavior.

**Comment by Saulman2** [comment]
Thank you
