### ISSUE TITLE
Hide Camera Siren Switch toggle does not work

### ISSUE THREAD

**Issue by lolgas** [dgreif/ring#1324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I have Hide Camera Siren Switch toggled in the plugin settings and the siren switches are still loaded into homekit.

### To Reproduce

Toggle the hide camera siren switch and note that the siren switch is still loaded into homekit.

### Expected behavior

The siren switch is not loaded into homekit when the toggle is set in the plugin config.

### Homebridge Ring Config

```shell
{
    "refreshToken": "redacted",
    "hideCameraLight": true,
    "hideCameraSirenSwitch": true,
    "hideAlarmSirenSwitch": true,
    "avoidSnapshotBatteryDrain": true,
    "platform": "Ring"
}
```

### OS

Linux

### Node.js Version

v18.16.0

### NPM Version

unknown

### Homebridge/HOOBs Version

v1.6.1

### Homebridge Ring Plugin Version

v12.0.1

### Operating System

Ubuntu Jammy Jellyfish (22.04.3 LTS)

**Comment by tsightler** [comment]
I'm not able to reproduce this behavior, the configuration option works fine for me and, looking at the code, it's a simple check if the option is set or not as to whether the siren is registered as a device characterisitc so it is very difficult to see how it could go wrong (it is implemented exactly like hideCameraLight).  Are you sure you are not somehow being impacted by cached accessories or is there any chance you did not restart after making the configuration change?

**Comment by lolgas** [comment]
I don't believe I failed to restart after making the change. This is on a fresh connection of homebridge to homekit. Regardless, with the config set, a restart of homebridge should remove the sensors from homekit, correct?
