### ISSUE TITLE
Snapshot issue

### ISSUE THREAD

**Issue by clipse2004** [dgreif/ring#133]
Hello, 
i got this error sometimes:

Fehler: Sep 18 07:10:45 homebridge-Pi4 homebridge: [2019-9-18 7:10:45] [Ring] Failed to retrieve snapshot for Haustür.  The camera currently reports that is it online

what can i do? 

thanks

**Comment by dgreif** [comment]
If you are still failing to get snapshots from that camera, you can reboot it (remove battery or cut power) and that usually straightens things out.  Beyond that, there isn't anything else to do. Sometimes Ring is just too slow with the snapshots.
