### ISSUE TITLE
This plugin slows down Homebridge

### ISSUE THREAD

**Issue by slonoed** [dgreif/ring#1330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

When restarting homebridge I see this log

```
[10/14/2023, 9:56:46 AM] [homebridge-ring] This plugin slows down Homebridge. The write handler for the characteristic 'Setup Endpoints' on the accessory 'Garden C01A' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
```

It leads to page https://homebridge.io/w/JtMGR

There is another issue https://github.com/dgreif/ring/issues/1166 but it was closed by reporter. I do not have unhealthy disk drive.

### Expected behavior

Expecting not to have such log

### Homebridge Ring Config

```shell
{
            "refreshToken": "<TOKEN>",
            "unbridgeCameras": true,
            "hideCameraLight": false,
            "hideCameraSirenSwitch": true,
            "hideAlarmSirenSwitch": true,
            "platform": "Ring"
        }
```

### OS

DSM 7.2-64570 Update 1

### Node.js Version

v18.16.0

### NPM Version

Unknown, but should be latest in HB container

### Homebridge/HOOBs Version

v1.6.1

### Homebridge Ring Plugin Version

v12.0.1

### Operating System

Synology DSM

**Comment by tsightler** [comment]
Can you please describe what functional problem you are actually having?  A single log message during reboot can be ignored if you have no other issues, it simply indicates the Ring API being slow to respond or perhaps not responding at all.  While it's true that this can cause the entire bridge to delay while waiting for this request (i.e. slowing down Homebridge), it's generally not worth addressing this for something that happens once or only very rarely.  If it really a problem for you you can always run the plugin isolated to a child bridge or set cameras as unbridged.

**Comment by slonoed** [comment]
@tsightler thanks for your response.
So, you mean this happens not because of plugin but because Ring API itself. I guess nothing can be done here.
Also, as you pointed there is no well defined impact anyway. I'm going to close this issue. It's essentially "By design" and should not affect homebridge.
