### ISSUE TITLE
"Video Doorbell 4" and "Spotlight Cam Plus" cameras showing "Unknown Model"

### ISSUE THREAD

**Issue by jarodwsams** [dgreif/ring#1335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I have both a Video Doorbell 4 and a Spotlight Cam Plus that are showing "Unknown Model". I know from another integration that I've contributed to that the model identifier for both devices have newer device type strings (`doorbell_oyster` for the Doorbell 4 and `cocoa_spotlight` for the Spotlight Cam Plus). Neither of those device types are currently included in the `ring-types.ts` file.

I have a Stick Up Cam that shows the correct model name. In my Hubitat environment, using the "Unofficial Ring Integration", I had to add the `cocoa_spotlight` type for the integration to pick up the camera, which it promptly did after that modification to the source code for that integration.

### To Reproduce

Set up an MQTT environment with Ring-MQTT (https://github.com/tsightler/ring-mqtt).
Make sure you've got a Ring Video Doorbell 4 and/or a Ring Spotlight Cam Plus set up in your Ring account.
Note that both devices show "Unknown Model" in the device info in Home Assistant (screenshots).

### Expected behavior

Both cameras should show the correct model names ("Doorbell 4" for the `doorbell_oyster` device and "Spotlight Cam Plus" for the `cocoa_spotlight` device)

### Screenshots

![image](https://github.com/dgreif/ring/assets/22972834/9e4ef15d-3e36-4e9b-81bb-eb3d68e55bf1)
![image](https://github.com/dgreif/ring/assets/22972834/324e4b41-2a6b-4973-8575-7ed239297cb7)

### Additional context

I have already forked the main branch and made the necessary modifications to `ring-types.ts`. The PR can be found [here (PR 1334)](https://github.com/dgreif/ring/pull/1334)

### OS

Ubuntu Server / Docker

### Node.js Version

v18.17.1

### NPM Version

v9.1.2

### ring-client-api

v12.0.1

### Operating System

Docker

**Comment by dgreif** [comment]
Thanks for getting these added! The PR looks good, so I'll get that merged and included in the next release
