### ISSUE TITLE
Home Assistant

### ISSUE THREAD

**Issue by Jens-Wymeersch** [dgreif/ring#1343]
### Description

Dear,

I did an amazing job. I wonder if you could make a version for home assistant ?

**Comment by tsightler** [comment]
You can use ring-mqtt for Home Assistant if you wish, or you can use Home Assistants support for Homekit devices.  This project is not even written in the same development lanaguage as Home Assistant and there are no plans to do anyting like that.  I've tried to make ring-mqtt work as well as possible with Home Assistant.
