### ISSUE TITLE
Question - Does this work with Smart Lighting Transformer

### ISSUE THREAD

**Issue by DigitalMystery** [dgreif/ring#135]
Was trying to figure out if this works with:
https://shop.ring.com/products/smart-lighting-transformer-bridge
I could tell people were using this with Ring smart lighting, but wasn't sure with using the transformer on third party low voltage lighting.

**Comment by dgreif** [comment]
I do mention the transformers in the readme: https://github.com/dgreif/ring/tree/master/homebridge#supported-devices-via-ring-alarm-and-ring-smart-lighting-hubs

I haven't had any homebridge users confirm that they are using it with the transformers, but the code is all in place and should work.  If you end up getting it all set up, please report back to let me know if it works.  If you run into any issues I would be happy to work with you to get them properly integrated.

**Comment by techoin** [comment]
I just installed ring transformer and I can confirm that it is shows up fine in homekit as light. I have not yet added third party low voltage lighting but since transformer shows up correctly they should work fine.
