### ISSUE TITLE
failed to reach ring server

### ISSUE THREAD

**Issue by tim-fin** [dgreif/ring#1354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

repeatedly hitting this error, replicates consistently

Failed to reach Ring server at https://oauth.ring.com/oauth/token.  getaddrinfo ENOTFOUND oauth.ring.com.  Trying again in 5 seconds...

### Expected behavior

not erroring

### Relevant log output

```shell
Failed to reach Ring server at https://oauth.ring.com/oauth/token.  getaddrinfo ENOTFOUND oauth.ring.com.  Trying again in 5 seconds...
```

### Homebridge Ring Config

```shell
{
            "refreshToken": "removed",
            "unbridgeCameras": true,
            "hideLightGroups": true,
            "hideDoorbellSwitch": true,
            "hideCameraLight": true,
            "hideCameraMotionSensor": true,
            "hideCameraSirenSwitch": true,
            "hideAlarmSirenSwitch": true,
            "avoidSnapshotBatteryDrain": true,
            "platform": "Ring"
        },
```

### OS

raspbian

### Node.js Version

20.9

### NPM Version

10.1.0

### Homebridge/HOOBs Version

1.6.1

### Homebridge Ring Plugin Version

12.0.1

### Operating System

raspbian

**Comment by tsightler** [comment]
> getaddrinfo ENOTFOUND oauth.ring.com

If you host is unable to resolve hostnames, that is not the fault of the plugin, that is something that will need to be figured out on your host.  There's some possibility it could be a conflict with some other outdated plugin, but in any case there's nothing that can be done on the plugin side, it is using standard libraries to make HTTP requests and it's failing on your host.
