### ISSUE TITLE
When debug=true, show more details about refresh token failures

### ISSUE THREAD

**Issue by ijpiantanida** [dgreif/ring#1365]
### Description

I'm currently debugging an issue where the same refreshToken is valid and works from my development environment (my house), but fails in production (hosted in fly.io). I have a feeling Ring started blocking fly.io servers in the last few days because otherwise there is no difference between these environments and this system has been working fine for over a year.

The only error I see in production is, even with debug=true:
`Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens`.

I'd be great if I could see the raw error we are receiving from Ring when debug=true.

**Comment by ijpiantanida** [comment]
actually, looking at the code this is exactly what it should be doing already ([source](https://github.com/dgreif/ring/blob/main/packages/ring-client-api/rest-client.ts#L270)).

So I wonder why I can't see the error in fly logs - i will keep debugging, but I will close this until I can figure that out since this should work.

**Comment by tsightler** [comment]
Also, you have the source code so just add whatever logging you want/need.  The code that handles auth is no different than the code that handles all other requests so it would be super wordy to log everything.  I would say that debug is not intended for that type of low-level troubleshooting.  If you can figure out some way to do it reasonably without generating way too much logging for the more common case, feel free to submit a PR.
