### ISSUE TITLE
Unlocking door via Siri

### ISSUE THREAD

**Issue by N-Hott** [dgreif/ring#137]
When using Siri to unlock a door an immediate response is that Siri is unable to do so. It does unlock without issue. Is there a status or something that isn’t being returned properly? Locking the door via Siri works fine.

**Comment by dgreif** [comment]
@N-Hott did it work properly before and just start having issues?  I'm guessing this is an iOS 13 issue because I noticed some other odd behavior with my other HomeKit locks (that aren't connected through this plugin).

**Comment by N-Hott** [comment]
I can't say for sure. I haven't been using Homebridge that long. I just installed the Ring Alarm/Lock/Doorbell the last week of July and built out Homebridge the middle of August. My Apple TV's and some of my devices were already running beta versions of iOS/tvOS/iPadOS13. I figured it may be due to that.

**Comment by dgreif** [comment]
Closing since this is a HomeKit issue
