### ISSUE TITLE
Alarm triggered when using Apple Home intercom

### ISSUE THREAD

**Issue by derrickpelletier** [dgreif/ring#1375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I was using the intercom feature via Homepod Mini and it resulted in my Ring alarm going off. Had probably used the intercom a dozen times back and forth across 2 devices (my partner and i were testing it out) over a few minutes.

The last time seemed to trigger our Ring alarm system, logs below.
There are no logs before this (previous logs were over an hour prior)

Whats odd is none of the logs inidicate the alarm should have triggered.

### Expected behavior

I don't expect the alarm to go off when using intercom.

### Relevant log output

```shell
[12/8/2023, 9:38:24 PM] [Ring] Downstairs snoozed for 24 hours
[12/8/2023, 9:38:24 PM] [Ring] Turning Side On
[12/8/2023, 9:38:24 PM] [Ring] Setting brightness of Base Station to 20%
[12/8/2023, 9:38:24 PM] [Ring] Turning Front On

Will attach the history from the ring app
```

### Homebridge Ring Config

```shell
{
    "platform": "Ring",
    "name": "Ring",
}

refresh token redacted. That's it.
```

### OS

Raspbian GNU/Linux Bullseye (11)

### Node.js Version

v18.18.2 (thats what it says in homebridge but i think im using 16.20.2?

### NPM Version

8.19.4

### Homebridge/HOOBs Version

v1.7.0

### Homebridge Ring Plugin Version

v12.0.1

### Operating System

Raspbian GNU/Linux Bullseye (11)

**Comment by derrickpelletier** [comment]
![image](https://github.com/dgreif/ring/assets/833426/0b68eccc-09f9-4392-9750-9d60dcee817e)

**Comment by tsightler** [comment]
Clearly the device picked up some voice command that made it turn on all switches on the device, including the alarm siren switch.  That's not a bug.  You can hide the alarm siren switches if you like, option is already there.
