### ISSUE TITLE
support for new ring products

### ISSUE THREAD

**Issue by pslogic** [dgreif/ring#138]
looking through [api/ring-types.ts](https://github.com/dgreif/ring/blob/master/api/ring-types.ts), it seems that support for new hardware would have to be added in if it does not already map into one of the existing types, is this correct?

if so, what information from the device would be needed to help accelerate support?

recent tech news seems to indicate that Amazon/Ring may be announcing new product tomorrow

**Comment by dgreif** [comment]
It entirely depends on the product.  If they add something that works just like existing cameras or security/light devices, then we probably don't need to change anything.  The only code that is model-specific is whether or not a camera has a battery.  I keep a close eye on their new hardware and will do whatever is necessary to get new hardware to work.
