### ISSUE TITLE
Ring Intercom

### ISSUE THREAD

**Issue by pilot1981** [dgreif/ring#1385]
### Description

this component supports Ring Intercom product? also two way audio?

**Comment by tsightler** [comment]
Please do not open issues to ask basic questions, there are discussions forums for that and supported devices are already listed in the [readme](https://github.com/dgreif/ring/tree/main/packages/homebridge-ring#supported-devices-via-ring-alarm-and-ring-smart-lighting-hubs).

Some automation focused functions of Ring Intercom are supported, but not live interactive features like two-way audio.
