### ISSUE TITLE
Home app no Motion Detection

### ISSUE THREAD

**Issue by schweppy** [dgreif/ring#139]
Hi there

I have installed your plugin and have been enjoying live view and doorbell notifications from the home app in iOS 13.

For some reason i am getting no motion notifications from the motion sensor accessory? Is there any settings in the Ring app that i need to adjust as I have motion notifications from the Ring app off at the moment.

Many thanks

**Comment by henkied** [comment]
I have the same issue!

**Comment by dgreif** [comment]
If you go into the camera settings in HomeKit, then "Notifications", there are two options.  "Notifications on This iPhone" turns on motion notifications, and "Doorbell Notifications" turns on doorbell press notifications.  If you have these both on and aren't receiving notifications, try turning them off then back on, then restarting your phone and your HomeKit hub (iPad or apple tv).  If notifications still aren't working, I'm not sure what else to recommend.  Sometimes HomeKit is really bad at notifications.  Please check whether or not the camera is showing that motion is detected when you move in front of the camera

**Comment by henkied** [comment]
Thanks!! that has solved the problem

**Comment by dgreif** [comment]
Hopefully that helps you as well @schweppy.  Closing as this is a HomeKit issue, not something I can change in the plugin

**Comment by schweppy** [comment]
Yes seems to have fixed it. Many thanks!
