### ISSUE TITLE
Ring Plugin v 12.1.0 works for everything but Live Video in Homebridge

### ISSUE THREAD

**Issue by bennettb15** [dgreif/ring#1390]
### Streaming Issue

All devices within the Ring plugin work, however, video from my rings cameras only provides a quick updated snapshot once its on then essentially stays on the snapshot and never shows a live feed.  This appears to be the same in HOOBS and HomeKit.  I have tried rolling back to 12.0.1 and12.0.0 and experienced no change in feed.

### Proposed Solution

I likely cannot help you

### Environment

HOOBS

### What operating system are you on?

Linux

### Relevant log output

```shell
1/19/2024, 12:13:37 PMRing BridgeRingPreparing Live Stream for Front Door
1/19/2024, 12:13:38 PMRing BridgeRingStream Prepared for Front Door (0.451s)
1/19/2024, 12:13:39 PMRing BridgeRingiceConnectionStateChange: completed
1/19/2024, 12:13:39 PMRing BridgeRingActivating stream for Front Door (1.392s)
1/19/2024, 12:13:39 PMRing BridgeRingconnectionStateChange: connecting
1/19/2024, 12:13:39 PMRing BridgeRingiceConnectionStateChange: new
1/19/2024, 12:13:39 PMRing BridgeRingiceConnectionStateChange: checking
1/19/2024, 12:13:39 PMRing BridgeRingActivating Session
1/19/2024, 12:13:39 PMRing BridgeRingStreaming active for Front Door (1.766s)
1/19/2024, 12:13:39 PMRing BridgeRingiceConnectionStateChange: new
1/19/2024, 12:13:39 PMRing BridgeRingiceConnectionStateChange: connected
1/19/2024, 12:13:41 PMRing BridgeRingconnectionStateChange: connected
1/19/2024, 12:13:41 PMRing BridgeRingReceived stream data from Front Door (3.527s)
1/19/2024, 12:14:06 PMRing BridgeRingStopped Live Stream for Front Door
1/19/2024, 12:14:06 PMRing BridgeRingconnectionStateChange: closed
1/19/2024, 12:14:06 PMRing BridgeRingiceConnectionStateChange: closed
```

### Honesty Time

- [X] I swear this is worth your time!

**Comment by dgreif** [comment]
@bennettb15 I don't see anything concerning in the logs you shared. Please read through https://github.com/dgreif/ring/wiki/Camera-Troubleshooting as that is everything we have on debugging/understanding streaming issues.
