### ISSUE TITLE
Ring Door Opener not working anymore

### ISSUE THREAD

**Issue by elvirusDE** [dgreif/ring#1391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

All of a sudden, the door opener won't open the door anymore. Maybe it is a temporary issue, if so, I will delete my bug report. If not, then the Ring API could have changed...

I generated a new Access token and updated the homebridge-ring plugin to the newest version.

The following response is logged whenever I try to open the door:
```[Ring] Unlock response: {"id":null,"jsonrpc":"2.0","result":{"code":0},"responseTimestamp":1705795373000}```

It worked reliably until yesterday and suddenly, it does not work anymore.

### To Reproduce

- Create an ApiClient
- Try to unlock the door from within homekit

### Expected behavior

The door should be opened

### Relevant log output

```shell
[Ring] Unlock response: {"id":null,"jsonrpc":"2.0","result":{"code":0},"responseTimestamp":1705795373000}
```

### Homebridge Ring Config

```shell
{
    "refreshToken": "xxx",
    "platform": "Ring"
},
```

### OS

macos

### Node.js Version

v18.17.1

### NPM Version

unkonwn

### Homebridge/HOOBs Version

v1.7.0

### Homebridge Ring Plugin Version

v12.1.0

### Operating System

Raspbian

**Comment by tsightler** [comment]
I think it is unlikely the API changed, based on the fact that the result is 0, which indicates success.  The most interesting thing is the id being null, which is quite strange, but feels more indicative of a system issue than an API change.  If we don't get any other reports in the next few days I will close this issue.

**Comment by elvirusDE** [comment]
Thank you for your message.
Nothing changed for today. It is not working if I trigger it from HomeKit. It only works when I trigger it from the Ring App. The door opens without problems here.
From HomeKit just nothing, no reaction at all. I‘ve restarted all systems unfortunately to no avail.
Is there any debug log I could check for more information on this issue?

**Comment by tsightler** [comment]
There's no additional debug logging other than the response, which looks basically normal.  It would likely require deeper investigation into the calls the app is making vs the API here, however, as none of the developers on this project have an intercom (I assume you mean Ring Intercom when you say "door opener"), there's very little that can be done unless someone can find a difference in what the API does vs the app.

We've had other users occasionally report similar issues, and one even dug into it but did not find any differences and the fact that no one else has reported it to this point indicates that this is isolated to your account only, not something widespread, although this could change.  For other users it seems that the issue eventually just resolved itself, see https://github.com/dgreif/ring/issues/1320 for a different, but similar issue, and it just eventually started working again.

**Comment by elvirusDE** [comment]
Thank you.
My hope is that it resolves itself, that would be great.
I will sniff on my network and try to look at the requests. I‘ll post my findings here.
And yes, I meant Ring Intercom. Sorry for the confusion.

**Comment by elvirusDE** [comment]
It just resolved itself. Thank you for your quick responses!

closed
