### ISSUE TITLE
Ring Intercom - not possible to choose which HomePods should ring

### ISSUE THREAD

**Issue by Je-Ho** [dgreif/ring#1394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

First of all thank you for your work!

I’m not sure if it really is a problem with this plugin:

I’m using the Ring Intercom and expose it via a child bridge to HomeKit. 

When I add the child bridge to HomeKit, I’ll get the question, if a ring from the intercom should be played on my HomePods. When I say yes, all my two HomePods will ring. 

The problem is: I can’t choose which HomePod should ring or configure it in any way after adding the child bridge to HomeKit. In the HomeKit documentation, it points to a configuration in each HomePods settings. But there is nothing to be found. 

I would really like to use this feature, we have a newborn at home and I would be able to deactivate our very loud mechanics chime, if it would be possible to play a sound only on one of our two HomePods. 

Again, thanks for your work!

### To Reproduce

Add ring intercom to ring account.  
Add a new child bridge to HomeKit.
Confirm “ring in HomePods”

### Expected behavior

HomePods should be excluded from ringing. 

### Homebridge Ring Config

```shell
"refreshToken": "xxx",
            "hideDoorbellSwitch": false,
            "_bridge": {
                "username": "xxx",
                "port": 41638
            },
            "platform": "Ring"
```

### OS

Ubuntu Focal Fossa (20.04.5 LTS)

### Node.js Version

18.13

### NPM Version

X

### Homebridge/HOOBs Version

1.6.1

### Homebridge Ring Plugin Version

12.1

### Operating System

Ubuntu Focal Fossa (20.04.5 LTS)

**Comment by tsightler** [comment]
It's not really clear to me how this could be an issue with the plugin.  The plugin simply registers a programmable switch with the doorbell service type that's all.  It doesn't make any decisions over what Homepods chime, that's all done in Homekit settings.

If you go to the individual Homepod settings for any individual Homepod and scroll to "Doorbell chime" option, which is usually near the bottom, it will by default say "All", but if you click that you should get a screen listing all Homepods with a toggle to select the specific Homepods that will chime.

**Comment by Je-Ho** [comment]
That’s the problem, the configuration for doorbell chime does not appear in the HomePod settings - even when the HomePods do ring.

But thank you very much for your response. 

![IMG_5874](https://github.com/dgreif/ring/assets/7677889/6ddd8f9d-bcc6-4109-a919-755786debe45)

**Comment by tsightler** [comment]
So how do you turn the chime on and off at all?  Normally the setting would be just below the section in your screenshot.  I do wonder if Homekit is a little confused because it's not a video doorbell, it's just a doorbell.  Are there any other non-video doorbells that work with Homekit?

**Comment by Je-Ho** [comment]
There is another non video doorbell, the Nuki Dooropener should be similar, but I don't have access to this one. Within HomeKit, there is no mention of a chime after adding the ring intercom via Homebridge. Only during the initial setup of the bridge.
________________________________
Von: tsightler ***@***.***>
Gesendet: Thursday, February 1, 2024 3:25:18 PM
An: dgreif/ring ***@***.***>
Cc: Je-Ho ***@***.***>; State change ***@***.***>
Betreff: Re: [dgreif/ring] Ring Intercom - not possible to choose which HomePods should ring (Issue #1394)


So how do you turn the chime on and off at all? Normally the setting would be just below the section in your screenshot. I do wonder if Homekit is a little confused because it's not a video doorbell, it's just a doorbell. Are there any other non-video doorbells that work with Homekit?

**Comment by tsightler** [comment]
Ah, so it looks like Nuki Opener has the same issue and maintainer came to the same conclusion I did that Homekit only fully supports doorbells with video.  See https://github.com/ebaauw/homebridge-nb/issues/79#issuecomment-1206094073 for more details.

I suppose it would be possible to register a fake video stream, with just a blank screen or some text or something, but I'm not sure that's something we'd really want to integrate into the project.  Really seems like Homekit needs to properly support non-video doorbells.

**Comment by Je-Ho** [comment]
I missed the issue with the Nuki Opener, good research! Well, I don’t know, it would be great to have such a feature as an option, but of course, the bug is within HomeKit.  Thank you anyways!

**Comment by Je-Ho** [comment]
So I bought a Ring Video Doorbell and after adding it to HomeKit, I got the configuration menu to choose which HomePod should ring and the setting is honored for the Ring Intercom as well.

**Comment by tsightler** [comment]
Thanks for updating, so that seems to confirm that the issue is simply that Homekit doesn't support this feature for doorbells without video, which just seems like an oversight on their part.  I'd guess the only way the plugin could work around this is to register a dummy camera source, but that seems quite hackish.

On the other hand, there have been quite a few requests to support two-way audio with the Intercom, and if they were added, faking a dummy, static video source would be pretty easy and probably act to solve the issue.  Unfortunately, due to the fact that I don't have an intercom, nor the time right now, it's unlikely this will be implemented soon unless somebody with the device does it and submits a PR.  My guess is the two-way audio is implemented using the same protocol used for video streaming, but I haven't looked at it at all since I don't have an intercom.
