### ISSUE TITLE
Ring Intercom

### ISSUE THREAD

**Issue by Philomath88** [dgreif/ring#1398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I would like to receive the events from the Ring Intercom (the device to make an existing intercom smart). The API gets the location but does not detect the device:

Refresh token updated in .env file
Found 1 location(s).
Location: Home (73ee35ca-968f-499f-9b01-2d3c708cf0a2)
Devices at Home:

### Expected behavior

Should at least show the Intercom device 

### Relevant log output

```shell
Refresh token updated in .env file
Found 1 location(s).
Location: Home (73ee35ca-968f-499f-9b01-2d3c708cf0a2)
Devices at Home:
```

### OS

macOS 

### Node.js Version

18.6.0

### NPM Version

9.5.1

### ring-client-api

v1.0.0

### Operating System

macOS

**Comment by tsightler** [comment]
It's not clear to me what code you are running, but it looks a lot like the API example code, which does not currently list intercom devices, only camera and alarm devices, but the API itself supports Intercoms for some time.  Similar to cameras, intercoms are available as an array via `location.intercoms` property.

**Comment by Philomath88** [comment]
@tsightler Thank you - how can I get a notification when a ring event occurs (someone is at my door)?

**Comment by tsightler** [comment]
I would suggest using the code from the Homebridge plugin as an example, see:

https://github.com/dgreif/ring/blob/main/packages/homebridge-ring/intercom.ts

Basically, subscript to onDing events and take action.

**Comment by Philomath88** [comment]
Thank you @tsightler !

What I couldn't see in the example is whether it is possible to get the real-time audio and send real-time audio to the intercom - do you happen to know if that is possible?

**Comment by tsightler** [comment]
No, it is not possible.
