### ISSUE TITLE
Accessories not exposed to HomeKit

### ISSUE THREAD

**Issue by men-rumple0** [dgreif/ring#1399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

While the accessories are found by the plugin: 
<img width="741" alt="2024-02-06_14-44-56" src="https://github.com/dgreif/ring/assets/159150255/c5d5e72e-b0c6-4bba-901a-e13c5a8d9b6b">

they are not shown in homekit. The pugin is shown, but not the accessories: 
<img width="504" alt="2024-02-06_14-42-44" src="https://github.com/dgreif/ring/assets/159150255/a8411e67-e2aa-4853-9734-32acc03f8d09">

the accessories are also not shown in Homebridge accessories:
<img width="471" alt="2024-02-06_14-46-07" src="https://github.com/dgreif/ring/assets/159150255/87268c08-ead4-4e08-aa69-b6658274a515">

Maybe there is an issue, when one of the Ring base stations are "is offline or on cellular backup." it is saying "Waiting for status to change" in that line. 

The two other Ring base stations are online, but not showing up either. 

Any idea? Thanks a lot!!
JJ

### Expected behavior

The accessories of the two Ring base stations that are online should be shown in Homekit and in the Homebridge accessory tab. 

### Homebridge Ring Config

```shell
{
            "refreshToken": "xxx",
            "showPanicButtons": true,
            "platform": "Ring",
            "_bridge": {
                "username": "____",
                "port": 38711
            }
```

### OS

Synology DSM

### Node.js Version

v18.15.0

### NPM Version

v12.1.0

### Homebridge/HOOBs Version

v1.7.0

### Homebridge Ring Plugin Version

v12.1.0

### Operating System

Synology DSM / docker(?)

**Comment by tsightler** [comment]
> Maybe there is an issue, when one of the Ring base stations are "is offline or on cellular backup." it is saying "Waiting for status to change" in that line.

All Ring hub devices at all locations must be online during plugin startup, plugin setup will not complete until this is the case, thus the message.
