### ISSUE TITLE
The doorbell press and motion detection features seem to be ineffective with the jbox_v1 (Video Doorbell Elite) device type

### ISSUE THREAD

**Issue by costanzo98042** [dgreif/ring#1411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

The doorbell press and motion detection features seem to be ineffective with the jbox_v1 (Video Doorbell Elite) device type. While live camera viewing functions properly, both doorbell press and motion events fail to respond. This issue appears to be specific to the jbox_v1 (Video Doorbell Elite), as other device types like cocoa_floodlight, stickup_cam_v4, and stickup_cam_mini operate as intended.

### To Reproduce

Install and configure plugin as per instructions.   Press doorbell and walk in front of camera view to trigger motion event.

### Expected behavior

Anticipated functionality involves triggering an alert upon detection of motion or pressing of the doorbell button.

### Relevant log output

```shell
NA
```

### Screenshots

NA

### Homebridge Ring Config

```shell
NA
```

### Additional context

NA

### OS

Synology NAS

### Node.js Version

v20.9.0

### NPM Version

v20.9.0

### Homebridge/HOOBs Version

v1.7.0

### Homebridge Ring Plugin Version

v12.1.0

### Operating System

Debian

**Comment by tsightler** [comment]
Without any logs, or access to such a device, it's impossible to know what the problem might be.  Motion and ding events are handled by Firebase push notifications for all other cameras, and it's hard for me to believe that Ring suddenly changed that for the Doorbell Elite, which doesn't seem particularly special vs other devices, so not clear why at all why it wouldn't work.  I guess it's possible they may be using a different category/message type, but someone would need to investigate and reverse engineer it if it's truly different.

Providing some logs from a motion/ding event would be useful as you don't really speak about the state not changing but out "notifications" which are handled by Homekit, not this plugin, so it would be interested to see if the events are getting there or not.

**Comment by costanzo98042** [comment]
Thanks for the follow up. I will investigate on my end and if I find anything I will be sure to share. Please feel fee to close this bug report.  Best regards,JohnSent from my iPhoneOn Apr 2, 2024, at 9:41 AM, tsightler ***@***.***> wrote:﻿
Without any logs, or access to such a device, it's impossible to know what the problem might be.  Motion and ding events are handled by Firebase push notifications for all other cameras, and it's hard for me to believe that Ring suddenly changed that for the Doorbell Elite, which doesn't seem particularly special vs other devices, so not clear why at all why it wouldn't work.  I guess it's possible they may be using a different category/message type, but someone would need to investigate and reverse engineer it if it's truly different.
Providing some logs from a motion/ding event would be useful as you don't really speak about the state not changing but out "notifications" which are handled by Homekit, not this plugin, so it would be interested to see if the events are getting there or not.

**Comment by tsightler** [comment]
OK, will close for now, but if there are no notifications in the logs feel free to follow up.
