### ISSUE TITLE
Support Setting Fan Control Of Honeywell T6 Pro Thermostat

### ISSUE THREAD

**Issue by SarathVadakkepat** [dgreif/ring#1413]
### Description

- I have a honeywell t6 pro thermostat
- The thermostat is connected to the Ring system 
- The controls available are HVAC modes (off/cool/heat), and Fan Modes (Auto, On, Circulate)
- These controls are available on the device itself and on the ring app as well.
- However using the Ring plugin for homekit, the homekit accessory for this contains only the HVAC modes and no FAN modes.

It would be really awesome if FAN modes can be supported on the homekit as well.

**Comment by tsightler** [comment]
Not currently planned, and I don't think it's likely to be coded up by the maintainers anytime soon.  The thermostat code was originally contributed by another user.  I do have this exact thermostat, but but the code would have to be implemented in some way as to be generic for all thermostats.  Feel free to submit a PR with the enhancement.
