### ISSUE TITLE
Intercom - Ding event not available in ioBroker where I use your adapter

### ISSUE THREAD

**Issue by WaldemarCichon** [dgreif/ring#1418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I use your adapter for some time. It works very well - I use it together with a chime to unlock the door and also to watch other persons unlocking the door. But the Ding event seems not to work. It is never called.

 

### To Reproduce

write a script with the handling of the ding event
ring the bell connected to the intercom
open the door by pushing the knob or calling the method in the API
`    intercom.onDing.subscribe({
            next: () => {
                console.log(Ding was triggered');
                chime.setVolume(8);
                chime.playSound("ding");
            }
    })
    
    console.log('init for unlocked');
    intercom.onUnlocked.subscribe({
        next: () => {
            console.log("Unlocked");
            chime.playSound("motion");
            
        }
    })`

### Expected behavior

the ding event should be called
in oposite - the unlock event works very well.`
`

### Relevant log output

```shell
no output / logs available
```

### Homebridge Ring Config

```shell
none, called directly by a script
```

### OS

Raspian

### Node.js Version

V18.18.0

### NPM Version

v10.2.4

### Homebridge/HOOBs Version

none

### Homebridge Ring Plugin Version

current

### Operating System

Raspian

**Comment by tsightler** [comment]
Please read https://github.com/dgreif/ring/wiki/Refresh-Tokens#refresh-token-updates, specifically the important note section.  Most likely you will need to delete the device from Ring Control Center and repeat the authentication process.
