### ISSUE TITLE
No motion triggers

### ISSUE THREAD

**Issue by pslogic** [dgreif/ring#142]
I have a door view cam, stick up cam, and the new indoor cam. I am able to receive snapshots and video streams from all of these devices, but the motion sensors are not being triggered.

I also have the Ring and Rapid Ring apps installed and they are detecting and notifying motion is occurring.

Where else can I look to provide more debug info to help troubleshoot? I've already tried resetting my iphone, apple tv, homebridge but am still experiencing problems.

**Comment by dgreif** [comment]
This is most likely a HomeKit issue if you are not receiving notifications.  You can confirm that motion is being detected by going into the camera settings, then clicking on "Accessories".  It should have a linked accessory for the motion sensor, which will show if motion is detected or not:

![image](https://user-images.githubusercontent.com/3026298/66146875-82a86180-e5c2-11e9-8424-cd355b803607.png)
![image](https://user-images.githubusercontent.com/3026298/66146896-8b993300-e5c2-11e9-8bc1-9e55f3bd44ef.png)

Assuming you see "Triggered" on the motion sensor, then this is a HomeKit notification issue.  You can try turning notifications off and back on for that camera, and make sure that your apple TV and iphone are on the latest firmware version

**Comment by pslogic** [comment]
@dgreif the situation is not related to notifications. the issue being experienced is that the sensor tile is not being triggered at all.

i forgot to mention that my iphone is still on 12.4.1 and my apple tv is on 13.0

**Comment by dgreif** [comment]
That's probably the problem. Try getting everything upgraded to iOS 13 and see if it's still an issue

**Comment by dgreif** [comment]
@pslogic I added some additional logging in `v5.8.0`.  It will now log (in your homebridge logs) when each camera detects motion or a doorbell is pressed.  See if the logs match up with your notifications from the ring app.  If they do, then it's definitely a HomeKit issue and nothing I can fix from the plugin side

**Comment by pslogic** [comment]
very nice, I'll try that out right now

**Comment by pslogic** [comment]
the original issue as reported seems resolved. it required both an update to latest software on all devices as well as following [this comment](https://github.com/dgreif/ring/issues/142#issuecomment-538028267) above.

the debug output is real nice for verifying data flow between components 👍for that enhancement

one thing I noted which I'm not sure where the root cause lies is specific to the door view cam... when I go into camera settings, the panel shows that there is 1 accessory, but when going into the next screen there are 2 accessories shown. screenshots for reference:

![IMG_2598](https://user-images.githubusercontent.com/526750/66174897-19e5d700-e60c-11e9-89a0-1c922edb270c.PNG)

![IMG_2599](https://user-images.githubusercontent.com/526750/66174906-22d6a880-e60c-11e9-987f-006d38199134.PNG)

going into the camera settings for a stickup cam wired and the new indoor cam show 2 accessories as expected, i.e. motion sensor and siren switch

**Comment by dgreif** [comment]
Yep, that's a fun iOS 13 bug.  I'm not sure why, maybe because it's a second programmable switch (doorbell button is a programmable switch as well) and they exclude those from the count.  In any case, it's an iOS issue and not something I can fix.  Glad you got your motion events working!
