### ISSUE TITLE
Intercom: It is not possible to disable HomeKit notifications when doorbell rings

### ISSUE THREAD

**Issue by simonbrueckner** [dgreif/ring#1424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I have added a Ring Intercom device to Homebridge and it works perfectly insofar that I can program the switch in HomeKit and also have automations to automatically open the door on a doorbell ring. However, I can not disable the push notifications sent by HomeKit when the doorbell rings. This is annoying as the Ring App itself also sends that notification (which I also want to receive so I can answer the Intercom).
I did disable notifications on the Lock itself in HomeKit, but this only removes the notifications that the door has been unlocked, not the notifications for ringing.

### To Reproduce

* Add Ring Intercom to Homebridge:
<img width="753" alt="Bildschirmfoto 2024-05-31 um 11 01 41" src="https://github.com/dgreif/ring/assets/861233/cb6a0d9f-7262-475d-9fcf-d7a3030c36e1">

* Disable Notifications on HomeKit Doorlock:

<img width="1268" alt="Screenshot 2024-05-31 at 11 09 09" src="https://github.com/dgreif/ring/assets/861233/ea3f9e00-de53-4477-a5ce-90d3cd85d523">

<img width="1268" alt="Screenshot 2024-05-31 at 11 03 07" src="https://github.com/dgreif/ring/assets/861233/507c2f54-6247-47d8-ab95-2d6321797a46">

* But there is no way to disable notifications on the Doorbell itself:
<img width="1268" alt="Screenshot 2024-05-31 at 11 04 14" src="https://github.com/dgreif/ring/assets/861233/f45a2139-5130-4ca9-b51a-0b4a629d1f3d">

### Expected behavior

Either the notification setting on the Doorlock should remove both ringing and unlocking notifications or there should be a separate setting on the Switch to disable ringing notifications.

### Homebridge Ring Config

```shell
"platforms": [
        {
            "refreshToken": "<redacted>",
            "platform": "Ring"
        }
    ]
```

### OS

Rasbian

### Node.js Version

v18.19.0

### NPM Version

0

### Homebridge/HOOBs Version

v1.8.2

### Homebridge Ring Plugin Version

v12.1.0

### Operating System

Rasbian

**Comment by tsightler** [comment]
This is a HomeKit limitation, not something that can be addressed by this plugin.

**Comment by simonbrueckner** [comment]
Thanks for your quick answer. I was wondering if that Is this true though?

I was checking on other doorbell providers which have native HomeKit integration and here, it seems to be possible to granularly set notifications for different events, see e.g. https://www.belkin.com/support-article/?articleNum=318671#:~:text=Step%201%3A%20Open%20your%20Apple,ON%20or%20OFF%20notification%20settings.
