### ISSUE TITLE
Plugin doesn’t respect Ring app settings for Live View

### ISSUE THREAD

**Issue by owellsjr** [dgreif/ring#1425]
### Streaming Issue

In the Ring app one can configure the system to disable live access to a given camera when it is in a certain Mode. In the Home app it will block Snapshots but tapping the camera will still allow Live access even when it’s been disabled in the Ring app. From a privacy perspective this should be fixed. 

### Proposed Solution

The plugin should respect the settings in the Ring app when it comes to live camera access. 

### Environment

HOOBS

### What operating system are you on?

Mac

### Honesty Time

- [X] I swear this is worth your time!

**Comment by tsightler** [comment]
Duplicate of https://github.com/dgreif/ring/issues/1327
