### ISSUE TITLE
No longer working (cannot arm and disarm)

### ISSUE THREAD

**Issue by qoodanny** [dgreif/ring#1432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

No response, keep looping and losing

### Expected behavior

Arm or disarm

### Homebridge Ring Config

```shell
-
```

### OS

macOS

### Node.js Version

20.14

### NPM Version

10.7

### Homebridge/HOOBs Version

1.8.2

### Homebridge Ring Plugin Version

12.1

### Operating System

macOS

**Comment by tsightler** [comment]
Duplicate, please use search before opening issues.

https://github.com/dgreif/ring/issues/1431
