### ISSUE TITLE
Add Medical Alert Option for Ring Alarm Integration with Home Assistant

### ISSUE THREAD

**Issue by wjnelson78** [dgreif/ring#1437]
### Description

Currently, the ringmqtt integration for Home Assistant provides the ability to handle Police and Fire alerts. However, there is a need to include a Medical alert option. When the Medical button is pressed by an individual (such as an elderly person or someone with medical conditions), it sends an alert to Ring Monitoring, the keypads flash along with the medical button, but no siren is activated. This feature request aims to include the Medical alert in the ringmqtt integration, allowing Home Assistant to trigger automations for local onsite proactive medical response and notification.

### Proposed solution

Add support for Medical alerts in the ringmqtt integration by implementing new MQTT topics and commands similar to those used for Police alerts. This would enable Home Assistant to monitor the state of the Medical button and set commands accordingly. The proposed MQTT topics for the Medical alerts are as follows:

1.	Get Medical Panic ON/OFF State:
	•	Topic: ring/<location_id>/alarm/<device_id>/medical/state
	•	Description: Retrieves the current state of the Medical button (ON/OFF).
2.	Set Medical Panic ON/OFF Command:
	•	Topic: ring/<location_id>/alarm/<device_id>/medical/command
	•	Description: Sets the Medical button state to ON or OFF.

These additions will allow users to create automations in Home Assistant to trigger specific actions, such as notifying caregivers, sounding additional alarms, or sending alerts to medical professionals, based on the Medical alert state.

### Device data

Example payloads for the new Medical topics:

	1.	Get Medical Panic ON/OFF State:
	•	Topic: ring/<location_id>/alarm/<device_id>/medical/state
	•	Payload Example:
{
  "state": "ON"
}

        •	Response Example:
{
  "command": "OFF"
}

Implementing this feature will enhance the ringmqtt integration, providing a comprehensive solution for monitoring and responding to medical emergencies through Home Assistant.

**Comment by tsightler** [comment]
This project is not ring-mqtt, so you've posted in the wrong place.  You should post requests for ring-mqtt on the projects [Feature Requests](https://github.com/tsightler/ring-mqtt/discussions/categories/feature-requests) discussion group.
