### ISSUE TITLE
Add ability to view camera activity in recent events

### ISSUE THREAD

**Issue by jakeleventhal** [dgreif/ring#1439]
### Description

When I look at the security tab of HomeKit, my cameras and locks are there. I also see a tab for Activity History.
<img width="438" alt="Screenshot 2024-06-21 at 10 23 38 AM" src="https://github.com/dgreif/ring/assets/15133828/49f6453b-7b2c-45ad-b848-c16fc4e7ea84">
When I click the activity history, I only see the lock history, not any camera motion detected history.
<img width="534" alt="Screenshot 2024-06-21 at 10 23 43 AM" src="https://github.com/dgreif/ring/assets/15133828/2c4eec48-211e-4155-8fde-720ff7fb1e20">
Moreover, when I get notifications about a camera detecting motion, if I click on it, I will see a screenshot of the camera at that time, but I have no way of viewing the event clip in HomeKit.

**Comment by tsightler** [comment]
You are asking for changes to the behavior of Homekit, this plugin can't change the way Homekit behaves, it only exposes the device capabilities to Homekit, that is all.  Homekit's "Activity History" is only for security devices (locks, garage doors, security system arm/disarm), it does not keep history for all sensors and definitely not for motion sensors.  Feature requests for Homekit should be made to Apple.
