### ISSUE TITLE
Ring Intercom - Possibility do make it a switch / button instead of a lock

### ISSUE THREAD

**Issue by knikkabokka** [dgreif/ring#1443]
### Description

At the moment I need a klick AND a slide to unlock the staircase-door by a widget from the lockscreen. 

... I'd love to unlock the door with only one klick ... Would be much more comfortable ...

### Proposed solution

As it will be no big security risk at an apartment building (as the door to the staircase unlocks only for two seconds anyway ... And does normally not stay unlocked permanently) it would be nice to have the possibility to configure the ring intercom alternatively as button / switch that triggers the door für only a few seconds instead of as a lock. 
(Should be no "on-off" switch, but a "one klick, one short action" switch, if that's possible ...) 

So one would only need one klick on the lockscreen instead of a klick - then wait-wait-wait - and then slide.

**Comment by tsightler** [comment]
The device is a lock, the action is unlocking and thus registering as a lock accessory is the correct thing to do.  If you prefer to allow unlock without any security for your use case there are multiple ways to address this, probably the easiest is to use the dummy switch plugin for Homebridge to create a switch and then use this to trigger an automation that unlocks the door, but there are plenty of other options.
