### ISSUE TITLE
Homebridge-Ring logs don't show up in Homebridge UI (Homebridge-Config-UI-X)

### ISSUE THREAD

**Issue by stevehoek** [dgreif/ring#1448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

When you view the Plugins page and choose "Plugin Logs" on the Homebridge-Ring plugin, the log is empty
Log messages show up correctly in the aggregated log on the UI's Status page

### To Reproduce

Open Homebridge Web UI
Go to Plugins
Choose "Plugin Logs" from the 3-dot menu of the Ring plugin
See empty log view

### Expected behavior

Logs pertaining just to Homebridge-Ring

### Homebridge Ring Config

```shell
Standard config
```

### OS

Raspbian

### Node.js Version

v20.15.1

### NPM Version

latest

### Homebridge/HOOBs Version

latest

### Homebridge Ring Plugin Version

latest

### Operating System

Raspbian

**Comment by dgreif** [comment]
@stevehoek unfortunately I'm not able to reproduce this issue. If I view the plugin logs for Ring, they show up as expected. I'd make sure you are on the latest version of homebridge-config-ui-x as well as homebridge-ring, then try restarting everything. If the issue persists, consider openeing an issue on homebridge-config-ui-x
