### ISSUE TITLE
Homebridge 2 support

### ISSUE THREAD

**Issue by rionshin** [dgreif/ring#1452]
### Description

homebridge will be releasing version 2.0 which will have breaking changes to existing plugins

### Proposed solution

Make it HB 2.0 compatible .  What is the plan for supporting Homebridge 2.0 - will the plugin be impacted and will it be easy to make it compatible with 2.0.

https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2

**Comment by tsightler** [comment]
I have not looked into it deeply, but I was under the impression that the changes needed were merged into the beta via https://github.com/dgreif/ring/pull/1447.

**Comment by dgreif** [comment]
@tsightler is correct that this was addressed in #1447 (thanks @donavanbecker!). I just released v13.0.0, which should work with Homebridge 2.0. Please let us know if you still see issues after updating.
