### ISSUE TITLE
Notifications for battery percentage below threshold X

### ISSUE THREAD

**Issue by psycoticninja** [dgreif/ring#1455]
### Description

Be able to define battery percentage below threshold X in plugin settings and be able to push notifications from Home app when that threshold is met.

### Proposed solution

Be able to define battery percentage below threshold X in plugin settings and be able to push notifications from Home app when that threshold is met.

### Alternatives

N/A

### Device data

I have some Ring cameras that are battery only and it would be good to get notified from Home app when that threshold is met/below.

**Comment by dgreif** [comment]
This is a great idea and something I wish HomeKit supported. Unfortunately, the homebridge plugin does not have any way to send direct push notifications. This is a feature you would need to request from Apple, as the Home app is owned by them and would be the right place to configure this type of notification.
