### ISSUE TITLE
All transformers are not showing up. 

### ISSUE THREAD

**Issue by kkazempour** [dgreif/ring#1456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I have three landscape transformers hooked up to a bridge. The bridge and 2 of the transformers show up in the logs, but not all three. 

### To Reproduce

Restart the child bridge and scan the logs for three occurrences of `transformer`

### Expected behavior

All three to be there. Logs below show the only entries.  

### Relevant log output

```shell
[8/4/2024, 11:19:01 AM] Loaded 5 cached accessories from cachedAccessories.0EC40C8D86FD.
[8/4/2024, 11:19:01 AM] [homebridge-ring] Configuring cached accessory 6e5b1774-1b8f-43c1-876a-********** Transformer Two
[8/4/2024, 11:19:01 AM] [homebridge-ring] Configuring cached accessory c359059d-9300-4edd-84ce-******** Transformer One
```

### Homebridge Ring Config

```shell
{
    "refreshToken": "<<REMOVED>>",
    "unbridgeCameras": true,
    "_bridge": {
        "username": "<<REMOVED>>",
        "port": 59901
    },
    "platform": "Ring"
}
```

### Additional context

![IMG_5973](https://github.com/user-attachments/assets/d6eccb64-e785-466b-8928-e466d37a1e86)

### OS

macOS Sonoma

### Node.js Version

v18.16.0

### NPM Version

9.5.1

### Homebridge/HOOBs Version

Homebridge v1.8.4 · UI v4.56.4 

### Homebridge Ring Plugin Version

v12.1.1

### Operating System

macOS Sonoma

**Comment by dgreif** [comment]
Hey @kkazempour, sorry you are running into issues. I don't see anything obvious to indicate where the issue is coming from. You aren't hiding any device types or locations based on the config you posted, so I'm not sure why the third transformer wouldn't show up. Unfortunately I think the most likely fix is to remove the homebridge plugin and re-install it. You will lose related automations, but hopefully it will fix your issue.

**Comment by kkazempour** [comment]
Nothing hidden at all. I think I'll have to do that

**Comment by dgreif** [comment]
Let me know if that fixes your issue

**Comment by kkazempour** [comment]
Thanks. You know what's funny is that the switch is live in HK. It's just not printing the ID in the logs.

**Comment by tsightler** [comment]
So are you saying everything is working fine and it's somehow just missing from the log?

**Comment by kkazempour** [comment]
Correct, that is more accurate description of the bug. I wanted the log line so I could get the device ID

**Comment by tsightler** [comment]
The thing is, I don't believe this problem can be in the plugin.  The logging is very simple and occurs whenever configureAccessory() is called.  This function is called by Homebridge, not by anything in the plugin itself and, if this function is called, then the first thing it does is log this message.  I don't think it is possible for the function to be called but the code that logs the message to not be executed.  Are you sure that perhaps the device isn't just logged differently, perhaps as a new accessory vs a cached one?  Can you please provide full startup logs?

**Comment by tsightler** [comment]
Closing as there has been no response and cannot be reproduced.
