### ISSUE TITLE
Ring Doorbell Pro Notifications Don't Show

### ISSUE THREAD

**Issue by mrtekkid** [dgreif/ring#146]
I have Ring plugin installed in Homebridge on OSX Mojave. 
Currently running iOS 13.2 but this issue happens on all devices. First my setup.
I'm using 2FA login for the Ring plugin.
Was able to add all my devices successfully into Homekit after installing the Ring plugin to home bridge. . 

I have: 
Ring Doorbell Pro
Ring Floodlight Cam (x2)
Ring Spotlight Cam

All cameras show up in Homekit just fine and update as expected when launching Home.app.
All light switches and siren switches work as expected in Home.app as well on iOS. 

My issue is with Motion notifications. I currently can get Motion notifications for my Floodlight Cams and my Spotlight cam but not for my doorbell. If I tap into settings for the Doorbell cam, I can see there is a motion sensor present but for whatever reason it doesn't update. I've tried removing my Doorbell cam and re-adding it with no success. 

In the Ring app and the Rapid Ring app all notifications appear (including the Ring Doorbell Pro) so it's not like the device is not seeing/sending notifications out. 

Any idea why just the Doorbell motion doesn't work? 

Thanks

**Comment by dgreif** [comment]
See #142.  This is a HomeKit issue and not something I can fix from the plugin

**Comment by dxdc** [comment]
@mrtekkid did you figure this out? I'm having the same issue and also have Ring Doorbell Pro's. I see the motion sensor and it *does* trigger -- in fact --  I have an automation running when motion detected, turn a light on, and THAT works fine too.

Just no notification. And no rich notification for the doorbell (@dgreif not sure if those are supported)? Some interesting discussion here about changes for rich notifications in iOS13:

https://github.com/KhaosT/HAP-NodeJS/pull/704
https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/351
https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/332

**Comment by mrtekkid** [comment]
I kinda figured it out.
I was told by the Dev to update all of my devices. They were all updated. However I had a lone iPad mini 2 that cannot go to iOS 13. Turning off Home in Settings for that device and rebooting everything seems to have fixed it since rebooting everything on its own did nothing.

Do you have any devices that cannot run iOS 13 that have access to your Homekit setup?

**Comment by dxdc** [comment]
@mrtekkid you've given me an idea.

My Apple TV and iOS devices are all running 10.13. However, my macOS devices are all running 10.14 (not interested in upgrading to Catalina until at least 2020). Do you think that could be it? If so, that's very interesting (and buggy) on the part of Apple to block motion notifications when macOS 10.14 devices are part of HomeKit.

**Comment by mrtekkid** [comment]
Odd, my iOS devices are on iOS 13 and my Macs are still running Mojave.
No issues.

**Comment by dxdc** [comment]
Strange. Appreciate your reply.

I will say HomeKit can be buggy (Shortcuts in particular), but really not sure what the issue is. The motion sensor is firing though.

Just curious...  do you have any automations set up with the motion sensor? I'm wondering if that could be related too. If all else fails maybe I'll just remove/re-add but I can't imagine why that would be any different since I see all the sensors and they're working and the log looks correct too.

**Comment by mrtekkid** [comment]
I do not have any automations with the motion sensor. It does send the picture in the notification when it detects motion though.
All my other sensors worked as well.

I’d maybe at this point try removing the camera for the doorbell, reboot all devices and re-add the camera for the doorbell back to HomeKit.

Not sure what to do after that because the Dev pretty much said it was a “Homekit” bug and ducked out. I removed everything, took that iOS 12 iPad off, removed the camera, rebooted and readded as a last ditch effort and it started working.

God speed.

**Comment by dxdc** [comment]
Thanks @mrtekkid ! Appreciate the discussion. I'll keep trying... I don't understand why the notification isn't firing but it makes sense if HomeKit does control those notifications.
