### ISSUE TITLE
No motion sensor under ios13

### ISSUE THREAD

**Issue by BAngel87** [dgreif/ring#147]
I can not see / use the Motion Sensor under iOS 13! It is there I can see it under Eve but not in the Home App, so I can not set the Motion Alarm to see the picture if anyone is at the door! Anyone else has the same issue?

**Comment by dgreif** [comment]
This is expected behavior in iOS 13. It groups the camera accessories together, but you can still see them if you go into settings for the camera. See #142 for details

**Comment by BAngel87** [comment]
Sadly the problem is that I don't receive messages when the motion is triggered! I activated messages in general for the camera but I can't see were to activate it for motion alerts! Thanks for the Tip#142 but I can't see where to activate the motion alert

**Comment by dgreif** [comment]
Motion notifications should be on if you turn on notifications for the camera. The doorbell has a separate toggle, but motion events are tied to the main notification toggle. If it’s not working, try rebooting your phone and other HomeKit devices including any Apple TV out iPads that you have.
