### ISSUE TITLE
Alarm Window & Door Contact Sensor Button to Trigger a HK action

### ISSUE THREAD

**Issue by illbigwill03** [dgreif/ring#1470]
### Description

I was previously a Nest Secure & Detect user before Google sunset the device. With my Starling Hub, I had the option to use the door sensor's button for a double click to trigger any action in HomeKit. I used this double-click feature to turn on my Patio String Lights or even disable my alarm.

### Proposed solution

Does Ring allow the Alarm Window and Door Contact Sensor's button to be used as a button for triggering actions within HomeKit, similar to how Starling enabled the use of Nest Detect's button?

**Comment by tsightler** [comment]
As this is mostly a question, perhaps it would be better as a discussion topic vs an issue.  Please consider using discussions vs issues in the future.

Regarding the request specifically, as far as I'm aware, the button is used only to get a quick status of the device locally and there is no method to interact with it via the API (the Ring App does not appear to show anything about this button).  Theoretically, it might generate an event on the message bus but, as I don't own any sensors with a button (first gen sensors did not have a button) I cannot test this.

You can use ring-client-api to subscribe to location.onDataUpdate() and see if messages are generated when the button is pressed.
