### ISSUE TITLE
RING DOOR - Videostream closed

### ISSUE THREAD

**Issue by guzzzi** [dgreif/ring#1476]
### Streaming Issue

Sometimes the Stream starts in HomeKit but will close the Connection, or it doesn't work from the beginning, I have to reopen the stream several times.
My Phone is connected to the same local Network. The Ring-App working well.

Hoobs 4.3.1 - No Update for Node available, I use your Ring App in Version 12.1.1

### Proposed Solution

i don't understand this question.

### Environment

HOOBS

### What operating system are you on?

Linux

### Relevant log output

```shell
22.8.2024, 16:52:53 Ring Bridge Ring Preparing Live Stream for Haustür
22.8.2024, 16:52:53 Ring Bridge Ring Stream Prepared for Haustür (0.478s)
22.8.2024, 16:52:53 Ring Bridge Ring Activating stream for Haustür (0.67s)
22.8.2024, 16:52:54 Ring Bridge Ring iceConnectionStateChange: completed
22.8.2024, 16:52:54 Ring Bridge Ring connectionStateChange: connecting
22.8.2024, 16:52:54 Ring Bridge Ring iceConnectionStateChange: new
22.8.2024, 16:52:54 Ring Bridge Ring iceConnectionStateChange: checking
22.8.2024, 16:52:54 Ring Bridge Ring Activating Session
22.8.2024, 16:52:54 Ring Bridge Ring Streaming active for Haustür (1.168s)
22.8.2024, 16:52:54 Ring Bridge Ring iceConnectionStateChange: new
22.8.2024, 16:52:54 Ring Bridge Ring iceConnectionStateChange: connected
22.8.2024, 16:53:14 Ring Bridge Ring [ ERROR ] Video stream closed
22.8.2024, 16:53:14 Ring Bridge Ring [ ERROR ] [object Object]
22.8.2024, 16:53:14 Ring Bridge Ring connectionStateChange: closed
22.8.2024, 16:53:14 Ring Bridge Ring iceConnectionStateChange: closed
22.8.2024, 16:53:37 Ring Bridge Ring Preparing Live Stream for Haustür
22.8.2024, 16:53:37 Ring Bridge Ring Stream Prepared for Haustür (0.357s)
22.8.2024, 16:53:37 Ring Bridge Ring Activating stream for Haustür (0.443s)
22.8.2024, 16:53:38 Ring Bridge Ring iceConnectionStateChange: completed
22.8.2024, 16:53:38 Ring Bridge Ring connectionStateChange: connecting
22.8.2024, 16:53:38 Ring Bridge Ring iceConnectionStateChange: new
22.8.2024, 16:53:38 Ring Bridge Ring iceConnectionStateChange: checking
22.8.2024, 16:53:38 Ring Bridge Ring Activating Session
22.8.2024, 16:53:38 Ring Bridge Ring Streaming active for Haustür (0.999s)
22.8.2024, 16:53:38 Ring Bridge Ring iceConnectionStateChange: new
22.8.2024, 16:53:38 Ring Bridge Ring iceConnectionStateChange: connected
22.8.2024, 16:53:38 Ring Bridge Ring Received stream data from Haustür (1.33s)
22.8.2024, 16:53:38 Ring Bridge Ring connectionStateChange: connected
22.8.2024, 16:53:59 Ring Bridge Ring Stopped Live Stream for Haustür
22.8.2024, 16:53:59 Ring Bridge Ring connectionStateChange: closed
22.8.2024, 16:53:59 Ring Bridge Ring iceConnectionStateChange: closed
22.8.2024, 16:54:04 Ring Bridge Ring Preparing Live Stream for Haustür
22.8.2024, 16:54:04 Ring Bridge Ring Stream Prepared for Haustür (0.353s)
22.8.2024, 16:54:04 Ring Bridge Ring Activating stream for Haustür (0.449s)
22.8.2024, 16:54:05 Ring Bridge Ring iceConnectionStateChange: completed
22.8.2024, 16:54:05 Ring Bridge Ring connectionStateChange: connecting
22.8.2024, 16:54:05 Ring Bridge Ring iceConnectionStateChange: new
22.8.2024, 16:54:05 Ring Bridge Ring iceConnectionStateChange: checking
22.8.2024, 16:54:05 Ring Bridge Ring Activating Session
22.8.2024, 16:54:05 Ring Bridge Ring Streaming active for Haustür (0.992s)
22.8.2024, 16:54:05 Ring Bridge Ring iceConnectionStateChange: new
22.8.2024, 16:54:05 Ring Bridge Ring iceConnectionStateChange: connected
22.8.2024, 16:54:13 Ring Bridge Ring connectionStateChange: connected
22.8.2024, 16:54:13 Ring Bridge Ring Received stream data from Haustür (9.633s)
22.8.2024, 16:54:45 Ring Bridge Ring [ ERROR ] Video stream closed
22.8.2024, 16:54:45 Ring Bridge Ring [ ERROR ] [object Object]
22.8.2024, 16:54:45 Ring Bridge Ring connectionStateChange: closed
22.8.2024, 16:54:45 Ring Bridge Ring iceConnectionStateChange: closed
```

### Honesty Time

- [X] I swear this is worth your time!

**Comment by guzzzi** [comment]
Tried  it on Homebridge, latest Plugin Version too

[22/08/2024, 19:29:00] [Ring] Preparing Live Stream for Küche-Schwarz
[22/08/2024, 19:29:00] [Ring] Stream Prepared for Küche-Schwarz (0.431s)
[22/08/2024, 19:29:00] [Ring] Activating stream for Küche-Schwarz (0.584s)
[22/08/2024, 19:29:01] [Ring] iceConnectionStateChange: completed
[22/08/2024, 19:29:01] [Ring] connectionStateChange: connecting
[22/08/2024, 19:29:01] [Ring] iceConnectionStateChange: new
[22/08/2024, 19:29:01] [Ring] iceConnectionStateChange: checking
[22/08/2024, 19:29:01] [Ring] Activating Session
[22/08/2024, 19:29:01] [Ring] Streaming active for Küche-Schwarz (1.536s)
[22/08/2024, 19:29:01] [Ring] iceConnectionStateChange: new
[22/08/2024, 19:29:01] [Ring] iceConnectionStateChange: connected
[22/08/2024, 19:29:02] [Ring] connectionStateChange: connected
[22/08/2024, 19:29:03] [Ring] Received stream data from Küche-Schwarz (3.258s)
[22/08/2024, 19:29:07] [Ring] Stopped Live Stream for Küche-Schwarz
[22/08/2024, 19:29:07] [Ring] connectionStateChange: closed
[22/08/2024, 19:29:07] [Ring] iceConnectionStateChange: closed
[22/08/2024, 19:31:49] [Ring] Preparing Live Stream for Haustür
[22/08/2024, 19:31:50] [Ring] Stream Prepared for Haustür (1.04s)
[22/08/2024, 19:31:50] [Ring] Activating stream for Haustür (1.192s)
[22/08/2024, 19:31:51] [Ring] iceConnectionStateChange: completed
[22/08/2024, 19:31:52] [Ring] connectionStateChange: connecting
[22/08/2024, 19:31:52] [Ring] iceConnectionStateChange: new
[22/08/2024, 19:31:52] [Ring] iceConnectionStateChange: checking
[22/08/2024, 19:31:52] [Ring] Activating Session
[22/08/2024, 19:31:52] [Ring] Streaming active for Haustür (3.065s)
[22/08/2024, 19:31:52] [Ring] iceConnectionStateChange: new
[22/08/2024, 19:31:52] [Ring] iceConnectionStateChange: connected
[22/08/2024, 19:32:11] [Ring] Video stream closed
[22/08/2024, 19:32:11] [Ring] {
  doorbot_id: 221186010,
  session_id: 'eyJraWQiOiJTaWduYWxsaW5nIiwiYWxnIjoiSFMyNTYifQ.eyJkaW5nX2tpbmQiOiJvbl9kZW1hbmQiLCJkb29yYm90X2lkIjoyMjExODYwMTAsInBpbmdfaW50ZXJ2YWwiOjEwLCJkaW5nX2lkIjoiNzQwNjAxNzg4NDg5MjEwNDY2NiIsImlwIjoiNTIuMTcuMTYyLjE2MSIsImNyZWF0ZWRfYXQiOjE3MjQzNDc5MTE4NDEsInJtc19mcWRuIjoiNTItMTctMTYyLTE2MS4zNjg3NjY5NDgyMjMuZXUtd2VzdC0xLnByb2Qucm1zLnJpbmcuZGV2aWNlcy5hMnouY29tIiwic2Vzc2lvbl9pZCI6ImQ2NzRmZTA5LTEwOTUtNDUzZS1hNTk2LTg2MzAwNjgyZmExOCIsImV4cCI6MTcyNDQzNDMxMSwiaWF0IjoxNzI0MzQ3OTExLCJybXNfdmVyc2lvbiI6IjJjZTA2YWNmIn0.cxICuGfhn3ejR0sY2wnF4LzgbQuosjJUcW5hyhFtc08',
  reason: { code: 8, text: 'Timeout waiting for camera connection' }
}
[22/08/2024, 19:32:11] [Ring] connectionStateChange: closed
[22/08/2024, 19:32:11] [Ring] iceConnectionStateChange: closed
[22/08/2024, 19:32:20] [Ring] Stopped Live Stream for Haustür

**Comment by tsightler** [comment]
The error message in your second post is quite clear 'Timeout waiting for camera connection'.  This is a message directly Ring sent via the control channel and indicates that Ring was unable to establish a streaming session with the camera.  There's nothing we can do for this as plugin developers.  I noticed above that, in at least one case, it shows taking almost 9 seconds to receive data from the camera, that is massively too long, it should generally be less than 5 seconds every time for reliable service, more commonly 2-3 seconds.

The Ring app is somewhat more forgiving of these issues as it supports adaptive bitrate and will silently try multiple times in the background, but, unfortunately, these functions don't exist in ring-homebridge today, and likely never will.  Also, for ring-homebridge + Homekit the video stream has to transit the network at least one additional time (sometimes 2x).  If everything is wifi, this can really stress the network, especially during startup when Ring sends a big burst of traffic which, with a fast network connection, can quite easily overrun the default Linux buffers.  You can try to increase the UDP buffers on the device running ring-homebridge in this case as it might help.

Another option is to enable debug and see if you get more detail.  For example, after starting a stream you should see details about first video and audio packet, etc.   It might give more clues or it might not.

Regardless, there is very little that can be done from the plugin side for the issue logged above.

**Comment by guzzzi** [comment]
Hello,
Thank you for your feedback. I have now switched to Homebridge. I have activated debug mode in the settings and restarted, but unfortunately I can no longer see the log files that I have already written here. 
It's crazy that it works sometimes and then I have to try several times for the stream to connect at all.

I have increased the UDP buffer, unfortunately without success.

A reconnect of the plugin until DATA comes for the stream is not possible, or would that make sense at all?

**Comment by tsightler** [comment]
If you enable debug logging in the plugin, there should definitely be more logs, you should see details about first packet received as well as ffmpeg details.  However, as noted, the error you posted in the second post is actually from Ring, not from the plugin, the plugin is just reporting it.  That is Ring saying it was unable to establish the connection with the camera on it's side, for whatever reason.

> A reconnect of the plugin until DATA comes for the stream is not possible, or would that make sense at all?

Unfortunately, not likely to help since the frontend client would have already timed out.  For the Ring app, it is the client, so retry is easy.  On the other hand, ring-homebridge, is just a proxy for the client (Homekit), so, even if a retry on the back end successfully established a stream, the frontend would have almost certainly timed out by then (5 seconds in most cases).

Ideally you should be able to figure out why the timeouts are happening, working with a bunch of users over the years it's almost always something unexpected, like a cheap switch, or some mesh wifi setup.

**Comment by guzzzi** [comment]
OK thank you. I will take a look at my Network Setup.
