### ISSUE TITLE
unbridgeCameras

### ISSUE THREAD

**Issue by gcastelli3** [dgreif/ring#1477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Once I add the "unbridgeCameras": true statement I do not see how to add the cameras back to Home.  It does not give me 4 new QR codes to add the four cameras separately. 

### To Reproduce

add "unbridgeCameras": true, to configuration

### Expected behavior

I expected additional QR codes to add them seperately.

### Homebridge Ring Config

```shell
{
    "unbridgeCameras": true,
    "beamDurationSeconds": 32767,
    "refreshToken": !!removed!!
    "platform": "Ring"
}Hoobs HPRO-1
```

### OS

Linux

### Node.js Version

18.17.1

### NPM Version

5.0.13

### Homebridge/HOOBs Version

1.7.0

### Homebridge Ring Plugin Version

13.1.0

### Operating System

Debian

**Comment by tsightler** [comment]
I would kindly ask that you do not open bugs for simply not know how to do something, that is not a bug, that is simply a question, more appropriate for the discussion groups or even discord channel.

To answer your question, you do not need separate codes, the same code used for the main bridge will work fine.  Simply select to add an accessory, and then, on the screen where there is the option to scan the code, select "more options" and you will see the individual cameras.  Select the one you wish to add and enter the code or select use camera to use the QR code.
