### ISSUE TITLE
No motion event for Ring Doorbell v2

### ISSUE THREAD

**Issue by jasonhnz** [dgreif/ring#148]
Installed on homebridge with no problem. 
2 Stick up cams working fine however the Doorbell doesnt appear to fire any triggers. 

Ive setup an event (homekit automation for single doorbell click) which works ok.
The doorbell camera works as well, however motions never fire. 

I'm assuming this event is covered? If so, anything I can try to debug further or to "reset" this device?

**Comment by dgreif** [comment]
See #142 and #147
