### ISSUE TITLE
Still getting "Please add ['Camera' xxxx] manually in Home app" message in Log File

### ISSUE THREAD

**Issue by sabresoftware2021** [dgreif/ring#1482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I have removed and reinstalled my cameras unbridged, and manually added them in Home app and they work fine, but each time HomeBridge is restarted I get the following message "Please add ['camera' xxxx] manually in Home app for each of my cameras.

Its a minor thing.

### Expected behavior

Not to see the "please Add ..." message once cameras are added

### Homebridge Ring Config

```shell
{
    "refreshToken": " xx ",
    "unbridgeCameras": true,
    "hideDoorbellSwitch": true,
    "hideCameraMotionSensor": false,
    "platform": "Ring"
}
```

### OS

Raspbian

### Node.js Version

v20.9.0

### NPM Version

v10.1.0

### Homebridge/HOOBs Version

v1.8.4

### Homebridge Ring Plugin Version

v13.1.0

### Operating System

Raspbian GNU/Linux Bullseye (11)

**Comment by tsightler** [comment]
This is expected, it's just informational.  The plugin has no method to know if the cameras are added or not so it logs the information on how to add the camera on each startup.

**Comment by sabresoftware2021** [comment]
OK, thanks
