### ISSUE TITLE
Intercom 

### ISSUE THREAD

**Issue by maennersache** [dgreif/ring#1484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Hi there,

I have an issue with the doorbell of the ring intercom.

Even though it shows up in the HomeBridge Accessories Page.
I don't see it in Homebridge and my HomePods do not chime when someone pressed the bell.

Any suggestions?

<img width="699" alt="image" src="https://github.com/user-attachments/assets/d1700c91-9d8e-457d-b49a-5e0cf8586523">

![image](https://github.com/user-attachments/assets/10bea7cb-4384-46d5-9f7f-20f5a71fd910)

### Expected behavior

The doorbell should show up in HomeKit as well an be controllable.

### Homebridge Ring Config

```shell
-
```

### OS

Debian GNU/Linux Bookworm (12)

### Node.js Version

v20.17.0

### NPM Version

-

### Homebridge/HOOBs Version

v1.8.4

### Homebridge Ring Plugin Version

v13.1.0

### Operating System

Rasbian

**Comment by tsightler** [comment]
Did you add the bridge to Homekit?  Overall, if it's visible in Homebridge then the job of the plugin is done, but the bridge still needs to be added to Homekit to be able to see the devices there.

**Comment by tsightler** [comment]
Closing due to no response.
