### ISSUE TITLE
Allow Setting Fixed Ports For Unbridged Cameras

### ISSUE THREAD

**Issue by dpharrall** [dgreif/ring#1485]
### Description

Anytime the Homebridge service is restarted, new ports are assigned to each unbridged camera. When allowing specific ports in Uncomplicated Firewall, this causes the cameras to no longer be reachable when the service restarts and new ports are assigned. 

### Proposed solution

Allow the user to define a port or port range for unabridged cameras.

**Comment by tsightler** [comment]
I don't believe this is possible as it is up to Homebridge to select the port for given accessories and it would be a mess if every plugin would allow defining such ports as users could easily configure plugins for overlapping port ranges.  However, you can define a range of ports for Homebridge itself and it will only use ports from that range for accessory assignment to limit the number of ports that are required to be open or forwarded in the case of Docker with non-host networking.  This is shown in the config-sample.json file on the Homebridge project Github.

However, I would also point out that video streams use dynamic ports as well, as is their nature, so firewalls can interfere with reliable video streaming as well.
