### ISSUE TITLE
Intercom - Bridge in the Home app stuck on connecting

### ISSUE THREAD

**Issue by FranciRoosters** [dgreif/ring#1486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

The Home app gets stuck on connecting when linking the Bridge to the app

### Expected behavior

App should connect to the bridge in a relatively short time

### Homebridge Ring Config

```shell
{
    "refreshToken": "token",
    "platform": "Ring"
}
```

### OS

Raspbian

### Node.js Version

20.16.0

### NPM Version

most recent

### Homebridge/HOOBs Version

4.57.1

### Homebridge Ring Plugin Version

13.1.0

### Operating System

Raspbian

**Comment by tsightler** [comment]
It's not really clear what your issue is as you provided no screenshots, logs, or anything that can really help.  hHwever, adding the bridge to Homekit sounds like a Homebridge issue, not something with the plugin.  Does your intercom appear in the Homebridge UI?

**Comment by tsightler** [comment]
Closing due to no response.
