### ISSUE TITLE
Ring Doorbell - Live Preview (No Response) - Works on Motion

### ISSUE THREAD

**Issue by Mightyred81** [dgreif/ring#150]
Hi,

First of all thanks for the efforts to create this plugin.

Ive had some "No response errors" in the preview and when attempting to access via live link. The snapshot of my cameras are refreshing within the expected intervals too, however the front door again doesn't update until motion is detected.

However when the front door camera detects motion then it updates the snapshot & allows me to connect to live view.

Does anyone have any idea on how to resolve this?

**Comment by Mightyred81** [comment]
![IMG_2358](https://user-images.githubusercontent.com/25375923/66718081-9c725180-edd7-11e9-88e5-36ea24691492.jpg)

**Comment by Mightyred81** [comment]
Sorry forgot to add using Hoobs

Since posting this Ive now seen refreshed snapshots however did see this in the logs?

[10/13/2019, 4:33:12 PM] [Ring] Streaming video only - ffmpeg was not found
[10/13/2019, 4:30:20 PM] [Ring] Snapshot failed to refresh after 60 attempts
[10/13/2019, 4:27:37 PM] [Config] [HapClient] Cannot load accessories. No Homebridge instances have been discovered. (This may be unrelated to Ring?)

**Comment by dgreif** [comment]
I'd recommend disconnecting power to the camera (pull out the battery or disconnect wires for doorbell) to restart the camera.  If you still have issues, restart all of your HomeKit devices (iPhone, apple TV, HomePod, iPad).

**Comment by dgreif** [comment]
@Mightyred81 did this ever get resolved?

**Comment by Mightyred81** [comment]
I did sorry! I rebooted everything and it sorted it! 

Thanks
