### ISSUE TITLE
Please add Homebridge 2.0 support 

### ISSUE THREAD

**Issue by fluxbeard** [dgreif/ring#1501]
### Description

Hi, I am using a Ring Intercom in my Homebridge setup and was wondering if the plugin will be Homebridge 2.0 compatible.

**Comment by tsightler** [comment]
Please do not open issues to ask basic questions.  There is a discussion forum if you just want to ask a question.  Patches for Homebridge 2.0 compatibility were merged some weeks ago and, as far as I know, there are no known issues with Homebridge 2.0 release at this time.  If you have an issue, feel free to open one with specifics.
