### ISSUE TITLE
Unable to add unbridged camera unless I disable firewall (homebridge running on Synology)

### ISSUE THREAD

**Issue by 6MH89F3j** [dgreif/ring#1504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I'm unable to add or stream an unbridged camera, unless I disable my entire firewall. Bridged mode works fine, since I'm able to allow traffic for the home bridge UI app in my firewall. Is there an equivalent way to do so for an unbridged camera?

I did search for this issue, and found #1461 , and a feature request #1485, but there doesn't seem to be any plan for a fix for this.

Is there any other way to make this work, except to disable my entire firewall?

### To Reproduce

1. Have homebridge-ring configured on a synology box (as a child bridge), running the homebridge app for synology
2. Configure synology firewall to block all traffic, and only add specific things to the allow list
3. Enable Unbridged mode, restart child bridge
4. Try to add the new unbridged camera in home.app

Things to note:
- DSM version on synology box: DSM 7.2.1-69057 Update 5
- DSM Homebridge app version: 3.1.2

### Expected behavior

I expected to be able to add the unbridged camera in home.app. The camera does appear, and I'm able to tap to add it, and it allows me to enter the setup code. However, it just spins for several minutes and ends with error saying the accessory is not reachable.

If I completely disable my synology firewall, then it allows me to add and stream the unbridged camera. I wasn't able to get it working by manually allowing the port the logs say it's using for the camera accessory either. Although, that wouldn't be a great option anyway, since the port changes each time the bridge restarts.

### Homebridge Ring Config

```shell
{
    "refreshToken": "[redact]",
    "unbridgeCameras": true,
    "hideLightGroups": true,
    "hideDoorbellSwitch": true,
    "hideCameraLight": true,
    "hideCameraMotionSensor": true,
    "hideCameraSirenSwitch": true,
    "hideInHomeDoorbellSwitch": false,
    "hideAlarmSirenSwitch": true,
    "avoidSnapshotBatteryDrain": false,
    "hideDeviceIds": [
        "[redact]",
        "[redact]",
        "[redact]",
        "[redact]",
        "[redact]"
    ],
    "_bridge": {
        "username": "[redact]",
        "port": [redact]
    },
    "platform": "Ring"
}
```

### OS

Synology DSM 7.2.1-69057 Update 5

### Node.js Version

v20.9.0-1003

### NPM Version

v10.8.2

### Homebridge/HOOBs Version

v1.8.4

### Homebridge Ring Plugin Version

v13.1.0

### Operating System

Synology DSM 7.2.1-69057 Update 5

**Comment by tsightler** [comment]
> I did search for this issue, and found https://github.com/dgreif/ring/issues/1461 , and a feature request https://github.com/dgreif/ring/issues/1485, but there doesn't seem to be any plan for a fix for this.

> Is there any other way to make this work, except to disable my entire firewall?

You say you saw #1485, but did you actually follow the advice there of defining the allowed port range for Homebridge?  If you do this then accessories are assigned sequentially from this range and you just need to define a range big enough for the camera devices you have and make sure that range of ports is open in the firewall.

**Comment by 6MH89F3j** [comment]
Thanks for the quick reply! Yes, I saw that. But here's where I'm struggling:
1. I dont know how to set the port range. I'm searching the internet, but not finding a lot. I'm only a low-medium level user of home bridge. I saw this reddit, which makes it seem like it might not work anyway [https://www.reddit.com/r/homebridge/comments/1br2x7l/any_way_to_set_a_port_range_for_child_bridges/](url). Do you know of any links I could look at for instructions? I'll keep digging since I'm sure it's out there, but if you have pointers, that would be really helpful. Since I'm not a super advanced user, I'm always cautious about making changes like this.
2. When I switch to Unbridged mode, it gives the port the camera accessory is on. I opened that port in my firewall, but home.app still couldn't communicate with the accessory (I'm guessing the child bridge might need to be restarted or something?). The only way I got it to work, was to turn off my firewall, switch to unbridged mode, and then add the accessory.
3. Does your comment "However, I would also point out that video streams use dynamic ports as well, as is their nature, so firewalls can interfere with reliable video streaming as well." mean that this won't work anyway, since I'm using this for camera streams?

**Comment by 6MH89F3j** [comment]
And to be clear, I'm guessing I need to edit my homebridge config.json. But I dont know how to handle the difference between the main bridge vs the child bridge. I have my ring plugin running on a child bridge. And I dont know the exact syntax to use to specify a port range. I see a few different spots in the json config that specify a port.

**Comment by tsightler** [comment]
You don't need to handle the child bridge at all because these devices are unbridged.  You can just use the config-sample.json from the Homebridge Github project page which you can Google easily, but here is the link:

https://github.com/homebridge/homebridge/blob/latest/config-sample.json

Just add the ports section to your config as shown in the sample, defining your preferred start and end options, make sure they ports are open in the firewall, and restart Homebridge.

**Comment by tsightler** [comment]
Yeah, sorry, I guess I thought saying the filename and was enough to know what to Google as it's literally just "Homebridge" and "config-sample.json" and it's the first hit, but perhaps that's me assuming too much there as I'm not a big fan of posting links as they change and then break at some point in the future.

I also removed the statement that you found confusing.

**Comment by 6MH89F3j** [comment]
That's fair feedback. I was googling the right thing, but I wasn't putting together how to interpret the example. I use to have more time to dig in on stuff. Anyway, I really do appreciate you helping. The other context you provided around not needing to handle the child bridge, etc, was super helpful too, since I was struggling to understand that too.

I was able to get everything setup with the port range, and all seems to be working well. The unbridged camera is much more performant than the bridged mode, so that's awesome! Thanks again for the help.

**Comment by tsightler** [comment]
Awesome, I'll close this then.  Thanks for the feedback as it made me realize I need to not assume so much!
