### ISSUE TITLE
Add RTSP Stream to Ring Intercom so it’s an videodoorbell in HomeKit 

### ISSUE THREAD

**Issue by Chr9727** [dgreif/ring#1505]
### Description

First of all I would like to say thank you for this great plugin and all the work behind it. 

Unfortunately, HomeKit is so limited that you can neither edit or deactivate the bell created by the Intercom. This would only be possible with a video doorbell. 
For my specific case, but I can imagine that others have the same problem, I have already installed another camera in the area of the doorbell. It would be great to see the live-image from this camera as soon as the Intercom bell is pressed. 
It would therefore be great if you could store an RTSP stream and the Intercom bell would then be displayed as a video doorbell. 

There are also plugins that do this (triggered via a button), but then you would receive 2 notifications, one from the intercom bell which can’t be deactivated and one from the video doorbell. 
Or is it perhaps possible to deactivate / hide only the bell on the plugin side and leave the switch displayed?

Thank you so much in advance!

**Comment by tsightler** [comment]
As neither myself nor @dgreif own an intercom, I'm going to say there's near zero percent chance that we would be interested in implementing this.  I'd say Iif you'd like to put something together that is easy to use/configure and submit a PR, I think we would consider it.

I'm pretty sure you can do this with the Homekit Bridge feature in Home Assistant if you really wanted to as it allows you to expose a camera entity and associate a different device as the doorbell sensor, but I admittedly haven't tried this.

**Comment by Chr9727** [comment]
Thank you very much for the quick reply. I'll give it a try with the Homeassistant plugin and let you know here, if you want. 

If I find the time, I will look into the videodoorbell plugin and possibly open a PR.
