### ISSUE TITLE
New Config - fetch is not defined - Failed to reach Ring server at https://oauth.ring.com/oauth/token

### ISSUE THREAD

**Issue by jgoines** [dgreif/ring#1513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I've tried a few of the existing suggestions for previous builds including:
- sudo systemctl enable systemd-networkd-wait-online.service
- ensuring all ring devices are online <-- let's come back to this one

Despite the error and no devices showing I was able to add the bridge to Homekit, no devices or options are shown in Homekit once added.

**Log entry from Hoobs:**
Ring BridgeBridge is running on port 51826.
Ring BridgeRingERRORFailed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch is not defined.  Trying again in 5 seconds...
{{repeats every 5 seconds}}

**Environment**
Everything is online and on ethernet except my phone of course.
HOWEVER, the actual ring alarm and ring cameras are on a separate VLAN/network from the bridge/Pi. I didn't think this would make a difference since things were connecting "in the cloud" but am I mistaken does everything need to be moved back to the main network to function?
_Adguard is place on the network. The logs just show that freegeoip.app is being blocked if that is of some importance._

### To Reproduce

Fresh install with latest build on Raspberry Pi (see additional env details if those are important)

### Expected behavior

Sorry new user, my understanding is that I should see devices either in Hoobs or in Homekit neither has taken place.

### Relevant log output

Ring BridgeBridge is running on port 51826.
Ring BridgeRingERRORFailed to reach Ring server at https://oauth.ring.com/oauth/token. fetch is not defined. Trying again in 5 seconds...
{{repeats every 5 seconds}}

### Homebridge Ring Config

```shell
Sorry, I don't know how to export this, and what I did export was a binary.
```

### OS

Rasbian

### Node.js Version

16.20.2

### NPM Version

8.19.4

### Homebridge/HOOBs Version

1.7.0

### Homebridge Ring Plugin Version

13.1.0

### Operating System

Rasbian

**Comment by tsightler** [comment]
> Node.js Version
> 16.20.2

As stated in the release notes for v13 as well as many other duplicate issues (including a pinned issue), NodeJS <18 is not supported and NodeJS >=20 is highly recommended.  Versions prior to Node 18 do not have fetch, thus the "fetch is not defined" error.

**Comment by tsightler** [comment]
Yes, there is a pinned issue here about HOOBS compatibility, or lack thereof, since they haven't provided an update to their platform in ages.  They have previously indicated that they expect a new version to be released by Nov 1st, so there is hope for HOOBS yet I guess but running native Homebridge is generally easier and more reliable.
