### ISSUE TITLE
Live View not stopping / repeating continuously

### ISSUE THREAD

**Issue by jchristianj** [dgreif/ring#1518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Hi, my complete Ring history is filled up with live view events, each of them app. 12 minutes long. As soon as a live view ends, the Plugin initiates a new one. This happens without user interaction on a Doorbell Pro 2. 
Does not happen with a Ring 2 on the same account.

### Expected behavior

No live view without user interaction.

### Homebridge Ring Config

```shell
{
    "refreshToken": "ey..19",
    "unbridgeCameras": true,
    "hideDoorbellSwitch": true,
    "debug": true,
    "hideDeviceIds": [
        "e2d83ff2-c810-4248-8521-30e9ef968b02"
    ],
    "_bridge": {
        "username": "0E:53:C7:39:B5:31",
        "port": 53876
    },
    "platform": "Ring"
}
```

### Additional context

[homebridge-ring.log.txt](https://github.com/user-attachments/files/17589235/homebridge-ring.log.txt)

### OS

Homebridge

### Node.js Version

22.11.0

### NPM Version

10.9.0.

### Homebridge/HOOBs Version

1.8.5.

### Homebridge Ring Plugin Version

13.1.0.

### Operating System

Debian

**Comment by tsightler** [comment]
Assuming that you have restarted homebridge and it happens immediately then some device on your network is attempting to stream video, you will need to figure out what that is.

**Comment by jchristianj** [comment]
Not sure what caused this, but after updating my HomePod and Apple TVs to 18.1 and rebooting them it seems to have stopped.
