### ISSUE TITLE
Homebridge 2.0 support

### ISSUE THREAD

**Issue by skydivedan** [dgreif/ring#1523]
### Description

It doesn't look like Homebridge 2.0 is supported (although it's mention in issues that it is).
I'm using the most recent version of the Ring plugin, btw.
<img width="562" alt="Screenshot 2024-11-16 at 12 13 45 PM" src="https://github.com/user-attachments/assets/a4ae26eb-2cee-4685-aeb5-981578f897a5">
<img width="828" alt="Screenshot 2024-11-16 at 12 13 36 PM" src="https://github.com/user-attachments/assets/8abf749a-bb76-450d-9aec-4a2ad6e41c97">

### Proposed solution

Modify the plugin so that Homebridge knows for sure that Homebridge 2.0 is supported.

### Alternatives

I tried filing a bug about this. But the form wouldn't let me. I could plainly see that I entered all the required fields.

**Comment by tsightler** [comment]
There are no know issues with current versions of this plugin when running on Homebridge 2.0, however, as far as I know, it is still in beta.  When Homebridge 2.0 is released it its final form, we'll update the package metadata.  Until then, if you have any actual issue to report, feel free to open an issue.
