### ISSUE TITLE
Expose Ring Chime 2 status light switch 

### ISSUE THREAD

**Issue by njuart** [dgreif/ring#1528]
### Description

Hi, well I hope the title is self-explanatory. Just wondering if there a possibility to expose Ring Chime 2 status light switch to use it in automations, for instance, when Chime is snoozed light is off and vice versa. Thx in advance!

**Comment by tsightler** [comment]
There are no plans to expose this switch at this time.  I appreciate that it might be nice, but realistically, some people wouldn't like that telling Siri to "Turn off all the lights" would turn this on/off, so then we'd need more controls to hide the device, etc.  There's just not enough use case for this feature to justify yet another config option.
