### ISSUE TITLE
download videos having data plan

### ISSUE THREAD

**Issue by divemasterjm** [dgreif/ring#153]
Hi, is there any possibility to download videos in batch? i would like to have them all in my cloud, downloading them once every hour, day.

**Comment by dgreif** [comment]
@divemasterjm this is definitely possible, but I'm not sure it needs to be part of this project.  It would be pretty simple to write a script which uses this api to do what you're asking.  Are you able to write code and set this up on your end?

**Comment by divemasterjm** [comment]
Sorry but I’m not able to write code.

JuanMa

**Comment by dgreif** [comment]
I'm not sure this feature really has a wide use case.  If anyone else finds this and is interested, let me know.
