### ISSUE TITLE
New head-to-toe battery doorbell video aspect ratio

### ISSUE THREAD

**Issue by Quilgy** [dgreif/ring#1533]
### Description

The new head-to-toe Ring battery video doorbell features a 1440p square aspect ratio. In the Ring app, you can zoom to fill either the vertical or horizontal viewing angle, but the camera’s default output is a square image with visible vignetting (a circular effect around the edges). When integrated with HomeKit, this square image cannot be resized or zoomed to fit a 16:9 display, leaving it partially filling the screen with the vignetting clearly visible.

### Proposed solution

Make an option available in the Ring plug-in for HomeBridge to select an aspect ratio for the camera, e.g., 16:9 which will zoom the image to fit, eliminating the vignette and square aspect.

**Comment by dgreif** [comment]
Changing the aspect ratio would require transcoding the video stream, which is processor-intensive. I see where the incorrect aspect ratio is annoying, but fixing it would require a fair amount of complexity which we don't really want to add in this project. The Home app does support pinch zooming, so at least there is a workaround if you need a tighter image during a live stream.
