### ISSUE TITLE
Question regarding sensor contact capability

### ISSUE THREAD

**Issue by iRayanKhan** [dgreif/ring#154]
Hello, I saw #47, but my question was, will my existing wired contact sensors for windows and doors add into HomeKit with the base station + keypad, or will I have to get ring branded ones?

**Comment by smockle** [comment]
If your existing wired contact sensors appear in the Ring app (e.g. via the [recently announced “Ring Retrofit Alarm Kit”](https://shop.ring.com/pages/announcements)), then this plugin should bring them into HomeKit.

If your existing wired contact sensors do not appear in the Ring app, then this plugin cannot bring them into HomeKit.

**Comment by iRayanKhan** [comment]
Thank you! I'll wait for it to roll out before getting anything for Alarms, but may get a doorbell.

**Comment by dgreif** [comment]
@smockle thanks for pointing out the retrofit alarm kit, I wasn't aware they had announced that!  Everything else @smockle said is spot on, and I would love to hear how that system works if you end up getting it when it's released.
