### ISSUE TITLE
Ring Intercom - door open works but registering doorbell event doesn't

### ISSUE THREAD

**Issue by bengoodson22** [dgreif/ring#1542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Homebridge (and therefore HomeKit) doesn't register when the doorbell is pressed.
Ring App does register it. I can trigger a door open from both Homebridge and in the Home app.

### Expected behavior

When the intercom bell is pressed, I expected the doorbell to be triggered and to receive a notification through Apple Home.

### Screenshots

<img width="569" alt="Screenshot 2024-12-09 at 11 55 29" src="https://github.com/user-attachments/assets/870f7d78-fddb-418a-8dfa-9bba646f8d66">

### Homebridge Ring Config

```shell
{
    "refreshToken": xxx,
    "unbridgeCameras": true,
    "hideAlarmSirenSwitch": true,
    "platform": "Ring"
}
```

### OS

Raspbian

### Node.js Version

20.18.0

### NPM Version

v4.65.0

### Homebridge/HOOBs Version

1.8.5

### Homebridge Ring Plugin Version

v13.2.1

### Operating System

Raspbian

**Comment by tsightler** [comment]
Please follow these steps:

https://github.com/dgreif/ring/wiki/Notification-Troubleshooting

**Comment by Wendelburg** [comment]
I have the same issue - it worked fine for two times after your troubleshoot @tsightler - but now it's not working again...

**Comment by tsightler** [comment]
@Wendelburg Overall there is little that can be done here without debugging and at least some logs.  The fact that it works, even once, after following the troubleshooting would indicate that there is nothing wrong with how the code processes the push message, so it can really only be that the push message doesn't arrive.  The latest update included some fixes for push-receiver which should log messages if the push receiver process is not able to maintain connection to the socket, but we can't log anything if we don't receive a message.

Ideally, someone that own an intercom would actually troubleshoot the issue, as no maintainer currently owns one and I think it is unlikely we will, however, the process is identical to camera and doorbell, so I don't know why there are so many more complaints for intercoms vs other devices when the latter are far used.

**Comment by Wendelburg** [comment]
Hi again @tsightler! Thank you for your quick response - when I commented on this issue I may have tried it too often so that was my problem there - it seems to work for now :) And also thank you for the insight... Have a great Christmas time and a happy new year!
