### ISSUE TITLE
Message dropped as it could not be decrypted: crypto-key is missing

### ISSUE THREAD

**Issue by andrewk123** [dgreif/ring#1555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I am seeing the above error approximately once per minute.  Previously I was only seeing the error when the socket.io connection was regenerated.  I have also seen the following error a couple of times recently:

Error: Client destroyed
    at PushReceiver.#clearReady (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/@eneris/push-receiver/src/client.ts:197:32)
    at PushReceiver.destroy (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/@eneris/push-receiver/src/client.ts:127:25)
    at PushReceiver.#socketRetry (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/@eneris/push-receiver/src/client.ts:238:14)
    at Timeout.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/@eneris/push-receiver/src/client.ts:217:68)
    at listOnTimeout (node:internal/timers:594:17)
    at processTimers (node:internal/timers:529:7)

### To Reproduce

No action required

### Expected behavior

N/A

### Relevant log output

```shell
Message dropped as it could not be decrypted: crypto-key is missing
```

### Homebridge Ring Config

```shell
{
    "refreshToken": <REMOVED>",
    "unbridgeCameras": true,
    "hideDoorbellSwitch": true,
    "hideCameraSirenSwitch": true,
    "hideInHomeDoorbellSwitch": true,
    "hideAlarmSirenSwitch": true,
    "avoidSnapshotBatteryDrain": true,
    "debug": false,
    "hideDeviceIds": [
        "<REMOVED>"
    ],
    "locationIds": [
        "<REMOVED>"
    ],
    "name": "Ring",
    "_bridge": {
        "username": "<REMOVED>",
        "port": 36139
    },
    "platform": "Ring"
}
```

### OS

Raspian (Bookworm)

### Node.js Version

v22.12.0

### NPM Version

v10.9.0

### Homebridge/HOOBs Version

v1.8.5

### Homebridge Ring Plugin Version

v13.2.1

### Operating System

Raspian (Bookworm)

**Comment by tsightler** [comment]
Please post full logs from Homebridge startup and describe the functional issue you are having, messages in the logs are not really actionable as the messages you posted are expected in some circumstances and can't be avoided.  In general, it indicates issues connecting to push servers, so you should follow standard notification troubleshooting steps, however, if you are not having any issues then you can just ignore the messages.

**Comment by tsightler** [comment]
Closing as these are just messages in the log and no functional issue has been described.  Some of these messages are expected based on various factors so, if it doesn't impact functionality, there is nothing actionable here.  We can re-open if you are having an issue that you believe is related to these messages, but you will need to describe what issue you are having.
