### ISSUE TITLE
Switch to turn on/off motion recording on Stick Up Cam

### ISSUE THREAD

**Issue by Rubenfer** [dgreif/ring#156]
Hi,
It's possible to support on this plugin the ability to turn on and off the record motion on the Stick Up Cam? Now I need to open the Ring app, go to the camera settings and finally turn it on when I leave home. I would love that's automated activating a switch when I activate a scene in the Home app.
Thanks in advance.

**Comment by dgreif** [comment]
This feature is definitely possible and I can see the benefits in it.  One reason I hesitate to implement it is that Ring has some new features coming out in November that might satisfy your needs.  If you read the "Modes" section towards the bottom of https://shop.ring.com/pages/announcements, they are planning a feature that changes your motion zones based on your Ring Alarm state.  Do you have a more intricate schedule that you need to set up, or would Home/Away/Disarmed cover all of the scenarios for turning your motion recordings on and off?

**Comment by Rubenfer** [comment]
I’m in Spain and here we haven’t the Ring Alarm available, so I don’t know if this option will be available to ones who haven’t the alarm. Also, the location trigger could not work properly for my needs. Sometimes I’m not at home and I need to turn the cam on but I’m in other floor of my building or in other near building. 
I’ll appreciate you so much if you can implement this.

**Comment by Rubenfer** [comment]
Hi @dgreif, have you any news about this topic? Ring doesn't launch for the moment the Modes feature and the HomeKit support for turn the cams on/off could be great and a plus to this plugin.
Thanks in advance.

**Comment by dgreif** [comment]
@Rubenfer Ring has started rolling out their "Modes" feature.  Do you have access to that now?  

I still need to get Modes added to the homebridge plugin for those users that don't have an alarm, but that will be done under #200

**Comment by Rubenfer** [comment]
For the moment Modes is not available in Spain. I don’t know if it will be available in the future or not.

**Comment by dgreif** [comment]
I'm not sure why the _wouldn't_ release it there.  It's a great feature, especially for use cases like yours.  I'm going to close this issue in favor of #200.  Let me know when if/when you do receive Modes 🤞

**Comment by dgreif** [comment]
@Rubenfer I've release a new  Location Modes switch in v`7.1.0`.  Hopefully you get the feature soon, if you haven't already!

**Comment by Rubenfer** [comment]
Thank you @dgreif. For the moment I don’t have the modes feature available...
