### ISSUE TITLE
Failure to set alarm mode

### ISSUE THREAD

**Issue by danielway** [dgreif/ring#1562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

When attempting to set the alarm mode (arming or disarming), I get a `Failed to set alarm mode` error. I originally encountered this when setting up my Homebridge, but I'm also seeing it when using the [`ring-client-example`](https://github.com/dgreif/ring-client-example).

### To Reproduce

- Authenticate
- Attempt to arm or disarm an alarm
- Alarm state is unchanged causing an error

### Expected behavior

Expected the alarm state to change.

### Relevant log output

```shell
Error: Failed to set alarm mode to "none".  Sensors may require bypass, which can only be done in the Ring app.
    at Location.setAlarmMode (/workspaces/ring-client-example/node_modules/ring-client-api/lib/location.js:183:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async example (/workspaces/ring-client-example/lib/example.js:41:9)
```

### Additional context

I am able to arm/disarm using the keypad without issue so I don't think any sensors require bypass. I also do not have a Ring subscription, but I didn't think that was required.

I'm not sure where to go with debugging. It looks like this error comes from checking whether the alarm state changed, so I was wondering if there's some way to capture an error being returned from the Ring device with more specific information about why the request failed.

### OS

Linux and macOS

### Node.js Version

v22.12.0

### NPM Version

10.9.0

### ring-client-api

v11.7.1

### Operating System

Ubuntu and macOS

**Comment by tsightler** [comment]
> I also do not have a Ring subscription, but I didn't think that was required.

Digital arming/disarming does require a subscription if you are not grandfathered into this feature before they required a subscription.  Users that purchased Ring alarm after March 29th, 2023, require a subscription for digital arming/disarming and is clearly spelled out on the Ring website these days.  Are you able to arm/disarm using the Ring app?

**Comment by danielway** [comment]
I think that explains the issue then, thank you for your help.
