### ISSUE TITLE
No snapshot error with HomeKit

### ISSUE THREAD

**Issue by TateB** [dgreif/ring#159]
Hi,
When accessing my Ring Doorbell's camera through the home app, the HomeBridge throws some errors, and nothing ever loads on the home app.

> homebridge_1  | [2019-10-24 04:44:39] [Ring] Front Door Detected Motion
homebridge_1  | [2019-10-24 04:44:39] [Ring] Snapshot for Front Door Requested
homebridge_1  | [2019-10-24 04:45:30] [Ring] Snapshot failed to refresh after 60 attempts
homebridge_1  | [2019-10-24 04:45:30] [Ring] 404 from endpoint https://api.ring.com/clients_api/snapshots/image/xxxxxxx
homebridge_1  | [2019-10-24 04:45:30] [Ring] Failed to retrieve snapshot for Front Door (51.398s).  The camera currently reports that is it online
homebridge_1  | [2019-10-24 04:45:30] [Ring] Error: Not found with response: no snapshot

Tried restarting my phone and HomeKit hub however after doing that the error was still there.

**Comment by dgreif** [comment]
Try restarting the camera by pulling out the battery or cutting the power to it

**Comment by TateB** [comment]
Seemingly no way I could restart it (first gen doorbell), so I reset it. Still results in the same thing on homebridge.

**Comment by dgreif** [comment]
This is cause by either slow internet, or an issue with the camera not uploading the snapshots properly.  Can you see snapshots in the Ring app?  Just open the app and see if it gives you an updated image for that camera within a few seconds

**Comment by dgreif** [comment]
There isn't really anything else for me to do here.  Sometimes Ring just doesn't get an updated snapshot so there is nothing for us to fetch.  Happens a lot on battery cameras since you can't get a snapshot while they are recording
