### ISSUE TITLE
merging two of the example .ts files

### ISSUE THREAD

**Issue by privatesam** [dgreif/ring#162]
Sorry to be opening an issue here which is much more of a coding support request!  I don't know much about node so I'm trying to cobble something together.

I've had great success using the examples from [examples ](https://github.com/dgreif/ring/tree/master/examples)folder (I use `npx tsc` to convert the .ts files into something I can run with node on the command line of a debian container).

What I'm trying to do now is to merge the [example.ts](https://github.com/dgreif/ring/blob/master/examples/example.ts) file with the [browser-example.ts](https://github.com/dgreif/ring/blob/master/examples/browser-example.ts) so that I have a node js program running like in the example.ts listening for motion and dings, and from the browser-example.ts with a express web server getting ready to fire up the video stream upon receiving one of the events.

So I added the various bits and pieces needed for the express web server and camera etc and then created a function for the stream to be called, I called this function sippy:

```    
async function sippy () {
    console.log('Call has started')
    const sipSession = await camera.streamVideo({
      output: [
        '-preset',
        'veryfast',
        '-g',
        '25',
        '-sc_threshold',
        '0',
        '-f',
        'hls',
        '-hls_time',
        '2',
        '-hls_list_size',
        '6',
        '-hls_flags',
        'delete_segments',
        path.join('/root/video/', 'stream.m3u8')
      ]
    })
  
    sipSession.onCallEnded.subscribe(() => {
      console.log('Call has ended')
      //process.exit()
    })
  
    setTimeout(function() {
      console.log('Stopping call...')
      sipSession.stop()
    }, 1 * 30 * 1000) // Stop after 5 minutes.
  }  
```

And I call the function when a ding or motion is received like this:

```  
if (allCameras.length) {
    allCameras.forEach(camera => {
      camera.onNewDing.subscribe(ding => {
        const event =
          ding.kind === 'motion'
            ? 'Motion detected'
            : ding.kind === 'ding'
            ? 'Doorbell pressed'
            : 'Video started (${ding.kind})'
        console.log(
          `${event} on ${camera.name} camera. Ding id ${
            ding.id_str
          }.  Received at ${new Date()}`
          ,sippy()
        )
      })
    })
```

The problem is the stream (sippy function) starts when either a ding or motion happens but I think it then gets called again if another motion is detected.  Also I can't get the stream to end with the 10 second timeout I put - I had to comment out the `process.exit()` because it killed the whole node process.

I'm not sure the above makes sense but my whole .ts file is here:
[https://gist.github.com/privatesam/721f117bb6f2a018cc8496cd61246e27](https://gist.github.com/privatesam/721f117bb6f2a018cc8496cd61246e27)

Clearly this is a bit beyond the remit of what you built here but what I'm trying to do would be really useful to myself and a few others trying to grab the ring stream for short snippets upon an event so thank you inadvance if you have the time to have a quick look at this.

**Comment by dgreif** [comment]
It sounds like the main issue is that you need only one stream playing at a time.  The easiest route would be to add a variable to prevent two streams at once.  I made an updated gist that shows what I'm talking about:  https://gist.github.com/dgreif/e147568e28ca8259676a3f9004447dbd
Beyond that I think you are on your own. Good luck!
