### ISSUE TITLE
Video snapshots not updating.. Logs show to add cameras again? (iOS 13.2 issue?)

### ISSUE THREAD

**Issue by jasonhnz** [dgreif/ring#165]
No sure if this is anyway related to iOS 13.2 and secure video, but on load for Homebridge, it connects and says its adds in accessories ok but then states to re add cameras in again. 

The cameras from the ring devices had been working perfectly up until a few days ago.
In the home app, I can still click on the snapshots which are no longer updating and get to a live view OK. 

If I try to re add the cameras as from the initial Homebridge log output, adding a new accessory shows no new devices...

Has something changed due to iOS 13.2?

**Comment by jasonhnz** [comment]
Was able to remove all cameras in the end and re add and back to working perfectly.

**Comment by dgreif** [comment]
Homebridge logs the info for adding the cameras every time it starts, even if you already added the cameras to HomeKit.  This is just how homebridge does cameras, not anything wrong with your setup.  If everything is functional, then there shouldn't be any action needed

**Comment by jasonhnz** [comment]
Thanks, that's good to know. I ended up removing and adding the cameras again and that seemed to solve the lack of snapshot updates, however, I now do not receive any Homekit alerts for motion on any of my cams. In the setting fro Home, under each camera I have notifications on with no restrictions. I receive ring alerts but no Homekit ones now.  Is is possible that she of the settings are corrupted to cause this?
