### ISSUE TITLE
Alarm not found...

### ISSUE THREAD

**Issue by ascotinmpls** [dgreif/ring#168]
Do i need to do anything special to add my Alarm and other alarm related devices such as the sensors and door lock?  My cameras and lights were found without issue but my Alarms, sensors and locks do not get pulled into Homekit.

Thanks

**Comment by dgreif** [comment]
That’s really odd, there is nothing special you need to do. Is the alarm hub directly on your account, or is it a shared device that belongs to another account and is shared with you?

**Comment by ascotinmpls** [comment]
It is directly on my account which is the primary account

**Comment by dgreif** [comment]
Did you add the homebride "bridge" accessory to HomeKit?  If this is your first homebridge plugin, you will need to not only add the camera accessories, but the bridge as well

**Comment by ascotinmpls** [comment]
I had to double check that because I don’t recall doing it but it is listed.
![724E54F0-C1FC-41F6-BEF8-A8F0D12908CB](https://user-images.githubusercontent.com/24881861/68138801-f1d4e680-fedd-11e9-98ec-afa0cf17804f.jpeg)

**Comment by dgreif** [comment]
If you click into the homebridge bridge, does it show a list of accessories?

**Comment by ascotinmpls** [comment]
It does not.

**Comment by dgreif** [comment]
Ok, it's possible that you didn't add the homebridge "bridge" accessory properly.  In the Home app, click the `+` icon in the top right and see if the bridge is available to add.  This is the same process you used to add the individual cameras.

**Comment by ascotinmpls** [comment]
Thanks for the continued troubleshooting.  Homebridge isn’t available if I try and add a new accessory.

**Comment by ascotinmpls** [comment]
I just removed Homebridge as a “bridge” and added it again.  Issue solved.  Should have just started with that!!  😬. Thanks again!
