### ISSUE TITLE
Keypad and Base Station won't remove from favorites

### ISSUE THREAD

**Issue by kahnartist81** [dgreif/ring#169]
Like the title says, no matter how may times I try, I cannot get the keypad or base station to not be included in favorites. All other components of the alarm were able to be removed, but since these 2 are "not supported," maybe that's possibly why? Any suggestions?

**Comment by dgreif** [comment]
Sorry @kahnartist81, this is an issue with HomeKit and not something I can fix from the plugin.  The only thing I could add is a setting to permanently remove those two devices from HomeKit.  The Home app doesn't support them, but other apps like eve can be used to control the volume of the two devices.

**Comment by kahnartist81** [comment]
Understood. Is there a way to do like a "hideKeypad" style thing to the config file, so only people who want to go the extra mile can disable them?

**Comment by dgreif** [comment]
Yep, that's exactly what I'm thinking.  Most people don't mind having all of the devices in there (especially with the new grouping features in iOS 13), but there are definitely users who like to keep their Home app all cleaned up.

**Comment by kahnartist81** [comment]
Strangest thing just happened. I just tried one more time to deselect from favorites, and it actually worked! Weird glitch I'm sure, and it'll probably come back, but I thinking talking it out with you fixed it ;).

**Comment by dgreif** [comment]
I added a new hideUnsupportedServices option in v`5.10.0` which will hide the base station and keypad
