### ISSUE TITLE
what actions so you set up with the door button??

### ISSUE THREAD

**Issue by basesnow** [dgreif/ring#174]
Interested in seeing what people come up with for the buttons on the doorbell. Trying to drum up some creative ideas for my home.

**Comment by dgreif** [comment]
@basesnow I appreciate your desire to come up with good automation ideas, but unfortunately GitHub issues are not the best place to do that.  I would suggest you ask the same question over on https://www.reddit.com/r/homebridge/ as many of the homebridge-ring users actively participate in conversations there.  Hope you are enjoying the plugin tho!
