### ISSUE TITLE
Updating names of sensors in ring breaks device on homebridge. New Devices dont appear in homebridge

### ISSUE THREAD

**Issue by nickmacwiz** [dgreif/ring#175]

**Comment by dgreif** [comment]
Just tried it out and it looks like it's a bug with some code I recently added to prevent duplicate devices.  I'll get it fixed up asap

**Comment by nickmacwiz** [comment]
Ok no worries. Glad I am not the only one having the issue. I understand how these things go. I do a little programming myself and sometimes when you change a few lines it accidentally breaks something else lol. This plugin is the best. It’s the main reason I setup homebridge.

**Comment by CanonCan** [comment]
Hi @dgreif any updates? my homebridge broke when my nest account logged me out it took some finaggling but got everything back up except my ring pro doorbell is no longer showing even though homebridge isnt erroring on the plugin (5.9.1) using iOS 13.3 when i try to find it under accesories I only find 5 wemo devices that use the legit bridge and are already in Homekit

**Comment by dgreif** [comment]
Sorry, no update.  Been pretty busy and haven't had a chance to address this yet.

**Comment by CanonCan** [comment]
> Sorry, no update. Been pretty busy and haven't had a chance to address this yet.

You know what I tried again about 24hrs later and it’s showing up and I was able to add it again

**Comment by CanonCan** [comment]
I should add I cant actually connect to the camera on my ring pro its just found in Homekit now
