### ISSUE TITLE
snoozing motion in app doesn't snooze in homebridge

### ISSUE THREAD

**Issue by basesnow** [dgreif/ring#176]
I have ring set up on homebridge and it is awesome. Thanks for all the work that has been put into this. I have noticed 2 issues over the past couple of days

1. Today I was cleaning up in the front yard. I snoozed motion alerts in the app, but I continued to receive notifications from the home app. Is there something I missed in the set up? Is it possible to have that passed to homebridge so it also snoozes home homekit notifications?
2. I have been getting two notifications for every motion event. One without a picture, then another about 10 secs later with a picture

**Comment by dgreif** [comment]
1.  The motion snooze for the Ring events is specific to the Ring app on that particular device.  Snoozing notifications on one device does not snooze them on your other devices.  I don't think we even have access to those snooze requests from the API, sorry.

2.  That sounds like it's just the default behavior of HomeKit.  It waits a few seconds after the motion event to see if it can get a snapshot.  If the snapshot takes too long, then it shows a notification without it.  If the snapshot comes in a few seconds after that, it replaces the notification with the snapshot notification.  The timing is all based on your connection speed, Ring's response time, and HomeKit processing the snapshot and sending it to your device.
