### ISSUE TITLE
Motion events stopped working

### ISSUE THREAD

**Issue by giejay** [dgreif/ring#181]
Been using this library now for 2 weeks for my Ring Doorbell and it was all working fine until november 13 @ 20:00 CEST. Now my ring events keep getting triggered, but no matter what I try, Im not getting any motion events using the example.js. 

```
Listening for motion and doorbell presses on your cameras.
Doorbell pressed on Front Door camera. Ding id 6759486635027xxxxxx.  Received at Fri Nov 15 2019 12:00:25 GMT+0100 (Central European Standard Time)
Doorbell pressed on Front Door camera. Ding id 67594876443xxxxxx.  Received at Fri Nov 15 2019 12:04:21 GMT+0100 (Central European Standard Time)
```

As soon as I wave in front of the doorbell, a motion event is trigger in the app, so motion still works at least. Even my IFTTT trigger, which I used before I found this library, sends a motion event if I reenable that one again. 

It it just me or are others experiencing similar behaviour?

**Comment by odenisenko** [comment]
yes, according to log file the last event was 
```
2019-11-14 22:57:47,487 - ring_doorbell - INFO - [{'id': 6759269365505915465, 'id_str': '6759269365505915465', 'state': 'ringing
```

**Comment by dgreif** [comment]
Unfortunately Ring has been fairly unreliable with their polling endpoint over the last few weeks.  We have been discussing this issue in #166.  IFTTT has true support from Ring and probably has a more reliable means of getting motion notifications.  Closing this as a duplicate.

**Comment by michaeldimoudis** [comment]
I don’t use this library but I use this unofficial ring API, and yes my motion events for my Ring doorbell stopped working this month after nearly 2 years of good use. I’ve now switched to using IFTTT with a web hook call and it’s been working good. 2 years ago I remember the notification taking a while to come from IFTTT, but now it’s only a couple of seconds 👌

**Comment by giejay** [comment]
I'm also using IFTTT, for motion at least, and since it seems ring events also get ignored by this library since Monday, I also enabled ring events through IFTTT today. 
The only downside is that I'm using this lib for recording a short video of getting a snapshot, so now I should expose some sort of endpoint using express (which then uses this library) to get a snapshot in Telegram from Openhab

**Comment by dgreif** [comment]
IFTTT is using some other approach to get motion events, but it's not an API that is exposed in a way that we can reverse engineer it.  Unfortunately we are at the mercy of Ring on this one.  For some reason my doorbell pro is still getting motion events, but others aren't.  Not sure how Ring is differentiating these cases, but there is nothing I can do from my end to fix it unless Ring gives me official API support (which will likely never happen)
