### ISSUE TITLE
Stopped live stream from entrance

### ISSUE THREAD

**Issue by codyc1515** [dgreif/ring#183]
Hi there

Whenever viewing the video in the Home I always get the same two messages in my Homebridge log and the Home app indicates the camera is not responding. It seems like this is due to ports. Which ports do I need to open?

[11/17/2019, 23:51:02] [Ring] Waiting for stream data from Entrance (1.374s)
[11/17/2019, 23:51:12] [Ring] Stopped Live Stream for Entrance

**Comment by dgreif** [comment]
See https://github.com/dgreif/ring/wiki/Camera-Troubleshooting#check-your-logs-in-homebridge

**Comment by codyc1515** [comment]
Yes, I read that first but I have asked which specific ports which you have not listed there. That’s why I filed this issue.

**Comment by dgreif** [comment]
Ok, sorry it wasn't clear in the documentation.  The plugin uses a random port every time it starts a live stream, so there isn't a specific port that you can open/forward.  The instructions in the wiki are the best I can offer at this point
