### ISSUE TITLE
Minor typo in log message

### ISSUE THREAD

**Issue by jdberry** [dgreif/ring#188]
I apologize for pointing out for this minor nit, but this one always gets to me: "Snapshot for Front Door is still within it's life time (20.513s old)". There should be no apostrophe in "its". The form with the apostrophe is the contraction for "it is".

**Comment by dgreif** [comment]
@jdberry I appreciate the correction!  I always feel bad correcting grammar on other projects, but _it's_  embarrassing to see 😂
