### ISSUE TITLE
Delay doorbell press

### ISSUE THREAD

**Issue by krazyflipj** [dgreif/ring#189]
I setup my ring doorbell to play a certain song on my HomePod when the doorbell is pressed. Unfortunately there is a big delay. Any fix? I saw that you can adjust polling. What polling time you suggest?

**Comment by dgreif** [comment]
For you scenario, I would recommend setting `cameraDingsPollingSeconds: 1`.  This means the plugin will only wait 1 second between requests to see if there is any motion or doorbell presses available from the Ring servers.  The default is 2 seconds, so it might not make a huge difference, but that's the best we can do with the Ring API.
