### ISSUE TITLE
retrofit kit contact sensors don't show

### ISSUE THREAD

**Issue by kwalkington** [dgreif/ring#192]
other devices show up, but now those connected with the retrofit kit.

**Comment by dgreif** [comment]
I don't have a retrofit setup to test with so it will be hard to get anything added for it.  Do the retrofit sensors show up in your Ring app just like Ring contact/motion sensors?

**Comment by kwalkington** [comment]
Yes they do.  There is a different icon, but each zone of the retrofit kit
is in the sensor section, just like other sensors.

**Comment by kwalkington** [comment]
Do you think we can get these integrated?

**Comment by dgreif** [comment]
I think we definitely could, but I'm probably going to need to get my hands on a retrofit kit and some magnetic contacts.  I may be able to convince a friend or family member to "upgrade" to Ring from a hard-wired system, but no guarantees.  I'll let you know if I make any progress

**Comment by dgreif** [comment]
@kwalkington could you please run the command in https://github.com/dgreif/ring/wiki/Data-Discovery and post the resulting data here?  This will help me get a glimpse into how Ring is structuring the data for the retrofit kit.  Thanks!

**Comment by kwalkington** [comment]
SORRY FOR THE DELAY...

I don't think this worked as intended....

hoobs@hoobs:~/.hoobs/etc $ ring-device-data-cli
bash: ring-device-data-cli: command not found
hoobs@hoobs:~/.hoobs/etc $

**Comment by dgreif** [comment]
First, make sure you are on the latest version of the plugin. I added it yesterday so you may be a few versions behind. If it still doesn’t work, try the second command in that wiki article. Thanks for trying it!

**Comment by dgreif** [comment]
@kwalkington @mattb112 could one of you install v`6.2.0-alpha.0` and give it a try?  It should pull in all of the enabled zones from your retrofit alarm kit and show them as contact sensors in HomeKit.  Let me know how it works!

**Comment by dgreif** [comment]
@kwalkington @mattb112 either of you have a chance to test this?

**Comment by kwalkington** [comment]
Hey sorry!  I’ve been out of the loop!  I’ll try to help out soon.

**Comment by dgreif** [comment]
I'm releasing this in v`7.0.0`.  Would still really appreciate it if one of you could test it out for me.

**Comment by dgreif** [comment]
@kwalkington @mattb112, either of you able to test out the retrofit contact sensors?

**Comment by tsightler** [comment]
It definitely works from an API perspective as I've had several ring-mqtt users report success with the Retro Kit so far.

**Comment by kwalkington** [comment]
I've installed the latest update and the retrofit contact sensors are not
present.

**Comment by dgreif** [comment]
@kwalkington I'm at a bit of a loss here.  @tsightler confirmed the API side works well via `ring-mqtt`, and I double checked that his usage is almost identical to how I have it set up for homebridge.  Can you double check that it's not working on the latest version?  Did you restart your homebridge server after updating?  Do you see anything in the startup logs about the zone sensors (either that they are recognized and being added, or that they are being hidden)?

**Comment by mattb112** [comment]
@dgreif you are correct I am using @tsightler mqtt version and it has been working well for over a month

**Comment by kwalkington** [comment]
I am using 7.2.0.  I restarted homebridge service.  I'm using hoobs 3.1.22.  There are no retrofit items as accessories.  There is nothing about retrofit items in the logs.

**Comment by dgreif** [comment]
@kwalkington I’d love to get this working.  Any chance you could post your logs from Ring after a restart of homebridge? It should log the cached and hidden devices with their if, type, and name. That would help me confirm they are the device type I expect them to be

**Comment by kwalkington** [comment]
SURE.  SO JUST RESTART THE HOMEBRIDGE, AND THEN FIND THE RING CODE AND SEND
IT TO YOU?

**Comment by dgreif** [comment]
Yep, just all the logs that start with [Ring]. There are some above the main homebridge QR code so make sure to scroll up a bit

**Comment by dgreif** [comment]
@kwalkington any luck getting these logs?  I'd really like to get this feature finished.

**Comment by kwalkington** [comment]
I’m so sorry for the delay. I’m away from my system till next week. I’ll really try to get it to you then.

**Comment by dgreif** [comment]
@kwalkington no problem!  I actually was able to confirm with another user that the retrofit sensor zones are working properly 🎉.  Confirmed in https://github.com/dgreif/ring/issues/410#issuecomment-660427356
