### ISSUE TITLE
latest version doesn't send notification anymore

### ISSUE THREAD

**Issue by redeemer666** [dgreif/ring#193]
Hello,

after updating to the latest version of the plugin, I didn't receive any notification from the ring video doorbell pro. No changes were made to HomeKit, and other cameras, homekit-compatible, works as usual.

Can you please look into it?

**Comment by dgreif** [comment]
#166 describes some issues that have popped up on the Ring side.  If you are having issues with motion notifications, it's most likely not an issue with the plugin.  Have you tried reverting to the previous version to test if they are for-sure broken by the latest version?  Mine are working fine on the latest version

**Comment by redeemer666** [comment]
Don't have thought about reverting back. Thanks for the info, will try it and update this ticket.

Regards

**Comment by redeemer666** [comment]
Sorry not to update this issue for a long time, but it seems after a few days that everything come back to normal. I'm receiving notifications again. Thank you anyway for your help!
