### ISSUE TITLE
ring-client-api RingCamera.streamVideo() no longer works with active ding/session

### ISSUE THREAD

**Issue by DustinBryant** [dgreif/ring#194]
**Repro steps:**
1. Manually ring doorbell
2. Start browser-example ```npm run browser-example```

Does not generate any m3u8 or .ts files for an active ding/session and hangs on the streamVideo() call.

When there is no active session or ding and the example is ran it will create a live session and works as you'd expect.

**Comment by dgreif** [comment]
@DustinBryant sorry for the slow response.  Have you still been noticing issues with my homebridge plugin, but can try the example you gave it it's still failing for you

**Comment by DustinBryant** [comment]
I don't actually use homebridge. I'm using your node ring-client-api (https://www.npmjs.com/package/ring-client-api) with a module I created for MagicMirror(https://magicmirror.builders/) called MMM-Ring(https://github.com/DustinBryant/MMM-Ring). All of a sudden we stopped getting the live video feed. As I was debugging and figuring out what was going on I noticed it would hang on the streamVideo() call and never got to the point where it was generating the m3u8 or ts file types in the public folder designated with the ffmpeg option parameters. I decided to get a fresh clone of this repo and noticed the same issue exists in the browser-example where they hadn't before.

**Comment by pelaxa** [comment]
Any updates in this? This was one of the few things that made ring worthwhile.

**Comment by pelaxa** [comment]
I did some debugging and posted on issue #205.  
This came down to the getPublicIp function not working for me, which is using public-ip package.  The utils.ts file already has a backup to use Google STUN server to determine this and that works fine.

After that change, atleast running the example-recording works just fine.

**Comment by dgreif** [comment]
@DustinBryant please check out https://github.com/dgreif/ring/issues/211#issuecomment-570231847 and let me know if v`5.12.1` fixes the issue for you

**Comment by DustinBryant** [comment]
@pelaxa and @dgreif , this has fixed my issue. Thank you for your contributions.
