### ISSUE TITLE
Ring doorbell unresponsive outside of local network

### ISSUE THREAD

**Issue by fLyRhyTHeMz** [dgreif/ring#198]
Ring doorbell cam pro goes unresponsive when I leave my local network, but other 2 cams keep working. 

This may be an ios 13.3 issue but seems odd that the other cams and the alarm all function perfectly. 

Logs also show no errors. Snapshots are requested and received without issue. 

Video here: https://imgur.com/a/IB7OZZg

System: Mac mini 2018, Catalina, HOOBS 3.1

**Comment by dgreif** [comment]
Thanks for the video, definitely a good illustration!  Are your other cameras Ring cameras as well? There were similar issues when the iOS 13/13.1 betas first came out and one of the solutions was to update you home hub (apple tv, ipad, homepod) to the latest version to match what's on your phone.  See #124 for another instance of this.

**Comment by fLyRhyTHeMz** [comment]
I have 2 other with ring, Floodlight (this is the backyard which is shown in the clip) and an indoor. Both remained functional. Issue seems to have risen recently since latest public beta of 13.3 dropped a few days ago. Will take beta profiles off all my devices and apple tv and report back when next update is pushed. Feels like this may just be some glitch with the apple tv serving the feed outside the network.

**Comment by dgreif** [comment]
@fLyRhyTHeMz I'm gonna close this out since it's all on the apple side.  Let me know if you get it figured out
