### ISSUE TITLE
Support for “Modes” feature

### ISSUE THREAD

**Issue by jarvismeier** [dgreif/ring#200]
Would be great if there was a switch that could control the new modes feature in Ring.

**Comment by dgreif** [comment]
I knew "Modes" was coming, but didn't realize that had released it!  I'll definitely take a look and see if I can get it added.

**Comment by smockle** [comment]
I think the modes feature is still being rolled out—I don’t have it in the latest iOS app.

**Comment by dgreif** [comment]
I do have the feature apparently, but hadn't gotten a notification about it.  @jarvismeier do you have a Ring Alarm, or just cameras?  It seems like it behaves the same way as the alarm always has, but if you don't have one it might be different.

**Comment by jarvismeier** [comment]
I don’t have an alarm.  I was part of the beta a long time ago.  I think they forgot to turn it off on my account when it ended.

**Comment by denniswham** [comment]
Hi @dgreif, what kind of data do you need? Anyway I can help? I have the modes in the Ring app, and don't have Ring Alarm. By itself this feature works great, would love to have this added in my Home Assistant via this component https://github.com/tsightler/ring-alarm-mqtt

**Comment by dgreif** [comment]
I think for this particular feature, the easiest road will be for me to set up a second account with Ring and add just a camera to it.  I need to see the network requests that they make, which is a very involved setup.  I'll try to get to this in the next couple weeks

**Comment by jarvismeier** [comment]
Are you just needing pcap files generated from a switch?

**Comment by dgreif** [comment]
Yeah, basically.  The hard part is it's all encrypted traffic and the apps all use ssl cert pinning.  I set up a second account but it doesn't have Modes as an option, so I'll just have to wait until it gets rolled out a bit farther.  If you are somehow able to capture the requests for turning modes on/off, please let me know

**Comment by denniswham** [comment]
> Yeah, basically. The hard part is it's all encrypted traffic and the apps all use ssl cert pinning. I set up a second account but it doesn't have Modes as an option, so I'll just have to wait until it gets rolled out a bit farther. If you are somehow able to capture the requests for turning modes on/off, please let me know

Happy to help and provide those requests, but to be honest don't have a clue where to look for them. If you can give me some tips, I will try to get it and send to you.

**Comment by dgreif** [comment]
I actually got all of the data that I needed for this already by creating a second location on my account and have a working version. I just need to do some clean up and get it released. I’ll post here when it is ready for public testing. Sorry for the delay!

**Comment by denniswham** [comment]
No need to say sorry, and many thanks for your effort. If there's anything I can do, please shout :-)

**Comment by dgreif** [comment]
This has been released in v`7.1.0`.  Unfortunately it required another polling setup to periodically fetch the current mode for each location (`locationModePollingSeconds`, 20 seconds by default), but it should work reliably.  Let me know if any of you get a chance to try it out!
