### ISSUE TITLE
New issue streaming video from MacBook

### ISSUE THREAD

**Issue by byronavory** [dgreif/ring#203]
I recently started getting timeout errors when attempting to pull up video streams on Homekit on my MacBook. I frequently use this option when I am working on my computer because it is the quickest way to get a stream when there is commotion outside.

Below is the debug output:

Dec 19 13:34:00 homebridge homebridge[302]: [12/19/2019, 1:34:00 PM] [Ring] Preparing Live Stream for Driveway
Dec 19 13:34:01 homebridge homebridge[302]: [12/19/2019, 1:34:01 PM] [Ring] Waiting for stream data from Driveway (0.909s)
Dec 19 13:34:01 homebridge homebridge[302]: [12/19/2019, 1:34:01 PM] [Ring] Received stream data from Driveway (0.974s)
Dec 19 13:34:01 homebridge homebridge[302]: [12/19/2019, 1:34:01 PM] [Ring] Streaming active for Driveway
Dec 19 13:34:06 homebridge homebridge[302]: [12/19/2019, 1:34:06 PM] [Ring] ffmpeg stderr: [sdp @ 0x2538620] Could not find codec parameters for stream 1 (Video: h264, none): unspecified size
Dec 19 13:34:06 homebridge homebridge[302]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Dec 19 13:34:06 homebridge homebridge[302]: [12/19/2019, 1:34:06 PM] [Ring] ffmpeg stderr: Guessed Channel Layout for Input Stream #0.0 : mono
Dec 19 13:34:06 homebridge homebridge[302]: Input #0, sdp, from 'pipe:':
Dec 19 13:34:06 homebridge homebridge[302]: [12/19/2019, 1:34:06 PM] [Ring] ffmpeg stderr:   Metadata:
Dec 19 13:34:06 homebridge homebridge[302]:     title           : Talk
Dec 19 13:34:06 homebridge homebridge[302]:   Duration: N/A, start: 0.000000, bitrate: 64 kb/s
Dec 19 13:34:06 homebridge homebridge[302]: [12/19/2019, 1:34:06 PM] [Ring] ffmpeg stderr:     Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
Dec 19 13:34:06 homebridge homebridge[302]:     Stream #0:1: Video: h264, none, 90k tbr, 90k tbn, 180k tbc
Dec 19 13:34:06 homebridge homebridge[302]: [12/19/2019, 1:34:06 PM] [Ring] ffmpeg stderr: Stream mapping:
Dec 19 13:34:06 homebridge homebridge[302]:   Stream #0:0 -> #0:0 (pcm_mulaw (native) -> aac (libfdk_aac))
Dec 19 13:34:07 homebridge homebridge[302]: [12/19/2019, 1:34:07 PM] [Ring] ffmpeg stderr: Output #0, rtp, to 'srtp://192.168.1.120:59865?localrtcpport=43583&pkt_size=188':
Dec 19 13:34:07 homebridge homebridge[302]:   Metadata:
Dec 19 13:34:07 homebridge homebridge[302]:     title           : Talk
Dec 19 13:34:07 homebridge homebridge[302]:     encoder         : Lavf58.33.100
Dec 19 13:34:07 homebridge homebridge[302]:     Stream #0:0: Audio: aac (libfdk_aac) (ELD), 16000 Hz, mono, s16, 24 kb/s
Dec 19 13:34:07 homebridge homebridge[302]:     Metadata:
Dec 19 13:34:07 homebridge homebridge[302]:       encoder         : Lavc58.59.102 libfdk_aac
Dec 19 13:34:07 homebridge homebridge[302]: [12/19/2019, 1:34:07 PM] [Ring] ffmpeg stderr: [libfdk_aac @ 0x259fa40] Queue input is backward in time
Dec 19 13:34:07 homebridge homebridge[302]: [12/19/2019, 1:34:07 PM] [Ring] ffmpeg stderr: size=      19kB time=00:00:05.59 bitrate=  28.1kbits/s speed=11.1x
Dec 19 13:34:07 homebridge homebridge[302]: [12/19/2019, 1:34:07 PM] [Ring] ffmpeg stderr: size=      21kB time=00:00:06.13 bitrate=  28.1kbits/s speed=5.98x
Dec 19 13:34:08 homebridge homebridge[302]: [12/19/2019, 1:34:08 PM] [Ring] ffmpeg stderr: size=      23kB time=00:00:06.61 bitrate=  28.1kbits/s speed=4.34x
Dec 19 13:34:09 homebridge homebridge[302]: [12/19/2019, 1:34:09 PM] [Ring] ffmpeg stderr: size=      25kB time=00:00:07.15 bitrate=  28.1kbits/s speed= 3.5x
Dec 19 13:34:09 homebridge homebridge[302]: [12/19/2019, 1:34:09 PM] [Ring] ffmpeg stderr: size=      26kB time=00:00:07.65 bitrate=  28.0kbits/s speed=3.01x
Dec 19 13:34:10 homebridge homebridge[302]: [12/19/2019, 1:34:10 PM] [Ring] ffmpeg stderr: size=      28kB time=00:00:08.17 bitrate=  28.0kbits/s speed=2.67x
Dec 19 13:34:10 homebridge homebridge[302]: [12/19/2019, 1:34:10 PM] [Ring] ffmpeg stderr: size=      30kB time=00:00:08.65 bitrate=  28.0kbits/s speed=2.43x
Dec 19 13:34:11 homebridge homebridge[302]: [12/19/2019, 1:34:11 PM] [Ring] ffmpeg stderr: size=      31kB time=00:00:09.19 bitrate=  28.0kbits/s speed=2.25x
Dec 19 13:34:11 homebridge homebridge[302]: [12/19/2019, 1:34:11 PM] [Ring] ffmpeg stderr: size=      33kB time=00:00:09.67 bitrate=  28.0kbits/s speed=2.11x
Dec 19 13:34:12 homebridge homebridge[302]: [12/19/2019, 1:34:12 PM] [Ring] ffmpeg stderr: size=      35kB time=00:00:10.21 bitrate=  28.0kbits/s speed=   2x
Dec 19 13:34:12 homebridge homebridge[302]: [12/19/2019, 1:34:12 PM] [Ring] ffmpeg stderr: size=      37kB time=00:00:10.73 bitrate=  28.0kbits/s speed=1.91x
Dec 19 13:34:13 homebridge homebridge[302]: [12/19/2019, 1:34:13 PM] [Ring] ffmpeg stderr: size=      38kB time=00:00:11.23 bitrate=  28.0kbits/s speed=1.83x
Dec 19 13:34:13 homebridge homebridge[302]: [12/19/2019, 1:34:13 PM] [Ring] ffmpeg stderr: size=      40kB time=00:00:11.71 bitrate=  28.0kbits/s speed=1.77x
Dec 19 13:34:14 homebridge homebridge[302]: [12/19/2019, 1:34:14 PM] [Ring] ffmpeg stderr: size=      42kB time=00:00:12.25 bitrate=  28.0kbits/s speed=1.72x
Dec 19 13:34:14 homebridge homebridge[302]: [12/19/2019, 1:34:14 PM] [Ring] ffmpeg stderr: size=      43kB time=00:00:12.75 bitrate=  27.9kbits/s speed=1.67x
Dec 19 13:34:15 homebridge homebridge[302]: [12/19/2019, 1:34:15 PM] [Ring] ffmpeg stderr: size=      45kB time=00:00:13.26 bitrate=  27.9kbits/s speed=1.63x
Dec 19 13:34:15 homebridge homebridge[302]: [12/19/2019, 1:34:15 PM] [Ring] ffmpeg stderr: size=      47kB time=00:00:13.77 bitrate=  27.9kbits/s speed=1.59x
Dec 19 13:34:16 homebridge homebridge[302]: [12/19/2019, 1:34:16 PM] [Ring] ffmpeg stderr: size=      49kB time=00:00:14.25 bitrate=  27.9kbits/s speed=1.56x
Dec 19 13:34:16 homebridge homebridge[302]: [12/19/2019, 1:34:16 PM] [Ring] ffmpeg stderr: size=      50kB time=00:00:14.79 bitrate=  27.9kbits/s speed=1.53x
Dec 19 13:34:17 homebridge homebridge[302]: [12/19/2019, 1:34:17 PM] [Ring] ffmpeg stderr: size=      52kB time=00:00:15.27 bitrate=  27.9kbits/s speed= 1.5x
Dec 19 13:34:17 homebridge homebridge[302]: [12/19/2019, 1:34:17 PM] [Ring] ffmpeg stderr: size=      54kB time=00:00:15.81 bitrate=  27.9kbits/s speed=1.48x
Dec 19 13:34:18 homebridge homebridge[302]: [12/19/2019, 1:34:18 PM] [Ring] ffmpeg stderr: size=      56kB time=00:00:16.29 bitrate=  27.9kbits/s speed=1.45x
Dec 19 13:34:18 homebridge homebridge[302]: [12/19/2019, 1:34:18 PM] [Ring] ffmpeg stderr: size=      57kB time=00:00:16.83 bitrate=  27.9kbits/s speed=1.44x
Dec 19 13:34:19 homebridge homebridge[302]: [12/19/2019, 1:34:19 PM] [Ring] ffmpeg stderr: size=      59kB time=00:00:17.35 bitrate=  27.9kbits/s speed=1.42x
Dec 19 13:34:19 homebridge homebridge[302]: [12/19/2019, 1:34:19 PM] [Ring] ffmpeg stderr: size=      61kB time=00:00:17.83 bitrate=  27.9kbits/s speed= 1.4x
Dec 19 13:34:20 homebridge homebridge[302]: [12/19/2019, 1:34:20 PM] [Ring] ffmpeg stderr: size=      63kB time=00:00:18.37 bitrate=  27.9kbits/s speed=1.39x
Dec 19 13:34:20 homebridge homebridge[302]: [12/19/2019, 1:34:20 PM] [Ring] ffmpeg stderr: size=      64kB time=00:00:18.85 bitrate=  27.9kbits/s speed=1.37x
Dec 19 13:34:21 homebridge homebridge[302]: [12/19/2019, 1:34:21 PM] [Ring] ffmpeg stderr: size=      66kB time=00:00:19.39 bitrate=  27.9kbits/s speed=1.36x
Dec 19 13:34:21 homebridge homebridge[302]: [12/19/2019, 1:34:21 PM] [Ring] ffmpeg stderr: size=      68kB time=00:00:19.87 bitrate=  27.9kbits/s speed=1.34x
Dec 19 13:34:22 homebridge homebridge[302]: [12/19/2019, 1:34:22 PM] [Ring] ffmpeg stderr: size=      70kB time=00:00:20.41 bitrate=  27.9kbits/s speed=1.33x
Dec 19 13:34:22 homebridge homebridge[302]: [12/19/2019, 1:34:22 PM] [Ring] ffmpeg stderr: size=      71kB time=00:00:20.95 bitrate=  27.9kbits/s speed=1.32x
Dec 19 13:34:23 homebridge homebridge[302]: [12/19/2019, 1:34:23 PM] [Ring] ffmpeg stderr: size=      73kB time=00:00:21.43 bitrate=  27.9kbits/s speed=1.31x
Dec 19 13:34:23 homebridge homebridge[302]: [12/19/2019, 1:34:23 PM] [Ring] ffmpeg stderr: size=      75kB time=00:00:21.97 bitrate=  27.9kbits/s speed= 1.3x
Dec 19 13:34:24 homebridge homebridge[302]: [12/19/2019, 1:34:24 PM] [Ring] ffmpeg stderr: size=      77kB time=00:00:22.49 bitrate=  27.9kbits/s speed=1.29x
Dec 19 13:34:24 homebridge homebridge[302]: [12/19/2019, 1:34:24 PM] [Ring] ffmpeg stderr: size=      78kB time=00:00:22.97 bitrate=  27.9kbits/s speed=1.28x
Dec 19 13:34:25 homebridge homebridge[302]: [12/19/2019, 1:34:25 PM] [Ring] ffmpeg stderr: size=      80kB time=00:00:23.51 bitrate=  27.9kbits/s speed=1.28x
Dec 19 13:34:25 homebridge homebridge[302]: [12/19/2019, 1:34:25 PM] [Ring] ffmpeg stderr: size=      82kB time=00:00:24.02 bitrate=  27.9kbits/s speed=1.27x
Dec 19 13:34:26 homebridge homebridge[302]: [12/19/2019, 1:34:26 PM] [Ring] ffmpeg stderr: size=      84kB time=00:00:24.53 bitrate=  27.9kbits/s speed=1.26x
Dec 19 13:34:26 homebridge homebridge[302]: [12/19/2019, 1:34:26 PM] [Ring] ffmpeg stderr: size=      85kB time=00:00:25.01 bitrate=  27.9kbits/s speed=1.26x
Dec 19 13:34:27 homebridge homebridge[302]: [12/19/2019, 1:34:27 PM] [Ring] ffmpeg stderr: size=      87kB time=00:00:25.53 bitrate=  27.9kbits/s speed=1.25x
Dec 19 13:34:27 homebridge homebridge[302]: [12/19/2019, 1:34:27 PM] [Ring] ffmpeg stderr: size=      89kB time=00:00:26.07 bitrate=  27.9kbits/s speed=1.24x
Dec 19 13:34:28 homebridge homebridge[302]: [12/19/2019, 1:34:28 PM] [Ring] ffmpeg stderr: size=      91kB time=00:00:26.55 bitrate=  28.0kbits/s speed=1.24x
Dec 19 13:34:28 homebridge homebridge[302]: [12/19/2019, 1:34:28 PM] [Ring] ffmpeg stderr: size=      92kB time=00:00:27.10 bitrate=  27.9kbits/s speed=1.23x
Dec 19 13:34:29 homebridge homebridge[302]: [12/19/2019, 1:34:29 PM] [Ring] ffmpeg stderr: size=      94kB time=00:00:27.61 bitrate=  27.9kbits/s speed=1.23x
Dec 19 13:34:29 homebridge homebridge[302]: [12/19/2019, 1:34:29 PM] [Ring] ffmpeg stderr: size=      96kB time=00:00:28.09 bitrate=  28.0kbits/s speed=1.22x
Dec 19 13:34:30 homebridge homebridge[302]: [12/19/2019, 1:34:30 PM] [Ring] ffmpeg stderr: size=      97kB time=00:00:28.57 bitrate=  28.0kbits/s speed=1.22x
Dec 19 13:34:30 homebridge homebridge[302]: [12/19/2019, 1:34:30 PM] [Ring] Stopped Live Stream for Driveway
Dec 19 13:34:40 homebridge homebridge[302]: [12/19/2019, 1:34:40 PM] [Ring] ffmpeg stderr: pipe:: Connection timed out
Dec 19 13:34:40 homebridge homebridge[302]: [12/19/2019, 1:34:40 PM] [Ring] ffmpeg stderr: size=      99kB time=00:00:29.05 bitrate=  28.0kbits/s speed=0.855x
Dec 19 13:34:40 homebridge homebridge[302]: video:0kB audio:85kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 16.839489%
Dec 19 13:34:40 homebridge homebridge[302]: [12/19/2019, 1:34:40 PM] [Ring] ffmpeg stderr: Exiting normally, received signal 15.
Dec 19 13:34:40 homebridge homebridge[302]: [12/19/2019, 1:34:40 PM] [Ring] ffmpeg exited with code 255
Dec 19 13:34:41 homebridge homebridge[302]: [12/19/2019, 1:34:41 PM] [Config] [HapClient] Discovery :: Ended
Dec 19 13:35:14 homebridge homebridge[302]: [12/19/2019, 1:35:14 PM] [Ring] Preparing Live Stream for Driveway
Dec 19 13:35:15 homebridge homebridge[302]: [12/19/2019, 1:35:15 PM] [Ring] Waiting for stream data from Driveway (0.855s)
Dec 19 13:35:15 homebridge homebridge[302]: [12/19/2019, 1:35:15 PM] [Ring] Received stream data from Driveway (0.965s)
Dec 19 13:35:15 homebridge homebridge[302]: [12/19/2019, 1:35:15 PM] [Ring] Streaming active for Driveway
Dec 19 13:35:20 homebridge homebridge[302]: [12/19/2019, 1:35:20 PM] [Ring] ffmpeg stderr: [sdp @ 0x2088620] Could not find codec parameters for stream 1 (Video: h264, none): unspecified size
Dec 19 13:35:20 homebridge homebridge[302]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Dec 19 13:35:20 homebridge homebridge[302]: Guessed Channel Layout for Input Stream #0.0 : mono
Dec 19 13:35:20 homebridge homebridge[302]: Input #0, sdp, from 'pipe:':
Dec 19 13:35:20 homebridge homebridge[302]:   Metadata:
Dec 19 13:35:20 homebridge homebridge[302]:     title           : Talk
Dec 19 13:35:20 homebridge homebridge[302]:   Duration: N/A, start: 0.000000, bitrate: 64 kb/s
Dec 19 13:35:20 homebridge homebridge[302]:     Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
Dec 19 13:35:20 homebridge homebridge[302]:     Stream #0:1: Video: h264, none, 90k tbr, 90k tbn, 180k tbc
Dec 19 13:35:20 homebridge homebridge[302]: Stream mapping:
Dec 19 13:35:20 homebridge homebridge[302]:   Stream #0:0 -> #0:0 (pcm_mulaw (native) -> aac (libfdk_aac))
Dec 19 13:35:20 homebridge homebridge[302]: [12/19/2019, 1:35:20 PM] [Ring] ffmpeg stderr: Output #0, rtp, to 'srtp://192.168.1.120:53300?localrtcpport=34245&pkt_size=188':
Dec 19 13:35:20 homebridge homebridge[302]:   Metadata:
Dec 19 13:35:20 homebridge homebridge[302]:     title           : Talk
Dec 19 13:35:20 homebridge homebridge[302]: [12/19/2019, 1:35:20 PM] [Ring] ffmpeg stderr:     encoder         : Lavf58.33.100
Dec 19 13:35:20 homebridge homebridge[302]:     Stream #0:0: Audio: aac (libfdk_aac) (ELD), 16000 Hz, mono, s16, 24 kb/s
Dec 19 13:35:20 homebridge homebridge[302]:     Metadata:
Dec 19 13:35:20 homebridge homebridge[302]:       encoder         : Lavc58.59.102 libfdk_aac
Dec 19 13:35:20 homebridge homebridge[302]: [12/19/2019, 1:35:20 PM] [Ring] ffmpeg stderr: size=      19kB time=00:00:05.55 bitrate=  28.3kbits/s speed=10.8x
Dec 19 13:35:21 homebridge homebridge[302]: [12/19/2019, 1:35:21 PM] [Ring] ffmpeg stderr: size=      21kB time=00:00:06.07 bitrate=  28.1kbits/s speed=5.85x
Dec 19 13:35:21 homebridge homebridge[302]: [12/19/2019, 1:35:21 PM] [Ring] ffmpeg stderr: size=      23kB time=00:00:06.61 bitrate=  28.1kbits/s speed=4.24x
Dec 19 13:35:22 homebridge homebridge[302]: [12/19/2019, 1:35:22 PM] [Ring] ffmpeg stderr: size=      24kB time=00:00:07.12 bitrate=  28.1kbits/s speed=3.43x
Dec 19 13:35:22 homebridge homebridge[302]: [12/19/2019, 1:35:22 PM] [Ring] ffmpeg stderr: size=      26kB time=00:00:07.63 bitrate=  28.1kbits/s speed=2.96x
Dec 19 13:35:23 homebridge homebridge[302]: [12/19/2019, 1:35:23 PM] [Ring] ffmpeg stderr: size=      28kB time=00:00:08.11 bitrate=  28.1kbits/s speed=2.64x
Dec 19 13:35:23 homebridge homebridge[302]: [12/19/2019, 1:35:23 PM] [Ring] ffmpeg stderr: size=      30kB time=00:00:08.63 bitrate=  28.1kbits/s speed= 2.4x
Dec 19 13:35:24 homebridge homebridge[302]: [12/19/2019, 1:35:24 PM] [Ring] ffmpeg stderr: size=      31kB time=00:00:09.17 bitrate=  28.1kbits/s speed=2.23x
Dec 19 13:35:24 homebridge homebridge[302]: [12/19/2019, 1:35:24 PM] [Ring] ffmpeg stderr: size=      33kB time=00:00:09.68 bitrate=  28.1kbits/s speed=2.09x
Dec 19 13:35:25 homebridge homebridge[302]: [12/19/2019, 1:35:25 PM] [Ring] ffmpeg stderr: size=      35kB time=00:00:10.23 bitrate=  27.8kbits/s speed=1.99x
Dec 19 13:35:25 homebridge homebridge[302]: [12/19/2019, 1:35:25 PM] [Ring] ffmpeg stderr: size=      37kB time=00:00:10.77 bitrate=  27.8kbits/s speed=1.91x
Dec 19 13:35:26 homebridge homebridge[302]: [12/19/2019, 1:35:26 PM] [Ring] ffmpeg stderr: [libfdk_aac @ 0x20efa40] Queue input is backward in time
Dec 19 13:35:26 homebridge homebridge[302]: [12/19/2019, 1:35:26 PM] [Ring] ffmpeg stderr: [rtp @ 0x20eed30] Non-monotonous DTS in output stream 0:0; previous: 175548, current: 175072; changing to 175548. This may result in incorrect timestamps in the output file.
Dec 19 13:35:26 homebridge homebridge[302]: [12/19/2019, 1:35:26 PM] [Ring] ffmpeg stderr: size=      38kB time=00:00:11.23 bitrate=  28.0kbits/s speed=1.82x
Dec 19 13:35:26 homebridge homebridge[302]: [12/19/2019, 1:35:26 PM] [Ring] ffmpeg stderr: size=      40kB time=00:00:11.71 bitrate=  28.0kbits/s speed=1.75x
Dec 19 13:35:27 homebridge homebridge[302]: [12/19/2019, 1:35:27 PM] [Ring] ffmpeg stderr: size=      42kB time=00:00:12.24 bitrate=  27.9kbits/s speed= 1.7x
Dec 19 13:35:27 homebridge homebridge[302]: [12/19/2019, 1:35:27 PM] [Ring] ffmpeg stderr: size=      43kB time=00:00:12.75 bitrate=  27.9kbits/s speed=1.66x
Dec 19 13:35:28 homebridge homebridge[302]: [12/19/2019, 1:35:28 PM] [Ring] ffmpeg stderr: size=      45kB time=00:00:13.26 bitrate=  27.9kbits/s speed=1.61x
Dec 19 13:35:28 homebridge homebridge[302]: [12/19/2019, 1:35:28 PM] [Ring] ffmpeg stderr: size=      47kB time=00:00:13.77 bitrate=  27.9kbits/s speed=1.58x
Dec 19 13:35:29 homebridge homebridge[302]: [12/19/2019, 1:35:29 PM] [Ring] ffmpeg stderr: size=      49kB time=00:00:14.31 bitrate=  27.8kbits/s speed=1.55x
Dec 19 13:35:29 homebridge homebridge[302]: [12/19/2019, 1:35:29 PM] [Ring] ffmpeg stderr: size=      50kB time=00:00:14.83 bitrate=  27.8kbits/s speed=1.52x
Dec 19 13:35:30 homebridge homebridge[302]: [12/19/2019, 1:35:30 PM] [Ring] ffmpeg stderr: [libfdk_aac @ 0x20efa40] Queue input is backward in time
Dec 19 13:35:30 homebridge homebridge[302]: [12/19/2019, 1:35:30 PM] [Ring] ffmpeg stderr: [rtp @ 0x20eed30] Non-monotonous DTS in output stream 0:0; previous: 239348, current: 239200; changing to 239348. This may result in incorrect timestamps in the output file.
Dec 19 13:35:30 homebridge homebridge[302]: [12/19/2019, 1:35:30 PM] [Ring] ffmpeg stderr: size=      52kB time=00:00:15.33 bitrate=  27.9kbits/s speed=1.49x
Dec 19 13:35:30 homebridge homebridge[302]: [12/19/2019, 1:35:30 PM] [Ring] ffmpeg stderr: size=      54kB time=00:00:15.81 bitrate=  27.9kbits/s speed=1.47x
Dec 19 13:35:31 homebridge homebridge[302]: [12/19/2019, 1:35:31 PM] [Ring] ffmpeg stderr: size=      56kB time=00:00:16.31 bitrate=  27.9kbits/s speed=1.45x
Dec 19 13:35:31 homebridge homebridge[302]: [12/19/2019, 1:35:31 PM] [Ring] ffmpeg stderr: size=      57kB time=00:00:16.85 bitrate=  27.9kbits/s speed=1.43x
Dec 19 13:35:32 homebridge homebridge[302]: [12/19/2019, 1:35:32 PM] [Ring] ffmpeg stderr: size=      59kB time=00:00:17.33 bitrate=  27.9kbits/s speed=1.41x
Dec 19 13:35:33 homebridge homebridge[302]: [12/19/2019, 1:35:33 PM] [Ring] ffmpeg stderr: size=      61kB time=00:00:17.85 bitrate=  27.9kbits/s speed=1.39x
Dec 19 13:35:33 homebridge homebridge[302]: [12/19/2019, 1:35:33 PM] [Ring] ffmpeg stderr: size=      62kB time=00:00:18.35 bitrate=  27.9kbits/s speed=1.38x
Dec 19 13:35:34 homebridge homebridge[302]: [12/19/2019, 1:35:34 PM] [Ring] ffmpeg stderr: size=      64kB time=00:00:18.89 bitrate=  27.9kbits/s speed=1.37x
Dec 19 13:35:34 homebridge homebridge[302]: [12/19/2019, 1:35:34 PM] [Ring] ffmpeg stderr: size=      66kB time=00:00:19.40 bitrate=  27.9kbits/s speed=1.35x
Dec 19 13:35:35 homebridge homebridge[302]: [12/19/2019, 1:35:35 PM] [Ring] ffmpeg stderr: size=      68kB time=00:00:19.91 bitrate=  27.9kbits/s speed=1.34x
Dec 19 13:35:35 homebridge homebridge[302]: [12/19/2019, 1:35:35 PM] [Ring] ffmpeg stderr: size=      69kB time=00:00:20.41 bitrate=  27.9kbits/s speed=1.33x
Dec 19 13:35:36 homebridge homebridge[302]: [12/19/2019, 1:35:36 PM] [Ring] ffmpeg stderr: size=      71kB time=00:00:20.93 bitrate=  27.9kbits/s speed=1.32x
Dec 19 13:35:36 homebridge homebridge[302]: [12/19/2019, 1:35:36 PM] [Ring] ffmpeg stderr: size=      73kB time=00:00:21.47 bitrate=  27.9kbits/s speed=1.31x
Dec 19 13:35:37 homebridge homebridge[302]: [12/19/2019, 1:35:37 PM] [Ring] ffmpeg stderr: size=      75kB time=00:00:21.95 bitrate=  27.9kbits/s speed= 1.3x
Dec 19 13:35:37 homebridge homebridge[302]: [12/19/2019, 1:35:37 PM] [Ring] ffmpeg stderr: size=      77kB time=00:00:22.49 bitrate=  27.9kbits/s speed=1.29x
Dec 19 13:35:38 homebridge homebridge[302]: [12/19/2019, 1:35:38 PM] [Ring] ffmpeg stderr: size=      78kB time=00:00:22.97 bitrate=  27.9kbits/s speed=1.28x
Dec 19 13:35:38 homebridge homebridge[302]: [12/19/2019, 1:35:38 PM] [Ring] ffmpeg stderr: size=      80kB time=00:00:23.49 bitrate=  27.9kbits/s speed=1.27x
Dec 19 13:35:39 homebridge homebridge[302]: [12/19/2019, 1:35:39 PM] [Ring] ffmpeg stderr: size=      82kB time=00:00:23.96 bitrate=  27.9kbits/s speed=1.26x
Dec 19 13:35:39 homebridge homebridge[302]: [12/19/2019, 1:35:39 PM] [Ring] ffmpeg stderr: size=      83kB time=00:00:24.53 bitrate=  27.9kbits/s speed=1.26x
Dec 19 13:35:40 homebridge homebridge[302]: [12/19/2019, 1:35:40 PM] [Ring] ffmpeg stderr: size=      85kB time=00:00:25.01 bitrate=  27.9kbits/s speed=1.25x
Dec 19 13:35:40 homebridge homebridge[302]: [12/19/2019, 1:35:40 PM] [Ring] ffmpeg stderr: size=      87kB time=00:00:25.55 bitrate=  27.9kbits/s speed=1.25x
Dec 19 13:35:41 homebridge homebridge[302]: [12/19/2019, 1:35:41 PM] [Ring] ffmpeg stderr: size=      89kB time=00:00:26.03 bitrate=  27.9kbits/s speed=1.24x
Dec 19 13:35:41 homebridge homebridge[302]: [12/19/2019, 1:35:41 PM] [Ring] ffmpeg stderr: size=      90kB time=00:00:26.55 bitrate=  27.9kbits/s speed=1.23x
Dec 19 13:35:42 homebridge homebridge[302]: [12/19/2019, 1:35:42 PM] [Ring] ffmpeg stderr: size=      92kB time=00:00:27.07 bitrate=  27.9kbits/s speed=1.23x
Dec 19 13:35:42 homebridge homebridge[302]: [12/19/2019, 1:35:42 PM] [Ring] Snapshot for Front Door Requested
Dec 19 13:35:42 homebridge homebridge[302]: [12/19/2019, 1:35:42 PM] [Ring] Snapshot for Front Door is still within its life time (118.179s old)
Dec 19 13:35:42 homebridge homebridge[302]: [12/19/2019, 1:35:42 PM] [Ring] Snapshot for Front Door Received (0.003s)
Dec 19 13:35:42 homebridge homebridge[302]: [12/19/2019, 1:35:42 PM] [Ring] Snapshot for Driveway Requested
Dec 19 13:35:42 homebridge homebridge[302]: [12/19/2019, 1:35:42 PM] [Ring] ffmpeg stderr: size=      93kB time=00:00:27.48 bitrate=  27.8kbits/s speed=1.22x
Dec 19 13:35:43 homebridge homebridge[302]: [12/19/2019, 1:35:43 PM] [Ring] ffmpeg stderr: size=      96kB time=00:00:28.14 bitrate=  27.8kbits/s speed=1.22x
Dec 19 13:35:43 homebridge homebridge[302]: [12/19/2019, 1:35:43 PM] [Ring] ffmpeg stderr: size=      97kB time=00:00:28.65 bitrate=  27.8kbits/s speed=1.21x
Dec 19 13:35:44 homebridge homebridge[302]: [12/19/2019, 1:35:44 PM] [Ring] ffmpeg stderr: size=      99kB time=00:00:29.13 bitrate=  27.8kbits/s speed=1.21x
Dec 19 13:35:44 homebridge homebridge[302]: [12/19/2019, 1:35:44 PM] [Ring] Snapshot for Driveway Received (2.111s)
Dec 19 13:35:44 homebridge homebridge[302]: [12/19/2019, 1:35:44 PM] [Ring] ffmpeg stderr: size=     101kB time=00:00:29.61 bitrate=  27.8kbits/s speed= 1.2x
Dec 19 13:35:44 homebridge homebridge[302]: [12/19/2019, 1:35:44 PM] [Ring] Stopped Live Stream for Driveway

**Comment by dgreif** [comment]
Could you clarify what you mean by "timeout errors"?  Is it failing to start the video stream, or are the video streams ending before you close the window in the Home app?  The logs that you provided look like a normal streaming session without anything going wrong...

**Comment by byronavory** [comment]
The stream never starts. 

Thanks,
Byron A. Couch
byronavory@gmail.com
 <mailto:byronavory@gmail.com>c: 614.530.6060 | f: 614.398.2332
https://www.linkedin.com//in/byroncouch <https://www.linkedin.com//in/byroncouch>

**Comment by dgreif** [comment]
Weird, that log looks like a perfectly good stream.  My guess is that they issue is on the apple side.  Make sure you have the latest firmware on your home hub (apple tv/ipad/homepod) and your mac.  Does it work sometimes and not others, or not at all now?

**Comment by dgreif** [comment]
@byronavory any updates?

**Comment by byronavory** [comment]
It is working now. It appears to resolved itself after the homebridge-ring v5.12.0. I am not sure if it is related or note. Nothing in the release notes suggest there was any change to video processing. 


Thanks,
Byron A. Couch
byronavory@gmail.com
 <mailto:byronavory@gmail.com>c: 614.530.6060 | f: 614.398.2332
https://www.linkedin.com//in/byroncouch <https://www.linkedin.com//in/byroncouch>
