### ISSUE TITLE
Trying to pull down all my ring videos but getRecord() hangs 

### ISSUE THREAD

**Issue by david-olshefski** [dgreif/ring#204]
HI,

   I am trying to pull down all my videos, or at least a bunch of them.  
It hangs on the getRecording(dingId), which should return a URL. 

Any ideas?
  

`import { RingApi } from 'ring-client-api'

const ringApi = new RingApi({
  email: 'my_email@gmail.com',
  password: 'my_pwd', 
  cameraStatusPollingSeconds: 20,
  cameraDingsPollingSeconds: 2,
});

async function do_it() {
  
  try {

    console.log("Getting cameras, I have only one")
    const cameras = await ringApi.getCameras()

    console.log("Getting history, this returns many items")
    const history = await cameras[0].getHistory(50)

    console.log("Getting recording for ", history[0].id.toString(10))
    const url = await cameras[0].getRecording(history[0].id.toString(10))
    // hung....
  }
  catch(e) {
    console.log("Problem: ", e);
  }
}

do_it();`

Dave

**Comment by dgreif** [comment]
Looks like it's getting into a loop where it continues to start a new session and try again because the endpoint is giving a `404`.  This is most likely because the history records only have the numerical ding id, rather than `ding_id_str` found on active dings.  I will do some digging and let you know how to use it correctly

**Comment by dgreif** [comment]
Ok, it looks like the `history` endpoint I'm using in there isn't really useful for this because it is missing `ding_id_str`.  You can use the `events` endpoint instead, but I currently only expose that through the `location`.

```js
const locations = await ringApi.getLocations(),
    location = locations[0],
    cameras = await ringApi.getCameras(),
    camera = cameras[0],
    events = (await location.getEvents(50)).events,
    event = events[0]

  console.log('Getting recording for ', event.ding_id_str)
  const url = await camera.getRecording(event.ding_id_str)
  console.log('URL', url)
```

**Comment by david-olshefski** [comment]
Thanks, but the videos that get pulled down apparenlty do not have the timestamp or 'Ring' logo on the video itself, which I need to have.    

The urls all begin with:

https://ring-untranscoded-videos.s3.amazonaws.com/72885303/6772308860474441003.mp4?<long query string>

Is there a way to obtain the video with the TS & logo?

**Comment by dgreif** [comment]
Ok, I just added an option to get transcoded recordings in v`5.12.0`.  `camera.getRecording(event.ding_id_str, true)` will return the transcoded URL, while `camera.getRecording(event.ding_id_str)` will still return the untranscoded.  Just a heads up, the timestamps seem to be fixed to the time that the recording started.  Hope that gets you everything you need!

P.S. when you pull down the events, there is a `recording_status: 'ready'` property when the recording for the event is actually available for download.  If that field isn't there, then don't try to pull the video or you will get an error.

**Comment by david-olshefski** [comment]
This is awesome, thank you so much. It works great, and is exactly what I was hoping for.

I just wish the videos captured by my device did not have so many skips & freeze/stops.

**Comment by dgreif** [comment]
@david-olshefski just wanted to give you a heads up, I changed the signature for `getRecording` in v6 of the api.  For your use case, it would now be `camera.getRecordingUrl(event.ding_id_str,  { transcoded: true })`.  `location.getEvents` is now `location.getCameraEvents` with a new options param.  Check out https://github.com/dgreif/ring/blob/master/examples/api-example.ts for example usage
