### ISSUE TITLE
Can't get stream video to work

### ISSUE THREAD

**Issue by MrMaik** [dgreif/ring#205]
When I run the stream example the output I get is:
```
Starting Video...
Video started, streaming to part files...
Call has ended
```
There is a part0.mp4 file, but it's only 286bytes (every time)

And with the browser example, as soon as you'd expect the video to start:
```
Call has ended
```
Both the stream.m3u8 and stream0.ts files are created, the stream.m3u8 seems to be okay, but the stream0.ts is 0 bytes

I'm using the 2fa and am able to get snapshots from the camera without issues.

```
{ id: theCameraId,
  wifi_name: 'mySsId',
  battery_percentage: '85',
  battery_percentage_category: 'very_good',
  battery_voltage: null,
  battery_voltage_category: null,
  latest_signal_strength: -44,
  latest_signal_category: 'good',
  average_signal_strength: -44,
  average_signal_category: 'good',
  firmware: 'Up to Date',
  updated_at: '2019-12-20T16:37:26+00:00',
  wifi_is_ring_network: false,
  packet_loss_category: 'good',
  packet_loss_strength: 0 }
```

I'm using tsc Version 3.7.3 and node v8.10.0

[part0_stream_stream0.zip](https://github.com/dgreif/ring/files/3989258/part0_stream_stream0.zip)

**Comment by dgreif** [comment]
@MrMaik I just tried out both the stream and browser examples and they worked just fine for me.  I'd recommend updating to node 12 and trying again.  Outside of that, it may be network related on your end.  Let me know if you see any other logs that could help debug what's going on

**Comment by MrMaik** [comment]
Hmm strange, I've just tried it again, using the node.js docker image and I'm still having the same issue...
Is there anything network related you could suggest that might help (port forwarding or something)?

btw, thank you for the quick response and a great project, even being able to get snapshots is great!

**Comment by pelaxa** [comment]
I am also trying to run the stream example and not able to get it to work.  it seems to get stuck on 'Video Starting'. Although I do see it start live view in my account, no video is output.  same result with the recording example.  I have a basic ring subscription that is active and working.

`korey@Ubuntu-VirtualBox:~/ring$ npm run-script stream-example

> ring-client-api@5.12.0 stream-example /home/korey/ring
> npm run build && node ./lib/examples/stream-example.js


> ring-client-api@5.12.0 build /home/korey/ring
> rm -rf lib && tsc --declaration

Starting Video...
^Ckorey@Ubuntu-VirtualBox:~/ring$ node -v
v12.14.0
korey@Ubuntu-VirtualBox:~/ring$ npm -v
6.13.4
korey@Ubuntu-VirtualBox:~/ring$ ffmpeg -v
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
`

**Comment by dgreif** [comment]
My guess is that these are network related issues.  See #191 for more details on the issue.

**Comment by pelaxa** [comment]
I added tons of debug and the first issue seems to be with getPublicIp().  This is taking for ever to come back.  I commented that out so that it uses the Google STUN server instead and that comes back very fast.

Now I get at least an MP4 file in the output folder but it is only 286 bytes and these ffmpeg errors
`KOREY-DEBUG: ffmpeg stderr: [sdp @ 0x56121a738980] Could not find codec parameters for stream 1 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, sdp, from 'pipe:':
  Metadata:
    title           : Talk
  Duration: N/A, bitrate: 64 kb/s
    Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
    Stream #0:1: Video: h264, none, 90k tbr, 90k tbn, 180k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_mulaw (native) -> aac (native))

KOREY-DEBUG: ffmpeg stderr: pipe:: Connection timed out
Finishing stream 0:0 without any data written to it.
[aac @ 0x56121a744e00] Too many bits 8832.000000 > 6144 per frame requested, clamping to max
Output #0, mp4, to '/home/kouroche/ring/output/example.mp4':
  Metadata:
    title           : Talk
    encoder         : Lavf57.83.100
    Stream #0:0: Audio: aac (LC) (mp4a / 0x6134706D), 8000 Hz, mono, fltp, 48 kb/s
    Metadata:
      encoder         : Lavc57.107.100 aac
size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[aac @ 0x56121a744e00] Qavg: -nan

KOREY-DEBUG: ffmpeg exited with code 0`

**Comment by guitarer09** [comment]
This is still an issue for me - it was working for most of the first day I implemented ring-client-api (yesterday), and then I started getting the following:

> Uncaught (in promise) Error: sip INVITE request failed with status 408
    at C:\Users\guita\projects\Ring and Clock\node_modules\ring-client-api\lib\api\sip-session.js:177

I think the original line is 169, I've got some debugging thrown in there. 

Streaming still worked, and then I came back to it this morning, and now I'm not getting anything.

I reverted back to just using the example (with my creds), but I'm still getting the error. 

@pelaxa's fix of switching to the Google STUN server in #194  did not work for me. Based on my debugging, that doesn't appear to be my issue anyway.

**Comment by dgreif** [comment]
@guitarer09 the 408 is a SIP timeout, which would be coming from the Ring servers.  Not sure I can do anything about that.  

@guitarer09, @pelaxa, @MrMaik can you all read through #191 and see if it applies in your situation?  Basically, do you have your main router (gateway) at an _abnormal IP address_.  192.168.0.1 or 192.168.1.1 would be "normal".

**Comment by giejay** [comment]
I have the exact same issue, every file is 286 bytes. Ive upgraded from node 10 to node 12 and the problem persists.

```
const ringApi = new RingApi({
      // Replace with your ring email/password
      email: env.RING_EMAIL!,
      password: env.RING_PASS!,
      // Refresh token is used when 2fa is on
      // Listen for dings and motion events
      cameraDingsPollingSeconds: 2
    }),
    [camera] = await ringApi.getCameras();

    await camera.recordToFile(filePath, videoLength);
```

**Comment by MrMaik** [comment]
> 
> 
> I have the exact same issue, every file is 286 bytes. Ive upgraded from node 10 to node 12 and the problem persists.
> 
> ```
> const ringApi = new RingApi({
>       // Replace with your ring email/password
>       email: env.RING_EMAIL!,
>       password: env.RING_PASS!,
>       // Refresh token is used when 2fa is on
>       // Listen for dings and motion events
>       cameraDingsPollingSeconds: 2
>     }),
>     [camera] = await ringApi.getCameras();
> 
>     await camera.recordToFile(filePath, videoLength);
> ```

My router is in the list posted on #191 but the wifi device the ring is connected to isn't, so that might be it

**Comment by pelaxa** [comment]
I definitely had to enable UPnP on my router when i was getting the 286 bytes files.  #191 was also an issue for me.

Problem is, I had to open firewall to get it working, and for the life of me I have not figured out a limited set of ports so I don't have to leave it wide open and still have it work.

**Comment by dgreif** [comment]
@pelaxa @MrMaik @giejay please try v`5.12.1`.  See https://github.com/dgreif/ring/issues/211#issuecomment-570231847 for a detailed explanation of the current state of live stream issues.

**Comment by giejay** [comment]
@dgreif, thanks for the update! Upgraded to 5.13 with the new port configs. However I dont think my issue was related to these ports because I think it was a VPN issue. I was mostly developing my Home Automation in the train, whenever I was connected to my home network using (Open)VPN. 

I tried 5.13 @ home without using the static port mapping and it's now working, 50 percent of the time. The other times, I only get audio :( Not sure if it's related to my raspberry pi 4 and docker (which includes ffmpeg) or just a Ring issue.

**Comment by dgreif** [comment]
@giejay that is extremely odd.  I would think that if audio got through, video should be able to as well.  Thanks for giving it a try!  As for VPN, I've noticed that I can't get streams to work through VPN either.  Are you able to test the Ring app through your VPN to see if it works?

**Comment by giejay** [comment]
I just tried it with the app on my phone with VPN connected, that works fine. Also tried another capture of the video from my raspberry pi, that also worked fine. It really seems to be a Ring server issue. 

As a last resort I might try running it outside docker, just to see if it's not a port/ffmpeg issue.

**Comment by dgreif** [comment]
Thanks for the info @giejay!. I'm going to close this issue in favor of #211 since it has the most relevant info on live streams not working.
