### ISSUE TITLE
Spotlight cam always reports 100% battery level

### ISSUE THREAD

**Issue by pslogic** [dgreif/ring#206]
spotlight cam always reports 100% battery level. Ring app shows battery level change over time.

currently have a battery in the left compartment only.

using homebridge-ring v5.10.0

**Comment by dgreif** [comment]
Hmm, that's a fun one.  I didn't realize some of the cameras had multiple batteries!  Ring provides a battery level field on the data for each camera, but they must have a second field for those dual battery cameras that I didn't know about.  I'll see if I can find any references in the web app source code.

**Comment by dgreif** [comment]
@pslogic could you please run the command in https://github.com/dgreif/ring/wiki/Data-Discovery and post the resulting data here?  This will help me get a glimpse into how Ring is reporting the battery level for that camera.  Thanks!

**Comment by pslogic** [comment]
@dgreif 

i just tried but running into the following problem and not sure how to proceed. can you advise?

```
pi@smarthome:~ $ npx -p ring-client-api ring-device-data-cli
npx: installed 169 in 36.865s
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'dotenv/config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/.npm/_npx/6951/lib/node_modules/ring-client-api/lib/api/refresh-token.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by dgreif** [comment]
Sorry about that! Just pushed a fix in `6.0.1`

**Comment by pslogic** [comment]
@dgreif here is the relevant section of the json file:

```
      {
        "description": "Patio",
        "subscribed": true,
        "subscribed_motions": true,
        "battery_life": "91",
        "external_connection": false,
        "firmware_version": "Up to Date",
        "kind": "stickup_cam_v4",
        "settings": {
          "offline_motion_event_settings": {
            "subscribed": true,
            "enabled": false,
            "max_upload_kb": 5000,
            "resolution_p": 360,
            "frequency_after_secs": 2,
            "period_after_secs": 30
          },
          "lite_24x7": {
            "subscribed": true,
            "enabled": true,
            "frequency_secs": 840,
            "resolution_p": 360
          },
          "enable_vod": 1,
          "exposure_control": 2,
          "motion_zones": [
            1,
            1,
            1,
            1,
            0
          ],
          "motion_snooze_preset_profile": "none",
          "motion_snooze_presets": [
            "none",
            "low",
            "medium",
            "high"
          ],
          "live_view_preset_profile": "middle",
          "live_view_presets": [
            "low",
            "middle",
            "high",
            "highest"
          ],
          "pir_sensitivity_1": 10,
          "vod_suspended": 0,
          "doorbell_volume": 8,
          "vod_status": "enabled",
          "advanced_motion_detection_enabled": false,
          "advanced_motion_zones": {
            "zone1": {
              "name": "Default Zone",
              "state": 2,
              "vertex1": {
                "x": 0,
                "y": 0.4
              },
              "vertex2": {
                "x": 0.333333,
                "y": 0.4
              },
              "vertex3": {
                "x": 0.666666,
                "y": 0.4
              },
              "vertex4": {
                "x": 1,
                "y": 0.4
              },
              "vertex5": {
                "x": 1,
                "y": 1
              },
              "vertex6": {
                "x": 0.666666,
                "y": 1
              },
              "vertex7": {
                "x": 0.333333,
                "y": 1
              },
              "vertex8": {
                "x": 0,
                "y": 1
              }
            },
            "zone2": {
              "name": "Zone 2",
              "state": 0,
              "vertex1": {
                "x": 0,
                "y": 0
              },
              "vertex2": {
                "x": 0,
                "y": 0
              },
              "vertex3": {
                "x": 0,
                "y": 0
              },
              "vertex4": {
                "x": 0,
                "y": 0
              },
              "vertex5": {
                "x": 0,
                "y": 0
              },
              "vertex6": {
                "x": 0,
                "y": 0
              },
              "vertex7": {
                "x": 0,
                "y": 0
              },
              "vertex8": {
                "x": 0,
                "y": 0
              }
            },
            "zone3": {
              "name": "Zone 3",
              "state": 0,
              "vertex1": {
                "x": 0,
                "y": 0
              },
              "vertex2": {
                "x": 0,
                "y": 0
              },
              "vertex3": {
                "x": 0,
                "y": 0
              },
              "vertex4": {
                "x": 0,
                "y": 0
              },
              "vertex5": {
                "x": 0,
                "y": 0
              },
              "vertex6": {
                "x": 0,
                "y": 0
              },
              "vertex7": {
                "x": 0,
                "y": 0
              },
              "vertex8": {
                "x": 0,
                "y": 0
              }
            }
          },
          "advanced_motion_detection_human_only_mode": false,
          "enable_audio_recording": true,
          "people_detection_eligible": true,
          "ignore_zones": {
            "zone1": {
              "name": "undefined",
              "state": 0,
              "vertex1": {
                "x": 0,
                "y": 0
              },
              "vertex2": {
                "x": 0,
                "y": 0
              }
            },
            "zone2": {
              "name": "undefined",
              "state": 0,
              "vertex1": {
                "x": 0,
                "y": 0
              },
              "vertex2": {
                "x": 0,
                "y": 0
              }
            },
            "zone3": {
              "name": "undefined",
              "state": 0,
              "vertex1": {
                "x": 0,
                "y": 0
              },
              "vertex2": {
                "x": 0,
                "y": 0
              }
            },
            "zone4": {
              "name": "undefined",
              "state": 0,
              "vertex1": {
                "x": 0,
                "y": 0
              },
              "vertex2": {
                "x": 0,
                "y": 0
              }
            }
          },
          "enable_rich_notifications": false,
          "rich_notifications_billing_eligible": true,
          "loitering_threshold": 10,
          "advanced_motion_detection_types": [],
          "motion_detection_enabled": true,
          "advanced_motion_zones_enabled": false,
          "advanced_motion_zones_type": "6pir",
          "advanced_pir_motion_zones": {
            "zone1_sensitivity": 5,
            "zone2_sensitivity": 5,
            "zone3_sensitivity": 5,
            "zone4_sensitivity": 5,
            "zone5_sensitivity": 5,
            "zone6_sensitivity": 5
          },
          "light_settings": {
            "brightness": 10
          },
          "enable_white_leds": 1,
          "rich_notifica-uuid": false
        },
        "features": {
          "motions_enabled": true,
          "show_recordings": true,
          "show_vod_settings": true,
          "rich_notifications_eligible": false,
          "show_24x7_lite": true,
          "show_offline_motion_events": false
        },
        "owned": true,
        "alerts": {
          "connection": "online"
        },
        "motion_snooze": null,
        "stolen": false,
        "battery_life_2": null,
        "battery_voltage": 4073,
        "battery_voltage_2": 208,
        "led_status": {
          "seconds_remaining": 0
        },
        "siren_status": {
          "seconds_remaining": 0
        },
        "night_mode": 0
      }
```

**Comment by dgreif** [comment]
@pslogic that is perfect!!!  Looks like there is a `battery_life_2` that I have never seen before 🥇 .  I'm guessing you switched the slot that you have the battery in.  Is it showing 91% in HomeKit currently?

**Comment by pslogic** [comment]
@dgreif yes, the voltage status of the battery is at 91%. currently, there is a battery only in the right slot (when looking head onto the camera lens).

**Comment by dgreif** [comment]
@pslogic would you be able to put the battery in the left slot and run that data tool again?  I'm just curious how it behaves if only the left slot is present.  Thanks!

**Comment by dgreif** [comment]
@pslogic I just released v`6.1.0` which should support the battery in either slot.  Could you test it out and let me know how it works?  I'm still interested in what the data looks like if you get a chance to run that data tool with the battery in the left slot.  Thanks!

**Comment by pslogic** [comment]
sorry, for the late response, here are the json snippets captured while still using v5.10.0.

- battery in left slot only
   ```

**Comment by pslogic** [comment]
here is the relevant portion of the ring app under device health for reporting battery status:

<img width="315" alt="Screen Shot 2020-01-21 at 4 01 50 PM" src="https://user-images.githubusercontent.com/526750/72853863-732f5000-3c67-11ea-92ea-b6130f8926c7.png">

**Comment by pslogic** [comment]
and, i'll update this issue once i've tested ```v6.1.0```

**Comment by dgreif** [comment]
That data is perfect, thank you so much!! I’m confident 6.1.0 should work. The way I have it set up, it will take the average of the batteries if both are interested since HomeKit has a max battery level of 100

**Comment by pslogic** [comment]
Based on the [page 47 of the product documentation](https://support.ring.com/hc/en-us/article_attachments/360022816112/Spotlight_Cam_Battery_MANUAL_web.pdf), it doesn't seem clear whether the cam is actually drawing current from 1 or both batteries if both slots are occupied. It may be better to show the battery levels separately similar to the ring app instead of averaging the values together.

I'll test this specific use case for a few days starting tomorrow and report back to you.

**Comment by dgreif** [comment]
Unfortunately I don't have control over how the battery levels are shown in HomeKit.  I can only supply a single battery level, with max value of 100.  Thanks for testing it out!

**Comment by pslogic** [comment]
after some testing I can report the following:

- the battery level averaging operation works correctly and displaying the expected value
- alternately, though, the cam is only drawing current from 1 of the batteries as i suspected.

in the ring app, here are screenshots of battery life yesterday vs today:

   - yesterday:
      <img width="316" alt="Screen Shot 2020-01-23 at 1 32 20 PM" src="https://user-images.githubusercontent.com/526750/73025967-6e90a600-3de5-11ea-89b3-961d45be51f8.png">

   - today:
      <img width="316" alt="Screen Shot 2020-01-23 at 1 33 00 PM" src="https://user-images.githubusercontent.com/526750/73025989-75b7b400-3de5-11ea-8d5e-ff7754e3c398.png">

i believe a valid use-case would be that a user would want the battery life report of the active battery only in order to know that it is time to recharge it. displaying an average value has an unintentional effect of masking the fact that there is a critically low battery to charge.

unfortunately, it takes a long time to charge up a ring battery, feels like at least half a day. i only have 1 spare to cycle through between the spotlight cam and the doorview cam and i really rely on monitoring remaining battery life to know when is the optimum time to recharge. the doorview cam starts to have degraded performance when the battery life gets below 30% because of its unique functions

to illustrate, here's a graph of battery life for both cams:
<img width="767" alt="Screen Shot 2020-01-23 at 1 54 57 PM" src="https://user-images.githubusercontent.com/526750/73027290-fbd4fa00-3de7-11ea-8126-27d86aec5257.png">

`green` is the doorview cam and `yellow` is the spotlight cam. the spotlight cam was only added at the end of november. from the middle of december to the beginning of january is the 100% bug, but then i had to do a battery change. the important thing to note from this graph is the current drain for both batteries are tracking very closely and it has to do with when i changed my batteries in each unit and how often they both detect events. ultimately, i have to be really on top of having a charged battery for the spotlight cam


i'll continue testing to help characterize how the cam fails over from 1 battery to the other. perhaps this information can be used to implement an alternative which is to display battery life of the active battery?

**Comment by dgreif** [comment]
Wow, that is some great data! I think the simplest solution would be to take the lower of the two values and report that as the current battery life.  That way you get the battery low warning as soon as one battery is low.  

Just curious, what are you using to track that data and make the graph?

**Comment by pslogic** [comment]
taking the lower of the values is a straightforward solution that should work independently of the failover logic in the cam.... saves us the trouble of waiting another 2 weeks for data :wink:

i'm using Telegraf-InfluxDB-Grafana (aka TIG stack) running on another raspberry pi. here's an [article](https://www.terminalbytes.com/temperature-using-raspberry-pi-grafana/) for reference.

my full setup can be found [here](https://gitlab.com/peter.look/home-automation)

**Comment by dgreif** [comment]
v`6.1.1` will take the lower of the two values.  I think that should do it for this issue, right?

**Comment by Rubenfer** [comment]
Offtopic to @pslogic: I'm really interested in monitor my ring battery as you made with TIG, but I cannot find any useful information in setup link you posted. Please, I'll appreciate if you can send me more information. Feel free to DM me in Twitter (@RubenApps).

**Comment by pslogic** [comment]
@dgreif i've verified that the latest plugin change implements the desired functionality, this issue can be closed.

@Rubenfer you're correct that the link on the TIG stack does not go into how battery monitoring is implemented. i also have mqtt and node-red running which is needed to make battery monitoring work end-to-end. i'll write up a how-to article in my repo [here](https://gitlab.com/peter.look/home-automation). please monitor for an update.
