### ISSUE TITLE
Snapshot not working

### ISSUE THREAD

**Issue by arjohnson15** [dgreif/ring#213]
snapshot does not work. I can select the camera and it will load the stream with audio but snapshot does not update without opening the stream. 
I am on v5.12.1

**Comment by dgreif** [comment]
Which camera model do you have?  Have snapshots recently stopped working, or never worked?  Please see https://github.com/dgreif/ring/wiki/Battery-Cam-Snapshots to see if it applies to you

**Comment by arjohnson15** [comment]
I have the Video Doorbell 2. Snapshots were working yesterday. 
It looks like it isn't even requesting snapshots in the logs now. I checked my logs from yesterday and it was requesting snapshots then.

**Comment by cah-dgreif** [comment]
If it isn't requesting snapshots, then something is messed up on the HomeKit side.  I'd suggest restarting your Home hub (AppleTV, HomePod, iPad) and your homebridge server

**Comment by dgreif** [comment]
If it isn't requesting snapshots, then something is messed up on the HomeKit side. I'd suggest restarting your Home hub (AppleTV, HomePod, iPad) and your homebridge server

**Comment by arjohnson15** [comment]
I will attempt to reboot a home hub when I get home. Restarting homebridge server didn't help. Snapshots on the ring doorbell is the only issue I am having currently. My RTSP camera streams are still requesting snap shots properly. I will update the status when I am able to reboot a hub.

**Comment by arjohnson15** [comment]
I had an update on my apple TV when I got home and after it rebooted the rinf snapshots started to work again as they are suppose to! glad it was something simple.
