### ISSUE TITLE
Require PIN for alarm disarm and/or remove alarm

### ISSUE THREAD

**Issue by TejasAntani** [dgreif/ring#214]
Hi there,
I am floored by how well this plugin works.  Thank you all so much for your work.

I wanted to raise a concern about the alarm functionality and get some input.  I can use the home app or Siri to disarm the alarm without entering a PIN code.  

How do I require a PIN to disarm the alarm, especially via Siri, but ideally via the app as well?  Could we add this to the backlog if it's not already a feature?

Also, in the interim, how do I prevent access to the alarm but retain access to the sensors?

Thanks!!

**Comment by dgreif** [comment]
Glad you are enjoying the plugin 😄.  I just played around with disarming on my iPhone 10 and the behavior seems correct.  I am able to _arm_ the alarm without unlocking my phone (by saying "Hey Siri, Set Ring Alarm to Stay".  If I try disarming ("Hey Siri, Disarm Ring Alarm") without unlocking my phone, she replies "You'll need to unlock your iPhone first".  If you don't have a pin/touch id/face id enabled on your iPhone, then you may just need to turn that on.  I'm not exactly sure how this would work from a siri-centric device (the HomePod), but I'm guessing Apple thought of that.  As for adding the PIN from the plugin side, I'm afraid that's simply not possible.  If the behavior isn't correct/secure in a certain scenario, then Apple would be the ones who need to fix it.  Let me know if that answers your questions well enough

**Comment by TejasAntani** [comment]
Hi there, thanks for this.  I also went back and looked at Apple's documentation on the HomePod and the disarm function works the same way as you described, with some more info that I gathered below.  I must have tested it with my phone unlocked the first couple of times.  I also tested the arm/disarm behavior using Siri from my Apple Watch and AirPods.  

AirPods: "Hey Siri" follows the same construct as the HomePod or a locked iPhone.  You have to unlock your phone before you can disarm.

Apple Watch: This one is a little different.  If the watch is unlocked, you __can__  disarm the alarm via Siri without any additional steps.  

I hope this helps others!

**Comment by dgreif** [comment]
@TejasAntani thanks for the detail, that all makes a lot of sense!
