### ISSUE TITLE
Bypassing sensors for arming securing system

### ISSUE THREAD

**Issue by jsrivatsan** [dgreif/ring#215]
@dgreif Happy new year! Hope you had a good break. I have been thoroughly enjoying this plugin for last few weeks. It has been such a pleasure to get the entire ring system integrated with rest of my homekit devices.

I just have a small request. Is there anyway we can add some control to bypass tripped sensors when arming? Currently, we have to physically press the bypass button on the keypad. This is not a big deal but it breaks some of the location aware automations. Thanks a ton for your help.

**Comment by dgreif** [comment]
Glad to hear you got everything working with the plugin.  Bypassing sensors is _possible_, but I'm not sure what the best approach would be to doing so.  One idea would be adding an option in the platform config like `"autoBypassSensors": true`, which would cause the plugin to detect situations where bypass is necessary and automatically send the bypass command when you arm your system from HomeKit.  The downside is that you would have no indication that bypass was applied in those situations, so you could accidentally leave a door wide open, allowing an intruder to walk right in.

Could you elaborate on your situation a little bit and explain when bypass is necessary?  If it's a matter of leaving windows open for air flow, one good option is to buy some of the "Open Window Magnets" (https://shop.ring.com/products/window-magnet) which allow you to open a window and still have the sensor register as "closed".  Would that fill your need?

**Comment by jsrivatsan** [comment]
@dgreif I understand that adding the bypass feature could be quite dangerous if not used properly. 

In my case, I have my parents who frequently open windows (kitchen, bedroom, living room) throughout the day. They usually forget to turn on the alarm when they leave. So I have an automation that automatically turns on the alarm when they leave. However, due to the bypass feature the alarm never turns on.

I do have dual magnets on some of the windows upstairs. But I am not comfortable to add additional magnets on downstair windows as it could potentially cause issues later on (forget to completely close downstair windows when we all leave for extended period).

Would it possible to expose a switch (based on configure.json setting) that controls the state of bypass? Moreover, the switch could be a timed switch that automatically turns off after “x” minutes (configurable in config.json as well). This way the default state of the bypass switch will be OFF unless turned on intentionally by user.

Thanks a ton for looking into this.

**Comment by apexad** [comment]
My thought on this would be to make use of 'Home' vs. 'Night'.  So in the config allow the user to specify which one should bypass sensors and which one should not (or maybe just default 'Home' to bypass sensors and 'Night' does not..  However, keep it so that 'Away' never bypasses sensors.

**Comment by jsrivatsan** [comment]
Wow... I did not think of that. This would work very well. It makes sense to keep the away mode to not bypass any sensors by default. Thanks a ton for looking into this.
