### ISSUE TITLE
Port to Python

### ISSUE THREAD

**Issue by bhden2007** [dgreif/ring#217]
I would like to port the work done here over to Python to get access to raw video.  I have successfully used my PFSense firewall to redirect the SIP/RDP traffic to a linux server where I can capture the video direct from the Ring Camera.  When I look at this traffic with Wireshark, the RTP payload (h265 type 97) looks corrupted.  Has anyone been able to pull video out of a Wireshark capture direct from a Ring Camera?

**Comment by jeroenterheerdt** [comment]
I am trying to accomplish a port to Python as well for reasons of integrating with Home Assistant..

**Comment by dgreif** [comment]
@bhden2007 I have not had any luck (or know of anyone who has) trying to interface directly with the camera.  In this library, all video streaming is done via SIP to the Ring servers.  The initiation process is awkward and a little slow.  The streams also have to go up to the Ring servers and then back down (most likely to the same network in the end).  If there is a way to request a SIP stream directly from the camera, I would _love_ to get the details on it!  Please share whatever you have so far if you are able.

As for the python port, @jeroenterheerdt has been working on it for a while (See https://github.com/tchellomello/python-ring-doorbell/pull/133).  His original approach was to invoke the node library from python, but a full port would probably be the most reliable approach.  I would love to help with the port, but unfortunately I don't have a lot of free time to spare on it right now.  Hopefully the two of you can work together and make it happen!  I'm happy to answer any questions you have along the way

**Comment by bhden2007** [comment]
Actually I am not trying to interface with the doorbell directly.  What I
want to do is re-direct the RTP traffic via my PFSense firewall (IPTables
NAT rules) to another PC so I can extract the video from the RTP traffic.
It might even be possible to proxy the traffic, extract the RTP video
payload, and also forward to Ring site (for normal operation).

I can receive the RTP traffic just fine, but the RTP payload does not look
like h.264 video. I have read RFC1684, and have looked at the captures in
Wireshark, but the NAL-U headers and Fragmentation Units are corrupt (S and
E bits set at the same time, improper payload lengths, etc, etc).  The next
thing I will check is if Wireshark is doing a proper decode of H.264 over
RTP.

The advantage of this method would be that I get instance access to the
video (direct from the doorbell camera), and don't have to worry about SIP
setup, and the delays you mentioned.

**Comment by bhden2007** [comment]
UPDATE:  I tried a different version of Wireshark on my MAC and it is parsing the video much better.   I will now write a Python parser to see if I can extract the raw h.264 video.  I will update this thread with my findings.

**Comment by dgreif** [comment]
You guys are welcome to continue commenting here, or it may be a good idea to open a draft PR on the python library to host discussions.  I'm going to close this comment since there isn't anything for me to do on the node side.
