### ISSUE TITLE
2 Factor

### ISSUE THREAD

**Issue by TSBarnette** [dgreif/ring#219]
I would like to start with a thank you for putting all of this together.  

I am attempting to enable 2fa for the ring connection.  I have created the refreshtoken and updated the json file.  Everything appears to be working within homebridge and homekit but I continue to get the text from ring with my validation code.  Is there anyone to stop this but keep 2fa enabled?

**Comment by htims1989** [comment]
Have you taken your username and password out of the config? You only need the refresh token in there if you are using 2FA. Only thing I can think of.

**Comment by TSBarnette** [comment]
Yes.  I have tried both ways and I continue to get the txt.

**Comment by dgreif** [comment]
How often are you getting the text from Ring?

**Comment by TSBarnette** [comment]
45 to 60 seconds

**Comment by dgreif** [comment]
Wow, that’s frequent. And if you turn off homebridge, it stops sending texts?  Can you confirm you are on the latest version of the plugin?

**Comment by TSBarnette** [comment]
Yes I am on latest version.   I have tested with different installs of Homebridge.

**Comment by dgreif** [comment]
If you turn off homebridge, do the texts stop?  I just want to make sure it's for sure coming from the plugin

**Comment by TSBarnette** [comment]
Fixed.  It was a SmartThings integration.  Homebridge works perfectly.   Thanks.

**Comment by TSBarnette** [comment]
This was an issue with an old Smarthings configuration.   Works great.
