### ISSUE TITLE
Request to https://api.ring.com/clients_api/dings/active failed

### ISSUE THREAD

**Issue by onefish2** [dgreif/ring#221]
Just started getting these new errors after the plugin had been working flawlessly for months:"

[1/10/2020, 10:29:52 PM] [Ring] Request to https://api.ring.com/clients_api/dings/active failed
[1/10/2020, 10:29:53 PM] [Ring] Request to https://api.ring.com/clients_api/ring_devices failed
[1/10/2020, 10:29:54 PM] [Ring] Request to https://api.ring.com/clients_api/dings/active failed
[1/10/2020, 10:29:56 PM] [Ring] Request to https://api.ring.com/clients_api/dings/active failed
[1/10/2020, 10:29:58 PM] [Ring] Request to https://api.ring.com/clients_api/dings/active failed
[1/10/2020, 10:29:59 PM] [Ring] Request to https://api.ring.com/clients_api/ring_devices failed
[1/10/2020, 10:29:59 PM] [Ring] Request to https://api.ring.com/clients_api/doorbots/26219510/floodlight_light_off failed
[1/10/2020, 10:29:59 PM] [Ring] Error: Request failed with status code 503
    at createError (/usr/local/lib/node_modules/homebridge-ring/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/homebridge-ring/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-ring/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
 {
  config: {
    url: 'https://api.ring.com/clients_api/doorbots/26219510/floodlight_light_off',
    method: 'put',
    data: '',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/x-www-form-urlencoded',
      authorization: 'Bearer eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiZGVmYXVsdCIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiJyaW5nX29mZmljaWFsX2FuZHJvaWQiLCJjaWQiOiJyaW5nX29mZmljaWFsX2FuZHJvaWQiLCJleHAiOjE1Nzg3MTY0MDksImhhcmR3YXJlX2lkIjoiNGNjMDZjZDgtZDA4Ny01YWJkLTU3ZjgtZTRhZTI1OTI4ODQyIiwiaWF0IjoxNTc4NzEyODA5LCJybmQiOiJXNWN4dzRXa3oxRHVyZyIsInNjb3BlcyI6WyJjbGllbnQiXSwidXNlcl9pZCI6ODY5NTU2Nn0.OQFIPRKvJRVySitDMjqKuxNth0xx2CB-11KFRnRg8cMUznXC7MWYwI-hRwuzTbuhZ072fIBdlTY2NPzh86UQZg',
      hardware_id: 'a946585d-37f9-55e2-a1f2-db71b1bb926c',
      'User-Agent': 'axios/0.19.0'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function],
      abort: [Function],
      aborted: [Function],
      error: [Function],
      timeout: [Function],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'api.ring.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.ring.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 199544,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    connection: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'api.ring.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.ring.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 199544,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'PUT /clients_api/doorbots/26219510/floodlight_light_off HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/x-www-form-urlencoded\r\n' +
      'authorization: Bearer eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiZGVmYXVsdCIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiJyaW5nX29mZmljaWFsX2FuZHJvaWQiLCJjaWQiOiJyaW5nX29mZmljaWFsX2FuZHJvaWQiLCJleHAiOjE1Nzg3MTY0MDksImhhcmR3YXJlX2lkIjoiNGNjMDZjZDgtZDA4Ny01YWJkLTU3ZjgtZTRhZTI1OTI4ODQyIiwiaWF0IjoxNTc4NzEyODA5LCJybmQiOiJXNWN4dzRXa3oxRHVyZyIsInNjb3BlcyI6WyJjbGllbnQiXSwidXNlcl9pZCI6ODY5NTU2Nn0.OQFIPRKvJRVySitDMjqKuxNth0xx2CB-11KFRnRg8cMUznXC7MWYwI-hRwuzTbuhZ072fIBdlTY2NPzh86UQZg\r\n' +
      'hardware_id: a946585d-37f9-55e2-a1f2-db71b1bb926c\r\n' +
      'User-Agent: axios/0.19.0\r\n' +
      'Host: api.ring.com\r\n' +
      'Connection: close\r\n' +
      'Content-Length: 0\r\n' +
      '\r\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      maxCachedSessions: 100,
      _sessionCache: [Object]
    },
    socketPath: undefined,
    method: 'PUT',
    path: '/clients_api/doorbots/26219510/floodlight_light_off',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      connection: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 503,
      statusMessage: 'Service Unavailable: Back-end server is at capacity',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular],
      responseUrl: 'https://api.ring.com/clients_api/doorbots/26219510/floodlight_light_off',
      redirects: []
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    _redirectable: Writable {
      _writableState: [WritableState],
      writable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function],
      _currentRequest: [Circular],
      _currentUrl: 'https://api.ring.com/clients_api/doorbots/26219510/floodlight_light_off'
    },
    [Symbol(kNeedDrain)]: false,
    [Symbol(isCorked)]: false,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      authorization: [Array],
      hardware_id: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 503,
    statusText: 'Service Unavailable: Back-end server is at capacity',
    headers: {
      date: 'Sat, 11 Jan 2020 03:29:59 GMT',
      'content-length': '0',
      connection: 'close',
      'set-cookie': [Array],
      'cf-cache-status': 'DYNAMIC',
      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
      server: 'cloudflare',
      'cf-ray': '5533cf398c8fe6f8-EWR'
    },
    config: {
      url: 'https://api.ring.com/clients_api/doorbots/26219510/floodlight_light_off',
      method: 'put',
      data: '',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'PUT /clients_api/doorbots/26219510/floodlight_light_off HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'authorization: Bearer eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiZGVmYXVsdCIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiJyaW5nX29mZmljaWFsX2FuZHJvaWQiLCJjaWQiOiJyaW5nX29mZmljaWFsX2FuZHJvaWQiLCJleHAiOjE1Nzg3MTY0MDksImhhcmR3YXJlX2lkIjoiNGNjMDZjZDgtZDA4Ny01YWJkLTU3ZjgtZTRhZTI1OTI4ODQyIiwiaWF0IjoxNTc4NzEyODA5LCJybmQiOiJXNWN4dzRXa3oxRHVyZyIsInNjb3BlcyI6WyJjbGllbnQiXSwidXNlcl9pZCI6ODY5NTU2Nn0.OQFIPRKvJRVySitDMjqKuxNth0xx2CB-11KFRnRg8cMUznXC7MWYwI-hRwuzTbuhZ072fIBdlTY2NPzh86UQZg\r\n' +
        'hardware_id: a946585d-37f9-55e2-a1f2-db71b1bb926c\r\n' +
        'User-Agent: axios/0.19.0\r\n' +
        'Host: api.ring.com\r\n' +
        'Connection: close\r\n' +
        'Content-Length: 0\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'PUT',
      path: '/clients_api/doorbots/26219510/floodlight_light_off',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      _redirectable: [Writable],
      [Symbol(kNeedDrain)]: false,
      [Symbol(isCorked)]: false,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: ''
  },
  isAxiosError: true,
  toJSON: [Function]
}
[1/10/2020, 10:30:00 PM] [Ring] Request to https://api.ring.com/clients_api/dings/active failed
[1/10/2020, 10:30:02 PM] [Ring] Request to https://api.ring.com/clients_api/dings/active failed
[1/10/2020, 10:30:05 PM] [Ring] Request to https://api.ring.com/clients_api/dings/active failed
[1/10/2020, 10:30:07 PM] [Ring] Request to https://api.ring.com/clients_api/dings/active failed
[1/10/2020, 10:30:07 PM] [Eveatmo Platform] Loading new data from API for: weatherstation
[1/10/2020, 10:30:09 PM] [Ring] Request to https://api.ring.com/clients_api/dings/active failed
[1/10/2020, 10:30:11 PM] [Ring] Request to https://api.ring.com/clients_api/dings/active failed
[1/10/2020, 10:30:13 PM] [Ring] Request to https://api.ring.com/clients_api/dings/active failed
[1/10/2020, 10:30:15 PM] [Ring] Request to https://api.ring.com/clients_api/dings/active failed
[1/10/2020, 10:30:18 PM] [Ring] Request to https://api.ring.com/clients_api/dings/active failed
[1/10/2020, 10:30:19 PM] [Ring] Request to https://api.ring.com/clients_api/ring_devices failed
[1/10/2020, 10:33:02 PM] [Ring] Request to https://api.ring.com/clients_api/dings/active failed
[1/10/2020, 10:33:02 PM] [Ring] Request to https://api.ring.com/clients_api/ring_devices failed
[1/10/2020, 10:33:04 PM] [Ring] Request to https://api.ring.com/clients_api/dings/active failed

**Comment by dgreif** [comment]
Hidden in their is `Service Unavailable: Back-end server is at capacity`.  My guess is that Ring was just having a bad moment.  If it's still happening, I'd recommend turning off your homebridge server for ~10 minutes just in case you are being rate-limited by the API.  Let me know if it resolves itself

**Comment by onefish2** [comment]
@dgreif, thanks for the quick response. I will let you know if anything like this comes up again. Its been pretty solid since last night, so just a glitch on the Ring back end like you mention.

**Comment by htims1989** [comment]
For future reference, be careful posting logs as you have provided your access token for the Ring API in this section:
> 'authorization: Bearer eyJhbGciOiJIUzUxMiIsImprdSI...

It's expired now, just something to bare in mind in the future :)

**Comment by dgreif** [comment]
@onefish2 any updates?

**Comment by onefish2** [comment]
@dgreif looks like it was a glitch on the Ring server side. Its been pretty solid since. Thank you for the follow up.

**Comment by jchhenderson** [comment]
I've been getting these in my logs a couple of times a day recently:
`Request to https://api.ring.com/clients_api/dings/active failed with status 200. Response body: ��)�L`

Does anyone know what status 200 is?

**Comment by dgreif** [comment]
200 means "OK", so it shouldn't be recognized as an error.  That's very odd!  I'll keep an eye on my logs for similar messages

**Comment by jchhenderson** [comment]
hahaha - funny.

OK, let me know if you need anything.
