### ISSUE TITLE
can't split separate tiles as favourite

### ISSUE THREAD

**Issue by paqpaqpaq** [dgreif/ring#223]
When I have the feed, the button and the motion detector tiles shown as separate tiles, I cannot add just the motion tile as favourite; the rest will automatically follow and vice versa.

**Comment by dgreif** [comment]
This is all controlled by the HomeKit and the Home app.  Sorry I can't help from the plugin side.

**Comment by paqpaqpaq** [comment]
@dgreif 
Strange, because other device are abel to do so. Separate the tiles, and choose which is favourite and which isn't.

**Comment by dgreif** [comment]
@paqpaqpaq I just tried it out on iOS 13.3 and I was able to assign individual parts of the camera as favorites.  Light/siren/motion all functioned separately and I was able to assign any/all of them as favorites independently of the others.  If it's not working that way for you, then the Home app probably has a bug in it.  Sorry I can't help out more!

**Comment by paqpaqpaq** [comment]
That's..... really really strange.
Thanks for testing though.
