### ISSUE TITLE
Snapshot feature 

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#226]
Does the new feature from ring effect or enhance your plugin?

![83EED750-23F2-4524-9589-702471CC3A47](https://user-images.githubusercontent.com/47482260/72324768-95dbca80-36a3-11ea-9ad8-58d7e0a3d3e4.png)

**Comment by dgreif** [comment]
@adavison007 I haven't looked into it as much as I would like, but from what I've seen so far it has no effect on the Ring plugin.  I was hoping those snapshots would be useful for the plugin, especially on battery cams that only update their snapshot every 10 minutes, but it looks like Ring is actually storing a video for each of those.  Again, I need to dig more, but for now there is no impact

**Comment by dgreif** [comment]
From everything that I have found so far, we are still stuck with the poor snapshot api, where updates are only possible every 30s/10m.  I'll keep an eye on snapshot functionality and improve it if Ring improves their API
