### ISSUE TITLE
Plugin doesn't initialize.

### ISSUE THREAD

**Issue by zirition** [dgreif/ring#228]
Hi!

I'm having problems initializing the plugin with my Homebridge installation.

I only see this on the log with my usual config.json:

homebridge[27675]: [1/15/2020, 4:04:10 PM] Registering platform 'homebridge-ring.Ring'
homebridge[27675]: [1/15/2020, 4:04:10 PM] [Ring] Initializing Ring platform...

But if I use an empty config.json with only the Ring plugin, the log shows my Ring device:

homebridge[29846]: [1/10/2020, 11:41:49 PM] Registering platform 'homebridge-ring.Ring'
homebridge[29846]: [1/10/2020, 11:41:49 PM] [Ring] Initializing Ring platform...
homebridge[29846]: [1/10/2020, 11:41:53 PM] [Ring] Configuring 1 cameras and 1 devices for location ...............
homebridge[29846]: [1/10/2020, 11:41:53 PM] [Ring] Adding new accessory doorbell_v3 ........

When I started adding plugins again to he config.json, the Ring plugin stopped working. Tried adding different plugins together with Ring plugin and always seems that stopped working.

Currently my config.json has this plugins:

- GPIODevice ( https://www.npmjs.com/package/homebridge-gpio-device )
- webostv ( https://www.npmjs.com/package/homebridge-webos-tv )
- yeelight ( https://www.npmjs.com/package/homebridge-yeelight )
- cmdSwitch2 ( https://www.npmjs.com/package/homebridge-cmdswitch2 )
- BroadlinkRM ( https://www.npmjs.com/package/homebridge-broadlink-rm )

With this versions (taken from npm):

├─┬ homebridge@0.4.50
├─┬ homebridge-broadlink-rm@3.6.18
├── homebridge-cmdswitch2@0.2.10
├─┬ homebridge-gpio-device@0.4.4
├─┬ homebridge-ring@5.12.1
├─┬ homebridge-webos-tv@1.6.3
├── homebridge-yeelight@0.0.18

Thank you!

**Comment by dgreif** [comment]
Unfortunately there isn't much I can do to help since I can't debug your setup.  You should try adding each of the other plugins one at a time to see if you can find exactly one that causes the issue.  It sounds like you tried that and it might be that _any_ of them can cause issues.  I have no idea why that would be the case, but you will have to debug it on your own.  Sorry I can't be of more help!  This is the hard part with homebridge because everyone's setup is just a little bit different.

As an aside, you could consider using homebridge-config-ui-x to help manage your config.json and ensure that it is valid.  Or full-blown HOOBS.

**Comment by zirition** [comment]
I will try to find the issue ! :) 

Is there a way to increment logging for the plugin?  Can you point me functions to start digging? 

Thanks again

**Comment by dgreif** [comment]
Running with `"debug": true` in your config for the Ring platform will add additional logs.  I'd first try to see if you can pin it down to one other plugin causing the failures to occur

**Comment by zirition** [comment]
For some reason, the invocations to `node-machine-id` never fulfill the promise, and the plugin keeps waiting forever, probably to some other plugin messing around.

I will keep digging, but the problem seems to be in the dependency. 

I changed the id in function getHardwareId() in the file utils.js to a constant to, at least have the plugin working until find the problem.

Changing
'const id = yield node_machine_id_1.machineId();'
to this
'const id = "......."'

(changing .... with a random string)

**Comment by dgreif** [comment]
Wow, great debugging @zirition!  You can read through #144 and #172 which are related to machine id failing to return.  Not sure if you have the same issue, but it may get you closer

**Comment by zirition** [comment]
In my case Homebridge is running on a Raspberry running Raspbian, so seems unrelated, but it's good to know the pitfalls with ioreg.

I'll take an eye on 'node-machine-id' and I'll update this thread if I see something causing this problem.

Thanks!

**Comment by dgreif** [comment]
@zirition I added a fallback in v`6.0.2` so that it will use a random id if one can't be obtained after 5 seconds.  Give it a try and see if that gets you up and running

**Comment by zirition** [comment]
Sure, later today I will upgrade to the new version and I will update this thread.

Thank you.

PS: I can't have time to take an eye on `node-machine-id`, I didn't forgot.

**Comment by zirition** [comment]
I upgraded to the latest version and now worked. As expected, failed to get the ID on the 5 seconds window, so fallback to the random session id.

`Registering platform 'homebridge-ring.Ring'
[Ring] Initializing Ring platform...
[Ring] Request for machine id timed out.  Falling back to random session id
[Ring] Configuring 1 cameras and 1 devices for location "..........." - locationId: ..........`

Thank you!

**Comment by dgreif** [comment]
Glad it worked for you!  I'd still love to find out why it's timing out, but this should get you up and running for now.  Let me know if you ever figure out the deeper issue.
