### ISSUE TITLE
Question: how do you update the plugin?

### ISSUE THREAD

**Issue by TejasAntani** [dgreif/ring#229]
As new releases are made available?

**Comment by dgreif** [comment]
The easiest way to do updates is to install `homebridge-config-ui-x` and use the web app to see what updates are available and install them.  Assuming you have a "normal" homebridge setup, you can run `npm i -g homebridge-ring` to update it (same command you used to install it initially).  For future reference, questions like this one or general discussion are better served on the [homebridge sub reddit](https://www.reddit.com/r/homebridge/) or [homebridge slack](https://slackin-znyruquwmv.now.sh/).  GitHub issues should be more focused on issue or feature requests for this specific plugin
