### ISSUE TITLE
Question: Number of DNS requests

### ISSUE THREAD

**Issue by cladmonitor** [dgreif/ring#230]
I have a pihole instance running on my workstation LAN, typically my IoT LAN hits CloudFlare DNS directly so I've never really seen the requests being made by devices there. I decided to add a pihole instance to that as well and was pretty shocked to see the number of daily requests to api.ring.com. Im seeing no less than 1 request per second and in 23 hours its at 80,000 and counting. 

Is this by design?

**Comment by dgreif** [comment]
See #116 and #145 - This is intended behavior.  Unfortunately the Ring api doesn't provide a good way to get motion/ding events without polling for them.
