### ISSUE TITLE
Ring devices don't show up

### ISSUE THREAD

**Issue by MSlawik** [dgreif/ring#232]
Hi,
I installed the plugin and used 2fa and generated the refresh token. the config file looks correct, but for some reason no ring devices are listed in Homebridge.
        {
            "refreshToken": "xxxxx",
            "hideCameraMotionSensor": true,
            "platform": "Ring"
        }

Node.js Version v12.14.1
NPM Version v6.13.6

Any ideas?
thx, marcus

**Comment by donavanbecker** [comment]
did you try the new config UI x option to get the refresh token?

**Comment by MSlawik** [comment]
Yes. I used the UIx plugin. And it was correctly transferred to the config file.

Gruss,
Marcus
________________________________
Von: donavanbecker <notifications@github.com>
Gesendet: Saturday, January 18, 2020 12:59:13 PM
An: dgreif/ring <ring@noreply.github.com>
Cc: Marcus Slawik <M.Slawik@F5.com>; Author <author@noreply.github.com>
Betreff: Re: [dgreif/ring] Ring devices don't show up (#232)


EXTERNAL MAIL: noreply@github.com


did you try the new config UI x option to get the refresh token?

**Comment by donavanbecker** [comment]
what devices do you have?

**Comment by MSlawik** [comment]
Doorbell pro & floodlight cam.

Gruss,
Marcus
________________________________
Von: donavanbecker <notifications@github.com>
Gesendet: Saturday, January 18, 2020 3:31:04 PM
An: dgreif/ring <ring@noreply.github.com>
Cc: Marcus Slawik <M.Slawik@F5.com>; Author <author@noreply.github.com>
Betreff: Re: [dgreif/ring] Ring devices don't show up (#232)


EXTERNAL MAIL: noreply@github.com


what devices do you have?

**Comment by donavanbecker** [comment]
can you post the config?

**Comment by dgreif** [comment]
@MSlawik couple questions:

Did you restart homebridge after you set your config?
In your logs, do you see `[Ring] Initializing Ring platform...`?
In your logs, do you see something like `[Ring] Configuring X cameras and X devices for location "X"`?

**Comment by MSlawik** [comment]
@donavanbecker 
here my complete config:
{
    "bridge": {
        "name": "Homebridge",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": 51826,
        "pin": "xxx-xx-xxx"
    },
    "description": "Home Smart Home",
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "red",
            "restart": "sudo -n systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "sudo": true,
            "log": {
                "method": "systemd",
                "service": "homebridge"
            }
        },
        {
            "platform": "HomeMatic",
            "name": "HomeMatic CCU2",
            "ccu_ip": "192.168.0.7",
            "filter_device": [],
            "filter_channel": [],
            "outlets": [],
            "doors": [],
            "programs": [],
            "subsection": "Homekit",
            "variables": []
        },
        {
            "refreshToken": "abcdefgh",
            "hideCameraMotionSensor": true,
            "platform": "Ring"
        }
    ],
    "accessories": []
}

**Comment by MSlawik** [comment]
@dgreif 
yes, i did restart home bridge.
where can I find these log?

**Comment by donavanbecker** [comment]
Depends how your HomeBridge is setup?  If you have the latest config UI x it will tell you where to find your logs and even has a place that shows you your logs

**Comment by MSlawik** [comment]
I got it. In the logs I saw that the refresh token was not valid. I recreated it, now the devices show up.
thank you!
