### ISSUE TITLE
Before new update live stream faster refesh

### ISSUE THREAD

**Issue by clipse2004** [dgreif/ring#238]
Hey dude,
Before I installed the last update, my ring refresh the live stream very fast!
Now it’s same like 3 versions before, it refresh after minutes :/ 
Sorry i didn’t want to add a bug label ^^

**Comment by dgreif** [comment]
I created issue templates for a reason - please fill out the details or I don't have enough information to help you.  Unfortunately your comment that it "refreshes after minutes" is too vague to understand.
