### ISSUE TITLE
Ring

### ISSUE THREAD

**Issue by wildman199** [dgreif/ring#240]
# Bug Report

### Describe the Bug
Checked and reconfigured my network. Network is fine. I'm still getting this message.

this template seems to have good recommendations but I don't know how to get to these configs. please help. I went with HOOBS in hope that it would just work. 

### Screenshots/Logs

```
[Homebridge] [1/21/2020, 9:58:30 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
```

(Edited, pulling original issue out of template comment)

**Comment by donavanbecker** [comment]
What kind of bug is this?

**Comment by dgreif** [comment]
@wildman199 there have been similar issues in the past, like #199.  @Bukashk0zzz claimed that his was a DNS issue, but I'm not sure exactly what caused it.  Ultimately, this is an issue with either your homebridge server or network setup.  Please post updates here if you get it figured out.  @Bukashk0zzz, I would appreciate an update on how you fixed yours if you are able.

**Comment by dgreif** [comment]
@wildman199 any updates?

**Comment by Bukashk0zzz** [comment]
I run Homebridge inside Docker. And after a hard reboot of PC (power outage) docker service start with old DNS settings that were in /etc/resolv.conf
I just update settings, restart docker service and that it.

**Comment by dgreif** [comment]
Thanks for the details @Bukashk0zzz!  Closing this due to lack of response from @wildman199
