### ISSUE TITLE
Delay in notification, no snapshot

### ISSUE THREAD

**Issue by baeef** [dgreif/ring#244]
After pressing the doorbell there is a big delay before I get a notification through Homekit. It takes like 10-20 seconds more than the Ring notification. I don't get a snapshot either with the Homekit notification. 

However when I press the doorbell again right afterwards the notifications with snapshot does come through right away. It almost seems it switches to sleep mode or something after a while.

See the log below

![907E38C1-AB36-45C8-84FC-151C9E6FF340](https://user-images.githubusercontent.com/60322075/73138617-08b25180-4065-11ea-8ca9-0cdc1beaf1af.jpeg)

Any idea what the issue can be and how to solve it?

**Comment by dgreif** [comment]
I'm going to assume that your camera is battery powered, in which case you should read through https://github.com/dgreif/ring/wiki/Battery-Cam-Snapshots which details why the behavior is the way that it is.

Just curious, were you presented with a template when you created this issue?  If so, why did you choose not to fill it out?

**Comment by baeef** [comment]
Sorry my bad, didn't read the template correctly.

Thanks for the explanation. I did read the 'camera troubleshooting' page, but hadn't found the one you refer to. This explains my problem!

**Comment by dgreif** [comment]
Great, glad that cleared it up
