### ISSUE TITLE
2fa - Can you expire a refreshToken?

### ISSUE THREAD

**Issue by fancypants66** [dgreif/ring#249]
I apologize if this has come up before - but is there an option (in ring-auth-cli or other place) to manage and/or expire previously generated a refresh tokens? Thanks.

**Comment by donavanbecker** [comment]
I would use the issue template

**Comment by dgreif** [comment]
The refresh tokens  expire automatically after 15 days if I recall correctly.  If you have the new "Control Center" feature in your Ring app, you can expire _all_ tokens for your account with "Control Center" -> "Authorized Client Devices" -> "Remove All"
