### ISSUE TITLE
Cannot add Ring video doorbell to home app

### ISSUE THREAD

**Issue by asimplegoose** [dgreif/ring#250]
I cannot seem to add the Ring video doorbell pro in the home app. I have plugin installed and the config.json appears to be working fine. The log as it appears is: 

[2/7/2020, 5:08:01 PM] [Ring] Adding new accessory lpd_v2 Wilkie St. Front Door
[2/7/2020, 5:08:01 PM] ******** St. Front Door is running on port 54204.
[2/7/2020, 5:08:01 PM] Please add [********  St. Front Door] manually in Home app. Setup Code: 565-95-363

When I attempt to add in the home app nothing appears. One thing of note is that my parents and I share one another's doorbell feeds. I was able to add their doorbell but mine does not appear. I've gone through the camera trouble shooting instructions but no luck.

Any help would be greatly appreciated!

**Comment by dgreif** [comment]
The best advice I can give is already in https://github.com/dgreif/ring/wiki/Camera-Troubleshooting#cannot-add-camera-from-home .  The fact that you see the camera in the logs means it's being properly picked up and configured by the plugin

**Comment by sdorilas** [comment]
Hey @asimplegoose  did you ever resolve this issue? I removed one of my ring cameras and now I can't add it back. The other is still in the Home App and works fine. I can also see the missing one in the logs when I run Homebridge.

**Comment by dgreif** [comment]
@sdorilas You should update to the latest version of the plugin and the latest version of homebridge. Cameras are now bridged, like all other ring devices, so you don’t have to worry about adding them individually

**Comment by sdorilas** [comment]
Both were updated today. One of my 2 Ring Cameras appear, but I did manually remove one myself. I just don’t know how to add it back. It does appear in my logs when homebridge is booting.
