### ISSUE TITLE
how to take a snapshot

### ISSUE THREAD

**Issue by jeroenterheerdt** [dgreif/ring#252]
# Bug Report

### Describe the Bug
This is not really a bug, but forgive me that I could not find another place to open this for discussion... I am trying to make my code not only expose a livestream using your browser example which works fine, but also to make a regular snapshot. I am not sure how to approach this? Would you suggest adding another output to the sipSession that calls ffmpeg to save snapshots every X seconds? Or use the getSnapShot() function? I am not even sure what that will return.
### To Reproduce
 - Create an `ApiClient`
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - ring-client-api: [e.g 6.0.3]

**Comment by dgreif** [comment]
Your best bet is to call the `getSnapshot()` method. It will return a `Promise` that resolves to a `Buffer`, or throw an error if a snapshot cannot be retrieved.  So you can do something like this:

```ts
async someFunctionInYourCode () {
  try {
    const snapshotBuffer = await camera.getSnapshot()
  } catch (e) {
    // failed to get a snapshot.  handle the error however you please
  }
}
```

**Comment by jeroenterheerdt** [comment]
Thanks, I tried that but that call seems to be blocked if a livestream is open.

**Comment by dgreif** [comment]
Yeah, that's because Ring is odd about when you can fetch a snapshot.  If you call `getSnapshot(true)`, it will return "stale" snapshots, as in they may not be from right that second.

**Comment by jeroenterheerdt** [comment]
in your expeirence how "old" will the stale snapshots be? it might be enough for my scenario. can you confirm I should be able to call `getSnapshot(true)` even if there is a livestream running?

**Comment by dgreif** [comment]
Snapshot limitations are detailed in https://github.com/dgreif/ring/wiki/Battery-Cam-Snapshots.  You can call `getSnapshot(true)` while live streaming, but there is no guarantee that you will receive a snapshot that isn't stale.
