### ISSUE TITLE
armHome()/armAway() when sensors need bypass generates UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by tsightler** [dgreif/ring#253]
# Bug Report

### Describe the Bug
 If I attempt to armHome() or armAway() to arm the alarm while sensors are in need of bypass I get an UnhandledPromiseRejectionWarning.  I thought at first this was on my side and that I was just not capturing the failed case, but even after adding catch block I still get this message:

```
(node:2367) UnhandledPromiseRejectionWarning: Error: Failed to set alarm mode to "some".  Sensors may require bypass, which can only be done in the Ring app.
    at Location.<anonymous> (/opt/ring-mqtt/node_modules/ring-client-api/lib/api/location.js:175:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/ring-mqtt/node_modules/ring-client-api/lib/api/location.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2367) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2367) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Am I still doing something wrong here or is there a missing error handling on this?

### To Reproduce
Call armHome() or armAway() when sensors need bypass.

### Expected behavior
No errors!

### Screenshots/Logs
```
(node:2367) UnhandledPromiseRejectionWarning: Error: Failed to set alarm mode to "some".  Sensors may require bypass, which can only be done in the Ring app.
    at Location.<anonymous> (/opt/ring-mqtt/node_modules/ring-client-api/lib/api/location.js:175:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/ring-mqtt/node_modules/ring-client-api/lib/api/location.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2367) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2367) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Additional context
I'm just a hobby level coder so I could be missing something obvious.  :)

### Environment

 - OS: CentOS 8
 - Node.js: v10.16.3
 - NPM: 6.9.0
 - ring-client-api: 6.2.0-alpha0

**Comment by dgreif** [comment]
@tsightler sorry to hear you are having issues.  I double checked the code on my end and it looks like I am properly returning those promises (and thus the errors) from the methods you mentioned.  Something like `armHome().catch(e => { console.log(e) })` should get rid of the `UnhandledPromiseRejectionWarning` and log the error on your end.  You can handle the error however you want within that `catch`

**Comment by tsightler** [comment]
Yeah, that's what I thought too but when I tried adding the catch but I was still getting the message.  I'm admittedly in the middle of a major code refactor, so perhaps I just screwed up my attempt to capture this error return, I'll double check my code now, it's probably something silly.

I was already handling the failure to set alarm state in my own code so I didn't even realize the API had this function built in now, looks like it's been in there a while.

**Comment by tsightler** [comment]
Sorry for the noise on this, it was a completely silly error on my part as it was coming from a portion of code I thought I had totally disabled so my catch was in a piece of code that wasn't even being called.  Thanks for setting me straight!
