### ISSUE TITLE
Ffmpeg Omx now has ffmpeg with libfdk-aac - Hope for Ring?

### ISSUE THREAD

**Issue by mikesalz** [dgreif/ring#255]
Homebridge Camera Ffmpeg Omx now has ffmpeg with libfdk-aac audio support.  Does this mean there is hope for Homebridge Ring to also natively include it?

https://github.com/oznu/docker-homebridge/issues/82#issuecomment-587392672

**Comment by oznu** [comment]
Adding ffmpeg with audio support to all the Docker image was thanks to this project I started to compile static ffmpeg binaries with everything that required for Homebridge cameras.

Pre-compiled binaries are provided for 9 different platforms across Linux, macOS and Windows:

https://github.com/oznu/ffmpeg-for-homebridge

**Comment by mikesalz** [comment]
Thanks @oznu !  Which binary would we use for Homebridge on docker running on a Synology NAS?

**Comment by oznu** [comment]
@mikesalz - No need to install anything extra for the Docker image, it's now bundled with the latest version of the image.

**Comment by mikesalz** [comment]
Just updated to the latest Homebridge image and it works perfectly!  Thanks so much!

**Comment by dgreif** [comment]
@mikesalz I opened [an issue](https://github.com/oznu/ffmpeg-for-homebridge/issues/1) on @oznu's new library to see if we can get those exported in a way that they can be pulled into `homebridge-ring` automatically, removing the need for users to install them manually.  If @oznu is able to do that, I will gladly pull it into this project.

**Comment by mikesalz** [comment]
@dgreif - I think we are set already!  @oznu added it directly to the Homebridge docker image. I downloaded the latest image and my Ring plugin now has sound!

> @mikesalz - No need to install anything extra for the Docker image, it's now bundled with the latest version of the image.

**Comment by dgreif** [comment]
@mikesalz that's great, glad it's working for you!  I'm still thinking it would be a good addition for other users who aren't using that docker image, but I'll close this issue since you are up and running
