### ISSUE TITLE
Two Step Verification now required for every login...?

### ISSUE THREAD

**Issue by david-olshefski** [dgreif/ring#256]
I see this error msg, starting today:

(node:1120) UnhandledPromiseRejectionWarning: Error: Your Ring account is configured to use 2-factor authentication (2fa).  See https://github.com/dgreif/ring/wiki/Two-Factor-Auth for details.
    at RingRestClient.<anonymous> (/Users/davidolshefski/Google_Drive_CAA/Tenant Assoc/Wolpers/ring_download/node_modules/doorbot/node_modules/ring-client-api/lib/api/rest-client.js:121:27)
    at Generator.throw (<anonymous>)
    at rejected (/Users/davidolshefski/Google_Drive_CAA/Tenant Assoc/Wolpers/ring_download/node_modules/doorbot/node_modules/ring-client-api/lib/api/rest-client.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:1120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I do not have 2FA enabled on my account. Every time I logon to ring.com, they now send me an email with a verification code. 

I chat with ring to find out why:

"Thank you so much, Dave. Upon checking here, since you're receiving the Two-Steps Verification code in your email. YOu need to put the code when you try to Log In to your Ring Account. The purpose of Two-Step Verification (2SV) is to protect you from bad actors logging into your Ring account, even if those bad actors have the proper login credentials. This feature will be enabled by default for all users and, unlike 2FA, there is no user option to opt out."

and 

"Every time you try to log into your Ring Account (any app or Ring.com) you will receive a One-Time Passcode (OTP) via email address on file, and will have to enter a 6-digit code to successfully log in to your Account."

Anyone else seeing this issue?  How do I get around this.  Do I need to use 2FA?

**Comment by david-olshefski** [comment]
ring support also told me:  "When enabling the Two-Factor Authentication, yes, you will receive an email also."

Doesn't this mean I'll need to get the email, type the code into the script every time I run it?

**Comment by sjiampojamarn** [comment]
Same issue here. Since this morning, I've been getting the email verification codes. Now, my ring cannot be connected as it failed to auth. No 2FA enabled on my account.

**Comment by david-olshefski** [comment]
Ok, so I switched to using 2FA, and got it working again.

**Comment by david-olshefski** [comment]
They must have started this policy of two step verification on all accounts today.  But I followed the directions on this link for using 2FA and it worked for me:

https://github.com/dgreif/ring/wiki/Two-Factor-Auth

**Comment by sjiampojamarn** [comment]
Tried to follow the steps, now I got 

UnhandledPromiseRejectionWarning: Error: Failed to fetch oauth token from Ring. You have requested too many 2fa codes.  Ring limits 2fa to 10 codes within 10 minutes.  Please try again in 10 minutes. (error: error requesting 2fa service to send code)

I'll try it again. Weird. I stopped all services > 10 minutes before running 

$node ring-auth-cli.js
