### ISSUE TITLE
Logins labelled as "Unknown device, android" in new Ring Control Center?

### ISSUE THREAD

**Issue by purplespider** [dgreif/ring#257]
# Feature Request

### Description
Ring's new Control Center screen in the app displays a list of all devices which connect to the account. Looking in my list, there are many instances of an "Unknown Device, android" connecting to my account. I don't have any Android devices so was immediately concerned, but am now wondering if this is HomeBridge Ring?

### Describe the solution you'd like
Add an identifiable name to avoid concern your Ring account has been compromised. e.g. "Homebridge Ring".

![IMG_4184](https://user-images.githubusercontent.com/329880/75030010-1e1b6f80-549b-11ea-82da-422f190ec9a1.PNG)

**Comment by dgreif** [comment]
I completely agree that it needs to display differently.  Just release v`7.0.0`, which will automatically set the name to `homebridge-ring` for homebridge, and `ring-client-api` for any projects directly using the api.  Shows up like this:
![image](https://user-images.githubusercontent.com/3026298/75047890-d5f15280-5484-11ea-84ea-c01160a1b7e1.png)
