### ISSUE TITLE
Have Ring Chime show as Separate Tile/Accessory

### ISSUE THREAD

**Issue by Nate872711** [dgreif/ring#262]
# Feature Request

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instuctions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by ifeign** [comment]
Why? What purpose would it serve to have the chime in HomeKit?

**Comment by Nate872711** [comment]
> Why? What purpose would it serve to have the chime in HomeKit?

Same as anything else in Homekit.  Easier to use from the Home App instead of going to the separate Manufacturer's app.

**Comment by ifeign** [comment]
There’s nothing to control on the chime besides the sound, which you’ll
have to do in the Ring app. What kind of accessory do you propose it
appears as? There is no chime accessory, so it would have to be an
occupancy sensor or similar.

**Comment by dgreif** [comment]
I was planning to register it as a speaker (which can't be controlled in Home, but can in 3rd party HomeKit apps), as well as a switch or two to turn it on/off for motion/ding chimes.  Similar to the switch I added for controlling mechanical doorbells ringing or not ringing

**Comment by ifeign** [comment]
I wasn’t aware that Homebridge supported speaker accessories. My bad.

**Comment by dgreif** [comment]
No problem! I’m happy to discuss use cases in case there are other ideas for what should be visible in HomeKit. Let me know if I missed anything

**Comment by dgreif** [comment]
Chime support has been added in v9.2.0. You can snooze for 24 hours, play the "ding" sound, and play the "motion" sounds.

Huge thanks to @jadenv for implementing the API part of this, which was definitely the more tedious half of the feature.
