### ISSUE TITLE
Homebridge crashing after opening Live feed

### ISSUE THREAD

**Issue by rp1989** [dgreif/ring#264]
Hi,

Im getting the error below when viewing the ring doorbell live feed then homebridge crashes. When viewing the live feed i can see my ring door bell as expected and hear the audio, it only crashes when i close the live feed.

Any suggestions on how to resolve this?

Im running homebridge on a raspberry pi 3 with the versions below:
OS - 10 (Buster)
Node JS - 9.9.0
NPM - 5.6.0
Homebridge - 0.4.52

Tue, 03 Mar 2020 07:04:10 GMT EventedHTTPServer [::ffff:192.168.1.17] HTTP request: /resource
    at Timer.listOnTimeout (timers.js:267:5)
    at tryOnTimeout (timers.js:304:5)
    at ontimeout (timers.js:466:11)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge/lib/cli.js:46:17)
    at process.exit (internal/process.js:140:15)
    at process.emit (events.js:180:13)
    at process.exitHandler (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-session.js:135:25)
[2020-3-3 07:04:10] TypeError: process.off is not a function
        request: [Function: request] } } }
        get: [Function: get],
        createServer: [Function: createServer],
        Server: [Function],
        globalAgent: [Agent],
      { Agent: [Function],
     'https:': 
        request: [Function: request] },
        get: [Function: get],
        createServer: [Function: createServer],
        ServerResponse: [Function],
        Server: [Function],
        OutgoingMessage: [Function],
        IncomingMessage: [Function],
        globalAgent: [Agent],
        ClientRequest: [Function],
        Agent: [Function],
        STATUS_CODES: [Object],
        METHODS: [Array],
      { _connectionListener: [Function: connectionListener],
   { 'http:': 
  nativeProtocols: 
  port: null,
  hostname: 'api.ring.com',
  auth: undefined,
  agents: { http: undefined, https: undefined },
  agent: undefined,
     'User-Agent': 'axios/0.19.2' },
     'Content-Type': 'application/x-www-form-urlencoded',

**Comment by dgreif** [comment]
@rp1989 I really appreciate that you provided all of the info and logs.  Looks like you are on node `9.9.0`, and this package requires node 10+.  Once you update to a newer version of node, that error should go away.

**Comment by rp1989** [comment]
Many thanks for your response. I can confirm updating node to latest 12.16.1 has resolved the issue.
