### ISSUE TITLE
Switch off / unvisible - Location Mode Button (Alarm) in HomeKit 

### ISSUE THREAD

**Issue by hhunger2404** [dgreif/ring#266]
# Feature Request

### Description
Since one of the latest version a Alarm Button appeared in HomeKit (symbolized by a siren). Simulates a security system (armed, disarmed etc.). I personally only have a video doorbell and don’t want that button. It’s actually confusing all of my family members.

### Describe the solution you'd like
Give me an option to switch it of like other buttons by HideLocationModeSwitch = true in the config.json

### Describe alternatives you've considered
None

### Device data
Ring video doorbell 2
![A3C2036D-0B5B-46AB-B7F6-B9011E9227BB](https://user-images.githubusercontent.com/61904020/76141376-d16f9100-6063-11ea-9c84-144678b2f962.jpeg)

**Comment by donavanbecker** [comment]
@hhunger2404 do you have ring modes enable in your ring app?

**Comment by hhunger2404** [comment]
Honestly, I‘ve no clue where this could be possible in my Ring App. 
I don‘t have the menue item that Ring described in this post.

https://support.ring.com/hc/en-us/articles/360036107792-Control-All-your-Ring-Cameras-with-Modes

So obviously I‘ve it enabled by their rollout and no option to disable it in my app.

Viele Grüße
Heiko

——————————

**Comment by donavanbecker** [comment]
* first, what version of the plugin are you running? if you are on not at 7.2.0 then update.

* second if you are indeed on 7.2.0, then set `"debug": true` in your config for the ring platform, it should log out a line like `Location Mode: {"mode":"disarmed", ....}`. @dgreif will need this.

**Comment by hhunger2404** [comment]
Hi,

[2020-3-7 13:17:30] [Ring] Location Mode: {"mode":"disarmed","lastUpdateTimeMS":1583584071143,"securityStatus":{},"readOnly":false,"notYetParticipatingInMode":[],"responseTimestamp":1583584783000}
[2020-3-7 13:17:30] [Ring] Configuring 1 cameras and 2 devices for location "17c" - locationId: 8578994b-eec7-4523-69e6-68bef4b94535
[2020-3-7 13:17:30] [Ring] Adding new accessory doorbell_v4 17c Ring
[2020-3-7 13:17:30] 17c Ring is running on port 44787.
[2020-3-7 13:17:30] Please add [17c Ring] manually in Home app. Setup Code: 033-44-254

Viele Grüße
Heiko

——————————

**Comment by donavanbecker** [comment]
Just FYI [#260](https://github.com/dgreif/ring/issues/260#issuecomment-592851423)

**Comment by dgreif** [comment]
@hhunger2404 I just released v7.2.1 which allows you to set "locationModePollingSeconds": 0 in your homebridge config. If you set that option to 0, it will now hide the location mode switch.  Sorry I can't find a better way to determine if Ring has turned that feature on for users yet!

**Comment by hhunger2404** [comment]
Perfect,

Works. Thank you very much for your service.

Viele Grüße
Heiko

——————————
