### ISSUE TITLE
Live view not working for camera

### ISSUE THREAD

**Issue by dswee999** [dgreif/ring#268]
Snapshots are working fine but when I try live view now it says no response from camera. FFmpeg is installed. Please help. Logs just say waiting for live stream and then stopped life stream. There’s no real error message that I see?

**Comment by arqjavier** [comment]
i have the same problem

**Comment by donavanbecker** [comment]
@arqjavier  @dswee999 You should each fill this template out for this issue [Live Streaming Issue Template](https://github.com/dgreif/ring/blob/master/.github/ISSUE_TEMPLATE/live_streaming_issues.md) so your whole setup is known. Using Eero routers has been known to prevent live streaming.

**Comment by dgreif** [comment]
@dswee999 @arqjavier I suggest you take a look at https://github.com/dgreif/ring/wiki/Camera-Troubleshooting.  That's the majority of help that I can give you on fixing live stream issues.  As @donavanbecker said, there is a know issue with Eero routers, which is discussed at length in #211.  Nothing I can do for this issue beyond that, sorry!

**Comment by arqjavier** [comment]
> @dswee999 @arqjavier I suggest you take a look at https://github.com/dgreif/ring/wiki/Camera-Troubleshooting. That's the majority of help that I can give you on fixing live stream issues. As @donavanbecker said, there is a know issue with Eero routers, which is discussed at length in #211. Nothing I can do for this issue beyond that, sorry!

I see Waiting for stream data

**Comment by dgreif** [comment]
> If you see Waiting for stream data followed by Stopped Live Stream, it is a network issue. Your router is not allowing the ring plugin to open the ports that it needs for stream data to flow in. Check your router to see if it has UPnP or NAT-PMP features that you can enable. If those settings aren't available or don't fix the issue, there isn't much I can do for you. If you are a developer and are able to find a code solution to the problem, I would be happy to take a PR to help others having similar network issues.
