### ISSUE TITLE
Ring refresh token is not valid

### ISSUE THREAD

**Issue by adyrobady** [dgreif/ring#275]
Hi everybody I’m new to this so go easy on my. My ring refresh token is not valid. I’ve tried getting new ones. Please tell me where I’m going wrong
[Homebridge] [3/29/2020, 3:10:33 PM] Got SIGINT, shutting down service...
[Homebridge] [3/29/2020, 3:10:35 PM] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [3/29/2020, 3:10:35 PM] Loaded plugin: "ring"
[Homebridge] [3/29/2020, 3:10:35 PM] Registering platform "homebridge-ring.Ring"
[Homebridge] [3/29/2020, 3:10:35 PM] Loading 1 platforms...
[Homebridge] [3/29/2020, 3:10:35 PM] [Ring] Initializing Ring platform...
[Homebridge] [3/29/2020, 3:10:35 PM] Loading 0 accessories...
[Homebridge] [3/29/2020, 3:10:35 PM] API launched
[Homebridge] [3/29/2020, 3:10:35 PM] Service is running on port 51826.
[Homebridge] [3/29/2020, 3:10:36 PM] [Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed
[Homebridge] [3/29/2020, 3:10:36 PM] [Ring] Error connecting to API
[Homebridge] [3/29/2020, 3:10:36 PM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.
    at RingRestClient.getGrantData (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:85:15)
    at RingRestClient.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:89:36)
    at Generator.next (<anonymous>)
    at /home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:4:12)
    at RingRestClient.getAuth (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:88:16)
    at RingRestClient.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:113:33)
    at Generator.throw (<anonymous>)
    at rejected (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:6

**Comment by dgreif** [comment]
It is most likely a copy paste issue. The easiest way to get set up is to install the homebridge-config-ui-x plugin. It has built in support for logging in to this plugin

**Comment by adyrobady** [comment]
Thank you. Your ui is amazing and set up instantly. How can I donate

Thanks
Adrian
Sent from my iPad

On 29 Mar 2020, at 18:20, Dusty Greif <notifications@github.com> wrote:

﻿

It is most likely a copy paste issue. The easiest way to get set up is to install the homebridge-config-ui-x plugin. It has built in support for logging in to this plugin

**Comment by dgreif** [comment]
@adyrobady I'm glad it worked well for you!  If you are happy with homebridge-ring, you can donate to [my paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=HD9ZPB34FY428&currency_code=USD&source=url).  The UI is all thanks to [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x), which accepts donations at https://paypal.me/oznu
