### ISSUE TITLE
503 Error on start of Homebridge

### ISSUE THREAD

**Issue by Casuallynoted** [dgreif/ring#277]
# Bug Report

### Describe the Bug
Homebridge starts but then produces a 504 error in the ring plugin.

### To Reproduce
 - Start Homebridge
 - All homebridge plugins stop working instantly
 - Check logs

### Expected behavior
It'd been working for nearly a month or so under 2FA before this started.

### Screenshots/Logs

Here's the beginning of the error:

[4/1/2020, 11:50:45 AM] [Ring] Request to https://app.ring.com/api/v1/mode/location/[Removed this cause not sure if it's supposed to be secret] failed with status 504. Response body: <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

{
            "refreshToken": "[Removed refresh token]",
            "platform": "Ring"
        }

```

### Environment
 - OS: Raspbian
 - Node.js: 10.14.0
 - NPM: 6.14.2
 - homebridge-ring: 7.2.1
 - homebridge: 0.4.53

**Comment by Casuallynoted** [comment]
*Meant 504 on the issue title.

**Comment by dgreif** [comment]
@Casuallynoted I think Ring has had a number of issues over the last couple days.  Are you still having issues?

**Comment by dgreif** [comment]
Closing due to lack of response
