### ISSUE TITLE
Enable Location Mode? Dont showing Security Button for switching

### ISSUE THREAD

**Issue by clipse2004** [dgreif/ring#278]
# Bug Report

### Describe the Bug
 Alarm System Button doesnt show up & refresh token after restart -> error

### In the RIng App the location Mode works fine, when i was running homebridge on a normal pi ist worked also, but now on Hoobs the alarm system switch didnt shiow up, only the cam is there. 
and next problem is with the refresh token, i got one, installed it -> works. After restart it says invalid token.. 

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

Config:
 {
            "platform": "Ring",
            "hideDoorbellSwitch": true,
            "hideInHomeDoorbellSwitch": false,
            "hideUnsupportedServices": false,
            "refreshToken": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "alarmOnEntryDelay": true,
            "debug": true,
            "hideLightGroups": false,
            "hideCameraSirenSwitch": false,
            "plugin_map": {
                "plugin_name": "ring"
            },
            "hideAlarmSirenSwitch": false,
            "hideCameraMotionSensor": false,
            "showPanicButtons": false,
            "cameraStatusPollingSeconds": 20,
            "cameraDingsPollingSeconds": 2,
            "locationIds": []
        },

```

### Environment
Hoobs newest verson -> also ring app newest version

this is my error:
ing] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed
[Homebridge] [4/1/2020, 4:07:24 PM] [Ring] Error connecting to API
[Homebridge] [4/1/2020, 4:07:24 PM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.
    at RingRestClient.getGrantData (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:85:15)
    at RingRestClient.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:89:36)
    at Generator.next (<anonymous>)
    at /home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:4:12)
    at RingRestClient.getAuth (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:88:16)
    at RingRestClient.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:113:33)
    at Generator.throw (<anonymous>)
    at rejected (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by dgreif** [comment]
There were some issues with Rings refresh tokens over the past week, but they seem to be resolved now.  Could you try generating a new refresh token and running the plugin again?

Regarding your issue with location modes, my guess is the `locationIds: []` option.  Since you supply the option, I check to see if each of your locations is listed, and hide it if not.  You should remove that line from your config and I'd expect your devices & location mode switch to show up.

**Comment by dgreif** [comment]
@clipse2004 did everything start working for you?  There were some issues with refresh tokens on Ring's end around the time that you reported this

**Comment by clipse2004** [comment]
Hi dustin, yes everything works fine now :)
Thx for your help
