### ISSUE TITLE
onNewDing.subscribe sends the same ding over and over

### ISSUE THREAD

**Issue by hanlongwang** [dgreif/ring#281]
camera.onNewDing.subscribe(ding => {
        const event =
          ding.kind === 'motion'
            ? 'Motion detected'
            : ding.kind === 'ding'
            ? 'Doorbell pressed'
            : `Video started (${ding.kind})`

        console.log(
          `${event} on ${camera.name} camera. Ding id ${
            ding.id_str
          }.  Received at ${new Date()}`
        )

Generates this on a doorbell press:

Doorbell pressed on Front Door camera. Ding id 6812430812854837500.  Received at Sun Apr 05 2020 20:16:41 GMT-0700 (Pacific Daylight Time)
Doorbell pressed on Front Door camera. Ding id 6812430812854837500.  Received at Sun Apr 05 2020 20:16:41 GMT-0700 (Pacific Daylight Time)
Doorbell pressed on Front Door camera. Ding id 6812430812854837500.  Received at Sun Apr 05 2020 20:16:42 GMT-0700 (Pacific Daylight Time)
Doorbell pressed on Front Door camera. Ding id 6812430812854837500.  Received at Sun Apr 05 2020 20:16:42 GMT-0700 (Pacific Daylight Time)
Doorbell pressed on Front Door camera. Ding id 6812430812854837500.  Received at Sun Apr 05 2020 20:16:43 GMT-0700 (Pacific Daylight Time)
Doorbell pressed on Front Door camera. Ding id 6812430812854837500.  Received at Sun Apr 05 2020 20:16:43 GMT-0700 (Pacific Daylight Time)

**Comment by hanlongwang** [comment]
I used a local hashmap to filter out the duplicates, but would be great to fix it on the onNewDing function instead.

**Comment by dgreif** [comment]
That's really interesting.  The way that is printing out, it looks like Ring is returning the same dings repeatedly from their active dings endpoint.  This never used to be the case, so that subscription only fired once (unless you tried to start a live stream while another active ding already existed).  I'll take a look at it when I get some time

**Comment by hanlongwang** [comment]
I tried to reproduce it a few times yesterday from what I recollect it happened when a second ding was happened while an active ding was there. In this case it was always motion and then doorbell ring, since you can't really avoid motion detected before you press the doorbell. Having motion alone did not cause this.

**Comment by dgreif** [comment]
Do you have it set up to start a live stream when a ding is detected?  If so, the process of starting the live stream is likely causing a new active ding (with the same id) to become available, which would then trigger your code to start another live stream, causing another ding...in an infinite loop.  If that's the case, then the local hashmap would probably be the correct solution

**Comment by hanlongwang** [comment]
I am recording when a ding is detected using the camera.recordToFile function.

**Comment by dgreif** [comment]
This is something you will need to filter out on your end.  By calling `recordToFile`, you may cause a new ding to be created simply by the way that Ring has it set up.  You should keep track of whether or not you are currently recording, and not call `recordToFile` if it is already in progress.
