### ISSUE TITLE
Entrance Ring Doorbell not responding

### ISSUE THREAD

**Issue by DMBlakeley** [dgreif/ring#282]
# Bug Report

### Describe the Bug
 As of last evening home bridge-ring logs into Ring successfully (confirmed on ring.com account webpage), however, Homekit reports "Entrance Ring Doorbell not responding". Creating new token did not correct issue.

### To Reproduce
 - Start Homebridge, verify that ring plugin properly loaded
 - Open Homekit on iPhone or iPad
 - See error at top of Homekit screen. If you try to open Ring camera "live view" you also receive not responding message.

### Expected behavior
 Ring doorbell camera snapshots and live view operational.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

        {
            "platform": "Ring",
            "refreshToken": "eyJhbGciOiJIUzU..."
        },

```

### Environment

 - OS: OSX 10.11.6
 - Node.js: 12.16.1
 - NPM: 6.14.4
 - homebridge-ring: 7.2.2
 - homebridge: 0.4.54-beta.15

**Comment by dgreif** [comment]
@DMBlakeley I've been having good luck with my live streams, even on `7.2.2`.  Might be worth doing a restart of your homebridge server, home hub, and force quitting the Home app.  If none of those resolve it, try reverting to `7.2.1` and see if it works before the latest dependency bump.  If `7.2.1` isn't working, might be the homebridge beta causing issues.

PS thanks for representing the Ring plugin in the homebridge beta testing!  I would love to help out more on that, but life has been way too busy lately.  Let me know if you need anything specific along the way

**Comment by DMBlakeley** [comment]
Turns out the problem was self-inflicted. Was adding new plug-in and in the process of understanding the settings I goofed up the persist configuration files. Needed to remove and re-add Homebridge-Ring camera.

No operational problem with the following configuration:
- OS: OSX 10.11.6
- Node.js: 12.16.1
- NPM: 6.14.4
- homebridge-ring: 7.2.2
- homebridge: 0.4.54-beta.15
