### ISSUE TITLE
Can't hide Siren (alarm in Homekit)

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#283]
<img width="494" alt="image" src="https://user-images.githubusercontent.com/47482260/78589899-dd07d080-7838-11ea-9081-fb74d3e1f1f1.png">

# Bug Report

### Describe the Bug
 When I set the setting to hide Ring Siren/Alarm switch it still shows the alarm in Homekit

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 Always happens since the latest hoops update just now

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
<img width="494" alt="Screenshot 2020-04-06 at 18 55 43" src="https://user-images.githubusercontent.com/47482260/78589768-a467f700-7838-11ea-96b7-d1bc9f43f23d.png">

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment
<!-- ✍️edit: -->
 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] <!-- run `node -v` to get current version -->
 - NPM: [e.g 6.13.4] <!-- run `npm -v` to get current version -->
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50]

**Comment by dgreif** [comment]
The `hideAlarmSirenSwitch` hides the _switch_ within that accessory, which can be used to turn the actual siren sound on/off on your ring alarm base station.  It _does not_ hide the alarm accessory itself, which is used to change the mode between away/home/disarmed.

If you do not have a ring alarm, you may be seeing that because of the new Ring Location Camera Modes feature.  Is that the case?

**Comment by adavison007** [comment]
hi @dgreif you are correct, it's because I recently enabled the new modes feature (I don't have the alarm)... is there a possibility you can add hide or show this in Homekit? I already have an alarm in homekit and it's another icon I don't need.

Hope you can help?

**Comment by dgreif** [comment]
The locations mode accessory shouldn't show if it's in the same location as your ring alarm.  My guess is that you have the alarm in one location, and the modes feature in a different location.  

But, if you still want to hide it, you can set `"locationModePollingSeconds": 0`.  Let me know if that works 😄

**Comment by adavison007** [comment]
> The locations mode accessory shouldn't show if it's in the same location as your ring alarm. My guess is that you have the alarm in one location, and the modes feature in a different location.
> 
> But, if you still want to hide it, you can set `"locationModePollingSeconds": 0`. Let me know if that works 😄

@dgreif I don't have a ring alarm.... ??

**Comment by dgreif** [comment]
Wow, totally misread that in your last comment 🤦‍♂.  Sorry!

**Comment by dgreif** [comment]
@adavison007 did that setting hide it for you properly?

**Comment by adavison007** [comment]
Sorry, I missed that command, just tried it and it worked fine, big thanks

Adam Davison
adavison@me.com <mailto:adavison@me.com>
01276 63145
07748 761448

On 15 Apr 2020, at 13:10, Dusty Greif <notifications@github.com> wrote:


@adavison007 <https://github.com/adavison007> did that setting hide it for you properly?
