### ISSUE TITLE
Cannot streamVideo anymore right after a ding event

### ISSUE THREAD

**Issue by hanlongwang** [dgreif/ring#284]
Another recent change I noticed was streamVideo does not work immediately after any ding event. Originally my script was working for a few months and it was calling camera.recordToFile in camera.onNewDing.subscribe and writing to my NAS. Now await camera.recordToFile never finishes. I tried initiating in a separate process, within a certain time period you cannot streamToVideo.

My theory is ring changed since 4/4 and is now expecting you to answer the motion directly with the ding id of some sort, and that is missing from the API. I'm assuming they rolled this update as well as the the refreshToken changes as part of their API changes.

**Comment by hanlongwang** [comment]
Further debugging looks like it's waiting on createSipSession()

**Comment by hanlongwang** [comment]
This is the error I'm seeing now:

Error: sip INVITE request failed with status 480
    at /home/hanlong/capture-ring/node_modules/ring-client-api/lib/api/sip-session.js:169:28
    at searching (/home/hanlong/capture-ring/node_modules/sip/sip.js:1313:5)
    at /home/hanlong/capture-ring/node_modules/sip/sip.js:1294:41
    at Object.message (/home/hanlong/capture-ring/node_modules/sip/sip.js:1113:7)
    at Object.signal (/home/hanlong/capture-ring/node_modules/sip/sip.js:979:55)
    at /home/hanlong/capture-ring/node_modules/sip/sip.js:1341:24
    at onMessage (/home/hanlong/capture-ring/node_modules/sip/sip.js:555:9)
    at content (/home/hanlong/capture-ring/node_modules/sip/sip.js:490:7)
    at headers (/home/hanlong/capture-ring/node_modules/sip/sip.js:477:9)
    at TLSSocket.<anonymous> (/home/hanlong/capture-ring/node_modules/sip/sip.js:501:27)

**Comment by dgreif** [comment]
`480` happens when the stream was already connected to and disconnected by another viewing source.  It should automatically create a new on-demand ding and start the stream again.  make sure you are on the latest version of the library

**Comment by hanlongwang** [comment]
I am using the latest version of the library, I upgraded after the refreshToken changes.

This used to work and was broken after 4/4.

camera.onNewDing.subscribe((ding) => {
  await camera.recordToFile('test.mp4', 10)
}

**Comment by hanlongwang** [comment]
I am using the latest version of the library, I upgraded after the refreshToken changes.

This used to work and was broken after 4/4 with status 480

```
camera.onNewDing.subscribe((ding) => {
    await camera.recordToFile('test.mp4', 10)
}
```

**Comment by jbittner1002** [comment]
I am getting the same 480 status when trying to connect right after a button push or a motion with details all sip details included with the ding.
No one else opened the stream before I am doing my tests so it cannot be an issue with a stream that was already connected.

**Comment by hanlongwang** [comment]
I figured out my issue, I had IFTTT Ring integration also on, which was messing it up. That was what the 480 was, IFTTT apparently was one of the ding accepts, and this was the other.

Now that I disabled IFTTT it works again.
