### ISSUE TITLE
Anyone else seeing more queries to app.ring.com since 7.2.2?

### ISSUE THREAD

**Issue by stevehoek** [dgreif/ring#285]
# Bug Report

### Describe the Bug
Since upgrading my Homebridge docker container with Homebridge-Ring 7.2.2, I notice that my pi-hole is receiving many more queries to app.ring.com coming from the container than previously.

### To Reproduce
 - Start Homebridge
-  watch requests to app.ring.com

### Expected behavior
should not need to query this every 2 seconds... why not using only api.ring.com

### Environment
latest oznu homebridge docker on Synology

**Comment by dgreif** [comment]
The new Location Modes feature does polling against the `app.ring.com` domain every 20 seconds if you have Modes enabled. If you don't care about location modes, set `"locationModePollingSeconds": 0` in your config.

**Comment by dgreif** [comment]
did that help @stevehoek?

**Comment by stevehoek** [comment]
@dgreif yes it did; I set it to 0 and it is back to normal now.  Thanks!
