### ISSUE TITLE
Problem when try to ad email/password

### ISSUE THREAD

**Issue by Piero24** [dgreif/ring#286]
Hi, I have this problem when try to install ring-client-api ring-auth-cli

> pi@raspberrypi:~ $ npx -p ring-client-api ring-auth-cli
ffmpeg version 4.2.git-47773f7 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal
  libavutil      56. 40.100 / 56. 40.100
  libavcodec     58. 68.102 / 58. 68.102
  libavformat    58. 38.100 / 58. 38.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 75.100 /  7. 75.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
This CLI will provide you with a refresh token which you can use to configure ring-client-api and homebridge-ring.
Email: ******@gmail.com
Password: **********
Error: Failed to fetch oauth token from Ring. Verify that your email and password are correct. (error: access_denied)
    at RingRestClient.<anonymous> (/home/pi/.npm/_npx/2242/lib/node_modules/ring-client-api/lib/api/rest-client.js:132:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/pi/.npm/_npx/2242/lib/node_modules/ring-client-api/lib/api/rest-client.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by dgreif** [comment]
Either you entered the wrong email/password, or your account is currently locked

**Comment by dgreif** [comment]
@Piero24 any luck?  If not, I recommend setting up `homebridge-config-ui-x` and using it to log in to your Ring account.
