### ISSUE TITLE
camera and motion sensor missing after update to 7.2.2

### ISSUE THREAD

**Issue by cab113** [dgreif/ring#287]
# Bug Report

### Describe the Bug
i have lost the camera and motion sensor from ring doorbell pro from homebridge. on home bridge restart log shows it configures 1 Camera and 2 two devices. Only alarm beacon shows up in homekit.

### To Reproduce
 upgrade to version 7.2.0

**Comment by dgreif** [comment]
I'm sorry, but there is not enough info in your issue for me to provide much support.  I'd recommend following the steps listed here: https://github.com/dgreif/ring/wiki/Camera-Troubleshooting#cannot-add-camera-from-home
