### ISSUE TITLE
Doorbell switch recognizing only single press

### ISSUE THREAD

**Issue by depaulsunny** [dgreif/ring#288]
# Bug Report

 

First of, this is a fantastic plugin, kudos!

I'm wondering if I'm missing something obvious but I figured I'll check. I have the ring doorbell 2. I was able to set everything up without any issues. 

However, I cannot get the Doorbell Switch to recognize anything other than "Single Press". Is there something I should be changing in my settings to get it to recognize that?

Thanks in advance!

I'm on the latest version on everything (Raspbian, homebridge, etc.)

**Comment by dgreif** [comment]
@depaulsunny glad you are enjoying the plugin.  Unfortunately the programmable switch from the doorbell only supports a single press, not double or long press.  I can't hide the unsupported actions in HomeKit and Ring doesn't have an event for anything other than a single press.

**Comment by depaulsunny** [comment]
Ah, makes sense. Thanks!
