### ISSUE TITLE
Packaged ffmpeg no longer supports High Sierra causing dependency issues / won’t install

### ISSUE THREAD

**Issue by SafariKC** [dgreif/ring#289]
# Bug Report

### Describe the Bug
With the last two updates your dependency on the homebridge ffmpeg package upped the dependency version and is no longer compatible with macOS High Sierra.  

### To Reproduce
High Sierra macOS machine
Install homebridge-ring@latest it should fail to install.  
Install homebridge-ring@7.2.0 works

### Expected behavior
I get it helps some people but do we need to force the install of ffmpeg?  We use this mostly for ring alarm. 

### Screenshots/Logs
The log just fails the install, if I add the package itself it tells me that it doesn’t support High Sierra. 

### Homebridge Ring Config

{
            "refreshToken": "shhhhhhitsasecret",
            "locationIds": [
                "Needtoknowbasis”
            ],
            "platform": "Ring"
        }

### Environment
 - OS: High Sierra 10.13.5
 - Node.js: 13.12.0
 - NPM: 6.14.4
 - homebridge-ring: 7.2.1 & 7.2.2
 - homebridge: 0.4.53

**Comment by dgreif** [comment]
Can you include the error message you are seeing when the install fails?  It should try to install ffmpeg, but the install shouldn't cause the npm install to fail if it's unable to proceed.  Once I have the log, I will probably open an issue on `ffmpeg-for-homebridge`

**Comment by SafariKC** [comment]
It had scrolled out of my buffer.  I just tried again in hopes it would fail like it did for hours last night and it’s working fine now... ... .... it’s skipping it as expected - whacky!  The only version that worked last night was 7.2.0 - go ahead and close this out sorry I lost the log but at least it’s not a real issue I guess :)
