### ISSUE TITLE
Snapshot failed to refresh after 60 attempts

### ISSUE THREAD

**Issue by nzbullet** [dgreif/ring#293]
# Bug Report

### Describe the Bug
Logs are showing errors as per below log extract. It automatically corrects itself (sometimes) and always after I restart Homebridge it is OK. 

Viewing the camera in Home works perfectly fine. 

My network is perfectly fine and I have full connectivity at the doorbell. Everything seems to be fine just that I have these errors appearing in the logs. Also because it is a non-removable battery I am unable to follow the directions to fix as per the error. 

### To Reproduce
Steps to reproduce the behaviour:
 - Start Homebridge
 - Open Logs
 - See error

### Expected behaviour
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
```

[4/15/2020, 14:58:29] [Ring] Snapshot failed to refresh after 60 attempts
[4/15/2020, 14:58:29] [Ring] 404 from endpoint https://api.ring.com/clients_api/snapshots/image/25573326
[4/15/2020, 14:58:29] [Ring] Failed to retrieve snapshot for Front Door (53.024s).  The camera currently reports that is it online
[4/15/2020, 14:58:29] [Ring] Front Door camera appears to be unable to upload snapshots.  This usually requires a physical restart of the camera.  Please turn off power to this camera by removing its battery or turning off the breaker for the circuit it is wired to.  Once power is cycled, snapshots should start working again.
[4/15/2020, 14:58:29] [Ring] Error: Not found with response: no snapshot
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:237:27)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[4/15/2020, 15:11:47] [Ring] Front Door Detected Motion
[4/15/2020, 15:11:47] [Ring] Snapshot for Front Door Requested
[4/15/2020, 15:12:39] [Ring] Snapshot failed to refresh after 60 attempts
[4/15/2020, 15:12:40] [Ring] Snapshot for Front Door Received (52.911s)
```

### Additional context
I have a Ring Video Doorbell v1 (Battery).

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
        {
            "platform": "Ring",
            "refreshToken": "xxx",
            "hideDoorbellSwitch": true,
            "hideCameraMotionSensor": false
        },

```

### Environment
 - OS:  Raspbian GNU/Linux Buster (10) 
 - Node.js: v12.14.1 
 - NPM: v6.13.7
 - homebridge-ring: v7.2.2
 - homebridge: Latest (non-beta)

**Comment by dgreif** [comment]
As the error states, this is an issue with the camera and not with the plugin.  If you want it fixed, you _must_ cycle power to the camera.  You should be able to find the correct breaker in your electrical panel, or as a last resort you can flip off your main breaker (not ideal, but no worse than a normal power blink from your utility company).  This issue used to pop up frequently, but rebooting the camera has fixed it in every case that I can recall.

**Comment by nzbullet** [comment]
Hey... how do I power cycle a **battery only camera** via my power board or main breaker??? 

> Also because it is a **non-removable battery** I am unable to follow the directions to fix as per the error.

Would have been good for you to read the whole issue. 

I have removed the camera from the wall, and fully charged it and the issue is still there. It is intermittent and seems it only happens when the camera has been idle for a while. 

However, I don’t think it is the camera. This only started happening recently from the last couple of updates and as stated everything actually works fine, I get snapshots and I can view the camera feed in both Home and Ring apps...it’s just I get an error in my logs. 

At the very least can you put something in the config to identify BATTERY Ring camera’s so this error isn’t presented as it is wrong. Perhaps and alternate error can be shown or be able to hide logs/errors.

**Comment by dgreif** [comment]
@nzbullet I did read the whole issue originally 😉.  I understand that you can't remove the battery, which means flipping the breaker (or removing the camera from the wall and disconnecting the wires, which I wouldn't recommend) is the only option.  It's up to you to find the _correct_ breaker and flip it, that is way outside the scope of this plugin.  I understand that your video feed is working fine in Home, but if you are seeing that error it means the plugin cannot get new snapshot.  The error is not wrong, and does apply even if it's a hard wired camera.

**Comment by nzbullet** [comment]
It’s **not** hard wired! That’s my point, there are no wires attached. It is **battery only** and with the Ring Video Doorbell (v1) you cannot remove the battery.

**Comment by dgreif** [comment]
@nzbullet I didn't realize the v1 doorbell had a fixed batter, that's very interesting!  How do you recharge the battery?

**Comment by nzbullet** [comment]
You unscrew it’s from the wall, take it inside and plug it in to USB. Very tedious.

**Comment by dgreif** [comment]
@nzbullet I apologize for the misunderstanding.  This issue has come up a number of times and a power restart was always the solution in the past.  Just had another report of this and did some testing on my end.  Looks like if you have Modes set up for the camera, and the camera is currently in a mode that prevents live viewing, then snapshots will fail to be retrieved.  I'll have to do some more digging to see if they give a specific error message in this case, but do you think that explains when you are seeing the issue?

**Comment by nzbullet** [comment]
@dgreif I have Modes switched off (as in the alarm feature - not sure why they just couldn’t call it that). I do have People Only Mode switched on so that it only sends alerts when people ar detected but wouldn’t think this affects snapshots.

Could it be to do with the timings on the Snapshot Capture?  I note in the Wiki you have: 

> These cameras (even when plugged in to a power source) will only take a snapshot once every 10 minutes

However there was an update to this and as you can see from the attached image there are now 4 options (to help with battery life). Hourly, 14 minutes, 5 minutes and 3 minutes. Mine by default is set to 14 minutes. 
![D934ECCD-AA05-4E47-857A-4FEBEA1C9D47](https://user-images.githubusercontent.com/24196566/79515374-8ef69680-809c-11ea-94ad-aab03ea99c8f.png)

**Comment by terriblefox** [comment]
Hey, got the same issue. I power cycled the camera but it doesnt affect the issue. Still no Snapshots. Also no snapshot on a new ding. The rest works fine.

+
[4/17/2020, 7:58:45 AM] [Ring] Snapshot failed to refresh after 60 attempts
[4/17/2020, 7:58:45 AM] [Ring] 404 from endpoint https://api.ring.com/clients_api/snapshots/image/21539393
[4/17/2020, 7:58:45 AM] [Ring] Failed to retrieve snapshot for Haustür (53.478s).  The camera currently reports that is it online
[4/17/2020, 7:58:45 AM] [Ring] Haustür camera appears to be unable to upload snapshots.  This usually requires a physical restart of the camera.  Please turn off power to this camera by removing its battery or turning off the breaker for the circuit it is wired to.  Once power is cycled, snapshots should start working again.
[4/17/2020, 7:58:45 AM] [Ring] Error: Not found with response: no snapshot

    at RingRestClient.<anonymous> (/homebridge/node_modules/homebridge-ring/lib/api/rest-client.js:237:27)
    at Generator.throw (<anonymous>)
    at rejected (/homebridge/node_modules/homebridge-ring/lib/api/rest-client.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by catjamz** [comment]
I'm also seeing this error after recently installing the Ring plugin. Snapshots are being taken and showing in my timeline in the Ring app, just very rarely do they make it to the Home app screen.

I'm not sure whether it is related, but if I go to Live view from the Home app, it eventually fails with a message that the camera is not responding. But when I go to the Ring app, the Live view video is in my events list.

Again Ring video doorbell v1, hard wired this time...

**Comment by tcoombs** [comment]
I also have the same issue but with my Ring Doorbell Pro. Live View always fails from the Home App. As my camera is AC powered I can reboot but this does not solve the problem. This is what I see in my HOOBS log:

02/05/2020, 17:17:20 [Ring] Snapshot for Front Gate Received (0s)
02/05/2020, 17:17:27 [Ring] Preparing Live Stream for Front Gate
02/05/2020, 17:17:29 [Ring] Waiting for stream data from Front Gate (1.229s)
02/05/2020, 17:17:38 [Ring] Stopped Live Stream for Front Gate
02/05/2020, 17:17:46 [Ring] Snapshot for Front Gate Requested
02/05/2020, 17:17:49 [Ring] Snapshot for Front Gate Received (3.927s)
02/05/2020, 17:18:00 [Ring] Snapshot for Front Gate Requested
02/05/2020, 17:18:00 [Ring] Snapshot for Front Gate is still within its life time (12.072s old)
02/05/2020, 17:18:00 [Ring] Snapshot for Front Gate Received (0.001s)
02/05/2020, 17:25:03 [Ring] Snapshot for Front Gate Requested
02/05/2020, 17:25:06 [Ring] Snapshot for Front Gate Received (3s)
02/05/2020, 17:31:22 [Ring] Snapshot for Front Gate Requested
02/05/2020, 17:31:27 [Ring] Snapshot for Front Gate Received (4.227s)
02/05/2020, 17:31:27 [Ring] Preparing Live Stream for Front Gate
02/05/2020, 17:31:28 [Ring] Waiting for stream data from Front Gate (1.445s)
02/05/2020, 17:31:37 [Ring] Stopped Live Stream for Front Gate

**Comment by javidial** [comment]
Same issue here. Live view always fails from the Home App

**Comment by dgreif** [comment]
Snapshot behavior has been updated in v`8.1.0`.  This includes handling Modes as best I can.  I'll post a full explanation of the changes in #311
