### ISSUE TITLE
Homebridge beta issue

### ISSUE THREAD

**Issue by DMBlakeley** [dgreif/ring#299]
# Bug Report

### Describe the Bug
 Since release 39 of Homebridge beta I have noticed the following error when Homebridge is initializing:
`[4/15/2020, 8:15:31 AM] One of your plugins incorrectly registered an external accessory using the platform name (Camera-ffmpeg) and not the plugin identifier. Please report this to the developer!`
I believe that this error may be being generated by the Ring plug-in as it is using Camera-ffmpeg to stream video, however, Ring is listed in the Homebridge config.js as a separate platform.

### To Reproduce
 - Start Homebridge beta
 - See error in initial boot of Homebridge

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
```
{
      "refreshToken": "eyJhbGcixxxxx",
       "platform": "Ring"
}
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment
<!-- ✍️edit: -->
 - OS: OSX 10.11.6
 - Node.js: 12.16.2
 - NPM: 6.14.4
 - homebridge-ring: 7.2.2
 - homebridge: 0.4.54-beta.42

**Comment by dgreif** [comment]
@DMBlakeley sorry, doesn't look like this is a `homebridge-ring` issue.  This plugin _does not_ use `camera-ffmpeg` internally.  If you have `camera-ffmpeg` in your homebridge config, I suggest you open an issue there.

**Comment by DMBlakeley** [comment]
@dgreif thanks for the quick response!
