### ISSUE TITLE
Hoobs ring plugin does not allow to get token

### ISSUE THREAD

**Issue by cleanev** [dgreif/ring#301]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 Remove ring plugin
Reboot
Add ring plugin
Error shows token invalid as the configuration already has old token
Trying to run npx -p ring-client-api ring-auth-cli generated error log shown below

### Expected behavior
Expected npx -p ring-client-api ring-auth-cli to allow to get new token to get ring plugin to work

### Screenshots/Logs

[Homebridge] [4/16/2020, 14:51:41] Got SIGINT, shutting down Homebridge...
[Homebridge] [4/16/2020, 14:51:47] Loaded config.json with 0 accessories and 2 platforms.
[Homebridge] [4/16/2020, 14:51:48] Loaded plugin "homebridge-bond".
[Homebridge] [4/16/2020, 14:51:48] Registering platform "homebridge-bond.Bond"
[Homebridge] [4/16/2020, 14:51:49] Loaded plugin "ring".
[Homebridge] [4/16/2020, 14:51:49] Registering platform "homebridge-ring.Ring"
[Homebridge] [4/16/2020, 14:51:49] Loading 2 platforms...
[Homebridge] [4/16/2020, 14:51:49] [Bond] Initializing Bond platform...
[Homebridge] [4/16/2020, 14:51:49] [Ring] Initializing Ring platform...
[Homebridge] [4/16/2020, 14:51:49] Loading 0 accessories...
[Homebridge] [4/16/2020, 14:51:49] Homebridge is running on port 51826.
[Homebridge] (node:1617) UnhandledPromiseRejectionWarning: Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
[Homebridge] at RingRestClient.getGrantData (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:85:15)
[Homebridge] at RingRestClient.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:89:36)
[Homebridge] at Generator.next (<anonymous>)
[Homebridge] at /home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:8:71
[Homebridge] at new Promise (<anonymous>)
[Homebridge] at __awaiter (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:4:12)
[Homebridge] at RingRestClient.getAuth (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:88:16)
[Homebridge] at new RingRestClient (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:65:33)
[Homebridge] at new RingApi (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/api.js:22:27)
[Homebridge] at RingPlatform.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/homebridge/ring-platform.js:129:29)
[Homebridge] at Generator.next (<anonymous>)
[Homebridge] at /home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/homebridge/ring-platform.js:8:71
[Homebridge] at new Promise (<anonymous>)
[Homebridge] at __awaiter (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/homebridge/ring-platform.js:4:12)
[Homebridge] at RingPlatform.connectToApi (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/homebridge/ring-platform.js:128:16)
[Homebridge] at API.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/homebridge/ring-platform.js:115:18)
[Homebridge] at API.emit (events.js:215:7)
[Homebridge] at Server.run (/home/hoobs/.hoobs/lib/bridge/server.js:111:15)
[Homebridge] at module.exports (/home/hoobs/.hoobs/lib/bridge/cli.js:74:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/lib/bridge/bin/homebridge:27:59)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:959:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:815:32)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
[Homebridge] at internal/main/run_main_module.js:17:11
[Homebridge] (node:1617) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[Homebridge] (node:1617) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Homebridge] [4/16/2020, 14:51:49] [Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed with status undefined. Response body: undefined
[Homebridge] [4/16/2020, 14:51:49] [Ring] Error connecting to API
[Homebridge] [4/16/2020, 14:51:49] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:85:15)
    at RingRestClient.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:89:36)
    at Generator.next (<anonymous>)
    at /home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:4:12)
    at RingRestClient.getAuth (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:88:16)
    at new RingRestClient (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/rest-client.js:65:33)
    at new RingApi (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/api.js:22:27)
    at RingPlatform.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/homebridge/ring-platform.js:129:29)
    at Generator.next (<anonymous>)
    at /home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/homebridge/ring-platform.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/homebridge/ring-platform.js:4:12)
    at RingPlatform.connectToApi (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/homebridge/ring-platform.js:128:16)
    at API.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/homebridge/ring-platform.js:115:18)
    at API.emit (events.js:215:7)
    at Server.run (/home/hoobs/.hoobs/lib/bridge/server.js:111:15)
    at module.exports (/home/hoobs/.hoobs/lib/bridge/cli.js:74:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/lib/bridge/bin/homebridge:27:59)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
[Homebridge] (node:1617) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "ID removed",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "orient-red",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "CT",
        "postal_code": "pcode"
    },
    "bridge": {
        "name": "Homebridge",
        "port": 51826,
        "pin": “Nnn-nn-nnn",
        "username": "MACADDRESS"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-bond",
        "ring"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "Bond",
            "plugin_map": {
                "plugin_name": "homebridge-bond"
            },
            "bonds": [
                {
                    "ip_address": "xx.xx.xx.xx",
                    "token": "Sometoken"
                }
            ]
        },
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "ring"
            }
        }
    ],
    "interfaces": [],
    "package_manager": "npm",
    "system": "hoobs"
}

```

### Environment
 - OS: raspbian 4.19.97+
 - Node.js: 12.13.1
 - NPM: 6.13.1
 - homebridge-ring: 7.2.5
 - homebridge: [e.g. 0.4.50]

**Comment by dgreif** [comment]
@cleanev the refresh tokens now only work a single time before the plugin needs a new one.  The plugin will update your config.json automatically, so it shouldn't be something you have to worry about.  If you continue to have issues with it in HOOBS, consider switching to pure homebridge with homebridge-config-ui-x to set up your Ring plugin credentials

**Comment by cleanev** [comment]
Thanks @dgreif. i was able to get the token from a new install and after few back and forth was able to move it to original installation. Homebridge happened to be new to me and 
It looked perfect except I did not see a way to add ring cameras to HomeKit.
Appreciate your guidance

**Comment by BobbySlope** [comment]
Heres how you can install the Ring Plugin on HOOBS
https://plugins.hoobs.org/plugin/homebridge-ring
is an Workaround while we preparing the Update, once the update is released we will certify the newer version and update the readme
