### ISSUE TITLE
Ring plug-in and sudden massive spike in DNS queries for api.ring.com

### ISSUE THREAD

**Issue by halfpress** [dgreif/ring#302]
I'm still working through this to determine more details, but yesterday at about 2 PM EDT (I only mention a time since there is a clear point at which this started - though not related to any actions on my part I can determine), my pi-hole system suddenly shot skyward on logged queries. I only discovered it this morning, but in the course of less than 24 hours, I'm seeing what looks like close to 100,000 queries to api.ring.com. Batches of them every second or few...

At first I assumed perhaps the pi-hole was acting oddly  (I can't rule it out 100%) because the queries were attributed to localhost until I remembered Homebridge and pi-hole are running on the same device (hence localhost attribution). I removed the ring config from Homebridge and restarted the service. The queries stopped. 

Note: these are all permitted queries. The pi-hole is not blocking anything related to Ring that might be causing chaos. Prior to this, the steady patter of ring.com queries is for their snapshots/timelapse feature that I enabled a week or more ago.

Just noting this since the config has been running for days without issue (pi-hole was a recent addition - Homebridge has been up for months). So 100,000+ localhost queries in less than 24 hours stands out rather starkly. :)

I mention it in case there has been a change in behavior, perhaps, at Ring in this regard? This could entirely be a strange edge case of my own, but figured it was worth inquiring and glad to offer any log data. I'll continue mining for answers as well...

**Comment by dgreif** [comment]
See #285 and #230.  The plugin has to poll for certain things, so it generates a lot of requests.  The most likely recent change is the new Modes feature.  If you have cameras and have Modes turned on, then it will now be polling for those modes frequently

**Comment by halfpress** [comment]
Sincere apologies for missing those previous reports. I didn't dig enough before posting, clearly. I do recall the Modes intro spamming me on launch of the app yesterday, but I was in a hurry and batted it away without enabling them (confirmed just now that they are not - so far as I can tell - enabled). I'll follow the other issues and close this one.

**Comment by halfpress** [comment]
Deferring to existing reports - thread was opened prematurely on my part.
