### ISSUE TITLE
Issue with refresh token -  ffmpeg-for-homebridge@0.0.3 

### ISSUE THREAD

**Issue by LIBHUT** [dgreif/ring#303]
# Bug Report

### Describe the Bug
Cannot use 'npx -p ring-client-api ring-auth-cli' for the refresh tokens 2fa support.  Command runs for a while then spits out an error in the console about 
   `Failed at the ffmpeg-for-homebridge@0.0.3 install script.`

### To Reproduce
 - Ran 
`npm i ring-client-api`
to make sure everything was on the latest
- Then ran
`npx -p ring-client-api ring-auth-cli`

### Expected behavior
 expected to see refreshToken in output

### Screenshots/Logs
 
```
Error: Cannot find module '/root/.npm/_npx/5865/lib/node_modules/ring-client-api/node_modules/ffmpeg-for-homebridge/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffmpeg-for-homebridge@0.0.3 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffmpeg-for-homebridge@0.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Additional context
 None.

### Environment

 - OS: debian
 - Node.js: 12.16.2
 - NPM: 6.14.4 
 - ring-client-api: latest

**Comment by LIBHUT** [comment]
OK I stumbled across the solution:  I changed
`npx -p ring-client-api ring-auth-cli`

to

`npx -i ring-client-api ring-auth-cli`

and it worked.

Not sure if what I did was right or not but its working now.  Was it a typo or my install I don't know.

**Comment by dgreif** [comment]
`Failed at the ffmpeg-for-homebridge` is logged if it fails to install, but that does not prevent the package from running as it is an dependency that is expected to fail in certain environments.  `npx -p ring-client-api ring-auth-cli` is the correct command, and I am really not sure what the `-i` argument does with `npx` as it is not in any of their documentation.  Glad you got it working tho!
