### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by croossin** [dgreif/ring#305]
# Bug Report

### Describe the Bug
I am simply just trying to convert the array of locations that are returned from `await ringApi.getLocations();` however, I am received the following error:
```bash
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'SwitchMapSubscriber'
    |     property '_parentOrParents' -> object with constructor 'Subscriber'
    |     property '_subscriptions' -> object with constructor 'Array'
    --- index 0 closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (/Users/croossin/Desktop/Git/roo-app/server/node_modules/express/lib/response.js:1123:12)
    at ServerResponse.json (/Users/croossin/Desktop/Git/roo-app/server/node_modules/express/lib/response.js:260:14)
    at exports.getAllLocations (/Users/croossin/Desktop/Git/roo-app/server/api/v1/ring/controller.js:13:28)
```

### To Reproduce
 - Create an `ApiClient`
 - Attempt to `getAllLocations()` and cast to JSON object
 - See error

### Expected behavior
A simple JSON blob

### Environment

 - OS: MacOS 10.15.1
 - Node.js: 12.13.1
 - NPM: 6.12.1
 - ring-client-api: 7.2.2

**Comment by dgreif** [comment]
That method returns a Promise, which resolves with the locations array

**Comment by croossin** [comment]
You would assume something like the following would work? Instead it is throwing the circular structure error.

```javascript
exports.getAllLocations = async function (req, res) {
  try {
    console.log("fetching locations");

    const locations = await ringApi.getLocations();

    return res.status(200).json({
      locations: locations
    });
  } catch (error) {
    console.log(error);
    return res
      .status(400)
      .json(
        createResponse(
          "ErrorFetchingLocations",
          `Unable to fetch all ring locations: ${error}`
        )
      );
  }
};
```

**Comment by dgreif** [comment]
You may need to delete some properties of the locations to get rid of the circular references. Better yet, just grab the fields you care about and return clean json

**Comment by AntonioM1996** [comment]
Hi, 

Isn't this a bug? How should one be able to parse the locations if it raises this error?
Is there any news?

Thanks

**Comment by tsightler** [comment]
It's only a bug if the error is occurring in the `ringApi.getLocations()` function.  This function does not return simple JSON, but rather a complex object with things like RxJS observables, which will not just convert to a JSON string.  It's in the attempt to do so that the error is happening.

I'm not really sure what the OP was trying to do, but if you just want the JSON string returned by the Ring API then probably it's easier to just call the REST API function directly rather than this higher level function.  Either that, or destructure the returned object to get the properties you want, as was previously suggested.

**Comment by AntonioM1996** [comment]
Thank you for your feedback, I did not find specific documentation about this and thought the locations array to which the promise resolved was a JSON.

Thanks
