### ISSUE TITLE
Constantly ring keeps shutting down my system

### ISSUE THREAD

**Issue by treforparr** [dgreif/ring#306]
Nothing a problem with ring where it keeps disconnecting I can't connect to the serverNothing a problem with ring here the log  

Homebridge] [4/27/2020, 6:55:14 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/11495610-ba8f-4a58-b400-38a8330cce3e.  Trying again in 5 seconds...
[Homebridge] [4/27/2020, 6:55:14 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
[Homebridge] [4/27/2020, 6:56:18 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
[Homebridge] [4/27/2020, 6:58:55 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
[Homebridge] [4/27/2020, 7:00:01 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
[Homebridge] [4/27/2020, 7:00:02 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/11495610-ba8f-4a58-b400-38a8330cce3e.  Trying again in 5 seconds...
[Homebridge] [4/27/2020, 7:01:04 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/11495610-ba8f-4a58-b400-38a8330cce3e.  Trying again in 5 seconds...
[Homebridge] [4/27/2020, 7:07:21 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Trying again in 5 seconds...
[Homebridge] [4/27/2020, 7:07:21 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/11495610-ba8f-4a58-b400-38a8330cce3e.  Trying again in 5 seconds...
[Homebridge] [4/27/2020, 7:08:23 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Trying again in 5 seconds...
[Homebridge] [4/27/2020, 7:08:24 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/11495610-ba8f-4a58-b400-38a8330cce3e.  Trying again in 5 seconds...
[Homebridge] [4/27/2020, 7:09:26 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Trying again in 5 seconds...
[Homebridge] [4/27/2020, 7:09:27 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/11495610-ba8f-4a58-b400-38a8330cce3e.  Trying again in 5 seconds...
[Homebridge] [4/27/2020, 7:10:29 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Trying again in 5 seconds...
[Homebridge] [4/27/2020, 7:10:30 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/11495610-ba8f-4a58-b400-38a8330cce3e.  Trying again in 5 seconds...
[Homebridge] [4/27/2020, 7:11:32 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Trying again in 5 seconds...
[Homebridge] [4/27/2020, 7:11:32 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/11495610-ba8f-4a58-b400-38a8330cce3e.  Trying again in 5 seconds...
[Homebridge] state get
[Homebridge] state get
[Homebridge] state get
[Homebridge] state get
[Homebridge] [4/27/2020, 7:15:41 PM] Got SIGINT, shutting down Homebridge...

**Comment by dgreif** [comment]
@treforparr it looks like homebridge shut down 4 minutes after the last event from ring.  I don't see anything in those logs that indicates homebridge-ring is causing the shutdown.  When it says "Failed to reach Ring server", that means either Ring is having an issue or your internet is having issues.  Do you have other plugins installed?

**Comment by BobbySlope** [comment]
Heres how you can install the Ring Plugin on HOOBS
https://plugins.hoobs.org/plugin/homebridge-ring
is an Workaround while we preparing the Update, once the update is released we will certify the newer version and update the readme
