### ISSUE TITLE
New version of Homebridge causes Ring to crash. 

### ISSUE THREAD

**Issue by dmryglod** [dgreif/ring#310]
# Bug Report

### Describe the Bug

I upgraded to Homebridge 1.0.4. Now it tries to load the ring plugin, but it causes homebridge to shutdown. When I remove the Ring entries from the config.json, no issue. My error log and the config.json are below. 

### To Reproduce
—-

### Expected behavior
—-

### Screenshots/Logs

May 03 15:44:10 DietPi homebridge[1947]: [03/05/2020, 15:44:10] [Config] Homebridge Config UI X v4.17.1 is listening on :: port 8080
May 03 15:44:20 DietPi systemd[1]: homebridge.service: Service RestartSec=10s expired, scheduling restart.
May 03 15:44:20 DietPi systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 13.
May 03 15:44:20 DietPi systemd[1]: Stopped Node.js HomeKit Server.
May 03 15:44:20 DietPi systemd[1]: Started Node.js HomeKit Server.
May 03 15:44:22 DietPi homebridge[2004]: [03/05/2020, 15:44:22] Loaded config.json with 2 accessories and 10 platforms.
May 03 15:44:22 DietPi homebridge[2004]: [03/05/2020, 15:44:22] ---
May 03 15:44:25 DietPi homebridge[2004]: [03/05/2020, 15:44:25] Loaded plugin: homebridge-camera-ffmpeg
May 03 15:44:25 DietPi homebridge[2004]: [03/05/2020, 15:44:25] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
May 03 15:44:25 DietPi homebridge[2004]: [03/05/2020, 15:44:25] ---
May 03 15:44:25 DietPi homebridge[2004]: [03/05/2020, 15:44:25] Loaded plugin: homebridge-config-ui-x
May 03 15:44:25 DietPi homebridge[2004]: [03/05/2020, 15:44:25] Registering platform 'homebridge-config-ui-x.config'
May 03 15:44:25 DietPi homebridge[2004]: [03/05/2020, 15:44:25] ---
May 03 15:44:25 DietPi homebridge[2004]: [03/05/2020, 15:44:25] Loaded plugin: homebridge-dummy
May 03 15:44:25 DietPi homebridge[2004]: [03/05/2020, 15:44:25] Registering accessory 'homebridge-dummy.DummySwitch'
May 03 15:44:25 DietPi homebridge[2004]: [03/05/2020, 15:44:25] ---
May 03 15:44:25 DietPi homebridge[2004]: [03/05/2020, 15:44:25] Loaded plugin: homebridge-ecoplug
May 03 15:44:25 DietPi homebridge[2004]: [03/05/2020, 15:44:25] Registering platform 'homebridge-ecoplug.EcoPlug'
May 03 15:44:25 DietPi homebridge[2004]: [03/05/2020, 15:44:25] ---
May 03 15:44:25 DietPi homebridge[2004]: [03/05/2020, 15:44:25] Loaded plugin: homebridge-magichome-platform
May 03 15:44:25 DietPi homebridge[2004]: [03/05/2020, 15:44:25] Registering platform 'homebridge-magichome-platform.MagicHome-Platform'
May 03 15:44:25 DietPi homebridge[2004]: [03/05/2020, 15:44:25] ---
May 03 15:44:26 DietPi homebridge[2004]: [03/05/2020, 15:44:26] Loaded plugin: homebridge-nest
May 03 15:44:26 DietPi homebridge[2004]: [03/05/2020, 15:44:26] Registering platform 'homebridge-nest.Nest'
May 03 15:44:26 DietPi homebridge[2004]: [03/05/2020, 15:44:26] ---
May 03 15:44:26 DietPi homebridge[2004]: [03/05/2020, 15:44:26] Loaded plugin: homebridge-nuheat
May 03 15:44:26 DietPi homebridge[2004]: [03/05/2020, 15:44:26] Registering platform 'homebridge-nuheat.NuHeat'
May 03 15:44:26 DietPi homebridge[2004]: [03/05/2020, 15:44:26] ---
May 03 15:44:26 DietPi homebridge[2004]: [03/05/2020, 15:44:26] Loaded plugin: homebridge-onkyo
May 03 15:44:26 DietPi homebridge[2004]: [03/05/2020, 15:44:26] Registering platform 'homebridge-onkyo.Onkyo'
May 03 15:44:26 DietPi homebridge[2004]: [03/05/2020, 15:44:26] ---
May 03 15:44:26 DietPi homebridge[2004]: [03/05/2020, 15:44:26] ====================
May 03 15:44:26 DietPi homebridge[2004]: [03/05/2020, 15:44:26] ERROR LOADING PLUGIN homebridge-ring:
May 03 15:44:26 DietPi homebridge[2004]: [03/05/2020, 15:44:26] Error: No valid exports main found for '/usr/local/lib/node_modules/homebridge-ring/node_modules/uuid'
May 03 15:44:26 DietPi homebridge[2004]:  at resolveExportsTarget (internal/modules/cjs/loader.js:611:9)
May 03 15:44:26 DietPi homebridge[2004]:  at applyExports (internal/modules/cjs/loader.js:492:14)
May 03 15:44:26 DietPi homebridge[2004]:  at resolveExports (internal/modules/cjs/loader.js:541:12)
May 03 15:44:26 DietPi homebridge[2004]:  at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
May 03 15:44:26 DietPi homebridge[2004]:  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
May 03 15:44:26 DietPi homebridge[2004]:  at Function.Module._load (internal/modules/cjs/loader.js:847:27)
May 03 15:44:26 DietPi homebridge[2004]:  at Module.require (internal/modules/cjs/loader.js:1016:19)
May 03 15:44:26 DietPi homebridge[2004]:  at require (internal/modules/cjs/helpers.js:69:18)
May 03 15:44:26 DietPi homebridge[2004]:  at Object.&lt;anonymous&gt; (/usr/local/lib/node_modules/homebridge-ring/lib/api/util.js:15:16)
May 03 15:44:26 DietPi homebridge[2004]:  at Module._compile (internal/modules/cjs/loader.js:1121:30)
May 03 15:44:26 DietPi homebridge[2004]: [03/05/2020, 15:44:26] ====================
May 03 15:44:27 DietPi homebridge[2004]: [03/05/2020, 15:44:27] Loaded plugin: homebridge-smartthings-tonesto7
May 03 15:44:27 DietPi homebridge[2004]: Homebridge Version: 2.5
May 03 15:44:27 DietPi homebridge[2004]: [03/05/2020, 15:44:27] Registering platform 'homebridge-smartthings-tonesto7.SmartThings'
May 03 15:44:27 DietPi homebridge[2004]: [03/05/2020, 15:44:27] ---
May 03 15:44:27 DietPi homebridge[2004]: [03/05/2020, 15:44:27] Loaded plugin: homebridge-sonybravia-platform
May 03 15:44:27 DietPi homebridge[2004]: [03/05/2020, 15:44:27] Registering platform 'homebridge-sonybravia-platform.SonyBravia'
May 03 15:44:27 DietPi homebridge[2004]: [03/05/2020, 15:44:27] ---
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] Loaded plugin: homebridge-synology
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] Registering accessory 'homebridge-synology.Synology'
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] ---
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] Loading 10 platforms...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [MagicHome-Platform] Initializing MagicHome-Platform platform...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [MagicHome-Platform] Discovering Devices
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] Initializing platform accessory 'Kitchen LED Strip'...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] Initializing platform accessory 'Basement Cabinet LED'...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [Config] Initializing config platform...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [Config] Spawning homebridge-config-ui-x with PID 2029
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [Nest] Initializing Nest platform...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [Nest] Fetching Nest devices.
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [Camera ffmpeg] Initializing Camera-ffmpeg platform...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [NuHeat] Initializing NuHeat platform...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [NuHeat] Logging into NuHeat...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [EcoPlug] Initializing EcoPlug platform...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [SonyBravia] Initializing SonyBravia platform...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [SonyBravia] Apps not enabled. Skipping discovery.
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [SonyBravia] Channels not enabled. Skipping discovery.
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [SonyBravia] Getting inputs...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [SonyBravia] HDMI inputs found in storage.
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [SonyBravia] CEC detection is enabled.
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [SonyBravia] CEC devices found in storage.
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [SonyBravia] Extra Inputs not enabled. Skipping discovery.
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [SonyBravia] Found 4 HDMI input(s) with 0 CEC device(s), 0 extra input(s), 0 app(s) and 0 channel(s)
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] Initializing platform accessory 'Sony Power'...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] Initializing platform accessory 'Sony HDMI 1'...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] Initializing platform accessory 'Sony HDMI 2'...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] Initializing platform accessory 'Sony HDMI 3/ARC'...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] Initializing platform accessory 'Sony HDMI 4'...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] Initializing platform accessory 'Sony Volume'...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [SmartThings] Initializing SmartThings platform...
May 03 15:44:28 DietPi homebridge[2004]: [03/05/2020, 15:44:28] [SmartThings] Fetching SmartThings devices.
May 03 15:44:29 DietPi homebridge[2004]: [03/05/2020, 15:44:29] [Onkyo] Initializing Onkyo platform...
May 03 15:44:29 DietPi homebridge[2004]: [03/05/2020, 15:44:29] [Onkyo] **************************************************************
May 03 15:44:29 DietPi homebridge[2004]: [03/05/2020, 15:44:29] [Onkyo]  homebridge-onkyo version 0.7.17
May 03 15:44:29 DietPi homebridge[2004]: [03/05/2020, 15:44:29] [Onkyo]  GitHub: https://github.com/ToddGreenfield/homebridge-onkyo
May 03 15:44:29 DietPi homebridge[2004]: [03/05/2020, 15:44:29] [Onkyo] **************************************************************
May 03 15:44:29 DietPi homebridge[2004]: [03/05/2020, 15:44:29] [Onkyo] start success...
May 03 15:44:29 DietPi homebridge[2004]: [03/05/2020, 15:44:29] [Onkyo] Configuration does not contain proper INPUTS configuration.
May 03 15:44:29 DietPi homebridge[2004]: [03/05/2020, 15:44:29] [Onkyo] Continuing without INPUTS filter option.
May 03 15:44:29 DietPi homebridge[2004]: [03/05/2020, 15:44:29] Initializing platform accessory 'Onkyo Stereo'...
May 03 15:44:29 DietPi homebridge[2004]: [03/05/2020, 15:44:29] Error loading platform requested in your config.json at position 10
May 03 15:44:29 DietPi homebridge[2004]: [03/05/2020, 15:44:29] Error: The requested platform 'Ring' was not registered by any plugin.
May 03 15:44:29 DietPi homebridge[2004]:  at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:223:15)
May 03 15:44:29 DietPi homebridge[2004]:  at /usr/local/lib/node_modules/homebridge/src/server.ts:386:37
May 03 15:44:29 DietPi homebridge[2004]:  at Array.forEach (&lt;anonymous&gt;)
May 03 15:44:29 DietPi homebridge[2004]:  at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:373:27)
May 03 15:44:29 DietPi homebridge[2004]:  at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:152:29)
May 03 15:44:29 DietPi homebridge[2004]:  at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
May 03 15:44:29 DietPi homebridge[2004]:  at Object.&lt;anonymous&gt; (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
May 03 15:44:29 DietPi homebridge[2004]:  at Module._compile (internal/modules/cjs/loader.js:1121:30)
May 03 15:44:29 DietPi homebridge[2004]:  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
May 03 15:44:29 DietPi homebridge[2004]:  at Module.load (internal/modules/cjs/loader.js:976:32)
May 03 15:44:29 DietPi homebridge[2004]:  at Function.Module._load (internal/modules/cjs/loader.js:884:14)
May 03 15:44:29 DietPi homebridge[2004]:  at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)
May 03 15:44:29 DietPi homebridge[2004]:  at internal/main/run_main_module.js:17:47
May 03 15:44:29 DietPi homebridge[2004]: [03/05/2020, 15:44:29] [MagicHome-Platform] Getting Bulbs from Cache
May 03 15:44:29 DietPi homebridge[2004]: [03/05/2020, 15:44:29] Got SIGTERM, shutting down Homebridge...
May 03 15:44:29 DietPi homebridge[2004]: [03/05/2020, 15:44:29] [MagicHome-Platform] ** Fetched Lights from Cache **
May 03 15:44:29 DietPi homebridge[2004]: [03/05/2020, 15:44:29] [MagicHome-Platform] {
May 03 15:44:29 DietPi homebridge[2004]:  DC4F22C5F5B6: '10.0.0.165',
May 03 15:44:29 DietPi homebridge[2004]:  '10.0.0.165': '10.0.0.165',
May 03 15:44:29 DietPi homebridge[2004]:  C44F3390FD8A: '10.0.0.137',
May 03 15:44:29 DietPi homebridge[2004]:  '10.0.0.137': '10.0.0.137'
May 03 15:44:29 DietPi homebridge[2004]: }
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] [NuHeat] Logged into NuHeat!
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] [SmartThings] Unknown Capabilities: ["Health Check","Relay Switch","Indicator"]
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'Back Door Lock'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'Fireplace'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'Basement Christmas Tree'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'Basement Dimmer Switch'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'Downstairs Counter Switch'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'Downstairs Hall Switch'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'Front Door Lights'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'Front Yard Christmas Lights'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'Front Yard Christmas Trees'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'Garage Door Lock'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'Garage Door Opener'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'R. Back Door Switch'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'Upstairs Outlet'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'Front Door Lock'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'GE Plug-in Outdoor Switch'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'DS Christmas Tree'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'L. Door Switch'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'Leviton Switch'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] [SmartThings] update_method: direct
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] [SmartThings] Direct Connect Is Listening On 10.0.0.101:8000
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] [NuHeat] Adding NuHeat Device NuHeat 1030113
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] Initializing platform accessory 'NuHeat'...
May 03 15:44:30 DietPi homebridge[2004]: [03/05/2020, 15:44:30] [NuHeat] getServices NuHeat
May 03 15:44:31 DietPi homebridge[2004]: [03/05/2020, 15:44:31] [NuHeat] Change NuHeat { Online: 'True' }
May 03 15:44:31 DietPi homebridge[2004]: [03/05/2020, 15:44:31] [SmartThings] SmartThings Hub Communication Established
May 03 15:44:31 DietPi homebridge[2004]: [03/05/2020, 15:44:31] [MagicHome-Platform] [ 'Polling Light', '10.0.0.137' ]
May 03 15:44:31 DietPi homebridge[2004]: [03/05/2020, 15:44:31] [MagicHome-Platform] /usr/local/lib/node_modules/homebridge-magichome-platform/src/flux_led.py 10.0.0.137 -i
May 03 15:44:31 DietPi homebridge[2004]: [03/05/2020, 15:44:31] [MagicHome-Platform] [ 'Polling Light', '10.0.0.165' ]
May 03 15:44:31 DietPi homebridge[2004]: [03/05/2020, 15:44:31] [MagicHome-Platform] /usr/local/lib/node_modules/homebridge-magichome-platform/src/flux_led.py 10.0.0.165 -i
May 03 15:44:31 DietPi homebridge[2004]: [03/05/2020, 15:44:31] [MagicHome-Platform] Unknown ID [10.0.0.137] OFF [Color: (191, 160, 36)]
May 03 15:44:31 DietPi homebridge[2004]: [03/05/2020, 15:44:31] [MagicHome-Platform] [ 'Updating Device', '10.0.0.137', { H: 48, S: 81, L: 75 }, false ]
May 03 15:44:31 DietPi homebridge[2004]: [03/05/2020, 15:44:31] [MagicHome-Platform] Unknown ID [10.0.0.165] OFF [Color: (128, 107, 24)]
May 03 15:44:31 DietPi homebridge[2004]: [03/05/2020, 15:44:31] [MagicHome-Platform] [ 'Updating Device', '10.0.0.165', { H: 48, S: 81, L: 50 }, false ]
May 03 15:44:32 DietPi homebridge[2004]: [03/05/2020, 15:44:32] [Nest] initing thermostat "Basement Thermostat": deviceId: STUFF structureId: STUFF
May 03 15:44:32 DietPi homebridge[2004]: [03/05/2020, 15:44:32] [Nest] initing thermostat "Hallway Thermostat": deviceId: STUFF structureId: STUFF
May 03 15:44:32 DietPi homebridge[2004]: [03/05/2020, 15:44:32] [Nest] initing home_away_sensor "Home Occupied": deviceId: STUFF structureId: STUFF
May 03 15:44:32 DietPi homebridge[2004]: [03/05/2020, 15:44:32] Initializing platform accessory 'Basement Thermostat'...
May 03 15:44:32 DietPi homebridge[2004]: [03/05/2020, 15:44:32] Initializing platform accessory 'Hallway Thermostat'...
May 03 15:44:32 DietPi homebridge[2004]: [03/05/2020, 15:44:32] Initializing platform accessory 'Home Occupied'...
May 03 15:44:32 DietPi homebridge[2004]: [03/05/2020, 15:44:32] [MagicHome-Platform] 2 bulbs found
May 03 15:44:32 DietPi homebridge[2004]: DC4F22C5F5B6=10.0.0.165
May 03 15:44:32 DietPi homebridge[2004]: C44F3390FD8A=10.0.0.137
May 03 15:44:32 DietPi homebridge[2004]: [03/05/2020, 15:44:32] [MagicHome-Platform] Saving Lights
May 03 15:44:32 DietPi homebridge[2004]: [03/05/2020, 15:44:32] [MagicHome-Platform] {"DC4F22C5F5B6":"10.0.0.165","10.0.0.165":"10.0.0.165","C44F3390FD8A":"10.0.0.137","10.0.0.137":"10.0.0.137"}
May 03 15:44:32 DietPi homebridge[2004]: [03/05/2020, 15:44:32] [MagicHome-Platform] Discovery Finished
May 03 15:44:32 DietPi homebridge[2004]: [03/05/2020, 15:44:32] [MagicHome-Platform] {
May 03 15:44:32 DietPi homebridge[2004]:  STUFF: '10.0.0.165',
May 03 15:44:32 DietPi homebridge[2004]:  '10.0.0.165': '10.0.0.165',
May 03 15:44:32 DietPi homebridge[2004]:  STUFF: '10.0.0.137',
May 03 15:44:32 DietPi homebridge[2004]:  '10.0.0.137': '10.0.0.137'
May 03 15:44:32 DietPi homebridge[2004]: }
May 03 15:44:32 DietPi homebridge[2004]: [03/05/2020, 15:44:32] [MagicHome-Platform] Lights Saved.
May 03 15:44:34 DietPi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
May 03 15:44:34 DietPi systemd[1]: homebridge.service: Failed with result 'exit-code'.

### Additional context
I removed the ring plugin, removed the ring portion from the config.json, reinstalled the plugin and configured. Still the same issue. 

### Homebridge Ring Config
{
"refreshToken": "TOKEN"
"hideDoorbellSwitch": true,
"platform": "Ring"
}

### Environment

 - OS: DietPi
 - Node.js: 13.2.0
 - NPM: 6.14.2
 - homebridge-ring: 8.0.0
 - homebridge: 1.0.4

**Comment by dgreif** [comment]
@dmryglod looks like the main error is `Error: No valid exports main found for '/usr/local/lib/node_modules/homebridge-ring/node_modules/uuid'`.  I'm guessing the `uuid` dependency got into a bad state somehow.  Could you try running `rm -rf /usr/local/lib/node_modules/homebridge-ring` followed by `npm i -g homebridge-ring` to reinstall the plugin?  Let me know if that fixes it

**Comment by dmryglod** [comment]
Unfortunately, I still receive the same error message.

**Comment by dgreif** [comment]
I did a little testing and it looks like the issue is that you are using node 13.  I recommend you update to version 14.1.0 which is the latest LTS version.

**Comment by jeffhummel** [comment]
I am having the same problem. Upgraded node to 14.1.0 and still get ERROR LOADING PLUGIN homebridge-ring:
[5/5/2020, 11:17:15 AM] Error: Package exports for '/usr/local/lib/node_modules/homebridge-ring/node_modules/uuid' do not define a '.' subpath

**Comment by dgreif** [comment]
@jeffhummel try uninstalling and reinstalling `homebridge-ring`.  I tried it on node 14.1.0 and it started up just fine

**Comment by jeffhummel** [comment]
uninstalled and re-installed, started homebridge and getting the same error in the logs. This is a fresh install of homebridge.  If I remove Ring it works fine.

**Comment by dgreif** [comment]
Apparently node 14 is _not_ LTS yet.  Can you try node 12.16.3?

**Comment by danewallace** [comment]
I was experiencing the same issue using node 13. Uninstalling node and reinstalling v 14.1.0 resolved the issue. Hope this helps.

**Comment by jeffhummel** [comment]
must be something else. Uninstalled node and npm and installed 12.16.3 then reinstalled homebridge-ring. same error. uninstalled everything and went to 14.1.0 again and same issue. Going to try and re-install 7.2.2 of ring package to see if that will still work.

**Comment by jeffhummel** [comment]
Let me know if you need me to try anything else. Running 7.2.2 works. Updating to 8.0.0 crashes with the same error every time. Whether I am on 14.1.0 of node, or 12.16.3. Updated to NPM 6.14.5 to see if that had any change, and it didn't. Thanks.

**Comment by dgreif** [comment]
@jeffhummel thanks for trying all those versions.  I'm wondering if one of your other plugins is messing with the underlying hap-node module.  Can you try running homebridge-ring 8.0.0 without any of the other plugins?  If that works, re-introduce each of your other plugins until you find the one that causes ring to error

**Comment by jeffhummel** [comment]
same error with a fresh install of everything.  If it helps I am on a mac running catalina 10.15.4.  Did a new install of node and npm.  Removed and reinstalled homebridge with no plugins.  Ring does not work.

**Comment by donavanbecker** [comment]
@jeffhummel I am running homebridge on my mac that is running Catalina and have no issues. you will have to give more details on your setup to better understand whats going on. Node Version, npm version, homebridge version, etc.

**Comment by jeffhummel** [comment]
Node version 14.1.0, NPM version 6.14.5, Homebridge 1.0.4, Ring plugin 7.2.2 works, but 8.0.0 does not.  The error I get is: ERROR LOADING PLUGIN homebridge-ring:
[5/5/2020, 11:17:15 AM] Error: Package exports for '/usr/local/lib/node_modules/homebridge-ring/node_modules/uuid' do not define a '.' subpath

**Comment by Lui5Jacint0** [comment]
`05/05/2020, 17:34:22 [Ring] Snapshot for Front Door is still within its life time (380.978s old)
05/05/2020, 17:34:22 [Ring] Snapshot for Front Door Received (0.001s)
05/05/2020, 17:34:28 [Ring] Preparing Live Stream for Front Door
05/05/2020, 17:34:30 [Ring] Waiting for stream data from Front Door (2.559s)
05/05/2020, 17:34:38 [Ring] Stopped Live Stream for Front Door`

My router is Technicolor TG789vac v2.

![Captura de ecrã 2020-05-07, às 22 26 20](https://user-images.githubusercontent.com/930892/81351723-81896680-90b4-11ea-99e7-e6a17c4d6ff1.png)
![Captura de ecrã 2020-05-07, às 22 26 30](https://user-images.githubusercontent.com/930892/81351725-82ba9380-90b4-11ea-9b03-6956cce4cb26.png)

Any ideia how can i configure hoobs for live stream?

**Comment by dgreif** [comment]
@Lui5Jacint0 You can read through https://github.com/dgreif/ring/wiki/Camera-Troubleshooting#live-stream-troubleshooting for help with live streaming issues.  This issue that you posted on has nothing to do with live streaming, so I am hiding your comment.  Please to do not respond in this thread.

**Comment by matth3w** [comment]
I’m having the same issue. I have tried in multiple versions of npm and node with no avail. Everything just keeps crashing and homebridge doesn’t boot. It specifically says this in the global log: Got SIGTERM, shutting down homebridge.  Currently I am using npm 6.14.4, node 14.2.0, homebridge 1.0.4 and homebridge-ring 8.0.1. Remove ring setup and homebridge boots just fine. This is running in a raspberry pi, with an up-to-date version raspbian buster (10).

**Comment by dgreif** [comment]
@matth3w `Got SIGTERM, shutting down homebridge` is not specific to `homebridge-ring` and does not indicate that this plugin is causing the `SIGTERM`. 

The original problems in this issue were all environmental.  If you are seeing an error like `No valid exports` or `Package exports ...` then it is likely due to your node version or a weird set of installed dependencies in your `node_modules` folder.  These are not issues that I can fix from the plugin and need to be solved on your end as I am not able to reproduce them.  I really wish I could solve every one of these issues, but unfortunately I can't get into your environment and debug every issue that pops up.  I think one of the best solutions is to post on Redit, where other users may have faced the same issue and have some idea of how they cleaned up their environment to fix it.
