### ISSUE TITLE
Hide specific cameras

### ISSUE THREAD

**Issue by ifeign** [dgreif/ring#312]
# Bug Report

### Describe the Bug
 Now that cameras are bridged I can’t hide ones that I don’t use. My office doorbell is shared with me via my coworker’s account, but I don’t want it to show up in my house. Previously I just wouldn’t add the accessory but now I don’t have a choice. 

### To Reproduce
 - Use the latest Ring plugin

### Expected behavior
The ability to hide a camera via the config either by specific camera or the ability to disable shared cameras that aren’t from the primary account.

**Comment by donavanbecker** [comment]
you have the option of `locationId`, you will have to set that to your house location.

**Comment by ifeign** [comment]
Ah, I wasn’t aware of that. Problem solved. Great work as usual.

**Comment by dgreif** [comment]
@ifeign the location ids are printed to your homebridge logs when the plugin starts up.  Should say something like `Configuring X cameras and X devices for location "LOCATION NAME" - locationId: THIS-IS-LOCATION-ID`
