### ISSUE TITLE
Looking for an option to support cameras as separate accessories

### ISSUE THREAD

**Issue by mangvlad** [dgreif/ring#313]
# Feature Request
Need an option to allow for cameras to continue to be separate accessories
### Description

Using homebridge with home-assistant and ha has no support for cameras.
Version 7.2.2 works great since you can add cameras directly to Home App but all other devices are coming from home-assistant instead.

### Describe the solution you'd like

It would be nice to allow this optional feature to provide configuration option during installation to support "legacy" behavior

**Comment by dgreif** [comment]
@mangvlad unfortunately the "legacy" behavior is not something that I want to support long term.  The homebridge project has made great strides lately, and I want to keep this plugin using the latest and greatest approach that homebridge has to offer.  If you are set on keeping external cameras, then you are welcome to continue using version 7.2.2 indefinitely.  It should continue to work as long as Ring does not introduce any breaking changes to their API (which they have been known to do).  The other option would be to switch away from Home Assistant for all of your Ring devices, especially given that homebridge-ring is specifically built to support HomeKit and covers the full range of Ring products.  I hope you are able to find a configuration that meets your needs!
