### ISSUE TITLE
DNS question

### ISSUE THREAD

**Issue by MSlawik** [dgreif/ring#314]
First Thank you for the great plugin you developed.

Is there a possibility to change the DNS server the Ring plugin is using, so instead of jamming the pihole query log, to just have it pointing directly to my router?

thanks

**Comment by dgreif** [comment]
Unfortunately it doesn't look like the library I currently use for HTTP requests supports any type of DNS configuration.  I'm considering switching to `got`, which has built-in DNS caching, which would probably help pihole users quite a bit.  No promises on when I'll have time to make the switch
