### ISSUE TITLE
Please add support for device type sensor.water 

### ISSUE THREAD

**Issue by rajaram-s** [dgreif/ring#316]
# Feature Request

### Description

First of all, thank you so much for creating this plugin and actively developing it. 

Ring supports third party zwave devices to be added to the Ring platform. I have few Fibaro Flood Sensors added to Ring and am able to get notifications when leaks are detected. In the Ring app, there is a temperature sensor and water sensor created for each of the Fibaro flood sensors.  

![fr_985](https://user-images.githubusercontent.com/2541810/81489930-61d77700-9249-11ea-81d1-f2994aec0c44.jpg)

The homebridge-ring plugin only includes the temperature sensor in HomeKit and hides the water sensor. In the homebridge logs. the message "[Ring] Hidden accessory sensor.water <Sensor Name>" is displayed.

### Describe the solution you'd like
Please add support for the device type "sensor.water". I assume this would be similar to the flood-freeze sensor.

### Describe alternatives you've considered
I was originally using the Fibaro Flood Sensor with Samsung Smartthings and was using the smartthings-homebridge plugin to bring them to Homekit. Since Ring supports the third party water sensors, it would be great to add support for that in the homebridge plugin as well.

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instuctions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dgreif** [comment]
I would be happy to add the water sensor. Should be very easy, probably identical to the flood sensor. Would you mind following the instructions in the device data section above, running the data discovery tool. If you are able to post that data, I can add this feature with high confidence that it will work with your sensor

**Comment by rajaram-s** [comment]
Thank you so much. I very much appreciate the quick response.
Regarding the device data, would it be okay if I just share the device information for the Fibaro Flood Sensor (added below)? 
After reviewing the complete prettified JSON from the data discovery tool, I am concerned that the posting the complete data in public would make it easy to identify all the sensor types and where they are located. Please let me know if the device data for the Fibaro Flood sensor posted below is sufficient for adding support or if you would need any other data from the tool. If so, I'll try to anonymize any PII from before posting.

`{"adapterType":"zwave","batteryLevel":56,"batteryStatus":"ok","categoryId":5,"commStatus":"ok","commandTypes":{"communication-poll":{"requiresTrust":false},"reconfigure.start":{"requiresTrust":false},"update-node-neighbors.start":{"requiresTrust":false}},"componentDevices":[{"rel":"2:sensor.temperature","zid":"0bcc1a6a-eb72-uuid"}],"deviceFoundTime":1589066977154,"deviceType":"sensor.water","impulseTypes":{"clear":{"trusted":false},"fault":{"trusted":false},"tampered":{"trusted":false},"tampered-cleared":{"trusted":false}},"lastCommTime":1589067110945,"lastUpdate":1589067111008,"managerId":"zwave","manufacturerName":"Fibaro","name":"Laundry Room Water","nextExpectedWakeup":1589110177746,"pollInterval":43200,"roomId":14,"setupByPluginStatus":"complete","setupByUserStatus":"complete","subCategoryId":0,"tags":["sleepy"],"tamperStatus":"ok","zid":"fb43fa21-d308-uuid","faulted":false},{"adapterType":"zwave","batteryLevel":56,"batteryStatus":"ok","categoryId":5,"commStatus":"ok","deviceFoundTime":1589066977620,"deviceType":"sensor.temperature","impulseTypes":{"clear":{"trusted":false},"fault.high":{"trusted":false},"fault.low":{"trusted":false}},"lastCommTime":1589066977220,"lastUpdate":1589066979675,"managerId":"zwave","name":"Laundry Room Temperature","parentZid":"fb43fa21-d308-uuid","pollInterval":0,"relToParentZid":"2:sensor.temperature","roomId":14,"rootDevice":"fb43fa21-d308-uuid","setupByPluginStatus":"complete","setupByUserStatus":"complete","subCategoryId":0,"tags":["sleepy"],"tamperStatus":"ok","zid":"0bcc1a6a-eb72-uuid","celsius":22.3,"faultHigh":32.22,"faultLow":7.22,"faulted":false}`

**Comment by dgreif** [comment]
That’s exactly what I needed from the data, no need to post anything else. Thanks for getting that! Looks just like the flood sensor so I should be able to get an update out for it tomorrow

**Comment by rajaram-s** [comment]
> That’s exactly what I needed from the data, no need to post anything else. Thanks for getting that! Looks just like the flood sensor so I should be able to get an update out for it tomorrow

Thank you! You are awesome 👍

**Comment by dgreif** [comment]
@rajaram-s water sensor is released in version `8.1.0`.  Would you mind confirming that it works and accurately displays if water is detected in HomeKit?  

I also have not had anyone confirm that the temperature sensor works properly.  Could you check that one out as well?

**Comment by rajaram-s** [comment]
@dgreif Thanks for adding support for the water sensor. 
I updated the plugin to the latest version and the water and temperature sensors are now showing up in HomeKit. I also tested the sensor and got the expected water detected notification from HomeKit.

**Comment by dgreif** [comment]
Perfect, thanks @rajaram-s! Glad to hear it’s working. I appreciate the initial data and final testing!
