### ISSUE TITLE
Can't acess live stream

### ISSUE THREAD

**Issue by Lui5Jacint0** [dgreif/ring#317]
# Live Streaming Issue

### Describe the live streaming issue
I can't acess live stream on ring.

### Screenshots/Logs
11/05/2020, 14:19:36 [Ring] Preparing Live Stream for Front Door
11/05/2020, 14:19:39 [Ring] Snapshot for Front Door Requested
11/05/2020, 14:19:39 [Ring] Snapshot for Front Door is still within its life time (545.754s old)
11/05/2020, 14:19:39 [Ring] Snapshot for Front Door Received (0.001s)
11/05/2020, 14:19:41 [Ring] Waiting for stream data from Front Door (4.751s)
11/05/2020, 14:19:47 [Ring] Stopped Live Stream for Front Door

### Recommended solution
 Please describe what you think is causing this issue, and how you recommend it be fixed

### Environment

 - Ring Camera: Videodorbell 2
 - OS:  HOOBS 3
 - Node.js: 12.14.1
 - NPM: 6.13.4
 - homebridge-ring (if applicable): 7.2.2
 - homebridge (if applicable): [e.g. 0.4.50]

### Network Environment
My router is Technicolor TG789vac v2, i have an ipad air 2 as my home hub, and a ring videodoorbell 2
![Captura de ecrã 2020-05-11, às 14 28 14](https://user-images.githubusercontent.com/930892/81573332-da4a4f00-9393-11ea-86a9-1dd4c1dba29c.png)
![Captura de ecrã 2020-05-07, às 22 26 20](https://user-images.githubusercontent.com/930892/81573348-e1715d00-9393-11ea-9e10-b8ff1772a58a.png)
![Captura de ecrã 2020-05-07, às 22 26 30](https://user-images.githubusercontent.com/930892/81573350-e2a28a00-9393-11ea-8852-f8109272eb26.png)

**Comment by dgreif** [comment]
Unfortunately if UPnP doesn't work, then there is nothing that I can do.  There are a lot of users that have the Eero router which has live streaming issues as well, but I have been unable to solve them.  Hopefully I can some day come up with a better hole-punch solution that works in all environments, but for now I don't have one.  If you find something that works, PRs are welcome.

**Comment by Lui5Jacint0** [comment]
I don’t know what magic you have done, but in version 9.0.0 it works in my setup. I can’t thank you enough!

**Comment by dgreif** [comment]
I finally figured out how Ring was making it work in any network and was able to replicate their approach. Glad to hear it’s working now!
