### ISSUE TITLE
cannot enable ring alarm

### ISSUE THREAD

**Issue by wga22** [dgreif/ring#319]
# Bug Report

### Describe the Bug
 Though the node.js application runs, the alarm is not actually enabled

### To Reproduce
1) OATH authenticate
2) write code using location.armHome()
		const house = locations[0];
		console.log("loc len:" + locations.length)
		house.armHome();

### Expected behavior
Alarm is enabled.

### Screenshots/Logs
Program output:
loc len:1

Location Vienna has the following
all done!

### Additional context
Here is the code being used (no errors) but alarm is not actually enabled:
https://github.com/wga22/nodejs/blob/master/ring/ring.js

### Environment

 - OS: windows (tested on Ubuntu 18.04.4 LTS)
 - Node.js: v12.16.1
 - NPM:6.14.4
 - ring-client-api: latest (refreshed via NPM on May 12)

**Comment by dgreif** [comment]
You need to await the arm home call

**Comment by calebboyd** [comment]
Node 8 Is unsupported
https://github.com/dgreif/ring/blob/a07bb022bd60a28c626f2b081d366fa80cf41172/package.json#L94-L96

**Comment by wga22** [comment]
I have moved to Node 12.16.1 and added await.  Same results (no arming or errors).

**Comment by dgreif** [comment]
I'm sorry but that isn't much to go on.  I know that the method works, so the issue is somewhere in your code.  If you update your example, I can take a look at the changes

**Comment by wga22** [comment]
> I'm sorry but that isn't much to go on. I know that the method works, so the issue is somewhere in your code. If you update your example, I can take a look at the changes

Appreciate the help!  Would you have sample code I might look at with it working?  Or a snippet you could share?  Maybe something wrong with my libraries, or something I can do to debug further?

I updated my code with await.  
I've also tried on my linux machine with same results.  Maybe I have wrong version of the hardware?

**Comment by dgreif** [comment]
Your current code is calling `testDevices`, which does not have an `await`.  `turnOnAlarm`, which does have an `await`, is commented out.

**Comment by wga22** [comment]
Thank you.  Feeling dumb about now.  I added "await" to the wrong function.
