### ISSUE TITLE
"hideInHomeDoorbellSwitch": "false" doesn't appear to do anything?

### ISSUE THREAD

**Issue by iainelliott** [dgreif/ring#323]
Trying to expose a switch that i can automate to turn off my in home doorbell at night to avoid waking up Junior. Am i looking in the wrong place? Is this the right thing to use? I'm using a Video Doorbell 3.

Thanks

Iain

**Comment by dgreif** [comment]
That’s the right option. “false” is a string that evaluates to a truthy value and acts like you passed in true. Either remove the quotes around false, or you can completely remove that line from your config. Either way, that switch should be what you are looking for. It will appears as an accessory within that camera in the home app

**Comment by iainelliott** [comment]
Thank you, that sorted it. Now i can see the switch. It appears to keep defaulting back to ON after a few minutes, is that expected? Is there something i need to do to make the change in state stick?

i.

**Comment by dgreif** [comment]
I did a lot of testing with the in-home doorbell switch and am confident that it is working perfectly in v9
