### ISSUE TITLE
Out Door Flood Light and Spotlight Cam Video Judder

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#324]
Hi @dgreif I meant to mention this before, all my ring devices work perfectly in ring app and your homebridge app, but the outdoor cams mentioned above both judder in you app and not in the ring app, it's literally a "Stop" moment in the video for about 1 second every 3 to 4 seconds... any ideas? it's not wifi related and works clearly in ring app.

Thanks

**Comment by dgreif** [comment]
I'd think through your network setup for the whole journey from your camera to your phone.  If you are using the Ring App, it looks like this:

Camera -> Router -> Ring Servers -> Router -> Phone

Whereas with homebridge it looks like this when you are on your home network:

Camera -> Router -> Ring Servers -> Router -> Homebridge Server -> Router -> Home Hub -> Router -> Phone

Sometimes the Home Hub is skipped, but the idea is the same.  Every one of those `->`s is a connection over wifi, ethernet, or the internet, so any one of them could be causing your Judder.  In the homebridge setup, there are a lot more hops to think through to get it right.  Let me know if that helps

**Comment by adavison007** [comment]
@dgreif Thanks for the above info, I've run a speed test on all the areas where the cameras are and I get > 350Mpbs everywhere, so don't think it's bandwidth on internet, the network is 1gb ethernet via manned switches everywhere... It seems it's just the outdoor cams only, these have the best signal as I have outdoor wifi.

I guess not a lot I can do?

**Comment by dgreif** [comment]
@adavison007 unfortunately no.  For video in particular, the plugin doesn't even touch the packets.  It just passes what it gets from Ring directly along to Homebridge without any transcoding or anything.  Has it always had the judder or just after 8.0 update?

**Comment by adavison007** [comment]
It's had it on both the previous version and the new version.

I might try a complete system reboot and see what happens.

Adam Davison
adavison@me.com
01276 63145
07748 761448

On 18 May 2020 at 17:53, Dusty Greif <notifications@github.com> wrote:


@adavison007 unfortunately no. For video in particular, the plugin doesn't even touch the packets. It just passes what it gets from Ring directly along to Homebridge without any transcoding or anything. Has it always had the judder or just after 8.0 update?

**Comment by JazzerAlto** [comment]
I am seeing the exact same with the floodlight cams. I’ve got through my whole network and upgraded to a RPI 4 which is hardwired to GigE. I never see this happen streaming in the Ring app and I’ve upgraded all my home network and can not find anything in my setup that I can point to as the cause.

**Comment by JazzerAlto** [comment]
And yes, my judder has been there since before 8.x for me. It’s never changed.

**Comment by dgreif** [comment]
I spent some more time diving into the streaming setup and I think it's as good as I can possibly get it right now.  The plugin currently passes data directly from Ring to HomeKit, and facilitates communication between the two to determine proper bitrate.  My video doesn't stream perfectly either, but I really don't think there is anything else I can do at this point.

**Comment by adavison007** [comment]
> I spent some more time diving into the streaming setup and I think it's as good as I can possibly get it right now. The plugin currently passes data directly from Ring to HomeKit, and facilitates communication between the two to determine proper bitrate. My video doesn't stream perfectly either, but I really don't think there is anything else I can do at this point.

@dgreif Many thanks for looking into this and the communication back, I agree I think this is great considering its so complex, what you have delivered is more than good enough, I appreciate the support.
