### ISSUE TITLE
Motion Sensor shows as no response

### ISSUE THREAD

**Issue by Crox77** [dgreif/ring#328]
Hi Upgraded to V8 today and got the two way audio working great, however my motion sensor for the door bell now shows a No Response!

Any Ideas please?
Thanks

# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50]

**Comment by dgreif** [comment]
Try rebooting your homebridge server and your Home Hub (apple tv, home pod)

**Comment by Crox77** [comment]
His I’ve done that and now the hole lot as gone from the home app

**Comment by Crox77** [comment]
Ok I’ve got it all working, oddly though my hardwired doorbell does not ring anymore when the button is pressed on the ring

**Comment by dgreif** [comment]
That's a setting in the ring app.  Also exposed as a switch in HomeKit that you may have pressed by accident.  glad you got it working!

**Comment by Crox77** [comment]
ok so how do I change the setting so the door bell rings? do I need to leave the switch ON in Home app?

**Comment by dgreif** [comment]
The "In-Home Doorbell" button should be on.  There is a setting in the Ring app as well if you go to the cameras settings -> Device Settings -> General Settings -> Doorbell Chime Type -> Ring my in-home doorbell

**Comment by Crox77** [comment]
don't seem to have that option in the ring app just a volume slider?

**Comment by dgreif** [comment]
If you don't see the "Internal Doorbell Settings" section in the General Settings, then something got messed up with your Ring camera.  Shouldn't be related to homebridge-ring in any way

**Comment by Crox77** [comment]
What ever was going on, its all working fine now, odd! but that you very much for your help, much appreciated

**Comment by Crox77** [comment]
Hi again, I’ve woken up this morning checked my home app, and the Camera has completely disappeared again!!! Any clue as to why? 
Before the update I never had any issues
