### ISSUE TITLE
Two-way audio input latency

### ISSUE THREAD

**Issue by tronny87** [dgreif/ring#329]
Two-way audio seems to have an issue with sound input as the audio session starts off great, but as time goes on during the session, the input from the device mic takes longer and longer to come out from the Doorbell. On the other hand, input from the Doorbell is very quick to play on the video stream on the device. It seems to be isolated to the input from the device only. 

Perhaps an issue with audio bitrate is causing the drift/latency?

Tested on iOS 13.5 on both iPhone and iPad.

**Comment by dgreif** [comment]
@tronny87 sorry for not replying earlier, but I can confirm that this was a bug introduced along side 2-way audio.  I have a fix in `8.3.0-alpha.2` if you want to try it out

**Comment by dgreif** [comment]
This is fixed in v`9.0.0`
