### ISSUE TITLE
Ring API and Asterisk PBX

### ISSUE THREAD

**Issue by jbittner1002** [dgreif/ring#333]
Anyone ever get Ring to talk to Asterisk. We have a custom script that pulls the data out of the API.
Creates a PJSIP.conf file in realtime and when we try to make a call we keep getting back 480 status.
Asterisk and API are running on the same box so the source ip does not change.
I am not running homebridge on my test box, only node with API. Anyone has any ideas ?
Any way I can capture a sip trace of homebridge ?  I have it running on another box with ring and it works perfect.

Any helps is very much appreciated.

John

This is copy of my pjsip settings. 

[ring01]
type=aor
contact=sip:3.233.91.166:15064

[ring01]
type = endpoint
transport=transport-tls
ice_support = yes
allow=!all,ulaw,alaw,h264
aors=ring01
media_encryption=sdes
from_user=109146114
from_domain=ring.com
outbound_proxy=sip:3.233.91.166:15064
direct_media=no
direct_media_method=invite
dtmf_mode=info
use_avpf=yes

**Comment by dgreif** [comment]
Just had someone else reach out Scott 480s. You need to set the user agent to a value that Ring has Whitelisted. See https://github.com/dgreif/ring/blob/d1cf0a5d3eae4d506d7aea839b4bb73140a042a0/api/sip-call.ts#L199

**Comment by jbittner1002** [comment]
I tested that and it do not fix my issue.
This is a trace of what I am getting.

INVITE sip:3.233.105.55:15064 SIP/2.0
Via: SIP/2.0/TLS 192.168.1.154:5061;rport;branch=z9hG4bKPjf6110200-72e0-4462-9f99-d3534a8bf82a;alias
From: <sip:109643183@ring.com>;tag=42e4a9cb-59af-4d40-a21f-00261afbd3be
To: <sip:3.233.105.55>
Contact: <sip:109643183@192.168.1.154:5061;transport=TLS>
Call-ID: 0d289bb0-30aa-4764-a25b-2efce21d6fb9
CSeq: 21617 INVITE
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Supported: 100rel, timer, replaces, norefersub
Session-Expires: 1800
Min-SE: 90
Route: <sip:3.233.105.55:15064>
Max-Forwards: 70
User-Agent: Android/3.15.3 (belle-sip/1.4.2)
Content-Type: application/sdp
Content-Length:  1320

v=0
o=- 1759867940 1759867940 IN IP4 192.168.1.154
s=Talk
c=IN IP4 192.168.1.154
t=0 0
m=audio 18976 RTP/SAVPF 0
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:7aAoeKmlyqukPkG0ktQSLwZeQG1Voa6cyA4ESo7e
a=ice-ufrag:0a5bfe930f6e97fe0ca0bca71e7710ae
a=ice-pwd:43e30efe1a84888e53f8f0501b65b7cc
a=candidate:Hc0a8019a 1 UDP 2130706431 192.168.1.154 18976 typ host
a=candidate:S47bb4620 1 UDP 1694498815 71.187.70.32 18976 typ srflx raddr 192.168.1.154 rport 18976
a=candidate:Hc0a8019a 2 UDP 2130706430 192.168.1.154 18977 typ host
a=candidate:S47bb4620 2 UDP 1694498814 71.187.70.32 18977 typ srflx raddr 192.168.1.154 rport 18977
a=rtpmap:0 PCMU/8000
a=ptime:20
a=maxptime:150
a=sendrecv
m=video 19466 RTP/SAVPF 99
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:W7OFHN/VXdu6nLfKRrC5i/1n9CbJuNrme2r64VhY
a=ice-ufrag:25e36db553db35f3534f0fa64b9fbb5a
a=ice-pwd:606f2d0e4056aa5b3559b3471eac3061
a=candidate:Hc0a8019a 1 UDP 2130706431 192.168.1.154 19466 typ host
a=candidate:S47bb4620 1 UDP 1694498815 71.187.70.32 19466 typ srflx raddr 192.168.1.154 rport 19466
a=candidate:Hc0a8019a 2 UDP 2130706430 192.168.1.154 19467 typ host
a=candidate:S47bb4620 2 UDP 1694498814 71.187.70.32 19467 typ srflx raddr 192.168.1.154 rport 19467
a=rtpmap:99 H264/90000
a=fmtp:99 max-br=2000;profile-level-id=42801F
a=sendrecv

<--- Received SIP response (392 bytes) from TLS:3.233.105.55:15064 --->
SIP/2.0 100 Trying
Via: SIP/2.0/TLS 192.168.1.154:5061;rport=45311;branch=z9hG4bKPjf6110200-72e0-4462-9f99-d3534a8bf82a;alias;received=71.187.70.32
From: <sip:109643183@ring.com>;tag=42e4a9cb-59af-4d40-a21f-00261afbd3be
To: <sip:3.233.105.55>
Call-ID: 0d289bb0-30aa-4764-a25b-2efce21d6fb9
CSeq: 21617 INVITE
User-Agent: Hi Zero Cool. Job?'); DROP TABLE servers;--
Content-Length: 0


<--- Received SIP response (757 bytes) from TLS:3.233.105.55:15064 --->
SIP/2.0 480 Temporarily Unavailable
Via: SIP/2.0/TLS 192.168.1.154:5061;rport=45311;branch=z9hG4bKPjf6110200-72e0-4462-9f99-d3534a8bf82a;alias;received=71.187.70.32
Max-Forwards: 70
From: <sip:109643183@ring.com>;tag=42e4a9cb-59af-4d40-a21f-00261afbd3be
To: <sip:3.233.105.55>;tag=85KXv64194UeD
Call-ID: 0d289bb0-30aa-4764-a25b-2efce21d6fb9
CSeq: 21617 INVITE
User-Agent: Hi Zero Cool. Job?'); DROP TABLE servers;--
Accept: application/sdp
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, NOTIFY
Supported: path, replaces
Allow-Events: talk, hold, conference, refer
Reason: Q.850;cause=16;text="NORMAL_CLEARING"
Content-Length: 0
Remote-Party-ID: "109643183" <sip:109643183@3.233.105.55>;party=calling;privacy=off;screen=no

I am pulling my hair out.. I will pay to help get this fixed.
John

**Comment by dgreif** [comment]
The other thing to keep in mind if User-Agent doesn't fix your 480s is that the sip credentials you receive from Ring are only good for a one-time use, and need to be used within about 10 seconds of when you receive them.  After that point, you need to request a new ding and get new credentials if you are not already connected

**Comment by jbittner1002** [comment]
We have tested both door button push and live view triggers with calls into ring within the 10 seconds.
What about the invite above, does that look correct ? Am I missing something ?

**Comment by jbittner1002** [comment]
What field are coming in from ring are required in the sip invite ? I think I got them all but does it need the session id or ding id anywhere ?

**Comment by jbittner1002** [comment]
here event Motion detected
Motion detected on Front Door camera. Ding id 6831622135464516686. Received at Wed May 27 2020 16:25:33 GMT-0400 (Eastern Daylight Time). "here server ip:"3.233.102.12. "here server port:"15063. "here sip token:". "here sip session id:"5tjmc4c00tn2e-20424772dnu22m-1s02. "here sip ding id:"6831622135464516686. "here sip to:"15064. "here sip from:"sip:109648087@ring.com. "here snapshort:" . "here device kind:" lpd_v1. "here kind:" motion. "here endpoints:" null. "here id str:" 6831622135464516686. "here state:" ringing. "here protocol:" sip. "here doorbot_description:" Front Door. "here device_kind:" lpd_v1. "here motion:" true. "here sip token:" . "here sip ding id:" 6831622135464516686
here ringcount 01

**Comment by jbittner1002** [comment]
Sorry but last question, any way to get a sip trace out of homebridge so I can compare.
Thanks for your help.
John

**Comment by dgreif** [comment]
You do not need to include the dingId anywhere, even though Ring does include it in their invite headers from the app.  Here is an example of the invite from my api:

```
INVITE sip:5tjmdqc085r2o-206709t1a3rapq-1s03@34.223.29.102:15064;transport=tls SIP/2.0
To: "FS Doorbot" <sip:5tjmdqc085r2o-206709t1a3rapq-1s03@34.223.29.102:15064;transport=tls>
From:  <sip:e04e43a1ed59@ring.com>;tag=486845
Max-Forwards: 70
Call-ID: 702145
User-Agent: Android/3.15.3 (belle-sip/1.4.2)
CSeq: 20 INVITE
Supported: replaces, outbound
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Content-Type: application/sdp
Contact:  <sip:e04e43a1ed59@ring.com>
Via: SIP/2.0/TLS 192.168.1.123:5061;branch=z9hG4bK258423
Content-Length: 467
```

**Comment by jbittner1002** [comment]
What about the other parts like 
v=0
o=- 1759867940 1759867940 IN IP4 192.168.1.154
s=Talk
c=IN IP4 192.168.1.154
t=0 0
m=audio 18976 RTP/SAVPF 0
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:7aAoeKmlyqukPkG0ktQSLwZeQG1Voa6cyA4ESo7e
a=ice-ufrag:0a5bfe930f6e97fe0ca0bca71e7710ae
a=ice-pwd:43e30efe1a84888e53f8f0501b65b7cc
a=candidate:Hc0a8019a 1 UDP 2130706431 192.168.1.154 18976 typ host
a=candidate:S47bb4620 1 UDP 1694498815 71.187.70.32 18976 typ srflx raddr 192.168.1.154 rport 18976
a=candidate:Hc0a8019a 2 UDP 2130706430 192.168.1.154 18977 typ host
a=candidate:S47bb4620 2 UDP 1694498814 71.187.70.32 18977 typ srflx raddr 192.168.1.154 rport 18977
a=rtpmap:0 PCMU/8000
a=ptime:20
a=maxptime:150
a=sendrecv
m=video 19466 RTP/SAVPF 99
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:W7OFHN/VXdu6nLfKRrC5i/1n9CbJuNrme2r64VhY
a=ice-ufrag:25e36db553db35f3534f0fa64b9fbb5a
a=ice-pwd:606f2d0e4056aa5b3559b3471eac3061
a=candidate:Hc0a8019a 1 UDP 2130706431 192.168.1.154 19466 typ host
a=candidate:S47bb4620 1 UDP 1694498815 71.187.70.32 19466 typ srflx raddr 192.168.1.154 rport 19466
a=candidate:Hc0a8019a 2 UDP 2130706430 192.168.1.154 19467 typ host
a=candidate:S47bb4620 2 UDP 1694498814 71.187.70.32 19467 typ srflx raddr 192.168.1.154 rport 19467
a=rtpmap:99 H264/90000
a=fmtp:99 max-br=2000;profile-level-id=42801F
a=sendrecv

**Comment by jbittner1002** [comment]
Do you know anyone I can hire to help me with this ? Please email me off line at john@xaccel.net

**Comment by dgreif** [comment]
@jbittner1002 I took some time to document what I have learned so far, along with example SIP captured from the Ring App on Android.  See https://github.com/dgreif/ring/wiki/SIP-Communication.  This is pretty much the extent of what I can provide, but I hope it holds what you need to get a successful connection!

**Comment by jbittner1002** [comment]
Thank You.

John
Xaccel

**Comment by dgreif** [comment]
Thank you for the donation John!  I take it you got Asterisk working?
