### ISSUE TITLE
HOOBS Certification

### ISSUE THREAD

**Issue by BobbySlope** [dgreif/ring#334]
Hello @dgreif 

We like to inform you that we have certified your Plugin directly for HOOBS as we no longer fork the plugin to certify it.

Your Plugin is set to automatically certify the Latest version you push to npm.

**Heres the Plugin site of your Plugin:**
https://plugins.hoobs.org/plugin/homebridge-ring

_HOOBS Tab - shows the HOOBS customised Readme
Homebridge Tab - shows your Readme on npm_

Users can also write reviews there and we plan to extend it with an Plugin based forum.

All support will be done by HOOBS, and you can direct any HOOBS Users to our Support site:
http://support.hoobs.org

We will check if its an Issue related to HOOBS or an issue with the Plugin itself. If the second is the case we will contact you via issues on your GitHub repo.

We created two badges that u can add to your readme:

[![certified-hoobs-plugin](https://badgen.net/badge/HOOBS/Certified/yellow)](https://plugins.hoobs.org) [![hoobs-support](https://badgen.net/badge/HOOBS/Support/yellow)](https://support.hoobs.org)

Feel free to add them to your readme.

Regards

Bobby @hoobs-org

**Comment by mkellsy** [comment]
Bobby this guy is on our Slack.

**Comment by BobbySlope** [comment]
I know
