### ISSUE TITLE
HAP CameraController not found.

### ISSUE THREAD

**Issue by Hornett69** [dgreif/ring#335]
# Bug Report

### Describe the Bug
Hello I have an issue since upgrade with homebridge 1.1.0
Any idea ??

### To Reproduce
 - Downgrade Homebridge --> same issue
 - Install ffmpeg --> same issue

### Screenshots/Logs
Msg : mai 25 17:59:20 raspberrypi homebridge[1856]: [2020-5-25 17:59:20] [Ring] HAP CameraController not found. Please make sure you are on homebridge version 1.0.0 or newer
mai 25 17:59:20 raspberrypi homebridge[1856]: [2020-5-25 17:59:20] [Ring] Error connecting to API
mai 25 17:59:20 raspberrypi homebridge[1856]: [2020-5-25 17:59:20] [Ring] Error: HAP CameraController not found. Please make sure you are on homebridge version 1.0.0 or newer
mai 25 17:59:20 raspberrypi homebridge[1856]: at new Camera (/usr/local/lib/node_modules/homebridge-ring/lib/homebridge/camera.js:27:19)
mai 25 17:59:20 raspberrypi homebridge[1856]: at /usr/local/lib/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:193:123
mai 25 17:59:20 raspberrypi homebridge[1856]: at Array.forEach ()
mai 25 17:59:20 raspberrypi homebridge[1856]: at RingPlatform. (/usr/local/lib/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:171:28)
mai 25 17:59:20 raspberrypi homebridge[1856]: at Generator.next ()
mai 25 17:59:20 raspberrypi homebridge[1856]: at fulfilled (/usr/local/lib/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:5:58)
mai 25 17:59:20 raspberrypi homebridge[1856]: at processTicksAndRejections (internal/process/task_queues.js:97:5)

### Homebridge Ring Config
3 cameras : 1 doorbell pro and 2 caméras Stick Up Cam
config.json
{
			"platform": "Ring",
			"name": "Ring",
			"refreshToken": "XXXXXXX"	
		},

### Environment
-Raspberry PI 3 up to date
-Node : v12.16.3
-Npm : 6.14.4
-Homebrige : 1.1.0
pi@raspberrypi:~ $ npm ls homebridge
/home/pi
└── (empty)

pi@raspberrypi:~ $ npm ls -g homebridge
/usr/local/lib
└── homebridge@1.1.0

 -Homebridge-ring: 8.2.0 

Hello I have a same issue since upgrade with homebridge 1.1.0 :

**Comment by Hornett69** [comment]
I have updated nom with 6.14.5... same issue..

**Comment by Hornett69** [comment]
I read issue #320... but i have not a solution with this one...

**Comment by dgreif** [comment]
This issue has popped up a number of times already and each time the user has had a second copy of homebridge installed _somewhere_.  Every homebridge setup is slightly different, so it's hard to know exactly where to look.  The main place would be whatever directory you actually start `homebridge` from.  In that directory, look to see if there is a `node_modules/homebridge` directory and if there is, then it's probably your second copy.

**Comment by Hornett69** [comment]
I confirm...
i have two : 
/usr/local/lib/node_modules/homebridge
and
/usr/lib/node_modules

the instance used is obviously the one in the directory : /usr/lib/node_modules

How to do ?

**Comment by Hornett69** [comment]
I have a solution... not clean... but now this issue is solved...
just make a copy...

sudo cp /usr/local/lib/node_modules/homebridge /usr/local/lib/node_modules/homebridge

And now the both homebridge are up to date...
