### ISSUE TITLE
Log Error and Failed Streaming - Unknown Cause

### ISSUE THREAD

**Issue by JazzerAlto** [dgreif/ring#338]
# Bug Report

### Describe the Bug
I had a failed stream error and it threw up some errors I have not seen before

[5/30/2020, 08:07:00] [Ring] Preparing Live Stream for Left Side Backyard
[5/30/2020, 08:07:01] [Ring] Failed to prepare stream for Left Side Backyard (1.154s)
[5/30/2020, 08:07:01] [Ring] Error: bind EADDRINUSE 0.0.0.0:44021
    at dgram.js:338:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 44021
}
(node:942) UnhandledPromiseRejectionWarning: Error: bind EADDRINUSE 0.0.0.0:44021
    at dgram.js:338:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
(node:942) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 61)
(node:942) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### To Reproduce
Unknown.  It appears to be a random occurrence and a subsequent attempt to stream from the same camera was successful

### Expected behavior
No failure to stream.  No error

### Screenshots/Logs
[5/30/2020, 08:07:00] [Ring] Preparing Live Stream for Left Side Backyard
[5/30/2020, 08:07:01] [Ring] Failed to prepare stream for Left Side Backyard (1.154s)
[5/30/2020, 08:07:01] [Ring] Error: bind EADDRINUSE 0.0.0.0:44021
    at dgram.js:338:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 44021
}
(node:942) UnhandledPromiseRejectionWarning: Error: bind EADDRINUSE 0.0.0.0:44021
    at dgram.js:338:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
(node:942) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 61)
(node:942) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Additional context
None

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

{
    "bridge": {
        "name": "Homebridge",
        "username": "XXX",
        "port": 51826,
        "pin": "XXX"
    },
    "accessories": [
        {
            "accessory": "Roomba",
            "name": "Roomba",
            "model": "e5",
            "blid": "3167012430612810",
            "robotpwd": "XXX",
            "ipaddress": "192.168.100.205",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": true,
            "cacheTTL": 30,
            "plugin_map": {
                "plugin_name": "homebridge-roomba-stv",
                "index": 0
            }
        },
        {
            "name": "1st Floor Vacuum",
            "ip": "192.168.100.207",
            "token": "XXX",
            "waterBox": false,
            "pause": true,
            "dock": true,
            "delay": false,
            "cleanword": "Clean The",
            "autoroom": false,
            "rooms": [
                {
                    "name": "Living Room",
                    "id": 16
                },
                {
                    "name": "Study",
                    "id": 17
                },
                {
                    "name": "Kitchen",
                    "id": 19
                },
                {
                    "name": "Entry Way",
                    "id": 21
                },
                {
                    "name": "Dining Room",
                    "id": 22
                }
            ],
            "accessory": "XiaomiRoborockVacuum"
        },
        {
            "name": "2nd Floor Vacuum",
            "ip": "192.168.100.208",
            "token": "XXX",
            "waterBox": false,
            "pause": true,
            "dock": true,
            "delay": false,
            "cleanword": "Clean The",
            "autoroom": false,
            "rooms": [
                {
                    "name": "David's Office",
                    "id": 17
                },
                {
                    "name": "Master Bathroom",
                    "id": 18
                },
                {
                    "name": "Guest Bedroom",
                    "id": 19
                },
                {
                    "name": "Guest Bathroom",
                    "id": 20
                },
                {
                    "name": "Julee's Office",
                    "id": 21
                },
                {
                    "name": "Master Bedroom",
                    "id": 22
                },
                {
                    "name": "Upstairs Hallway",
                    "id": 23
                }
            ],
            "accessory": "XiaomiRoborockVacuum"
        }
    ],
    "platforms": [
        {
            "refreshToken": "XXX",
            "hideDoorbellSwitch": true,
            "hideCameraMotionSensor": false,
            "hideInHomeDoorbellSwitch": true,
            "hideUnsupportedServices": true,
            "locationModePollingSeconds": 0,
            "platform": "Ring"
        },
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "units": "us",
            "interval": 5,
            "stations": [
                {
                    "nameNow": "Home",
                    "service": "weatherunderground",
                    "key": "XXX",
                    "stationId": "KKSOVERL74",
                    "language": "en",
                    "compatibility": "both",
                    "conditionCategory": "simple",
                    "now": true,
                    "extraHumidity": true,
                    "hidden": [
                        "Air Pressure",
                        "Ozone",
                        "Solar Radiation",
                        "UV Index"
                    ],
                    "tresholdWindSpeed": 1
                },
                {
                    "nameNow": "Olathe",
                    "service": "openweathermap",
                    "key": "XXX",
                    "locationCity": "Olathe, US",
                    "language": "en",
                    "compatibility": "both",
                    "conditionCategory": "detailed",
                    "now": true,
                    "extraHumidity": true,
                    "hidden": [
                        "Air Pressure",
                        "Ozone",
                        "Solar Radiation",
                        "UV Index"
                    ]
                }
            ],
            "platform": "WeatherPlus"
        }
    ]
}

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: 12.17.0
 - NPM: 6.14.5
 - homebridge-ring: 8.2.0
 - homebridge: 1.1.0

**Comment by dgreif** [comment]
@JazzerAlto that issue occurs when ffmpeg tries to bind to a port that is already in use on your computer.  It's a tough race condition where we try to find open ports, but then within milliseconds of finding it, it is taken by something else.  It's a rare occurrence, but I'll keep this issue open and think through possible solutions.  The main challenge is that the way I currently pass configuration to ffmpeg, we have to know the port number ahead of time.

**Comment by dgreif** [comment]
I found an issue in my setup where issues like this one weren't getting relayed back to HomeKit.  I added logic to give you immediate "No Response" feedback when this issue happens, so you can stop and start a new stream immediately, instead of waiting 30 seconds for it to time out.  I think this is the best I can do for now.
