### ISSUE TITLE
Plugin hangs up (no modes selection, no live stream) after several running hours

### ISSUE THREAD

**Issue by jchristianj** [dgreif/ring#340]
# Bug Report

### Describe the Bug
After several hours of running the plugin (something between 5 - 15 hours) it refuses to work. Normally, after re-start of my RPi everything is fine, Ring modes can be changed, Snapshots are updated, and live stream (for both of my cams) can be initiated and is pretty quick.
Approximately Half a day later, nothing of it works. Changing modes results in a spinning wheel on the tile in the home app (Homekit), live streams do not start at all and result in either "camera  not available" or "camera is occupied by another user" overlay (don't know the English wording as it is in German language here)
All other plugins are working fine.
### To Reproduce
Start Pi with Hoobs, verify all functions of the Ring plugin are working (modes selection, live stream etc.)
Wait at least 12 hours, then nothing is working any longer. 
After a restart of the Hoobs service or a full shutdown and restart of the RPi everything is fine again.

### Expected behavior
Should be running continuously without these issues.

### Screenshots/Logs
Logs if live stream and modes selection is working:
31.5.2020, 09:45:51 [Ring] Preparing Live Stream for Haustür
31.5.2020, 09:45:52 [Ring] Waiting for stream data from Haustür (0.909s)
31.5.2020, 09:45:53 [Ring] Received stream data from Haustür (1.489s)
31.5.2020, 09:45:53 [Ring] Streaming active for Haustür
31.5.2020, 09:46:00 [Ring] Stopped Live Stream for Haustür
....
31.5.2020, 09:46:52 [Ring] Setting Zuhause Mode to away
31.5.2020, 09:46:55 [Ring] Setting Zuhause Mode to home
....
If it is not working, then it is stuck at
[Ring] Preparing Live Stream for Haustür

### Additional context
Having this issue since Hoobs 3.2.4 and Ring plugin 7.2.5. (updated at the same time). Former versions of Hoobs and/or ring didn't have this issue, all has been fine.
Tried the following steps to resolve:

1) Removed and re-installed ring plugin
2) Setup Hoobs (3.2.6) from scratch, fresh installed and configured Ring 8.2.0
3) Re-newed API key 
4) Put static IP of Raspberry in DMZ of router
5) Used different DNS (e.g. 1.1.1.1 or 8.8.8.8 in router)
6) Several re-starts of Router, RPi.

### Homebridge Ring Config
```
{
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "xxx",
            "debug": false,
            "hideInHomeDoorbellSwitch": false,
            "locationIds": []
        }
```

### Environment

 - OS: buster 4.19.97-v7+
 - Node.js: 12.16.3
 - NPM: 6.14.4
 - homebridge-ring: 8.2.0
 - homebridge: Hoobs 3.2.6

**Comment by dgreif** [comment]
@jchristianj please update to version `9.0.0` and see if live streams work for you now

**Comment by jchristianj** [comment]
Just updated... first feeling is that live stream establishes quicker than before (app. 5 seconds in 8.2.0, now <3 seconds in 9.0.0) on my Ring Pro (hardwired).
But on my battery powered original Ring it is half chance that live stream starts at all. Succeeds in 50% of cases... 
I'll have a look at long term usage (which my initial problem is related to) tomorrow after a few more hours running time and keep you informed.

**Comment by ifeign** [comment]
I have noticed similar behavior with my battery powered camera @jchristianj, my camera was almost 100% reliable before this update and now it’s more of a gamble. Occasionally after using live view, homebridge hangs for a few seconds, rendering all other plugins unresponsive briefly. Might move ring to its own instance after this.

**Comment by jchristianj** [comment]
Running now for >30 hours and both cams still connecting upon live view, and modes selection working as well. Well done, seems to be solved. Overall impression is that version 9.0.0 is much quicker in establishing live view connection (at least for wired cams), inside my home network takes <2s, outside on LTE mostly <5s which is no difference to the Ring app.
Battery cam fails sometimes, but this also happens in the Ring app, so maybe not related to the plugin.
