### ISSUE TITLE
Trigger live view

### ISSUE THREAD

**Issue by Bravedragon0313** [dgreif/ring#343]
# Feature Request
How to make script which has function as same as press ring button pressed
### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instuctions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dgreif** [comment]
@Bravedragon0313 I'm sorry but your question isn't clear enough for me to provide an answer.  I see you copied the whole project, which seems a bit unnecessary.  You can install the client with `npm i ring-client-api` and then interact with it by requiring `ring-client-api` in your code.  The examples directory holds a number of examples of how to interact with the api.

**Comment by Bravedragon0313** [comment]
Thanks for your response
I installed node modules and I got sip info.
Now I need to make script which has function as same as ring button pressed
In case of  ding.kind === 'ding' it recognized doorbell pressed
In other words can I press doorbell by script?
Please let me know
Thanks

**Comment by dgreif** [comment]
As far as I know, there is no way to _simulate_ a doorbell press by creating a new ding.  Dings only come from the real cameras.

**Comment by Bravedragon0313** [comment]
Thanks I understood.
On your sample code I can see camera.startVideoOnDemand()
This function ask the camera to start a new video stream
How to make sure I am getting video?

**Comment by dgreif** [comment]
That's correct, you can start new live streams on demand.  There are a lot of options for how you can handle the live stream, such as https://github.com/dgreif/ring/blob/master/examples/stream-example.ts and https://github.com/dgreif/ring/blob/master/examples/record-example.ts.  You are able to pass in whatever options you want for `ffmpeg`, which allows you to store or use the live stream in whatever way is useful to you.  Just calling `startVideoOnDemand()` will start a live stream that gets stored on the Ring servers, but you don't _have_ to do anything with the output if you just want video to be stored by Ring.

**Comment by Bravedragon0313** [comment]
Thanks for answering
I have one more question.
when I click doorbell pressed which event will happen?
How to check if I press doorbell or not with your ring api source code?
Is it impossible to make script which has function as same as ring doorbell pressed?

**Comment by dgreif** [comment]
You can see an example event subscription that listens for all motion/press/live stream events from the cameras here: https://github.com/dgreif/ring/blob/master/examples/example.ts#L75-L76

If you only care about doorbell presses (not motion or other streaming events), then you can use `onDoorbellPressed` instead of `onNewDing`

I'm still not clear on what you mean by "function as same as ring doorbell pressed", but hopefully I have answered your question.

**Comment by Bravedragon0313** [comment]
Thanks
Which different event will happen when video started, motion detected, doorbell pressed on your source code?
Please let me know in more detail

**Comment by dgreif** [comment]
I'm sorry but I'm still very unclear on what you are trying to accomplish.  The examples are the best resource that I can give you to demonstrate how to use the api.  Since you already have a copy of the code, you can do an `npm install` and then `npm run example` to see the main example start up and listen for motion/press events on your cameras.

**Comment by Bravedragon0313** [comment]
Okay 
Thanks for your help
What can I do for your helping?

**Comment by dgreif** [comment]
Donations are always welcome if you feel so inclined.  https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=HD9ZPB34FY428&currency_code=USD&source=url

**Comment by sjiampojamarn** [comment]
is there any change in the api? I'm no longer get startVideoOnDemand from the latest update:

error TS2339: Property 'startVideoOnDemand' does not exist on type 'RingCamera'.
