### ISSUE TITLE
Add new device (Ring 3)

### ISSUE THREAD

**Issue by nikbyte** [dgreif/ring#346]
Please, add Ring Doorbell 3.
Its id "doorbell_scallop_lite".

Maybe this is the reason why I see only camera after I upgrade by Ring?
Now I have no any controls, camera only.

**Comment by dgreif** [comment]
Can you give it a try in v`9.1.0`?

**Comment by nikbyte** [comment]
Thank you. Now I see it as Ring 3, but I have no additional accessories which I was seen when I used Ring 1. Why?

**Comment by dgreif** [comment]
So if you go into the live feed, then settings, then accessories, you don’t see the motion sensor and doorbell? You may have had the tiles separated previously

**Comment by nikbyte** [comment]
Yes. I see only camera accessory and no doorbel and motion accessories.
I'm 100% sure (I know that first time I need to go into settings and choose menu item to split accessories to separate icons). I had these accessories for Ring 1.
After I removed Ring 1 from my account, I have only Camera accessory.

**Comment by nikbyte** [comment]
If you need, I can provide you my authentication token (privately).

**Comment by dgreif** [comment]
I'd prefer not to log into anyones account.  Can you verify that you do not have the `hideCameraMotionSensor` config option set?  It's possible that HomeKit got confused somehow when you added the new camera and removed the old one.  Might be a case where you need to remove the `homebridge-ring` plugin from homebridge to remove the camera in HomeKit, and then re-add it.

**Comment by nikbyte** [comment]
Thank you very much. You're right. I'm confused with this option too. I disabled it and I still had accessories on old Ring. After replacing Ring with this option enabled, my accessories disappeared. Now I see Ring button and motion switch.

Tell me please, is there any accessory which allows to disable Ring Chime?

**Comment by dgreif** [comment]
I'm planning to do some work with the Ring Chime this week, which should end with a button to disable the chime based on motion/presses of your doorbell just like the app.  So are you good to go with the camera accessories now?

**Comment by nikbyte** [comment]
Yes, I'm ok now. Thank you very much for all your help and all your work on this plugin.
