### ISSUE TITLE
attempting live stream on a camera crashed server

### ISSUE THREAD

**Issue by schemers** [dgreif/ring#347]
# Bug Report

### Describe the Bug
 Just clicked on a camera in Home app on iOS and it caused Hoobs to crash due to an error: 

`This callback function has already been called by someone else; it can only be called one time.
`
### To Reproduce
 - Start Homebridge
 - Just clicked on a camera to view live
 - Homebridge/Hoobs crashed

### Expected behavior
 Expected behavior was to view the live camera stream

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

```
6/5/2020, 5:54:36 PM [Ring] Streaming active for Front Garage
6/5/2020, 5:54:37 PM Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/once.js:11:19
    at Mute.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/homebridge/base-data-accessory.js:19:17)
    at Mute.emit (events.js:215:7)
    at Mute.EventEmitter.emit (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
    at Mute.Characteristic._this.getValue (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Characteristic.js:190:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:753:32
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:694:18)
    at HAPServer.emit (events.js:210:5)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
6/5/2020, 5:54:37 PM Got SIGTERM, shutting down Bridge...
```

### Additional context
 Wasn't able to reproduce, working fine on subsequent attempts 

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "xxx",
            "hideCameraMotionSensor": true,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "showPanicButtons": false,
            "locationIds": []
        }

```

### Environment

 - OS: Raspbian 4.19.75-v7l+
 - Node.js: 12.13.1
 - NPM: 6.13.4
 - homebridge-ring: 8.2.0
 - homebridge: Hoobs 3.2.6

**Comment by dgreif** [comment]
Sounds like a race condition of some sort. The code that ran into an issue was actually not the live stream, but the logs don’t provide enough info to narrow it down all the way (you provided plenty, the info I need just isn’t logged at all). I did make some changes to the behavior in v9 that would probably get rid of this problem, but HOOBS hasn’t certified that release yet. Let me know if you see this error again once you are able to update to v9
