### ISSUE TITLE
Snapshot 10 second latency

### ISSUE THREAD

**Issue by erpeters3** [dgreif/ring#348]
# Bug Report

### Describe the Bug
 when opening HomeKit the snapshots shows update “now” but is not actually current.  At exactly 10 seconds it refreshes to current. 

### To Reproduce
 - Open Home App
 - View ring camera snapshot (any of them)
 - Note refresh tag “Now” but notice it’s an old snapshot.  For instance still dark out after sunrise. 

### Expected behavior
 Current snapshot on open. 

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 This is recent behavior.  Perhaps last 2-3 releases. Not most recent release only. 

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensit

    "platforms": [
        {
            "refreshToken”:”XXX",
            "hideLightGroups": true,
            "hideDoorbellSwitch": true,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "nightModeBypassFor": "some",
            "debug": false,
            "platform": "Ring"
        },

```

### Environment
<!-- ✍️edit: -->
 - OS: Mac OS X latest
 - Node.js: latest<!-- run `node -v` to get current version -->
 - NPM: latest<!-- run `npm -v` to get current version -->
 - homebridge-ring: 9.0.0
 - homebridge: latest

**Comment by dgreif** [comment]
See https://github.com/dgreif/ring/wiki/Snapshot-Limitations

**Comment by erpeters3** [comment]
All wired cameras and it didn’t behave this way before.  It would always refresh snapshots within 2-3 seconds of opening.  Not a huge deal but wanted to report this new behavior.   Could be faulty memory in my part.

**Comment by dgreif** [comment]
https://github.com/dgreif/ring/wiki/Snapshot-Limitations#work-arounds-as-of-v810 bullet 2

**Comment by erpeters3** [comment]
Thanks!
