### ISSUE TITLE
enable / disable placeholder image 

### ISSUE THREAD

**Issue by jchristianj** [dgreif/ring#350]
# Feature Request

### Description
Make the new function "placeholder image" optional.

### Describe the solution you'd like
Add a parameter in the json file such as "showPlaceholderImage": true
to enable the placeholder. If FALSE, then it reverts to the old solution (show formerly cached image like in 9.0.0)

**Comment by dgreif** [comment]
I just released v`9.1.1`, which will keep the timestamps in cache for 2 minutes.  Give it a try and let me know what you think

**Comment by jchristianj** [comment]
Thanks, installed and briefly tested: Placeholder appears if I didn't use the home app for more than 2 minutes, correct?
Although I think it's a matter of individual taste and maybe other users may think differently, I find it disturbing und not a good user experience to show these placeholders. It is like something isn't working correctly. They do not fit to the simplicity the whole Apple home app is designed with. 
So for my feeling it still would be better to provide an option if placeholders shall be shown or just use older snapshots.

**Comment by dgreif** [comment]
That's correct, they will show if there hasn't been a snapshot update in the last 2 minutes.  When you open the Home app, you will see the placeholder immediately while a new image is fetched.  If you are on the same LAN as your homebridge server, then HomeKit requests a new snapshot after 10 seconds.  If you are off the network (like on LTE), then HomeKit doesn't request a new snapshot until 60 seconds later.  I know this isn't an ideal setup, but it's the best I can do within the constraints of HomeKit and Ring.  Both sides have their own quirks and limitations, which I am trying to balance.  The reason the placeholders make sense is that showing an old image makes it look like a valid snapshot but with a recent time stamp.  It may say the image is 5 seconds old, but it was actually taken yesterday.  I have had a lot of complaints of the images being stale and leading to a false sense that camera is clear, and that's what I am trying to avoid.  I prefer not to add new options as the list has gotten pretty large, so I'm trying to find a balance with this feature that makes sense for everyone. I'll continue to work on snapshots and use new features as Ring introduces them, but for now I think this needs to stay as it is. I do really appreciate the feedback and will keep it in mind going forward.
