### ISSUE TITLE
Select which cameras or exclude them all

### ISSUE THREAD

**Issue by stephendowning** [dgreif/ring#353]
Hi I have a few Ring accessories - doorbell, alarm, cameras etc.

I only really want the alarm in my Homekit but now since I updated my doorbell and cameras are all there and they give people access that I wouldn't normally want to have access - also doorbell notifications.

Please can you allow us to exclude either by device type or by individual device?

Thanks for the awesome work :)

**Comment by stephendowning** [comment]
Hi @dgreif just wondered if this was possible please at it's driving me mad!

**Comment by dgreif** [comment]
I added a new `hideDeviceIds` option which allows you to selectively remove devices, including cameras, from HomeKit.  See https://github.com/dgreif/ring/tree/master/homebridge#optional-parameters for details
