### ISSUE TITLE
Option to remove ugly “Fetching Snapshot please wait..”

### ISSUE THREAD

**Issue by malmentm** [dgreif/ring#354]
Hello
Can it be an option to choose to remove this? I rather have an old outdated image showing than this ugly message lite it was before :)

Thanks for the great work!

**Comment by dgreif** [comment]
Please search for existing issues before opening a new one.  This is a duplicate of #351.

**Comment by malmentm** [comment]
@dgreif hello! I love your work on this plugin and I know I am in no position to demand features etc. But to get the old snapshot behaviour back (with the outdated snapshot instead of the “fetching etc”, is my only option to downgrade?

**Comment by dgreif** [comment]
@malmentm currently downgrading is your only option, but I'm planning to make some changes to snapshots in the near future that would return it to the previous behavior
