### ISSUE TITLE
Homebridge exits when loading homebridge-ring config

### ISSUE THREAD

**Issue by ceeeekay** [dgreif/ring#360]
# Bug Report

### Describe the Bug
Previously working Homebridge install is refusing to start completely, and exits on startup
This only occurs when the Ring platform is present in the Homebridge config.

### To Reproduce
 - Start Homebridge with Ring config present

### Expected behavior
Homebridge starts cleanly

### Screenshots/Logs
https://gist.github.com/ceeeekay/b1abf28eade1a1b6890a13317e0e9b84

### Additional context
I am unsure whether this issue is related to homebridge-ring, or some other underlying Homebridge/OS issue.
I updated homebridge-config-ui-x and homebridge-ring to the lastest versions, and have had this issue since restarting the Homebridge service after the update.
It was previously working fine with the current config (and tested again against a known good backup). 
I've also downgraded homebridge-ring to 9.0.0 but the problem persists.
* Removing all other plugin configs, and leaving the Ring config present still exhibits this issue.
* Removing only the ring config and leaving all other plugin configs, and Homebridge starts successfully.
This makes me suspect the issue is something related to homebridge-ring, but I'm not 100% sure that's the case.

### Homebridge Ring Config
https://gist.github.com/ceeeekay/987ca27c0fa0675e1c41099759ed7c80

### Environment
 - OS: Ubuntu
 - Node.js: v14.0.0 
 - NPM: 6.14.4
 - homebridge-ring: 9.1.1
 - homebridge: 1.1.0
 - hoobs: N/A

**Comment by dgreif** [comment]
The only odd thing in the logs is this line: ‘[Ring] Request for machine id timed out.  Falling back to random session id’. This means the plugin is unable to fetch the machine id for you computer, which means it can’t keep a consistent session across restarts of homebridge. Can you try running ‘sudo cat /var/lib/dbus/machine-id’ and see what it returns? It should be a bunch of random characters. If it instead shows an error, then let me know what the error is

**Comment by ceeeekay** [comment]
Yep I get a hash/hex string back. That error isn't always in the logs, BTW. Not sure what's causing it though.

I've just done another restart of HB to confirm (with the Ring config present) and it's not complaining about machine id.

**Comment by dgreif** [comment]
That’s really odd... without any errors in the logs, it’s really hard to track down the issue. I haven’t had any other complaints since I released the current version, so I think it’s most likely something specific to your environment. No idea what it could be without errors in the logs though. Maybe try setting “debug”: true in the ring config

**Comment by ceeeekay** [comment]
Enabled debug fo rth eplugin, but I'm not seeing anything at all from the ring plugin, debug or otherwise. The only ring entry in my logs is `[Ring] Initializing Ring platform...` then a bit further on `[Ring] didFinishLaunching`

Note that I did downgrade all the way to 9.0.0 because I couldn't remember the previous version I was using (it wasn't more than a few weeks old though).

If there were any errors to speak of I could probably figure my way though this, but I'm completely stuck.

**Comment by dgreif** [comment]
Did you try downgrading config UI x?

**Comment by ceeeekay** [comment]
Good call - I'll give that a try.

**Comment by ceeeekay** [comment]
Downgrading Config UI X didn't help, and neither did reinstalling it fresh. So I went nuclear and purged/reinstalled nodejs.

This seems to have worked, and I have Ring running as the only plugin for now, although I've unsurprisingly lost all my automations.

The only downside is I have no idea what caused the original issue, but the Ring plugin is 90% of the reason why I have Homebridge in the first place, so I'll call it a win.

Thanks for all your help (and for the awesome plugin).

**Comment by dgreif** [comment]
Sorry to hear you had to wipe everything but I’m glad you got it running again. If you still have the backup you mentioned earlier, you might be able to restore your homebridge and get your automation back. I have no idea what went wrong, but I would guess you should be fine to reinstall the other plugins as well.
