### ISSUE TITLE
Doorbell actions appears not to be working

### ISSUE THREAD

**Issue by malouf-erfan** [dgreif/ring#362]
# Bug Report

### Describe the Bug
I have a Ring Doorbell with camera added all works fine except when I added an action (in my case turning on the light ) on Single Press, it does not seem to trigger the action, when I test the automation with Home app it works but does not trigger on single press.

### To Reproduce
Add the ring plugin
Add an action to Single Press ( like turning a light )
Press the door bell 

### Expected behavior
Action needs to trigger the accessory in my case light

### Homebridge Ring Config

```
        {
            "refreshToken": "omitted",
            "hideInHomeDoorbellSwitch": true,
            "platform": "Ring"
        }
```

### Environment
 - OS: Ubuntu 18.04
 - Node.js: v10.19.0
 - NPM: 6.14.4
 - homebridge-ring: v9.1.1
 - homebridge: 1.1.0
 - hoobs: N/A

**Comment by dgreif** [comment]
I just tried it out with my Doorbell Pro and it triggered the single press action with no issues.  Even if it detects motion first, it still registers the doorbell press.  Which  version of doorbell camera do you have?

**Comment by malouf-erfan** [comment]
thanks for quick response, I have Doorbell Pro as well, hmmm that is strange, thanks for confirming, I will try removing and adding back the accessory and will test more.

**Comment by malouf-erfan** [comment]
re-adding the accessory worked, thanks.
