### ISSUE TITLE
Hide security system (Request)

### ISSUE THREAD

**Issue by Lui5Jacint0** [dgreif/ring#366]
I would like to hide the security system from Homekit, but i can't seem to be able to.

config:

"alarmOnEntryDelay": true,
            "hideLightGroups": true,
            "hideDoorbellSwitch": true,
            "hideCameraMotionSensor": false,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "showPanicButtons": false,
            "debug": true,
            "locationIds": [
                "59d11c50-09a6-4bc6-7bcf-0e15e2f1b308"
            ],
            "platform": "Ring"

![Captura de ecrã 2020-06-17, às 18 07 12](https://user-images.githubusercontent.com/930892/84935470-483b1200-b0c8-11ea-8c5c-555b6a506d57.png)
![Captura de ecrã 2020-06-17, às 18 25 59](https://user-images.githubusercontent.com/930892/84935481-4bce9900-b0c8-11ea-885e-c9d1e3b2631f.png)
![Captura de ecrã 2020-06-17, às 18 25 47](https://user-images.githubusercontent.com/930892/84935484-4c672f80-b0c8-11ea-9cf2-5332776090a2.png)

**Comment by dxdc** [comment]
@Lui5Jacint0 is this a duplicate?

https://github.com/dgreif/ring/issues/283

**Comment by dxdc** [comment]
It's also listed in the docs:

```
Location Modes
For homes not equipped with a Ring Alarm, Locations Modes can be used as an alternative way to change settings for Ring cameras.
Shows as a security system in HomeKit, just like the Ring Alarm.
Can be hidden with "locationModePollingSeconds": 0
```

**Comment by Lui5Jacint0** [comment]
Thanks! Solved
