### ISSUE TITLE
Disable camera snapshots on doorbell events

### ISSUE THREAD

**Issue by Dillinja2** [dgreif/ring#368]
# Feature Request

### Description
 A clear and concise description of the problem or missing capability...

Currently, I'm using an Echo Show to automatically stream video of Ring Doorbell events. This prevents snapshots from ever working properly (404 issue).

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

Expose a toggle to disable homebridge from attempting to retrieve a new snapshot on doorbell events.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

Hiding the 404 attempts in the log?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dgreif** [comment]
I’m planning to do some overhaul on snapshots in the coming weeks. Not promise on a timeline, but the changes I plan to make should eliminate the 404 logs in most scenarios, including when a stream is live. With those changes, an option to disable snapshots will be unnecessary, so I’m going to close this issue. Will post here when the changes are released.
