### ISSUE TITLE
9.3.1 & 9.3.2 added weird switch.

### ISSUE THREAD

**Issue by MikeDProducer** [dgreif/ring#369]
# Bug Report

### Describe the Bug
A switch appeared in my favorites on the Home App after the last updates 9.3.1 and 9.3.2. I cannot remove it.

### To Reproduce
I have restarted homebridge many times. Also restarted the home app. It will not go away.

### Expected behavior
Usually this switch was hidden. All of the commands to hide switches in the schema are still selected. 

### Screenshots/Logs
![Screen Shot 2020-06-17 at 4 20 19 PM](https://user-images.githubusercontent.com/61333457/84951730-76175b00-b0b6-11ea-87ad-da1f7f99266a.png)

### Additional context
I reverted to 9.3.0 and was able to remove the new switches from Favorites, but they are still showing up in the home app. I cannot remove them.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

  "refreshToken": "xxx",
            "hideLightGroups": true,
            "hideDoorbellSwitch": true,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "locationModePollingSeconds": 0,
            "platform": "Ring"

```

### Environment
 - OS:  Raspbian
 - Node.js: v12.16.3
 - NPM:  v6.14.4
 - homebridge-ring: 9.3.2
 - homebridge: 1.1.1

**Comment by mikesalz** [comment]
Yep, same weird switch here.  I tried every "hide" configuration and nothing worked.  Maybe in the future, new additions should be defaulted to hidden?

**Comment by dgreif** [comment]
It’s a switch to control your Chime, which was introduced in 9.3.0. You can use the hideDeviceIds option if you don’t want to see it

**Comment by mikesalz** [comment]
@dgreif Thanks for responding.  How/where can the device ID be found?  I ran Homebridge in debug and only saw a single line for Ring:

> [6/18/2020, 2:05:28 PM] [Ring] Configuring 1 cameras and 2 devices for location "Tampa" - locationId: xxxxxxx-xxxxx-x

I also tried using the serial number from the device properties in HomeKit, and that did not work.  Suggestions?

**Comment by mikesalz** [comment]
Never mind.  I found it in the log!  I'm not sure why I didn't see it before.

**Comment by dgreif** [comment]
Glad you found the Id. Were you able to hide the chime switches?

**Comment by mikesalz** [comment]
@dgreif Yes, once I found the ID, I was able to hide the chime switches.  Thanks for checking in.  I really appreciate it!!  While I have you, another quick question - Is there a config setting that would allow me to display the cached snapshot instead of the "Fetching new snapshot" message?  My preference is to see *something* rather than text, but no biggie if that is not an option!

**Comment by dgreif** [comment]
I'm planning to overhaul snapshots soon.  Should be able to do away with the placeholders

**Comment by mikesalz** [comment]
Great!  Thanks again for your help!
