### ISSUE TITLE
[Ring] Error connecting to API & TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by GuanacoSensei** [dgreif/ring#375]
# Bug Report

### Describe the Bug
 I installed HOOBS over the weekend on my raspberry Pi, and I installed the homebridge-ring plugin. I followed the steps provided, including creating the refresh token, and saved. As of today, I still am unable to see any of my devices and i get the following errors in the log: 

### To Reproduce
 - install Hoobs plugin, configure Refresh token and safe. 
 - Go to devices and you'll see nothing there (relating to Ring). 
 - Go to logs. 
 - See error. 

### Expected behavior
 

Normally i should be able to add my ring devices, but i can't even connect to the API. 

### Screenshots/Logs
 

```
6/23/2020, 1:21:04 PM [Ring] Error connecting to API
6/23/2020, 1:21:04 PM [Ring] TypeError: Cannot read property 'filter' of undefined
    at RingApi.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/api.js:141:18)
    at Generator.next (<anonymous>)
    at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/api.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

{
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "[REFRESH TOKEN DELETED, AS REQUESTED, FOR BEING SENSITIVE INFO",
            "hideUnsupportedServices": false,
            "hideLightGroups": false,
            "hideDoorbellSwitch": false,
            "hideCameraMotionSensor": false,
            "hideCameraSirenSwitch": false,
            "hideInHomeDoorbellSwitch": false,
            "hideAlarmSirenSwitch": false,
            "debug": true,
            "cameraDingsPollingSeconds": 0,
            "locationModePollingSeconds": 0,
            "hideDeviceIds": [],
            "locationIds": []
        }

```

### Environment

 - OS: Raspbian 
 - Node.js: v12.16.3
 - NPM: 6.14.4
 - homebridge-ring: 9.3.3
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: 3.2.6

**Comment by dgreif** [comment]
Based on the error stack, it looks like you didn't receive a valid response from Ring when your locations were requested.  I have never seen that happen before and can't recreate it on my end.  One thing I recommend you change is the `"locationIds": []` line shouldn't be in your config.  This tells the plugin not to allow _any_ locations.  Try removing that line and restarting HOOBS

**Comment by GuanacoSensei** [comment]
I tried removing that line but it comes back when I reboot the service.  I imagine that's because HOOBS' Plugin configuration page is automatically adding it there on reboot. 

`6/23/2020, 2:44:07 PM Got SIGINT, shutting down Bridge...
6/23/2020, 2:44:12 PM Loaded plugin "homebridge-ring".
6/23/2020, 2:44:12 PM Loaded plugin "homebridge-smartthings-v2".
6/23/2020, 2:44:12 PM INFO: Homebridge Version: 2.5
6/23/2020, 2:44:12 PM INFO: SmartThings-v2 Plugin Version: 2.3.4
6/23/2020, 2:44:12 PM INFO: Checking Package Version for Updates...
6/23/2020, 2:44:13 PM INFO: Fetching SmartThings-v2 Devices. NOTICE: This may take a moment if you have a large number of device data is being loaded!
6/23/2020, 2:44:13 PM GOOD: Refreshing All Device Data | Source: (First Launch)
6/23/2020, 2:44:13 PM Bridge is running on port 51826.
6/23/2020, 2:44:13 PM NOTICE: Temperature Unit is Now: (F)
6/23/2020, 2:44:13 PM NOTICE: Updating Global Values | HubIP: 192.168.86.48 | UseLocal: false
6/23/2020, 2:44:13 PM WARN: Devices to Remove: (0) []
6/23/2020, 2:44:13 PM INFO: Devices to Update: (1)
6/23/2020, 2:44:13 PM GOOD: Devices to Create: (0) []
6/23/2020, 2:44:13 PM ALERT: Total Initialization Time: (0 seconds)
6/23/2020, 2:44:13 PM NOTICE: Unknown Capabilities: []
6/23/2020, 2:44:13 PM INFO: SmartThings DeviceCache Size: (1)
6/23/2020, 2:44:13 PM INFO: WebServer Initiated...
6/23/2020, 2:44:13 PM INFO: Sending StartDirect Request to SmartThings | SendToLocalHub: (false)
6/23/2020, 2:44:13 PM INFO: Direct Connect Active | Listening at 192.168.86.56:8000
6/23/2020, 2:44:13 PM INFO: SmartThings-v2 Hub Communication Established
6/23/2020, 2:44:14 PM [Ring] Error connecting to API
6/23/2020, 2:44:14 PM [Ring] TypeError: Cannot read property 'filter' of undefined
    at RingApi.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/api.js:141:18)
    at Generator.next (<anonymous>)
    at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/api.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
6/23/2020, 2:44:14 PM INFO: INFO: Your plugin version is up-to-date
6/23/2020, 2:44:14 PM NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.4`

I just sent a message to the HOOBS team with your suggestion to see what they can do. I will keep you posted with their response.

**Comment by dgreif** [comment]
The HOOBS team will probably direct you back to me as this is a plugin level issue instead of HOOBS level.  You mentioned that this is a fairly new setup.  Did you _ever_ see devices load via homebridge-ring or has it been throwing this error from the start?  

Assuming it's been this way from the start, you may be in a situation where there are no locations tied to the Ring account you are using for your refresh token.  You should try logging into the Ring app with the same credentials and ensure that it has access to the location(s) that you expect it to.

**Comment by GuanacoSensei** [comment]
Success! @dgreif you nailed it. It turns out i was logging in with the wrong email account.... I made the changes necessary using the right account and i was able to successfully import all my devices. 

Thank you very much for your support!

**Comment by dgreif** [comment]
No problem, glad it was that simple!
