### ISSUE TITLE
camera.recordToFile error

### ISSUE THREAD

**Issue by hanlongwang** [dgreif/ring#377]
After upgrading to 9.3.3 to fix the 406 issue, I've started to see this error after recordToFile is called: 

{"log":"Writing to file /data/20200624_130413.mp4\n","stream":"stdout","time":"2020-06-24T20:04:13.247890247Z"}
{"log":"err:  [Error: 140163181193024:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/ssl3_record.c:677:\n","stream":"stdout","time":"2020-06-24T20:04:14.38433783Z"}
{"log":"] {\n","stream":"stdout","time":"2020-06-24T20:04:14.384401279Z"}
{"log":"  library: 'SSL routines',\n","stream":"stdout","time":"2020-06-24T20:04:14.384414625Z"}
{"log":"  function: 'ssl3_get_record',\n","stream":"stdout","time":"2020-06-24T20:04:14.384426179Z"}
{"log":"  reason: 'decryption failed or bad record mac',\n","stream":"stdout","time":"2020-06-24T20:04:14.384442432Z"}
{"log":"  code: 'ERR_SSL_DECRYPTION_FAILED_OR_BAD_RECORD_MAC'\n","stream":"stdout","time":"2020-06-24T20:04:14.38445385Z"}
{"log":"}\n","stream":"stdout","time":"2020-06-24T20:04:14.384465143Z"}
{"log":"err:  Error: write EPROTO\n","stream":"stdout","time":"2020-06-24T20:04:14.390295366Z"}
{"log":"    at afterWriteDispatched (internal/stream_base_commons.js:154:25)\n","stream":"stdout","time":"2020-06-24T20:04:14.390497484Z"}
{"log":"    at writeGeneric (internal/stream_base_commons.js:145:3)\n","stream":"stdout","time":"2020-06-24T20:04:14.39062446Z"}
{"log":"    at TLSSocket.Socket._writeGeneric (net.js:782:11)\n","stream":"stdout","time":"2020-06-24T20:04:14.3907426Z"}
{"log":"    at TLSSocket.Socket._write (net.js:794:8)\n","stream":"stdout","time":"2020-06-24T20:04:14.390849905Z"}
{"log":"    at writeOrBuffer (_stream_writable.js:352:12)\n","stream":"stdout","time":"2020-06-24T20:04:14.390946829Z"}
{"log":"    at TLSSocket.Writable.write (_stream_writable.js:303:10)\n","stream":"stdout","time":"2020-06-24T20:04:14.391045121Z"}
{"log":"    at Object.send (/app/node_modules/sip/sip.js:602:18)\n","stream":"stdout","time":"2020-06-24T20:04:14.391136744Z"}
{"log":"    at Object.value (/app/node_modules/sip/sip.js:835:11)\n","stream":"stdout","time":"2020-06-24T20:04:14.391253342Z"}
{"log":"    at Object.enter (/app/node_modules/sip/sip.js:1141:7)\n","stream":"stdout","time":"2020-06-24T20:04:14.391353097Z"}
{"log":"    at Object.enter (/app/node_modules/sip/sip.js:978:21) {\n","stream":"stdout","time":"2020-06-24T20:04:14.391447095Z"}
{"log":"  errno: -71,\n","stream":"stdout","time":"2020-06-24T20:04:14.391554454Z"}
{"log":"  code: 'EPROTO',\n","stream":"stdout","time":"2020-06-24T20:04:14.391645737Z"}
{"log":"  syscall: 'write'\n","stream":"stdout","time":"2020-06-24T20:04:14.391734603Z"}
{"log":"}\n","stream":"stdout","time":"2020-06-24T20:04:14.391837327Z"}
{"log":"Error: sip INVITE request failed with status 503\n","stream":"stderr","time":"2020-06-24T20:04:14.396858697Z"}
{"log":"    at /app/node_modules/ring-client-api/lib/api/sip-call.js:120:28\n","stream":"stderr","time":"2020-06-24T20:04:14.397040967Z"}
{"log":"    at next (/app/node_modules/sip/sip.js:1305:7)\n","stream":"stderr","time":"2020-06-24T20:04:14.397149794Z"}
{"log":"    at searching (/app/node_modules/sip/sip.js:1312:14)\n","stream":"stderr","time":"2020-06-24T20:04:14.39725422Z"}
{"log":"    at /app/node_modules/sip/sip.js:1297:41\n","stream":"stderr","time":"2020-06-24T20:04:14.397350887Z"}
{"log":"    at Object.message (/app/node_modules/sip/sip.js:1116:7)\n","stream":"stderr","time":"2020-06-24T20:04:14.397439998Z"}
{"log":"    at Object.signal (/app/node_modules/sip/sip.js:982:55)\n","stream":"stderr","time":"2020-06-24T20:04:14.397560232Z"}
{"log":"    at TLSSocket.\u003canonymous\u003e (/app/node_modules/sip/sip.js:1296:18)\n","stream":"stderr","time":"2020-06-24T20:04:14.397657126Z"}
{"log":"    at TLSSocket.emit (events.js:327:22)\n","stream":"stderr","time":"2020-06-24T20:04:14.397750071Z"}
{"log":"    at TLSSocket._emitTLSError (_tls_wrap.js:887:10)\n","stream":"stderr","time":"2020-06-24T20:04:14.397824093Z"}
{"log":"    at TLSWrap.onerror (_tls_wrap.js:414:11)\n","stream":"stderr","time":"2020-06-24T20:04:14.397878622Z"}

**Comment by hanlongwang** [comment]
When I have some time, I'll validate if this behavior occurs on 8.2.0 also, since all the builds between 8.2.0 and 9.3.3 won't work anymore. I was on a 9.0.1 originally when it was working, but cannot test that version anymore.

**Comment by dgreif** [comment]
@hanlongwang I just tried the `record-example.ts` file on the master branch and it was able to record just fine.  I have never seen anything along the lines of what you have in your logs.  Could you share a sample of the code that you are running this from?

**Comment by hanlongwang** [comment]
Just FYI it works again on 9.3.3, I've never seen this in the past either, just this one instance right after I upgraded to 9.3.3.

Seems like an intermittent that I can't reproduce anymore ATM.

The recording part isn't doing anything fancy:

`      camera.onNewDing.subscribe(async (ding) => {
        if (ding.id_str in dings) {
          return
        }

        dings[ding.id_str] = 1

        const event =
          ding.kind === 'motion'
            ? 'Motion detected'
            : ding.kind === 'ding'
            ? 'Doorbell pressed'
            : `Video started (${ding.kind})`

        console.log(
          `${event} on ${camera.name} camera. Ding id ${
            ding.id_str
          }.  Received at ${new Date()}`
        )
        var dt = datetime.create()
        var filename = '/data/' + dt.format('Ymd_HMS') + '.mp4'
        console.log('Writing to file ' + filename)
        await camera.recordToFile(filename, 60)
        console.log('Done recording video')
      })
`

**Comment by dgreif** [comment]
I really think this was a weird issue coming from the Ring servers yesterday.  Rather than leaving this lay around, I'm going to close it for now and you can re-open it if the issue pops up again
