### ISSUE TITLE
Ability to disconnect RingApi in order to update options

### ISSUE THREAD

**Issue by djm181** [dgreif/ring#378]
# Feature Request

### Description
Once a RingApi instance is set up with a polling interval and refresh token there is no way to have it stop polling or change any of the options associated with the instance. For example if the set of locations to be monitored changes, one cannot change the `options`.

### Describe the solution you'd like
Would like to be able to disconnect the RingApi object and dispose of it so it is no longer polling for dings or active in any way etc, then would simply create a new instance

### Describe alternatives you've considered
Considered restarting the process with new options, but this increases the complexity of the solution as the Ring portion of the application must be hosted in a separate process in order to do this.

**Comment by dgreif** [comment]
@djm181 I think this is a completely valid request.  No promises on timeline as I have been a bit limited on free time lately.  I would be happy to take a PR if you want to dive into the api code.

**Comment by dgreif** [comment]
`api.disconnect()` added in v`9.6.0`
