### ISSUE TITLE
2-Way Audio Slows Down

### ISSUE THREAD

**Issue by dgreif** [dgreif/ring#381]
# Bug Report

### Describe the Bug
Over time, the sound from 2-way audio gets more and more delayed.  

### To Reproduce
 - Start Homebridge
 - Start a live stream
 - Enable mic and start talking

### Expected behavior
Output from camera should stay in-sync with mic input on iPhone

**Comment by dgreif** [comment]
I confirmed with another homebridge developer that this is an issue for homebridge-nest-cam and the starling hub as well.  Most likely an issue with how we are all configuring ffmpeg transcoding, but no clear solution on how to prevent the delay

**Comment by tronny87** [comment]
Fixing this bug would make this plug-in nearly flawless. Good for quick 2-way audio sessions, but gets worse if you're still talking to someone at your door for more than a few seconds!

**Comment by dgreif** [comment]
This seems to be resolved now 🎉
