### ISSUE TITLE
No response when trying to create a token

### ISSUE THREAD

**Issue by jdebardi** [dgreif/ring#382]
# Bug Report

### Describe the Bug
I restarted Homebridge and noted my Ring cameras no longer worked. Found the known 406 issue. Updated to 9.3.4.
Now homebridge nor ring-auth-cli ever seem to get a response, they just sit waiting indefinitely (or silently timeout but don't report an error and keep the program running, not sure which).
Submitting under ring-auth-cli as it's easier to reproduce

### To Reproduce
Just run ring-auth-cli

>ring-auth-cli
This CLI will provide you with a refresh token which you can use to configure ring-client-api and homebridge-ring.
Email: (node:3052) ExperimentalWarning: The dns.promises API is experimental

Same when running via npx;
>npx -p ring-client-api ring-auth-cli
This CLI will provide you with a refresh token which you can use to configure ring-client-api and homebridge-ring.
Email: (node:3052) ExperimentalWarning: The dns.promises API is experimental

### Expected behavior
To get a response

### Screenshots/Logs
Homebridge just prints this which is what makes me assume it is running the ring-auth code, but never see anything else;
Jun 29 09:00:01 jose-stick homebridge[32630]: [6/29/2020, 9:00:01 AM] [Ring] Initializing Ring platform...
Jun 29 09:00:01 jose-stick homebridge[32630]: (node:32630) ExperimentalWarning: The dns.promises API is experimental

### Additional context
There is no issue reported on status.ring.com at this time

### Environment
 - OS: Ubuntu 16.04.5 LTS
 - Node.js: v11.3.0
 - NPM: 6.4.1
 - ring-client-api: 9.3.4

**Comment by dgreif** [comment]
It is possible that your client got rate limited.  You should try logging in from the web application at ring.com on the same network.  If you are able to log in there, then try again with ring-auth-cli.  Otherwise, wait 24 hours and then try again.

**Comment by jdebardi** [comment]
So I realised that the 'Email:' was a prompt to enter my credentials but was obscured by the Experimental warning.
I enter my email/password, however the script then dies a few seconds later and doesn't wait for me to enter the 2FA code that I receive via email.
So still a bit stumped!
Homebridge still doesn't register anything - not sure if the token has expired now give it's not been used for a while. There's no debug to go on (unless there is more I can turn on?).

**Comment by dxdc** [comment]
@jdebardi is your dns working properly? You can try `dig ring.com` for example from your server. Also, try logging out/in from the actual Ring.com app and then try this process again.

> ExperimentalWarning: The dns.promises API is experimental
@dgreif maybe an issue with `cacheable-lookup`?

> https://github.com/nodejs/node/issues/21930
> https://github.com/szmarczak/cacheable-lookup/blob/master/source/index.js

**Comment by jdebardi** [comment]
@dxdc DNS is fine. The server does lots of other things for me so I’d know if it had a connectivity issue.

I’ve also updated all NPM packages to latest and still no joy.

Given someone else has reported similar in the last couple of days I’m thinking maybe it’s a recent change on Ring’s side.

**Comment by dgreif** [comment]
@jdebardi did you ever get this working?  If not, you might want to try updating to node 12.18.2 (latest LTS).

**Comment by dxdc** [comment]
@jdebardi 

Not sure if related, but agree with @dgreif maybe related to your Node version.

> make dns.promises enumerable (cjihrig) #26592
> remove dns.promises experimental warning (cjihrig) #26592

See: https://nodejs.org/en/blog/release/v11.14.0/

**Comment by dgreif** [comment]
I just tried the auth cli with node `11.3.0` and saw the exact behavior described in this issue.  Updating to node `11.14.0` or `12.18.2` fixes the issue.  Thanks for tracking down the dns change @dxdc.  Closing since this is a user environment issue.

**Comment by jdebardi** [comment]
Thanks both for your help! I plan to rebuild my whole homebridge environment in a docker on my Synology NAS shortly so I'll just wait til I do that to get it working rather than faff with my very delicate Intel Compustick install (something always goes wrong when I mess with node!). Thanks again.
