### ISSUE TITLE
iOS 14 HomeKit Facial Recognition 

### ISSUE THREAD

**Issue by tronny87** [dgreif/ring#385]
A neat idea, but I'm not sure if it can be implemented. They announced facial recognition for HomeKit cameras would become available in iOS 14, however I'm not sure if that is restricted exclusively to cameras that support HomeKit Secured Video.

Just throwing the idea out there!

**Comment by dgreif** [comment]
It’s definitely a cool new feature! From everything we have seen, it will be restricted to HomeKit secure video. HSV is not yet supported by homebridge, and it is unlikely I will be able to add HSV support any time soon. Maybe some day, but for now it’s simply not possible
