### ISSUE TITLE
Snapshot Issues

### ISSUE THREAD

**Issue by sixteenpaws** [dgreif/ring#386]
On v9.3.5

After the doorbell (Ring Doorbell 2) has a motion alert it is unable to retrieve a snapshot. Eventually, get these errors:
`[6/30/2020, 9:08:07 AM] [Ring] Snapshot failed to refresh after 70 attempts`
`[6/30/2020, 9:08:07 AM] [Ring] Snapshot failed to refresh after 70 attempts`
`[6/30/2020, 9:08:07 AM] [Ring] Snapshot failed to refresh after 70 attempts`
`[6/30/2020, 9:08:07 AM] [Ring] Snapshot failed to refresh after 70 attempts`
`[6/30/2020, 9:08:07 AM] [Ring] Failed to cache snapshot for Front Door (41.601s), The camera currently reports that is it online`
`[6/30/2020, 9:08:07 AM] [Ring] Failed to cache snapshot for Front Door (41.589s), The camera currently reports that is it online`
`[6/30/2020, 9:08:07 AM] [Ring] Failed to cache snapshot for Front Door (41.588s), The camera currently reports that is it online`
`[6/30/2020, 9:08:07 AM] [Ring] Failed to cache snapshot for Front Door (41.41s), The camera currently reports that is it online`

I am able to live view easily and quickly, but snapshots have not worked.

**Comment by dgreif** [comment]
This is common behavior for battery cameras.  Please read https://github.com/dgreif/ring/wiki/Snapshot-Limitations for a full description.  If you are unable to _ever_ fetch snapshots, then I suggest you try getting a snapshot through the Ring app and see if it works there.  If it doesn't, then pull the battery out of the camera and put it back in.

**Comment by sixteenpaws** [comment]
Thanks for the response, but the doorbell is not on battery power.

**Comment by dgreif** [comment]
If the camera _has_ a battery, then it behaves as a battery camera with snapshots, even if it is plugged into power

**Comment by sixteenpaws** [comment]
Oh. I didn’t realize that. So there is no way, with the Ring Doorbell 2, to get the functionality of a wired device?

**Comment by dgreif** [comment]
Nope, this is a limitation that Ring puts on the cameras

**Comment by sixteenpaws** [comment]
Well that’s a shame. Thanks.
