### ISSUE TITLE
location.getDevices() stalls under certain conditions

### ISSUE THREAD

**Issue by jasonparekh** [dgreif/ring#388]
# Bug Report

### Describe the Bug
The `example.ts` script was hanging after logging the "Connected to location" message. I traced through the code and found that it stalls at the `await location.getDevices()` because the message received for `DeviceInfoDocGetList` doesn't pass some of the criteria that's currently required to return data for `getDevices`.

### To Reproduce
 - I'm not sure what in my set up is causing the issue. I have a single location with 9 cameras and an offline Ring Alarm base station without any sensors ever connected.
 - Attempt to run example.ts script.
 - Notice it never gets past the "Connected to location" message.

### Expected behavior
- Runs to completion listing the 9 cameras.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
Here's the `DeviceInfoDocGetList` message I get back (IDs redacted):
```
{"msg":"DeviceInfoDocGetList","seq":1,"dst":"aaaa","sessionId":2,"status":-66,"context":{"uiConnection":{"userUuid":"3","accountPermissions":["hub:connect","room:read","masterkey:create","device-state:configure","asset:read","device:create","rule:read","rule:create","beams-device:update","ringnet-security:create","security-user:enable","beams-device:delete","access-code:update","location:update","security-panel:disarm","beams-device:read","room:update","beams-bridge:delete","location-user:read","room:create","monitoring-permit:update","location-user:delete","beams-group:delete","rule:update","mode-settings:update","ringnet-device:create","rule:delete","security-user:disable","ringnet-packet:update","beams-device:create","security-panel:arm","monitoring-settings:update","user.summary:read","asset-command:send","access-code:create","monitoring-settings:read","device-profile:read","beams-group:read","beams-bridge:create","beams-group:create","beams-bridge:read","monitoring-permit:read","rule-list:read","device-profile:update","room:delete","history:read:location","device:delete","location:read","location:delete","device-state:control","beams-bridge:update","location-user-list:read","location-user:update","beams-firmware:read","mode:update","mode:read","beams-group:update","rule:activate","masterkey:read","access-code:delete","location-user:create","alarm-action:send"],"ipAddress":"4.4.4.4","userAgent":"","userPermissions":[]}}}
```

### Environment
 - OS: Windows and Linux
 - Node.js: 12.18.2
 - NPM: 6.14.5
 - ring-client-api: 9.3.5

**Comment by dgreif** [comment]
The offline alarm base station is the reason it hangs. If you have no intention of using it, the easiest fix would be to remove the alarm from Ring. If the base station is offline, you can’t interact with it and get the device list from it, so I wait for all base stations to come online before reporting the full device list.

**Comment by dgreif** [comment]
Did that info solve it for you @jasonparekh?

**Comment by dgreif** [comment]
Closing due to lack of response.  This is working as intended

**Comment by Darrilla** [comment]
@dgreif I ran into this myself, and I don't see a good way to fix it, other than a local timeout in my code.  However, when the base station is offline or on backup cellular, this also prevents me from discoverying other devices, such as sensors, that are in the account. I can find the cameras and doorbells, but not the sensors (because of the offline base station). Is there any plan to fix this?

**Comment by Darrilla** [comment]
I understand that this is important, however I'd like to still discover other controllable devices - and proceed as if there is no hub or base station. I can always come back in later and do another discovery if the controller is not available.

**Comment by tsightler** [comment]
The code is there for you to do as you wish, feel free to submit non-breaking PRs for review.
