### ISSUE TITLE
A text notification instead of the video notification

### ISSUE THREAD

**Issue by sergoo-lbt** [dgreif/ring#392]
Recently started having problems with notifications. After clicking the button on the ring, you will receive an app notification, but without a video. Just a text notification. Sometimes, it is not clear why you receive a notification with a video, but more often just a text - the doorbell rang.
Ver. Plugin 9.4.0. 
![73BB39D0-F29D-4992-A69C-AE60EB2A8DA1](https://user-images.githubusercontent.com/64399012/86527815-dfbba580-bebb-11ea-90dd-c1f214ebced3.png)
![2A80C708-6ABB-4602-97FF-AF703B909AE3](https://user-images.githubusercontent.com/64399012/86527818-e6e2b380-bebb-11ea-96ed-5fbe3323b452.png)

**Comment by dgreif** [comment]
What type of camera do you have?  If it has a battery (even if you have it wired), it usually won't have a snapshot in the notification.  You can find more info in the wiki: https://github.com/dgreif/ring/wiki/Snapshot-Limitations

**Comment by sergoo-lbt** [comment]
> What type of camera do you have? If it has a battery (even if you have it wired), it usually won't have a snapshot in the notification. You can find more info in the wiki: https://github.com/dgreif/ring/wiki/Snapshot-Limitations

I have a ring V. 1.everything used to work as expected. Both the photo and video were in the notification. I tried to delete the plugin, reset the ring to factory settings, all without success. Now I will install the version of the plugin ring 9.3.4. I will Try. I don't know what to do next...

**Comment by dgreif** [comment]
Yeah, installing 9.3.4 is a good next step.  I did change some of the logic around snapshots between 9.3.4 and 9.4.0 so it's possible I introduced a bug related to notification snapshots.  Let me know how it goes with 9.3.4

**Comment by dgreif** [comment]
Can you post some logs from your homebridge server?  I log a fair amount of info about snapshots and motion events.  Might be some useful details in there

**Comment by sergoo-lbt** [comment]
> Can you post some logs from your homebridge server? I log a fair amount of info about snapshots and motion events. Might be some useful details in there

I still think the problem is on my side. Now I have installed 9.3.4, and I still can't turn on the video when I get a call at the door. It used to look like this screenshot.
![EE821654-2FBB-4D81-B434-03B2B45BE165](https://user-images.githubusercontent.com/64399012/86534928-14e4e980-bef6-11ea-8a46-32874c9f2bd9.png)

**Comment by dgreif** [comment]
Looking at the logs is definitely the next step. You can also check to see if snapshots are working if you just look at the cameras in the Home app, or in the Ring app

**Comment by sergoo-lbt** [comment]
> Looking at the logs is definitely the next step. You can also check to see if snapshots are working if you just look at the cameras in the Home app, or in the Ring app

Unfortunately, I can't copy a beautiful log for you because I'm not at home. But snapshots and live broadcasts work both in the Home app and in the ring app. The only problem is getting a normal notification.

**Comment by dgreif** [comment]
> I have a ring V

I'm still not clear on which camera you have. Does it have a battery in it?

**Comment by sergoo-lbt** [comment]
> I'm still not clear on which camera you have. Does it have a battery in it?

Excuse me. I have a ring of the first version.

**Comment by dgreif** [comment]
Ok, the first version has a battery built into it.  This means it falls into the "battery" category (even if it is wired).  On battery cams, a snapshot cannot be taken while recording is in progress, which is why you don't see a snapshot in the motion notifications.  You may occasionally see a snapshot in one if a snapshot was taken in the last 2 minutes, but it will never be a "current" snapshot of what was in front of the camera at the time that motion/ding was detected.  This is a limitation from Ring that I cannot get around.

**Comment by sergoo-lbt** [comment]
> Ok, the first version has a battery built into it. This means it falls into the "battery" category (even if it is wired). On battery cams, a snapshot cannot be taken while recording is in progress, which is why you don't see a snapshot in the motion notifications. You may occasionally see a snapshot in one if a snapshot was taken in the last 2 minutes, but it will never be a "current" snapshot of what was in front of the camera at the time that motion/ding was detected. This is a limitation from Ring that I cannot get around.

I was concerned about the notification about the call and not about the movement.?

**Comment by dgreif** [comment]
If by "call", you mean someone pressing the button on the doorbell, then it behaves exactly the same way.  When they push the button, the camera starts recording, which blocks a snapshot from being taken.

**Comment by sergoo-lbt** [comment]
> If by "call", you mean someone pressing the button on the doorbell, then it behaves exactly the same way. When they push the button, the camera starts recording, which blocks a snapshot from being taken.

Exactly! Previously, when someone clicked a button, a notification came, I made a long tap on this notification and it opened a live stream. Now it won't happen? I'm already confused, sorry.

**Comment by dgreif** [comment]
It won't start a live stream because there is no snapshot attached to the notification.  There is no snapshot because it is a battery camera.  You can just tap on the notification to open the home app instead of doing a long tap.

**Comment by sergoo-lbt** [comment]
> It won't start a live stream because there is no snapshot attached to the notification. There is no snapshot because it is a battery camera. You can just tap on the notification to open the home app instead of doing a long tap.

But a few days ago, everything worked through a long click?! And there were notifications with a picture ... Ehh. I'm sad...
![CA81965C-2716-4AF4-A628-26197997FF1F](https://user-images.githubusercontent.com/64399012/86536837-3c42b300-bf04-11ea-8c8f-4747ef94965f.png)

**Comment by sergoo-lbt** [comment]
@dgreif , I understand you. Thank you very much for the clarification! Please tell me, is there any way to leave my snapshot image, even if it is not up-to-date instead of saying snapshot blocked?

**Comment by dgreif** [comment]
@sergoo-lbt the "snapshots blocked" image shows when you have your location modes set such that a snapshot cannot be captured, meaning motion detection is disabled.
