### ISSUE TITLE
Unabel to Add Ring Devices to Home App with HOOBS

### ISSUE THREAD

**Issue by cbarnhart76** [dgreif/ring#395]
Hello,

I have been trying to get my HOOBS to add the Ring devices for several days now. 

I have removed the HOOBS bridge from the Home app, restored the HOOBS to factory settings, reinstalled Nest plugin (that works like it should), reinstalled Ring plugin with updated refresh token. Still not seeing the Ring devices in the Home app or in the devices section of HOOBS.
Latest log below,

10:54:14 AM + homebridge-ring@9.4.1 added 192 packages from 142 contributors in 44.629s 7/8/2020, 
10:54:15 AM 24 packages are looking for funding run `npm fund` for details7/8/2020, 
10:54:15 AM Plugin "homebridge-ring" installed.7/8/2020, 
10:54:15 AM Got SIGINT, shutting down Bridge...7/8/2020, 
10:54:21 AM Loaded plugin "homebridge-nest".7/8/2020, 
10:54:24 AM Loaded plugin "homebridge-ring".7/8/2020, 
10:54:24 AM [Nest] Fetching Nest devices.7/8/2020, 
10:54:24 AM (node:13060) UnhandledPromiseRejectionWarning: Error: Refresh token is not valid. Unable to authenticate with Ring servers. See https://github.com/dgreif/ring/wiki/Refresh-Tokens7/8/2020, 
10:54:24 AM at RingRestClient.getGrantData (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:118:15)7/8/2020, 
10:54:24 AM at RingRestClient.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:122:36)7/8/2020, 
10:54:24 AM at Generator.next (<anonymous>)7/8/2020, 
10:54:24 AM at /home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:27:717/8/2020, 
10:54:24 AM at new Promise (<anonymous>)7/8/2020, 
10:54:24 AM at __awaiter (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:23:12)7/8/2020, 10:54:24 AM at RingRestClient.getAuth (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:121:16)7/8/2020, 
10:54:24 AM at new RingRestClient (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:98:33)7/8/2020, 
10:54:24 AM at new RingApi (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/api.js:24:27)7/8/2020, 
10:54:24 AM at RingPlatform.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:135:29)7/8/2020, 
10:54:24 AM (node:13060) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)7/8/2020, 
10:54:24 AM (node:13060) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.7/8/2020, 
10:54:24 AM [Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed with status undefined. Response body: undefined7/8/2020, 
10:54:24 AM [Ring] Error connecting to API7/8/2020, 
10:54:24 AM [Ring] Error: Refresh token is not valid. Unable to authenticate with Ring servers. See https://github.com/dgreif/ring/wiki/Refresh-Tokens at RingRestClient.getGrantData (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:118:15) at RingRestClient.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:122:36) at Generator.next (<anonymous>) at /home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:27:71 at new Promise (<anonymous>) at __awaiter (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:23:12) at RingRestClient.getAuth (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:121:16) at new RingRestClient (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:98:33) at new RingApi (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/api.js:24:27) at RingPlatform.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:135:29)7/8/2020, 
10:54:24 AM (node:13060) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)7/8/2020, 
10:54:28 AM [Nest] initing thermostat "Hallway Thermostat": deviceId: XXXXXXXXXXXX0K3Z structureId: 3ff7fa10-XXXX-XXX-XXXX-XXXXXXX 7/8/2020, 
10:54:28 AM [Nest] initing home_away_sensor "Home Occupied": deviceId: 3ff7fa10-XXXX-XXX-XXXX-XXXXXXX structureId: 3ffXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX 7/8/2020, 
10:54:28 AM [Nest] Initializing platform accessory "Hallway Thermostat"...7/8/2020, 
10:54:28 AM [Nest] Initializing platform accessory "Home Occupied"...7/8/2020, 10:54:55 AM Bridge is running on port 51826.7/8/2020, 
10:59:27 AM Got SIGINT, shutting down Bridge...7/8/2020, 
10:59:33 AM Loaded plugin "homebridge-nest".7/8/2020, 
10:59:35 AM Loaded plugin "homebridge-ring".7/8/2020, 
10:59:35 AM [Nest] Fetching Nest devices.7/8/2020, 
10:59:37 AM [Ring] Creating location socket.io connection7/8/2020, 
10:59:37 AM [Ring] Ring connected to socket.io server7/8/2020, 
10:59:37 AM [Ring] Ring beams_bridge_v1 XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX1a98 is offline or on cellular backup. Waiting for status to change
7/8/2020, 1:30:11 PM [Ring] Creating location socket.io connection
7/8/2020, 1:30:11 PM [Ring] Ring connected to socket.io server
7/8/2020, 1:30:11 PM [Ring] Ring beams_bridge_v1 XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX1a98 is offline or on cellular backup.  Waiting for status to change

**Comment by dgreif** [comment]
Looks like your beams bridge is offline.  The plugin waits for all bridges to come online so that it can get a complete list of devices.  Either bring your beams bridge back online or remove it from your Ring account

**Comment by cbarnhart76** [comment]
> Looks like your beams bridge is offline. The plugin waits for all bridges to come online so that it can get a complete list of devices. Either bring your beams bridge back online or remove it from your Ring account

Thank you,

That was the issue. I had the Ring Smart Lighting Bridge disconnected wile finishing the room it was in.
