### ISSUE TITLE
cannot install update 9.3.3

### ISSUE THREAD

**Issue by koweye** [dgreif/ring#402]
# Bug Report

### Describe the Bug
i am running HOOBS 3.2.6 and i see there is an update to the ring plug in to 9.3.3, when i click on update, it seems like it updates, restarts the service, but then when i go back into the plugin screen the ring plugin still shows as there is an update

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
i expect that when i select update, it will update the plug in and not say that there is still an update

### Screenshots/Logs
7/11/2020, 4:44:10 PM [Ring] Configuring cached accessory e18423f1-8a95-460f-8b13-4f5313c7286e Ring Alarm
7/11/2020, 4:44:10 PM [Ring] Configuring cached accessory 2c369f3b-ae30-468b-b9b3-2d2d8be3a282 Base Station
7/11/2020, 4:44:10 PM [Ring] Configuring cached accessory e56752ae-c7a2-4165-9fb8-6672eb00ec57 Bedroom (Middle) Sensor 35929
7/11/2020, 4:44:10 PM [Ring] Configuring cached accessory c1c117cf-aec5-4bb4-89eb-26b20b5bee2a Front Door Sensor 60377
7/11/2020, 4:44:10 PM [Ring] Configuring cached accessory 10a97f3e-4a07-45cb-82b5-db0b4ca00618 Bedroom (Front) Sensor 39675
7/11/2020, 4:44:10 PM [Ring] Configuring cached accessory c38e1228-eae1-488d-94e8-0a5d584554c3 Garage Entry Door Sensor 18306
7/11/2020, 4:44:10 PM [Ring] Configuring cached accessory 47a28881-0329-46d2-b4f6-ea9b170c4cae Living Room Motion Sensor 34637
7/11/2020, 4:44:10 PM [Ring] Configuring cached accessory 8a082460-aefa-4b43-b947-1b7d5bdeed98 Family Room Sliding Door 07623
7/11/2020, 4:44:10 PM [Ring] Configuring cached accessory 332f5d76-75cb-4ab7-933b-b1b7b6a819b2 Bedroom (Master) Sensor 08891
7/11/2020, 4:44:10 PM [Ring] Configuring cached accessory 922d397d-e0ef-4e59-bd93-81b4f946910e Ring Keypad
7/11/2020, 4:44:14 PM [Ring] Creating location socket.io connection
7/11/2020, 4:44:15 PM [Ring] Ring connected to socket.io server
7/11/2020, 4:44:15 PM [Ring] Configuring 0 cameras and 15 devices for location "My Ring Home" - locationId: 87zdjn-dq8i-0
7/11/2020, 4:44:15 PM [Ring] Hidden accessory bfa528c8-35a9-4d80-94e2-118694af6427 adapter.zigbee ZigBee onboard adapter
7/11/2020, 4:44:15 PM [Ring] Hidden accessory eb0edcd4-11ce-483f-b242-886ae7418f76 access-code.vault Code Vault
7/11/2020, 4:44:15 PM [Ring] Hidden accessory da5785c8-0914-4fba-9185-740c5b5bdc36 access-code Security Access Code
7/11/2020, 4:44:15 PM [Ring] Hidden accessory 2c369f3b-ae30-468b-b9b3-2d2d8be3a282 hub.redsky Base Station
7/11/2020, 4:44:15 PM [Ring] Hidden accessory ad5ee297-ecd1-4d23-8c56-d84260d7ce29 adapter.zwave Z-Wave Adapter
7/11/2020, 4:44:15 PM [Ring] Hidden accessory eb5453d1-01f5-4a8a-8993-caf7ba57a30f range-extender.zwave Ring Z-Wave Extender 50821
7/11/2020, 4:44:15 PM [Ring] Hidden accessory 922d397d-e0ef-4e59-bd93-81b4f946910e security-keypad Ring Keypad
7/11/2020, 4:44:15 PM [Ring] Removing stale cached accessory 2c369f3b-ae30-468b-b9b3-2d2d8be3a282 Base Station
7/11/2020, 4:44:15 PM [Ring] Removing stale cached accessory 922d397d-e0ef-4e59-bd93-81b4f946910e Ring Keypad

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
The latest version of the Ring plugin is 9.5.0. If you do not see that as an update option, then there is a bug in HOOBS. I suggest you open an issue with them and they should be able to help you get it updated
