### ISSUE TITLE
Ability to Hide Chime

### ISSUE THREAD

**Issue by MrMathlete** [dgreif/ring#403]
# Bug Report

### Describe the Bug
Not able to hide chimes using the "hideDeviceIds" function as they do not generate an ID

### To Reproduce
Open HomeBridge log
Search for chime
Attempt to locate ID

### Expected behavior
Find and then copy ID to Config Editor to hide chimes

### Screenshots/Logs
[37m[6/18/2020, 12:46:27 PM] [39m[36m[Ring] [39mAdding new accessory chime_pro Kitchen
[37m[6/18/2020, 12:46:27 PM] [39m[36m[Ring] [39mAdding new accessory chime Loft
[37m[6/18/2020, 12:46:27 PM] [39m[36m[Ring] [39mAdding new accessory chime Garage

### Additional context
N/A

### Homebridge Ring Config
"refreshToken": "xxx",
            "hideLightGroups": true,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "hideDeviceIds": [
                "xxx",
            ],
            "platform": "Ring"

### Environment
 - OS: Windows 10 64 bit
 - Node.js: 12.16.1
 - NPM: 6.14.5
 - homebridge-ring: 9.5.0
 - homebridge: 1.1.1

**Comment by dgreif** [comment]
If you restart your homebridge server, you should see a log that looks like this for each of those chimes:

```
[Ring] Configuring cached accessory xxxx-xxxxxxx Kitchen
```

The xx value here is the id that you need for `hideDeviceIds`.  Ironically I did add the id to the `Adding new accessory` output in `9.5.0` so you must have pulled those logs from a previous version

**Comment by MrMathlete** [comment]
Thank you! I have the chime devices named the same as the cameras because it differentiates them in the Ring UI. Updated my naming convention and restarted HomeBridge and am now good to go. Appreciate the support and everything you do to keep my home happy and automated.
