### ISSUE TITLE
ring-client-api not found in NPMJS.org registry

### ISSUE THREAD

**Issue by jeroenterheerdt** [dgreif/ring#407]
# Bug Report

### Describe the Bug
cannot create refresh token on Windows 10, errors with: 
```
C:\dev\ring [master ≡ +13 ~0 -0 !]> npx -p ring-clent-api ring-auth-cli
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/ring-clent-api - Not found
npm ERR! 404
npm ERR! 404  'ring-clent-api@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
### To Reproduce
- run `npx -p ring-client-api ring-auth-cli`

### Expected behavior
Being able to create a refresh token

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Environment

 - OS: Windows 10
 - Node.js: 12.18.0
 - NPM: 6.14.6
 - ring-client-api: most recent from github

**Comment by dgreif** [comment]
You have a typo `npx -p ring-clent-api ring-auth-cli` -> `npx -p ring-client-api ring-auth-cli`

**Comment by jeroenterheerdt** [comment]
wow, massive user error here. fixed the typo and ended up with another error: 
![image](https://user-images.githubusercontent.com/8188990/87466278-da044500-c5ca-11ea-974a-e0a36747b4ff.png)
Command I ran: `npx -p ring-client-api ring-auth-cli`. Same environment.

**Comment by dgreif** [comment]
That looks like you may have the repo cloned and linked locally.  Try running that command on a different computer

**Comment by jeroenterheerdt** [comment]
thanks - I removed the repo locally and got it working... weird though.
