### ISSUE TITLE
ERR_INVALID_ARG_TYPE after some time on ring-hassio add-on

### ISSUE THREAD

**Issue by jeroenterheerdt** [dgreif/ring#408]
# Bug Report

### Describe the Bug
In the ring-hassio add-on I am getting a `ERR_INVALID_ARG_TYPE` error after some time. I know this is not the repo for it, and it is my own add-on, but I am sure where to start looking. Packages are up to date. Just wondering if this is something you have seen before or where this could come from. Have not seen it in previous versions.

```
/ring-hassio/ring_hassio/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object
    at Object.unlinkSync (fs.js:1126:10)
    at SafeSubscriber._next (/ring-hassio/ring_hassio/livestream.js:202:28)
    at SafeSubscriber.__tryOrUnsub (/ring-hassio/ring_hassio/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/ring-hassio/ring_hassio/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/ring-hassio/ring_hassio/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/ring-hassio/ring_hassio/node_modules/rxjs/internal/Subscriber.js:66:18)
    at ReplaySubject.Subject.next (/ring-hassio/ring_hassio/node_modules/rxjs/internal/Subject.js:60:25)
    at ReplaySubject.nextInfiniteTimeWindow (/ring-hassio/ring_hassio/node_modules/rxjs/internal/ReplaySubject.js:48:31)
    at SipSession.callEnded (/ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/sip-session.js:177:33)
    at SipSession.stop (/ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/sip-session.js:186:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### To Reproduce
start ring-hassio addon.

### Expected behavior
no errors :)

### Environment
Home Assistant

**Comment by dgreif** [comment]
It's probably because you just deleted your local copy of the `ring` repo and you had it in an `npm link`.  Try running `npm unlink ring-client-api` in your `ring_hassio` folder

**Comment by jeroenterheerdt** [comment]
no, sorry, it is not on the same environment. The ring-hassio component for HA just starts this code: https://github.com/jeroenterheerdt/ring-hassio/blob/master/ring_hassio/livestream.ts, so I am wondering where this originates from as I don't see a reference to that code in the stack trace...

**Comment by dgreif** [comment]
`at SafeSubscriber._next (/ring-hassio/ring_hassio/livestream.js:202:28)` -> https://github.com/jeroenterheerdt/ring-hassio/blob/master/ring_hassio/livestream.js#L202

Looks like the .js file isn't necessarily up to date with the .ts file.  You need to recompile the typescript file to generate a new js version of it.

**Comment by dgreif** [comment]
Closing as this isn't an issue with the ring client api

**Comment by jeroenterheerdt** [comment]
so I recompiled the .js file, but the issue still exists. What can cause this? I am not seeing anything except: "The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object", but I am not even sure how the .ts file even relates to this.

**Comment by dgreif** [comment]
the `.js` file is generated when you run `tsc` to compile the `.ts` file.  The normal flow would be that you make changes in the `.ts` file and then compile it and run the generated `.js` file.  You shouldn't be making changes in the `.js` file.

**Comment by jeroenterheerdt** [comment]
sorry, that's what I meant - I have run `tsc livestream.ts` to get a new `js` file. I have not edited the `js` file.

**Comment by dgreif** [comment]
it looks like the `livestream.js` file has been updated and no longer has the `unlinkSync` call in it (it is commented out).  I would assume you shouldn't be receiving that same error anymore.  Maybe post a stack trace or the new error?

**Comment by jeroenterheerdt** [comment]
weird, error is gone now.
