### ISSUE TITLE
Device ID - Hide Chime from Homekit

### ISSUE THREAD

**Issue by thrangster** [dgreif/ring#409]
# Bug Report

### Describe the Bug
 I am unable to locate/understand what is the Device ID for Ring devices to be able to hide the Chime from Homekit - there seems to be no reason to having someone ringing the door chime from within the Home app

### Expected behavior
 To be able to hide all instances of the Chime.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 I tried adding the AID and IID separately, as well as the serial number and Homebridge Instance username in the Hidden Device ID field in option config, to no avail

### Homebridge Ring Config
"refreshToken": "xxxxxx",
            "hideDoorbellSwitch": true,
            "hideCameraMotionSensor": false,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "debug": true,
            "hideDeviceIds": [
                "9"
            ],
            "platform": "Ring"
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [OS X 10.16
 - Node.js: 12.18.2
 - NPM: 6.14.5
 - homebridge-ring: 9.6.0
 - homebridge: NA
 - hoobs: NA

**Comment by dgreif** [comment]
Sorry the logs are more explicit about which value to use for the device id when hiding.  If you restart your homebridge server, your logs should contain a number of lines that look like this:

```
[Ring] Configuring cached accessory 0afca478-5483-4077-a1ad-xxxxxxxxxxx CHIME NAME HERE
```

You need to locate the line that has a name matching what you have set for your chime in the Ring app.  Then the id is the value like `0afca478-5483-4077-a1ad-xxxxxxxxxxx`

**Comment by thrangster** [comment]
Thank you - so I restarted Homebridge and there is not one RING entry at all as described (I swear)

When I load Home on my iPhone, I start to see these Ring entries (interspersed with others):

> [7/17/2020, 15:52:38] [Ring] No snapshot cached for Front Door
> [7/17/2020, 15:52:38] [Ring] Loading new snapshot into cache for Front Door
> [7/17/2020, 15:52:39] [Home Alarm] Handling camera snapshot for 'Hallway' at 1280x720
> [7/17/2020, 15:52:39] [Ring] Snapshot cached for Front Door (1.375s)
> [7/17/2020, 15:52:42] [Home Alarm] Closed 'Hallway' snapshot request with 63kB image
> [7/17/2020, 15:52:42] [Ring] Used cached snapshot for Front Door
> [7/17/2020, 15:52:49] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":257,"sid":"uuid:154","control":"_0","action":120,"node":"","eventInfo":""}
> [7/17/2020, 15:52:52] [Home Alarm] Handling camera snapshot for 'Hallway' at 1280x720
> [7/17/2020, 15:52:56] [Home Alarm] Closed 'Hallway' snapshot request with 64kB image
> [7/17/2020, 15:52:56] [Ring] Used cached snapshot for Front Door
> [7/17/2020, 15:52:56] [Ring] Loading new snapshot into cache for Front Door
> [7/17/2020, 15:52:57] [Ring] Snapshot cached for Front Door (1.386s)

I have Debug mode on for the Ring plug in and Homebridge.

So it's working - just no device ID entries on boot - I've never seen it, or I wouldn't have even posted here as I (Hopefully) would have figured that out.

Thanks

**Comment by dgreif** [comment]
I think you just need to look a bit further back in your logs.  _Before_ the QR code is logged out, you should have a line that says `[Ring] Initializing Ring platform...`.  Immediately following that, the cached accessories will be logged.  If you aren't seeing those logs, then it may be an issue with your logging setup since those logs should alway be present (even without the debug flag)

**Comment by thrangster** [comment]
Thanks for the response... but there are no Ring entries in the log at all until I start previewing a camera in Home. None.

I’ve scrolled back to the beginning on the main screen, and have done the same in the GUI log window.

If the log accessed via terminal (more verbose) is different, I could check, but not sure how to read/poem it via terminal if possible

Thanks again

**Comment by dgreif** [comment]
Are you rubbing HOOBS or homebridge? And which version?  There should absolutely be logs during plugin initialization so there is something funky in your setup

**Comment by thrangster** [comment]
Homebridge - 

This is how the log starts...

Loading logs using native method...
File: /var/lib/homebridge/homebridge.log

ed 'Hallway' snapshot request with 17kB image
[7/20/2020, 07:22:49] [Home Alarm] Closed 'Hallway' snapshot request with 17kB image
[7/20/2020, 07:22:49] [Home Alarm] Closed 'Hallway' snapshot request with 65kB image
[7/20/2020, 07:23:12] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":1993,"sid":"uuid:155","control":"_0","action":120,"node":"","eventInfo":""}
[7/20/2020, 07:23:24] [Home Alarm] Alarm received event: ALARM_DISARM
[7/20/2020, 07:23:37] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":1994,"sid":"uuid:155","control":"_0","action":120,"node":"","eventInfo":""}
[7/20/2020, 07:24:02] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":1995,"sid":"uuid:155","control":"_0","action":120,"node":"","eventInfo":""}
[7/20/2020, 07:24:27] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":1996,"sid":"uuid:155","control":"_0","action":120,"node":"","eventInfo":""}
[7/20/2020, 07:24:52] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":1997,"sid":"uuid:155","control":"_0","action":120,"node":"","eventInfo":""}
[7/20/2020, 07:25:17] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":1998,"sid":"uuid:155","control":"_0","action":120,"node":"","eventInfo":""}
[7/20/2020, 07:25:42] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":1999,"sid":"uuid:155","control":"_0","action":120,"node":"","eventInfo":""}

Homebridge:

OS | Raspbian GNU/Linux Buster (10)
-- | --
homebridge
xxx.xxx.xxx.xxx
zzzz::zzzz:zzzz:zzzz:zzzz
Nodejs - v12.18.1
NPM v6.14.5
user: pi
/var/lib/homebridge
/var/lib/homebridge/config.json
Service Mode:
Yes

Plug ins are:

Homebridge Config UI X
homebridge-config-ui-x v4.23.2

Homebridge Ring
homebridge-ring v9.6.0

Homebridge ISY
homebridge-isy v0.5.0-rc22

Homebridge Simplisafe3
homebridge-simplisafe3 v1.6.7

Homebridge Debug Mode -D ON
Homebridge Insecure Mode / Enable Accessory Control -I ON 


Ring Debug Loggng On

**Comment by dgreif** [comment]
Based on what I have seen of your logs, the method you are using to view them appears to only show the last ~10 lines, which is why you aren't seeing the output that you need.  You will need to figure out how to view more than just the last 10 lines.  This is all dependent on how you have your service set up, but in my setup it's something like this:

Show last 10 lines: `sudo systemctl status homebridge`
Show all logs, starting with latest: `journalctl -u homebridge -r`

**Comment by thrangster** [comment]
Sorry, I only included a snippet to not flood the thread... the log is much longer, though does roll out the oldest entries after some time - again, this is the log in the GUI not terminal if there is a verbose difference

So I reboot Homebridge from the menu, and look at the log as it starts.... and for as long as it runs there are no entries as you describe. Tons of ISY entries, many Home Alarm (SimpliSafe) entries, but nothing for Ring until I start viewing a camera in Home (thumbnail or live view)

Does a hard reboot matter (pulling power) vs a soft reboot when it comes to the startup and logs?

Thanks

**Comment by dgreif** [comment]
No, soft restart should be fine.  One option would be to turn off those other plugins since they seem to be flooding the logs.  Main downside is you would likely lose your automations for those accessories if HomeKit sees that they have been removed.  Alternatively, you could spin up another homebridge instance with just ring.  You mainly need to be looking for `[Ring] Initializing Ring platform...`, which is something that homebridge _always_ logs, so if you can't see it, then your logs are getting dumped before you get to them.

**Comment by thrangster** [comment]
perhaps = I'll try setting it up on my Mac just with ring... thanks

**Comment by dgreif** [comment]
@thrangster did you get this figured out?

**Comment by dgreif** [comment]
Closing due to lack of response.  Let me know if you have an update.
