### ISSUE TITLE
Please add error handler in api\ffmpeg.js to prevent uncatchable exceptions

### ISSUE THREAD

**Issue by Apollon77** [dgreif/ring#411]
# Bug Report

### Describe the Bug
We use your library in one of our ioBroker adapter and we see several uncatchable crashes:

Error [ERR_STREAM_DESTROYED] doWrite(_stream_writable): 

... in this case there seems to be cases where a call to "start" on ffmpeg on a closed stdin. I think it would be an idea to add error handlers on stdin.

We use 8.x version here, but I checked and that code part was basically not changed in later versions.

### To Reproduce
I can not tell you that, we just See the crashes in our sentry. We see 70 affected users (from 700 having the adapter installed)

### Expected behavior

it do not crashes. This means the exception is somehow catchable by our code or catched by library code

### Screenshots/Logs
Details see: https://sentry.iobroker.net/share/issue/7e22d3b15cc446d49b2da387c1846f6a/ 

```
Error: Cannot call write after a stream was destroyed
  File "_stream_writable.js", line 399, col 19, in doWrite
  File "_stream_writable.js", line 387, col 5, in writeOrBuffer
  File "_stream_writable.js", line 318, col 11, in Socket.Writable.write
  File "/opt/iobroker/node_modules/ring-client-api/lib/api/ffmpeg.js", line 76, col 23, in FfmpegProcess.start
    this.ff.stdin.write(input);
  File "/opt/iobroker/node_modules/ring-client-api/lib/api/sip-session.js", line 125, col 16, in SipSession.<anonymous>
    ff.start(inputSdpLines.filter((x) => Boolean(x)).join('\n'));
  ?, in Generator.next
  File "/opt/iobroker/node_modules/ring-client-api/lib/api/sip-session.js", line 5, col 58, in fulfilled
    function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
  File "internal/process/task_queues.js", line 97, col 5, in processTicksAndRejections
```

### Environment

 - OS: Linux based and also Windows!
 - Node.js: mostly 12.8.x
 - NPM: unknown
 - ring-client-api: 8.2.0

**Comment by dgreif** [comment]
@Apollon77 I'm happy to see the `ring-client-api` getting used elsewhere.  Could you give me some idea of how you are configuring ffmpeg?  The way the code is set up, it starts the process and then immediately calls `start`, so the only way I can think that this would error is if you have invalid ffmpeg options.  I'd also definitely recommend updating as there have been significant changes to live streaming since v8.2.0

**Comment by Apollon77** [comment]
Hi, the problem is that it is not about „me“
But about some users out there - so I can not tell you. But the main question would be if not a check make sense now that we see that this error can happen ... and catch it in a way that the „User of the Library“ (so our Software) can show that to the user and do not need to hard crash ;-)

Also interesting we have bombigste report of any of those users in our project :-( so hard to get more details on it beside „it happens“

**Comment by Apollon77** [comment]
Unchecked also closed issues and was only able to find such cases when ffmpeg was not really able to be started because maybe wrong setup. Do you see any way to detect that beforehand of using it?

**Comment by dgreif** [comment]
Honestly, I don't think I should catch these errors.  I need to continue surfacing the errors all the way up so that users of the api know that there was an error.  You can do something like this to catch the error yourself:

```js
try {
  await camera.streamVideo({ your options here })
} catch (e) {
  logError(e)
}
```

**Comment by Apollon77** [comment]
No this is the problem. This exception happens async and that’s why it is not catchable that way. And yes I totally agree: the error should be catchend and returned in a proper catchable way ;-)

**Comment by dgreif** [comment]
If you update to the latest version, it is not async.  It is thrown properly and is catchable.

**Comment by Apollon77** [comment]
Ok, thank you ... then we will try that

**Comment by dgreif** [comment]
Reopen if you still see uncaught errors after updating
