### ISSUE TITLE
Ring Stick up Cam - No response

### ISSUE THREAD

**Issue by dipen26** [dgreif/ring#414]
I just configured HOOBs to centralized all the smart devices in my house and so far I loved it. I have ring security, and Stickup cam both, but weirdly Stickup cam shows no response but thumbnail are updating every few mins. I tried some solutions but having same issue. I am not good with coding and trying to understand how to make it work. I really appreciate your work to making ring HomeKit reality. 

This is what I get:

Preparing Live Stream for Garage
7/25/2020, 4:19:04 PM [Ring] Request to https://api.ring.com/clients_api/doorbots/31764567/live_view failed with status 403. Response body: 
7/25/2020, 4:19:04 PM [Ring] Failed to prepare stream for Garage (0.189s)
7/25/2020, 4:19:04 PM [Ring] HTTPError: Response code 403 (Forbidden)
    at onResponse (/home/hoobs/.hoobs/node_modules/got/dist/source/as-promise/index.js:142:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,

**Comment by dgreif** [comment]
I haven't seen this specific issue before, but I think this behavior can happen if you have live views disabled for the camera.  You should check your Ring app and verify that Modes aren't preventing live view from the camera.  Try doing a live view in the Ring app, and once that works, you should be able to do live views through HOOBS

**Comment by dipen26** [comment]
Thank you so much for reply. Your little hint helped me to check under ring and I found the issue. It is regarding to mode setting when you have home or disarm option on the indoor camera will only take video but no live view is available . I went and got all fixed. Thank you
