### ISSUE TITLE
I am getting a UnhandledPromiseRejectionWarning: HTTPError: Response code 406 (Not Acceptable)

### ISSUE THREAD

**Issue by gpai01** [dgreif/ring#415]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

I am trying to use the ring-client-api and with a simple implementation, capture the videos and store in my local machine. However, the step ringApi.getLocations() is failing. Please see error message below 

### To Reproduce
1. Create an `ApiClient'
2. Use token generated with npx -p ring-client-api ring-auth-cli (note 2fa was successful)
3. Set cameraStatus and cameraDings polling time intervals
4. Attempt to get location using "const locations = await ringApi.getLocations()"
5. Failing at step #4 above. See error below

### Expected behavior
 A clear and concise description of what you expected to happen.

Once this step is successful, I am expecting 
1. to get the camera location
2. On detecting motion, I am getting the timestamp
3. Recording video for 30 secs
4. So expecting to see the video for 30 secs. 

Here is the code 
// @target: es2017
// @module: esnext
import { RingApi } from 'ring-client-api'
//import { sharp } from 'sharp'
const sharp = require('sharp')

// Start function
const main = async function() {
  console.log("here")
    const ringApi = new RingApi({
      refreshToken: "Use token generated with npx -p ring-client-api ring-auth-cli",

      cameraStatusPollingSeconds: 50,
      cameraDingsPollingSeconds: 20,
    });
    console.log("here 1a")
    //console.log(ringApi)
    const locations = await ringApi.getLocations()
        console.log("here 1");
    const location = locations[0]
        console.log(location.cameras)
    const camera = location.cameras[0]
    camera.onMotionDetected.subscribe(async data =>  {
     //console.log(data)
        const now = Date.now()
        console.log("detected new motion: " + now)
    // called every time new data is fetched for this camera
        const file_name = 'sample_video_' + now + '.mp4'
        camera.recordToFile(file_name, 30)
    })

// Call start
main();

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

(node:15128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15128) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Additional context
 Add any other context about the problem here.

### Environment

 - OS: Windows 10 Enterprise ver 10.0.18363 Build 18363
 - Node.js:  v12.18.0.
 - NPM: 6.14.4
 - ring-client-api: 9.6.0

Thank you for your help!

**Comment by dgreif** [comment]
You are seeing a 406 because Ring rate-limits requests to certain endpoints.  You will need to wait 24 hours and try again.  This should have been fixed with #389 which causes sessions to be reused across api creations.  The only way it wouldn't properly reuse sessions if it is unable to grab the hardware id from your computer, in which case you should see a log that says `Request for machine id timed out.  Falling back to random session id`

**Comment by gpai01** [comment]
Thank you dgreif! I am not getting the hardware error. Do you think the
rate limit fix isn't working as expected? Thanks!

**Comment by dgreif** [comment]
I'm pretty confident that the rate limit fix is working properly.  Not sure what else would be getting you into this scenario.  Basically just need to wait it out at this point

**Comment by gpai01** [comment]
Sure, will wait out. Thank you!

**Comment by dgreif** [comment]
Any luck @gpai01 ?

**Comment by gpai01** [comment]
Hey Dusty - I will check this out in the next couple hours and respond to
you. Thanks for checking!

**Comment by gpai01** [comment]
No luck. Same error being thrown.  

(node:14420) UnhandledPromiseRejectionWarning: HTTPError: Response code 406 (Not Acceptable)
    at onResponse (C:\Users\gpai\node_modules\got\dist\source\as-promise\index.js:124:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:14420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by gpai01** [comment]
@dgreif  any update on this? Thank you!

**Comment by dgreif** [comment]
Just looked through some old issues and pretty much all of them had to do with rate limiting when a 406 was received.  Can you try logging in to `ring.com` and see if you are able to get in on the same network that your homebridge server is one?  Sometimes that clears it up.  Other than that, make sure you don't have a second homebridge server running somewhere else that could be constantly restarting.  Last, try updating to the latest nodejs (12.18.3)

**Comment by dgreif** [comment]
@gpai01 any updates?  I haven't had any other reports of 406 errors recently so this seems pretty isolated to your setup at this point.

**Comment by gpai01** [comment]
@Dusty - I will test this out Tonite and confirm to you. Thank you!

**Comment by dgreif** [comment]
@gpai01 any updates?

**Comment by gpai01** [comment]
Hey Dusty,
Its working now!, I'd tried to run this 2 days after I'd first reported the issue and was running into the 406 error. But now, after ~2 weeks the same code (w/ same version of node and the same way of generating refresh token via ring-auth-cli) is working. It looks like the rate limiting might be quite long lasting. 

As an aside, what I am trying to do is detect any motion and record the video. I'm polling the doorbell a couple times a minute to achieve this. Does that seem feasible given the rate limiting?

```javascript
const main = async function() {
    const ringApi = new RingApi({
      refreshToken: "...",
      cameraStatusPollingSeconds: 50,
      cameraDingsPollingSeconds: 20,
    });
    const locations = await ringApi.getLocations()
    const location = locations[0]
    const camera = location.cameras[0]
    camera.onMotionDetected.subscribe(async data =>  {
        const now = Date.now()
        const file_name = 'sample_video_' + now + '.mp4'
        camera.recordToFile(file_name, 30)
    })
}

```

**Comment by dgreif** [comment]
The rate limiting is only applied to the login/session endpoints, not the camera status and dings endpoints.  You can set `cameraDingsPollingSeconds: 1` and not run into issues.  The rate limiting scenarios usually show up with you are rapidly stopping and restarting your code during development, but even then, I have workarounds in place to prevent rate limiting if at all possible.  The code that you have there looks like it should work fine.  If your goal is to avoid paying for a Ring subscription, then I can't really condone it because I think their pricing is exceptionally fair.  Glad the 406 has cleared up tho!  Have fun tinkering 😄
