### ISSUE TITLE
Ring Camera On/Offline Sensor for HomeBridge

### ISSUE THREAD

**Issue by JeremyLaurenson** [dgreif/ring#416]
# Feature Request

### Description
I would like to see a contact sensor surfaced in HomeBridge that shows the online status of Ring cameras. Currently there is no way to be notified that a device is offline using the Ring App.

### Describe the solution you'd like
Create a contact sensor device for each camera/chime in the plugin. When a device is offline for n consecutive polls, mark the contact as open. When the device is online again, mark it as closed.

### Describe alternatives you've considered
I have looked to ring for direct support of this capability, which it does not have. I have also considered using a simple ping tool, however ring devices behind chime pros are essentially NATted devices and are not available to poll this way.

**Comment by dgreif** [comment]
While I'm sure this could be useful for a handful of users, I think the majority would find this extra sensor an annoyance, in which case I'm going to get an immediate request for an option to hide it (just trying to be realistic, this happens often).  Can you elaborate on your situation? Specifically why you _expect_ your cameras to go offline?

**Comment by JeremyLaurenson** [comment]
Maybe off by default then.

I have a lot of ring devices and every couple of months something goes off-line. Today as an example our Ring Chime pro device in the garage was down. We had not noticed it for a week or more.

We do the usual unplug replug reset and it stays operational for a while until again things go down.

A security system is pretty useless if it doesn't notify you of a problem, and so this would solve the issue for us

**Comment by dgreif** [comment]
This really seems like it would be better as a feature in the Ring app.  You mentioned you looked for direct support from Ring.  Did you reach out to them to see if they could add a push notification if a camera goes offline?  I think that would be the right fix for this problem since all Ring users would get the benefit.

**Comment by JeremyLaurenson** [comment]
Yup - its been a feature request and I think theyre ignoring it since it sheds light on device instability ;-)

**Comment by dgreif** [comment]
Well...that's a bit frustrating.  I'm not super interested in implementing it in the plugin at this point so you may just need to follow up with Ring and see if you can get it pushed forward on their end.

**Comment by JeremyLaurenson** [comment]
Im just going to use 
GREP_STRING=`grep -c  ", The camera currently reports that is it" /var/lib/homebridge/homebridge.log`
 if [ $GREP_STRING -ne 0 ] 
 then
    echo "A camera is down"
 fi

**Comment by dgreif** [comment]
Sounds good, glad you have a workaround for now!

**Comment by JeremyLaurenson** [comment]
Ah, this is only valid if an event happens and then the device is offline. Ill try muddle thru the API to see if I can doit myself.

J

**Comment by dgreif** [comment]
In case you wanted to query the api directly, there are number of examples in https://github.com/dgreif/ring/tree/master/examples.  You would want to do something like this:

```js
import { RingApi } from '../api'

async function example() {
  const { env } = process,
    ringApi = new RingApi({
      // Replace with your refresh token
      refreshToken: env.RING_REFRESH_TOKEN!,

      // how often it should poll the camera status, in seconds
      cameraStatusPollingSeconds: 20,
    }),
    cameras = await ringApi.getCameras()

  cameras.forEach((camera) => {
    camera.onData.subscribe(() => {
      if (camera.isOffline) {
        console.log(`Camera ${camera.name} is offline!!`)
        // do something here to notify yourself that the camera is offline
      }
    })
  })
}

example()
```
