### ISSUE TITLE
Snapshot failed to refresh / Failed to cache snapshot.

### ISSUE THREAD

**Issue by Lorccan** [dgreif/ring#418]
# Bug Report

### Describe the Bug
Snapshot Failure

### To Reproduce
Seems to appear after a camera detects motion

### Expected behavior
Not to see the error
### Screenshots/Logs
[7/29/2020, 03:47:06] [Ring] Deck Detected Motion
[7/29/2020, 03:47:51] [Ring] Snapshot failed to refresh after 70 attempts
[7/29/2020, 03:47:51] [Ring] Snapshot failed to refresh after 70 attempts
[7/29/2020, 03:47:51] [Ring] Snapshot failed to refresh after 70 attempts
[7/29/2020, 03:47:51] [Ring] Snapshot failed to refresh after 70 attempts
[7/29/2020, 03:47:51] [Ring] Snapshot failed to refresh after 70 attempts
[7/29/2020, 03:47:51] [Ring] Failed to cache snapshot for Deck (44.937s), The camera currently reports that is it online
[7/29/2020, 03:47:51] [Ring] Failed to cache snapshot for Deck (44.914s), The camera currently reports that is it online
[7/29/2020, 03:47:51] [Ring] Failed to cache snapshot for Deck (44.912s), The camera currently reports that is it online
[7/29/2020, 03:47:51] [Ring] Failed to cache snapshot for Deck (44.839s), The camera currently reports that is it online
[7/29/2020, 03:47:51] [Ring] Failed to cache snapshot for Deck (44.838s), The camera currently reports that is it online

### Additional context
I had also been getting a previous error about not being able to reach ring server, but I fixed this by changing my router's DNS settings away from my ISP's (to CloudFlare). Things seemed to settle down, but now I am seeing these errors (which I saw as being fixed by a previous release). The cameras are stick-up cams wired to the mains.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
{
 "refreshToken": "xxx",
            "platform": "Ring"
}
```

### Environment

 - OS: Raspbian
 - Node.js: 12.18.3
 - NPM: 6.14.3
 - homebridge-ring: 9.6
 - homebridge: 1.1.1
 - hoobs: N/A

**Comment by dgreif** [comment]
When you say they are stickup cams that are wired, do they also have a battery in them?  If so, they will be unable to capture a snapshot while recording.  If they are the true wired version, then your error is a bit more unusual.  I'd recommend you try loading the Ring app and see if it is able to pull a new snapshot from the cameras.  If not, then you should unplug the ones that are having trouble, then plug them back in and try again.  Sometimes they just need a reboot 😄

**Comment by Lorccan** [comment]
The cameras are both wired without a battery. I'll try rebooting and will report back.

**Comment by Lorccan** [comment]
I’m still getting the errors after rebooting the cameras, and it’s definitely happening when motion is detected.

I have snapshots switched off in the Ring app as I don’t need them.

I don’t really need to see the feed and snapshots provided by the plugin in the Home app, but I would like to use the detection of motion to trigger HomeKit lights. Is there an option to just do this please?

**Comment by dgreif** [comment]
Those logs about snapshots failing to load should not prevent motion detection from working.  They are more for informational purposes, to help users understand that the plugin tried to fetch snapshots but was unable to.  Could you elaborate on your statement "I have snapshots switched off in the Ring app"?  Do you not see snapshots on the dashboard of the Ring app?  Which setting did you turn off?

**Comment by Lorccan** [comment]
Under Devices>[device]>Device Settings>Snapshot Capture you can toggle Snapshot Capture off.

I can’t confirm until I experiment some more, but I think that when these issues are logged immediately after motion is detected the trigger to switch on lights in a HomeKit automation is not fired (or if it is it fires too late to be recorded by the camera).

**Comment by dgreif** [comment]
Since these are wired cameras, the plugin will wait until it receives the snapshot before triggering the motion event.  This ensures that a snapshot is available for the rich notification triggered by the motion event.  Unfortunately, you camera doesn't seem to be uploading snapshots properly, so it waits ~45 seconds for the snapshot before triggering motion, which is the delay you are seeing in activating the light.  If we get the snapshots fixed, then you will get motion events pretty much immediately.

Regarding the Snapshot Capture setting that you referred to, that is specifically for the 24x7 snapshots that get captured every X minutes.  Even with that off, you should still be able to get snapshots from the camera in the ring app on the Dashboard.  When you open the app, you should see your cameras listed as tiles on the dashboard.  Each camera will automatically fetch a snapshot and display the new snapshot in the respective tile with a timestamp of how long ago the snapshot was taken.  Can you look at those camera tiles and see if they properly load a new snapshot?  

Couple other items to check:
 - Which camera model do you have?
 - Are you experiencing this issue on multiple cameras or just this one?
 - Do you have the "Record Motion" setting turned on for the `Deck` camera?

**Comment by Lorccan** [comment]
Sorry for delay in my response.

- The cameras are both “Ring Stick Up Cam Plug In”

- I’m seeing the problem with both cameras.

- I DO have ‘Record Motion’ On for both.

**Comment by dgreif** [comment]
Thanks for that info.  Still curious if you see snapshots for those cameras in the Ring app on the dashboard.  And in particular, do the snapshots update every ~30 seconds if you just leave the dashboard open?

**Comment by Lorccan** [comment]
The snapshots do not update in the dashboard.

I tried switching one of them to record snapshots 24x7 (every 30s) - as you mentioned above - makes no difference to the dashboard.

Even quitting and relaunching (iPad) doesn’t force a refresh.

I just caught something out of the corner of my eye and then confirmed: the refresh of the preview image in the dashboard is happening just after the 10m Mark. I’ll need to speak to Ring support to find out what is causing this.

**Comment by Lorccan** [comment]
I can't say my experience with Ring support was very positive. I went through two levels and I am promised a callback 'in 24-48h). I will update here when I hear something. This Is what I was told:

- The Dashboard tile for each camera shows the most recent 'event'. I asked what constituted an event and was told it was a recording (triggered by motion) or a snapshot. I asked why the 30 second snapshots were not updating the dashboard, but I couldn't get an answer. I then stood in front of one camera and triggered a recording, but this, too, did not get reflected in the dashboard.

- I went through delete, restart, re-download, re-sign-in on the app and this made not a shred of difference. 

- I was asked whether I had any 'home automation' linked to Ring, so I was asked to delete access by homebridge-ring. That, naturally, made no difference to the situation.

@dgrief From your understanding, is it the Snapshot frequency that governs the Dashboard updates or are they independent?

I notice that across 4 iOS devices (2 x iPad, 2 x iPhone) every dashboard preview for each camera is perfectly in sync. Quitting and reloading the app will not force a Dashboard tile preview refresh and my previous assertion that refreshes were running on a 10m cycle seems less certain as they now seem entirely random (my observation of two cycles of 10m meant that I thought I had found a pattern!)

Some snapshots are missing from the timeline with 'This footage is unavailable', so I suspect the problem is likely to originate with the Ring server on which my account is hosted.

**Comment by dgreif** [comment]
@Lorccan I'm sorry I didn't get a response to you yesterday, and that you had to sit through that painful process with Ring.  The behavior you described (snapshot every 10 minutes) is exactly how the cameras behave if they are equipped with a battery.  The snapshots on the dashboard are unrelated to the "Capture Snapshots" feature and they are unrelated to motion/ding events.  In battery cams, snapshots can be captured every 10 minutes _at the most frequent_ in the Ring app.  For wired cams, it's every 30 seconds _at the most frequent_ in the Ring app.  If you don't have the dashboard open, it doesn't request snapshots (but homebridge-ring might request them).  The snapshot frequency is something I have worked very hard to get around, but it is definitely the issue you are running into.  From my previous experiences, Ring always drew the line at battery vs wired for the differing functionality, but it sounds like you have a wired camera that is behaving like a battery cam.  

* Can you verify that the cameras are not _equipped_ with a battery (even if you have them plugged in)?  
* Can you grab the model number?  It's accessible in the Home app under the settings for the camera in the "Model" field.  Should be something like "Floodlight Cam (hp_cam_v1)".

**Comment by Lorccan** [comment]
Frankly, 'painful' doesn't even begin to explain the ignorance of the people I spoke to. Worst of all was the supposed second tier who was making it up as he went along. Given that I have just a couple of weeks using these things and I could see through him doesn't fill me full of confidence.

Anyway, now I have got that off my chest, I can't get to the cameras tonight to dismount them and check inside but I don't recall seeing a battery. I know that the battery version can be equipped with an optional mains pack in place of the battery (this is probably just a battery with a permanent charger connection), but I have not seen any mention of making a mains version run off a battery pack.

The Model shown in the Home app is 'Stick UP Cam (cocoa_camera)'

Thank you for your help untangling this.  In case I decide to throw in the towel with this model, can you let me have details of Ring cameras that do work with your plugin please?

**Comment by dgreif** [comment]
Thanks for grabbing the model for me, that's all I really need at this point. I'll get an update out tomorrow morning that should fix it up for you. You won't see snapshots in the motion notifications, but it won't block your bridge on every motion event any more. Will post here when it's released

**Comment by Lorccan** [comment]
Thank you. BTW I just noticed a typo in the model. It should read: 'Stick Up Cam (cocoa_camera)'
