### ISSUE TITLE
React App Failed to compile after importing ring-client-api

### ISSUE THREAD

**Issue by Creator-360** [dgreif/ring#420]
# Bug Report

### Describe the Bug
React App Failed to compile after importing ring-client-api

### To Reproduce
 - Create React App with "npx create-react-app my-app"
 - Attempt to import ring-client-api in the default "App.js" file "import { RingApi } from 'ring-client-api'"
 - run the React App "npm install" and "npm start"
 - Then open "localhost:3000" to see the error

### Expected behavior
The React App should compile and run normally  

### Screenshots/Logs
Screenshot of "localhost:3000" of the  Failed to compile error:
![image](https://user-images.githubusercontent.com/42955270/88837624-f7602280-d20a-11ea-9309-cd6a24b2b70f.png)

### Additional context
No Additional context

### Environment
 - OS: Windows 10
 - Node.js:  v12.16.1
 - NPM: 6.13.4
 - ring-client-api: 9.6.0

**Comment by dgreif** [comment]
See #419.  Running the client api in a browser is not currently supported.  Just like #419, I'm curious what you are trying to accomplish in the browser just for future reference.

**Comment by Creator-360** [comment]
Hi @dgreif Thanks for your fast reply !
Of course ! I'm building a web app with React to monitor my Ring DoorBell and I would like to stream the video and receive the notification from the doorbell inside of my React web app. Because Ring do not have a official API, that is the reason I tried to use this one.

**Comment by dgreif** [comment]
Good to know.  Unfortunately live streaming in the browser simply will not work with the current SIP setup.  I'm investigating another approach, but I'm not sure that it's supported by Ring.  For now, the `ring-client-api` is node only and does not support the browser.
