### ISSUE TITLE
Is there any way of making it available in the Google home

### ISSUE THREAD

**Issue by treforparr** [dgreif/ring#421]
# Feature Request

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dgreif** [comment]
Your question is pretty vague, but I'll do my best to give you an answer.  If you want Google Home integration, your best bet is to use the `homebridge-gsh` plugin.  Unfortunately, the supported devices are pretty limited, and don't cover much of what's available from the `homebridge-ring` plugin (See https://github.com/oznu/homebridge-gsh#supported-device-types). 
 If you are specifically asking about cameras, they are not supported, but could possibly be in the future - https://github.com/oznu/homebridge-gsh/issues/54.

**Comment by treforparr** [comment]
I'm not very good at writing things due to my dyslexia but I would love to see a feature with a Ding feature on the Google Home as ring is never going to be investing Google Home or I'm going to have to sell my Google Home and go to Alexa ￼￼￼￼￼

**Comment by treforparr** [comment]
I would love to see the live stream to if possible But this would be more in-depth coding￼￼

**Comment by treforparr** [comment]
But if you can do it it would be amazing￼

**Comment by treforparr** [comment]
Or a press of the button notification would be good￼

**Comment by dgreif** [comment]
@treforparr I understand where you are coming from, and why you would want support in Google Home.  Unfortunately this repo simply isn't the right place to ask for it.  I recommend you comment on https://github.com/oznu/homebridge-gsh/issues/54 and specify that you are interested in getting your Ring camera integrated into Google Home via homebridge.
