### ISSUE TITLE
Disable Security System / Location Mode

### ISSUE THREAD

**Issue by Ironboltx** [dgreif/ring#425]
# Feature Request

### Description
I would like to have an option to disable the HomeKit security system that is labeled as "(Location) Mode". 

### Describe the solution you'd like
An option to disable this

### Describe alternatives you've considered
There was nothing I could do really. 

### Device data
N/A

**Comment by Ironboltx** [comment]
I would also really like this because I don't use rings security system and their location modes. I just don't want to see an extra security system in my house and have Siri maybe arm the wrong one. This plugin is  **REALLY** good though. Thank you so much!

**Comment by Tesla-P100FX** [comment]
I agree the plugin is AWESOME.  Love to resolve my issue with video over a VPN, still awesome regardless 😀

**Comment by dgreif** [comment]
See the Location Modes section in the readme: https://github.com/dgreif/ring/tree/master/homebridge#supported-devices-via-ring-alarm-and-ring-smart-lighting-hubs. You can set locationModePollingSeconds to 0 to hide the modes switch

**Comment by Ironboltx** [comment]
Thank you!
