### ISSUE TITLE
Alam Button in Homebridge

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#428]
Hi, The Alarm Button pin Homebridge Shows the Home, Away and Disarm, but when you go to do automations, it shows Arm and Off or Triggered (which is good). However, it needs to expose (like other alarms in Homekit) the Home, Away, Disarm. I need to be able to do automation on Home Armed, Vs Away Armed and Off... Is that  quick fix, if so you would make my day.... As you usually do :)

**Comment by dgreif** [comment]
Automations are completely controlled by HomeKit and only expose what apple chooses to expose.  I don't think there is anything I can do to change the values you see there.

You mentioned other alarms expose more options.  Do you have an example (particularly a homebridge plugin)?  Could you post a screenshot of the automation page listing those?

**Comment by adavison007** [comment]
Update, 

If I say when a switch turns on, then Set Alarm too X it shows Home, Away. Off. Perfect... 

If I say When alarm is set to (I don't see Home, Away, off, I see arm, disarm or triggered. 

so shows correctly one way, not the other, jI;ve check the other alarm and it is the same..... Bugger..... I need to see Home, Away, off in both control directions.

**Comment by dgreif** [comment]
I think if you select `Arm` as the trigger, it will trigger that automation for both home and away. This is a HomeKit (or at least Home app) limitation, so you would need to make a request to Apple if you want to see the additional option, more specific options.  Sorry I can't do it from my end!

**Comment by adavison007** [comment]
Thanks, so I found that the home+ app does expose what I need, so its a homekit app issue :)

**Comment by dgreif** [comment]
Great, glad you found a work around!
