### ISSUE TITLE
Can't set Modes

### ISSUE THREAD

**Issue by tsightler** [dgreif/ring#429]
Bug Report

### Describe the Bug
In my ring-mqtt project I'm attempting to implement a modes control panel for users that are requesting support for setting modes but don't have an alarm.  I've managed to get everything working pretty well and mode states are monitored just fine if I change them from the Ring app, but, no matter what I do, I can't seem to actually set a mode.

I looked at the homebridge code for this and it seems it should be as simple as:
`location.setLocationMode('away')`
I call this, and indeed it returns no errors, but nothing actually happens.  If I put dummy values in there, vs home/away/disarm, then I get HTTP 400 errors, which I would say are expected for invalid values, so this feels like this is the correct way, but I must be missing something.  I looked at the homebridge code and it appears to do the same so I'm just not sure what I could be doing wrong here.

I assume I must just be doing something incorrectly but I just can't figure it out.

### To Reproduce
Run: `location.setLocationMode('away')`

### Expected behavior
Mode should be set to away.

**Comment by tsightler** [comment]
Nevermind, as I expected, it was something super silly on my part.  Somehow missed an await in my state checking code so actually it was working but didn't appear to be.  Didn't help that the state doesn't update until a manual refresh in the Ring app.  Sorry for the noise.

**Comment by dgreif** [comment]
Glad you got it working. Thanks for keeping up the MQTT project!
