### ISSUE TITLE
Unable to upgrade from 7.2.2 on Hoobs

### ISSUE THREAD

**Issue by dominvepf** [dgreif/ring#432]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...
the ring plugin often crashes my hoobs. I have to restart it and then it works for a while.
I thought I might fix the problem but I cannot upgrade.

In Hoobs 3.2.6 when I try to click the upgrade button, it appears to work, then once the service is restarted the version reported is still 7.2.2.

### To Reproduce
In Hoobs 3.2.6 when I try to click the upgrade button, it appears to work, then once the service is restarted the version reported is still 7.2.2.

This seems to silently fail.

I have tried to manually install the latest by going to Hoobs terminal and typing
npm i -g --unsafe-perm homebridge-ring
but I get error messages:
`npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/@sindresorhus/is
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/@types/node
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/dns-socket
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/engine.io/node_modules/ws
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/get-stream
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/http2-wrapper
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/minizlib
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/onetime
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/protocols
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/is-ssh
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/parse-path
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/parse-url
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/public-ip/node_modules/cacheable-request/node_modules/get-stream
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/simple-concat
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/tar
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/agentkeepalive
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/execa
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/ffmpeg-for-homebridge
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/got
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/public-ip
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/sdp
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/uuid
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/@sindresorhus
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/@types
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/engine.io/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-ring/node_modules/public-ip/node_modules/cacheable-request/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules/homebridge-ring/node_modules/@sindresorhus/is
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/homebridge-ring/node_modules/@sindresorhus/is'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/homebridge-ring/node_modules/@sindresorhus/is'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/usr/local/lib/node_modules/homebridge-ring/node_modules/@sindresorhus/is'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/homebridge-ring/node_modules/@sindresorhus/is'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-08-15T19_47_26_422Z-debug.log`

### Expected behavior
 A clear and concise description of what you expected to happen.
For the plugin to update

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
`"platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiZGVmYXVsdCIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTc0NzkxNjYsInJlZnJlc2hfY2lkIjoicmluZ19vZmZpY2lhbF9hbmRyb2lkIiwicmVmcmVzaF9zY29wZXMiOlsiY2xpZW50Il0sInJlZnJlc2hfdXNlcl9pZCI6MzI4MjQwMDgsInJuZCI6Ijd1YTNnYmdqaVJwZ2JnIiwic2Vzc2lvbl9pZCI6ImE3YjAyMjkyLTY2NjgtNGJlMi1hNjY3LTNiMjg5YjE4OWY2OCIsInR5cGUiOiJyZWZyZXNoLXRva2VuIn0.BWFk7DTZ9UCQ-ZBmmO_gFf8k2VDQDcdhfng-4Qc0Jnv8S9gBuwjPcUnyP-kh_cZQENGevXFcbWdvpqBRVugs8A",
            "locationIds": []
        },`

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: Hoobs on raspberry Pie self install
 - Node.js: v12.16.2 
 - NPM: 6.14.4 
 - homebridge-ring: 7.2.2
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: 3.2.6

**Comment by dgreif** [comment]
Try `sudo npm i -g --unsafe-perm homebridge-ring`.  the `sudo` should help you get past those `checkPermissions` errors

**Comment by dominvepf** [comment]
Dear Dusty, thanks for your suggestion.

It appears that the operation completed successfully as per the screenshot


However, Hoobs still reports being on version 7.2.2 in the plug-in section, And when I click the update button (mettre à jour) it once again fails silently.



When I try to see who is at the door, I get the following in the journal and only the video, no sound. This is rather weird but thanks for helping!

2020-08-15 19:03:05 [Ring] Streaming video only - ffmpeg was not found. See https://github.com/dgreif/ring/wiki/FFmpeg for details.
2020-08-15 19:03:07 [Ring] Waiting for stream data from Porte d'entrée (1.892s)
2020-08-15 19:03:08 [Ring] Received stream data from Porte d'entrée (2.858s)
2020-08-15 19:03:08 [Ring] Streaming active for Porte d'entrée
2020-08-15 19:03:16 [Ring] Stopped Live Stream for Porte d'entrée
_________________________________________________________________
Prof. Dr. Dominic Villeneuve, Ph.D.
dominicvilleneuve@live.ca <mailto://dominicvilleneuve@live.ca> | Web: http://DominicVilleneuve.ca <http://dominicvilleneuve.ca/>

**Comment by dgreif** [comment]
I suggest you reach out to HOOBS for help on this issue.  They should definitely be able to help you with the update process.  As for that error, that should hopefully go away and audio should work when you get on the latest version.

**Comment by dgreif** [comment]
Closing since this really seems like a HOOBS issue.  Let me know if they send you back my way.

**Comment by dominvepf** [comment]
Ok thanks a lot!

Envoyé de mon iPhone

Le 16 août 2020 à 11:27, Dusty Greif <notifications@github.com> a écrit :

﻿

Closing since this really seems like a HOOBS issue. Let me know if they send you back my way.
