### ISSUE TITLE
Getting undefined refreshToken with ring-auth-cli

### ISSUE THREAD

**Issue by sunbit** [dgreif/ring#433]
Today I realized that i needed to update my code for the new refreshToken expiring so quick. First thing i did was request a new refreshToken via the command line, and i obtained this:

```This CLI will provide you with a refresh token which you can use to configure ring-client-api and homebridge-ring.
Email: xxxxxxx@gmail.com
Password: xxxxxxx
Ring 2fa or verification code is enabled.  Please enter code from the text/email.
2fa Code: xxxxxx
Successfully logged in to Ring. Please add the following to your config:

"refreshToken": "undefined"
```

I tried to put wrong credentials and wrong 2fa code just to check if somehow a authentication error was "swallowed", but i get the expected errors from the cli. I guess that something have changed on their side again, but no clue where start looking. 

Can someone help with this? I would be happy to help if someone can point me where's the code for getAuthWith2fa.

Thank you

**Comment by dgreif** [comment]
I just tried it on my end and was able to get a refresh token no problem.  Can you please provide the following info?

* `homebridge-ring` version
* `node` version (`npm i -v`)
* Operating System

**Comment by sunbit** [comment]
Hi, these are the versions

homebridge-ring@9.8.0
node version: v14.0.0
npm version: 6.14.4
OSX 10.15.5

Based on your answer, i just tried with a node:latest docker image (node 14.9, npm 6.14.7m same homebridge-ring) and it worked there...

Then I tried again on osc after updating npm to 6.14.7, so left with osx and node version variables as sources of the trouble.

**Comment by dgreif** [comment]
Yeah, it's very possible that node `14.0.0` had an issue that would cause what you saw.  So you are good to go now?
