### ISSUE TITLE
Homekit Secure Video

### ISSUE THREAD

**Issue by cvk14** [dgreif/ring#434]
# Feature Request

### Description
Implement Homekit Secure Video for Ring Devices

### Describe the solution you'd like
Implement Homekit Secure Video for Ring Devices

### Describe alternatives you've considered
HSV will allow the streams to be stored in the users purchased data pool from iCloud storage. We *MAY* be able to stop paying for ring services?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by cvk14** [comment]
https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/338

**Comment by dgreif** [comment]
@cvk14 if you read through that issue, you will find that HSV is not currently supported by homebridge, and may never be supported depending on how well Apple has locked it down.  Please search old issues before opening a new one (See #177)

**Comment by ifeign** [comment]
https://github.com/homebridge/HAP-NodeJS/pull/904

Looks like HKSV is coming to Homebridge!

**Comment by intrepidsilence** [comment]
Since this is now supported in homebridge 1.40, could this be re-opened?
