### ISSUE TITLE
Chime switch not working

### ISSUE THREAD

**Issue by vosmike** [dgreif/ring#435]
Hi @dgreif! Thank you for creating this plugin! Very happy with it so far 👍 
I'm new to all this (Hoobs), so I'm probably missing something, but unable to find out what.

# Bug Report

### Describe the Bug
The chime appears in my Home app as do the alarm and Ring Camera/Doorbell.
All devices are working as expected, except two chime switches.
The Play Ding and Play Motion are turning back off after I turn them on within a second. The snooze switch does work.
Because I can't turn the chime on, it does not play a sound when the doorbell is used.

### To Reproduce
Steps to reproduce the behaviour:
- Click the switch in the Home app
- The switch flicks back off immediately

### Expected behavior
The switch to function and stay on when clicked

### Screenshots/Logs
Nothing found in the logs

### Additional context
Hiding the chime in the hoobs config did not help.

### Homebridge Ring Config
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "xxxxxxx",
            "hideDoorbellSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideCameraMotionSensor": true,
            "hideCameraSirenSwitch": true,
            "hideAlarmSirenSwitch": true,
            "showPanicButtons": false,
            "debug": true,
            "hideDeviceIds": [
                "xxxxxx-xxxx-xxxxx-xxxxxx-xxxxxxxx"
            ]

```

### Environment

 - OS: macOS 10.15.6
 - Node.js: 12.18.3
 - NPM: 6.14.6
 - homebridge-ring: 9.8.0
 - homebridge: N/A
 - hoobs: 3.2.6

**Comment by dgreif** [comment]
The `Play Ding` and `Play Motion` switches will simply play the associated sound through the chime, a single time.  They don't change any settings.  Since they simply play a sound, I have them set up to turn off immediately after they turn on.  Does that answer your question?

**Comment by vosmike** [comment]
That makes sense, yes! I thought they would set the chime on/off for click and movement.
As my chime stopped producing any sound, even from the app. It must just have died on me.

Thanks you!

Met vriendelijke groet, Yours sincerely,
Mike Vos
