### ISSUE TITLE
Sending custom audio through API

### ISSUE THREAD

**Issue by anshgupta1234** [dgreif/ring#436]
# Feature Request

I am not sure whether Ring could even allow this, but can we send custom audio through the speakers of the Ring device? I was thinking of just making a small script that plays "Don't forget to wear a mask!" if it detects motion.

**Comment by dgreif** [comment]
That is technically possible using ffmpeg and the events generated by the client api.  You should take a look at https://github.com/dgreif/ring/blob/master/examples/return-audio-example.ts which streams an `output.mp4` file to the camera.  That, in combination with the event watcher in https://github.com/dgreif/ring/blob/master/examples/example.ts#L71-L77 should get you what you want

**Comment by bachdinhnhan** [comment]
> That is technically possible using ffmpeg and the events generated by the client api. You should take a look at https://github.com/dgreif/ring/blob/master/examples/return-audio-example.ts which streams an `output.mp4` file to the camera. That, in combination with the event watcher in https://github.com/dgreif/ring/blob/master/examples/example.ts#L71-L77 should get you what you want

I tried to do the same thing. Listen "motion" event and send a voice audio to the Ring DoorBell. Unfortunately, the voice only last for few seconds (properly 2s) and then being interupted. Still investigate the cause!

Can you try the scenario as an example?

**Comment by bachdinhnhan** [comment]
> > That is technically possible using ffmpeg and the events generated by the client api. You should take a look at https://github.com/dgreif/ring/blob/master/examples/return-audio-example.ts which streams an `output.mp4` file to the camera. That, in combination with the event watcher in https://github.com/dgreif/ring/blob/master/examples/example.ts#L71-L77 should get you what you want
> 
> I tried to do the same thing. Listen "motion" event and send a voice audio to the Ring DoorBell. Unfortunately, the voice only last for few seconds (properly 2s) and then being interupted. Still investigate the cause!
> 
> Can you try the scenario as an example?

Finally I got it. After placing "await cleanOutputDirectory()" as your example, now my code can send out the custom audio.

It seems like cleaning out the output is necessary.
