### ISSUE TITLE
Live feed drops frames consistently

### ISSUE THREAD

**Issue by donaldallen** [dgreif/ring#437]
# Bug Report

### Describe the Bug
I have a Ring Doorbell 3 and a Ring Floodlight Cam. Using the Ring app, the video feed comes up within 2 seconds and is very smooth, no stuttering.

However, when opening the Home app, the preview thumbnail takes 5-10 seconds to load (sometimes longer). Then when tapping on a feed, the video takes sometime to load, about 5-10 seconds again.

The video feed itself will stream, but it drops quite a lot of frames. Sometimes it seems like it's paused on a frame for 10 seconds, then will continue live.

### To Reproduce
 - Open Home
 - Tap on Ring video feed

### Expected behavior
Would expect the feed to be smooth with no dropped frames.

### Screenshots/Logs
https://streamable.com/rtv018

### Homebridge Ring Config
```
{
    “bridge”: {
        “name”: “Homebridge D948”,
        “username”: “D9:48”,
        “port”: 51279,
        “pin”: “xxx-xxx-xxx”
    },
    “accessories”: [],
    “platforms”: [
        {
            “refreshToken”: “...”,
            “platform”: “Ring”
        }
    ]
}
```

### Environment

- Homebridge 1.1.2
- Homebridge Ring 9.8.1
- Raspbian GNU/Linux Buster (10)
- Node.js v12.18.3
- NPM v6.14.6
- Ethernet connection
- Apple TV as a home hub, also ethernet
- Service Mode: Yes (not sure what that is)

**Comment by dgreif** [comment]
I've just updated the wiki with some info for the issues you are experiencing.  Please see https://github.com/dgreif/ring/wiki/Camera-Troubleshooting#live-stream-quality .  Unfortunately I have optimized the video streams as much as I possibly can at this point, and any remanining issues are a side-effect of the many connections the stream has to go through for Ring + homebridge.  Your best bet is to investigate the network connections mentioned in the wiki and try to make them as fast as possible on your end.
