### ISSUE TITLE
Cannot log in after changing email of Ring account

### ISSUE THREAD

**Issue by newbeetle59** [dgreif/ring#440]
Hello,

After changing my email account I’m not able to connect anymore. Looks like refresh token is not doing the job correctly (I use config-ui-x). Any suggestions ?

Thanks.

Amaury

**Comment by newbeetle59** [comment]
Ok, I fixed it by removing the plugin then add it again in config-ui-x, at first start it requires ring email address and password. Once this 1st step is ok, you receive an email or sms with authentication code, fill in the verify code field in config-ui-x and you should be good to go.

**Comment by dgreif** [comment]
Sorry it's not super clear in the ui, but you can also deleted the refresh token and it will show you the login flow again, without removing the whole plugin
