### ISSUE TITLE
Can't set volume on base station (hub.redsky)

### ISSUE THREAD

**Issue by tsightler** [dgreif/ring#441]
### Describe the Bug
I'm working on adding support for setting the volume of the keypad/base station to ring-mqtt but ran into a very strange issue.  Setting the volume seems super simple, just "device.setVolume(0.50)" basically the same as a multi-level switch/fan.  Indeed this works perfectly for the security-keypad, but attempting to do this for the base station simply does nothing.  If I run in debug I can see the command being sent:

"device":{"v1":{"volume":0.5}}}

But the volume of the device does not change.  However, doing exactly the same with security-keypad works fine.  I know this is really weird and seems super straightforward, but I just can't get it to work.

### To Reproduce
`device.setVolume(0.50)
`
Check that volume did not change.  I receive no errors, it appears to work.  If I call the function on non-supported devices I get a proper error that I can only set volume on security-panel and hub-redsky devices.

### Expected behavior
Volume for hub should change just like for keypad.

**Comment by tsightler** [comment]
For completeness, here's some test code I'm using (basically, pretty close to your example code:
```
(async () => {
    const locations = await ringApi.getLocations()
    const devices = await locations[0].getDevices()
    const device = devices.find(device => device.data.deviceType === 'hub.redsky')
    device.onData.subscribe(data => {
        console.log(device.data.volume)
    })
    await device.setVolume(.75)
})();

```

For the keypad this outputs the original volume, and then, in <1 second the new volume as the change is registered and the data updated.  For the base station, no errors, but only the original volume is shown.  Obviously the setVolume() is being accepted but nothing is actually changing.

**Comment by dgreif** [comment]
I copied and pasted your code and it worked exactly as it should.  Logged the old volume and new volume, and it updated on the base station properly.  Did you try opening the Ring app to see if the volume is updating properly?  Is this a v1 or v2 base station?

**Comment by tsightler** [comment]
Yeah, it seems so straightforward.  I did check in the app and no changes, also, if I change the volume in the app it's reflected almost immediately with a data update.  Change the code to the security panel and it works.  Could it somehow have something to do with the fact that I'm using a shared account to access the Ring API?

I assume I have a v1 as I purchased just a few months after they came out.  

I'll try to setup a MITM proxy and see what command my app is sending.

**Comment by dgreif** [comment]
Yeah, it's definitely possible that the shared account doesn't have permission to set the volume on the base station. Not sure why it would work for the keypad tho...

**Comment by tsightler** [comment]
Just checked and, even in the Ring app it's not possible to set the volume when logged in as a shared user.  The option doesn't even appear.

Weirdly you can still rename the device, change the room, or test the siren, but can't set the volume.  Anyway, I'm going to guess that explains it.

I'll have to dig to see if there's a way to detect if setting the volume is possible or not and only enable the option when the account has the capability.

**Comment by tsightler** [comment]
I'm going to go ahead and close this since I confirmed it works with the main account but not any shared accounts and this is true in the app as well.  I could not figure out an obvious way to detect if the account can change the password or not, other than try to change it and then see if it changes.
