### ISSUE TITLE
Refresh token error uncatchable

### ISSUE THREAD

**Issue by djm181** [dgreif/ring#443]
# Bug Report

### Describe the Bug
Given that you have an invalid refresh token, when firing up the ring api client the thrown error is not catchable

### To Reproduce
```
try {
  const ring = new RingApi({ refreshToken: 'invalidToken' });
  await ring.getProfile()
} catch (err) {
  console.log(err.toString())
}
```

### Observed
The console.log does get hit, because of the await ring.getProfile call, but the runtime also throws an "UnhandledPromiseRejectionWarning" into the output

### Expected behavior
The console.log should get hit and there should be no unhandled promise rejection

### Environment

 - OS: Mac OS 10.15.5
 - Node.js:14.4.0
 - NPM: 6.14.4
 - ring-client-api: 9.7.0

**Comment by tsightler** [comment]
But isn't that because you're writing the entire err object to console, which includes the promise rejection?  If you want just the error message itself I think something like this would work:
```
try {
  const ring = new RingApi({ refreshToken: 'invalidToken' });
  await ring.getProfile()
} catch (err) {
  console.log(err.message)
}
```

**Comment by djm181** [comment]
No, that's not it. Try the following code - if you run this verbatim it demonstrates the issue:
```
var ring = require('ring-client-api');
async function main() {
    try {
        const r = new ring.RingApi({ refreshToken: 'asdf' });
        const p = await r.getProfile();
        console.log('Done')
    }
    catch (err) {
        console.log('Received error');
    }
}
main();
```

The output of this *should* be `Received error` and nothing else, but instead, you get this:

```
% node src/catchtest.js
Received error
(node:52708) UnhandledPromiseRejectionWarning: Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/Users/david/src/ringsync/node_modules/ring-client-api/lib/api/rest-client.js:118:15)
    at RingRestClient.<anonymous> (/Users/david/src/ringsync/node_modules/ring-client-api/lib/api/rest-client.js:122:36)
    at Generator.next (<anonymous>)
    at /Users/david/src/ringsync/node_modules/ring-client-api/lib/api/rest-client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/david/src/ringsync/node_modules/ring-client-api/lib/api/rest-client.js:23:12)
    at RingRestClient.getAuth (/Users/david/src/ringsync/node_modules/ring-client-api/lib/api/rest-client.js:121:16)
    at RingRestClient.<anonymous> (/Users/david/src/ringsync/node_modules/ring-client-api/lib/api/rest-client.js:146:33)
    at Generator.throw (<anonymous>)
    at rejected (/Users/david/src/ringsync/node_modules/ring-client-api/lib/api/rest-client.js:25:65)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:52708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:52708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dgreif** [comment]
@djm181 I agree that this should not be registering an unhandled promise rejection.  It's a little tricky because I want to start the authentication request as soon as the api is created, without needing clients to "start" anything.  I'll play around with catching the error internally while still surfacing it if you call a function that needs authentication.  Free time has been pretty thin lately, so no promises on when I'll get an update out.

**Comment by djm181** [comment]
Thanks Dusty. Stephen Cleary has some good thoughts on the topic here: https://blog.stephencleary.com/2013/01/async-oop-2-constructors.html

Admittedly, using a factory method and private constructor would substantially change the shape of the RingApi interface so I'd understand if you were hesitant.

**Comment by dgreif** [comment]
@djm181 I was able to get this all sorted out without changing the API.  Should be able to catch all auth related errors in v`9.21.0`

**Comment by tsightler** [comment]
@dgreif I'm not actually seeing any change in behavior with 9.21.0 around this.  Do I need to do something special to catch this?  I feel like my use is pretty basic and nearly identical to the example above, but here's the basic code:

```
try {
    ringClient = new RingApi(ringAuth)
    await ringClient.getLocations()
} catch(error) {
    ringClient = null
    debug(colors.brightYellow(error.message))
    debug(colors.brightYellow('Unable to connect to Ring API using '+tokenSource+' refresh token.'))
}
```

**Comment by dgreif** [comment]
That should be able to catch refresh token issues now. Nothing special you need to do. What error do you get?

**Comment by tsightler** [comment]
As far as I can tell, nearly identical to above:

`  ring-mqtt Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens +269ms
  ring-mqtt Unable to connect to Ring API using saved refresh token. +0ms
  ring-mqtt Attempting connection to Ring API using refresh token from file: /data/options.json +0ms
(node:5217) UnhandledPromiseRejectionWarning: Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/mnt/c/Users/tom.sightler/Documents/GitHub/ring-mqtt/node_modules/ring-client-api/lib/api/rest-client.js:109:15)
    at RingRestClient.<anonymous> (/mnt/c/Users/tom.sightler/Documents/GitHub/ring-mqtt/node_modules/ring-client-api/lib/api/rest-client.js:113:36)
    at Generator.next (<anonymous>)
    at /mnt/c/Users/tom.sightler/Documents/GitHub/ring-mqtt/node_modules/ring-client-api/lib/api/rest-client.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/tom.sightler/Documents/GitHub/ring-mqtt/node_modules/ring-client-api/lib/api/rest-client.js:4:12)
    at RingRestClient.getAuth (/mnt/c/Users/tom.sightler/Documents/GitHub/ring-mqtt/node_modules/ring-client-api/lib/api/rest-client.js:112:16)
    at RingRestClient.<anonymous> (/mnt/c/Users/tom.sightler/Documents/GitHub/ring-mqtt/node_modules/ring-client-api/lib/api/rest-client.js:137:33)
    at Generator.throw (<anonymous>)
    at rejected (/mnt/c/Users/tom.sightler/Documents/GitHub/ring-mqtt/node_modules/ring-client-api/lib/api/rest-client.js:6:65)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5217) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5217) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by tsightler** [comment]
Also ran the example from above from https://github.com/dgreif/ring/issues/443#issuecomment-689249272 and still get the same error as well.  It doesn't really cause me any issues, it just still creates an error as in prior versions.

**Comment by tsightler** [comment]
And, just to be clear, I currently just deal with this by catching all unhandled promise rejections with a process error handler and suppressing the output on token errors and various other messages, so it's really not a problem for me, but I was expecting that this would be caught within the try block with the changes, vs the global process handler.

**Comment by dgreif** [comment]
@tsightler thanks for sticking with me on this one.  I did have everything set up to pass the error to the top level, but I had one new spot using the auth promise internally that was causing the unhandled rejection warnings.  Give it a try with `9.21.2`

**Comment by tsightler** [comment]
Sorry for taking so long to get back to you on this, yes, it works now.  I mean, I was already trapping these in my code anyway, but now it never even hits the trap function so I think there are good now.  Appreciate the work on this.
