### ISSUE TITLE
Ability to specify specific udp port usage for live view

### ISSUE THREAD

**Issue by plittlemore** [dgreif/ring#446]
# Feature Request

### Description
If operating homebridge-ring in a segregated network, it seems almost impossible for live view to work due to a huge range of ports that need to be opened in both directions.

### Describe the solution you'd like
Either publish the port range that is used for the live view RTSP connection - or provide the ability to limit the number of ports down to a reasonable number

### Describe alternatives you've considered
Workaround is currently to open a significant number of ports (or even all ports between clients and the homebridge server)

**Comment by dgreif** [comment]
The current behavior is to bind to a random port, which is assigned by the operating system, so the range is basically any possible port.  I have tried limiting the port numbers in the past, but it is very tedious to keep track of all used ports and prevent the pool of available ports from being depleted.  Even if I bind to a specific set of ports, I can't change which port number is used by your iPhone/iPad/other Home client.  One solution would be to put your Home Hub (Apple TV or Home Pod) into the same segregated network as the homebridge server.  Then connections from the client will be made to the Home Hub, and the home hub can connect to the homebridge server unimpeded.
