### ISSUE TITLE
Ring camera devices don’t show feed in HomeKit outside local home wifi network

### ISSUE THREAD

**Issue by jourdannorman** [dgreif/ring#454]
I have successfully integrated my Ring devices to HomeKit using Hoobs, however when I’m outside of my home network or on cellular, the Video feeds from the camera devices do not work (see attached screenshot). 

![F2B6B1FE-5780-485A-AB87-D4BD5F03F1E0](https://user-images.githubusercontent.com/18621976/93640836-da510000-f9c0-11ea-984d-9ec6b36a0e19.jpeg)

**Comment by dgreif** [comment]
This is an issue that has been happening this week if your iPhone is on iOS 14 and you have a HomePod proxies the stream.  HomePod firmware is still on 13, which isn't compatible.  Hopefully Apple releases 14 for HomePod soon to fix the issue, but updating to the 14 beta on the HomePod could fix it now if you don't want to wait.

**Comment by jourdannorman** [comment]
I’m actually not using a HomePod but rather an Apple TV. Is it the same issue there?

-jn

**Comment by dgreif** [comment]
If you haven't updated the Apple TV to tvOS 14 yet, then yes, it would prevent it from working off your home network.

**Comment by jourdannorman** [comment]
I’ve since updated to tvOS 14 and still no video.

-jn

**Comment by dgreif** [comment]
I updated mine and it's working great. Can you check your logs to see if there are any errors? Can you confirm it works if you are on the same network? If so, try rebooting your Apple TV and iPhone.

**Comment by jourdannorman** [comment]
Yeah, it’s pretty strange because I updated/restarted all devices but still having trouble accessing just the camera feeds on cellular/outside network - all other Ring devices are responsive. Everything works perfectly on network including cameras.

-jn

**Comment by dgreif** [comment]
Sorry to hear non of that worked.  This is definitely an issue on the HomeKit side, and not something I can fix from the plugin.  It's been reported many times before, and usually resolves after reboots and possibly some time.  You can also try rebooting your router/modem to be on the safe side.

**Comment by Cardo1** [comment]
I’ve had this issue since I started using this plugin a while back (at least iOS 13, possibly 12?).  I’ve never been able to access the Ring cameras from outside my home network.  My other, HK native cameras work fine.

**Comment by dgreif** [comment]
@Cardo1 since yours has never worked, I don't think it's related to this issue (which seems to be caused by iOS 14 updates).  Do you have a Home Hub (Apple TV or HomePod) on the same network as your homebridge server?  Without one, you can't stream off-network.

**Comment by jourdannorman** [comment]
Yes I use an Apple TV on the same network but it still does not work remotely.

-jn

**Comment by Cardo1** [comment]
> @Cardo1 since yours has never worked, I don't think it's related to this issue (which seems to be caused by iOS 14 updates). Do you have a Home Hub (Apple TV or HomePod) on the same network as your homebridge server? Without one, you can't stream off-network.

I have a HomePod and three Apple TV’s. I can access all other devices remotely, just not the Ring devices. I figured it was just a quirk of the plugin.

**Comment by DMBlakeley** [comment]
There is an iOS 14 update for Apple TV but not HomePod. Would suggest that you make sure the Apple TV’s are updated and that the HomePod is not your Home hub.

**Comment by Cardo1** [comment]
> There is an iOS 14 update for Apple TV but not HomePod. Would suggest that you make sure the Apple TV’s are updated and that the HomePod is not your Home hub.

Alas, this is already the case.

**Comment by muflon-cmd** [comment]
Is there any option how to improve push notifications? If I connecet to local WiFI I receive push almost realtime but when I'm connecet to internet it last 10 - 15 sec (I'm using ATV as HomeHub)
Thx

**Comment by dgreif** [comment]
@jourdannorman  any updates? I'm not sure what else to recommend at this point. I really think this is a HomeKit issue, or possibly homebridge 1.2+

**Comment by jourdannorman** [comment]
The good news is that the video feeds started working correctly a couple days after our conversation. Bad news is that I’m not sure what happened to fix the issue. Anyway looks like I’m all set!

**Comment by dgreif** [comment]
Glad to hear that! 

@muflon-cmd There isn't anything to change, it's all controlled by HomeKit
