### ISSUE TITLE
Base Station and Keypads do not show "Include in Favorites" toggle in Home.app.

### ISSUE THREAD

**Issue by 3920dxb3182** [dgreif/ring#456]
# Bug Report

### Describe the Bug
Base Station and Keypads do not show "Include in Favorites" toggle in Home.app.
All other ring components do show favorites toggle.

### Additional context
Seems to have disappeared with iOS 14 update, but not sure.

### Environment

 - OS: Raspbian
 - Node.js: 12.16.1
 - NPM: 6.13.7
 - homebridge-ring: 9.9.0
 - homebridge: 1.2.2
 - hoobs: [N/A

**Comment by dgreif** [comment]
The favorites toggle is a feature of the Home app and not something that can be controlled by homebridge. Those two devices are technically not supported in the Home app, which is probably why they are behaving differently. You can remove them by setting the option '"hideUnsupportedServices": true' in your homebridge-ring config

**Comment by 3920dxb3182** [comment]
Thx.
