### ISSUE TITLE
No Livestream on home wifi - works on Ethernet and cellular

### ISSUE THREAD

**Issue by pcdocdwb** [dgreif/ring#459]
I have all my Ring cameras in Homebridge and they show in the Home App.  I can livestream the cameras from my Mac which is connected via ethernet.  I can livestream the cameras from my phone or iPad or Mac when I am on cellular at my home or away from my home.  However, I CANNOT livestream the cameras from any device when I am on my home wifi.  Doesn't make any sense.  Any ideas?  

Here is the log when streaming is successful on ethernet or cellular:

9/25/2020, 1:01:23 PM [Ring] Preparing Live Stream for Backyard
9/25/2020, 1:01:23 PM [Ring] Ding 6876471244874125067 is expired (480).  Fetching a new ding and trying video stream again
9/25/2020, 1:01:25 PM [Ring] Stream Prepared for Backyard (1.703s)
9/25/2020, 1:01:25 PM [Ring] Received stream data from Backyard (1.725s)
9/25/2020, 1:01:25 PM [Ring] Streaming active for Backyard
9/25/2020, 1:01:27 PM [Ring] Stopped Live Stream for Backyard

Here is the log when streaming is not successful on home wifi:

9/25/2020, 1:03:57 PM [Ring] Preparing Live Stream for Backyard
9/25/2020, 1:03:59 PM [Ring] Stream Prepared for Backyard (1.424s)
9/25/2020, 1:03:59 PM [Ring] Received stream data from Backyard (1.445s)
9/25/2020, 1:04:00 PM [Ring] Streaming active for Backyard
9/25/2020, 1:04:19 PM [Ring] Live stream for Backyard appears to be inactive. (21.247s)
9/25/2020, 1:04:40 PM [Ring] Stopped Live Stream for Backyard

 

# Live Streaming Issue

### Describe the live streaming issue
 A clear and concise description of the problem.  If all you can say is that "live streaming doesn't work on my network", then please do not open an issue.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Recommended solution
 Please describe what you think is causing this issue, and how you recommend it be fixed

### Environment

 - Ring Camera: [e.g. Stickup Cam Battery]
 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring (if applicable): [e.g 6.0.3 or N/A]
 - homebridge (if applicable): [e.g. 0.4.50 or N/A]
 - hoobs (if applicable): [e.g. 0.4.50 or N/A]

### Network Environment
 Please provide a detailed description of your network setup, including all network hardware between your camera, the internet, your homebridge server, and your HomeKit home hub (Apple TV, HomePod, iPad).  Please include brand and model for each device that the network traffic passes through.

**Comment by dgreif** [comment]
This is likely a bug with iOS 14.  Do you have your iPhone on iOS 14, with a HomePod as your home hub?

**Comment by pcdocdwb** [comment]
Actually, right now my iPad is my home hub, but it's usually my Apple TV.  Homepod's are on standby

**Comment by pcdocdwb** [comment]
Plus it is not just my iPhone.  If my Mac is wired, I see the stream.  If it is on wifi, the stream fails.

**Comment by dgreif** [comment]
Is your mac the device that is running homebridge, or is homebridge running somewhere else on the network?

**Comment by pcdocdwb** [comment]
Good point.  Yes, that Mac is running home bridge.  If I put the Homebridge Mac on wifi, I get no camera response anywhere.  I do see this in the log:  9/25/2020, 2:28:39 PM (node:88329) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpaired listeners added to [Bridge]. Use emitter.setMaxListeners() to increase limit

**Comment by pcdocdwb** [comment]
But even my other Mac, when on wifi with speeds of 200+ MBPS, the cameras won't live stream.

**Comment by pcdocdwb** [comment]
I do appreciate your help a lot.  I really would love to get this working, but don't know what to try next.

**Comment by pcdocdwb** [comment]
I never answered the iOS question.  Yes, my phone, iPad, and Apple TV's are all on 14

**Comment by dgreif** [comment]
This may be related to a bug in `homebridge` 1.2+.  Try installing homebridge `1.1.6` and see if it works then.

**Comment by pcdocdwb** [comment]
Ok, do I have to uninstall home bridge and start from scratch again?

**Comment by dgreif** [comment]
Nope, just run `npm i -g homebridge@1.1.6` and then restart your homebridge service

**Comment by pcdocdwb** [comment]
Installed 1.1.6 and the behavior is the same.  When on cellular on my iPhone, the cameras stream live.  When I connect via wifi, the cameras do not respond.  Frustrating.

**Comment by dgreif** [comment]
Do you have rules set up on your network to block certain traffic?

**Comment by pcdocdwb** [comment]
I figured it out with your suggestion about the network traffic.  I was using a VPN with Netmotion Mobility to work from home.  I always leave it running so forgot all about it.  As soon as I turned it off, it all works great.  Maybe time to get a Raspberry Pi.  Can I just re-install Homebridge 1.2 the same command.  Thank you so much for being patient.  Can I contribute?

**Comment by dgreif** [comment]
@pcdocdwb I’m glad it was that simple! Always easy to forget the VPN. As far as contributing, if you mean code wise, PRs are welcome if you see anything that needs updated. If you mean monetarily, there are donation links on the GitHub repo. Either form of contribution is much appreciated!
