### ISSUE TITLE
Mode security device disappeared after home bridge server reboot.

### ISSUE THREAD

**Issue by jarvismeier** [dgreif/ring#462]
I restarted my homebridge server and the security accessory that handles ring modes has disappeared from HomeKit.  I've attached any relevant Ring logs from my home bridge log file.

Sep 28 17:29:05 raspberrypi homebridge[1811]: [9/28/2020, 6:29:05 PM] [Ring] 404 from endpoint https://api.ring.com/clients_api/ring_devices
Sep 28 17:29:05 raspberrypi homebridge[1811]: [9/28/2020, 6:29:05 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
Sep 28 17:29:09 raspberrypi homebridge[1811]: [9/28/2020, 6:29:09 PM] [Ring] Creating location socket.io connection
Sep 28 17:29:11 raspberrypi homebridge[1811]: [9/28/2020, 6:29:11 PM] [Ring] Ring connected to socket.io server
Sep 28 17:29:12 raspberrypi homebridge[1811]: [9/28/2020, 6:29:12 PM] [Ring] Configuring 7 cameras and 16 devices for location "My Location" - locationId: c96ur8-23ub-0
Sep 28 17:29:12 raspberrypi homebridge[1811]: [9/28/2020, 6:29:12 PM] [Ring] Hidden accessory c9a5171b-d430-4b20-b04e-6789300acc7b adapter.ringnet RingNet Adapter

**Comment by jarvismeier** [comment]
Issue fixed itself.  Assuming an issue with the ring API

**Comment by dgreif** [comment]
Glad to hear that @jarvismeier. I don't have an account set up with basic location modes currently so it was going to be a pain to test 😅. Thanks for keeping me up to date!
