### ISSUE TITLE
After Installation and Configuration no Ring Accessories are added to HomeKit

### ISSUE THREAD

**Issue by arejay73** [dgreif/ring#465]
# Bug Report

### Describe the Bug
I have loaded the Homebridge-ring plugin into the Homebridge-UX and followed configuration instructions.  After restarting Homebridge I see no errors in the log, but not accessories are available in the home app.

### To Reproduce
Restart Homebridge
look in the logs for errors, non.
Open Home app and expect to see my ring accessories.  Nothing is available.

### Expected behavior
Open Home app and expect to see my ring accessories.
See my ring alarm sensors and view their status via the Home app.
Create some automations based on the sensors values.

### Screenshots/Logs
```
[10/1/2020, 3:18:28 PM] Homebridge v1.2.3 is running on port 59443.
[10/1/2020, 3:20:42 PM] [Config] Homebridge Reset: New Username: XX:XX:XX:XX:XX:XX
[10/1/2020, 3:20:42 PM] [Config] Homebridge Reset: New Pin: 000-00-000
[10/1/2020, 3:20:42 PM] [Config] Changes to config.json saved.
[10/1/2020, 3:20:42 PM] [Config] Homebridge Reset: "persist" directory removed.
[10/1/2020, 3:20:42 PM] [Config] Homebridge Reset: "accessories" directory removed.
[10/1/2020, 3:20:42 PM] [Config] Homebridge restart request received
[10/1/2020, 3:20:42 PM] [Config] No restart command defined, killing process...
[10/1/2020, 3:20:42 PM] [HB Supervisor] Stopping services...
[10/1/2020, 3:20:42 PM] Got SIGTERM, shutting down Homebridge...
[10/1/2020, 3:20:47 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[10/1/2020, 3:20:50 PM] [HB Supervisor] Homebridge Storage Path: /Users/xxxx/.homebridge
[10/1/2020, 3:20:50 PM] [HB Supervisor] Homebridge Config Path: /Users/xxx/.homebridge/config.json
[10/1/2020, 3:20:50 PM] [HB Supervisor] Logging to /Users/xxx/.homebridge/homebridge.log
[10/1/2020, 3:20:50 PM] [HB Supervisor] OS: Darwin 19.6.0 x64
[10/1/2020, 3:20:50 PM] [HB Supervisor] Node.js v14.9.0 /usr/local/Cellar/node/14.9.0/bin/node
[10/1/2020, 3:20:50 PM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[10/1/2020, 3:20:50 PM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[10/1/2020, 3:20:50 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[10/1/2020, 3:20:50 PM] [HB Supervisor] Started Homebridge v1.2.3 with PID: 48673
[10/1/2020, 3:20:50 PM] Loaded config.json with 2 accessories and 2 platforms.
[10/1/2020, 3:20:50 PM] ---
[10/1/2020, 3:20:50 PM] Loaded plugin: homebridge-cmdswitch2@0.2.10
[10/1/2020, 3:20:50 PM] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
[10/1/2020, 3:20:50 PM] ---
[10/1/2020, 3:20:50 PM] Loaded plugin: homebridge-config-ui-x@4.28.0
[10/1/2020, 3:20:50 PM] Registering platform 'homebridge-config-ui-x.config'
[10/1/2020, 3:20:50 PM] ---
[10/1/2020, 3:20:50 PM] Loaded plugin: homebridge-ring@9.9.0
[10/1/2020, 3:20:50 PM] Registering platform 'homebridge-ring.Ring'
[10/1/2020, 3:20:50 PM] ---
[10/1/2020, 3:20:50 PM] Loaded plugin: homebridge-roomba-stv@1.6.0
[10/1/2020, 3:20:50 PM] Registering accessory 'homebridge-roomba-stv.Roomba'
[10/1/2020, 3:20:50 PM] ---
[10/1/2020, 3:20:50 PM] Loading 2 platforms...
[10/1/2020, 3:20:50 PM] [Config] Initializing config platform...
[10/1/2020, 3:20:50 PM] [Config] Running in Service Mode
[10/1/2020, 3:20:50 PM] [Ring] Initializing Ring platform...
[10/1/2020, 3:20:50 PM] Loading 2 accessories...
[10/1/2020, 3:20:50 PM] [Roomba Downstairs] Initializing Roomba accessory...
[10/1/2020, 3:20:50 PM] [Roomba Downstairs] Enabling keepAlive
[10/1/2020, 3:20:51 PM] [Config] Homebridge Config UI X v4.28.0 is listening on :: port 8581
[10/1/2020, 3:20:50 PM] [Roomba Upstairs] Initializing Roomba accessory...
[10/1/2020, 3:20:50 PM] [Roomba Upstairs] Enabling keepAlive
[10/1/2020, 3:20:50 PM] [Ring] didFinishLaunching
Setup Payload:
X-HM://0024W3JCEG7C3
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 000-00-000 │     
    └────────────┘     
                       
[10/1/2020, 3:20:51 PM] Homebridge v1.2.3 is running on port 59443.
[10/1/2020, 3:21:18 PM] [Roomba Downstairs] Running status requested
[10/1/2020, 3:21:18 PM] [Roomba Downstairs] Battery status requested
[10/1/2020, 3:21:18 PM] [Roomba Upstairs] Running status requested
[10/1/2020, 3:21:18 PM] [Roomba Upstairs] Battery status requested
[10/1/2020, 3:22:23 PM] [Roomba Upstairs] Charging status requested
[10/1/2020, 3:22:23 PM] [Roomba Upstairs] Battery level requested
[10/1/2020, 3:22:29 PM] [Roomba Downstairs] Battery level requested
[10/1/2020, 3:22:29 PM] [Roomba Downstairs] Charging status requested
```

### Additional context
I have tried multiple resets and removed and re-added the bridge with the same results.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

{
    "bridge": {
        "name": "Homebridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 59443,
        "pin": "000-00-000"
    },
    "description": "Homebridge",
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "debug": false,
            "platform": "config"
        },
        {
            "refreshToken": "xxx",
            "debug": true,
            "platform": "Ring"
        }
    ],
    "accessories": [
        {
            "accessory": "Roomba",
            "name": "Roomba Downstairs",
            "model": "960",
            "blid": "xxx",
            "robotpwd": "xxx",
            "ipaddress": "xxx",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": true,
            "cacheTTL": 30
        },
        {
            "accessory": "Roomba",
            "name": "Roomba Upstairs",
            "model": "960",
            "blid": "xxx",
            "robotpwd": "xxx",
            "ipaddress": "xxx",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": true,
            "cacheTTL": 30
        }
    ]
}

```

### Environment
 - OS: MacOS 10.15.7
 - Node.js: v14.9.0
 - NPM: 6.14.8
 - homebridge-ring: 9.9.0
 - homebridge: 1.2.3
 - hoobs: N/A

**Comment by dgreif** [comment]
Unfortunately there isn't enough in the logs for me to go off of. The last valuable line is `[Ring] didFinishLaunching`, which means it's about to connect to the api and fetch your devices/locations.  Are there any logs that start with `[Ring]` further down?  

Another thing you can try is to follow the steps in https://github.com/dgreif/ring/wiki/Data-Discovery to see if the basic ring client is able to connect and fetch your devices.

**Comment by arejay73** [comment]
I just tried to run the command and it hangs.  It is because I have two factor authentication?  But when I rant through setup it asked for my two factor credentials.  This command is not.

**Comment by dgreif** [comment]
The command should ask for your 2fa token.  It's possible that Ring is having some issues with authentication today.  I can't think of another scenario that would cause that CLI to just hang.

**Comment by arejay73** [comment]
Tried again and his is what I get:

```
$ ring-device-data-cli
This CLI will log data from you Ring Account to help debug issues and discovering new device types.
The logged data is anonymized and should not compromise your account in any way.
Email: XXX@XXX.COM
Password: ********
```

The command just hangs and doesn't ask for anything else after password.

**Comment by dgreif** [comment]
Can you try logging into ring.com from your browser and then try the CLI again?  I'm really not sure why it's not proceeding to the 2fa step for you. Without anything being logged, it's really hard to debug.

**Comment by arejay73** [comment]
So, I was able to login to the ring website.  I tried the command again and it still hangs.  I have two factor setup as email not text.  I went into my ring account and cleared out all authorize devices and tried to re-add Homebridge-ring.  It appears that it has connected, but shows up as an UnknownDevice authorized device.  The CLI still hangs.

**Comment by arejay73** [comment]
Just tried this again.  I tried to reconfigure the plugin from the Homebridge-UX and when I get to the point to verify the token via code.  It says invalid code.  I can login to the ring website and access my account just fine.

I tried the command utility again: ring-device-data-cli.  Same behavior it just hangs there.  I can't breakout I have close the terminal window to stop the process.

Any other things I could try?

**Comment by anthonyallure** [comment]
I had this issue too, but only when the verification code started with a 0 (zero).

**Comment by dgreif** [comment]
@arejay73 I'm really at a loss on this.  It seems that you are the only one having this issue.  Based on your comments from previous issues, I'm guessing you have had it working in the past, so I'm not sure why it would have stopped suddenly.  The only other idea would be to run the `ring-auth-cli` from a different computer if you haven't tried that already.

**Comment by dallen** [comment]
I've had this exact same issue for several weeks now as well. Upgrading my node.js from 14.10 to 14.13.1 just now fixed it.

**Comment by dgreif** [comment]
@dallen Thanks for the insight! @arejay73 Could you try updating node?

**Comment by arejay73** [comment]
Just tried and I am getting the same behavior.  This is very strange.  I am at a loss.

**Comment by dgreif** [comment]
@arejay73 maybe try node `12.19.0` instead

**Comment by arejay73** [comment]
@dgreif I get a "login failure" from the Homebridge UI when I try to authenticate with ring plug-in and put in the auth code from ring.

**Comment by dgreif** [comment]
@arejay73 does that happen when you submit your email/password, or when you enter the auth code?  Do you ever get to the auth code screen?

**Comment by dgreif** [comment]
@arejay73 there were similar issues reported in #471.  Sounds like they just updated the plugin and then it worked.  Maybe try restarting your homebridge server

**Comment by leefc01** [comment]
I have a similar issue.  No accessories appear in Home.  

Adding my log in case it helps.

Apologies if I should open a separate issue.  New to homebridge and HOOBS.

Separately, Nest is working.

Environment

- RPi2B
- HOOBS v. 3.2.9
- Node v. 12.16.3
- Homebridge-ring v. 9.12.1

`10/23/2020, 5:00:36 PM HOOBS listening on port 80.
10/23/2020, 5:00:44 PM Loaded plugin 'homebridge-nest'
10/23/2020, 5:00:45 PM [10/23/2020, 6:00:45 PM] Registering platform 'homebridge-nest.Nest'
10/23/2020, 5:00:49 PM Loaded plugin 'homebridge-ring'
10/23/2020, 5:00:49 PM [10/23/2020, 6:00:49 PM] Registering platform 'homebridge-ring.Ring'
10/23/2020, 5:00:49 PM Loading 2 platforms...
10/23/2020, 5:00:49 PM [Nest] Initializing Nest platform...
10/23/2020, 5:00:49 PM [Ring] Initializing Ring platform...
10/23/2020, 5:00:49 PM [Nest] Fetching Nest devices.
10/23/2020, 5:00:49 PM Bridge is running on port 51826.
10/23/2020, 5:01:06 PM [Ring] Creating location socket.io connection
10/23/2020, 5:01:06 PM [Ring] Location Mode: {"mode":"unset","securityStatus":{},"readOnly":true,"notYetParticipatingInMode":[],"responseTimestamp":1603497666000}
10/23/2020, 5:01:06 PM [Ring] Configuring 4 cameras and 4 devices for location "San Francisco" - locationId: 71614953-6e36-45a4-bd44-d04b2c7e8504
10/23/2020, 5:01:06 PM [Ring] Adding new accessory 1135401b-0c4e-40cb-9be1-7290d705bae3 jbox_v1 Front Door
10/23/2020, 5:01:06 PM [Ring] Adding new accessory 4328a4cf-38bc-4562-8037-89c6c94a9543 hp_cam_v1 Backyard
10/23/2020, 5:01:06 PM [Ring] Adding new accessory 132aa2dc-8bb5-4ee8-a39b-c6691195412e hp_cam_v1 Front
10/23/2020, 5:01:06 PM [Ring] Adding new accessory 533326dd-1263-436e-b5c9-889830b064cd hp_cam_v1 Garage
10/23/2020, 5:01:07 PM [Ring] Ring connected to socket.io server
10/23/2020, 5:01:07 PM [Ring] Ring base_station_v1 b37df953-0462-44fc-6d52-45a81bcc48ad is offline or on cellular backup.  Waiting for status to change
10/23/2020, 5:01:10 PM [Nest] initing home_away_sensor "Home Occupied": deviceId: 451c8af0-090f-11eb-8082-0ef710f23a70 structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/23/2020, 5:01:10 PM [Nest] initing protect "Hallway": deviceId: 18B4300000F32170 structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/23/2020, 5:01:10 PM [Nest] initing protect "Office": deviceId: 18B4300000F29873 structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/23/2020, 5:01:10 PM [Nest] initing protect "Downstairs": deviceId: 18B4300000F3A3A0 structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/23/2020, 5:01:10 PM [Nest] initing protect "Master Bedroom": deviceId: 18B4300000F27FEE structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/23/2020, 5:01:10 PM [Nest] initing protect "Den": deviceId: 18B4300000F2800D structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/23/2020, 5:01:10 PM [Nest] initing protect "Basement": deviceId: 18B4300000F3A6FC structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/23/2020, 5:01:10 PM [Nest] initing protect "Kids Room": deviceId: 18B4300000F286DC structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/23/2020, 5:01:10 PM [Nest] initing protect "K Office": deviceId: 18B4300000F38AD4 structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/23/2020, 5:01:10 PM [Nest] initing protect "Entryway": deviceId: 18B4300000F38C6F structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/23/2020, 5:02:18 PM [Ring] Garage Detected Motion. Loading snapshot before sending event to HomeKit
10/23/2020, 5:02:18 PM [Ring] Loading new snapshot into cache for Garage
10/23/2020, 5:02:19 PM [Ring] Snapshot cached for Garage (0.44s)`

**Comment by dgreif** [comment]
@leefc01  the logs show that your base station is offline. The plugin intentionally waits until all base stations are online so that accessories don't get deleted by accident. I suggest you bring it back online, or remove it from your ring account if it's not used anymore

**Comment by leefc01** [comment]
> @leefc01 the logs show that your base station is offline. The plugin intentionally waits until all base stations are online so that accessories don't get deleted by accident. I suggest you bring it back online, or remove it from your ring account if it's not used anymore

Thanks for the quick analysis.  My situation might be an edge case, but I can't seem to remove the offline base station.  It's for a place where I used to live, but no longer have access.  

I tried removing the device, but since it's offline, Ring won't let me.

I also added the device ID to the Hide Device ID parameter, but that didn't have an impact.

**Comment by dgreif** [comment]
@leefc01  that's unfortunate. If it's listed under a location that you don't care about anymore, you can use specific location ids in your config to select only the locations you do want. That's probably the only way around waiting for the bridge.

**Comment by leefc01** [comment]
> @leefc01 that's unfortunate. If it's listed under a location that you don't care about anymore, you can use specific location ids in your config to select only the locations you do want. That's probably the only way around waiting for the bridge.

@dgreif 
Thanks for the ideas. Added the Location ID to the Hide list and rebooted.  Didn't seem to make a difference.
Used the Location ID from the Ring.com URL ("l" parameter) as I didn't see Location ID anywhere in logs.

''''
10/24/2020, 12:32:13 PM Got SIGINT, shutting down Bridge...
10/24/2020, 12:32:24 PM Loaded plugin 'homebridge-nest'
10/24/2020, 12:32:24 PM [10/24/2020, 1:32:24 PM] Registering platform 'homebridge-nest.Nest'
10/24/2020, 12:32:27 PM Loaded plugin 'homebridge-ring'
10/24/2020, 12:32:27 PM [10/24/2020, 1:32:27 PM] Registering platform 'homebridge-ring.Ring'
10/24/2020, 12:32:27 PM Loading 2 platforms...
10/24/2020, 12:32:27 PM [Nest] Initializing Nest platform...
10/24/2020, 12:32:27 PM [Ring] Initializing Ring platform...
10/24/2020, 12:32:27 PM [Nest] Fetching Nest devices.
10/24/2020, 12:32:28 PM Bridge is running on port 51826.
10/24/2020, 12:32:32 PM [Ring] Creating location socket.io connection
10/24/2020, 12:32:32 PM [Ring] Ring connected to socket.io server
10/24/2020, 12:32:32 PM [Ring] Ring base_station_v1 b37df953-0462-44fc-6d52-45a81bcc48ad is offline or on cellular backup.  Waiting for status to change
10/24/2020, 12:32:36 PM [Nest] initing home_away_sensor "Home Occupied": deviceId: 451c8af0-090f-11eb-8082-0ef710f23a70 structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/24/2020, 12:32:36 PM [Nest] initing protect "Hallway": deviceId: 18B4300000F32170 structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/24/2020, 12:32:36 PM [Nest] initing protect "Office": deviceId: 18B4300000F29873 structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/24/2020, 12:32:36 PM [Nest] initing protect "Downstairs": deviceId: 18B4300000F3A3A0 structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/24/2020, 12:32:36 PM [Nest] initing protect "Master Bedroom": deviceId: 18B4300000F27FEE structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/24/2020, 12:32:36 PM [Nest] initing protect "Den": deviceId: 18B4300000F2800D structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/24/2020, 12:32:36 PM [Nest] initing protect "Basement": deviceId: 18B4300000F3A6FC structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/24/2020, 12:32:36 PM [Nest] initing protect "Kids Room": deviceId: 18B4300000F286DC structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/24/2020, 12:32:36 PM [Nest] initing protect "K Office": deviceId: 18B4300000F38AD4 structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
10/24/2020, 12:32:36 PM [Nest] initing protect "Entryway": deviceId: 18B4300000F38C6F structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
''''

**Comment by leefc01** [comment]
> > @leefc01 that's unfortunate. If it's listed under a location that you don't care about anymore, you can use specific location ids in your config to select only the locations you do want. That's probably the only way around waiting for the bridge.
> 
> @dgreif
> Thanks for the ideas. Added the Location ID to the Hide list and rebooted. Didn't seem to make a difference.
> Used the Location ID from the Ring.com URL ("l" parameter) as I didn't see Location ID anywhere in logs.
> 
> ```
> 10/24/2020, 12:32:13 PM Got SIGINT, shutting down Bridge...
> 10/24/2020, 12:32:24 PM Loaded plugin 'homebridge-nest'
> 10/24/2020, 12:32:24 PM [10/24/2020, 1:32:24 PM] Registering platform 'homebridge-nest.Nest'
> 10/24/2020, 12:32:27 PM Loaded plugin 'homebridge-ring'
> 10/24/2020, 12:32:27 PM [10/24/2020, 1:32:27 PM] Registering platform 'homebridge-ring.Ring'
> 10/24/2020, 12:32:27 PM Loading 2 platforms...
> 10/24/2020, 12:32:27 PM [Nest] Initializing Nest platform...
> 10/24/2020, 12:32:27 PM [Ring] Initializing Ring platform...
> 10/24/2020, 12:32:27 PM [Nest] Fetching Nest devices.
> 10/24/2020, 12:32:28 PM Bridge is running on port 51826.
> 10/24/2020, 12:32:32 PM [Ring] Creating location socket.io connection
> 10/24/2020, 12:32:32 PM [Ring] Ring connected to socket.io server
> 10/24/2020, 12:32:32 PM [Ring] Ring base_station_v1 b37df953-0462-44fc-6d52-45a81bcc48ad is offline or on cellular backup.  Waiting for status to change
> 10/24/2020, 12:32:36 PM [Nest] initing home_away_sensor "Home Occupied": deviceId: 451c8af0-090f-11eb-8082-0ef710f23a70 structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
> 10/24/2020, 12:32:36 PM [Nest] initing protect "Hallway": deviceId: 18B4300000F32170 structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
> 10/24/2020, 12:32:36 PM [Nest] initing protect "Office": deviceId: 18B4300000F29873 structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
> 10/24/2020, 12:32:36 PM [Nest] initing protect "Downstairs": deviceId: 18B4300000F3A3A0 structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
> 10/24/2020, 12:32:36 PM [Nest] initing protect "Master Bedroom": deviceId: 18B4300000F27FEE structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
> 10/24/2020, 12:32:36 PM [Nest] initing protect "Den": deviceId: 18B4300000F2800D structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
> 10/24/2020, 12:32:36 PM [Nest] initing protect "Basement": deviceId: 18B4300000F3A6FC structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
> 10/24/2020, 12:32:36 PM [Nest] initing protect "Kids Room": deviceId: 18B4300000F286DC structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
> 10/24/2020, 12:32:36 PM [Nest] initing protect "K Office": deviceId: 18B4300000F38AD4 structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
> 10/24/2020, 12:32:36 PM [Nest] initing protect "Entryway": deviceId: 18B4300000F38C6F structureId: 451c8af0-090f-11eb-8082-0ef710f23a70
> ```

Actually, I can see in the logs that the online accessories no longer throw a log statement about being added.  That's progress.  For whatever reason, I can't still see them through Homekit, though.  Added the debug flag for the logging, but no additional details on the issue.

**Comment by dgreif** [comment]
Sorry, I should have been more clear. Rather than using the hide setting, use '"locationIds": ["good id here"]' to specify the locations you want to have show up in HomeKit. The location ids are logged during the plugin startup, tho you may not get to that point in the logs with the bridge offline. Pulling the location ids from the url in ring.com works too!

**Comment by leefc01** [comment]
@dgreif - Using the "good" Location ID worked.  Sorry I should've read the documentation more closely.

Thanks for all the help.  Testing the functionality now.

**Comment by dgreif** [comment]
Closing since @arejay73 hasn't followed up in quite a while.  Let me know if you are still having issues.
