### ISSUE TITLE
Changed Ring Password

### ISSUE THREAD

**Issue by jourdannorman** [dgreif/ring#467]
I changed my password on my Ring account. How do I update the HOOBs plugin to ensure everything works correctly? I would like to avoid uninstalling so that I don't have to set up my devices all over again in Homekit.

**Comment by dgreif** [comment]
You definitely don't need to uninstall everything. You should reboot HOOBS and see if it works without any changes. If it doesn't, you just need to generate a new refreshToken. The HOOBS page for the plugin has details on how to do that.
