### ISSUE TITLE
Integrity error installing on Hoobs

### ISSUE THREAD

**Issue by far-north** [dgreif/ring#476]
# Bug Report

### Describe the Bug
When attempting install in Hoobs, logs show that there was an issue with the integrity of the download.

### To Reproduce
 - Log into Hoobs, navigate to Plugins screen
 - Search for "ring" and click install for the resulting plugin
 - Plug appears to begin installation and then stops with no result.

### Expected behavior
Plugin should install and home bridge service should restart ready to configure.

### Screenshots/Logs
15/10/2020, 12:55:26  ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
15/10/2020, 12:55:26 npm
15/10/2020, 12:55:26 ERR! Invalid response body while trying to fetch https://registry.npmjs.org/homebridge-ring: Integrity verification failed for sha512-6zRIuNq16aGS2WVOcm74VLUCNWP1muNjSdu06B2p70Ut+1JM0xJcS77FKoXrh8QBDV/KuOifJBVWSCVIHPi0Wg== (/home/hoobs/.npm/_cacache/content-v2/sha512/eb/34/48b8dab5e9a192d9654e726ef854b5023563f59ae36349dbb4e81da9ef452dfb524cd3125c4bbec52a85eb87c4010d5fcab8e89f2415564825481cf8b45a)
15/10/2020, 12:55:26 
15/10/2020, 12:55:26 npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-10-15T11_55_26_348Z-debug.log
### Homebridge Ring Config
N/A as cannot install

### Environment
 - OS: Raspbian 4.19.97-v7+
 - Node.js: v12.16.3
 - NPM: 6.14.4
 - homebridge-ring: 9.11.0
 - homebridge: 1.2.3
 - hoobs: 3.2.6

**Comment by far-north** [comment]
Debug log as noted above:

`cat /home/hoobs/.npm/_logs/2020-10-15T11_55_26_348Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--prefer-offline',
1 verbose cli   '--no-audit',
1 verbose cli   '--unsafe-perm',
1 verbose cli   '--progress=true',
1 verbose cli   'homebridge-ring@9.11.0'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose npm-session 9148036dc37292dc
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for homebridge-ring@9.11.0 Invalid response body while trying to fetch https://registry.npmjs.org/homebridge-ring: Integrity verification failed for sha512-6zRIuNq16aGS2WVOcm74VLUCNWP1muNjSdu06B2p70Ut+1JM0xJcS77FKoXrh8QBDV/KuOifJBVWSCVIHPi0Wg== (/home/hoobs/.npm/_cacache/content-v2/sha512/eb/34/48b8dab5e9a192d9654e726ef854b5023563f59ae36349dbb4e81da9ef452dfb524cd3125c4bbec52a85eb87c4010d5fcab8e89f2415564825481cf8b45a)
8 timing stage:rollbackFailedOptional Completed in 3ms
9 timing stage:runTopLevelLifecycles Completed in 3372ms
10 verbose type system
11 verbose stack FetchError: Invalid response body while trying to fetch https://registry.npmjs.org/homebridge-ring: Integrity verification failed for sha512-6zRIuNq16aGS2WVOcm74VLUCNWP1muNjSdu06B2p70Ut+1JM0xJcS77FKoXrh8QBDV/KuOifJBVWSCVIHPi0Wg== (/home/hoobs/.npm/_cacache/content-v2/sha512/eb/34/48b8dab5e9a192d9654e726ef854b5023563f59ae36349dbb4e81da9ef452dfb524cd3125c4bbec52a85eb87c4010d5fcab8e89f2415564825481cf8b45a)
11 verbose stack     at Readable.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:195:14)
11 verbose stack     at Readable.emit (events.js:310:20)
11 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/cache.js:92:30
11 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
11 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
11 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
11 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:695:18)
11 verbose stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
11 verbose stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
11 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
11 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose stack     at processImmediate (internal/timers.js:456:21)
12 verbose cwd /home/hoobs/.hoobs
13 verbose Linux 4.19.97-v7+
14 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--prefer-offline" "--no-audit" "--unsafe-perm" "--progress=true" "homebridge-ring@9.11.0"
15 verbose node v12.16.3
16 verbose npm  v6.14.4
17 error code EINTEGRITY
18 error errno EINTEGRITY
19 error Invalid response body while trying to fetch https://registry.npmjs.org/homebridge-ring: Integrity verification failed for sha512-6zRIuNq16aGS2WVOcm74VLUCNWP1muNjSdu06B2p70Ut+1JM0xJcS77FKoXrh8QBDV/KuOifJBVWSCVIHPi0Wg== (/home/hoobs/.npm/_cacache/content-v2/sha512/eb/34/48b8dab5e9a192d9654e726ef854b5023563f59ae36349dbb4e81da9ef452dfb524cd3125c4bbec52a85eb87c4010d5fcab8e89f2415564825481cf8b45a)
20 verbose exit [ 1, true ]`

**Comment by dgreif** [comment]
@far-north sorry to hear you are having issues, but this is not a problem with the actual plugin.  It's possible that NPM is having issues, or it could be something weird in the HOOBS environment.  I suggest you open an issue with the HOOBS team as they may have seen this issue before

**Comment by far-north** [comment]
Thanks @dgreif 

It looks like it was an issue with the npm cache.

I resolved by running `npm cache verify`
