### ISSUE TITLE
2FA codes with leading zeroes do not work

### ISSUE THREAD

**Issue by slobatch** [dgreif/ring#477]
# Bug Report

### Describe the Bug
 When logging into your Ring account, if the 2FA code entered has one or more leading zeroes (e.g. 012345), the 2FA will fail.

### To Reproduce
1. Start Homebridge
2. Install Ring plugin
3. Enter username and password to receive 2FA prompt
  1. If 2FA code does not start with zero, log into Ring.com and try step 3 again to receive a new 2FA code.
  2. Repeat step 3.1 until you receive a 2FA code with a leading zero.
4. Observe failed 2FA, even if code entered correctly.

### Expected behavior
 Any 2FA code, even one with leading zeros, if entered correctly, should allow user to login successfully.

### Additional context
 My hunch is that the 2FA code input is treated as an integer or "number", and upon submission, leading zeros are truncated. This hunch is supported by the field type and the up and down arrows on the right side of the field.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

        {
            "refreshToken": "xxxx",
            "avoidSnapshotBatteryDrain": true,
            "platform": "Ring"
        }

```

### Environment

 - OS: Raspbian
 - Node.js: v12.19.0
 - NPM: v6.14.8
 - homebridge-ring: v9.11.0
 - homebridge: v1.2.3
 - hoobs: N/A

**Comment by dgreif** [comment]
@slobatch thanks for reporting.  This has actually already been addressed in #471 and has been fixed in https://github.com/oznu/homebridge-config-ui-x/commit/d1d7aa39919975cb1e8e32beecb156a26ee512c8 .  The fix should be in the next release of homebridge-config-ui-x.

**Comment by slobatch** [comment]
Thanks @dgreif — didn’t occur to me to look in closed issues. And no wonder I couldn’t find the code that handled this in your plugin’s repo!

**Comment by dgreif** [comment]
@slobatch no problem! It was kind of a side conversation that spun out of that other issue so it wasn't super easy to find.  And it's also not obvious that the UI code isn't part of the plugin.  @oznu was super generous to add that directly into his UI.  Hopefully we can find a way for plugins to eventually supply their own UI but it's a pretty tricky problem to solve.
