### ISSUE TITLE
Home Assistant Support

### ISSUE THREAD

**Issue by kimme1024** [dgreif/ring#485]
# Feature Request

### Description
Hi,

I know this has nothing to do with homebridge but I recently switched to Home Assistant Core to be able to have more control over the automations and the fact that I needed to build my own multi-room thermostat system...

The only thing that I really miss over there is decent Ring support. There is a Ring plugin which can trigger motion and button and displays your last motion video but there's no 2 way-talk support.

I have no idea how difficult it'd be to port this to Home Assistant but your homebridge-plugin is VERY superior to the existing HA-plugin.

If it'd be impossible I'll keep running homebridge just for your plugin but I'm trying to implement everything into one system.

### Describe the solution you'd like
Please port your HB-plugin to HA if possible! :D

### Describe alternatives you've considered
The existing plugin but it's too limited.

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dgreif** [comment]
@kimme1024 I don't personally use Home Assistant.  I think that would be a great project for someone to tackle in a separate repo, but it's not something I'm looking to add here.  Unfortunately my free time has been stretched thin lately, and maintaining the homebridge plugin is all I really have time for right now.
