### ISSUE TITLE
9.12.2 Seems to be slow comparing to other RTSP FFMpeg streams on Cellular

### ISSUE THREAD

**Issue by rog889** [dgreif/ring#486]
# Live Streaming Issue

### Describe the live streaming issue
When I am on LTE cellular, all the feeds from Ring cameras would take almost 10 to 15 seconds to display the snapshots of each of my 4 Ring cameras. But all of my 12 RTSP cameras' snapshots would show up in 1 to 2 seconds. My firewall at home would alert me that my Apple TV 3 is streaming directly to my iPhone. Just wondering if this is the case that, the Apple TV is doing the actual streaming of all of my Ring Cameras feeds to my phone. If so, how can I improve the performance and speed of showing the snapshots and Ring video feeds? Would upgrade to HomePod or Apple TV 4K would help? or would upgrade of the Raspberry pi to a 8 core Linux help?

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Recommended solution
 Please describe what you think is causing this issue, and how you recommend it be fixed

### Environment

 - Ring Camera: Ring Doorbell Pro and Wired Stick Up Outdoor Cam
 - OS: Raspbian
 - Node.js:  12.14.1
 - NPM: 6.13.4
 - homebridge-ring (if applicable): 9.12.2
 - homebridge (if applicable): 1.6.1
 - hoobs (if applicable): N/A

### Network Environment
Apple TV 4, Raspberry pi 4, all GigE, no Wifi. The Stick up Cams are PoE, and Ring Doorbell Pro is wired with 16v.

**Comment by rog889** [comment]
All of my Ring cameras are NOT battery powered, they are either PoE or powered by 16v transformer.

**Comment by dgreif** [comment]
Sorry to hear you are having some speed issues.  Unfortunately it's probably just a side effect of the complex path the snapshots and live stream have to go through.  See https://github.com/dgreif/ring/wiki/Camera-Troubleshooting#live-stream-quality for details on the full setup. I can't speak to whether or not an apple tv 3 would be slower than other options, but I think it mainly just forwards along the packets so it's more about network speeds.
