### ISSUE TITLE
No audio input from ring doorbel

### ISSUE THREAD

**Issue by zilnik1234** [dgreif/ring#487]
I have a ring doorbell 2 and it seems after the last update that i made on ring plugin for homebridge i'am not able to hear any sound from the doorbell in live mode. I have the speaker slider and everything..but no 
I'm using hoobs on latest version

**Comment by dgreif** [comment]
@zilnik1234 audio should be working fine in the latest version.  For testing purposes, you could try downgrading to the previous version and testing audio again.  You should also check your logs and post any logs generated during a call here.  Without more info, there isn't much I can do to help.

**Comment by dgreif** [comment]
@zilnik1234 any updates?

**Comment by zilnik1234** [comment]
I just updated with the latest version and nkw is working perfect! 
Thank a lot!
