### ISSUE TITLE
ring-auth-cli not returning a token

### ISSUE THREAD

**Issue by thesteev** [dgreif/ring#490]
Hello,

I'm having some challenges getting my homebridge-ring plug-in working again after my 2FA was activated.

When I try to use the config-x UI to login, I get a generic error "login failed"

When I try to generate the token from terminal using ring-auth-cli, the app never returns my token. It just sits there until I force quit the command.

Not sure what I'm doing wrong here but I expect this isn't supposed to be the case...

**Comment by dgreif** [comment]
What version of node are you on? Please try either the latest node 12 or 14

**Comment by a1980h** [comment]
Same here using Homebridge v1.1.6 and running the plugin homebridge-ring v9.12.2

**Comment by dgreif** [comment]
@a1980h I would ask you the same question, which version of `node` are you on?  You can get it by running `node -v`

**Comment by thesteev** [comment]
> What version of node are you on? Please try either the latest node 12 or 14

@dgreif I'm running Homebridge v1.2.3, node.js 12.16.2, and npm 6.14.4

**Comment by thesteev** [comment]
I was able to isolate the problem. I changed internet providers and my DNS was no longer available, which caused a long series of problems, including this issue. 

On another note, I upgraded everything to the latest—so thanks for the recommendation.
