### ISSUE TITLE
BUG: live feed stops: Ring camera live feed refresh (on fail or timeout)

### ISSUE THREAD

**Issue by jneuringer** [dgreif/ring#492]
Looking to get the live feed feature have an built in auto-refresh at 60 seconds.  My cameras seems to disconnect / stop for one reason or another at 70 seconds.  

### Hello Team, I'm trying to use a ring camera to display on a screen continuously through the homebridge / hoobs system, specifically on an apple TV.  But the Ring cameras each time out on live feed after 60 seconds to 5 minutes
 A clear and concise description of the problem or missing capability...

### would be great if the feed would display the last live frame while refreshing on 60 second interval (or 30) so that I could effectively have continuous feed (with a possible quick pause every minute. (acceptable).  

 If you have a solution in mind, please describe it.

### FYI, I'm using Hoobs 3, with 3.2.9 software and the latest ring plugin.
Intend on displaying out an apply TV (since I cant seem to make it come out the HOOBS HDMI, but if you know how to do that, great!

 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by jneuringer** [comment]
Looks like this hasnt even been read yet?  did I do something wrong in the postin?

**Comment by dgreif** [comment]
@jneuringer the stream ending after a certain period of time is being enforced by Ring. The main goal for the plugin is to make it easy to quickly view your cameras when someone is at the door, not necessarily to have a 24x7 live stream going on your TV.  If you do that, Ring will be recording your camera 24x7, which means lots of storage cost on their end.  I don't really want to raise any red flags by ramping up storage costs for them.  Still, I'll see if I can get it to stream longer than 70 seconds.  No promises on when I'll get time to look into it tho.

**Comment by jneuringer** [comment]
Thanks Dusty…  

I’m actually trying to create a feature window in my windowless office (for 1 camera) to display on 1 screen while i’m in the office (not 24/7 but maybe a few hours a day)..  If the thing refreshed every minute or two that would work…

or alternatively, rather than live video, what about a frame a second?

Thanks in advance.
Jeremy

**Comment by dgreif** [comment]
Your use case makes sense, but is definitely outside the norm, and not necessarily something that needs to be supported by the homebridge plugin. If you are a developer, you may be able to accomplish your goal using the ring-client-api node module, but you are on your own for implementation if you go that route. Since this isn't an immediate need for most plugin users, I'm going to close this issue. Not saying I won't ever make it possible to stream longer than 70 seconds, but it's not a high priority right note.

**Comment by jneuringer** [comment]
sadly i'm not a developer...  and as such..  my dreams are dashed..  lol.
