### ISSUE TITLE
Motion Notification from Doorbell Pings HomePods

### ISSUE THREAD

**Issue by dubofodin** [dgreif/ring#499]
# Bug Report

### Describe the Bug
 Motion triggering on the Doorbell will set off all HomePods to chime as if someone is at the door. I've disabled the new tvOS 14 notification options, issue still persists. Apologies if I selected the wrong category. 

### To Reproduce
 - Have motion notifications enabled in ring
- Person walks by doorbell, motion detected, triggers HomePod.

Note: Motion notifications are disabled in the Home app. 

### Expected behavior
 The HomePods not do a doorbell chime when there's motion and motion notifications are disabled in Home app. 
<img width="789" alt="Screen Shot 2020-11-23 at 12 47 56 PM" src="https://user-images.githubusercontent.com/74931060/100008019-1ff7c380-2d8a-11eb-963f-6a24a4ecfb9d.png">

### Screenshots/Logs
 Log attached of this activity. 

### Additional context
 Thanks for a great plugin! 
<img width="777" alt="Screen Shot 2020-11-23 at 12 48 51 PM" src="https://user-images.githubusercontent.com/74931060/100008193-53d2e900-2d8a-11eb-9fca-5449e5fe9878.png">

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
Make sure that `sendCameraMotionNotificationsToTv` or `sendDoorbellMotionNotificationsToTv` is set to `false`, or completely remove the line from your config.   The fact that it still has `Simulating Doorbell Press` in the logs means the setting is still on.  Also make sure to restart homebridge after you update your config.

**Comment by dubofodin** [comment]
Was on `false`, removed the line completely and rebooting. Then I will run in front of the camera here soon. Thank you!

**Comment by dubofodin** [comment]
I removed the line and this is fixed! Thanks for the help!
