### ISSUE TITLE
Ring accessories no longer appear in Homebridge

### ISSUE THREAD

**Issue by SKnight79** [dgreif/ring#507]
# Bug Report

### Describe the Bug
 Ring are no longer showing up.

### To Reproduce
 - Start Homebridge
 - Attempt to change alarm state.
 - Alarm and other ring objects do not appear.

### Expected behavior
 Ring accessories appear in Homebridge

### Screenshots/Logs
 
[11/29/2020, 2:08:07 PM] Loaded plugin: homebridge-ring@9.12.6
[11/29/2020, 2:08:07 PM] Registering platform 'homebridge-ring.Ring'
[11/29/2020, 2:08:13 PM] [Ring] Initializing Ring platform...
[11/29/2020, 2:08:24 PM] [Ring] 404 from endpoint https://api.ring.com/clients_api/ring_devices
[11/29/2020, 2:08:24 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.

### Additional context
 Multiple instances of homebridge-ring as authorized client appear in Ring account. Removing them all and re-auth starts adding one more each time I restart Homebridge. I've tried rolling back the plugin to 9.12.0 and forward to 9.12.7-beta.1 but no change in doing so.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
        {
            "refreshToken": "[[private]]",
            "platform": "Ring"
        }
```

### Environment

 - OS: Mac
 - Node.js: v15.3.0
 - NPM: 7.0.14
 - homebridge-ring: v9.12.6
 - homebridge: v1.1.6
 - hoobs: N/A

**Comment by SKnight79** [comment]
Reviewed https://github.com/dgreif/ring/issues/380 and https://github.com/dgreif/ring/issues/465. Not getting anything after [Ring] Creating location socket.io connection.

**Comment by dgreif** [comment]
@SKnight79 can you enable the `debug` option?  Might have some extra info in the logs.  Otherwise, probably a network issue.

**Comment by SKnight79** [comment]
Enabled "debug": true￼ in config.json.
Restarted homebridge.
Nothing extra appears in homebridge regarding ring.

**Comment by dgreif** [comment]
@SKnight79 make sure you have all of your Ring hubs powered and connected to the internet.  If you have an alarm base station or a smart lighting hub on your account, but not actively connected, then the plugin waits for it to come online before proceeding.

**Comment by SKnight79** [comment]
Ring hub is powered and connected. I can control the system by web and by app.  

It was all working with homebridge until I performed recent updates.

I noticed a slew of node npm homebridge and ring updates recently so I don’t know exactly at which point it crapped out. 

Unless you have any other suggestions, I will rebuild homebridge from scratch and test that.

**Comment by lkzhao** [comment]
@SKnight79 Did rebuilding home bridge help solve the issue? I'm having the same issue where it doesn't continue after "Creating location socket.io connection"

**Comment by SKnight79** [comment]
I removed homebridge from HomeKit (just in case that was the issue). No change. Ran a fresh install of macOS BigSur, npm and homebridge and ring plugin (all latest versions). Got the same result. Nothing happens after Ring initialized. No debug logging either although I turned it on. Is the debug log somewhere else other than the Homebridge log?

**Comment by dgreif** [comment]
@SKnight79 please try updating to 9.12.8.  It's possible that your homebridge was restarting frequently enough to hit the Ring session limit, which was happening because the plugin was not able to find a unique id for your machine.  I changed the way this is set up, so you should hopefully not run into that issue after updating.  You may need to update and then wait an hour (or maybe 24 hours) for the rate limiting to clear out on Ring's side

**Comment by SKnight79** [comment]
Your analysis would likely explain exactly my situation. A friend of mine with similar setup has had no issues. It could very well be specific to my account and activity.  Even with a brand new setup my connection and ring account was the same so that explains that.

**Comment by iOSDevil** [comment]
I'm having the same issue, none of the Ring devices are showing up in HomeKit anymore.

I've been using HomeBridge for a while and the Ring Doorbell was showing up, seems to have disappeared after one of the two last updates.

I've also setup an instance of HOOBS to see if it's a HomeBridge issue but it's the same experience.

I've enabled debug mode and the only console output is:
[12/12/2020, 1:18:33 PM] Loaded plugin: homebridge-ring@9.12.8
[12/12/2020, 1:18:33 PM] Registering platform 'homebridge-ring.Ring'
[12/12/2020, 1:18:34 PM] [Ring] Creating location socket.io connection

Thanks

**Comment by lkzhao** [comment]
I'm running homebridge on an M1 powered Mac mini, not sure if that contributed to anything. But I'm also not seeing anything after 
[Ring] Creating location socket.io connection

**Comment by SKnight79** [comment]
This also returns nothing:

$ ring-device-data-cli
This CLI will log data from you Ring Account to help debug issues and discovering new device types.
The logged data is anonymized and should not compromise your account in any way.
Email: [[private]]
Password: [[private]]
Ring 2fa or verification code is enabled.  Please enter code from the text/email.
2fa Code: [[private]]
Successfully logged in.  Fetching devices...

**Comment by lkzhao** [comment]
I tried with an Raspberry Pi and it worked. I think it has to do with Mac build of node.

**Comment by SKnight79** [comment]
> I tried with a Raspberry Pi and it worked. I think it has to do with Mac build of node.

I was able to restore Ring by downgrading from Node v15.4.0 to v14.15.3. I'm running plug-in v9.12.8. Node v15 (somewhere in there) seems to be the culprit. Has the plug-in been tested on Node v15?

**Comment by dgreif** [comment]
@SKnight79 I have not tested the plugin with node 15. Node 14 is the LTS version, and is the main version I aim to support.  The odd number versions like 15 often have breaking changes, which may be the issue here. I'll try it out when I get a chance, but for now running node 14 is probably the best solution.

**Comment by iOSDevil** [comment]
Thanks @dgreif 

On my Intel Mac I have rolled back to the LTS version of node which is v14.15.3 using the following:
npm install -g n
n 14.15.3

A reboot for good measure and this wonderful plugin is working for me.

**Comment by DMBlakeley** [comment]
I recently found out that Homebridge only supports even numbered releases of Node.is (10.x, 12.x and 14.x). Reference: https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js

Best to stay away from odd numbered releases.

**Comment by SKnight79** [comment]
All,

A suggestion: After downgrading to v14, do a “brew pin node“ in case your homebrew environment auto updates with a script, or you run “brew update” by chance and wonder why it stopped working.

-Hector

**Comment by dgreif** [comment]
I just confirmed I see the same behavior of I install node 15. Since 15 isn't supported by homebridge, I don't think it needs to be supported by plugins. Node 14 is the best version to use currently, so downgrading is the right solution to this issue. Glad to have this one figured out finally!
