### ISSUE TITLE
Ring Plugin works only with bug in Hoobs

### ISSUE THREAD

**Issue by Otto-Wilhelm** [dgreif/ring#508]
The Ring plugin allows under Homebridge to select one of the alarm modes "home" and "away" as "night" alarm modes, which does not require that an open contact sensor is confirmed. This selection is not possible in Hoobs. The selection drop down box in the configuration menu doesn't work.

Version
3.2.10

Did you upgrade
Please let us know if you upgraded from a previous version.

 Yes
[x ] No
Complete new installation on Raspberry 4 with the image downloaded from Hoobs. Now additional plugin installed so far besides the Ring plugin.

For the time being I will return to normal Homebridge. Here the Ring plugin works fine.

# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
Hey @Otto-Wilhelm, sorry for the super delayed response. Been a flood of other issues and this one got lost in the mix.  The plugin has a schema which defines how those dropdowns should behave, but it's up to HOOBS to supply the actual UI.  If the dropdown isn't working properly, I suggest you open an issue with HOOBS.  They are very responsive and should be able to get it fixed up.
