### ISSUE TITLE
Ring Mode no longer appears as its own accessory

### ISSUE THREAD

**Issue by alaw168** [dgreif/ring#509]
In v9.12.5, mode appears as its own accessory that can be toggled within Home app.

In v9.12.6, this accessory disappears.

Reverting to v9.12.5 and the accessory reappears.

**Comment by dgreif** [comment]
There weren't any changes in 9.12.6 that should cause this type of issue.  Can you please try upgrading again to confirm?

**Comment by alaw168** [comment]
Sorry for the false alarm. Something else must have gone wrong during restart. Upgrading again and cannot reproduce the problem.
