### ISSUE TITLE
Multiple Home locations

### ISSUE THREAD

**Issue by acrmedics** [dgreif/ring#510]
I have 2 homes, both setup as individual Homes within Apple Homekit and 2 base stations in the Ring app.  Is there a way to separate the base stations out between the 2 Homekit Homes?   

# Feature Request

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dgreif** [comment]
Homebridge only allows multiple HomeKit homes if you run multiple instances of homebridge.  If you set that up, you can then configure the ring plugin to only load a particular location in each homebridge instance using the `locationIds` options.

**Comment by acrmedics** [comment]
Thank you so much Dusty. That’s exactly what I thought, just wanted to confirm before I made a mess of things. :-)

Thank you
Jordan
