### ISSUE TITLE
Door/Window sensors disappeared

### ISSUE THREAD

**Issue by yweiss** [dgreif/ring#513]
I'm not sure when this happened but none of my Ring Security Door/Window sensors show up in the home app anymore. I've restarted homebridge and the raspberry pi, un-hid the base station and keypads, but the sensors still don't show up. Any ideas?

**Comment by yweiss** [comment]
I think I found them all hiding in the default room. I guess one of the recent updates broke the room association?

**Comment by dgreif** [comment]
The plugin doesn't impact which room they show up in within HomeKit.  It's possible they got temporarily removed and re-added, which would move them to the default room.  If you find a way to reproduce that, let me know.  Otherwise, sounds like you are good to go for now.
