### ISSUE TITLE
(homebridge) register "knock" as ding

### ISSUE THREAD

**Issue by dgreif** [dgreif/ring#514]
# Feature Request

### Description
Add ability to register a "knock" on the door as a doorbell ring in the homebridge plugin

### Describe the solution you'd like
Knocks are currently not registered as a ding or as a motion event.  They are just ignored

Original Request: https://www.reddit.com/r/homebridge/comments/k45isi/ring_peephole_knock_notification/

**Comment by galoiring** [comment]
Great request ! Hope it will be integrated soon !

**Comment by dgreif** [comment]
@galoiring I added a new `treatKnockAsDing` option in v`9.23.0`.  Would you mind giving it a try and confirming that it works?
