### ISSUE TITLE
Plugin has stopped working in entirety (no alarm control, no camera access)

### ISSUE THREAD

**Issue by ryanleesmith** [dgreif/ring#515]
# Bug Report

### Describe the Bug
Ring plugin is no longer functioning, and appears to be erroring out on the following line during init:
"Ring floodlight_v2 {uuid} is offline or on cellular backup.  Waiting for status to change"

It's not clear if floodlight_v2 is a misnomer. While I do have one v2 floodlight, and two v1s, all of them have been online and powered for weeks, if not longer (they are hardwired). I do have a stickup cam whose battery died a few days ago, around the same time this started happening, however I have recharged and it is online in the native Ring app (along with the other cameras, and all of the Ring devices).

After confirming everything is online and connected in the Ring native app, I have tried rebooting Homebridge multiple times to no avail. I have also tried using a freshly generated refreshToken to no avail. Turning on debug logging does not print anything further.

### To Reproduce
 - Start Homebridge
 - Attempt to view Ring cameras or control alarm
 - No error or logs show up at all - the line mentioned above is the last thing that ever gets logged, which is during init of Homebridge

### Expected behavior
Should behave as normal

### Screenshots/Logs
Log line provided above, that is the only error message, and the last log from the plugin

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
{
"refreshToken": "xxx",
"debug": true,
"platform": "Ring"
}
```

### Environment
 - OS: macOS
 - Node.js: v12.18.3
 - NPM: v6.14.8
 - homebridge-ring: v9.12.6
 - homebridge: v1.2.2

**Comment by dgreif** [comment]
This is very interesting!  Until now, the Ring Alarm and Ring Smart Lighting have been the only devices to support a websocket connection.  Based on your experience, it appears they may finally be adding a websocket connection for cameras, which means the plugin will no longer have to regularly poll the server for camera updates.  I have not yet seen this behavior on my cameras.  Would you be willing to share access to your `floodlight_v2` camera with me for testing?  If so, my email is `dustin.greif@gmail.com`. If the camera is in a location where you would not feel comfortable sharing access, that is completely understandable.  Either way, I should be able to get a fix out that ignores these websocket connections for now and gets you back online.  Are you by chance participating in an Explorer Program beta?

**Comment by dgreif** [comment]
I released `9.12.7` which _should_ get you up and running again.  Please let me know if it works.  I'd still be interested in temporary access to the camera if you are willing, but no pressure if you aren't comfortable with it.

**Comment by ryanleesmith** [comment]
Yep, that fixed the issue, thanks!

I'm not in the Explorer Program, is that Ring or Homebridge sponsored? Also, I'll need to double check, but I think the V2 camera is one that isn't particularly risky for me to share - I'll look into this and ping you. Thanks!

**Comment by dgreif** [comment]
The explorer program is Ring's beta testing program.  I think you have to be invited by Ring, but it gives you access to certain beta programs to test out new features/hardware before they are released to the public.  If you have never heard of it, this is likely a wide-spread firmware update for the `floodlight_v2` cameras. Hopefully it will roll out to the other cameras soon as well.
