### ISSUE TITLE
cacheableLookup ENOTFOUND localhost error after installing plugin

### ISSUE THREAD

**Issue by dskaggs** [dgreif/ring#520]
# Bug Report

### Describe the Bug
I am unable to get the homebridge-ring plugin to function with Homebridge due to the error message below.

### To Reproduce
 - Start HomeBridge
 - Search for plugin on Plugins page
 - Install plugin from search results
 - Restart HomeBridge from UI
 - See `Failed to reach Ring server at https://oauth.ring.com/oauth/token.  cacheableLookup ENOTFOUND localhost.  Trying again in 5 seconds...` in log output on Status page every 5 seconds
 - Observe no camera listed in Home app on iOS

### Expected behavior
Ring doorbell camera appears in the Home app on iOS

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
I first tried this plugin on version 9.12.5 a few weeks ago and was not able to get it to work for the same error as above. I tried reverting to 9.12.4 but got the "enhance your calm" error. I tried 9.12.6 as well but the cacheableLookup error remained. I loaded 9.12.8 this morning and observed the same error.

I checked my `/etc/hosts` file as noted in [this comment](https://github.com/dgreif/ring/issues/497#issuecomment-739257646) on #497 and didn't see anything out of the ordinary there:

```
root@homebridge:~# cat /etc/hosts
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback

ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       homebridge
```

I even went so far as to disable IPv6 using instructions I found [here](https://www.raspberrypi.org/forums/viewtopic.php?t=256349). 
```
root@homebridge:~# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 123.45.678.90  netmask 255.255.255.0  broadcast 123.45.678.255
        ether xx:xx:xx:xx:xx:xx  txqueuelen 1000  (Ethernet)
        RX packets 5284  bytes 1171778 (1.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4613  bytes 790281 (771.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

I can ping the URL from a shell and see the IPv4 address returned:
```
root@homebridge:~# ping oauth.ring.com
PING oauth.ring.com.cdn.cloudflare.net (104.17.128.1) 56(84) bytes of data.
64 bytes from 104.17.128.1 (104.17.128.1): icmp_seq=1 ttl=54 time=13.3 ms
64 bytes from 104.17.128.1 (104.17.128.1): icmp_seq=2 ttl=54 time=14.3 ms
64 bytes from 104.17.128.1 (104.17.128.1): icmp_seq=3 ttl=54 time=12.8 ms
64 bytes from 104.17.128.1 (104.17.128.1): icmp_seq=4 ttl=54 time=12.7 ms
64 bytes from 104.17.128.1 (104.17.128.1): icmp_seq=5 ttl=54 time=13.4 ms
64 bytes from 104.17.128.1 (104.17.128.1): icmp_seq=6 ttl=54 time=12.8 ms
```

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
{
     "refreshToken": "<redacted>",
     "platform": "Ring"
}
```

### Environment

 - OS: Raspbian GNU/Linux 10 (buster)
 - Node.js: 12.19.1
 - NPM: 6.14.8
 - homebridge-ring: 9.12.8 (also seen in 9.12.5 and 9.12.6)
 - homebridge: 1.1.6
 - hoobs: N/A

### Installed Plugins
 -  Homebridge UI (homebridge-config-ui-x v4.34.0)
 -  Homebridge Vivint Latest (@michaelmade/homebridge-vivint-latest v0.0.7)
 -  Homebridge Sonos (homebridge-sonos v0.4.0)
 -  Homebridge Vivint Latest (@michaelmade/homebridge-vivint-latest v0.0.7)
 -  Homebridge Ring (homebridge-ring v9.12.8)
 -  Homebridge Weather (homebridge-weather v1.12.4)

**Comment by dgreif** [comment]
Can you try version 9.12.2?

**Comment by dskaggs** [comment]
Installed 9.12.2 and restarted HomeBridge from the UI. Below is the initial log output:
```
[12/5/2020, 11:56:33 AM] [Ring] 404 from endpoint https://api.ring.com/clients_api/ring_devices
[12/5/2020, 11:56:33 AM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[12/5/2020, 11:56:34 AM] [Ring] Configuring 1 cameras and 2 devices for location "<City Redacted>" - locationId: <redacted>
[12/5/2020, 11:56:34 AM] [Ring] Adding new accessory <UUID redacted> lpd_v2 Front Door
[12/5/2020, 11:56:34 AM] [Ring] Adding new accessory <UUID redacted> location.mode <City redacted> Mode
[12/5/2020, 11:56:48 AM] [Insteon Local Platform] Error getting power state of Master Bedroom Keypad
[12/5/2020, 11:56:58 AM] [Temperature] Fetched temperature value 11.49deg of type 'current' for accessory Temperature
[12/5/2020, 11:56:58 AM] [Temperature] Fetched humidity value 50% of type 'current' for accessory Temperature
[12/5/2020, 11:57:01 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
```
The error code on the last line is repeating every 5 seconds.

**Comment by gallarda** [comment]
I get the same error with v9.12.5 and newer.  If I revert to v9.12.4 the problem goes away.  I am running homebridge on Windows 10 with nodejs v14.15.1.  I have localhost in my Windows hosts table as well as in DNS for my default domain.

**Comment by clipse2004** [comment]
my error looks like: 
 Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/xxxxxxxxxxxxxxxxxxxxxxxxxxx.  queryA ESERVFAIL app.ring.com.  Trying again in 5 seconds...

**Comment by dskaggs** [comment]
FYI - Upgrading to NodeJS v12.20.0 and installing v9.12.8 still produced the `cacheableLookup ENOTFOUND localhost` error

**Comment by dgreif** [comment]
@dskaggs what type of router do you have?  If it's an Eero, check out https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Fix-Eero-Router-Internet-and-DNS-Connectivity-Issues

**Comment by dskaggs** [comment]
I use a Ubiquti Networks EdgeRouter X. I've updated the firmware to be current. The RPi that runs HomeBridge is on a VLAN that bypasses all my ad blocking configurations and uses Google DNS for name resolution.

I am able to ping `oauth.ring.com` from the RPi in question:
```
pi@homebridge:~ $ ping oauth.ring.com
PING oauth.ring.com.cdn.cloudflare.net (104.17.127.1) 56(84) bytes of data.
64 bytes from 104.17.127.1 (104.17.127.1): icmp_seq=1 ttl=54 time=11.4 ms
64 bytes from 104.17.127.1 (104.17.127.1): icmp_seq=2 ttl=54 time=11.4 ms
64 bytes from 104.17.127.1 (104.17.127.1): icmp_seq=3 ttl=54 time=11.2 ms
64 bytes from 104.17.127.1 (104.17.127.1): icmp_seq=4 ttl=54 time=11.3 ms
64 bytes from 104.17.127.1 (104.17.127.1): icmp_seq=5 ttl=54 time=11.3 ms
```

**Comment by dgreif** [comment]
@dskaggs can you try `9.14.1`?  I removed all DNS caching, which should hopefully get rid of your issue.

**Comment by dskaggs** [comment]
@dgreif So far so good. I am able to to access the camera from the Home app. I get no errors in the logs and am seeing log entries for motion detection. I'll continue to monitor it today and report back if I see anything. If not, I'll close the ticket tomorrow.

Thanks so much!

**Comment by gallarda** [comment]
9.14.1 is working well for me too.  Thanks for the fix!

**Comment by dskaggs** [comment]
Looking good. No errors in the log and no issues with operation in the last 24 hours. Thanks again!
