### ISSUE TITLE
404 Error in logs.

### ISSUE THREAD

**Issue by Raiden38** [dgreif/ring#521]
# Bug Report

### Describe the Bug
I have this in my error message:
[05/12/2020, 23:11:20] [Ring] Request for system uuid timed out.  Falling back to random session id
and
[05/12/2020, 23:11:33] [Ring] 404 from endpoint https://api.ring.com/clients_api/ring_devices
[05/12/2020, 23:11:33] [Ring] Session hardware_id not found.  Creating a new session and trying again.

### To Reproduce
It's in the log.

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
[05/12/2020, 23:11:20] [Ring] Request for system uuid timed out.  Falling back to random session id
and
[05/12/2020, 23:11:33] [Ring] 404 from endpoint https://api.ring.com/clients_api/ring_devices
[05/12/2020, 23:11:33] [Ring] Session hardware_id not found.  Creating a new session and trying again.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

{
            "refreshToken": "XXXXXXXXXXXXXXXXXXX",
            "platform": "Ring"
        },

```

### Environment

 - Node.js: v14.15.0
 - NPM: 6.14.8
 - homebridge-ring: homebridge-ring v9.12.8
 - homebridge: 1.2.3

**Comment by dgreif** [comment]
This error is normal. You should have seen it once after the latest update, but you shouldn't see it on future restarts or updates. Did you only see it one time?

**Comment by Raiden38** [comment]
I see those 3 errors each time I reboot homebridge..

**Comment by dgreif** [comment]
You shouldn't after the latest update. Please provide all the version info requested in the issue template

**Comment by Raiden38** [comment]
OS: Raspbian GNU/Linux Buster (10)
Node.js: v14.15.0
NPM: 6.14.8
homebridge-ring: homebridge-ring v9.12.8
homebridge: 1.2.3
hoobs: latest (just did an update)

**Comment by dgreif** [comment]
@Raiden38 do you still see this issue every time you restart homebridge?  It should have happened one time when you updated to 9.12.8, but not again after that.

**Comment by Raiden38** [comment]
@dgreif Just did a restart and I got those errors : (RPI has been up for a while now, just did a restart)

[26/12/2020, 17:47:01] [Ring] Request for system uuid timed out.  Falling back to random session id
[26/12/2020, 17:47:15] [Ring] 404 from endpoint https://api.ring.com/clients_api/ring_devices
[26/12/2020, 17:47:15] [Ring] Session hardware_id not found.  Creating a new session and trying again.

Homebridge 1.2.4
Ring Plugin 9.12.8

Thanks!

**Comment by solbadguy2010** [comment]
I have the same errors. Official Homebridge Image.

Node.js: v14.15.3
NPM: 6.14.9
homebridge-ring: homebridge-ring v9.14.1
homebridge: 1.1.7

**Comment by cpettis** [comment]
Mine has started to do the same basic thing. It seems to start ok and I can ever get a live stream for a few minutes, but then it starts throwing the errors below:
1/13/2021, 1:41:49 PM Loaded plugin 'homebridge-nest'
1/13/2021, 1:41:49 PM [1/13/2021, 1:41:49 PM] Registering platform 'homebridge-nest.Nest'
1/13/2021, 1:41:52 PM Loaded plugin 'homebridge-ring'
1/13/2021, 1:41:52 PM [1/13/2021, 1:41:52 PM] Registering platform 'homebridge-ring.Ring'
1/13/2021, 1:41:52 PM Loading 2 platforms...
1/13/2021, 1:41:52 PM [Nest] Initializing Nest platform...
1/13/2021, 1:41:52 PM [Ring] Initializing Ring platform...
1/13/2021, 1:41:52 PM [Ring] Configuring cached accessory 2df91078-25f3-43be-bb0c-b04f34c06d52 Front Door
1/13/2021, 1:41:52 PM [Ring] Configuring cached accessory 9bc76f72-b60c-4cbd-9c36-cee48961164a Garage
1/13/2021, 1:41:52 PM [Ring] Configuring cached accessory 696baa1b-c5f5-4043-98d9-1f324d5ff9b6 Living Room
1/13/2021, 1:41:52 PM [Ring] Configuring cached accessory b82fd901-69da-4000-bce1-ab624bedddbe Hallway
1/13/2021, 1:41:52 PM [Ring] Configuring cached accessory 14e96686-b65c-4cd6-828a-1455be679b5e Wylie Mode
1/13/2021, 1:41:52 PM [Nest] Fetching Nest devices.
1/13/2021, 1:41:53 PM Bridge is running on port 51826.
1/13/2021, 1:41:56 PM [Ring] Found the following locations:
1/13/2021, 1:41:56 PM [Ring]   locationId: d208e509-67f2-4228-7b9e-cbe040fe5543 - Wylie
1/13/2021, 1:41:56 PM [Ring] Configuring 3 cameras and 5 devices for location "Wylie" - locationId: d208e509-67f2-4228-7b9e-cbe040fe5543
1/13/2021, 1:41:58 PM [Nest] initing thermostat "Bedroom Thermostat": deviceId: 09AA01AC021703MT structureId: 52ead3e0-33d9-11e6-91bb-22000b8a89fb
1/13/2021, 1:41:58 PM [Nest] initing protect "Bedroom": deviceId: 18B430000033AD2F structureId: 52ead3e0-33d9-11e6-91bb-22000b8a89fb
1/13/2021, 1:41:58 PM [Nest] initing protect "Family Room": deviceId: 18B4300000338998 structureId: 52ead3e0-33d9-11e6-91bb-22000b8a89fb
1/13/2021, 1:42:36 PM [Ring] Preparing Live Stream for Garage
1/13/2021, 1:42:37 PM [Ring] Waiting for stream data from Garage (1.025s)
1/13/2021, 1:42:37 PM [Ring] Received stream data from Garage (1.454s)
1/13/2021, 1:42:37 PM [Ring] Streaming active for Garage
1/13/2021, 1:42:44 PM [Ring] Stopped Live Stream for Garage
1/13/2021, 1:43:15 PM [Ring] Preparing Live Stream for Front Door
1/13/2021, 1:43:16 PM [Ring] Waiting for stream data from Front Door (0.961s)
1/13/2021, 1:43:16 PM [Ring] Received stream data from Front Door (1.551s)
1/13/2021, 1:43:16 PM [Ring] Streaming active for Front Door
1/13/2021, 1:43:25 PM [Ring] Stopped Live Stream for Front Door
1/13/2021, 1:44:16 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/timestamps.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/13/2021, 1:44:17 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/13/2021, 1:44:18 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/13/2021, 1:44:21 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/timestamps.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/13/2021, 1:44:22 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/13/2021, 1:44:23 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/13/2021, 1:44:25 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/13/2021, 1:44:26 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/timestamps.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/13/2021, 1:44:27 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/13/2021, 1:44:28 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/13/2021, 1:44:30 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/13/2021, 1:44:31 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/timestamps.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/13/2021, 1:44:32 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/13/2021, 1:44:34 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...

With enhanced logging on, I get:
1/13/2021, 1:41:43 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...1/13/2021, 1:41:43 PM [Ring] RequestError: Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM
    at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/got/dist/source/core/index.js:953:111)
    at Object.onceWrapper (events.js:417:26)
    at ClientRequest.emit (events.js:322:22)
    at ClientRequest.origin.emit (/home/hoobs/.hoobs/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at ClientHttp2Stream.<anonymous> (/home/hoobs/.hoobs/node_modules/http2-wrapper/source/utils/proxy-events.js:5:34)
    at ClientHttp2Stream.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at ClientHttp2Stream._destroy (internal/http2/core.js:2148:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:38:8)
    at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2164:12)
    at Http2Stream.onStreamClose (internal/http2/core.js:511:26) {
  code: 'ERR_HTTP2_STREAM_ERROR',
  timings: {
    start: 1610566903193,
    socket: 1610566903195,
    lookup: 1610566903195,
    connect: 1610566903195,
    secureConnect: 1610566903195,
    upload: 1610566903195,
    response: undefined,
    end: undefined,
    error: 1610566903253,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 0,
      tcp: 0,
      tls: 0,
      request: NaN,
      firstByte: undefined,
      download: undefined,
      total: 60
    }
  }
}

**Comment by cpettis** [comment]
It seems that the errors start after the first live stream is initiated, then you can't view a live stream until the HOOBS bridge is rebooted.
My Ring HOOBS Configuration Below:
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "TOKEN HERE"          
            "hideDoorbellSwitch": true,
            "alarmOnEntryDelay": false,
            "hideLightGroups": false,
            "hideCameraMotionSensor": false,
            "hideCameraSirenSwitch": false,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": false,
            "showPanicButtons": true,
            "sendCameraMotionNotificationsToTv": true,
            "sendDoorbellMotionNotificationsToTv": true,
            "hideDeviceIds": [],
            "locationIds": [],
            "onlyDeviceTypes": []
        }
Most recent logs from a test run:
1/15/2021, 8:39:04 AM HOOBS listening on port 80.
1/15/2021, 8:39:13 AM Loaded plugin 'homebridge-nest'
1/15/2021, 8:39:13 AM [1/15/2021, 8:39:13 AM] Registering platform 'homebridge-nest.Nest'
1/15/2021, 8:39:31 AM Loaded plugin 'homebridge-ring'
1/15/2021, 8:39:31 AM Loading 2 platforms...
1/15/2021, 8:39:31 AM [Nest] Initializing Nest platform...
1/15/2021, 8:39:31 AM [1/15/2021, 8:39:31 AM] Registering platform 'homebridge-ring.Ring'
1/15/2021, 8:39:31 AM [Ring] Initializing Ring platform...
1/15/2021, 8:39:31 AM [Ring] Configuring cached accessory 2df91078-25f3-43be-bb0c-b04f34c06d52 Front Door
1/15/2021, 8:39:31 AM [Ring] Configuring cached accessory 9bc76f72-b60c-4cbd-9c36-cee48961164a Garage
1/15/2021, 8:39:31 AM [Ring] Configuring cached accessory 696baa1b-c5f5-4043-98d9-1f324d5ff9b6 Living Room
1/15/2021, 8:39:31 AM [Ring] Configuring cached accessory b82fd901-69da-4000-bce1-ab624bedddbe Hallway
1/15/2021, 8:39:31 AM [Ring] Configuring cached accessory 14e96686-b65c-4cd6-828a-1455be679b5e Wylie Mode
1/15/2021, 8:39:31 AM [Nest] Fetching Nest devices.
1/15/2021, 8:39:32 AM Bridge is running on port 51826.
1/15/2021, 8:39:32 AM [Ring] Request for system uuid timed out.  Falling back to random session id
1/15/2021, 8:39:35 AM [Ring] 404 from endpoint https://api.ring.com/clients_api/ring_devices
1/15/2021, 8:39:35 AM [Ring] Session hardware_id not found.  Creating a new session and trying again.
1/15/2021, 8:39:35 AM [Ring] Found the following locations:
1/15/2021, 8:39:35 AM [Ring]   locationId: d208e509-67f2-4228-7b9e-cbe040fe5543 - Wylie
1/15/2021, 8:39:36 AM [Ring] Configuring 3 cameras and 5 devices for location "Wylie" - locationId: d208e509-67f2-4228-7b9e-cbe040fe5543
1/15/2021, 8:39:37 AM [Nest] initing thermostat "Bedroom Thermostat": deviceId: 09AA01AC021703MT structureId: 52ead3e0-33d9-11e6-91bb-22000b8a89fb
1/15/2021, 8:39:37 AM [Nest] initing protect "Bedroom": deviceId: 18B430000033AD2F structureId: 52ead3e0-33d9-11e6-91bb-22000b8a89fb
1/15/2021, 8:39:37 AM [Nest] initing protect "Family Room": deviceId: 18B4300000338998 structureId: 52ead3e0-33d9-11e6-91bb-22000b8a89fb
1/15/2021, 11:05:48 AM [Ring] Preparing Live Stream for Front Door
1/15/2021, 11:05:49 AM [Ring] Waiting for stream data from Front Door (1.313s)
1/15/2021, 11:05:49 AM [Ring] Received stream data from Front Door (1.365s)
1/15/2021, 11:05:50 AM [Ring] Streaming active for Front Door
1/15/2021, 11:05:56 AM [Ring] Stopped Live Stream for Front Door
1/15/2021, 11:05:58 AM [Ring] Preparing Live Stream for Garage
1/15/2021, 11:05:59 AM [Ring] Waiting for stream data from Garage (0.925s)
1/15/2021, 11:05:59 AM [Ring] Received stream data from Garage (1.112s)
1/15/2021, 11:05:59 AM [Ring] Streaming active for Garage
1/15/2021, 11:06:05 AM [Ring] Stopped Live Stream for Garage
1/15/2021, 11:06:17 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:22 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:25 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:27 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:27 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:32 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:35 AM [Ring] Preparing Live Stream for Garage
1/15/2021, 11:06:35 AM [Ring] Ding 6918034210288170948 is expired (480).  Fetching a new ding and trying video stream again
1/15/2021, 11:06:35 AM err:  Error: remote peer disconnected
1/15/2021, 11:06:35 AM at TLSSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/sip/sip.js:584:43)
1/15/2021, 11:06:35 AM at TLSSocket.emit (events.js:322:22)
1/15/2021, 11:06:35 AM at endReadableNT (_stream_readable.js:1187:12)
1/15/2021, 11:06:35 AM at processTicksAndRejections (internal/process/task_queues.js:84:21)
1/15/2021, 11:06:36 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/doorbots/3798980/live_view.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:36 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:37 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:37 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:41 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/doorbots/3798980/live_view.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:41 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:42 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:42 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:46 AM [Ring] Stopped Live Stream for Garage
1/15/2021, 11:06:46 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/doorbots/3798980/live_view.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:46 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:47 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:47 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:51 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/doorbots/3798980/live_view.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:52 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/15/2021, 11:06:52 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...

**Comment by cpettis** [comment]
Version 9.13.0 Does not have any errors related to starting streams.

Version 9.14.0 Shows these errors when streaming to one device more than once with a short interval between stream requests.
Hope this helps, I'm going to stay on 9.14.0 for now.
1/15/2021, 11:47:08 AM [Ring] Preparing Live Stream for Front Door
1/15/2021, 11:47:09 AM [Ring] Ding 6918044672827999274 is expired (480).  Fetching a new ding and trying video stream again
1/15/2021, 11:47:09 AM err:  Error: remote peer disconnected
1/15/2021, 11:47:09 AM at TLSSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/sip/sip.js:584:43)
1/15/2021, 11:47:09 AM at TLSSocket.emit (events.js:322:22)
1/15/2021, 11:47:09 AM at endReadableNT (_stream_readable.js:1187:12)
1/15/2021, 11:47:09 AM at processTicksAndRejections (internal/process/task_queues.js:84:21)
1/15/2021, 11:47:09 AM [Ring] Waiting for stream data from Front Door (1.182s)
1/15/2021, 11:47:10 AM [Ring] Received stream data from Front Door (1.606s)
1/15/2021, 11:47:10 AM [Ring] Streaming active for Front Door
1/15/2021, 11:47:24 AM [Ring] Stopped Live Stream for Front Door
1/15/2021, 11:47:29 AM [Ring] Preparing Live Stream for Garage
1/15/2021, 11:47:29 AM [Ring] Ding 6918044715778176964 is expired (480).  Fetching a new ding and trying video stream again
1/15/2021, 11:47:29 AM err:  Error: remote peer disconnected
1/15/2021, 11:47:29 AM at TLSSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/sip/sip.js:584:43)
1/15/2021, 11:47:29 AM at TLSSocket.emit (events.js:322:22)1/15/2021, 
11:47:29 AM at endReadableNT (_stream_readable.js:1187:12)1/15/2021, 
11:47:29 AM at processTicksAndRejections (internal/process/task_queues.js:84:21)
1/15/2021, 11:47:30 AM [Ring] Waiting for stream data from Garage (1.168s)
1/15/2021, 11:47:35 AM [Ring] Received stream data from Garage (6.652s)
1/15/2021, 11:47:35 AM [Ring] Streaming active for Garage
1/15/2021, 11:47:44 AM [Ring] Stopped Live Stream for Garage

**Comment by dgreif** [comment]
@cpettis the `NGHTTP2_ENHANCE_YOUR_CALM` is a separate issue and can be fixed by updating your NodeJS version.  See https://github.com/dgreif/ring/issues/548#issuecomment-760288703 for details on how to update with a HOOBS setup. 

Heads up, I'm going to mark these comments "Off Topic" since they are technically for a different issue.  Feel free to follow up on https://github.com/dgreif/ring/issues/496 if you have any questions.

**Comment by johnsills1** [comment]
I have the same error on v9.14.2
Homebridge v1.2.5
Docker on Synology NAS

**Comment by dgreif** [comment]
This will happen one more time on the first reboot after updating to v`9.15.3`.  After that, you shouldn't see it again on future updates/reboots
