### ISSUE TITLE
change snapshot setting on device? (lite_24x7)

### ISSUE THREAD

**Issue by gtxaspec** [dgreif/ring#525]
# Feature Request

### Description
is it possible, under:

```
            "lite_24x7": {
              "subscribed": true,
              "enabled": true,
              "frequency_secs": 840,
              "resolution_p": 360
```

to set the "frequency_secs" value? this will change the time in between snapshots.

### Describe the solution you'd like
a way to set this using the API

### Describe alternatives you've considered
none discovered.

### Device data
posted above

**Comment by dgreif** [comment]
Here is an example of updating a setting: https://github.com/dgreif/ring/blob/6f590d6f345626c9a8a8725cf436dce9295e4d30/api/ring-camera.ts#L268-L274

You can make requests like this with something like `await ringApi.restClient.request({...})`.  That should work for you now, and I'll consider adding another method specifically for updating camera settings to make it a little easier.

**Comment by dgreif** [comment]
I added camera.setSettings() in the latest version.  Should be exactly what you need.  Something like `await camera.setSettings({ chime_settings: { enable: true }})`
