### ISSUE TITLE
Hide Spotlight Camera Lights

### ISSUE THREAD

**Issue by danielniemeyer** [dgreif/ring#527]
# Feature Request

### Description
I have a newer Ring Spotlight Camera in my backyard. Unfortunately occasionally when I ask Siri to turn on basement lights, it triggers the backyard spotlight camera light... Would love the ability to hide this accessory in my home app. Since the Camera is already smart enough to turn on this light when motion happens.

### Describe the solution you'd like
Would either love a flag such as hideCameraLights or for the plug-in to log the camera light as a separate accessory so I can hide it.

### Describe alternatives you've considered
As mentioned above, I tried to look for a specific GUID for the camera light accessory only so I could hide it along other accessories I already hide. Unfortunately the plug-in only lists the entire Camera GUID and not the light as separate.

**Comment by dgreif** [comment]
This feature seems pretty specific to your use case, and isn't something I really want to add and have to support.  Have you considered making a "backyard" room so that the camera isn't in your "basement" and siri won't get confused?

**Comment by danielniemeyer** [comment]
Thank you for the input, I appreciate the feedback. While I do see your point, I would consider perhaps the use-case where the light shows up as a separate device GUID. That would at least provide a scalable solution where one can hide the accessory, if they so desire. This way it at least behaves like other devices.

**Comment by dgreif** [comment]
I get where you are coming from, but it's not technically correct since it's all in one physical device.  Is there a reason you can't put it in a separate room?

**Comment by danielniemeyer** [comment]
Gotcha! That makes sense. I took your advice and placed it in a backyard room. At least this way I can forget it exists :D
