### ISSUE TITLE
Snapshot Capture updated to Homekit

### ISSUE THREAD

**Issue by Marfre888** [dgreif/ring#528]
# Feature Request

### Description
Hi, Thank you for this plugin,

I have a Ring Video Doorbell Pro. I have the snapshot capture feature in the Ring app set to capture a shot every 1minute.

### Describe the solution you'd like

Does the API make it possible to periodically push snapshots to Homekit? 

So the snapshot provided in the first 10s before homekit refreshes to a new snapshot isn't hours out of date? Though at the moment I quite like the fact that it tells you when it was last updated.

If I understand correctly presently it only does so every time motion is detected, but even then these snapshots aren't pushed to Homekit (or at least in my case they aren't)

**Comment by dgreif** [comment]
Unfortunately it's not possible to post snapshots to HomeKit. You can only provide them when HomeKit requests them. There are also limitations on the Ring side. Full details here: https://github.com/dgreif/ring/wiki/Snapshot-Limitations
