### ISSUE TITLE
Sorry, a live streaming issue...

### ISSUE THREAD

**Issue by barryl93** [dgreif/ring#531]
# Live Streaming Issue

### Describe the live streaming issue
 Live streaming stopped working -- when I tap on the camera snapshot, I get a spinner that goes on for a while, then the screenshot below. When I tap out of the live streaming view, the snapshot updates, but I never get live streaming.

I have tried downgrading all the way to 9.12.5. Upgrading to the latest beta. Rebooting my iOS devices, my hubs, my wifi network, HB installation. I power-cycled my Ring doorbell. Nothing impacts the issue.

### Screenshots/Logs
 [12/23/2020, 9:23:28 AM] [Ring] Preparing Live Stream for Front Door
[12/23/2020, 9:23:28 AM] [Ring] Ding 6909457242200013226 is expired (480).  Fetching a new ding and trying video stream again
[12/23/2020, 9:23:30 AM] [Ring] Stream Prepared for Front Door (1.588s)
[12/23/2020, 9:23:30 AM] [Ring] Received stream data from Front Door (1.651s)
[12/23/2020, 9:23:30 AM] [Ring] Streaming active for Front Door
[12/23/2020, 9:23:58 AM] [Ring] Stopped Live Stream for Front Door

![IMG_6535](https://user-images.githubusercontent.com/39839859/103007513-8eeb4800-4501-11eb-80c4-9187125809a4.png)

### Recommended solution
 I'm not a developer, but it looks like something to do with losing access to the Ding? That element doesn't show up in the "proper live stream" example from https://github.com/dgreif/ring/wiki/Camera-Troubleshooting.

### Environment

 - Ring Camera: Ring Doorbell
 - OS: Mac OS 10.12.6 (Sierra)
 - Node.js: 12.18.3 
 - NPM: 6.14.8 
 - homebridge-ring (if applicable): 9.12.5-9.12.9 beta
 - homebridge (if applicable): 1.2.4
 - hoobs (if applicable): N/A

### Network Environment
 
Hubs: HomePod and 2 HomePod minis (all running 14.3). 2 AppleTV 4th gen (both running 14.3). eero 2nd gen gateway and beacons, running 6.1.0-877

**Comment by dgreif** [comment]
The `Ding 6909457242200013226 is expired (480)` error occurs when you try to start a stream two times in a row, within a short period of time (< 1 minute or so).  This can _delay_ the stream starting, but it shouldn't cause it to fail completely. Beyond that, there really isn't anything I can add here.  I've optimized live streaming as much as I possibly can for now and any issues must be due to your network blocking traffic.  Make sure your network doesn't have restrictions between your homebridge server and your apple tv/homepod that is acting as your home hub for HomeKit.

**Comment by shaileshck** [comment]
dgreif,

Multiple users complaining about the same issue. It was working well in initial stages and now completely stopped working.
Same no response error even though in logs it shows its streaming.. 
This HomeKit issue i face only on MacOS BigSur. 
Same works perfectly fine on iPhone with IOS 14. Also with TVOS14.

Can you help to diagnose the same.

Also keen to run Homebridge on Raspberry PI.
Can you recommend model which can suitable to run Ring Pluggin with video streaming.
As to my understand video streaming requires good processing to avoid lags and delays in notifications.

Pls suggest.

Regards

Shailesh K.
