### ISSUE TITLE
createSipSession - Listen for RTP from it?

### ISSUE THREAD

**Issue by kangadrewie** [dgreif/ring#532]
Hey guys, great job on the api! I have a question regarding createSipSession (Forgive my ignorance on what is actually going on) and how it works.

What I would like to do is essentially get the live feed by creating a sip call and initiating RTP then listen to the RTP outside of the API. For example, I would like to stream the udp (is it using udp?) packets in python's CV2 library for some real time manipulation of the stream. Is this possible?  

I'm just throwing alot of things at the api and hoping they stick. Again, sorry if I completely have things upside down. Below is an example of where I'm going with this.

```   
doorbell.onNewDing.subscribe((newDingOrMotion) => {
        const sipSession = doorbell.createSipSession();
        .then((session) => {
            console.log(session);
            return session.start();
        })
        .then((start) => {
            console.log(start);
            console.log('Stream going to', `udp://${start.address}:${start.video.port}`);
        });
    });
````

Based on the information from createSipSession, can I see where the data stream is going so I could get the udp stream within python? 

```
cap = cv2.VideoCapture('udp://3.251.100.100:35662',cv2.CAP_FFMPEG)
if not cap.isOpened():
    print('VideoCapture not opened')
    exit(-1)

while True:
    ret, frame = cap.read()
    if not ret:
        print('frame empty')
        break

    cv2.imshow('image', frame)

    if cv2.waitKey(1)&0XFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
```

Any information that might help me is greatly appreciated! Thanks

**Comment by dgreif** [comment]
Your best bet would be to use `streamVideo` instead of `createSipSession`.  This allows you to leverage `ffmpeg` by passing in options to tell `ffmpeg` how to output the stream once it is received locally.  Here is an example that outputs the stream to files: https://github.com/dgreif/ring/blob/master/examples/stream-example.ts.  You will have to figure out the exact ffmpeg output command for your use case, but you will most likely want to use the `copy` codec for the video portion at a minimum.

**Comment by Jonathan-Cotugno** [comment]
Hi @dgreif ! Were you able to figure this out by any chance? I'm trying to do something similar, starting from the [stream example](https://github.com/dgreif/ring/blob/master/examples/stream-example.ts).  However, the `sipSession` call keeps ending immediately.  I'm only using `-codec copy` for ffmpeg options and of course the udp address. 

Please let me know. Thanks!

**Comment by dgreif** [comment]
There isn't much for me to look into here.  Streaming via ffmpeg works perfectly (I do it for the homebridge-ring plugin audio), so you just have to find the right ffmpeg arguments.  I can't really provide help with that since every setup is different.
