### ISSUE TITLE
Could not find a security panel for location

### ISSUE THREAD

**Issue by helmut-hoffer-von-ankershoffen** [dgreif/ring#533]
# Bug Report

### Describe the Bug

Calling get/setAlarmMode() on a location leads to "Could not find a security panel for location ..." if the ring account does not have a security panel.

### To Reproduce

Buy a Ring Spotlight, create a Ring account, use the ring-client-api as described above.

### Expected behavior

Alarm Mode of the location can be get/set as is possible in the Ring Mobile App without having security panel.

**Comment by dgreif** [comment]
If you only have cameras and not an alarm system, then you want to use `setLocationMode` instead of `setAlarmMode`

**Comment by helmut-hoffer-von-ankershoffen** [comment]
Ah, I see, thx. Works!

**Comment by helmut-hoffer-von-ankershoffen** [comment]
@dgreif Built a little add-on for Home Assistant used to automatically set the location mode based on the presence of residents at home - thx for your lib, works great. https://github.com/helmut-hoffer-von-ankershoffen/hassio-ring-bridge
