### ISSUE TITLE
Home app loads for a long time and finally says "No Response"

### ISSUE THREAD

**Issue by dormk23** [dgreif/ring#534]
# Live Streaming Issue

### Describe the live streaming issue
 I went through the logs and find a line - **"pipe:: Operation timed out" for the Audio.** 
**for video, it says "Output file empty"**
might be it?

## What i'm doing:
When I'm opening the Ring app - it streams well there. But when I'm opening the Home app - it loads for a long time, Homebridge logs shows that its streaming, and after a minute or so I get a "No Response", where underneath it says "This camera is not responding.".
Cached snapshot works good as well.

### Screenshots/Logs
 
`[12/28/2020, 12:51:21 PM] [Ring] Return Audio (Front Door): pipe:: Operation timed out

[12/28/2020, 12:51:21 PM] [Ring] Return Audio (Front Door): Output #0, rtp, to 'srtp://127.0.0.1:55421?pkt_size=188':
  Metadata:
    title           : Talk
    encoder         : Lavf58.45.100
    Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
    Metadata:
      encoder         : Lavc58.91.100 pcm_mulaw

size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)

[12/28/2020, 12:51:21 PM] [Ring] Return Audio (Front Door): stopped gracefully`

### Recommended solution
 could be a problem with the transcoder.

### Environment

 - Ring Camera: Peephole Doorbell
 - OS: MacOS 10.15.7
 - Node.js: v14.15.3
 - NPM: v6.14.9
 - homebridge-ring (if applicable): v9.12.8
 - homebridge (if applicable): config-ui-x v4.36.0

### Network Environment
 Netgear AX4 Router, Sagecom F@st3686 Modem, Homekit hub is Apple TV 4K

**Comment by dgreif** [comment]
The `Operation timed out` is actually on the return audio in the logs you included.  I don't see enough info in the logs to debug further than that.  Live streaming has been working very well for 99% of users and has been optimized as much as I can at this point.  Users from other camera plugins have been reporting similar "No Response" issues when trying to stream, which indicates it is probably a homebridge/hap or HomeKit bug.  Closing as I don't have any course of action for live stream issues at this point.
