### ISSUE TITLE
GetDevices hangs on M1 Mac

### ISSUE THREAD

**Issue by tylervsd** [dgreif/ring#539]
# Bug Report

### Describe the Bug
When running the ring-client-api on M1 Mac, the client appears to hang on the getDevices call (sample program below). I realize my environment is not common, and would be happy to help debug as needed.

### To Reproduce

I first saw this issue when running homebridge, then was able to reproduce in a standalone script. Note that I am not a Node js developer so the code below is rough:

Script:
```
import  { RingApi }  from '/opt/homebrew/Cellar/node/15.5.0/node_modules/ring-client-api/lib/api/api.js';

const ringApi = new RingApi({
  refreshToken: 'ABC123',
	debug: true

});
console.log('Initialized Ring API');
const locations =  await ringApi.getLocations();
const allCameras = await ringApi.getCameras()

console.log(
    `Found ${locations.length} location(s) with ${allCameras.length} camera(s).`
)

const    location = locations[0];
//location is logged properly
console.log(location);
const devices = await location.getDevices()
//Code never makes it here
console.log('Got Devices');
```

From stepping into the code, the following area of ring-client-api location.js is what appears to never return:
```
return new Promise((resolve, reject) => {
                connection.once('connect', () => {
                    resolve(connection);
                    this.onConnected.next(true);
                    util_1.logInfo('Ring connected to socket.io server');
                    assets.forEach((asset) => this.requestList(deviceListMessageType, asset.uuid));
                });
                connection.once('error', reject);
            }).catch(reconnect);
```

### Expected behavior
Expect the list of devices to be returned

### Screenshots/Logs
NA

### Additional context
I have homebridge-ring running fine on a Raspberry Pi, so I don't feel this is specific to my network

### Environment
I installed node/npm using the ARM HomeBrew build for the M1 Mac.
 - OS: MacOS 11.1
 - Node.js: 15.5.0
 - NPM: 7.3.0
 - ring-client-api: 9.12.8

**Comment by dgreif** [comment]
Thanks for providing all the info in the issue template!  You are on Node 15, which causes the issue you are seeing.  If you install the latest node 14, it should work just fine.

**Comment by tylervsd** [comment]
Thank you so much for the prompt reply. Good to hear this is a known issue. I will install node14

**Comment by dgreif** [comment]
@tylervsd any luck?

**Comment by tylervsd** [comment]
@dgreif - Thank you for the follow-up. Unfortunately it does not look like Node 14 will be supported natively on the M1 ( https://github.com/nodejs/node/issues/36161 ).

In the meantime I have kept the ring client running on my Raspberry Pi (where it works great). I didn't want to manage side-by-side Intel and ARM Node installs on my M1 :) 

I have also found another homebridge plugin with a similar issue, so it is not just the ring plugin that is impacted.

For my own knowledge, is this issue due to a bug in Node15, or was a breaking change introduced in Node 15?

Thanks again!

**Comment by dgreif** [comment]
@tylervsd good to know that node 14 isn't compatible on M1! Running it on an rpi is definitely the easiest option, and has the most support since that's how most users have theirs set up.

I'm not exactly sure why node 15 isn't working, but the main observation is that the `socket.io-client` fails to connect to Rings server if you are using node 15.  I haven't found any issues on that package related to node 15.  Might be something that gets figured out eventually, but for now it's safer to just use node 14 which is their current LTS version.

**Comment by tylervsd** [comment]
Sounds good. I will keep updating Node15 periodically on my M1. If things start working I will update the thread. Thanks again!
