### ISSUE TITLE
How to use the examples?

### ISSUE THREAD

**Issue by larxene066** [dgreif/ring#540]
Probably a dumb question, but I'm failing to see any documentation about how to simply use the .ts files provided in the example directory. Are they meant to be fed into ffmpeg as an input?

**Comment by dgreif** [comment]
The `.ts` files are typescript files which can be run with `ts-node` or compile to run with `node`.  The easiest way to run them is to clone the project and run `npm install` and then `npm run example` which runs `example.ts`.  Some of them use ffmpeg, but ffmpeg is not used to run typescript.
