### ISSUE TITLE
Multiple Locations - Won't show accessories unless I specify location ID

### ISSUE THREAD

**Issue by afd696** [dgreif/ring#541]
# Bug Report

### Describe the Bug
Installed Ring on a Hoobs install that is within a docker container on a Synology NAS.  After a successful Ring plugin install and have a good refresh token, accessories won't show.

I have two locations on my ring account.  A home and office.  Only the office seems to load in the logs, and it ignores home.  I can't get the location ID for home because it never loads.  The only way to get my office camera into hoops is to put the location ID in the configuration settings.  My understanding is this plugin is supposed to load all locations if that is left blank.

### To Reproduce
 - Create an `ApiClient`
 - Attempt to ...
 - See error

### Expected behavior
I expect to be able to see all ring devices or be able to just limit it to my home devices.

### Screenshots/Logs
Only ring mention in the logs:
[Ring] Configuring 1 cameras and 2 devices for location "Albany - CTR World HQ" - locationId: [redacted]
1/1/2021, 4:48:10 PM [Ring] Adding new accessory [redacted] lpd_v2 Office
1/1/2021, 4:48:10 PM [Ring] Adding new accessory [redacted] chime_pro Bay Area
1/1/2021, 4:48:14 PM [Ring] Preparing Live Stream for Office
1/1/2021, 4:48:15 PM [Ring] Waiting for stream data from Office (0.526s)
1/1/2021, 4:48:25 PM [Ring] Stopped Live Stream for Office

### Additional context
 Add any other context about the problem here.

### Environment

 - OS: Synology DSM 6.2.3-25426 Update 3, HOOBS 3.12.1
 - Node.js: 14.15.1
 - NPM: 6.14.8
 - ring-client-api: 9.13.0 (updated today from previous version without change)

**Comment by dgreif** [comment]
Do you happen to have a Ring Alarm or smart lighting hub at the other location that is offline?  That would cause the behavior you are seeing.  There should be more info further up in your logs either way.  Try removing the locationIds config and running it again, looking for anything prefixed with `[Ring]`

**Comment by afd696** [comment]
at home I have a ring alarm and smart lighting hub, both are online.  the office does not have those.  I have removed the locationid in the config and ran again.  This is all I get.  I've searched through the logs and nothing more.  seems to stop here.

I know it says that a bridge is offline, however it is only a chime pro and a single doorbell camera there.  I can't identify my home locationid as I would try to force the plugin just to use that.  I have tried a lot of stuff over past few days before posting here. Somehow it just won't go past this point.

[Ring] Creating location socket.io connection
1/1/2021, 6:41:56 PM [Ring] Configuring 1 cameras and 2 devices for location "Albany - CTR World HQ" - locationId: [redacted]
1/1/2021, 6:41:56 PM [Ring] Ring connected to socket.io server
1/1/2021, 6:41:56 PM [Ring] Ring beams_bridge_v1 [redacted] is offline or on cellular backup.  Waiting for status to change

**Comment by dgreif** [comment]
The last line says your beams hub, aka smart lighting hub, is offline. That's why it's waiting.

**Comment by dgreif** [comment]
@afd696 were you able to track down the offline hub?

**Comment by afd696** [comment]
> @afd696 were you able to track down the offline hub?

Yes - just figured it out. Some type of hub was added in that didn’t actually exist. Seems to have fixed all of my issues. I still think it would be good to be able to pull your location ids from ring. Seems to help in some troubleshooting. Thanks.

**Comment by dgreif** [comment]
Added some additional logging at startup to show all location ids before attempting to connect to them.  Hope that helps anyone who runs into similar issues in the future.
