### ISSUE TITLE
Ring Notifications on HomeKit compatible Sony TV

### ISSUE THREAD

**Issue by qsgithub1** [dgreif/ring#542]
# Feature Request

### Description
Ring notification like tvOS on HomeKit compatible TV

### Describe the solution you'd like
It would be nice for my Sony TV to receive Ring doorbell notifications, it might be possible as it supports HomeKit out the box

### Describe alternatives you've considered
None
### Device data
TV is Sony AF9, AG9 which are both HomeKit compatible

**Comment by scottsimon1979** [comment]
Just wanna say I'd love this functionality as well on any homekit compatible TV device.  I have several and I'd love that.

**Comment by dgreif** [comment]
Does the Sony TV allow you to interact with other HomeKit devices from the screen, or is it more of an accessory where you can control the TV from other HomeKit devices?  Either way, HomeKit (not homebridge) is responsible for how notifications flow to devices and when/how they show up.  The plugin currently informs HomeKit when the doorbell is pressed, and then HomeKit takes it from there.  Unfortunately there is nothing more that can be done from the plugin side.
