### ISSUE TITLE
Alarm "night mode" bypass implementation has unintended consequences

### ISSUE THREAD

**Issue by michaelyork** [dgreif/ring#545]
# Bug Report

### Describe the Bug
I love the idea behind the Night mode feature you've built for homebridge-ring and Ring Alarm, but the way it's implemented (where it does not actually **stay** in Night mode, but rather bypasses sensors and then switches to either Home/Away mode) produces a couple of bugs that make it difficult to use in certain situations.

1. A scene that includes setting the alarm to Night mode will always return "Failed" because it's waiting for the target state of "Night" to be achieved, but the plugin will always reset it to Home/Away (as selected in plugin config).
2. This one's an odd one, but something about the quick resetting behavior from Night to Home/Away fails when trying to set the alarm to Night mode via the Home app from a **cellular** connection. Setting it over local WiFi works fine. I know – weird – but completely reproducible for me. Happy to provide footage if helpful.

### To Reproduce
For issue 1:
- Add alarm to a scene
- Set scene's alarm state to Night
- Save and try setting scene

For issue 2:
- Enable plugin option for Night mode mapping to Home or Away w/ bypass
- Disconnect from WiFi / disable WiFi on iOS device
- Try setting alarm to Night

### Expected behavior
Some options:

- (My ideal solution) Plugin has an option to always bypass faulted sensors when setting to Home. Would resolve both issues.

- Plugin has an option to retain HomeKit state of Night mode after bypassing sensors. Would also resolve both issues.

### Screenshots/Logs
Please let me know what I can provide to assist you further.

### Additional context
Thanks for building this great plugin! Happy to donate.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
        {
            "refreshToken": "xxx"
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "nightModeBypassFor": "some",
            "hideDeviceIds": [],
            "locationIds": [
                "xxx"
            ],
            "platform": "Ring"
        }
```

### Environment

 - OS: Ubuntu 18.04.5 LTS
 - Node.js: 14.15.3
 - NPM: 6.14.9
 - homebridge-ring: 9.14.0
 - homebridge: 1.2.5
 - hoobs: N/A

**Comment by dgreif** [comment]
@michaelyork sorry it took me so long to get a fix out for this.  It's been on my radar, but camera issues were a higher priority.  I really appreciate the thorough write-up!  I've opted to keep the alarm in Night mode after it is armed as the best solution.  Give it a try in v`9.21.0` and let me know how it works for you!

**Comment by michaelyork** [comment]
@dgreif You're the man! No apology needed – thanks for the great work you're sharing with all of us.
