### ISSUE TITLE
Ring Adding End To End Encryption

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#549]
Will this stop the plugin from working?

https://www.engadget.com/ring-end-to-end-encryption-doorbell-security-2021-040000314.html

**Comment by dgreif** [comment]
Yes, this will almost certainly prevent video streams from working via the homebridge plugin.  It _may_ be possible to get it working if you supply the encryption key to the plugin, but it will take a fair amount of work to figure out exactly how they are encrypting the video.  Not something I plan to support in the near future unless someone supplies a pull request adding the functionality.

**Comment by moshed** [comment]
is this something that will affect their entire line of products (contact sensors and alarm systems) or just the cameras/doorbells?

**Comment by dgreif** [comment]
It only impacts cameras, and you have to manually turn on end-to-end encryption yourself.  It's not on by default.  It's also only available for wired cameras (likely because they do cloud-based image processing for battery cameras)

**Comment by donjalex2** [comment]
Good thing is that we have to opt in for encryption, so as long as we don't...  video should still work.

**Comment by codyc1515** [comment]
For now...

**Comment by ryanngo0911** [comment]
I did not opt in for end to end encryption but my feeds have been broken since day 1. Any advice?
