### ISSUE TITLE
Random Motion Alerts

### ISSUE THREAD

**Issue by itsgabraf** [dgreif/ring#55]
Does anyone else get random “fake” motion alerts from HomeKit when you open Home on a different device sometimes? I know it’s not real because my Ring app doesn’t make the motion alert notification. But it does make my chimes ring...I have doorbot_v3...

**Comment by dgreif** [comment]
@itsgabraf that sounds pretty odd.  Can you give some more detailed steps on how to recreate this issue?

**Comment by itsgabraf** [comment]
It hasn’t been an every time occurrence but I did notice today and yesterday that a couple of times when I’d open Home on my device, that the Motion notification (from HomeKit) was triggered, which made all my chimes go off but oddly enough not on my Ring app or any Ring official notifications. It did it today again, and something happened that made my Ring app unable to work until I logged out and logged back in. Wish I could explain and give a clear way to replicate it, but I find it’s done it a few times now.

**Comment by dgreif** [comment]
What version of the plugin are you on?

**Comment by itsgabraf** [comment]
latest

**Comment by dgreif** [comment]
It made your Ring Chime go off? As in, the little device that plugs into the wall and makes noise when your doorbell is pressed?

**Comment by itsgabraf** [comment]
Yes

Gabriel Rafael
Menswear Blogger / GQ Insider
www.gabrielrafael.com
0447194078
________________________________

**Comment by dgreif** [comment]
@itsgabraf is this still happening?

**Comment by itsgabraf** [comment]
Nope. Not since V4
