### ISSUE TITLE
 i have uninstalled Ring from Hoobs and i would like the cameras in Home to not show up. 

### ISSUE THREAD

**Issue by Tesla-P100FX** [dgreif/ring#550]
My Ring install stated throwing errors again> reinstalled Plug in, rebooted server, got a new KEY still getting the below every 5 seconds.

[Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/timestamps. Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM. Trying again in 5 seconds...1/13/2021, 3:13:52 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/timestamps. Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM. Trying again in 5 seconds...1/13/2021, 3:13:53 PM

AT this point i have uninstalled Ring from Hoobs and i would like the cameras in Home to not show up.     However when i rebuild my connection on my phone to Homebridge they are still there asking me to pair them. what JSON in what directory do i need to edit via Terminal  for them to go away?

HOOBS Version3.3.2

Node Version12.16.3
My config.json was this below , but i have removed it and the "favorite" cameras still show up

{

"platform": "Ring",

"plugin_map": {

"plugin_name": "homebridge-ring"

},

"hideLightGroups": false,

"hideDoorbellSwitch": true,

"hideCameraSirenSwitch": true,

"hideAlarmSirenSwitch": true,

"hideCameraMotionSensor": false,

"hideInHomeDoorbellSwitch": true,

"hideUnsupportedServices": true,

"cameraStatusPollingSeconds": 299

}

**Comment by dgreif** [comment]
The `NGHTTP2_ENHANCE_YOUR_CALM` error can be fixed by updating node.  See https://github.com/dgreif/ring/issues/548#issuecomment-760288703.  If you still want to remove the plugin, you should just need to remove the plugin and remove the config that you pasted in your issue from the config in HOOBS.  If that doesn't help, reach out to HOOBS support

**Comment by Tesla-P100FX** [comment]
Updating crashed my Hoobs server and it would not reboot , spent the day reimagining and rebuilding plug ins.   I am in good shape now,   Took all day🤨

**Comment by dgreif** [comment]
Wow, sorry to hear that! You can always reach out to HOOBS support if your need help with stuff like that in the future. Glad to hear it's working now tho 😀

**Comment by Tesla-P100FX** [comment]
I figured it was time and would have a better outcome to reimage , appreciate your help
