### ISSUE TITLE
Live feed no longer available

### ISSUE THREAD

**Issue by mreassassin** [dgreif/ring#551]
# Live Streaming Issue

### Describe the live streaming issue
 any time I attempt to view a live feed I get errors and the feed does not show up. It says camera is not responding. Sometimes the snap shots update after exiting the live feed. Sometimes the errors don't show up but never does the feed show up. This was all working until I did an npm update. I've tried several releases and the beta. None work for me for live feed. 

### Screenshots/Logs

 ![image](https://user-images.githubusercontent.com/37232767/104799092-15055200-5781-11eb-8172-49b683f84ce7.jpeg)

![image](https://user-images.githubusercontent.com/37232767/104799098-1afb3300-5781-11eb-88c6-f6a5b0899ec2.jpeg)

### Recommended solution
 What is the recommended npm version? Can I revert back to that?

### Environment

 - Ring Camera: ring doorbell pro
 - OS: Raspbian
 - Node.js: 14.15.1 
 - NPM: 6.14.11 
 - homebridge-ring (if applicable): 19.14.1
 - homebridge (if applicable): 1.2.5
 - hoobs (if applicable):

### Network Environment

ASUS mesh network with one router and one mesh node. Running homebridge via raspberry pi.

**Comment by mreassassin** [comment]
![image](https://user-images.githubusercontent.com/37232767/104799198-f8b5e500-5781-11eb-83f5-c57108dd7315.jpeg)

![image](https://user-images.githubusercontent.com/37232767/104799200-fd7a9900-5781-11eb-9d29-3a81f41b6e03.jpeg)

**Comment by dgreif** [comment]
It doesn't look like homebridge is receiving any data from the camera.  Can you confirm that it is able to stream via the Ring app?

**Comment by mreassassin** [comment]
This may be helpful...

![image](https://user-images.githubusercontent.com/37232767/104799279-ae813380-5782-11eb-8899-e4e9b523a53a.jpeg)

**Comment by mreassassin** [comment]
Yes. Steaming via the ring app is good

**Comment by mreassassin** [comment]
I was just viewing the live feed from the ring app then closed that feed and opened the feed in HK. That works. 
If I then close the feed in HK and try to re open it in HK, it fails.

**Comment by mreassassin** [comment]
I was noticing other devices offline last night so I gave this a few more tests on the ring app and back to HK. Ring was intermittent so I have a couple reboots to my routers and verified the ring doorbell was online. I didn't try to check the live feed in HK until this morning. All is well now. I'd chalk it up to some funky network conflict or error. All good now! Thank you!
