### ISSUE TITLE
When adding accessories or updating homebridge, ring accessories move back to "default" room

### ISSUE THREAD

**Issue by JeremyLaurenson** [dgreif/ring#552]
# Bug Report

### Describe the Bug
If I add new sensors to ring or update the plugin I very often have my ring accessories all default back to the default room, breaking automations and causing me to have to reassign dozens of devices.

### To Reproduce
Add device in ring.
Restart homebridge

### Expected behavior
Only new devices should be in "default" room

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
  {
      "refreshToken": "xxxxxxxx",
      "debug": false,
      "cameraStatusPollingSeconds": 30,
      "platform": "Ring"
  },
```

### Environment

 - OS: Raspbian GNU/Linux Buster (10) 
 - Node.js:v14.15.3
 - NPM: 6.14.9
 - homebridge-ring: homebridge-ring v9.14.1 
 - homebridge: Homebridge v1.2.5
 - hoobs: na

**Comment by dgreif** [comment]
That's a really rough thing to have happen!  It happened to me few weeks ago when I was switching back and forth between beta versions of the ring plugin, many of which were erroring before they could fetch devices.  Really sucked to remember and reconfigure all the automations.  Outside of that one occurrence, I've never seen this happen.  I'm curious if this is still occurring in your setup now that a lot of those connection bugs have been worked out.  It's one of those issues that going to be really hard to track down if it's still around.  Do you happen to have the homebridge logs from any occurences?  Also, is it just accessories connected to the Ring alarm that get reset, or cameras too?

**Comment by JeremyLaurenson** [comment]
This has been happening for months now. Cameras as well as switches for lights seem to move. I have noticed that according to some applications those devices have no serial numbers associated  I wonder if that is an issue for identifying them

**Comment by JeremyLaurenson** [comment]
![12D577BE-0169-4FBB-B856-C8BBF461D0B9](https://user-images.githubusercontent.com/942556/104847557-b6d68d00-58ae-11eb-9f24-ce6646e22c71.png)
![EBF33F0B-B89D-4A4C-B108-EC2685CB1633](https://user-images.githubusercontent.com/942556/104847559-b807ba00-58ae-11eb-91a7-d7d2089b6b69.png)

**Comment by dgreif** [comment]
I just noticed you are on homebridge 1.2.5, which is known to have some issues.  Could you try downgrading to 1.1.7 or trying the latest beta version of homebridge and see if the issues persist?

**Comment by JeremyLaurenson** [comment]
New Beta solves the issue

**Comment by dgreif** [comment]
Glad to hear that!  I actually hit the same issue earlier this week after updating to beta.53.  Chatted with the other homebridge devs and hopefully it won't happen moving forward.
