### ISSUE TITLE
Chime on repeat

### ISSUE THREAD

**Issue by rcoletti116** [dgreif/ring#556]
# Bug Report

### Describe the Bug
When running v9.14.1 and using the Ring Chime in an automation enabled using an automation, when the automation is triggered the chime will play endlessly until Homebridge is restarted.

### To Reproduce
 - Enable automation with the Ring Chime in response to some sensor or geofence.
 - Trigger automation
 - Chime will repeat over and over until HB is restarted.

### Expected behavior
Chime should turn on/off once.

### Screenshots/Logs
There are no logs displayed for this problem.

### Additional context
Specifically I use the chime in location based automation when someone arrives home.
This issue does not occur on v9.14.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
        {
            "refreshToken": "XXX",
            "platform": "Ring"
        },

```

### Environment

 - OS: Raspbian GNU/Linux Buster (10)
 - Node.js: v12.18.3
 - NPM: v6.14.8
 - homebridge-ring: 9.14.1
 - homebridge: 1.2.5
 - hoobs: N/A

**Comment by dgreif** [comment]
@rcoletti116 try updating to node 14.  12.18.3 has issues with Http2 and causes repeated requests to the server, which is most likely why you are experiencing this issue

**Comment by rcoletti116** [comment]
It seems that did the trick. Thanks!
