### ISSUE TITLE
It doesn’t work correctly on iOS 14.4

### ISSUE THREAD

**Issue by eliammarrero** [dgreif/ring#558]
# Bug Report

### Describe the Bug

Official iOS 14.4 has been released. Same behavior from the beta. It not able to handle multiple cameras. It's froze all after the third. On Ring app works fine. 

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
iOS 14.4 has not been released.  The 14.4 RC was released today, which is still not an official full release and will not be supported.  Also, please fill out the entire issue template as it provides a lot of information that helps me debug without asking a bunch of questions.  Hopefully Apple gets this sorted out before doing the true 14.4 release.
