### ISSUE TITLE
In-Home doorbell switch not appearing in Home-app

### ISSUE THREAD

**Issue by m1ch37** [dgreif/ring#563]
# Bug Report

### Describe the Bug
 I want to disable the in-home doorbell using an automation, but i am not able to turn the doorbell on or off in the Apple home-app. In a previous version there was a switch that i could use to toggle the in-home doorbell. 

### To Reproduce
 - Start Homebridge
 - Open PLUGINS-tab 
 - Open settings for this plugin
 - Click OPTIONAL CONFIGURATION
 - Uncheck 'HIDE IN-HOME DOORBELL SWITCH'
 - Click SAVE & restart Homebridge

### Expected behavior
 I expect to see a newly added switch to toggle the in-home doorbell on/off

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_

```
        {
            "refreshToken": "eyJhb.......",
            "hideCameraMotionSensor": true,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": false,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "avoidSnapshotBatteryDrain": true,
            "platform": "Ring"
        }

```

### Environment

 - OS: Debian GNU/Linux Buster (10)
 - Node.js: v14.15.3 
 - NPM: 6.14.9 
 - homebridge-ring: 9.14.2
 - homebridge: 1.1.7

**Comment by dgreif** [comment]
That's odd, I haven't made any changes to how the in home doorbell switch works recently. Mine still showing up fine if I go into the Accessories within my doorbells camera. Did you turn that "hide" setting on for a reason, or just for testing after the switch disappeared?

**Comment by m1ch37** [comment]
Thank you for your prompt feedback! I do see a doorbell ("Deur") that i can mute in the Homebridge UI, but that button is not visible in the Home-app. When i set the button to mute or unmute then the in-home doorbell always works and does not mute. Could you check to see if the mute function works for you? 

I tried to hide the button and then unhide the button to fix the issue, but it did not solve it. I also reinstalled the plugin, but that also didn't work for me. 

Thanks again for your help!

Thanks,
Michel

<img width="609" alt="Schermafbeelding 2021-01-31 om 18 12 31" src="https://user-images.githubusercontent.com/43075336/106391928-fd200600-63ef-11eb-979b-649ae4c00726.png">

**Comment by dgreif** [comment]
Thanks for clarifying what you are seeing.  That "Mute" button is actually connected to the audio output on the camera itself.  If you turn on that mute, you will not be able to speak out of the camera via the Home app.  The In Home doorbell switch is shown as a separate switch.  Here's how you get to it via the Home app:

Start streaming from the camera, then click on the settings icon
![image](https://user-images.githubusercontent.com/3026298/106392427-fde47800-63ae-11eb-8540-ead024c2bbca.png)

Click on Accessories within the settings
![image](https://user-images.githubusercontent.com/3026298/106392432-08067680-63af-11eb-9a40-4dbe1a1b592f.png)

The in-home doorbell accessory should show up in here
![image](https://user-images.githubusercontent.com/3026298/106392443-118fde80-63af-11eb-9fd6-863cc54ac125.png)

If you do _not_ see the in-home doorbell switch in there, then I would wonder if you are confusing the in-home doorbell with a chime. Do you have a traditional doorbell (mechanical or digital) wired in your home connected physically to your ring doorbell, or do you have a Ring Chime as your in-home doorbell?

**Comment by m1ch37** [comment]
Thanks again! I do not see the in-home doorbell switch in this view - see below. I have no Ring Chimes in my home, but i do have a mechanical doorbell that rings when the button on the doorbell is pressed. I would like to turn off this mechanical doorbell when my children are sleeping, so i want to set this in an automation. 

I did see the switch before, but i haven't seen it for a while. Not sure when it changed.. Do you know if there is a way to go back to default? I reinstalled the plugin, but perhaps that kept some of my history?

**Comment by dgreif** [comment]
Can you confirm that you are able to turn the in-home doorbell on and off from the Ring app?  I wonder if Ring lost track of it.  If you can control it in the Ring app, the next step would probably be to have you post the output from the [Data Discovery Tool](https://github.com/dgreif/ring/wiki/Data-Discovery) and I can verify that everything looks correct

**Comment by m1ch37** [comment]
I checked the app earlier and could not find any setting related to the machanical doorbell. See attached the output data, hope this gives you any answers. 

Thanks again! 
Michel

[ring-json.txt](https://github.com/dgreif/ring/files/5900388/ring-json.txt)

**Comment by dgreif** [comment]
Thanks for providing the device data and looking through the Ring app.  These both confirm that you Ring camera isn't currently configured to support an in-home doorbell (even though it physically works).  In the Ring app, open the setting for your camera, then go to Device Settings -> Genera Settings -> Doorbell Chime Type (under Internal Doorbell Settings).  Here, select Mechanical or Digital, whichever is accurate to your actual doorbell.  Once you save that, you can restart homebridge and the In-Home doorbell button should show up again within your camera in the Home app.

**Comment by m1ch37** [comment]
I checked the app, but i do not have any option to set a chime type in the app. Can you share a printscreen? 

Thanks!

**Comment by dgreif** [comment]
![image](https://user-images.githubusercontent.com/3026298/106665565-b3582c80-6563-11eb-9868-794342c5f040.jpeg)

**Comment by dgreif** [comment]
@m1ch37 did you find these settings in the Ring app?

**Comment by m1ch37** [comment]
I found the page, but the internal doorbell settings are missing. Not sure if there is anything i can do to fix this, but i assume it is also why i don’t see the switch in the Home app. 
![C28D8740-735F-43FC-B413-A1F4E4069AA0](https://user-images.githubusercontent.com/43075336/107147298-8d5cce80-694d-11eb-9bd6-17a453ef9791.jpeg)

**Comment by dgreif** [comment]
Which doorbell camera do you have? Did the button show up for you previously with this same camera?

**Comment by m1ch37** [comment]
Yes, the button was visible previously but i’m not sure when it was. I have the first version of the Ring doorbell.

**Comment by dgreif** [comment]
I think the best thing at this point would be for you to reach out to Ring support and have them help figure out why those options aren't showing up for you. May be something with your wiring or transformer, but not something I know enough about to help solve. Once those settings are back and set properly in the Ring app, the button should show up on HomeKit again after a restart. I wouldn't mention the homebridge plugin when you contact them, just to be on the safe side :). Let me know how it goes

**Comment by dgreif** [comment]
@m1ch37 any luck getting the Ring app settings fixed?

**Comment by dgreif** [comment]
@m1ch37 any updates?

**Comment by dgreif** [comment]
Closing since this seems like an issue on Rings end, or in the physical setup. Please let me know if anything changes.
