### ISSUE TITLE
Mailbox

### ISSUE THREAD

**Issue by cello8619** [dgreif/ring#564]
Would like support for the new mailbox motion sensor.  Would be great to be able to utilize HomeKit automations for when the mailbox triggers.

**Comment by dgreif** [comment]
I'd be happy to get the mailbox sensor added.  Can you follow the steps here: https://github.com/dgreif/ring/wiki/Data-Discovery.  Once I get a look at the data, it should be a pretty easy change

**Comment by cello8619** [comment]
Hi Dgreif,

Thanks for the quick response, I just checked and won't be able to run the attached as the data will not be there.  Reason being the main ring account is in another login and it is shared with the login I use in home bridge.  If I swap it out it will (I assume) break all of our current automations.  Since the Ring Mailbox is setup like a light group which ring currently does not allow sharing with, I do not see the device in my shared ring access.

Maybe, someone else in the group has the mailbox sensor and is using the main account to link home bridge to ring that can share their data.

Mike

**Comment by fallingrock** [comment]
[ring-mbox-json.txt](https://github.com/dgreif/ring/files/5911718/ring-mbox-json.txt)

**Comment by dgreif** [comment]
Thanks for the data @fallingrock!  From what I can tell, the sensor is set up just like the Ring Smart Lighting Motion Sensors (`motion-sensor.beams`), which were already supported.  I don't see anything different that indicates it won't work as-is.  @fallingrock @cello8619 do you see the mailbox sensor showing up as a motion sensor in HomeKit?

**Comment by fallingrock** [comment]
![image](https://user-images.githubusercontent.com/4029821/106630144-31570c00-6541-11eb-9df3-9d657ba4d9c9.png)

**Comment by fallingrock** [comment]
Interesting that it's showing as charging.

**Comment by dgreif** [comment]
@fallingrock thanks for confirming that it shows up.  Looks like your battery is at 100%, and reports a `batteryStatus` of `charged`, which the code assumes means it's "charging".  

@cello8619 are you able to see a similar sensor?

**Comment by cello8619** [comment]
@dgreif All set, I changed the plug-in credentials to the main account login from Ring and I see the mailbox now.  Hopefully in future Ring will allow the sharing of light groups to authorized user logins as well, even on the Ring app the shared access users can't access any of the lighting.
