### ISSUE TITLE
No Alarm/Mode Status In Home App

### ISSUE THREAD

**Issue by walshy1009** [dgreif/ring#565]
Bug Report

Describe the Bug
Missing alarm status control in the home app. Don’t know when this started happening precisely as I only noticed it recently due to wanting to set up automations based around alarm status.

To Reproduce
Couldn’t tell you :/

Expected behavior
Being unable to change alarm/mode status from the home app for ring devices.

Screenshots/Logs
Will provide if needed!

Additional context
Tried upgrading, downgrading, removing cached accessories and uninstalling and reinstalling the plugin together, all with no luck.

Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

 {
            "refreshToken": "xxx",
            "platform": "Ring"
        }

```
Environment
 - OS: Ubuntu Focal Fossa (20.04.1 LTS)
 - Node.js: v14.15.0
 - NPM: v6.14.8
 - homebridge-ring: v9.14.2
 - homebridge: v1.1.7
 - hoobs: N/A

**Comment by dgreif** [comment]
Very little to go off of here unfortunately.  My alarm is still showing up no problem.  Might be helpful if you follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and I can verify your alarm shows up in the results.  Did did you make any other changes recently, like switching to a shared account, etc?

**Comment by walshy1009** [comment]
> Very little to go off of here unfortunately. My alarm is still showing up no problem. Might be helpful if you follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and I can verify your alarm shows up in the results. Did did you make any other changes recently, like switching to a shared account, etc?

No other changes as far as I know of other than adding a new ring camera (spotlight cam) as of yesterday. Have always had my Mum as an invited user.

{"locations":[{"name":"xx","cameras":[{"description":"Front Door","subscribed":true,"subscribed_motions":true,"battery_life":"98","external_connection":false,"firmware_version":"Up to Date","kind":"cocoa_doorbell","settings":{"cv_settings":{"detection_types":{"human":{"enabled":true,"mode":"cloud","record":null,"notification":null},"loitering":{"enabled":null,"mode":"none","record":null,"notification":null},"motion":{"enabled":true,"mode":"cloud","record":null,"notification":false}},"threshold":{"loitering":10}},"cv_paid_features":{"human":true,"loitering":true,"motion":true,"other_motion":true,"package_delivery":true,"package_pickup":true},"concierge_settings":{"mode":null},"other_paid_features":{"alexa_concierge":true},"sheila_settings":{"sheila_camera_settings":null},"offline_motion_event_settings":{"subscribed":true,"enabled":false,"max_upload_kb":5000,"resolution_p":360,"frequency_after_secs":2,"period_after_secs":30},"lite_24x7":{"subscribed":true,"enabled":true,"frequency_secs":3600,"resolution_p":360},"enable_vod":1,"exposure_control":2,"motion_zones":[1,1,1,0,0],"motion_snooze_preset_profile":"medium","motion_snooze_presets":["none","low","medium","high"],"live_view_preset_profile":"middle","live_view_presets":["low","middle","high","highest"],"pir_sensitivity_1":5,"vod_suspended":0,"doorbell_volume":4,"vod_status":"enabled","video_settings":{"encryption_enabled":null},"advanced_motion_detection_enabled":true,"advanced_motion_zones":{"zone1":{"name":"Zone 1","state":2,"vertex1":{"x":0,"y":0.24955116},"vertex2":{"x":0.490404,"y":0.24955116},"vertex3":{"x":0.8681818,"y":0.25314182},"vertex4":{"x":0.869697,"y":0.6117841},"vertex5":{"x":1,"y":0.61400354},"vertex6":{"x":1,"y":1},"vertex7":{"x":0,"y":1},"vertex8":{"x":0,"y":0.6862904}},"zone2":{"name":"Zone 2","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}},"zone3":{"name":"Zone 3","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}}},"advanced_motion_detection_human_only_mode":true,"enable_audio_recording":true,"people_detection_eligible":true,"live_view_disabled":false,"ignore_zones":{"zone1":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone2":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone3":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone4":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}}},"enable_rich_notifications":true,"rich_notifications_billing_eligible":true,"loitering_threshold":10,"advanced_motion_detection_types":["human"],"motion_detection_enabled":true,"rich_notifications_scene_source":"cloud","recording_storage_type":"default_s3","advanced_motion_zones_enabled":true,"advanced_motion_zones_type":"8vertices","advanced_pir_motion_zones":{"zone1_sensitivity":5,"zone2_sensitivity":5,"zone3_sensitivity":5,"zone4_sensitivity":5,"zone5_sensitivity":5,"zone6_sensitivity":5},"rich_notifica-uuid":false},"features":{"motion_zone_recommendation":false,"motions_enabled":true,"show_recordings":true,"show_vod_settings":true,"rich_notifications_eligible":true,"show_24x7_lite":true,"show_offline_motion_events":false,"cfes_eligible":null,"chime_auto_detect_capable":false},"owned":true,"alerts":{"connection":"online","ota_status":"successful"},"motion_snooze":null,"stolen":false,"is_sidewalk_gateway":false,"created_at":"2020-07-14T07:29:25Z","shared_at":null,"active_schedule_uuid":null,"ext_power_state":0},{"description":"Front","subscribed":true,"subscribed_motions":true,"battery_life":"89","external_connection":false,"firmware_version":"Up to Date","kind":"stickup_cam_v4","settings":{"cv_settings":{"detection_types":{"human":{"enabled":false,"mode":"none","record":null,"notification":false},"loitering":{"enabled":false,"mode":"none","record":null,"notification":false},"motion":{"enabled":true,"mode":"edge","record":null,"notification":true},"moving_vehicle":{"enabled":false,"mode":"none","record":null,"notification":false},"other_motion":{"enabled":false,"mode":"none","record":null,"notification":false},"package_delivery":{"enabled":false,"mode":"none","record":null,"notification":false},"package_pickup":{"enabled":false,"mode":"none","record":null,"notification":false}},"threshold":{"loitering":10}},"cv_paid_features":{"human":true,"loitering":true,"motion":true,"other_motion":true,"package_delivery":true,"package_pickup":true},"other_paid_features":{"alexa_concierge":true},"sheila_settings":{"sheila_camera_settings":null},"offline_motion_event_settings":{"subscribed":true,"enabled":false,"max_upload_kb":5000,"resolution_p":360,"frequency_after_secs":2,"period_after_secs":30},"lite_24x7":{"subscribed":true,"enabled":true,"frequency_secs":840,"resolution_p":360},"enable_vod":1,"exposure_control":2,"motion_zones":[1,1,1,1,1],"motion_snooze_preset_profile":"low","motion_snooze_presets":["none","low","medium","high"],"live_view_preset_profile":"middle","live_view_presets":["low","middle","high","highest"],"pir_sensitivity_1":4,"vod_suspended":0,"doorbell_volume":8,"vod_status":"enabled","video_settings":{"encryption_enabled":false},"advanced_motion_detection_enabled":true,"advanced_motion_zones":{"zone1":{"name":"Zone 1","state":2,"vertex1":{"x":0.31204355,"y":0.524249},"vertex2":{"x":0.41425198,"y":0.54847395},"vertex3":{"x":1,"y":0.64437443},"vertex4":{"x":1,"y":1},"vertex5":{"x":0.5310769,"y":1},"vertex6":{"x":0,"y":1},"vertex7":{"x":0,"y":0.24955116},"vertex8":{"x":0.1014675,"y":0.55879706}},"zone2":{"name":"Zone 2","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}},"zone3":{"name":"Zone 3","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}}},"advanced_motion_detection_human_only_mode":false,"enable_audio_recording":true,"people_detection_eligible":true,"live_view_disabled":false,"ignore_zones":{"zone1":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone2":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone3":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone4":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}}},"enable_rich_notifications":true,"rich_notifications_billing_eligible":true,"loitering_threshold":10,"advanced_motion_detection_types":[],"motion_detection_enabled":true,"rich_notifications_scene_source":"cloud","recording_storage_type":"default_s3","advanced_motion_zones_enabled":true,"advanced_motion_zones_type":"8vertices","advanced_pir_motion_zones":{"zone1_sensitivity":5,"zone2_sensitivity":5,"zone3_sensitivity":5,"zone4_sensitivity":5,"zone5_sensitivity":5,"zone6_sensitivity":5},"light_settings":{"brightness":10},"enable_white_leds":1,"rich_notifica-uuid":false},"features":{"motion_zone_recommendation":false,"motions_enabled":true,"show_recordings":true,"show_vod_settings":true,"rich_notifications_eligible":true,"show_24x7_lite":true,"show_offline_motion_events":false,"cfes_eligible":false},"owned":true,"alerts":{"connection":"online","rssi":"low","ota_status":"no_ota"},"motion_snooze":{"scheduled":true},"stolen":false,"is_sidewalk_gateway":false,"created_at":"2021-02-02T11:16:51Z","shared_at":null,"active_schedule_uuid":null,"battery_life_2":null,"battery_voltage":4042,"battery_voltage_2":208,"led_status":{"seconds_remaining":0},"siren_status":{"seconds_remaining":0},"night_mode":0,"ext_power_state":0}],"chimes":[{"description":"Front Room","firmware_version":"Up to Date","kind":"chime_pro_v2","settings":{"volume":11,"status_led_enable":true,"night_light_settings":{"light_sensor_enabled":true,"luma_light_threshold":0,"schedule_enabled":false,"start_time":64800,"stop_time":21600,"duration":null,"light_level":null,"flashing":null}},"features":{"ringtones_enabled":true,"cfes_eligible":null},"owned":true,"alerts":{"connection":"online","ota_status":"successful"},"do_not_disturb":{"seconds_left":0},"stolen":false,"is_sidewalk_gateway":false,"created_at":"2020-07-14T05:02:27Z","shared_at":null,"night_light_state":"unknown"}],"devices":[]}],"amazonKeyLocks":[]}

**Comment by dgreif** [comment]
Just to clarify, do you have a Ring Alarm system, or are you trying to use the Location Modes feature?

**Comment by walshy1009** [comment]
> Just to clarify, do you have a Ring Alarm system, or are you trying to use the Location Modes feature?

Location modes :)

**Comment by dgreif** [comment]
@walshy1009 I've seen a few other reports of this issue with location modes not showing up. I haven't had a chance to try to recreate it yet, but I'm guessing Ring changed one of the fields I was using to determine if modes was enabled

**Comment by dgreif** [comment]
@walshy1009 would you mind installing `9.15.3-beta.0` and then rebooting and checking your logs?  There should be a line in there like ` Location Mode: {"mode":"away","lastUpdateTimeMS":1606992479602, ....}` or `Location Mode Skipped: true`.  If you post that line here, that should help me track this down further.  I also made one small change that _might_ fix it, but I'm not terribly optimistic it will.  I'm still not positive what the issue is until I see the new log output.

**Comment by walshy1009** [comment]
> @walshy1009 would you mind installing `9.15.3-beta.0` and then rebooting and checking your logs? There should be a line in there like ` Location Mode: {"mode":"away","lastUpdateTimeMS":1606992479602, ....}` or `Location Mode Skipped: true`. If you post that line here, that should help me track this down further. I also made one small change that _might_ fix it, but I'm not terribly optimistic it will. I'm still not positive what the issue is until I see the new log output.

![4E225EE1-9E5B-4A26-9FA8-4511FED78D99](https://user-images.githubusercontent.com/13233049/108628498-78d11800-74af-11eb-9c93-a510cdd01bf0.jpeg)

**Comment by dgreif** [comment]
Further discussion in discord: https://discord.com/channels/432663330281226270/432671438156070931/813060419182526485.  Looks like `notYetParticipatingInMode` had values in it, but they aren't really useful anymore since the feature is fully rolled out.  Just going to ignore that field going forward.
