### ISSUE TITLE
Camera not responding when trying live but snapshot shows

### ISSUE THREAD

**Issue by todesto** [dgreif/ring#566]
# Live Streaming Issue

### Describe the live streaming issue
Snapshot shows up but when i click to see live video, camera not responding error comes up

### Screenshots/Logs
i see this in the log. 

[Ring] Request to https://api.ring.com/clients_api/ring_devices failed with status 504. Response body:

### Recommended solution
api? could this be refresh token issue?

### Environment

 - Ring Camera: every ring camera, doorbell, stick up
 - OS: hoobs
 - Node.js: latest
 - NPM: [e.g 6.13.4] 
 - homebridge-ring (if applicable): [e.g 6.0.3 or N/A]
 - homebridge (if applicable): [e.g. 0.4.50 or N/A]
 - hoobs (if applicable): [e.g. 0.4.50 or N/A]

### Network Environment
I have mesh network, apple tv and home pod as hub and hoobs to connect ring.

**Comment by dgreif** [comment]
Ring is having server issues today. See https://status.ring.com/ for updates. If you try the cameras from the bring app, they likely won't work there either.
