### ISSUE TITLE
“Cannot Find Module” Errors when trying to connect to ring servers

### ISSUE THREAD

**Issue by enrogue** [dgreif/ring#567]
### Describe the Bug
I receive a number of errors when I try and connect to the ring servers to generate a RefreshToken

### To Reproduce
 - Start Homebridge
 - Install Plug In
 - In Terminal am running the following command “ npx -p ring-client-api ring-auth-cli “

### Screenshots/Logs
Screenshot attached with error messages

### Config
There is nothing in the config other than the below related to Ring since I do not get the prompt fur email, password, etc:

        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "hideDeviceIds": [],
            "locationIds": [],
            "onlyDeviceTypes": []
        }

### Versions
Hoobs 3.3.2
Node 14.15.1
Installed in Docker on Synology NAS
****
![0B8B9A53-699D-403B-86AF-2110FF27D92C](https://user-images.githubusercontent.com/73302989/106788725-53bf5700-661f-11eb-9ddd-0d2245d8452c.jpeg)

**Comment by dgreif** [comment]
Did you try loggin in through the HOOBS UI instead using the auth cli?  It should walk you through it if you go to the settings for the Ring plugin

**Comment by enrogue** [comment]
> Did you try logging in through the HOOBS UI instead using the auth cli? It should walk you through it if you go to the settings for the Ring plugin

Thanks for the reply. These are the instructions I am following (scroll down to configuration): https://plugins.hoobs.org/plugin/homebridge-ring

As for the configuration tab in Hoobs, first field is to enter is the refresh token which I cant generate due to errors as described in original post. Screenshot attached.
![AF5674E0-A4C4-43A9-96B5-20B390B0C67C](https://user-images.githubusercontent.com/73302989/106806757-57120d00-6636-11eb-906b-0038760d1ab3.jpeg)

**Comment by dgreif** [comment]
I reached out to the HOOBS team about this issue and it sound like they will probably release an update for HOOBS 3 to get the UI working properly.  I'll keep you posted if I hear more from them.

**Comment by dgreif** [comment]
@enrogue did this ever get resolved?

**Comment by enrogue** [comment]
Yes and no.
I could not get the authentication key via hoobs. I installed homebridge, retrieved the key, and used it in hoobs.

**Comment by dgreif** [comment]
Great, I'll close this issue then. The ui should be live in the next version of HOOBS
