### ISSUE TITLE
No Audio In Child Bridge

### ISSUE THREAD

**Issue by Marfre888** [dgreif/ring#568]
# Bug Report

### Describe the Bug
I updated my Homebridge installation to 1.3.0 Beta, because the new 'Child Bridge' feature was too important for me to wait for. I moved the Ring plugin to it's own child bridge, and readded it to Homekit. It adds correctly, and video functions (albeit a bit stuttery). Tile screenshot also updates correctly. The only problem I'm facing is that I'm not getting any sound.

### To Reproduce
Move Ring plugin to Child Bridge

### Expected behavior
Get Sound/Voice and no video stutter as when child bridge is disabled.

### Screenshots/Logs

![ring1](https://user-images.githubusercontent.com/63603736/107477229-acd73f80-6b77-11eb-85fe-2cf94a9d268a.PNG)

### Environment

 - OS: Raspbian GNU/Linux Buster (10)
 - Node.js: 14.15.4
 - NPM: 6.14.10
 - homebridge-ring: 9.14.2
 - homebridge: 1.3.0-beta.54

**Comment by dgreif** [comment]
I just did some testing on my end and it appears that this is an issue specifically with the new child bridge setup.  I'm chatting with the rest of the homebridge team and will let you know if we find a solution

**Comment by Marfre888** [comment]
I have removed the plugin from the child bridge last night, and can confirm that it's back to working correctly.

Glad that this issue isn't affecting only me.

Thank you for your help and this plugin.

**Comment by dgreif** [comment]
This is fixed in the latest homebridge beta (61) and should work perfectly when 1.3 is released. One note, if you added a child bridge on one of the earlier beta versions and your audio doesn't work, you will need to remove and re-pair the child  bridge in HomeKit after updating homebridge to get audio working again.

**Comment by Marfre888** [comment]
Thank you, I saw that it was fixed in the release notes.

Will test it out and report any problems..
