### ISSUE TITLE
2 Way Communication

### ISSUE THREAD

**Issue by anuj-biz-insights** [dgreif/ring#569]
# Feature Request

### Description
Hello, I Really love this Library but I would like to get the API or Something like that so I can Manage the two-way communication on the app end currently I am working on an app where I have to integrate multiple smart devices in a single app most of the things are done in ring side but only two-way communication is remaining.

### Describe the solution you'd like
For Single Way, I have used the RTSP server but I am stuck on how I can make two-way

**Comment by Marfre888** [comment]
This plugin already supports 2 way communication

**Comment by anuj-biz-insights** [comment]
> This plugin already supports 2 way communication

How I can make use of it as a live stream currently it stores in mp4

**Comment by dgreif** [comment]
@anuj-biz-insights see https://github.com/dgreif/ring/blob/master/examples/return-audio-example.ts for an example of streaming an audio file back to the camera via the `ring-client-api`

**Comment by anuj-biz-insights** [comment]
> @anuj-biz-insights see https://github.com/dgreif/ring/blob/master/examples/return-audio-example.ts for an example of streaming an audio file back to the camera via the `ring-client-api`

Hello sorry have seen that but not able to get that done right as its getting mp4 file generated it would be best if I can get done like this https://github.com/dgreif/ring/blob/master/examples/browser-example.ts so I can Stream anywhere like live feed

**Comment by dgreif** [comment]
@anuj-biz-insights I'm not quite sure what you are asking for.  The return audio example does not _generate_ an mp4, it uses one that you have stored in your file system.  There are lots of unique use cases and unfortunately I can't build an example for each and every one of them.  In the end, you will need to figure out how you need to configure ffmpeg to do what you want.  It's very flexible, but takes research to get it right.

**Comment by anuj-biz-insights** [comment]
Ok, thank you so much, I have tried to get it done but not able to figure it out that's why asked you but thank you so much for your help really appreciate that.
