### ISSUE TITLE
Base station connection issues 

### ISSUE THREAD

**Issue by jianyu-li** [dgreif/ring#57]
I am now having connection issues with the base station and the official ring app

**Comment by dgreif** [comment]
Log out and back in to the app. I have had similar issues but haven’t had a chance to track it down yet

**Comment by jianyu-li** [comment]
That did the trick. Does it happen often? Thank you very much

**Comment by dgreif** [comment]
No, i think it's only happened 2 times for me over the past several months.  Let me know if it happens to you (or anyone else seeing this issue).  I'll leave this open as a bug so that I have something to track it against.

**Comment by jianyu-li** [comment]
Will do. Thanks for the quick response!

**Comment by LeviJSmith** [comment]
I’ve had it happen 3or4 times in the last week.  Logging out and back in fixed it fir a few day.

**Comment by jianyu-li** [comment]
Does it only happen to the account that’s signed into homebridge or does it happen to anyone that has access to your cameras?

**Comment by dgreif** [comment]
It happened to me again today on the account I use for homebridge. I’m trying to get set up so I can debug the Ring app, but it’s a fair amount of work. @codahq what Xposed module did you use for pinned certain?

**Comment by jianyu-li** [comment]
I just had to log out and log back in again but now I got this message https://imgur.com/gallery/kvRyjF6

**Comment by dgreif** [comment]
Interesting, I wondered if it was a rate limiting issue. Try shutting down homebridge about 3 minutes and then try logging into the Ring app again

**Comment by jianyu-li** [comment]
I created a new shared account to see if that helps. I also wonder if every time I fetch the camera feed it counts toward some quota? I tend to check it more than I should :)

**Comment by jianyu-li** [comment]
Oh and just to report back I did log out for a while and was able to successfully log back in. So thanks for the tip

**Comment by LeviJSmith** [comment]
I only have the one account so I can’t say for sure if it’s just the one account or others.

**Comment by jianyu-li** [comment]
I’ll let you know if having a dedicated account for homebridge helps

**Comment by eddydas** [comment]
My friends and I both experience frequent drop-out of ring session recently. Restarting the entire homebridge fixed it. We're both NOT using 2FA login. Maybe it's the new 2FA architecture from Ring that puts additional timeout there?

**Comment by jianyu-li** [comment]
Just a small update, I had created a dedicated account for homebridge and I haven’t had any issues for 2 days

**Comment by LeviJSmith** [comment]
Thx for the update.  I’ll give that a try.

**Comment by Dillinja2** [comment]
Also having consistent base station connection issues. It’s rare that it stays connected for more than a day. (It was working fine for months prior.) iOS 13b2 FWIW.

**Comment by jianyu-li** [comment]
Try creating a separate ring account, share your system with that account in the ring app, and then using that new account as the login for your config file. That’s working for me so far

**Comment by Dillinja2** [comment]
Tried secondary account. Lost connection in less than an hour.

**Comment by jianyu-li** [comment]
Ah man. It was worth a shot

**Comment by EarthRise626** [comment]
I have been struggling with similar issues the last week or so. I was on version 3 of the plugin prior to yesterday, so I don’t believe the upgrade to 4 is a potential cause.

I too created a separate Ring account for HomeBridge, and all is now working perfectly.

**Comment by jamesg311** [comment]
I was experiencing the same. Ring app was showing as Alarm Base Station and the Smart Lighting Bridge as not connected. Logged out, setup an alternate account to access my devices, then added that account in my Homebridge setup. However, that second account doesn’t have access to Ring Smart Lighting but I think that’s on Ring to fix since I don’t see a way to share those devices when setting up a new account to share with.

**Comment by dgreif** [comment]
Thanks for all the input. I think this started happening when I introduced sessions which are needed for camera events to work properly. I’m guessing the issue is that I create a new session every time with tokens expire (about once an hour) and Ring must be dumping old sessions off the back, which happens to the session from the Ring app. I’ll get an update out this week with an attempted fix.

**Comment by dgreif** [comment]
Everyone, give v`4.0.4` a try.  I am now creating a new session only when the previous session can no longer be found.  I'm also reusing the hardware_id between sessions, which is how Ring identifies which device is making the request so that it can hand out the correct "active dings".  I just updated mine and will monitor my Ring app over the next few days.

**Comment by LeviJSmith** [comment]
I updated this morning.  Will let you know if I see any issues.

**Comment by EarthRise626** [comment]
I just updated to 4.0.7 - will report any issues. So far, everything is stable and responsive.

**Comment by EarthRise626** [comment]
Unfortunately, I just experienced the issue once more this evening when attempting to arm the alarm through HomeKit. This is using a dedicated Ring account for the plugin.

**Comment by Dillinja2** [comment]
Seems I’m in the same boat. 

4.0.7, devices refusing to update status / respond after about 5 hours.

**Comment by dgreif** [comment]
@EarthRise626 @Dillinja2 I think you guys are experiencing something different than the original issue.  What I was experiencing (and it sounds like @jianyu-li was also) was the actual Ring app would loose connection with the base station, but homebridge would continue to function normally.  Can you confirm that your _homebridge_ is what is now loosing connection to the alarm base station?  Is your Ring app staying connected?  Both environments have been perfect for me since updating to `4.0.7` yesterday morning

**Comment by Dillinja2** [comment]
Ah, that is a different behavior.

My issue is, after a period of time, the entirety of the ring alarm devices (including the arming / disarming function) cease to update or allow interaction. 

Rebooting / restarting homebridge remedies this for a time.

**Comment by EarthRise626** [comment]
Yes - I have had no issues with the Ring app timing out or refusing requests. 

My issue is exactly as @Dillinja2 describes. The command to Arm will appear in the HomeBridge log but does not actually occur. A restart has fixed this for a time for me as well.

**Comment by dgreif** [comment]
@EarthRise626 @Dillinja2 this might not work, but could you try using a `refreshToken` instead of `email`/`password`?  See https://github.com/dgreif/ring/wiki/Two-Factor-Auth for details on how to set it up.  This is how I am set up and it is working great.  Note, you need `homebridge-ring` v`4.2.0` installed globally if you use the first command.

**Comment by EarthRise626** [comment]
@dgreif sure! Will install the update this evening and setup the 2FA. I’ll report back!

**Comment by dgreif** [comment]
Awesome!  You can actually follow all of those steps without turning on 2fa and it will work just fine.

**Comment by EarthRise626** [comment]
I had been intending to get the 2FA turned on once supported by the plugin, so this was the perfect opportunity to do so. 

I successfully updated and configured the refresh token. So far, so stable! I’ve successfully armed and disarmed the Alarm multiple times with no issues. Will report back on long-term stability.

Thank you for all of your work on this - it’s a huge help and is greatly appreciated!

**Comment by jianyu-li** [comment]
I was also having some issues arming/disarming so I updated the config file for 2FA as well. Thanks for responding so quickly to issues @dgreif !  Here are the errors I would get

`[7/15/2019, 5:51:35 AM] [Ring] Disarming Ring Alarm
(node:1581) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 414)
(node:1581) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
    at createError (/usr/local/lib/node_modules/homebridge-ring/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/homebridge-ring/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-ring/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:74:11)
(node:1581) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 415)`

and also...


`[7/15/2019, 9:49:20 PM] [Ring] Arming (Home) Ring Alarm
(node:6530) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 359)
(node:6530) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
    at createError (/usr/local/lib/node_modules/homebridge-ring/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/homebridge-ring/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-ring/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:74:11)
(node:6530) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 360)
`

**Comment by dgreif** [comment]
@jianyu-Lin thanks for the logs, that’s really helpful! Just curious, what version of node are you on?

**Comment by jianyu-li** [comment]
@dgreif 6.10.1

**Comment by jianyu-li** [comment]
@dgreif whoops I mean 12.5.0

**Comment by dgreif** [comment]
Ahhh, that might be why. @EarthRise626 are you on node 12 as well?

**Comment by EarthRise626** [comment]
I am on version 10.15.2

**Comment by Dillinja2** [comment]
I updated my Node version to 10.15.2 last night (I was on an older fork) and so far so good.

**Comment by dgreif** [comment]
Based on the stack track that @jianyu-li posted, I took a look through the authentication code and was able to track down a potential cause for the issue.  @EarthRise626 @jianyu-li @Dillinja2 would any of you be willing to turn 2fa back off and use email/password auth (make sure you delete the `refreshToken` line from your config) for a few days and test out v`4.2.1`?  I'm glad it's working well with 2fa, but I want to make sure I get this fixed for anyone not using 2fa and I was never able to recreate the issue myself.  Big thanks in advance!!

**Comment by jianyu-li** [comment]
I’ll make the changes when I get home tonight and test. Do I need to update my node? I thought I was on the most current version but I’m still a bit new at this

**Comment by dgreif** [comment]
@jianyu-li it would actually be best if you stay on the same version just to eliminate as many variables as possible.  12.5.0 is a very new version, so you are not behind at all.

**Comment by EarthRise626** [comment]
@dgreif I will update to 4.2.1 and switch back to traditional authentication right now. Will report back!

**Comment by jianyu-li** [comment]
Sorry I wasn’t able to test @dgreif , we’re getting to ready to head out of town. Sounds like @EarthRise626 is reporting good news. I’ll test some more when I get back in town!

**Comment by Dillinja2** [comment]
Meant to reply- I’ve been solid on the latest rev for 36hrs! Thanks again for the quick fix.

**Comment by dgreif** [comment]
Awesome, thanks for testing @EarthRise626 and @Dillinja2!   Feel free to switch back to 2fa 🎉 🚀 🔒 . Thanks you all for reporting the issue as I was not seeing this one on my end.

**Comment by metroidmen** [comment]
I didn’t know this issue was caused by this plugin! I wondered what on earth was happening! Yeah, this is still occurring for me. And I don’t even have 2FA on. It went away for a few days but popped back up this morning. :/ 

Its super frustrating because i wont get any notifications from my Ring app
or my Home and my Home automations with the cameras motion sensors stop functioning.

**Comment by EarthRise626** [comment]
@metroidmen which version of the plugin are you currently on?

**Comment by metroidmen** [comment]
Newest version. Reinstalling seems to resolve the issue temporarily. I though it was gone until it came back this morning.

**Comment by dgreif** [comment]
@metroidmen are you on `homebridge-ring` v`4.2.1` or `homebridge-ring-alarm` v`3.9.0`?  You must switch to `homebridge-ring` to get the fix for this issue.

@Dillinja2 @EarthRise626 has everything still been good since you updated?

**Comment by metroidmen** [comment]
I’m on the 4.2.1 ring version.

And the issue already popped back up. It’s not allowing me to set my alarm with HomeKit either and it’s driving me bonkers as I can’t even use the ring app without logging out and back in

**Comment by dgreif** [comment]
@metroidmen follow the instructions in https://github.com/dgreif/ring/wiki/Two-Factor-Auth to get a `refreshToken` (you don't need 2fa enabled for it to work).  It seems like using a refresh token instead of email/password tends to avoid this issue.  Let me know if that fixes it for you

**Comment by metroidmen** [comment]
I tried. I can’t figure out how to get it to work. I login to my terminal on my raspberry pi to do it and run the commands and it doesn’t work. It’s the only reason I don’t have 2FA enabled.

**Comment by metroidmen** [comment]
Just says “command not found” when I run either of those commands

**Comment by EarthRise626** [comment]
@dgreif Everything has been working great. No issues whatsoever.

**Comment by dgreif** [comment]
@EarthRise626 thanks for the info.  @metroidmen I am not convinced you have `4.2.1` installed properly.  If you did, the `ring-auth-cli` command should be accessible.  Try running `npm i -g homebridge-ring` and then run `ring-auth-cli` again...

**Comment by metroidmen** [comment]
http://tinypic.com/view.php?pic=2prvb69&s=9

I don’t know what to say. Because I’ve made sure to update to every single version you release. Ive tried reinstalling it again and the same exact message every time.

**Comment by dgreif** [comment]
If you run the `npx` version of it, what output do you get?  Is `npx` found?

**Comment by metroidmen** [comment]
Gives me the same exact error.

**Comment by dgreif** [comment]
Screenshot?

**Comment by metroidmen** [comment]
http://tinypic.com/view.php?pic=1z4wruw&s=9#.XTNdChYpAlQ

**Comment by dgreif** [comment]
Your `npm` install appears to be messed up, preventing globally installed bin files from being run.  Running `npm bin -g` will tell you where your global npm bin directory is (something like `/usr/local/bin`).  That directory needs to be on your `PATH`.  If you don't know how to do that, the easiest thing is probably reinstalling node/npm.

**Comment by metroidmen** [comment]
Tried looking it up and changing the path, still not working. Same errors. 

How do I reinstall node/npm? I’m generally a noob with homebridge.

**Comment by metroidmen** [comment]
Okay, I’m really suspecting something weird is going on. I even just tried uninstalling and reinstalling the plugin and had no luck. 

But I’m getting an alert my base station battery is low, which I understand is a bug you’ve allegedly fixed. 

So something is happening where this app is just not updating.

**Comment by dgreif** [comment]
@metroidmen yeah it definitely sounds like you are on an older version.  Unfortunately reinstalling node/npm is outside the scope of a GitHub issue on this repo.  There should be plenty of info if you try googling it, or others are welcome to jump in and help out here.

**Comment by metroidmen** [comment]
I ended up nuking my entire homebridge and raspberry pi. I’m such a noob I just started from scratch.
