### ISSUE TITLE
Guidance Re homebridge-ring plugin

### ISSUE THREAD

**Issue by Bradley225** [dgreif/ring#572]
Hi, I am hoping this is the right place to ask. I am a bit confused about homebridge-ring plugin I have installed on my OSX device.

I have discovered and installed homebridge and the homebridge-ring plugin and have it seemingly connected as I see my camera in accessories in homebridge although I am unsure what to do next. Should I be able to click on the camera in homebridge ui accessories to instantly view it as it currently isn't clickable?

Using homebridge I have added the ring camera in home app but it only shows that it is updating every 10 seconds although because the camera is pointing at nothing that changes I can't tell if it is actually updating. Also when I click to view live stream I never get a live preview of the camera in home app just a spinner but everything seems to be ok in homebridge logs when I try to view (see below). 

[2/14/2021, 2:07:58 PM] [Ring] Stream Prepared for Front Door (1.603s)
[2/14/2021, 2:07:58 PM] [Ring] Streaming active for Front Door
[2/14/2021, 2:07:59 PM] [Ring] Received stream data from Front Door (1.747s)
[2/14/2021, 2:08:27 PM] [Ring] Stopped Live Stream for Front Door

I have also discovered and added it in my home assistant setup to try to show the ring camera's more up to date snapshot than I am can currently get by waiting 2 1/2 mintues before I can download the motion video using the current homeassistant ring integration and grabbing a frame from the video. Again I can't really see if it is updating but should it be and if so is it configurable?

Is there a way to now live view the camera via VLC for instance? Ideally I just want an up to date image url or something which refreshes as often as possible (I have the ring camera constantly connected to micro usb cable so not bothered about battery drainage if that helps).

Any help appreciated.

**Comment by dgreif** [comment]
@Bradley225 it sounds like everything is working as expected, with the exception of live streams.  The images you see before clicking on the camera are snapshots that should update every 10 seconds (60 seconds if you are not on your home network).  The live stream appears to be failing since you are always seeing a spinner and never getting connected.  Unfortunately these live streaming issues are very difficult to track down since it could be related to your network, or something weird that Ring is doing.  See https://github.com/dgreif/ring/wiki/Camera-Troubleshooting for more detailed information.  Just curious, does the camera stream reliably in the Ring app?

**Comment by Bradley225** [comment]
Hi @dgreif Thanks for responding.

Yes Ring app is fine in viewing my camera live stream. I'll look into that trouble shooting info to try and fix the live streaming issues but as mentioned I really just need a way to have the most up to date image possible from my ring camera to load and show via my own Samsung tv app I use to overlay all my cameras over my TV output. I am currently using an automation to snapshot the newly added homebridge ring camera in homeassistant and then saving the image on my local http server but it doesn't seem like it is changing in homeassistant very often if at all. Do I need to go via homeassistant to get this image or can I get it direct from homebridge-ring plugin itself and is the ring camera always updating in homebridge or does a refresh need to be requested for example as home does when you scroll the camera image into view?

Just need an image as live as poss from ring!

**Comment by Bradley225** [comment]
Also just one more question - should homeassistant when I click the camera also initiate a stream in homebridge logs like home app does because there is no indication I have clicked the camera in the logs it just shows the image larger.

**Comment by dgreif** [comment]
I haven't worked with Home Assistant at all so I can't speak to how it interacts with homebridge.  The snapshot does need to be requested, which HomeKit does any time you scroll to the camera tile in the Home app.

**Comment by Bradley225** [comment]
Thanks @dgrief. I can see that there is a 10 second delay for each image currently from the camera via homebridge. I have the homebridge-ring plugin js files open. Is there a way to change the files to get a 5 second delay or less just for my personal use? I can't seem to work out which file/variable dictates the 10 sec delay or is this snapshot only changed every 10 seconds on the ring servers?

**Comment by dgreif** [comment]
HomeKit controls that 10 seconds delay. That's got often it requests a new snapshot if you have the camera in view in the Home app

**Comment by dgreif** [comment]
Not sure there is anything else for me to do here.  Sounds like your setup is working as well as it can be if you want to go through Home Assistant and Homebridge
