### ISSUE TITLE
Ring Live Stream Via HomeKit Default App

### ISSUE THREAD

**Issue by PhxAZ89** [dgreif/ring#573]
Constant Live Stream
<img width="815" alt="Screen Shot 2021-02-18 at 8 29 07 AM" src="https://user-images.githubusercontent.com/79269615/108379674-63b06c80-71c3-11eb-801f-0770d47e6e6e.png">

Viewing Livestream Through Homekit Viewer
Currently when you are using your ring cameras in Apple Home Kit, Apple is taking a screen shot of your ring cameras and giving you a snippet every 15-30 sec of your cameras. I understand this is because Ring does not give you a live stream view of ALL of your cameras at once. You can only view ring cameras in live stream mode after clicking the desired camera one by one in the ring app. 

Solution: Always on Live Stream
If possible I would love to have the ability when using my HomeKit app to have a constant live stream of all my ring cameras at once without having to open each camera and viewing them individually. Currently you can only view a live stream after opening one camera. Homekit gives you the ability to see all of your cameras in one place. I would like to have all those cameras in live stream mode at all times. I have POE ring cameras and a very high network speed at my house I am confident my network can handle it.

**Comment by DMBlakeley** [comment]
Have you tried using the Eve app? This lets you view all of your cameras in live mode in a single view. I have 4 cameras (Logitech Circle, 2 Eufy 2k, and a Ring doorbell) and all show in live mode in the Eve app. Would be interesting if your 4 Ring cameras would display at the same time.

**Comment by PhxAZ89** [comment]
I have not. I use Apple HomeKit to control all of my devices and scenes at my house. I have Lutron wall switches, automatic blinds, my front gates are controlled by home kit as well with MQ from lift master. I have about 85 devices in all with everything set up from HomeKit. I was hoping to have a way to not have to use another app to view my cameras since I am always using my HomeKit App. By allowing the ring cameras to live stream in home kit I can use an Apple TV to have them live stream through the home kit view on anytv in the house. It would be amazing. I love ring but I hate that they do not offer that feature.

**Comment by DMBlakeley** [comment]
The Eve app is fully compatible with HomeKit and all of your HomeKit devices will show in the app. Encourage you to give it a try.

**Comment by PhxAZ89** [comment]
I will, thank you. I wasn’t aware ring would sink woth Eve. Thank you for your help sir!

**Comment by dgreif** [comment]
Thanks for pointing out the Eve app @DMBlakeley.  @PhxAZ89 the snapshot behavior you see in the Home app is completely controlled by Apple and are not something that can be controlled from the homebridge side.  All the plugin can do is supply a live stream when one is _requested_, and that is completely up to the implementation of the app you use to view HomeKit devices.
