### ISSUE TITLE
Not able to add doorbell camera

### ISSUE THREAD

**Issue by jahnkenneth** [dgreif/ring#58]
Hello,
I´ve installed and configured the plugin.
The logs shows that my doorbell camera has been found.

When i tried adding it to the Home app, it failed after a while... When trying to add it a second time, it doesn't show under the add new accessory dialogue in the Home app.
Have tried restarting Homebridge.
:-(

**Comment by dgreif** [comment]
Sorry to hear you are having issues.  Try following these instructions and let me know how it goes: https://github.com/dgreif/ring/issues/41#issuecomment-505609919

**Comment by jahnkenneth** [comment]
I seems I only have two files in the persist directory, and none of them are pointing to a camera :-(
Also, I only have one "ring" plugin...

**Comment by dgreif** [comment]
Odd..can you confirm that you are on the same network as your homebridge setup?

**Comment by jahnkenneth** [comment]
Yes, I am. :-)

**Comment by jahnkenneth** [comment]
Here is the content of one of the two files...
Is this the camera?

{"displayName":"Homebridge","category":2,"pincode":"031-45-xxx","signSk":"91304284fced3cb268bd189426df9cf3cb7f8ccf6bcaf1ce9d79cacfa81645c5f963a0c1ee2806656089c95d08c4f6b672$

**Comment by dgreif** [comment]
Nope, the "displayName" would be the name you have assigned to your camera in the Ring app.  A more drastic step that you can take is deleting the `persist` and `accessories` directories.  Note, this will mess up any automations or settings you have in HomeKit for any other homebridge accessories.  If you don't have many other plugins, it's not a big deal.  Make sure you stop homebridge before deleting them, and they will get recreated when you start up again.  You will then need to remove you existing homebridge bridge from the Home app and add the new one

**Comment by jahnkenneth** [comment]
I was really hoping not to have to do that... :-( 
I have a few plugins running, and would hate to set it all up again...

**Comment by dgreif** [comment]
@jahnkenneth I totally get where you are coming from.  I don't have any other ideas at this point, but I also can't guarantee it will fix the issue.  Sounds like homebridge got into a funky state with your camera and I haven't had anyone else run into this issue yet.

**Comment by jahnkenneth** [comment]
Tried deleting both the folders, but still i can't get the camera to show... :-(

**Comment by dgreif** [comment]
I believe it uses an additional port to expose the camera.  Maybe you need to open that port for your phone to see it?

**Comment by jahnkenneth** [comment]
Yes, so it seems... 
[0;37m[2019-7-11 19:33:31][0m [0;36m[Config][0m Console v3.9.6 is listening on port 8080.
[0;37m[2019-7-11 19:33:31][0m [0;36m[Config][0m Using Form Authentication
[2019-7-11 19:33:29] Please add [Inngangsdør] manually in Home app. Setup Code: 031-45-676
[2019-7-11 19:33:29] Inngangsdør is running on port 37921.
[2019-7-11 19:33:29] [RingAlarm] Adding new accessory lpd_v2 Inngangsdør
[2019-7-11 19:33:29] [RingAlarm] Configuring 1 cameras and 0 devices for locationId u5r8uf-2898f-0
[2019-7-11 19:33:29] Homebridge is running on port 51826.

Where should i open this port? On my router? The config file?

**Comment by dgreif** [comment]
Looks like you need to open `37921`.  _Where_ you need to open it is entirely dependent on your setup.  For Windows, probably in your firewall settings on the computer.  Beyond that, maybe your router.  I probably won't be able to provide any more help than that as every network is unique

**Comment by jahnkenneth** [comment]
I will check with my ISP tomorrow. :-)

**Comment by jahnkenneth** [comment]
Got it working!
Now you just have to get live streaming to work ;-)

**Comment by dgreif** [comment]
Awesome! Could you share what the problem was?

**Comment by jahnkenneth** [comment]
The problem was the router... My ISP did something, and now it works. :-)
