### ISSUE TITLE
UrlToHttpOptions error: Unable to auth

### ISSUE THREAD

**Issue by PhillOliver-Dev** [dgreif/ring#585]
# Bug Report

### Describe the Bug
 Unable to authenticate with Ring due to urlToHttpOptions function not existing

### To Reproduce
 - Start Homebridge (3.3.3, node v14.16.0 ubuntu 18.04)
 - Only plugin installed is ring
 - Get token using ring-auth-cli

### Screenshots/Logs

```
02/03/2021, 22:53:42 [Ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  urlToHttpOptions is not a function.  Trying again in 5 seconds...
```

**Comment by dgreif** [comment]
See #577.  You just need to re-install the plugin by installing a previous version and then the latest version again.

**Comment by PhillOliver-Dev** [comment]
Have you got an documentation on the way to do this? I have global installed 9.12.8 but the app itself is shows 9.15.3. I have installed natively, not running dockerised.

**Comment by dgreif** [comment]
I just released a new version so you should be able to update and then it should work

**Comment by dgreif** [comment]
@PhillOliver-Dev any luck?
