### ISSUE TITLE
Can we somehow disable this annoying logging?

### ISSUE THREAD

**Issue by marksthomas** [dgreif/ring#587]
Getting loads of these in the logs - not sure what causes it:-

**[homebridge-ring] Snapshot for Front Door failed to refresh after 70 attempts.  This is normal behaviour since this camera is unable to capture snapshots while streaming

[homebridge-ring] Failed to cache snapshot for Front Door (47.751s), The camera currently reports that it is online**

If it's online I don't care about not getting snapshots.

[This is just from one ring ](https://imgur.com/a/9IUFCOF)- overkill?

Also - **'[Front Door] Snapshot request handler provided empty image buffer!'**

This seems to appear when I have Home App open on ipad with camera showing. Not sure this info is useful. 

Are we able to disable this?

HB 13.2, latest version of plugin

**Comment by dgreif** [comment]
9.15.4 should only show one line now if that happens. Thanks for the suggestion!

**Comment by marksthomas** [comment]
Thank you! :)
