### ISSUE TITLE
cannot arm the ring system via Homekit

### ISSUE THREAD

**Issue by Sungamm** [dgreif/ring#589]
# Bug Report

### Describe the Bug
cannot arm the ring system via Homebridge / Homekit

### To Reproduce
 - Start Homebridge
 - Attempt to arm ring (set to away / abwesend)
 - no error in the log - confirmation ([06/03/2021, 14:05:30] [Ring] Setting Köln Mode to away)

### Expected behavior
Ring system must armed. But in the App (ios 15.2.1) its still at home (Zuhause) and not away (abwesend).

### Screenshots/Logs
[Apple Home] (https://bilderupload.org/bild/1a6859804-img-3229)
[ring iOS App] (https://bilderupload.org/bild/7dd059840-img-3228)

### Additional context
arm and disarm did not work anymore. Its works perfect for some time ago but now for serval days not. 

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
` {
            "refreshToken": "xxx",
            "platform": "Ring"
        }``

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment
<!-- ✍️edit: -->
 - OS: Raspberian
 - Node.js: 14.16.0
 - NPM: 7.6.1
 - homebridge-ring: 9.15.4
 - homebridge: 1.3.2

*Update to
iOS 15.2.1
Homebridge 1.4.0
Node 16.14.0
npm 8.5.0
homebridge-ring v9.24.0

**Comment by dgreif** [comment]
Can you clarify whether you are trying to use location modes vs a Ring Alarm system?  The log you posted indicates that it is setting Location Mode (which is specifically for cameras), but the rest of your description sounds more like you have a Ring Alarm.

**Comment by Sungamm** [comment]
Sorry. yes correct. I use a ring indoor camera. 
at home mode is configured as no video, no motion alerts. away there will record videos and alert via motion sensor.
In the past I set the homekit ring buttion to away and camera was armed. when I at home it set to at home. 

If I now change the button in Homekit, nothing happend.

**Comment by dgreif** [comment]
@Sungamm sorry for the delay on this issue. I just set up a test location with location modes and everything seems to be working perfectly.  Are you still experiencing issues with the Modes switch in HomeKit?

**Comment by Sungamm** [comment]
Hi Dusty,

thank you for asking back. Unfortunately the issue ist not solved on my side. In the meantime I updated the ring plugin, node and Homebridge but the switch did not work anymore. 



If I changed the status, nothing happens at ring. 

Anwesend means away. But ring stay at inaktive. Same game if I try to deactivate. Ring status will not change. 

Best regards
Magnus
...von unterwegs gesendet.

**Comment by apexad** [comment]
Do you have any offline devices?  This may be the case.  I think the bypass logic may not handle this situation

**Comment by Sungamm** [comment]
> Hold on, did you say you were on iOS 5.0?? That might be a big part of it...I have a ring alarm and camera, and have had no issues with modes/away, etc.

Good Morning, 
sorry a type from me. I run the actual iOS version on my iDevices incl. the AppleTV (Hub). I corrected it to avoid confusion.  Thank you.

**Comment by Sungamm** [comment]
> Do you have any offline devices? This may be the case. I think the bypass logic may not handle this situation

Good Morning, 
no, there are no off-line devices. I keep my Homebridge up-to-date and get "crazy" is there a device that is not responding. Luckly I have no issues of this.

**Comment by dgreif** [comment]
What happens when you try to arm from the keypad? Does it mention anything needing bypass?

**Comment by Sungamm** [comment]
HiHo,
what do you mean from keypad?

There is no diffent if I use Apple Homekit or Homebridge directly. Only when I change it in the ring app itself its work. 

But it looks that I am alone ;-)

I found a semi-good option for streaming only and did not change the status anymore :-) Maybe not the smart solution but it works. No need to spent additional effort for this single cause issue. 

Thank you for the great plug-in and that you sharing that with us.
