### ISSUE TITLE
Hiding doorbell button and siren switch configuration not working. 

### ISSUE THREAD

**Issue by metroidmen** [dgreif/ring#59]
I set these commands up in the homebridge configuration file and it just doesn’t seem to do anything. I’ve made sure they were put in correctly. They just aren’t taking.

**Comment by dgreif** [comment]
Can you post a copy of the ring section of your config?  Make sure you don't include your real email/password

**Comment by metroidmen** [comment]
http://tinypic.com/r/70xbmv/9

**Comment by dgreif** [comment]
Those look correct.  What version of the plugin do you have installed?

**Comment by metroidmen** [comment]
It’s up to date. It’s been like this for the last few versions. This never seemed to work, unfortunately.

**Comment by dgreif** [comment]
Maybe update homebridge?  I know others have had success with those settings and I have tested them out locally so I am confident that they work.  If nothing else does the trick, you will need to wipe your `.homebridge/accessories` directory, but I try to avoid that as much as possible as it can mess up any automations you have set up

**Comment by johnsonjoshuaa** [comment]
This update worked for me. I was able to hide both the doorbell button and siren switch. I have 1 ring doorbell pro, and 2 ring flood cams. It works for all 3 devices in various configs with version 4.0.2 installed. My end config is to keep the doorbell button visible but to hide the siren switches on my flood cams.

**Comment by metroidmen** [comment]
I can confirm the update fixed this issue! Thanks!!
