### ISSUE TITLE
Not able to speak to doorbell

### ISSUE THREAD

**Issue by d0nY90** [dgreif/ring#590]
Hi there !

thank you for the great plugin an support. 
I have problems with the 2 way communication between my iphone and the doorbell pro. When I open the camera in Home I can hear everything from outside but I’m not able to speak to the doorbell. When I press the button „speak“ nothing comes out of the speaker of the doorbell. 

Hope you can help me with that. 

Thanks !
Daniel

**Comment by dgreif** [comment]
@d0nY90 I was just able to recreate this issue with my Ring Doorbell Pro.  It looks like an issue with cameras using Rings new media servers, which have a slightly different streaming setup. I should be able to get this fixed, but it may be a few weeks before I get a chance to work on it.

**Comment by jimmyfisher** [comment]
Having this same issue with my Ring Doorbell Pro as well as my spotlight cam. Following on the 30 sec thread, but also wanted to weigh in here because seems to all be connected.

Thanks!

**Comment by djm181** [comment]
I believe this is fixed now right? I just tried the return audio example and it appears to work as expected.

**Comment by dgreif** [comment]
I was trying to debug this over the weekend and noticed it seems to be working on all my cameras as well. I think this must be something Ring changed in their end. @d0nY90 Can you try it again and see if yours is working now?

**Comment by jimmyfisher** [comment]
FWIW - just tried on my Spotlight Cam and Ring Pro Doorbell and both are working as expected w the intercom feature! 😄

**Comment by League2EB** [comment]
@dgreif Hello 

I still run into this problem ..... 

Ring Device: Video Doorbell V2
Signal Strength: RSSI-53
Firmware: Up to Date
Homebridge version: V1.3.4
Homebridge Ring version: V9.20.1-beta.0

do you need more info to help me fix it ? very thx all
