### ISSUE TITLE
Can we turn these messages off? What use are they?

### ISSUE THREAD

**Issue by marksthomas** [dgreif/ring#592]
[Front Door] Snapshot request handler provided empty image buffer!
[Front Door] Snapshot request handler provided empty image buffer!

I get it, you were provided an empty image buffer -  but do I need a log full of notifications? Can they be disabled?

HB 1.3.3. - plugin, latest stable build.

**Comment by dgreif** [comment]
They come from homebridge, not from the plugin. I'll chat with them homebridge developers but this was an intention addition so they may not want to remove it.

**Comment by dgreif** [comment]
I talked to the homebridge developers and we were able to find a workaround to get rid of these logs.  Released in v`9.15.5`

**Comment by marksthomas** [comment]
Awesome. Thanks for doing this.
