### ISSUE TITLE
Uninstall Plugin - Not removing cameras, resulting in many errors

### ISSUE THREAD

**Issue by nodecentral** [dgreif/ring#593]
# Bug Report

### Describe the Bug

I was receiving loads of “Snapshot request handler provided  empty image buffer " and the Home App did not always show an image so I decided to uninstall it which, I did - but it continues to show up in the logs and this time with loads of red errors, such as fetching  errors or no such file errors. 

### To Reproduce

All I can put here is do an uninstall 

### Expected behavior

I expected it would completely remove the plugin and all it features, leaving no further trace in the logs

### Screenshots/Logs

I have a screenshot, but can’t seem to see how to post it here?

### Homebridge Ring Config

It’s no longer installed.

### Environment
 - OS: QNAP NAS
 - Node.js:  v14.15.3
 - NPM: v6.14.9
 - homebridge-ring: v9.15.4
 - homebridge: v1.3.3

**Comment by dgreif** [comment]
Can you include the actual logs?  Without seeing the errors, it's hard to judge where they are coming from.

A couple things to try on your end:
* Make sure the plugin config has been removed from your config.json
* Do a full restart of the server

Let me know if you still have issues after that

**Comment by dgreif** [comment]
Your original issue with `Snapshot request handler provided empty image buffer` has been fixed in `9.15.5`, so you are welcome to re-install the plugin.  Feel free to reopen this issue if you continue to have other issues.

**Comment by nodecentral** [comment]
> * Make sure the plugin config has been removed from your config.json
> * Do a full restart of the server

Thanks, I’ll keep an eye on it, I’ve been doing a number of changes recently so there has been a lot of reloads, I’ll do a full restart and see .
