### ISSUE TITLE
re upgrading ring plugin 

### ISSUE THREAD

**Issue by oliverchapple** [dgreif/ring#595]
hi 

is there a command the ring plugin 

because when I chick update it won't update that way 

thanks Oliver

**Comment by dgreif** [comment]
Sorry, I'm missing a lot of details based on you initial question. Are you on HOOBS or homebridge-config-ui-x? What happens when you try to update? Are there any logs?

**Comment by oliverchapple** [comment]
I’m on hoobs but there’s no log on the error when i update 

all it does when I chick update is update but then the update is still there after restart.  

thanks oliver

**Comment by dgreif** [comment]
This is a HOOBS issue then and you are best off reaching out to HOOBS support.  They are really good at helping with issues like this one

**Comment by snarknesor** [comment]
did you get to resolve this with HOOBS? i'm having the same issue

**Comment by oliverchapple** [comment]
still go the issue.
