### ISSUE TITLE
“Setup Endpoints” error when trying to view camera/s in HomeKit 

### ISSUE THREAD

**Issue by LS73** [dgreif/ring#597]
[Ring] Waiting for stream data from Backyard Ring (1.217s)
2021-03-22, 11:25:44 PM [HOOBS 0543@Setup Endpoints] The write handler for the characteristic 'Setup Endpoints' on the accessory 'Backyard Ring' was slow to respond!
2021-03-22, 11:25:50 PM [HOOBS 0543@Setup Endpoints] The write handler for the characteristic 'Setup Endpoints' on the accessory 'Backyard Ring' didn't respond at all!. Please check that you properly call the callback!

If so, any recommendations on how to correct this issue?

Thanks,
Leo

# Live Streaming Issue

### Describe the live streaming issue
 A clear and concise description of the problem.  If all you can say is that "live streaming doesn't work on my network", then please do not open an issue.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Recommended solution
 Please describe what you think is causing this issue, and how you recommend it be fixed

### Environment

 - Ring Camera: Doorbell Pro, Spotlight Cam Wired and Stickup Cam
 - OS: Raspian / Hoobs
 - Node.js: V14.16.0
 - NPM: 7.6.3
 - homebridge-ring (if applicable): 9.15.5
 - homebridge (if applicable): N/A
 - hoobs (if applicable): 3.3.5

### Network Environment
 Please provide a detailed description of your network setup, including all network hardware between your camera, the internet, your homebridge server, and your HomeKit home hub (Apple TV, HomePod, iPad).  Please include brand and model for each device that the network traffic passes through.

**Comment by dgreif** [comment]
The `Setup Endpoints` handler is currently as fast as I can make it, unfortunately.  Within that handler, I have to call out to Rings servers, which start a stream on your camera, and then I have to wait for the stream to hit there servers and then homebridge before I can return.  Not really anything I can do to avoid it at this point, just a side-effect of how Rings streaming works.
