### ISSUE TITLE
Camera not responding

### ISSUE THREAD

**Issue by winzelerm** [dgreif/ring#598]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...
After updating the HOOBS Ring plug in all camera views have stopped.  All I get is "camera not responding"
I'm running HOOBS 3.3.5 and Ring plug in 9.15.5 (the one that was released on 3/18/21).  
Prior to upgrading the plug in I could use my Home app on my iPhone and the cameras would work, ie, I could see the camera view of my front porch.  After the plug in update all I get is "camera not responding."

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by joshstubble** [comment]
I was experiencing this same problem last few days. HomeKit would pull 'snapshots' of the cameras but would not play the actual live video. 

I moved ring to a child bridge and updated homebridge but it didn't seem to fix it. 

All of a sudden this morning I woke up and it was working again. Maybe a ring api problem? 

It's back to working perfectly right now. Will update if it stops.

**Comment by dgreif** [comment]
@joshstubble makes a good point about iPhone iOS beta, that could definitely be the source of the issue.  @winzelerm you didn't include any version info in your original issue, but iOS version would definitely be helpful in figuring out what might be your issue.

**Comment by joshstubble** [comment]
After further troubleshooting, the camera seem to be working through HomeKit on every iOS device not on beta (girlfriend, roommate and iPad), but random errors on devices on beta (my phone, and two backup iPads). My phone is again throwing an error message when going to live view, but the sensors are still working and pushing notifications. 

Ive deleted iOS beta profiles on those devices so just gotta wait until a stable release is pushed to get off beta (don't feel like backing up and restoring). 

Will keep you posted.

**Comment by stubbz00** [comment]
I am having this issue as well, but I am on iOS 14.4.1.  I have on the latest homebridge-ring running on a child bridge.  Restarting the child fixes the issue, but it seems to occur randomly and don't notice there is an issue until I try to pull up the camera.

**Comment by joshstubble** [comment]
Ah that’s interesting it does work again when child bridge is restarted

**Comment by winzelerm** [comment]
It did not matter what device I was using (iPhone, iPad).  Neither would show the live camera view.  I was running IOS 14.4.1 on both.  
I tried uninstalling and re-installing the Ring plug in with no luck.  I even re-flashed my SD card in the HOOBS box which took me back to version 3.3.1 then upgraded to the latest HOOBS OS and then installed the Ring plug in.  Nothing worked.  
My solution:  After doing all the above, I deleted HOOBS from my Apple Home app, waited a minute and then added it back.  It worked!  The cameras have been responding (showing views) ever since.

**Comment by joshstubble** [comment]
Ok I moved everything back down to stable iOS and was still getting the problem. I removed ring from homebridge and reinstalled and it's been working ever since. 

Only difference for me is it was working on every device but my regular iPhone. But as of now it's working on iOS 14.4.x

**Comment by joshstubble** [comment]
It’s been working perfectly since the homebridge-ring reinstall.

**Comment by winzelerm** [comment]
I don't know if it was the HomeKit side or not.  Remember that my issues didn't start until I upgraded HOOBS Ring plug in.

**Comment by dgreif** [comment]
Well if all is working now, I think it's safe to close this.  Thanks for your patience!
