### ISSUE TITLE
Home notification “Someone rang the doorbell” but no one rang.

### ISSUE THREAD

**Issue by tooh** [dgreif/ring#599]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

Home notification “Someone rang the doorbell” but no one rang.

At the same time I get a Ring notification “There is motion at your frontdoor”.

This notification is correct.

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: Raspbian
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: N/A

**Comment by dgreif** [comment]
I'm guessing you have `"sendDoorbellMotionNotificationsToTv": true` in your config.  If so, this is working as intended.  The only way to get motion events to initiate a live stream on the Apple TV is to _fake_ a doorbell press when motion is detected.  This has the side effect of sending a doorbell press notification to all your other HomeKit devices that have notifications enabled

**Comment by tooh** [comment]
Ok,

Thank you for response.
Indeed this option was switched to true.

Item can be closed.
