### ISSUE TITLE
Cannot update or uninstall plugin

### ISSUE THREAD

**Issue by snarknesor** [dgreif/ring#603]
Ever since updating HOOBS to version 3.3.5 my ring cameras are nowhere to be found in my Home app I can't update my Ring plugin (still on V9.14.2) or uninstall it. Whenever run it through the update process it tells me that it updated successfully but then it is still on V9.14.2 and still tells me that there is an update available. not sure what to do at this point

**Comment by dgreif** [comment]
Sorry to hear HOOBS updates are still an issue. As I pointed out in #595, this is a HOOBS specific issue and isn't a problem with the plugin. You should reach out to HOOBS support for help. Hopefully they can help you get it straightened out.
