### ISSUE TITLE
NGHTTP2_ENHANCE_YOUR_CALM-Error

### ISSUE THREAD

**Issue by CxRustySides** [dgreif/ring#606]
4/9/2021, 3:41:37 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details

# Bug Report

### Describe the Bug
After upgrading to version 9.15.6 I am getting a repeating error stating:
4/9/2021, 3:41:37 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
Cameras show initially but after several errors in a row, the cameras stop working.
Then the error changes to This is a known issue with your current NodeJS version (v12.16.3).  Trying again in 5 seconds...

### To Reproduce
 - Start Homebridge
 - Install and configure homebridge-ring plugin putting in proper token for authentication
 - Error starts immediately

### Expected behavior
No errors and video streams stable

### Screenshots/Logs
4/9/2021, 3:55:34 PM Plugin "homebridge-ring" installed.
4/9/2021, 3:55:34 PM Got SIGINT, shutting down Bridge...
4/9/2021, 3:55:40 PM Initializing HAP-NodeJS v0.9.3...
4/9/2021, 3:55:43 PM Loaded plugin 'homebridge-ring'
4/9/2021, 3:55:43 PM [4/9/2021, 2:55:43 PM] Registering platform 'homebridge-ring.Ring'
4/9/2021, 3:55:43 PM Loading 1 platforms...
4/9/2021, 3:55:43 PM [Ring] Initializing Ring platform...
4/9/2021, 3:55:43 PM [Ring] Configuring cached accessory 6e5f1f4f-b309-4b0b-a659-900ceeab6714 Front Door
4/9/2021, 3:55:43 PM [Ring] Configuring cached accessory 95a6e6bf-35b9-43b0-8d31-78c001940f38 Driveway
4/9/2021, 3:55:43 PM Preparing Advertiser for 'HOOBS 35DC' using bonjour-hap backend!
4/9/2021, 3:55:43 PM [Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed:
4/9/2021, 3:55:43 PM [Ring] Error connecting to API
4/9/2021, 3:55:43 PM Starting to advertise 'HOOBS 35DC' using bonjour-hap backend!
4/9/2021, 3:55:43 PM Bridge is running on port 51826.
4/9/2021, 3:55:45 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:55:45 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:55:45 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:55:45 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:55:45 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:55:45 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:55:45 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:55:45 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:55:45 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:55:45 PM [HOOBS 35DC@Driveway@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:55:45 PM [HOOBS 35DC@Driveway@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:55:45 PM [HOOBS 35DC@Driveway@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:55:45 PM [HOOBS 35DC@Driveway@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:55:45 PM [HOOBS 35DC@Driveway@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:55:45 PM [HOOBS 35DC@Driveway@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:55:45 PM [HOOBS 35DC@Driveway@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:55:45 PM [HOOBS 35DC@Driveway@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:55:57 PM Got SIGINT, shutting down Bridge...
4/9/2021, 3:56:04 PM Initializing HAP-NodeJS v0.9.3...
4/9/2021, 3:56:06 PM Loaded plugin 'homebridge-ring'
4/9/2021, 3:56:06 PM [4/9/2021, 2:56:06 PM] Registering platform 'homebridge-ring.Ring'
4/9/2021, 3:56:06 PM Loading 1 platforms...
4/9/2021, 3:56:06 PM [Ring] Initializing Ring platform...
4/9/2021, 3:56:06 PM [Ring] Configuring cached accessory xxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxxxxx Front Door
4/9/2021, 3:56:06 PM [Ring] Configuring cached accessory xxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxxxxx Driveway
4/9/2021, 3:56:07 PM Preparing Advertiser for 'HOOBS 35DC' using bonjour-hap backend!
4/9/2021, 3:56:07 PM Starting to advertise 'HOOBS 35DC' using bonjour-hap backend!
4/9/2021, 3:56:07 PM Bridge is running on port xxxxx.
4/9/2021, 3:56:08 PM [Ring] Found the following locations:
4/9/2021, 3:56:08 PM [Ring]   locationId: xxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxxxxx - xxxxxxxxx
4/9/2021, 3:56:09 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:56:09 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:56:09 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:56:09 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:56:09 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:56:09 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:56:09 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:56:09 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:56:09 PM [HOOBS 35DC@Front Door@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:56:09 PM [HOOBS 35DC@Driveway@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:56:09 PM [HOOBS 35DC@Driveway@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:56:09 PM [HOOBS 35DC@Driveway@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:56:09 PM [HOOBS 35DC@Driveway@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:56:09 PM [HOOBS 35DC@Driveway@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:56:09 PM [HOOBS 35DC@Driveway@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:56:09 PM [HOOBS 35DC@Driveway@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:56:09 PM [HOOBS 35DC@Driveway@@Selected RTP Stream Configuration] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/9/2021, 3:56:09 PM [Ring] Configuring 2 cameras and 2 devices for location "xxxxxxxxxxx" - locationId: xxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxxxxx
4/9/2021, 3:57:38 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/image/27797590.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:57:38 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
4/9/2021, 3:57:39 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:57:39 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
4/9/2021, 3:57:43 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/image/27797590.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:57:43 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
4/9/2021, 3:57:44 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:57:44 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
4/9/2021, 3:57:48 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/image/27797590.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:57:48 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
4/9/2021, 3:57:50 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:57:50 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
4/9/2021, 3:57:50 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:57:50 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
4/9/2021, 3:57:53 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/image/27797590.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:57:53 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
4/9/2021, 3:57:55 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:57:55 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
4/9/2021, 3:57:55 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:57:55 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
4/9/2021, 3:57:57 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:57:57 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
4/9/2021, 3:57:58 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/image/27797590.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:57:58 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
4/9/2021, 3:58:00 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:58:00 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
4/9/2021, 3:58:00 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:58:00 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
4/9/2021, 3:58:02 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:58:02 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
4/9/2021, 3:58:03 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/image/27797590.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:58:03 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
4/9/2021, 3:58:05 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:58:05 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
4/9/2021, 3:58:05 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
4/9/2021, 3:58:05 PM [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details

### Homebridge Ring Config
Default config with RefreshToken only configured

### Environment
 - OS: Raspian
 - Node.js: v12.16.3
 - NPM: 6.14.4
 - homebridge-ring: 9.15.6
 - homebridge: N/A
 - hoobs: 3.3.5

**Comment by dgreif** [comment]
The error links to a wiki page, which explains that you need to update to a newer version of node 12 or node 14. Is there a reason you are unable to perform that update?

**Comment by CxRustySides** [comment]
> The error links to a wiki page, which explains that you need to update to a newer version of node 12 or node 14. Is there a reason you are unable to perform that update?

Thank you!  After performing the update from the wiki, my problem is solved.  Closing the issue.  Great Wiki by the way!  I didn't see it before you mentioned it.
