### ISSUE TITLE
Snapshot not showing on Home.app on Mac OS

### ISSUE THREAD

**Issue by tomsteenbakkers** [dgreif/ring#607]
# Bug Report

### Describe the Bug
I have a Rind Doorbell and it's working on all iOS devices including my Apple Watch. But on the Mac it will stream the video but the snapshot function is not working. When ik stop the live streaming the snapshot shows 

### Expected behavior
I would expect a request in the Homebridge log when I leave the Home.app open in the Mac. When I do this on i.e. my iPad, then I see a a few second a new snapshot. 

### Screenshots/Logs
<img width="449" alt="Screenshot 2021-04-10 at 13 44 13" src="https://user-images.githubusercontent.com/24613800/114268771-35048480-9a03-11eb-9c4a-e03686956ce8.png">

### Homebridge Ring Config
```
{
            "refreshToken": "secret",
            "hideDoorbellSwitch": true,
            "hideCameraMotionSensor": false,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "platform": "Ring",
            "_bridge": {
                "username": "XX:XX:XX:XX:XX:XX",
                "name": "Ring",
                "port": 51488
            }
        },


### Environment
 - OS: Raspbian
 - Node.js: v14.16.0
 - NPM: v6.14.11
 - homebridge-ring: 9.16.0
 - homebridge: 1.3.4

**Comment by dgreif** [comment]
This sounds like an issue with the Home app on macOS.  Are you running a beta version of macOS?  If not, try quitting the Home app and trying again, or rebooting your laptop.  Unfortunately I don't have any control at this level.  If the Home app doesn't request a snapshot, there is nothing the plugin can do.

**Comment by CxRustySides** [comment]
@tomsteenbakkers I am not sure if this is helpful for you or not, but I am working with MacOS homekit streaming and snapshop perfectly.  Here is my environment.

OS: Raspbian
MacOS: 11.2.3
Node.js: v14.16.0
NPM: v6.14.11
HOOBS: 3.3.5
homebridge-ring: 9.15.6
