### ISSUE TITLE
Cannot use doorbell button for automations

### ISSUE THREAD

**Issue by gondalez** [dgreif/ring#611]
# Bug Report

First of all thank you for the excellent plugin. I have got a lot of use out of it and appreciate the effort that goes into making it so rock solid 🙏 

### Describe the Bug
I can not use my ring2 battery doorbell button as automation trigger.
Previously I was able to set this up so that pressing the doorbell triggered a doorbell switch on my other hard wired camera.
This allowed pressing the doorbell to show a nice video preview from the hardwired camera, which doesn't work for battery ring cameras when in low power mode.
Hardware: battery ring doorbell 2.

### To Reproduce
 - configure ring doorbell 2 
 - see camera shows in home app
 - press edit
 - see "unconfigured button" message  (see screenshot)
 - create automation in home app
 - see button for doorbell
 - attempt to use button as automation trigger
 - see "programmable switches must be set up" message (see screenshot)
 - unable to complete automation
Note I have tried removing and re-adding the bridge in the home app. I have also tried scanning for a new accessory in the hopes the button would show but to no avail.

### Expected behavior
Previously I was able to see the doorbell as a button in the room in the home app.
And I was able to use it as an automation trigger.

### Screenshots/Logs
![image](https://user-images.githubusercontent.com/1468141/114651579-d434bf00-9d16-11eb-86a5-5e2f40d6e0dd.png)
![image](https://user-images.githubusercontent.com/1468141/114651586-d860dc80-9d16-11eb-8778-c49aed33f674.png)
![image](https://user-images.githubusercontent.com/1468141/114651592-db5bcd00-9d16-11eb-861a-dc0abbc7f7dc.png)

### Additional context
💁  I recently moved the plugin to an isolated bridge and back again (ringing on homepod did not work when it was in isolated mode).
This may be a red herring but I figure best to mention.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
{
    "refreshToken": "...",
    "hideDoorbellSwitch": false,
    "hideCameraMotionSensor": true,
    "hideCameraSirenSwitch": true,
    "hideInHomeDoorbellSwitch": true,
    "hideAlarmSirenSwitch": true,
    "hideUnsupportedServices": true,
    "platform": "Ring"
}
```

### Environment
![image](https://user-images.githubusercontent.com/1468141/114651888-650b9a80-9d17-11eb-87c5-0d0d48599b47.png)
![image](https://user-images.githubusercontent.com/1468141/114651909-6f2d9900-9d17-11eb-89a9-79f7dabf6efa.png)

**Comment by dgreif** [comment]
It looks like you are simply trying to set it up from the wrong spot.  If you go into the actual camera view (live stream), then click Settings -> Accessories -> (click on the programmable switch) -> Single Press (Add).  I think the Home app forces you to set it up from this page because there can be multiple actions (single, double, long press).  Let me know if that path works for you!

**Comment by gondalez** [comment]
Thanks for the reply @dgreif.
I thought that too but I have been all over the home app trying to find the accessory :) 

There is no accessories option on the settings screen for the camera (A).  
On the associated bridge there is an accessories option but opening it shows a blank screen (B).

(Apologies for the artefacts, I did a scrolling screen capture.)

## A
![image](https://user-images.githubusercontent.com/1468141/114809819-77500c00-9ddd-11eb-976c-6fd525ba3bf2.png)

## B
![image](https://user-images.githubusercontent.com/1468141/114809925-a23a6000-9ddd-11eb-81be-ea3531342f9a.png)
![image](https://user-images.githubusercontent.com/1468141/114809982-be3e0180-9ddd-11eb-9f38-e24efd40c508.png)

**Comment by dgreif** [comment]
Can you post your config for the ring plugin (without the refresh token)

**Comment by gondalez** [comment]
Oh yep they are at the bottom of the original PR comment above ☝️ 
\+ I added screenshots of the homebridge env if that helps.

**Comment by dgreif** [comment]
Ahh, thanks! I missed the part about you switching to a child bridge and back. That may the cause, but not sure. At this point, you are probably best to remove the Ring plugin, restart and make sure the camera disappears from HomeKit, then add it back again. Let me know if that helps

**Comment by gondalez** [comment]
Awesome thank you @dgreif, removing the plugin and reinstalling worked.

Bonus is I was able to get it to work in isolated bridge mode too 😌 
(Previously when it was in isolated mode the homepod doorbell ring feature did not work)

thanks again 🙏
