### ISSUE TITLE
"Return Audio" example no longer working

### ISSUE THREAD

**Issue by bachdinhnhan** [dgreif/ring#614]
# Bug Report

### Describe the Bug
"Return Audio" example no longer send out the sample audio to cameras. However, it DOES record video from cameras. 

Please see my log which is attached below

### To Reproduce
 - Clone source code
 - npm install 
 - npm run build && node ./lib/examples/return-audio-example.js

### Expected behavior
Camera SHOULD play the audio that is send out by the script

### Screenshots/Logs

[dump.log](https://github.com/dgreif/ring/files/6328771/dump.log)

### Environment

 - OS: Mac OSX 11.1
 - Node.js: 14.6.0
 - NPM: 6.14.7
 - ring-client-api: 9.16.0

**Comment by bachdinhnhan** [comment]
@dgreif  I tried to test the example on Docker and it seems still not working.

```
FROM node:lts-alpine

ADD . /ring

WORKDIR ring

RUN ["npm", "install"]

RUN ["npm", "run", "build"]

CMD ["node", "./lib/examples/return-audio-example.js"]
```

**Comment by dgreif** [comment]
@bachdinhnhan this is an issue on any camera using Ring's newer media servers.  I'm guessing it's an encoding issue, likely that the new servers expect opus instead of PCMU, but I need to spend some time experimenting with it.  It's on my todo list, just haven't had time to look into it yet.

**Comment by bachdinhnhan** [comment]
> @bachdinhnhan this is an issue on any camera using Ring's newer media servers. I'm guessing it's an encoding issue, likely that the new servers expect opus instead of PCMU, but I need to spend some time experimenting with it. It's on my todo list, just haven't had time to look into it yet.

If you can tell me some hints, I definitely can figure it out. (My test phone is broken so that I can't reverse engineer it right now.)

**Comment by dgreif** [comment]
This still isn't fixed, but it's technically the same problem as #590.  I'm going to close this issue and you can track progress there instead.
