### ISSUE TITLE
Add support to Ring Outdoor Siren

### ISSUE THREAD

**Issue by Rubenfer** [dgreif/ring#615]
# Feature Request

### Description
Could be nice if it's possible to integrate the newly released Ring Alarm Outdoor Siren.

### Device data

{"acStatus":"error","adapterType":"zwave","batteryLevel":100,"batteryStatus":"full","categoryId":34,"commStatus":"ok","commandTypes":{"communication-poll":{"requiresTrust":false},"reconfigure.start":{"requiresTrust":false},"siren-backlight.disable":{"requiresTrust":false},"siren-backlight.enable":{"requiresTrust":false},"siren-test.start":{"requiresTrust":false},"siren-test.stop":{"requiresTrust":false},"siren.start":{"requiresTrust":false},"update-node-neighbors.start":{"requiresTrust":false}},"deviceFoundTime":100000000001,"deviceType":"siren.outdoor-strobe","firmwareUpdate":{"eligibility":"eligible","state":"up-to-date"},"impulseTypes":{"comm.ping.received":{"trusted":false},"tampered":{"trusted":false},"tampered-cleared":{"trusted":false}},"lastCommTime":1618666899786,"lastUpdate":1618666899886,"linkQuality":"ok","managerId":"zwave","manufacturerName":"Ring","name":"Outdoor Siren","pollInterval":43200,"roomId":8,"setupByPluginStatus":"complete","setupByUserStatus":"complete","subCategoryId":0,"tags":["kitted","scanned"],"tamperStatus":"ok","zid":"xx0xx000-0xx0-uuid","auxBattery":{"level":0,"status":"none"},"backlightState":"disabled","brightness":1,"maxSirenDuration":3,"maxVolume":4,"sirenStatus":"inactive","volume":4}

**Comment by dgreif** [comment]
Thanks @Rubenfer! What functionality would you like to see exposed via HomeKit? Just volume, or are there other functions of the siren that can be controlled from the Ring app?

**Comment by Rubenfer** [comment]
I think could be interesting to see the battery level and if it's possible a switch (with a setting to hidde it) to turn on the siren (currently this feature is supported by ring app, but I don't know if it's possible to expose it to HomeKit.

Related to battery, at the moment I take the data it was only powered by D batteries so I assume that "acStatus" means if it is plugged in, "batteryLevel" and "batteryStatus" references D batteries and "auxBattery" key references the removable battery. The data should be exposed via HomeKit is the "auxBattery" and if the level is 0 should be "batteryLevel".

Thanks!

**Comment by CJTalbot87** [comment]
I like this idea, any chance of controlling the Siren, Logo and Strobe from Homebridge?

**Comment by dgreif** [comment]
I haven't had time to add this myself. Happy to take a PR for it if anyone has one and wants to get it working
