### ISSUE TITLE
Displaying Exit Delays

### ISSUE THREAD

**Issue by ayanm00** [dgreif/ring#617]
# Feature Request

### Description
I just got a Ring Alarm, and I noticed that the security system immediately shows an armed state when arming through HomeKit even though there is an exit delay.

### Describe the solution you'd like
I used my previous Xfinity Home system through HomeBridge, and that plugin showed "Arming..." in the Home app until the exit delay ended. This enabled some helpful automations based around the target and current states of the security system.

### Describe alternatives you've considered
It's not at all a dealbreaker for me, so I really haven't thought of an alternative.

### Device data
N/A

**Comment by tsightler** [comment]
Took another really quick look at this and I see that there is actually a property `transitionDelayEndTimestamp` which is the time when the actual mode take effect, even though the mode value immediately reflects the target mode, thus it's at least technically possible to implement this.

**Comment by dgreif** [comment]
Thanks for pointing out that property @tsightler.  I don't this feature is worth the effort at this time.

**Comment by tsightler** [comment]
Understood.  I actually did implement this in ring-mqtt since the Home Assistant alarm control panel component supported a status for this and I had multiple requests from users that were coming from other alarm integrations that did supported arming status.
