### ISSUE TITLE
Hoobs 4.0.48 - Ring Bridge Corrupt with Error Msg

### ISSUE THREAD

**Issue by Biggsylad** [dgreif/ring#623]
# Bug Report

### Describe the Bug
Having rolled in the latest Hoobs Beta update, the Ring Bridge would not start. Cleared cache on all hubs but still could not start. Removed Bridge and reinstalled same issue. Reflashed to the latest version supplied by Hoobs and bridge restarted and then error message came back up after 20 mins or so

### To Reproduce
Start Hoobs
Bridge attempts startup
Errors in Logs 
Bridge stops

### Expected behavior
The bridge to start!

### Screenshots/Logs
21/04/2021, 21:55:28
Ring Bridge
ERROR
Error: write EPIPE at afterWriteDispatched (internal/stream_base_commons.js:156:25) at writeGeneric (internal/stream_base_commons.js:147:3) at Socket._writeGeneric (net.js:785:11) at Socket._write (net.js:797:8) at writeOrBuffer (internal/streams/writable.js:358:12) at Socket.Writable.write (internal/streams/writable.js:303:10) at /usr/lib/hoobsd/node_modules/@hoobs/ipc/src/client.ts:58:24 at Socket.<anonymous> (/usr/lib/hoobsd/node_modules/@hoobs/ipc/src/client.ts:70:36) at Socket.emit (events.js:315:20) at Socket.EventEmitter.emit (domain.js:467:12) at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1132:10)
21/04/2021, 21:55:28
Ring Bridge
ERROR
Error: write EPIPE at afterWriteDispatched (internal/stream_base_commons.js:156:25) at writeGeneric (internal/stream_base_commons.js:147:3) at Socket._writeGeneric (net.js:785:11) at Socket._write (net.js:797:8) at writeOrBuffer (internal/streams/writable.js:358:12) at Socket.Writable.write (internal/streams/writable.js:303:10) at /usr/lib/hoobsd/node_modules/@hoobs/ipc/src/client.ts:58:24 at Socket.<anonymous> (/usr/lib/hoobsd/node_modules/@hoobs/ipc/src/client.ts:70:36) at Socket.emit (events.js:315:20) at Socket.EventEmitter.emit (domain.js:467:12) at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1132:10)
21/04/2021, 21:55:59
Ring Bridge starting

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
{
    "accessories": [],
    "platforms": [
        {
            "platform": "Ring",
            "refreshToken": ********** Deleted **************
            "hideLightGroups": false,
            "hideCameraMotionSensor": false,
            "hideCameraSirenSwitch": false,
            "hideUnsupportedServices": false,
            "hideInHomeDoorbellSwitch": false,
            "hideDoorbellSwitch": false
        }
    ]
}
```



```

### Environment

 - OS: Buster
 - Node.js: 14.16.1
 - NPM: 6.14.12
 - homebridge-ring : 9.17.0
 - homebridge: N/A
 - hoobs: 4.0.48 (Beta)

**Comment by dgreif** [comment]
All of the errors/stack traces in your logs seem to point to HOOBS being the actual issue.  I don't see anything in there specific to this plugin.  I suggest you reach out to their support as they are very good at helping with these types of issues.  Best of luck!
