### ISSUE TITLE
Switch Simulation

### ISSUE THREAD

**Issue by MoTechnicalities** [dgreif/ring#624]
# Feature Request

### Description
I got the new Outdoor Smart Plug but it only displays as a light.

### Describe the solution you'd like
I want to display it as a switch or as a fan.

**Comment by dgreif** [comment]
The challenge is that Ring reports the plugins as a `switch.beams`, which simply indicates that it is a switch in their "Beams" aka Smart Lighting lineup.  I'm not sure there is a lot of value in making this configurable.  Do you have a specific reason you would like to change the type, other than to make it look right in the Home app?

**Comment by MoTechnicalities** [comment]
I'm not sure why you would think there is little value in making the appearance configurable. The hole point of HomeBridge is to give us the flexibility ￼to make things work with HomeKit. HomeKit is by nature intended to be a visually appealing interface. Why should we be content and constrained then to show a switch as a 💡? Why not as anything I wish to run on that switch?

It is the "ability" and "flexibility" that makes the thing valuable. It is the essence of HomeBridge.

**Comment by dgreif** [comment]
The problem is that configuring individual _accessories_ with a _platform_ plugin is a challenging.  If you have ideas on how that should be done, you are welcome to open a Pull Request and I'll take a look

**Comment by MoTechnicalities** [comment]
I can recommend that you at least look into how the HomeBridge EWeLINK plugin does this as an example. The EWeLINK plugin is HOT!It allows Accessory Simulations. With it, I am even able to combine devices so that they perform the function of a HomeKit garage accessory. With it, a switch can easily be identified within the plugin as other types for HomeKit. I'm not a programmer, but having the ability do these types of configurations is what makes the plugin super valuable to me. Having the ability to use the Ring products within HomeKit is cool! But trust me, you can make it HOT!

**Comment by MoTechnicalities** [comment]
I wanted to get back with you regarding a use case reason for allowing us to correctly configure the HomeKit simulation of the switch devices. I am currently connecting ventilation fans to my new outdoor switch, but with having HomeKit stuck on simulating the Ring Outdoor Switch as a 💡, instead of a fan, I am unable to simply tell Siri to turn off the lights in the Lab, as this will unintentionally cut off the fans as well. Such things don't happen in other rooms where I have fans connected to other brand smart plugs that are set to simulate fans in HomeKit.
