### ISSUE TITLE
Unhandled Promised Rejection Error and Output File is Empty message

### ISSUE THREAD

**Issue by 400HPMustang** [dgreif/ring#626]
# Live Streaming Issue

### Describe the live streaming issue
 Ring pro doorbell (OG not the new one) shows no response in HomeKit. The camera loads just fine in the Ring app. Getting an unhandled promise rejection error. Logs are attached for my back door but this also happens with the front.  Also have logs that indicate an empty output file. Note in the logs wherever it says connection stopped gracefully there was never a stream going at least from what I could tell on my iPhone. I would just get the spinner and then eventually the no response message. I can however go right to the Ring app and pull up a stream right away. 

### Screenshots/Logs
 I

https://pastebin.com/zgrSe9zz

https://pastebin.com/HFtHVu21

https://imgur.com/a/uxgEJd1

### Recommended solution
 I guess the first thing is to fix the unhandled promise rejection error

### Environment

 - Ring Camera: [Ring Pro]
 - OS: [Ubuntu Bionic Beaver (18.04.5 LTS)]
 - Node.js: [14.16.1] 
 - NPM: [6.14.12] 
 - homebridge-ring (if applicable): [9.17.0]
 - homebridge (if applicable): [1.3.4]
 - hoobs (if applicable): [N/A]

### Network Environment
 Please provide a detailed description of your network setup, including all network hardware between your camera, the internet, your homebridge server, and your HomeKit home hub (Apple TV, HomePod, iPad).  Please include brand and model for each device that the network traffic passes through.

Network: Cisco AIR-AP2802I-B-K9  access points (3) > Cisco Catalyst 2960 X switch > Ubiquiti USG > Comcast Gig speed internet
Home Hubs: Apple TV 4k, Home Pod (4), Home Pod Mini (3)

**Comment by dgreif** [comment]
Could you please try again with `9.20.0`?  You should no longer receive the `UnhandledPromiseRejectionWarning: Error [ERR_SOCKET_DGRAM_NOT_RUNNING]` error.  I can't guarantee the stream will actually work though.  Please post new logs if you are still having issues
