### ISSUE TITLE
Streaming video only - ffmpeg was not found. See https://github.com/dgreif/ring/wiki/FFmpeg for details.

### ISSUE THREAD

**Issue by dogntbone** [dgreif/ring#632]
Dear All,

Not sure how to get this to work, I am running this in a docker container that is running off OMV on a Raspberry Pi 4.

I am using the oznu/homebridge image.
![Capture](https://user-images.githubusercontent.com/77230990/116998752-42b2de80-ad11-11eb-98dd-f1721ab3a916.PNG)

**Comment by smockle** [comment]
> I am using the oznu/homebridge image.
Hmm, that image should include `ffmpeg`: https://github.com/oznu/docker-homebridge#1-need-ffmpeg 🤔

**Comment by dogntbone** [comment]
> From @dogntbone in [#632 (comment)](https://github.com/dgreif/ring/issues/632#issue-875379981):
> 
> > I am using the oznu/homebridge image.
> 
> Hmm, that image should include `ffmpeg`: https://github.com/oznu/docker-homebridge#1-need-ffmpeg 🤔
> 
> @dogntbone, are you using the Alpine or Ubuntu-based image?

Ubuntu. Did I use the wrong one?

**Comment by dogntbone** [comment]
`root@raspberrypi:/homebridge# which ffmpeg
/usr/local/bin/ffmpeg
root@raspberrypi:/homebridge# ffmpeg -codecs | grep libfdk_aac
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
 DEAIL. aac                  AAC (Advanced Audio Coding) (decoders: aac aac_fixed libfdk_aac ) (encoders: aac libfdk_aac )
root@raspberrypi:/homebridge# `

Please refer to the above for the output: I am a newbie at this, does this mean all's good now?

**Comment by TallWilber** [comment]
I'm seeing the same issue. Running Homebridge on a RPi, ffmpeg looks like it is installed and working, but no snapshots in the notifications.

**Comment by dgreif** [comment]
Do you see this issue if you revert down a few versions?  Maybe try `9.15.5`

**Comment by dogntbone** [comment]
> Do you see this issue if you revert down a few versions? Maybe try `9.15.5`

sorry I have only just saw this; had a job change so I was busy. Did you mean oznu/docker-homebridge 9.15.5?

**Comment by saschapohle-blueforte** [comment]
Just experienced the same issue with ffmpeg.
Seems like Ring (and in my case Unifi Protect) expects ffmpeg to be somewhere like /usr/bin/ffmpeg (if I remember right)
Your installation of ffmpeg is in /usr/local/bin/ffmpeg.
Adding 
"ffmpegPath": "/usr/local/bin/ffmpeg"
to the homebridge config for ring (and in unifi settings) solves the issue for me.
Now I am stuck with 30 sec streams however.

**Comment by dgreif** [comment]
@dogntbone please use the workaround supplied by @saschapohle-blueforte.  I'm still not sure why the npm modules are determining the path automatically, but this should be a rare issue based on the user environment. 

@saschapohle-blueforte 30 sec streams should be fixed now :)

**Comment by dogntbone** [comment]
`{
    "bridge": {
        "name": "Homebridge 321B",
        "username": "0E:E9:2A:E2:32:1B",
        "port": 51110,
        "pin": "031-45-154"
    },
    "ffmpegPath": "/usr/local/bin/ffmpeg",
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "refreshToken": "eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiYzEyODEwMGIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2MjgzODY5NjIsImlzcyI6IlJpbmdPYXV0aFNlcnZpY2UtcHJvZDp1cy1lYXN0LTE6OTI2YmM1ZWYiLCJyZWZyZXNoX2NpZCI6InJpbmdfb2ZmaWNpYWxfYW5kcm9pZCIsInJlZnJlc2hfc2NvcGVzIjpbImNsaWVudCJdLCJyZWZyZXNoX3VzZXJfaWQiOjIzMzk3NzQxLCJybmQiOiJZTy1fQTZmSXVpaTQ0QSIsInNlc3Npb25faWQiOiJhYjU0ZDdhZS1iZDExLTRiMjUtYjQxYi0zODYwZjY2ZDIxZTAiLCJ0eXBlIjoicmVmcmVzaC10b2tlbiJ9.gNPzicvRW593rXm9zIAQc8ITlM5VbrKar4Q3DeAZezcTnimjYsUkhO9oLaO2j_AW0AX96LuwB-0oSoZXTOztLQ",
            "platform": "Ring"
        }
    ]
}`

**Comment by dogntbone** [comment]
I found the other config to change under here:
![image](https://user-images.githubusercontent.com/77230990/128618197-da8eacb0-1775-4ff8-8a08-771ea38afb43.png)

![image](https://user-images.githubusercontent.com/77230990/128618207-703f6c43-5f83-4148-94ce-4413378e1bb3.png)

Now it works perfectly! Thanks all!
