### ISSUE TITLE
Unable to authenticate with Ring (unable to verify the first certificate)

### ISSUE THREAD

**Issue by fredsocial** [dgreif/ring#633]
# Bug Report

### Describe the Bug
Unable to authenticate with Ring

### To Reproduce
Start Homebridge (v1.3.4, node v14.16.1 Raspbian GNU/Linux Buster (10))
Get token using ring-auth-cli:
This CLI will provide you with a refresh token which you can use to configure ring-client-api and homebridge-ring.
Email: xxxxxxxxx
Password: xxxxxxxxx
The token gets generated after a long wait for the 2FA (sometimes 10 minutes).

### Expected behavior
The plugin should authenticate with ring servers.

### Screenshots/Logs
Getting the following error every 5 seconds:
[Ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token. unable to verify the first certificate. Trying again in 5 seconds...

### Homebridge Ring Config
{
            "refreshToken": "xxxxxxxxxxxxxxxx",
            "alarmOnEntryDelay": true,
            "showPanicButtons": true,
            "sendCameraMotionNotificationsToTv": false,
            "sendDoorbellMotionNotificationsToTv": false,
            "platform": "Ring"
}

### Environment

 - OS: Raspbian GNU/Linux Buster (10)
 - Node.js: v14.16.1
 - NPM: v7.11.1
 - homebridge-ring: 9.18.0
 - homebridge: v1.3.4
 - hoobs: N/A

**Comment by fredsocial** [comment]
Also, when you try to regenerate the token using the UI. I always get a login failure (I tested the user/password on the ring site and it works fine).
![Screen Shot 2021-05-04 at 11 13 35 AM](https://user-images.githubusercontent.com/4115751/117026512-dbbe0700-acc9-11eb-8a67-87c1bb42174e.png)

**Comment by fredsocial** [comment]
Found the root cause of the issue: My router firewall was blocking some ports from my RPi4. I opened the ports and now it works. Closing this bug.

**Comment by dgreif** [comment]
@fredsocial sorry I didn't get around to helping with this issue sooner, but I'm glad you got it figured out! Thanks for sharing, hopefully it will be helpful if someone else hits the same issue in the future.
