### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by mczac** [dgreif/ring#636]
Every now and then Ring plug-in is reporting to HomeBridge log unhandled Rejection with Status Code 504.

[5/5/2021, 6:31:49 AM] [Ring] Request to https://app.ring.com/api/v1/mode/location/[xxxx removed xxxx]
 failed with status 504. Response body: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

(node:1486) UnhandledPromiseRejectionWarning: HTTPError: Response code 504 (Gateway Timeout)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:117:42)
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

(node:1486) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1792)

**Comment by intrepidsilence** [comment]
I am seeing the same thing happening right now. I can open a stream but it will fail after a short wait with this error.

**Comment by dgreif** [comment]
This likely happening due to a network issue somewhere between you and the Ring servers.  As long as it isn't disrupting functionality of the plugin, you can ignore it.

**Comment by intrepidsilence** [comment]
I only noticed the error due to failures to display video or crashing during the video stream.
