### ISSUE TITLE
Problème Plugin Ring !

### ISSUE THREAD

**Issue by Stewart06** [dgreif/ring#647]
Bonjour,

Depuis la dernière version du plugin, quand je lance la vidéo de ma sonnette Ring Doorbell, au bout d’un moment le flux s’arrête et me fait arrêter Homebridge tout simplement.

Obligé de relancer manuellement mon Raspberry.

Hello,

   Since the last version of the plugin, when I play the video of my Ring Doorbell, after a while the flow stops and makes me simply stop Homebridge.

   Forced to raise before my Raspberry.

**Comment by dgreif** [comment]
This seems like a duplicate of #479, though I can't say for certain.  Feel free to re-open if I misunderstood your issue.
