### ISSUE TITLE
Handle multiple homes/locations

### ISSUE THREAD

**Issue by doronkatz** [dgreif/ring#649]
Hi.. I am not sure if this has been asked before, but I have multiple homes and ring in both homes. How do I associate specific Ring devices with specific Homes?

**Comment by dgreif** [comment]
I think this should be possible, but you will have to get creative.  HomeKit only allows devices from a bridge to be added to a single Home.  You would need to create a second platform config for the plugin and run it as a child bridge, which allows you to add it separately to HomeKit.  Once you have two separate configs running as two separate bridges, you need to set the `locationsIds` in the config.  So in one bridge you would have `"locationIds": ["location-id-from-home-a"]` and then the other location id in the other platform config.  The location ids should be logged when you start up homebridge.
