### ISSUE TITLE
Alarm Base Station reporting battery at 0%

### ISSUE THREAD

**Issue by jamesg311** [dgreif/ring#65]
My Ring Alarm has a Device called "Base station" and is reporting a 0% battery which continues to show up on the Home tab under status. This seems like a new condition. For model it just says "hub.redsky" and charging = yes. Assuming this is my Ring Alarm but could it also be the Ring Smart Lighting bridge device?

**Comment by dgreif** [comment]
Yeah, I might just get rid of that since it doesn’t do anything in Home. In retrospect, I probably should have attached the siren to that device instead of the alarm.  Not sure why it shows 0% but I can confirm mine has the same thing. Will look into it when I get a chance

**Comment by dgreif** [comment]
@jamesg311 Give v`4.0.7` a try.  Should report 100% battery for the base station now (assuming it's fully charged), which will remove the low battery warning.

**Comment by dgreif** [comment]
@jamesg311 let me know when you get a chance to try out the latest version.  Just wanting to clean up this and #64 if they are both good

**Comment by jamesg311** [comment]
All good!
