### ISSUE TITLE
Ring Video Door Bell 3 "Falling Asleep"

### ISSUE THREAD

**Issue by rpmartinez3** [dgreif/ring#656]
If my Ring Doorbell is not rang after a day or so it goes into a sort of sleep mode.
I can open the home app and live stream the camera but any presses to the ring door bell don't cause it to appear on my Apple TV or cause the chimes to go off on my HomePod Minis. I restart my HOOBs box in order to get it to work correctly again.

### To Reproduce
 - Don't have visitors in a day
 - Attempt to ring door bell
 - Nothing happens other than sound ringing from the actual door bell.

### Expected behavior
The camera/ plugin to not "fall asleep" and work immediately on my Apple TV and HomePods even if no one has rang the doorbell in over a month.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by ITDevTom** [comment]
I have possibly had this issue today! Notification in the ring app but not via any apple devices. Running Homebridge on my Mac mini that its only used for this service currently.

**Comment by dgreif** [comment]
This is likely related to #616.  Does your internet occasionally cut out?

**Comment by rpmartinez3** [comment]
The issue happened again today. A friend came to visit, she rang the ring door bell and it didn’t chime on any of my homepods or popup the notification on the TV. The HOOBs support says that if I turn on the motion events on doorbell cameras will trigger a doorbell press event for tvOS 14 notification support that my issues will be resolved and maybe they’re right. But, my issue is that I live in an apartment complex and there’s a lot of foot traffic by my door.. so it’ll get annoying real quick.

**Comment by ITDevTom** [comment]
Yeah when it happened to me I could still connect to the live stream but needed to restart the homebridge service to get the bell presses back

**Comment by ultrathew** [comment]
I'm getting the exact same problem with my Ring Pro. Basically doorbell presses and motion alerts just stop coming in via Homekit periodically - even though they're working fine in the Ring app. Restarting the Homebridge service always fixes the issue, but it seems to be happening with more frequency lately.

**Comment by dgreif** [comment]
After re-reading, I'm confident that #616 is the root cause for this issue.  Please keep an eye on that one for any updates (there aren't any yet, but it's something I plan to work on in the near future).
