### ISSUE TITLE
Hidden Siren Switch not Working

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [dgreif/ring#66]
This is my config and it is not hidden in the Home App
`{
  “hideDoorbellSwitch” : true,
  “hideCameraMotionSensor” : false,
  “cameraDingsPollingSeconds” : 2,
  “refreshToken” : “***************”,
  “hideAlarmSirenSwitch” : true,
  “cameraStatusPollingSeconds” : 20,
  “beamDurationSeconds” : 60,
  “alarmOnEntryDelay” : false,
  “hideLightGroups” : true
}`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dgreif** [comment]
Weird, just had another report of this in #59. Are you on the latest version?

**Comment by d0n4v4nb3ck3r** [comment]
V4.0.3

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by d0n4v4nb3ck3r** [comment]
Also the motion sensor on my ring pro isn’t going off with HomeKit but is with my floodlight 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dgreif** [comment]
@d0n4v4nb3ck3r I just tried it out locally and it works exactly as intended.  Your config looks correct.  Try updating to the latest version of homebridge and see if that fixes it for you

**Comment by d0n4v4nb3ck3r** [comment]
>@d0n4v4nb3ck3r I just tried it out locally and it works exactly as intended.  Your config looks correct.  Try updating to the latest version of homebridge and see if that fixes it for you

@dgreif I am up to date on both. And still showing

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dgreif** [comment]
Maybe I should have asked this up front. Are you trying to hide the alarm siren (called Ring Alarm Siren by default) or a camera siren? That setting only works for the alarm siren currently

**Comment by d0n4v4nb3ck3r** [comment]
@dgreif funny thing is, I asked you for this as a feature when I asked if you would add other ring devices. Since it’s a switch, I want to disable it so I don’t accidentally hit it.

I am talking about the Ring Floodlight Cam, Siren. And not the Ring Alarm siren. I don’t have the Ring Alarm system.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by d0n4v4nb3ck3r** [comment]
>Maybe I should have asked this up front. Are you trying to hide the alarm siren (called Ring Alarm Siren by default) or a camera siren? That setting only works for the alarm siren currently

@dgreif is there anyway you can change the characteristic so it looks like a siren in HomeKit?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dgreif** [comment]
@d0n4v4nb3ck3r unfortunately HomeKit is pretty limiting in this regard.  I can make Light Bulbs and Switches, but if I make it a Speaker it won't show up in the Home app.  Speakers show up great in Eve, but for some reason Home just chooses to ignore them.  Thus..I ended up with a Switch for the siren 😞.  I guess the best option at this point is to add a `hideCameraSirenSwitch` option.  Is that what you would like?

**Comment by d0n4v4nb3ck3r** [comment]
>@d0n4v4nb3ck3r unfortunately HomeKit is pretty limiting in this regard.  I can make Light Bulbs and Switches, but if I make it a Speaker it won't show up in the Home app.  Speakers show up great in Eve, but for some reason Home just chooses to ignore them.  Thus..I ended up with a Switch for the siren 😞.  I guess the best option at this point is to add a `hideCameraSirenSwitch` option.  Is that what you would like? 

@dgreif sure! Whenever you have time, no rush.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dgreif** [comment]
@d0n4v4nb3ck3r `hideCameraSirenSwitch` released in v`4.1.0`
