### ISSUE TITLE
Error when pressing In-Home Doorbell Switch

### ISSUE THREAD

**Issue by solbadguy2010** [dgreif/ring#661]
# Bug Report

### Describe the Bug
Error in log as soon as in try to disable the ring with the In-Home Doorbell Switch. The switch re-enables itself after 3 sek

### To Reproduce
 - Set the Switch in Home App to „off“. 

### Expected behavior
No ringing as long the switch is off

### Screenshots/Logs
![814AEA3D-2F64-4FC0-8E94-632407C10478](https://user-images.githubusercontent.com/30244171/120912708-e6393b00-c691-11eb-9fa5-75df64745280.png)

### Additional context
Using Ring Video Doorbell - 2020 Version

### Environment
![9068A629-F9B3-4C42-A409-FD69F67C89AD](https://user-images.githubusercontent.com/30244171/120912739-141e7f80-c692-11eb-8f2a-3f6435e30a15.jpeg)

**Comment by dgreif** [comment]
@solbadguy2010 I can't reproduce this issue.  Are you still seeing this error when you try to press the button?

**Comment by solbadguy2010** [comment]
@dgreif Yes, it is still as reported. Also just updated to the newest version prior trying again. 

![310292BD-EA56-4C02-9574-BDFCDA3B3317](https://user-images.githubusercontent.com/30244171/126936716-2a13085e-7e10-44a7-89c4-b693b8175ad3.png)

**Comment by dgreif** [comment]
What doorbell model do you have?

**Comment by solbadguy2010** [comment]
In the Ring App its called „Video Doorbell - 2020 Release“.

i think its this one:

https://www.amazon.de/dp/B07WMKZZXL/ref=cm_sw_r_cp_awdb_imm_7SWNPDNNQRG1CCRE12HE

**Comment by dgreif** [comment]
Would you mind following the steps in https://github.com/dgreif/ring/wiki/Data-Discovery? That should give me a better idea of how the data is set up for that camera

**Comment by solbadguy2010** [comment]
{"locations":[{"name":"Zuhause","cameras":[{"description":"Haustür","subscribed":true,"subscribed_motions":true,"battery_life":"100","external_connection":true,"firmware_version":"Up to Date","kind":"cocoa_doorbell","settings":{"cv_settings":{"detection_types":{"human":{"enabled":false,"mode":"none","record":null,"notification":false},"loitering":{"enabled":false,"mode":"none","record":null,"notification":false},"motion":{"enabled":true,"mode":"edge","record":null,"notification":true},"moving_vehicle":{"enabled":false,"mode":"none","record":null,"notification":false},"other_motion":{"enabled":false,"mode":"none","record":null,"notification":false},"package_delivery":{"enabled":false,"mode":"none","record":null,"notification":false},"package_pickup":{"enabled":false,"mode":"none","record":null,"notification":false}},"threshold":{"loitering":10},"triggers":[]},"cv_paid_features":{"human":true,"loitering":true,"motion":true,"moving_vehicle":true,"other_motion":true,"package_delivery":true,"package_pickup":true},"concierge_settings":{"mode":null},"other_paid_features":{"alexa_concierge":true,"sheila_cv":true,"sheila_recording":true},"sheila_settings":{"cv_processing_enabled":null,"local_storage_enabled":null},"server_settings":{"ring_media_server_enabled":true},"zone_settings":{"motion":[{"name":"Default Zone","state":"enabled","properties":{"detection_types":["motion"]},"vertices":[{"x":0,"y":0.5189743},{"x":0.31545526,"y":0.49743593},{"x":0.7318333,"y":0.4574359},{"x":1,"y":0.42871797},{"x":1,"y":1},{"x":0.666666,"y":1},{"x":0.333333,"y":1},{"x":0,"y":1}]}]},"offline_motion_event_settings":{"subscribed":true,"enabled":false,"max_upload_kb":5000,"resolution_p":360,"frequency_after_secs":2,"period_after_secs":30},"lite_24x7":{"subscribed":true,"enabled":true,"frequency_secs":3600,"resolution_p":360},"enable_vod":1,"exposure_control":2,"motion_zones":[1,1,1,1,0],"motion_snooze_preset_profile":"low","motion_snooze_presets":["none","low","medium","high"],"live_view_preset_profile":"middle","live_view_presets":["low","middle","high","highest"],"pir_sensitivity_1":0,"vod_suspended":0,"doorbell_volume":8,"vod_status":"enabled","chime_settings":{"type":0,"enable":true,"duration":10},"video_settings":{"encryption_enabled":false},"advanced_motion_detection_enabled":true,"advanced_motion_zones":{"zone1":{"name":"Default Zone","state":2,"vertex1":{"x":0,"y":0.5189743},"vertex2":{"x":0.31545526,"y":0.49743593},"vertex3":{"x":0.7318333,"y":0.4574359},"vertex4":{"x":1,"y":0.42871797},"vertex5":{"x":1,"y":1},"vertex6":{"x":0.666666,"y":1},"vertex7":{"x":0.333333,"y":1},"vertex8":{"x":0,"y":1}},"zone2":{"name":"Zone 2","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}},"zone3":{"name":"Zone 3","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}}},"advanced_motion_detection_human_only_mode":false,"enable_audio_recording":true,"people_detection_eligible":true,"live_view_disabled":false,"ignore_zones":{"zone1":{"name":"","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone2":{"name":"","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone3":{"name":"","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone4":{"name":"","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}}},"enable_rich_notifications":true,"rich_notifications_billing_eligible":true,"loitering_threshold":10,"advanced_motion_detection_types":[],"motion_detection_enabled":true,"rich_notifications_scene_source":"cloud","recording_storage_type":"default_s3","advanced_motion_zones_enabled":true,"advanced_motion_zones_type":"8vertices","advanced_pir_motion_zones":{"zone1_sensitivity":5,"zone2_sensitivity":5,"zone3_sensitivity":5,"zone4_sensitivity":5,"zone5_sensitivity":5,"zone6_sensitivity":5},"rich_notifica-uuid":false},"features":{"motion_zone_recommendation":false,"motions_enabled":true,"show_recordings":true,"show_vod_settings":true,"rich_notifications_eligible":true,"show_24x7_lite":true,"show_offline_motion_events":false,"cfes_eligible":false,"sheila_camera_eligible":null,"sheila_camera_processing_eligible":null,"chime_auto_detect_capable":false},"owned":true,"alerts":{"connection":"online","ota_status":"successful"},"motion_snooze":null,"stolen":false,"is_sidewalk_gateway":false,"created_at":"2020-09-16T11:25:08Z","shared_at":null,"active_schedule_uuid":null,"health":{"device_type":"cocoa_doorbell","last_update_time":1628234006,"connected":true,"rss_connected":true,"vod_enabled":true,"sidewalk_connection":false,"floodlight_on":false,"white_led_on":false,"night_mode_on":false,"hatch_open":false,"packet_loss":0,"rssi":-57,"battery_voltage":3997,"wifi_is_ring_network":false,"ota_status":"successful","ext_power_state":3,"network_connection_value":"wifi","ac_power":1,"battery_present":true,"external_connection":true,"battery_percentage":100,"battery_percentage_category":"very_good","firmware_version":"cam-1.10.13400","rssi_category":"good","battery_voltage_category":"good","second_battery_voltage_category":"unknown","second_battery_percentage_category":"unknown","battery_save":false,"firmware_version_status":"Up to Date","night_light_state":true},"deactivated_at":null,"ext_power_state":3}],"chimes":[{"description":"Keller","firmware_version":"Up to Date","kind":"chime","settings":{"volume":6,"status_led_enable":true},"features":{"ringtones_enabled":true,"cfes_eligible":null},"owned":true,"alerts":{"connection":"online","ota_status":"successful"},"do_not_disturb":{"seconds_left":0},"stolen":false,"is_sidewalk_gateway":false,"created_at":"2019-04-25T14:31:10Z","shared_at":null},{"description":"Wohnzimmer","firmware_version":"Up to Date","kind":"chime","settings":{"volume":8,"status_led_enable":true},"features":{"ringtones_enabled":true,"cfes_eligible":false},"owned":true,"alerts":{"connection":"online","ota_status":"successful"},"do_not_disturb":{"seconds_left":0},"stolen":false,"is_sidewalk_gateway":false,"created_at":"2021-04-23T11:58:39Z","shared_at":null}],"devices":[]}],"amazonKeyLocks":[]}

**Comment by dgreif** [comment]
I took a look at the data you posted and everything appears to be laid out as expected.  My next suggestion would be updating your `npm` version to the latest version (`npm i -g npm@7`).  After that, try updating your plugin to the latest version and then try the in-home doorbell control again

**Comment by solbadguy2010** [comment]
All is up to Date. I also rebooted the Pi. No change. Error persists. But I also have these, maybe part of the Problem?

[13/08/2021, 19:47:11] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[13/08/2021, 19:48:14] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[13/08/2021, 19:48:22] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/3bd6e039-9290-4545-88fb-4f40aaa122ad.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[13/08/2021, 19:48:42] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/3bd6e039-9290-4545-88fb-4f40aaa122ad.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...

**Comment by dgreif** [comment]
What version of the plugin do you have?  Those errors should no longer be present in the latest version.

**Comment by solbadguy2010** [comment]
Its 9.20.1. The Updates never solves this issue for me.

**Comment by dgreif** [comment]
Does your homebridge server have unreliable internet? You should t be seeing that error unless it is unable to reach the Ring servers

**Comment by solbadguy2010** [comment]
No. LAN Connection to the Router. 100mbit Internet and all other 11 Plugins are happy. This started one day and never stopped. When i restart Homebridge the Error stops some Time

**Comment by solbadguy2010** [comment]
When i click the URL in the error it shows „ {"error":"Unauthorized","status_code":401}“. I think this comes from the server. Its reachable but won‘t let me in.

**Comment by solbadguy2010** [comment]
Just generated a new refresh Token. Will report back if this helped.

**Comment by solbadguy2010** [comment]
Did not help. Here the Log. Homebridge UI reports a terminated Child Process?

[13/08/2021, 21:29:34] [Ring]   locationId: 3bd6e039-9290-4545-88fb-4f40aaa122ad - Nieste

...

[13/08/2021, 21:29:35] [Ring] Configuring 1 cameras and 3 devices for location "Nieste" - locationId: 3bd6e039-9290-4545-88fb-4f40aaa122ad

...

[13/08/2021, 21:30:01] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[13/08/2021, 21:30:06] [Homebridge UI] [homebridge-ring] Terminating child process...
[13/08/2021, 21:30:06] [Homebridge UI] [homebridge-ring] Child process ended
[13/08/2021, 21:32:18] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[13/08/2021, 21:33:10] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[13/08/2021, 21:33:19] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/3bd6e039-9290-4545-88fb-4f40aaa122ad.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[13/08/2021, 21:33:55] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[13/08/2021, 21:34:24] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[13/08/2021, 21:35:01] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[13/08/2021, 21:36:12] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[13/08/2021, 21:36:46] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[13/08/2021, 21:38:08] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[13/08/2021, 21:38:31] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/3bd6e039-9290-4545-88fb-4f40aaa122ad.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[13/08/2021, 21:38:40] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[13/08/2021, 21:39:05] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[13/08/2021, 21:39:48] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...

**Comment by solbadguy2010** [comment]
When i click the location URL it says: "{"errors":[4006]}"

**Comment by dgreif** [comment]
Clicking those links directly won't work since you need the authentication token in your request headers (which you don't have in the browser).  Sounds like your original issue may or may not be gone, but the plugin is completely non-operational now?

**Comment by solbadguy2010** [comment]
Ah, ok. The Plugin is working. Only a little slow.

**Comment by dgreif** [comment]
Is the in home doorbell switch working?

**Comment by solbadguy2010** [comment]
No. Just tested it again. Still ringing when switch is off. This is how i found the error.

**Comment by dgreif** [comment]
I wonder if we are not on the same page about what this switch does.  From your device data, I see you have some Chimes.  This switch does _not_ disable the chimes.  It disables the mechanical doorbell built into your home, which is wired to your doorbell.  The equvalent setting can be found in the Ring app if you go into your cameras settings -> Device Settings -> General Settings -> Doorbell Chime Type -> "Ring my in-home doorbell".  If you turn the switch off in HomeKit, you should see this switch turn off in the Ring app (you will need to go up a level to General Settings and then back into Doorbell Chime Type to see it update).  As long as that switch is updating properly, then the plugin is working properly.  The chimes are controlled _separately_ and have their own "Snooze" switch.  With all that in mind, can you verify if the switch is working properly?

**Comment by solbadguy2010** [comment]
Hi, we are on the same page. When i tested i listened to my mechanical doorbell, not the chimes.
Background: mechanical doorbell is near my kids rooms. Chimes are in the basement and livingroom, the kids can‘t hear them anyway when they sleep. 

The switch does not disable the mechanical doorbell. But as a workaround i can use the setting in the ring app.

**Comment by dgreif** [comment]
Ok, glad to know we're at least on the same page.  This behavior works exactly as expected for me.  Unfortunately I can't reproduce this so I won't be able to get a fix in for you.  Wish I could help more!

**Comment by solbadguy2010** [comment]
It works as expected when it NOT disables the mechanical doorbell?

**Comment by dgreif** [comment]
Mine _does_ disable the mechanical doorbell. I can't reproduce any issues with it.

**Comment by solbadguy2010** [comment]
Ok. I can only offer, if this help, you can remote to my computer anytime and do tests. But the workaround with the original app helps a lot. I did not know i can disable it there also.

**Comment by solbadguy2010** [comment]
Since tonight the error is gone. Not even rebooted HB. Maybe on Ring server side?
