### ISSUE TITLE
Enhancement: Support for new HomeKit features

### ISSUE THREAD

**Issue by rondorn** [dgreif/ring#663]
Is it possible to add some of the motion detection and iCloud recording options to Ring via homebridge?

If it is, that would be an awesome addition. I would pay to support that feature set.

Thanks for making this tool, it very good as is, but this enhancement would take it to the next level!

**Comment by dgreif** [comment]
I believe the features you are requesting are all related to HomeKit Secure Video, which is not a feature I'm able to support at this time.  See https://github.com/dgreif/ring/issues/177 for details
