### ISSUE TITLE
Power State

### ISSUE THREAD

**Issue by itsgabraf** [dgreif/ring#67]
I’ve noticed that the Camera has a Power setting in other home apps. It seems to always be toggled to off? I turn it on and I don’t see any differences. What is it?

![8D97F984-DB15-4F7B-91E9-4CFC038997FD](https://user-images.githubusercontent.com/36346259/61194990-a321f780-a708-11e9-83a9-ba68d8b57715.jpeg)

**Comment by dgreif** [comment]
@itsgabraf it looks like this is a power switch that Eve is adding for every camera.  I don't think there is anything I can do to get rid of this, but you can click on the `edit` link in the top right of the page in eve and then hide that specific attribute on the camera.  Doesn't hurt anything if you turn it on/off.
