### ISSUE TITLE
Ring Video Doorbell 2 Two Way Issue

### ISSUE THREAD

**Issue by MartTo22** [dgreif/ring#671]
# Live Streaming Issue

When doing Two Way Talk via the HomeKit app, the camera freezes. The camera then proceeds to crash and reboot.

### Screenshots/Logs
N/A

### Recommended solution
Fix the bug with Two Way talk

### Environment

 - Ring Camera: Video Doorbell 2
 - OS: Headless Raspbian
 - Node.js: 14.16.1
 - NPM: 7.11.1
 - homebridge-ring 9.18.1
 - homebridge 1.3.4
 - hoobs N/A

### Network Environment
 Homebridge server is a Raspberry Pi 1 (B) and is connected via ethernet. One home hub is running, which is a Apple TV 4K.

**Comment by Hackintoshbigsur** [comment]
Same problom

**Comment by MartTo22** [comment]
Yeah, it’s a problem with the code most likely. Not sure what could be
wrong exactly however

**Comment by Hackintoshbigsur** [comment]
Question: how do I go to a previus version

**Comment by MartTo22** [comment]
If you have the Homebridge UI, uninstall the plugin, after that search it
up again but instead of just clicking install, go to the wrench and select
“Install Previous Version”

**Comment by dgreif** [comment]
This is an issue with some updates that Ring made to their media servers.  I haven't pinned down a solution yet, but I don't think any previous versions will work with the new servers.  Let me know if you try it and an old version actually does work!

**Comment by Hackintoshbigsur** [comment]
I tried it doesn’t work :/

**Comment by Hackintoshbigsur** [comment]
Any luck?.

**Comment by MartTo22** [comment]
No unfortunately. It’s an issue on Ring’s end.

**Comment by Hackintoshbigsur** [comment]
So basically no work around or 2 way talk only way

**Comment by Casuallynoted** [comment]
I'm noticing this message in my logs when I try to use the microphone in my camera stream. I'm not sure if this is the same issue but it seems like it could be:
err:  Error: remote peer disconnected
    at TLSSocket.<anonymous> (/Users/cas/.npm-packages/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:584:43)
    at TLSSocket.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

**Comment by SlyRix** [comment]
same Problem

**Comment by Hackintoshbigsur** [comment]
Hmm I don’t see this anywhere in my homebridge logs??

**Comment by jimmyfisher** [comment]
Same issue too - nothing in the logs aside from 

`7/10/2021, 2:33:09 PM  Ring Bridge  Ring  Stopped Live Stream for Front Door`

This only happens after clicking the 'Intercom' button in Home. If I do it in the normal Ring app, no problem. Also happening with my Spotlight Cam in the backyard.

**Comment by Hackintoshbigsur** [comment]
Yeah. I use homebridge just click the talk button and it’s not hardware issue

**Comment by dgreif** [comment]
Duplicate of #590
