### ISSUE TITLE
Access Controller Pro update?

### ISSUE THREAD

**Issue by radtadbrad** [dgreif/ring#679]
Good afternoon!  I was doing some research and ended up here.  Any chance that the status of the access controller pro integration has improved?  I would be will to fund the project if necessary / within reason.  I have successfully integrated dozens of ring doorbells, cameras, sensors, and alarms through hubitat.  My plan is to create a dasshboard that can view and control all of ring locks and cameras at my office and warehouse.  Everything works perfectly except for the access controller pro.  Any help at all would be greatly appreciated.  Thanks! - Brad

**Comment by dgreif** [comment]
Hey Brad, there are no changes to the situation with controller pro. It really belongs in a separate plugin dedicated to Amazon key accessories. That's not something I'm interested in building myself, but it's possible another developer in the homebridge community would be willing to at some point. Sorry I can't be of more help on this one!
