### ISSUE TITLE
Unable to stream at all

### ISSUE THREAD

**Issue by nathanjskelton** [dgreif/ring#683]
# Bug Report

### Describe the Bug
Recently (2 or 3 weeks) I am unable to open a stream to my ring doorbell or flood cam from HomeKit (iPhone, AppleTV, etc). I get the snapshots OK but when I try to stream, it tries for a few seconds then I get the following error:

### To Reproduce
Any time I try to view the stream from HomeKit client

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
`
hoobs         | [Ring] Stopped Live Stream for Front Door
hoobs         | [Ring] Failed to prepare stream for Front Door (9.068s)
hoobs         | [Ring] Error:
hoobs         |     at _super (/hoobs/node_modules/rxjs/src/internal/util/createErrorClass.ts:13:22)
hoobs         |     at new EmptyErrorImpl (/hoobs/node_modules/rxjs/src/internal/util/EmptyError.ts:26:3)
hoobs         |     at Object.complete (/hoobs/node_modules/rxjs/src/internal/lastValueFrom.ts:72:18)
hoobs         |     at Object.complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:193:14)
hoobs         |     at SafeSubscriber.Subscriber._complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:131:24)
hoobs         |     at SafeSubscriber.Subscriber.complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:105:12)
hoobs         |     at OperatorSubscriber.Subscriber._complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:131:24)
hoobs         |     at OperatorSubscriber.Subscriber.complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:105:12)
hoobs         |     at OperatorSubscriber.Subscriber._complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:131:24)
hoobs         |     at OperatorSubscriber.Subscriber.complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:105:12)
hoobs         |     at OperatorSubscriber.Subscriber._complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:131:24)
hoobs         |     at OperatorSubscriber.Subscriber.complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:105:12)
hoobs         |     at OperatorSubscriber.Subscriber._complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:131:24)
hoobs         |     at OperatorSubscriber.Subscriber.complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:105:12)
hoobs         |     at Subject.complete (/hoobs/node_modules/rxjs/src/internal/Subject.ts:84:28)
hoobs         |     at Object.complete (/hoobs/node_modules/rxjs/src/internal/operators/share.ts:165:16) {
hoobs         |   message: 'no elements in sequence'
hoobs         | }
`

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
{
            "hideAlarmSirenSwitch": true,
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "platform": "Ring",
            "refreshToken": "xxx",
            "hideUnsupportedServices": true,
            "hideDeviceIds": [],
            "locationIds": [],
            "onlyDeviceTypes": []
        }
```

### Environment
 - OS: Ubuntu
 - Node.js: 14.16.0
 - NPM: 6.14.4
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: N/A
 - hoobs: 3.3.3

**Comment by dgreif** [comment]
@nathanjskelton can you try with the latest version of the plugin?

**Comment by nathanjskelton** [comment]
No dice-- appears to be timing out establishing the connection...

```
hoobs         | [Ring] Preparing Live Stream for Front Door
hoobs         | [Ring] Connecting to Front Door using STUN
hoobs         | [Ring] Waiting for stream data from Front Door (0.323s)
hoobs         | [HOOBS3 004D@Setup Endpoints] The write handler for the characteristic 'Setup Endpoints' on the accessory 'Front Door' was slow to respond!
hoobs         | [HOOBS3 004D@Setup Endpoints] The write handler for the characteristic 'Setup Endpoints' on the accessory 'Front Door' didn't respond at all!. Please check that you properly call the callback!
hoobs         | [Ring] Stopped Live Stream for Front Door
hoobs         | [Ring] Failed to prepare stream for Front Door (9.251s)
hoobs         | [Ring] Error:
hoobs         |     at _super (/hoobs/node_modules/rxjs/src/internal/util/createErrorClass.ts:13:22)
hoobs         |     at new EmptyErrorImpl (/hoobs/node_modules/rxjs/src/internal/util/EmptyError.ts:26:3)
hoobs         |     at Object.complete (/hoobs/node_modules/rxjs/src/internal/lastValueFrom.ts:72:18)
hoobs         |     at Object.complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:194:14)
hoobs         |     at SafeSubscriber.Subscriber._complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
hoobs         |     at SafeSubscriber.Subscriber.complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
hoobs         |     at OperatorSubscriber.Subscriber._complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
hoobs         |     at OperatorSubscriber.Subscriber.complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
hoobs         |     at OperatorSubscriber.Subscriber._complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
hoobs         |     at OperatorSubscriber.Subscriber.complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
hoobs         |     at OperatorSubscriber.Subscriber._complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
hoobs         |     at OperatorSubscriber.Subscriber.complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
hoobs         |     at OperatorSubscriber.Subscriber._complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
hoobs         |     at OperatorSubscriber.Subscriber.complete (/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
hoobs         |     at /hoobs/node_modules/rxjs/src/internal/Subject.ts:90:30
hoobs         |     at Object.errorContext (/hoobs/node_modules/rxjs/src/internal/util/errorContext.ts:29:5) {
hoobs         |   message: 'no elements in sequence'
hoobs         | }
hoobs         | [Ring] From Ring (Front Door): stopped gracefully
hoobs         | [Ring] From Ring (Front Door): Guessed Channel Layout for Input Stream #0.0 : mono
```

**Comment by dgreif** [comment]
Maybe try updating HOOBS? Otherwise, it looks like a networking issue. Might be blocking the ports needed to stream. It uses a random port so all need to be open

**Comment by nathanjskelton** [comment]
I actually moved from HOOBS to the latest oznu homebridge/docker image and have the same issue. Although I am runnign in host networking mode, within docker there are so many interfaces such as docker0, etc in addition to eno1 which is the actual host interface. Is it possible that the plugin (and ffmpeg) is trying to use the wrong interface to connect to ring and if so, is there a way to specify the interface that you know of?

**Comment by dgreif** [comment]
I'm sure it's possible to get it working in Docker, but it's not something I can help debug and configure.  You may have good luck asking in the #docker channel in the homebridge discord server.
