### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by Zakstensrud4590** [dgreif/ring#685]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...
I am trying to add my ring to home bridge and whenever I try to add the refresh token json to config I get a JSON error

### To Reproduce
 - Start Homebridge
 - Attempt to ...add refresh token to console
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.
accept refresh token

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.
<img width="1440" alt="Screen Shot 2021-07-04 at 8 33 25 AM" src="https://user-images.githubusercontent.com/82841997/124386990-88087380-dca2-11eb-9400-964aa584e75d.png">

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS:MacOS Big Sur
 - Node.js: 14.17.0 
 - NPM: 6.14.13 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: N/A

**Comment by dgreif** [comment]
Can you try setting up the plugin from the plugin page instead of editing the json manually? There is a nice UI for logging in to ring, and it sets everything for you
