### ISSUE TITLE
Ring Accessories not showing in HOOBS 4 after re-authenticating

### ISSUE THREAD

**Issue by grizleeeee** [dgreif/ring#687]
# Bug Report

### Describe the Bug
Recently had to move which bridge I was connecting my Ring account to, and when I authenticate successfully (I've tried both the CLI method and the GUI in HOOBS), no accessories are visible.  I've tried unlinking the account and re-authenticating multiple times.

### To Reproduce
1. In HOOBS 4, install "Ring" plugin
2. Select Create New bridge
3. Configure Plugin
4. Click on Link Account 
5. Enter Credentials
6. Enter MFA Code
7. Successfully login (no errors in Log)
8. Check for Accessories and nothing is there.

### Expected behavior
Accessories would normally be visible in the HOOBS Accessories list.

### Screenshots/Logs
(After restarting bridge):
7/9/2021, 9:50:53 PM ringbridge stopping
7/9/2021, 9:50:53 PM Ring BridgeShutting down
7/9/2021, 9:50:55 PM Ring BridgeStopped
7/9/2021, 9:50:57 PM Ring Bridge starting
7/9/2021, 9:51:00 PM Ring BridgeInitializing HAP-NodeJS v0.9.4...
7/9/2021, 9:51:04 PM Ring BridgeERRORError loading plugin "homebridge-ring"
7/9/2021, 9:51:04 PM Ring BridgeWARNINGNo plugins installed.
7/9/2021, 9:51:04 PM Ring BridgeLoading 1 platforms...
7/9/2021, 9:51:04 PM Ring BridgePreparing Advertiser for 'Ring Bridge 418D' using bonjour-hap backend!
7/9/2021, 9:51:04 PM Ring BridgeSetup URI 'X-HM://--REMOVED--'
7/9/2021, 9:51:04 PM Ring BridgeStarting to advertise 'Ring Bridge 418D' using bonjour-hap backend!
7/9/2021, 9:51:04 PM Ring BridgeBridge is running on port 51826.

### Additional context
Successfully upgraded HOOBS 3.3.7 to 4.0.66, didn't split my hubs, ran into some issues removing old plugins, so created new bridges, the old install on the original bridge showed all the accessories fine after the upgrade to HOOBS 4.

### Homebridge Ring Config

```
{
    "accessories": [],
    "platforms": [
        {
            "platform": "Ring",
            "refreshToken": "----REMOVED----",
            "alarmOnEntryDelay": true,
            "hideDoorbellSwitch": false,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "debug": true,
            "cameraStatusPollingSeconds": 20,
            "cameraDingsPollingSeconds": 2,
            "locationModePollingSeconds": 0,
            "hideLightGroups": true
        }
    ]
}
```

### Environment
 - OS: Raspbian
 - Node.js: v14.17.2
 - NPM: 6.14.13
 - homebridge-ring: 9.18.1
 - homebridge: N/A
 - hoobs: 4.0.79

**Comment by dgreif** [comment]
Have you reached out to HOOBS support? If the plugin was working fine before the update, it's likely an issue with HOOBS

**Comment by grizleeeee** [comment]
I have not, but will do so now.  

The reason I came here first was because I wasn't seeing this behavior in any of the other plugins (7 total).  Checked the debug logs in HOOBS and enabled Debug for the plugin and nothing is giving me any indication that anything's even wrong aside from the fact that the 2 cams and my Chime aren't visible.  

I'll try HOOBS Support and will report back what they say.

**Comment by dgreif** [comment]
@grizleeeee any luck?

**Comment by mkellsy** [comment]
Try upgrading HOOBS. After you might have to Unlink and re Link to get a fresh refresh token.

**Comment by dgreif** [comment]
This doesn't seem like a plugin issue at this point.  If you continue to have issues, please reach out to HOOBS support.
