### ISSUE TITLE
Ring Encryption

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#688]
If I turn the new ring Encryption on will this step the video working in Homekit?

https://www.engadget.com/ring-doorbell-end-to-end-encryption-133046912.html?src=rss

**Comment by dgreif** [comment]
If you turn on end-to-end encryption, the homebridge plugin will no longer be able to stream video from your Ring cameras.  The plugin is not set up to decrypt the video.  This is not a feature that I intend to add any time soon as it would be extremely complex to figure out how the video is being encrypted, and how to get the keys to decrypt it.  Sorry I can't give better news!

**Comment by adavison007** [comment]
Thanks, much appreciated, off stays encryption 👀

Sent from my iPhone

On 13 Jul 2021, at 19:34, Dusty Greif ***@***.***> wrote:

﻿
Closed #688.
