### ISSUE TITLE
Talk button causes doorbell to restart.

### ISSUE THREAD

**Issue by EdwardChamberlain** [dgreif/ring#689]
# Bug Report

### Describe the Bug
 Using the 'talk' button on the camera preview causes the doorbell to restart.

### To Reproduce
 - Open camera feed, 
 - Press talk.
 - Doorbell restart is immediate.

### Expected behavior
 Hear voice. 

### Screenshots/Logs
 N\A

### Additional context
 This is the new Ring Hardwired doorbell. 

### Homebridge Ring Config
```
{
    "refreshToken": "XXXX",
    "platform": "Ring"
}

```

### Environment

 - OS: unRAID 6.9.1 running homebridge docker.
 - Node.js: v14.17.3 
 - NPM: 6.14.13 
 - homebridge-ring: v9.18.1
 - homebridge: v1.3.4
 - hoobs: N/A

**Comment by dgreif** [comment]
@EdwardChamberlain are you still having this issue after the recent updates?  What doorbell model do you have?
