### ISSUE TITLE
"remote peer disconnected" errors in log

### ISSUE THREAD

**Issue by HanSooloo** [dgreif/ring#693]
# Live Streaming Issue

### Describe the live streaming issue
After I restart a live stream, I see the "remote peer disconnected" error message in the log.  The way to reproduce is the following:
1. View live stream.
2. Stop
3. View live stream again
4. Observe error

If I wait for a few minutes, then I don't see this error upon first live stream.  But 2nd and onwards live streams exhibit this errror. 

### Screenshots/Logs
```
[7/19/2021, 2:31:19 PM] [homebridge-ring] Ding 6986645037236162537 is expired (480).  Fetching a new ding and trying video stream again
err:  Error: remote peer disconnected
    at TLSSocket.<anonymous> (/usr/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:584:43)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

### Recommended solution
Not sure?

### Environment

 - Ring Camera: [Video Doorbell Pro]
 - OS: [Ubuntu 18.04.5 LTS]
 - Node.js: [14.16.0] 
 - NPM: [7.6.3] 
 - homebridge-ring (if applicable): [9.18.2]
 - homebridge (if applicable): [0.9.4]

### Network Environment
Doorbell connects to home Wi-Fi, which is a Verizon FiOS Quantum G3100 router.
Pi-hole latest providing DHCP and DNS services.
Apple TV 4K, on tvOS 14.6 acting as HomeKit hub.

**Comment by tomsteenbakkers** [comment]
i have the same issue. after this error the child proces running will crash with `Error: SIP session has already ended. ` and this is a red error in homebridge

**Comment by benoitvinc** [comment]
Same issue here.

**Comment by dgreif** [comment]
Please see https://github.com/dgreif/ring/wiki/Camera-Troubleshooting
