### ISSUE TITLE
Add Re-Link Button for Account.

### ISSUE THREAD

**Issue by donavanbecker** [dgreif/ring#696]
# Feature Request

### Description
 A clear and concise description of the problem or missing capability...
If you change password or need to ever re-link the account, the refreshtoken needs to be removed and then you are able to re-link the account. The problem is that all of the config from the plugin is then removed and then you need to reset that back up.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
It would be nice if there was a re-link account Botton that would take you back to the login screen you can then type in your username and password and then it would pull in a new refresh token, leaving everything else in the current config as it is.

<img width="832" alt="Screen Shot 2021-07-26 at 9 20 34 AM" src="https://user-images.githubusercontent.com/9875439/127005197-be084d27-6e6d-4648-91ac-65d9ae15b7a1.png">

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by donavanbecker** [comment]
[homebridge-ui.zip](https://github.com/dgreif/ring/files/6890125/homebridge-ui.zip)
customerKey and customerSecret can be changed to email and password so that you can re-link account and not loose your current config if you need to re-link your account.

**Comment by dgreif** [comment]
Yep, I've been planning to add a custom ui so that @oznu can remove the ring ui from homebridge-config-ui-x.  Just haven't gotten around to it, but I'll keep this issue as a placeholder for that work 😄

**Comment by donavanbecker** [comment]
@dgreif Thanks!
