### ISSUE TITLE
Is there any way of implementing the pre-rolled subscription  into HomeKit 

### ISSUE THREAD

**Issue by treforparr** [dgreif/ring#698]
# Feature Request
Is there any way of involving a pre-rolled subscription the people pay for from the ring cloud into HomeKit maybe there might be a way of dragging it into make Secure video but only for pay used for a ring subscription
### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dgreif** [comment]
I'm having trouble understanding exactly what you are asking for, but the plugin is not able to impact subscriptions at all.  I also don't plan to support HomeKit Secure Video at this point.  See #177 if you want more details on that decision.
