### ISSUE TITLE
Moving from ring alarm plugin to ring

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#70]
I have ring-alarm-platform plugin installed with hoobs, that’s now depreciated, how do I migrate to the new hombride-ring plugin without all devices duplicating etc?

**Comment by dgreif** [comment]
See https://github.com/dgreif/ring/wiki/Upgrading-from-v3-to-v4#upgrading-homebridge

**Comment by adavison007** [comment]
@dgreif thanks, ok, will work out how to stop homebridge in hoobs and give it a go.

**Comment by dgreif** [comment]
@adavison007 I'm going to close this as there isn't really anything to do on my end.  Let me know if you have any questions for me
