### ISSUE TITLE
Hoobs 401 error, correct token

### ISSUE THREAD

**Issue by nakedeye515** [dgreif/ring#707]
[](url)[Ring] HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: {
    start: 1627427682624,
    socket: 1627427682796,
    lookup: 1627427682797,
    connect: 1627427682797,
    secureConnect: 1627427682797,
    upload: 1627427682802,
    response: 1627427682919,
    end: 1627427682934,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 172,
      dns: 1,
      tcp: 0,
      tls: 0,
      request: 5,
      firstByte: 117,
      download: 15,
      total: 310
    }
  }
}
7/27/2021, 7:14:42 PM [Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed:
7/27/2021, 7:14:42 PM [Ring] Error connecting to API

**Comment by nertwork** [comment]
This is the same issue as described in #699 and #722

**Comment by dgreif** [comment]
Looks like Ring removed the endpoint we were using before. Should be fixed in 9.18.6
