### ISSUE TITLE
Motion Schedules Enabled/Disabled via HomeKit

### ISSUE THREAD

**Issue by jimmyfisher** [dgreif/ring#709]
# Feature Request

### Description
I've been running into this annoying issue where, while I can set 'motion detection' and 'live view' enabled/disabled per device per mode, I can't toggle on/off motion schedules. I've written into Ring who were going to 'submit the feedback', but I doubt that will go anywhere.

The problem being that I can use HomeKit to change the mode from 'Home' to 'Away', but then I'm not recording **anything** when home if I disable 'motion detection'.

### Describe the solution you'd like
I'm hoping that whatever this plugin's code talks to on Ring's API is able to tap into whether or not Motion Schedules have been enabled or disabled and then I could set up a HomeKit automation that would enable/disable those schedules depending on whether anyone was home or not.

The functionality would be to set up a motion schedule in the Ring app that silenced motion notifications during whatever time you didn't want them while you were physically home. The automation in HomeKit would then disable that schedule (no matter what mode the Ring system was in because apparently those motion schedules are independent of Modes) when you left the house.

That way (for instance), I wouldn't get notified during 7a-7p from my backyard Spotlight Cam that there was motion while I was home (ensuring that when it was dark, even if I **was** home, I would still be notified), but if I happened to go somewhere during the day, that schedule would be disabled until I arrived back so I **would** get notifications between 7a-7p.

And all the while, any motion would still be getting recorded by the device along with snapshots being captured.

One hiccup I could see would be the fact that each motion schedule can be created either as 'Night Time', 'Morning', 'Evening' and 'custom'. So I'm not sure how you'd identify which schedule to enable/disable. If it's not possible to see the existing schedules individually, then hoping there's a way to disable **all** motion schedules in this fashion as a workaround.

### Describe alternatives you've considered
Tried reaching out to Ring to see if this is a feature I was missing. It is not.

**Comment by dgreif** [comment]
I appreciate the detailed description, but I don't think this is a feature that I care to add/maintain in the plugin.  Have you considered using HomeKit notifications in some way to supplement the Ring notifications?  HomeKit _does_ give you the ability to specify both time _and_ home/not home when setting up notifications.

**Comment by jimmyfisher** [comment]
Thanks for the quick response!

The issue I have w the HomeKit notifications is that you don't get the different audio cues that you can get with Ring. Right now, I have different sounds for the front and back of the house, where as with HomeKit, all notifications are the same no matter what. Also, those don't give you the option to long-press on the notification and temporarily snooze motion notifications for 30 min or 1 hr.

I was hoping it wouldn't be something too intensely buried. I really don't get why Ring hasn't allowed users to set per-mode motion schedules. Seems like an oversight considering the whole idea of 'modes' is to have the hardware do different things depending on the mode. 

To have something like the motion schedule independent of modes seemed weird to me. Hence this as a workaround to Ring's shortcomings.

Totally understand if it's not something you want to pursue, but would definitely appreciate it if it's something that may be possible.

Thanks again!

**Comment by jimmyfisher** [comment]
I should also mention - it seems that the Ring Chime automatically has this 'snooze' option as a toggle in HomeKit. When I go into Home, it shows me 'snooze', 'ding', and 'play motion' as 3 separate on/off sliders.

In the Ring app, if I click on the Chime, 'Chime Snooze' is one of the buttons and it's the same thing as 'Motion Snooze' in the Spotlight cam with a slider saying how long you want to snooze it for.

I wonder if that's an alternative - rather than having to deal with the motion schedules, see if there's a way for an additional 'accessory' to be shown that is a toggle on/off for the Motion Snooze. 

Right now, I see 'Motion', 'Ring Light', and 'Ring Siren' as the 3 accessories that come in with my connected Spotlight Cam. I'm not sure where these are generated from, but perhaps 'Ring Motion Snooze' is something that's already accessible?

Then, I could set something up with automations to activate 'Motion Snooze' at certain intervals unless I'm away from home.

**Comment by dgreif** [comment]
While it's probably possible through the API, I think your original approach of reaching out to Ring is the right path.  This is a feature they should be building in the Ring app.  Hopefully they listen to your feedback and add it soon!

**Comment by jimmyfisher** [comment]
I hope so too. Was hoping since the Chime puts through the snooze option that it was something copy/paste to the Spotlight Cam so that on/off switch would show in the Home app. 

Appreciate your time.
