### ISSUE TITLE
Resize Snapshots

### ISSUE THREAD

**Issue by dgreif** [dgreif/ring#71]
We currently use the raw snapshot that we receive from Ring, without resizing it to match the request from HomeKit.  This means we are potentially uploading a larger image than we need to.  Need to find out what size the current snapshots are, and find a way to resize them accordingly.

**Comment by dgreif** [comment]
Decided to take a break from live stream and knock this one out.  Snapshots from ring were 1920x1080.  HomeKit requests 480x270.  By resizing the images, we reduce the size by 95% (yeah, seriously), which means HomeKit will be able to upload and distribute the snapshots to devices _way_ faster.  🚀 🐎 🔥

**Comment by d0n4v4nb3ck3r** [comment]
@dgreif that is awesome!! Thanks!

**Comment by ifeign** [comment]
I can't update. It throws an error which causes the plugin to uninstall itself, I have to manually reinstall 4.2.1. Will get a log for you later.. I'm not at home right now

**Comment by dgreif** [comment]
@ifeign I was afraid that might happen to some users. The library I pulled in for resizing needs node-gyp. It’s a pain, but this particular library was way faster at resizing than others that I tried. Do a good search for setting up node-gyp. What platform are you running homebridge on (windows, Linux, mac)?

**Comment by ifeign** [comment]
I run it on a raspberry pi through docker

**Comment by ifeign** [comment]
Here's the error btw
`USER: root
DIR: /usr/local/lib
CMD: npm --no-update-notifier install --unsafe-perm homebridge-ring@latest

/usr/local/bin/ring-auth-cli -> /usr/local/lib/node_modules/homebridge-ring/ring-auth-cli.js

> sharp@0.22.1 install /usr/local/lib/node_modules/homebridge-ring/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linuxmusl-armv6.tar.gz
/usr/local/lib/node_modules/homebridge-ring/node_modules/sharp/install/libvips.js:86
          throw new Error(`Status ${response.statusCode}`);
          ^

Error: Status 404
    at /usr/local/lib/node_modules/homebridge-ring/node_modules/sharp/install/libvips.js:86:17
    at f (/usr/local/lib/node_modules/homebridge-ring/node_modules/once/once.js:25:25)
    at ClientRequest.protocol.request.res (/usr/local/lib/node_modules/homebridge-ring/node_modules/simple-get/index.js:63:5)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
make: Entering directory '/usr/local/lib/node_modules/homebridge-ring/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:10: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
          ^~~~~~~~~~~~
compilation terminated.
`

**Comment by dgreif** [comment]
See #73. Sorry for the trouble

**Comment by dgreif** [comment]
I tried several other packages (`jimp`, `imagejs`, `image-js`) and they were all poor compared to `sharp`.  For comparison, `sharp` took ~37ms and reduced the image size by 95%.  `image-js` took ~363ms and only reduced the image size by 65%.  The other libraries performed even worse.  I really really don't want to have node-gyp install issues because it will be a never ending stream of Github issues about not being able to install the plugin.  At this point, I'm just going to revert snapshot resizing and use the original image size that we receive from Ring 😞.  If anyone knows of a different image processing library that is pure node and performs resizes quickly, please let me know.
