### ISSUE TITLE
Ring plugin downloading/uploading massive amounts of data!

### ISSUE THREAD

**Issue by EagleDTW** [dgreif/ring#710]
Ring plugin downloading/uploading massive amounts of data! It’s the normal download site (share-service-download-bucket.s3.amazonaws.com) but in a month the updates from late June now download and upload about a TB of data and it’s all traffic to that site for video. Caused us to run over our data allowance.

Thank you, Daniel

**Comment by dgreif** [comment]
Are you leaving the Home app open all the time? The only media downloaded by the plugin is snapshots, which only get fetched while the Home app is open and has a camera visible

**Comment by EagleDTW** [comment]
I typically do leave the home app open although the interface often doesn’t update correctly when you do that, I’ve since learned how to create a client specific group in pihole and block it from accessing the website. Hopefully that takes care of it!
