### ISSUE TITLE
Request to https://api.ring.com/clients_api/dings/active failed:

### ISSUE THREAD

**Issue by kjellywang** [dgreif/ring#718]
# Bug Report

### Describe the Bug
 The system does not refresh the token after ~1 hour or so. Error message:

Request to https://api.ring.com/clients_api/dings/active failed:
[8/2/2021, 8:43:07 AM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:93:15)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:97:36)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:4:12)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:96:16)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:121:33)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:6:65) "

 {"error":"Unauthorized","status_code":401}

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. MacOS]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. v19.0.0]
 - hoobs: [ N/A]

**Comment by dgreif** [comment]
The second line of the error explains the problem: `Refresh token is not valid`.  You need to generate a new refresh token, store it in your config, and then restart homebridge.

**Comment by kjellywang** [comment]
Yes, it works every time I generate a new token. The token in the config also automatically updates, but it only lasts ~1 hour after which the token won't refresh anymore.

**Comment by kjellywang** [comment]
By the way, it used to work quite stably. The problem started to appear since ~10 days ago...

**Comment by dgreif** [comment]
@kjellywang have you changed anything with your configuration or user permissions on your homebridge server?  The refresh token is written to your config file after every re-authentication.  If the homebridge process somehow didn't have permission to write the file, you would see the behavior you have described.

**Comment by kjellywang** [comment]
@dgreif I don't think I have changed anything to the configuration or file permissions. As I described earlier, the token stops to refresh after ~1 hour or so.

**Comment by kjellywang** [comment]
@dgreif And there is an error message before the refresh token issue line:

"Request to https://api.ring.com/clients_api/dings/active failed:", And when I click the link, it pops up:
{"error":"Unauthorized","status_code":401}

**Comment by kjellywang** [comment]
@dgreif It looks that the first error message is 

HTTPError: Response code 429 (Too Many Requests)

**Comment by joesturz** [comment]
I am also seeing this same issue starting about 2 weeks ago. I had not changed my config file previously. I have followed the error message suggesting to update my token. It works for about an hour after updating the token and then begins to fail with the same errors mentioned above.

**Comment by jimmyfisher** [comment]
My cameras stopped responding in HomeKit today. Same error happening every 1 sec. Was working totally fine up until noticing today. No changes - using HOOBS and the Ring plugin with the UI to authorize access.

Going to try unlinking and relinking, but just wanted to mention this is the same for me.

**Comment by TheUglyKorean** [comment]
Same exact error for me on Mac. Can confirm the config file is being written and running the latest versions across the board.

**Comment by kjellywang** [comment]
@dgreif switched to a raspberry pi, and everything now seems to be fine.

**Comment by tsightler** [comment]
I've recently had a few reports of a seemingly similar issue with ring-mqtt users as well.  I store updated tokens in a state file, but somehow, some users are seeing this and the code stops working.  Strangely though, the saved token is clearly valid as these users can actually just restart and it works.  It's almost like the code is getting a new token but the token isn't valid yet.  I've never had reports of such issues previously, seemed to just start the last couple of weeks.

Out of curiosity, what does the API code do if it gets and authentication error?  I'm assuming it does not consider this a retryable error because, well, why would it expect a currently invalid token to become valid.  Right now it seems like getting this error simply kills the code.  Should I be attempting to address these types of errors in my code, perhaps just exiting on a token error and restarting?

**Comment by anupchavda1** [comment]
I am also getting exactly the same behaviour on a Mac after an hour of refreshing the token.

**Comment by dgreif** [comment]
@tsightler the ring client should be handling this, it's not something you should have to worry about.  I'm not able to reproduce this issue.  It doesn't make sense that Ring would be rejecting the auth tokens some times but not others.  This feels like an issue on the Ring side, and not something I can fix on my end...

**Comment by tsightler** [comment]
@dgreif I agree regarding the issues on Ring side.  I've seen some pretty strange behavior over the last few weeks, even in the official Ring app, that I think was also token related.  My app would open and attempt to connect but would fail with various authentication related error messages, however, it would never prompt me to authenticate with my username/password.  It was as if the app thought it had a valid token and just kept trying to use it.  I tried killing and restarting the app and even restarting the phone, with no effect.  I was finally able to dismiss the errors enough to get to the Account Settings page in the app and click Signoff, which then let me re-authenticate via 2FA and get back in.

I also keep seeing this little, well, I don't know how to describe it, I guess I would call it a "blip" where I'm using the Ring app.  I've been testing some new devices that I'm supporting in ring-mqtt, like a thermostat, so I've been using the app a lot more than normal.  I'll go to change a setting and suddenly the app will show "offline", like the connection to Ring is broken, but it only last maybe a few hundred milliseconds at most.  It's almost like, that app itself is getting the invalid token, but then retries quickly and it works.  Admittedly, this is just theorizing based on the visible behavior.

**Comment by ekovacs34** [comment]
I've been experiencing this identical behavior as well. I haven't changed anything so it was really surprising when my refresh token randomly expired (about two weeks ago). Since then, I've been generating new tokens and it would work for about an hour (sometime 3 or 4 hours) but it would always expire. I've tried uninstalling and reinstalling several times to see if that fixed it. 

Suddenly, today - ring informed me my password is incorrect and forced me to reset. We'll see in by tomorrow morning. 

I don't think it's the device I'm using, my setup, or the plugin. The fact that Ring suddenly invalidated my password makes me wonder if it's something they've been doing. Thanks all.

**Comment by ekovacs34** [comment]
No luck resetting my password with ring. The refresh token expired.

**Comment by ekovacs34** [comment]
@TheUglyKorean Are you still experiencing this issue? I am and I'm stumped. Wondering if anyone has found the solution to this. Thanks.

**Comment by TheUglyKorean** [comment]
> @TheUglyKorean Are you still experiencing this issue? I am and I'm stumped. Wondering if anyone has found the solution to this. Thanks. 

I am. I don't see what's causing it in the code, and I'm not sure why it's not affecting all systems.  I've gone back to using the app like a primitive 🦧😔

**Comment by ekovacs34** [comment]
> > @TheUglyKorean Are you still experiencing this issue? I am and I'm stumped. Wondering if anyone has found the solution to this. Thanks.
> 
> I am. I don't see what's causing it in the code, and I'm not sure why it's not affecting all systems. I've gone back to using the app like a primitive 🦧😔

Same here - hopefully it gets worked out.

**Comment by dgreif** [comment]
@kjellywang are you still experiencing issues?

**Comment by VGXisTheWay** [comment]
> @kjellywang are you still experiencing issues?

I am. I've since disabled the plug-in and now use Ring's native scheduling 😢

**Comment by kjellywang** [comment]
> @kjellywang are you still experiencing issues?

I had no issue since I switch to a Raspberry PI.

**Comment by ekovacs34** [comment]
@dgreif the issue still persists on mac, it appears. I can update my token but it expires after about an hour. I’ve uninstalled everything and reinstalled.

**Comment by Martin-de-W** [comment]
I'm having the same issue on a raspberry. It eventually creates enough load that other plugins (like for my AC) stop working as well.

**Comment by joesturz** [comment]
After disabling the ring plugin for several months, I decided to revisit this by updating the plugin and enabling it with a new token. Everything has been working for the last 2 weeks. 

Have others seen this issue appear to be resolved? Was it determined to be an issue on the Ring side? Is this still an issue?

Running the server on MacOS 10.14.6, Homebridge v1.3.6

**Comment by dgreif** [comment]
This has splintered a lot from the original issue.  If you are still having problems, please open a new issue
