### ISSUE TITLE
Floodlight Cam Snapshots Not Loading

### ISSUE THREAD

**Issue by EarthRise626** [dgreif/ring#72]
The plugin has been working great for me until today. For whatever reason, my doorbell cams are loading snapshots into HomeKit, but the floodlight cam is not. I am also unable to get a response from the floodlight “light” in HK as well as the associated motion detector. I obtained a new refresh token to attempt to troubleshoot, but that resulted in no improvement.

**Comment by EarthRise626** [comment]
Floodlight needed power cycled.

**Comment by dgreif** [comment]
Awesome, glad you got it figured out!
