### ISSUE TITLE
Ring Doorbell wired : Not able to hear to voice from doorbell

### ISSUE THREAD

**Issue by benoitvinc** [dgreif/ring#723]
Hi there !

thank you for the great plugin an support. I'm getting the following issue :
When doing Two Way Talk via the HomeKit app, I can talk and be heard trough the doorbell, however I cannot hear when people are talking, i only hear white noise. 

Environment

Ring Camera: Video Doorbell wired
OS: Headless Raspbian
Node.js: 14.16.0
NPM: 6.14.11
homebridge-ring 9.19.0
hoobs 3.3.5
Network Environment
Homebridge server is a Raspberry Pi 2 (B) and is connected via ethernet.

**Comment by dgreif** [comment]
I think Ring cuts audio from the mic on the doorbell when you talk from your phone. This would make sense to avoid feedback. Unfortunately there is nothing I can do to fix this.
