### ISSUE TITLE
Ring Alarm Bypass mode Night

### ISSUE THREAD

**Issue by DavidWhicker** [dgreif/ring#726]
When using home app to arm alarm into NIGHT mode which is set to enable bypassing automatically if any contact sensor is open the tile gets stuck on 'arming'.

The alarm is successfully armed but the tile doesn't update. 

Plug-in and homebridge is up to date.

**Comment by dgreif** [comment]
This was already reported in #545, but I appreciate you bringing it up again.  Should be fixed in v`9.21.0`.
