### ISSUE TITLE
Issue with 9.20.0

### ISSUE THREAD

**Issue by searay345** [dgreif/ring#727]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...Ok I have to admit I don't know what the problem is. I had no control over any ring products in HomeKit Hone App. Reverting back to 9.19.0 fixed the issue. The weird thing is I was running 9.20.0 for a while without issue and at midnight everything stopped responding. After multiple reboots of the Pi 4, a dedicated Hoobs install, nothing worked. I even rebooted my network just to make sure. Also didn't work. So I reverted back to 9.19.0 and it immediately worked. 

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
Ring is having issues with a number of their services. All the issues started last night, which lines up with when you started having issues. Please try upgrading to the latest version again and everything should hopefully work just fine

**Comment by searay345** [comment]
> Ring is having issues with a number of their services. All the issues started last night, which lines up with when you started having issues. Please try upgrading to the latest version again and everything should hopefully work just fine

Thank you @dgreif  I just upgraded to 9.20.0 and it's working now. Interesting. I wonder why downgrading worked immediately last night. Unless the services were restored in the middle of the downgrade. Talk about timing in that case. Thank you. I'll keep an eye on it throughout the day.
