### ISSUE TITLE
Error code 404

### ISSUE THREAD

**Issue by wildman199** [dgreif/ring#729]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by wildman199** [comment]
I have tried token refresh. Ring still not working at all. getting error code 404

**Comment by wildman199** [comment]
![Screen Shot 2021-08-08 at 1 47 43 AM](https://user-images.githubusercontent.com/48616222/128622346-43b706fb-05e2-4a0e-8331-d767bd79735a.png)

**Comment by wildman199** [comment]
![Screen Shot 2021-08-08 at 1 48 26 AM](https://user-images.githubusercontent.com/48616222/128622356-10908fec-216c-4a53-abb7-ad619dda30fd.png)

**Comment by wildman199** [comment]
![Screen Shot 2021-08-08 at 1 48 43 AM](https://user-images.githubusercontent.com/48616222/128622359-34730b74-48a9-42dc-b083-04e1f5e2db6e.png)

**Comment by wildman199** [comment]
![Screen Shot 2021-08-08 at 1 49 04 AM](https://user-images.githubusercontent.com/48616222/128622371-a274e711-f156-4bbb-8dbe-feda4fc3d5d9.png)

**Comment by wildman199** [comment]
![Screen Shot 2021-08-08 at 1 50 19 AM](https://user-images.githubusercontent.com/48616222/128622382-67a68a46-5af2-438e-a802-90d86a138a84.png)

**Comment by dgreif** [comment]
This issue was fixed in one of the recent versions. Please update the plugin and try again
