### ISSUE TITLE
Sharp wont install on rasp pi?

### ISSUE THREAD

**Issue by SafariKC** [dgreif/ring#73]
> sharp@0.22.1 install /usr/local/lib/node_modules/homebridge-ring/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

ERR! sharp EACCES: permission denied, mkdir '/root/.npm'
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-ring/node_modules/sharp/build'
gyp ERR! System Linux 4.19.50-v7l+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-ring/node_modules/sharp
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-21T18_02_43_909Z-debug.log

**Comment by SafariKC** [comment]
Looks like sharp was added in 4.2.2 and is having trouble on the pi.  I troubleshot for a while and got nowhere wondering if I’m alone or not.   Fell back to 4.2.1

**Comment by waltersobchak40** [comment]
Same error on macOS. I reverted back to 4.2.1 as well.

**Comment by metroidmen** [comment]
Oh wow. I thought I messed up something and ended up reformatted my entire homebridge. 

But eventually 4.2.2 did install.

**Comment by cargueta001** [comment]
I too am going through the same thing and tried reinstalling from scratch to no luck.

@waltersobchak40 @SafariKC What steps did you take to revert back to version 4.2.1? At this point, I have no build installed.

**Comment by waltersobchak40** [comment]
@cargueta001 I installed a specific version of 4.2.1 on macOS:

`sudo npm install -g homebridge-ring@4.2.1`

**Comment by cargueta001** [comment]
@waltersobchak40 I tried that command line via Terminal for my RPI but when I rebooted Homebridge, the plugin won't appear 🤷🏻‍♂️

**Comment by dgreif** [comment]
Hey sorry for the headache everyone. I’ll take a look at some alternative libraries so we can drop the node gyp requirement. I’ll try to get an update out this afternoon or tomorrow morning at the latest. Anyone having issues installing should just hold off until then.

**Comment by dgreif** [comment]
I tried several other packages (`jimp`, `imagejs`, `image-js`) and they were all poor compared to `sharp`.  For comparison, `sharp` took ~37ms and reduced the image size by 95%.  `image-js` took ~363ms and only reduced the image size by 65%.  The other libraries performed even worse.  I really really don't want to have node-gyp install issues because it will be a never ending stream of Github issues about not being able to install the plugin.  At this point, I'm just going to revert snapshot resizing and use the original image size that we receive from Ring 😞.  If anyone knows of a different image processing library that is pure node and performs resizes quickly, please let me know.
