### ISSUE TITLE
Actions on ring doorbell fail intermittently

### ISSUE THREAD

**Issue by TristanBrotherton** [dgreif/ring#731]
# Bug Report

### Describe the Bug
Assigning an action to the ring doorbell button press will work sometimes and then fail intermittently. No error is shown in homebridge log

### To Reproduce

Add an action on single press of ring doorbell. IE turn on a smart plug.

### Expected behavior
Action should be initialized on button press 

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config

```

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
Are you getting doorbell press events from that camera? If so, do you get the notifications consistently, or do they seem to fail when the automation fails?

**Comment by TristanBrotherton** [comment]
Should I be able to see that in the generic homebridge log? If so I am not seeing the notifications for it.

**Comment by dgreif** [comment]
I can't reproduce this.  Do you happen to have the `sendDoorbellMotionNotificationsToTv` setting on?  If so, please note that motion detection will not turn on the doorbell stateless switch.  Only _real_ doorbell presses

**Comment by TristanBrotherton** [comment]
I do not have that on. My hunch is that tvOS 15 may have introduced instability. I've turned on extra logging to try and get more information.

**Comment by dgreif** [comment]
@TristanBrotherton any updates?
