### ISSUE TITLE
Cannot update ring plugin

### ISSUE THREAD

**Issue by sdorilas** [dgreif/ring#739]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 - Start Homebridge
 - Attempt to ...update homebridge-ring plugin
 - See error:
 USER: pi
n
•DIR:
/usr/local
CMD: sudo
-E
-n pm install
-g homebridge-ring@latest
npm ERRI
code ENOTEMPTY
npm ERRI
syscall rename
pm ERR! path /usr/local/lib/node modules/homebridge-
ring
npm ERR! dest
/usr/local/lib/node modules/.homebridge
-ring-rVzgYZG4
npm ERRI
errno
-39
npm ERRI
ENOTEMPTY:
directory not empty,
/local/lib/node modules/homebridge-ring
rename
" /usr
_>
"/usr/loc
al/lib/node modules/.homebridge-ring-rVzgYZG4
pm ERR! A complete log of this run
can be found in:
nom ERRI
/home/pi/.npm/ logs/2021-08-15T12 31 44
356z-debug. log

### Expected behavior
 Would expect plug-in to update. 

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_

```

    "refreshToken": "xxxxxx ",
            "alarmOnEntryDelay": true,
            "hideDoorbellSwitch": true,
            "hideCameraMotionSensor": false,
            "hideInHomeDoorbellSwitch": true,
            "hideUnsupportedServices": true,
            "nightModeBypassFor": "some",
            "platform": "Ring"
        },

```

### Environment

 - OS: Raspbian 
 - Node.js: v14.16.0
 - NPM: 7.6.1
 - homebridge-ring: v9.18.0
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: n/a

**Comment by dgreif** [comment]
This usually indicates an issue with your local npm setup. Try updating npm first and the. Updating the plugin again.  npm i -g npm@7

**Comment by sdorilas** [comment]
Thank you for your response. I ran the update command provided, still 7.6.1 and same error.

**Comment by sdorilas** [comment]
> This usually indicates an issue with your local npm setup. Try updating npm first and the. Updating the plugin again. npm i -g npm@7

Any other recommendations?

**Comment by dgreif** [comment]
Try this command

npm cache clean --force

Then update again

**Comment by sdorilas** [comment]
Thank you for response. Ran command, updated to mom 7.22.0. Same error message.

Kind regards,

Stephane D.

**Comment by dgreif** [comment]
Try running `rm -rf /local/lib/node modules/homebridge-ring`.  It looks like npm is unhappy because that directory already exists

**Comment by sdorilas** [comment]
Ran that then updated again:

USER•
pi
DIR:
/usr/local
CMD:
sudo
-E
-n npm install
-g homebrid
***@***.***
pm ERR! code ENOTEMPTY
npm ERR! syscall rename
nom ERR! path /usr/local/lib/node modul
npm
es/homebridge-ring
nom ERR! dest /usr/local/lib/node modul
es/
•homebridge-ring-rVzgYZG4
nom ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty
rename
'/usr/local/lib/node
modules/h
omebridge-ring
_>
'/usr/local/lib/node
modules/.homebridge-ring-rVzgyzG4'
pm ERR! A complete log of this run can

Kind regards,

Stephane D.

**Comment by dgreif** [comment]
Try `rm -rf /usr/local/lib/node
modules/.homebridge-ring-rVzgyzG4`

**Comment by sdorilas** [comment]
Tried it. Doesn’t seem to remove the directory. Same error after running, and attempting to update plugin.

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-ring
npm ERR! dest /usr/local/lib/node_modules/.homebridge-ring-rVzgYZG4
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-ring' -> '/usr/local/lib/node_modules/.homebridge-ring-rVzgYZG4'

npm ERR! A complete log of this run can be found in:
npm ERR! /home/pi/.npm/_logs/2021-09-06T22_24_54_635Z-debug.log

Kind regards,

Stephane D.

**Comment by dgreif** [comment]
Try adding `sudo` on the front - `sudo rm -rf /usr/local/lib/node modules/.homebridge-ring-rVzgyzG4`
