### ISSUE TITLE
Live Feeds - Well Done!

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#74]
@dgreif I have updated to this version, but I get no response on all cameras, but sounds like progress?

**Comment by jahnkenneth** [comment]
Same here :-( Ring pro doorbell

**Comment by EarthRise626** [comment]
What version of iOS are you both on? Also, are you using an iPhone or an iPad to attempt to view the live stream?

**Comment by adavison007** [comment]
Using latest version  of iOS and also macOS, neither work, snaps shots do, just not live stream

**Comment by jahnkenneth** [comment]
My iPhone is on iOS 13, and my iPad is on 12. 
Not working on any if them. :-(

**Comment by jahnkenneth** [comment]
Got it working now on my iPad. Took 26 seconds... But only got it working this one time...
On my iPhone (iOS 13) it goes directly to «not responding»...

**Comment by ifeign** [comment]
I had to restart my phone before it started working.

**Comment by adavison007** [comment]
@ifeign no joy doing that on mac or iPhone

**Comment by BradMcGonigle** [comment]
I had to remove the camera from HomeKit and then re-add it and it started working.

- iOS 13 beta 4
- Doorbell Pro (lpd_v2)

**Comment by adavison007** [comment]
> I had to remove the camera from HomeKit and then re-add it and it started working.
> 
> * iOS 13 beta 4
> * Doorbell Pro (lpd_v2)

@BradMcGonigle  So I just remove the camera, but can add it again? do i need to flush the accessory cache first?

**Comment by BradMcGonigle** [comment]
> So I just remove the camera, but can add it again? do i need to flush the accessory cache first?

I just removed it in the Home app and added it again.  That worked for me.  Hopefully it works for you too.

**Comment by adavison007** [comment]
@dgreif so i removed a camera to then try and re add it to get live stream working... when adding an accessory the camera does not reappear? any ideas? I also deleted Accesorries file and that did not work either?

**Comment by ifeign** [comment]
Not sure why people keep removing their cameras. All I had to do was
restart my phone.

**Comment by mikesalz** [comment]
Mine also did not work at first, but after a phone restart it is working perfectly!  Thank you for the amazing work, and for doing what Ring couldn't do on their own in the 3 years since they announced HomeKit compatibility!

**Comment by dgreif** [comment]
Glad to hear live streams are working for some of you.  I also had issues at first, but restarting my phone and homebridge seemed to fix the issue.  I have noticed that the _first_ live stream can take a while to start. It almost seems like HomeKit needs to set up the stuff on their end to receive the stream and it takes a long time to do it.

One important factor on performance will be your network setup.  The streams go from your camera, up to Rings servers, then down to your homebridge server (rpi or whatever you are running it on), and then to either your phone, computer, or AppleTV/HomePod if you are not at home.  This means that you need to have the best network speed you can between all of those jumps.  For example, I connected my rpi to ethernet this morning instead of wifi and it seemed to make a big difference.  The nice thing about the way I have everything flowing is that we don't need to re-encode the audio/video.  Homebridge is simply passing along the raw UDP packets, so it's all about network speed and not CPU.

While my live streams are now working great, I have noticed that snapshots seem to be almost completely missing on my phone.  My guess is that this is an iOS 13 issue (I'm on the beta currently) as homebridge isn't receiving the _requests_ for snapshots at all.  When they are requested, they still work as well as they did before live streams.

**Comment by adavison007** [comment]
Is anyone using the 2FA refresh token? I am and i'm not getting live feeds... I'm wondering if that is the cause?

**Comment by dgreif** [comment]
@adavison007 I am using the refresh token and it works just fine

**Comment by Sunoo** [comment]
I have the iOS 13 beta, and I have the plugin using the refresh token. It doesn't work for me, but what happens is it clocks for a while, then I get like one frame from the camera, and it is immediately greyed out saying camera not responding. I've tried readding the camera and rebooting all devices, no change.

**Comment by adavison007** [comment]
> @adavison007 I am using the refresh token and it works just fine

@dgreif so I desalted all cameras, then deleted the plugin, then cleared the accessory cache and restarted home bridge. I then reinstalled your plugin and re did the JSON file, and now i can't add any cameras, ideas?

**Comment by ifeign** [comment]
Did you remember to manually add back the cameras by searching for nearby
accessories?

**Comment by adavison007** [comment]
> Did you remember to manually add back the cameras by searching for nearby accessories?
> […](#)

yep, add accessory, no code and nothing...

**Comment by dgreif** [comment]
@adavison007 the cameras are cached in `~/.homebridge/persist` instead `~/.homebridge/accessories`.  See https://github.com/dgreif/ring/issues/41#issuecomment-505609919 for details on how to clean it up.

**Comment by EarthRise626** [comment]
@dgreif I am on iOS 13 on my phone as well. The camera snapshots within the Home app are working great and updating frequently enough. I haven’t received any motion notifications yet so can’t speak as to whether or not a snapshot will appear in the notification. 

@adavison007 I am using the refresh token with no issues as well.

**Comment by adavison007** [comment]
> @adavison007 the cameras are cached in `~/.homebridge/persist` instead `~/.homebridge/accessories`. See [#41 (comment)](https://github.com/dgreif/ring/issues/41#issuecomment-505609919) for details on how to clean it up.

BOOM! You're a star

**Comment by divemasterjm** [comment]
Just reboot iPhone and works!!! Thanks dgreif!!!!

**Comment by onefish2** [comment]
I am not getting the live feed. I have a Video Doorbell 2 and Floodlight Cam. This is what I see in the logs:

[7/27/2019, 5:49:40 AM] [Ring] Snapshot Requested for Driveway
[7/27/2019, 5:49:40 AM] [Ring] Snapshot Requested for Front Door
[7/27/2019, 5:49:43 AM] [Ring] Preparing Live Stream for Driveway
[7/27/2019, 5:49:45 AM] [Ring] Waiting for stream data from Driveway
[7/27/2019, 5:49:54 AM] [Ring] Stopped Live Stream for Driveway
[7/27/2019, 5:49:56 AM] [Ring] Snapshot Requested for Front Door
[7/27/2019, 5:49:56 AM] [Ring] Snapshot Requested for Driveway

I have 2FA enabled. I just got a new token. Pasted that into the config.json and rebooted. And I still get the same error.

Yesterday I removed the cameras than added them back in. Any ides?

**Comment by adavison007** [comment]
@dgreif OK, so I deleted a camera yesterday, I followed your instructions and removed them from Persist... I then re added them all, they all added and worked apart from a Flood Light Cam (only one I have)..... so I took the opportunity to WIPE MY HOMEBRIDGE and start again whilst moving from the old RPI3 to RPI4... so complete new install..... all fresh... can add everything again, but that Flood Light cam shows, but no snapshots, can turn light on and can't see motion sensor triggering in homekit... is there an issue with floodlights cams with your new code? also side note... live stream still not working on complete new install (using hoobs)

**Comment by adavison007** [comment]
> @dgreif OK, so I deleted a camera yesterday, I followed your instructions and removed them from Persist... I then re added them all, they all added and worked apart from a Flood Light Cam (only one I have)..... so I took the opportunity to WIPE MY HOMEBRIDGE and start again whilst moving from the old RPI3 to RPI4... so complete new install..... all fresh... can add everything again, but that Flood Light cam shows, but no snapshots, can turn light on and can't see motion sensor triggering in homekit... is there an issue with floodlights cams with your new code? also side note... live stream still not working on complete new install (using hoobs)

HERE IS THE LOG, GARDEN IS THE FLOOD LIGHT CAM NOT WORKING>>> (I XXXX the code)

[7/27/2019, 1:05:15 PM] [Ring] Configuring 11 cameras and 0 devices for locationId gcpkpc-gdlu-0
[7/27/2019, 1:05:15 PM] [Ring] Adding new accessory lpd_v2 Gate
[7/27/2019, 1:05:15 PM] [Ring] Adding new accessory doorbell_v3 Side Gate
[7/27/2019, 1:05:15 PM] [Ring] Adding new accessory doorbell_v4 Front Door
[7/27/2019, 1:05:15 PM] [Ring] Adding new accessory stickup_cam_elite Lounge
[7/27/2019, 1:05:15 PM] [Ring] Adding new accessory stickup_cam_elite Dining Room
[7/27/2019, 1:05:15 PM] [Ring] Adding new accessory stickup_cam_v3 Den
[7/27/2019, 1:05:15 PM] [Ring] Adding new accessory stickup_cam_v3 Study
[7/27/2019, 1:05:15 PM] [Ring] Adding new accessory hp_cam_v2 Patio
[7/27/2019, 1:05:15 PM] [Ring] Adding new accessory stickup_cam_elite Kitchen
[7/27/2019, 1:05:15 PM] [Ring] Adding new accessory hp_cam_v1 Garden
[7/27/2019, 1:05:15 PM] [Ring] Adding new accessory stickup_cam_elite Hallway
[7/27/2019, 1:05:15 PM] Gate is running on port 32905.
[7/27/2019, 1:05:15 PM] Please add [Gate] manually in Home app. Setup Code: XXXXXXX
[7/27/2019, 1:05:15 PM] Side Gate is running on port 34119.
[7/27/2019, 1:05:15 PM] Please add [Side Gate] manually in Home app. Setup Code:  XXXXXXX
[7/27/2019, 1:05:15 PM] Front Door is running on port 34873.
[7/27/2019, 1:05:15 PM] Please add [Front Door] manually in Home app. Setup Code:  XXXXXXX
[7/27/2019, 1:05:15 PM] Lounge is running on port 35279.
[7/27/2019, 1:05:15 PM] Please add [Lounge] manually in Home app. Setup Code:  XXXXXXX
[7/27/2019, 1:05:15 PM] Dining Room is running on port 33757.
[7/27/2019, 1:05:15 PM] Please add [Dining Room] manually in Home app. Setup Code:  XXXXXXX
[7/27/2019, 1:05:15 PM] Den is running on port 44407.
[7/27/2019, 1:05:15 PM] Please add [Den] manually in Home app. Setup Code:  XXXXXXX
[7/27/2019, 1:05:15 PM] Study is running on port 43457.
[7/27/2019, 1:05:15 PM] Please add [Study] manually in Home app. Setup Code:  XXXXXXX
[7/27/2019, 1:05:15 PM] Patio is running on port 39165.
[7/27/2019, 1:05:15 PM] Please add [Patio] manually in Home app. Setup Code:  XXXXXXX
[7/27/2019, 1:05:15 PM] Kitchen is running on port 37557.
[7/27/2019, 1:05:15 PM] Please add [Kitchen] manually in Home app. Setup Code:  XXXXXXX
[7/27/2019, 1:05:15 PM] Garden is running on port 42315.
[7/27/2019, 1:05:15 PM] Please add [Garden] manually in Home app. Setup Code:  XXXXXXX
[7/27/2019, 1:05:15 PM] Hallway is running on port 41195.
[7/27/2019, 1:05:15 PM] Please add [Hallway] manually in Home app. Setup Code:  XXXXXXX
[7/27/2019, 1:05:20 PM] [Ring] Snapshot Requested for Kitchen
[7/27/2019, 1:05:20 PM] [Ring] Snapshot Requested for Patio
[7/27/2019, 1:05:58 PM] [Ring] Snapshot Requested for Kitchen
[7/27/2019, 1:05:58 PM] [Ring] Snapshot Requested for Garden
[7/27/2019, 1:05:58 PM] [Ring] Snapshot Requested for Patio
[7/27/2019, 1:05:58 PM] [Ring] Snapshot Requested for Gate
[7/27/2019, 1:05:58 PM] [Ring] Snapshot Requested for Front Door
[7/27/2019, 1:06:09 PM] [Ring] Snapshot Requested for Front Door
[7/27/2019, 1:06:11 PM] [Ring] Snapshot Requested for Kitchen
[7/27/2019, 1:06:12 PM] [Ring] Snapshot Requested for Gate
[7/27/2019, 1:06:13 PM] [Ring] Snapshot Requested for Patio
[7/27/2019, 1:06:19 PM] [Ring] Snapshot Requested for Front Door
[7/27/2019, 1:06:22 PM] [Ring] Snapshot Requested for Kitchen
[7/27/2019, 1:06:23 PM] [Ring] Snapshot Requested for Gate
[7/27/2019, 1:06:24 PM] [Ring] Snapshot Requested for Patio
[7/27/2019, 1:06:30 PM] [Ring] Snapshot Requested for Front Door
[7/27/2019, 1:06:33 PM] [Ring] Snapshot Requested for Kitchen
[7/27/2019, 1:06:34 PM] [Ring] Snapshot Requested for Gate
[7/27/2019, 1:06:35 PM] [Ring] Snapshot Requested for Patio
[7/27/2019, 1:06:40 PM] [Ring] Snapshot Requested for Front Door
[7/27/2019, 1:06:44 PM] [Ring] Preparing Live Stream for Gate
[7/27/2019, 1:06:46 PM] [Ring] Waiting for stream data from Gate
[7/27/2019, 1:06:55 PM] [Ring] Stopped Live Stream for Gate
[7/27/2019, 1:06:59 PM] [Ring] Snapshot Requested for Front Door
[7/27/2019, 1:06:59 PM] [Ring] Snapshot Requested for Kitchen
[7/27/2019, 1:06:59 PM] [Ring] Snapshot Requested for Gate
[7/27/2019, 1:06:59 PM] [Ring] Snapshot Requested for Patio
[7/27/2019, 1:07:00 PM] [Ring] Snapshot Requested for Garden
[7/27/2019, 1:08:00 PM] [Ring] Preparing Live Stream for Garden
[7/27/2019, 1:08:11 PM] [Ring] Snapshot Requested for Garden
[7/27/2019, 1:08:11 PM] [Ring] Snapshot Requested for Front Door
[7/27/2019, 1:08:12 PM] [Ring] Snapshot Requested for Patio
[7/27/2019, 1:08:12 PM] [Ring] Snapshot Requested for Kitchen
[7/27/2019, 1:08:12 PM] [Ring] Snapshot Requested for Gate

**Comment by dgreif** [comment]
@onefish2 it looks like the stream data from Ring is unable to reach your homebridge server.  This can happen if your network is fairly complex, particularly with complex NAT structures.  As my current approach seems to be working for most users, I would say it is probably specific to your network 😞.  You can try some basic steps like rebooting your router/homebridge server/HomeKit hub/phone, but if the problem is still present then there is not much I can do to help.

@adavison007 floodlight cameras should work just fine (I have 2 of them).  It looks like there is some error during live stream prep, but it's not being logged in the version you are on.  Try updating to v`4.3.2` which has a little more logging and send me the new logs.  Everything after `Preparing Live Stream...` is what matters.  Snapshots look like they are being requested, so I'm not sure why they wouldn't show up.  Maybe reboot your apple tv (if that is your HomeKit hub).

**Comment by ifeign** [comment]
@dgreif I think it would be wise to include in the readme a message to restart iOS devices and home hubs if upgrading to a version with live streaming. Streaming was very unreliable for me until I restarted my Apple TV. That would probably reduce the amount of people reporting their connection issues

**Comment by onefish2** [comment]
@dgreif Here is my setup. homebridge is running a Pi4 Buster with a static IP connected to an 8 port switch that connects to an Apple Airport Extreme. All software is up to date. Node.JS version is 10.16.0 The homebridge instance is newly installed. I have 3 Apple TVs as HomeKit hubs. They are on IOS13 beta. I have an iPad Pro that is on IOS 12 as another Homekit hub. 

I have 2FA on and used your CLI tool this morning to get a new token.
I have 2 ring devices. One is a Floodlight Cam the other is a Video doorbell 2. This are working properly. They show up in the Ring app with a live stream no problem. I rebooted the Floodlight Cam yesterday.

I rebooted the switch, the Apple TVs, the iPad, Airport Extremes, the Pi and my iPhone wich is a XS MAx on IOS 12.

I still do not get a live stream. I just wanted to inform you of my trouble shooting. I was very excited to see your updates this past week and I am enjoying seeing the Ring devices in HomeKit. I just wish I could get the streaming to work. Thanks for your hard work on this!!

**Comment by danewallace** [comment]
Jumping in with some (hopefully helpful) log information. 

Context: I originally was able to see Live Stream without issue on macOS, iOS 13 b4, and iOS 12.4. However, I after uninstalling node, homebridge, and all plugins for other unrelated reasons, I am unable to get live stream to work. 

Ring works, snapshots work, but live stream fails. Strangely, activity log typically shows normal activity even if the stream fails. e.g.:
`[7/27/2019, 3:57:11 PM] [Ring] Preparing Live Stream for Yard
[7/27/2019, 3:57:15 PM] [Ring] Waiting for stream data from Yard
[7/27/2019, 3:57:16 PM] [Ring] Received stream data from Yard
[7/27/2019, 3:57:16 PM] [Ring] Streaming active for Yard
[7/27/2019, 3:57:35 PM] [Ring] Stopped Live Stream for Yard`

During one particular attempt I was able to get this output:
`[7/27/2019, 3:38:21 PM] [Ring] Failed to prepare stream for Front Door
[7/27/2019, 3:38:21 PM] [Ring] Error: sip INVITE request failed with status 408
    at failWithMessage (/Users/danewallace/.nvm/versions/node/v12.7.0/lib/node_modules/homebridge-ring/lib/api/sip-session.js:99:24)
    at /Users/danewallace/.nvm/versions/node/v12.7.0/lib/node_modules/homebridge-ring/lib/api/sip-session.js:116:21
    at searching (/Users/danewallace/.nvm/versions/node/v12.7.0/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:1313:5)
    at /Users/danewallace/.nvm/versions/node/v12.7.0/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:1294:41
    at Timeout.<anonymous> (/Users/danewallace/.nvm/versions/node/v12.7.0/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:1091:9)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)`

Hope this helps troubleshooting. Really appreciate the work you're doing.

**Comment by mikesalz** [comment]
This is probably already be a known issue, but throwing it out there just in case... I am able to see the thumbnail and click though to live video.  But after the live video streams for about 30-60 seconds, it goes to No Response.

**Comment by ifeign** [comment]
This time limit is known already. @dgreif is trying to figure out how to
keep the connection awake

**Comment by metroidmen** [comment]
My live streams were working last night but haven’t worked all day here. Tried the new update and restarting the homebridge and my router and my phone. Nothing. 😕

**Comment by jianyu-li** [comment]
Kudos to @dgreif , my cameras load faster in live view than in Ring’s own app. No problems yet over here. Cheers!

**Comment by onefish2** [comment]
Those of you with the live stream working, could you post what your platform config looks like from you config.json.

Here is mine. I am wondering if the last two lines are needed and if the time of 2 seconds and 20 seconds are ok.

"platform": "Ring",
            "email": "my.email@xyz.com",
            "password": "password",
            "hideDoorbellSwitch": true,
            "hideCameraSirenSwitch": true,
            "hideCameraMotionSensor": false,
            "cameraStatusPollingSeconds": 20,
            "cameraDingsPollingSeconds": 2

**Comment by dgreif** [comment]
@onefish2 there isn't anything special that you need to do in your config.  If you are still having issues, it is most likely network related.  A lot of people have needed to restart homebridge/HomeKit Hub (apple tv/ipad) and phone to get streams working.

**Comment by onefish2** [comment]
I have rebooted my Apple TVs, iPhone, Router, pi running homebridge. Everything. I do not have a complicated network setup. My Pi has a static IP and is connected via Ethernet. I do not know why this will not work. The live stream comes right up in the Ring app.

**Comment by jianyu-li** [comment]
@onefish2 have you tried removing the cameras and re-adding? I’ve read that’s helped others in this thread

**Comment by onefish2** [comment]
@jianyu-li, pls see above... My comment from July 27th. I have done just about everything possible.

**Comment by dgreif** [comment]
@ifeign I took your advice and put together a wiki with all of the troubleshooting steps that have worked so far: https://github.com/dgreif/ring/wiki/Camera-Troubleshooting.  I would appreciate a couple proof-reads from anyone who has been following the live streaming threads in case I missed anything.

@onefish2 @metroidmen @adavison007 it looks like you are all getting stuck at the `Waiting for stream` step.  This means the plugin successfully negotiated the call with the Ring servers, but your homebridge server has not received any data from the live stream.  This is probably something with your network (router/ISP) blocking access for that incoming data.  I will try to find a way to get those ports open more reliably, but I think I'm already doing everything that I need to do.  Unfortunately some networks are just more difficult to get streaming data into than others. 

@danewallace your logs look normal and everything should be working.  The only possible blocker is if your network isn't allowing some traffic between your HomeKit hub and your homebridge server.  Beyond that, I would try following the steps in the [troubleshooting guide](https://github.com/dgreif/ring/wiki/Camera-Troubleshooting).

**Comment by ifeign** [comment]
@dgreif the wiki looks good. I wonder if there's one final step that people
should check - their Ring subscription, I'm assuming this doesn't work
unless you have a paid subscription? Or is that not relevant?

**Comment by danewallace** [comment]
Restarting all Home hubs appears to have resolved the issue with logs showing normal traffic but Home.app still not showing live steam.

**Comment by dgreif** [comment]
@ifeign great suggestion, I've added another step to check your subscription in the wiki

@danewallace I'm not sure what else to suggest for troubleshooting. I think it's something on your network blocking the traffic between the devices if you are seeing all the correct logs (all the way up to `Streaming active for camera`...

I am going to close out this thread as I think it has served its purpose for the initial phase of troubleshooting and bug fixes.  For those of you who are still having issues, I haven't forgotten you, but I'm not sure what else I can do to help troubleshoot at this point.  I will continue to investigate ways to more reliably open the ports for streaming from the Ring servers, but I can't make any promises that I will find a better way.  If you have a specific error in your logs, or have done some debugging on your own and think you have found a bug in the code, please open another GitHub issue. 

Thanks everyone for the feedback and support in getting live streams launched!!

**Comment by Frederik840** [comment]
> @jianyu-li, pls see above... My comment from July 27th. I have done just about everything possible.

I noticed you mentioning that you use the AirPort Extreme, is that also your router? I’ve put in the local IP address of my RPI as Standard Host and that fixed the problem for me.

**Comment by onefish2** [comment]
@Frederik840, AMAZING!!! That was it. I added the IP of my Pi to be in the DMZ or in Apple terms "enable the default host at:"

I restarted the homebridge service and rebooted my Apple TV hub and Phone... And it works!!! @dgreif, please add this tip to your wiki.

**Comment by onefish2** [comment]
I am not too happy about having homebridge on my Pi exposed to the Internet but for now it works!!!

**Comment by dgreif** [comment]
@Frederik840 @onefish2 really glad you guys got this working! I'm not 100% clear on what you had to do to get it working since I don't have an AirPort Extreme.  Would one of you mind updating the wiki with some clear steps for users with that router?

**Comment by onefish2** [comment]
@dgreif, I will add that info later today. As I mentioned in the comments above, in the config for Apple networking products there is an option to add 1 host on your network to the DMZ so that its on the Internet instead of behind NAT on the router. Apple calls this option "enable the default host at:" and that is where you have the option to add in the IP for the host you want in the DMZ.

**Comment by dgreif** [comment]
I just read up on it a little bit and it does seem a little dangerous.  SSH and other ports will all be open to the outside.  This will definitely be a problem if you are running homebridge with the `-I` flag because anyone could control your homebridge devices from the outside world with no authentication.  _Maybe_ we shouldn't add this one to the wiki 😬

**Comment by Sunoo** [comment]
If we can figure out which ports are needed, we can open just those to the Homebridge instance. Any idea how to determine those?

**Comment by Frederik840** [comment]
Agreed, i’ve Created a separate Pi with all other things disabled. Agree with Sunoo that opening the specific ports would be best, but not sure how to work that out.

**Comment by Sunoo** [comment]
For what it's worth, I also have an Airport (the latest Time Capsule), and this also solved my problem.

**Comment by dgreif** [comment]
My current approach lets node grab a random open port, which could be anything (I think it's usually in the 50k range).  I'll try adding an option where you could specify a port range for the camera feeds to use.  The downside is that it creates race conditions when binding to the ports, but I should be able to work around those...will probably have an update out for this next week some time.  Thanks for all the info!!

**Comment by Sunoo** [comment]
If it's the 50,000 range, I could just open 50,000-59,999, which would be much better than DMZing it.

**Comment by adavison007** [comment]
> > @jianyu-li, pls see above... My comment from July 27th. I have done just about everything possible.
> 
> I noticed you mentioning that you use the AirPort Extreme, is that also your router? I’ve put in the local IP address of my RPI as Standard Host and that fixed the problem for me.

I literally just changed from using my Airport extreme as my router (Virgin Media Super hub in modem mode) and have added a Peplink unit in as my router  instead (This gives me Internet via Virgin and a backup Cell connection automatically if the WAN goes down via Vodafone)... anyway.. my point is with the Airport as the router I could not get live streams, now with airports in "bridge mode" and using the Peplink HD2 as a router live streams works... so Apple's simplicity probably is breaking something for live streams... I had the same issue with Sky Q, Airport could not deal with it and Sky Q boxes would not work, but with Peplink they do...

Hope this helps

**Comment by mikesalz** [comment]
My live feed works great, but I noticed there is no sound.  Is that a Ring limitation?

**Comment by ifeign** [comment]
This is mentioned in the wiki. Audio is not supported yet.

**Comment by dgreif** [comment]
^ Opened a new issue specifically for Airport routers.  Almost everyone that was on my list of "still having issues" appears to have been using an Airport.  If anyone finds a good config option (other than DMZ) please post it on #87.

**Comment by metroidmen** [comment]
I’m still having issues and don’t have an airport router. Have all my ports forwarded too.
