### ISSUE TITLE
[Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...

### ISSUE THREAD

**Issue by shayweiss** [dgreif/ring#744]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...
I'm getting constant error in HomeBridge logs console about this exception. I've noticed there's another bug reported on a similar issue (https://github.com/dgreif/ring/issues/718), however that issue is about a Token Refresh and the error I'm getting is different
![image](https://user-images.githubusercontent.com/85425190/129856114-f2498db5-e4a5-4102-96c7-828ae776c841.png)

And also
![image](https://user-images.githubusercontent.com/85425190/129861343-c4356590-a2da-48f2-bb5b-4bfa328feba1.png)

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.
![image](https://user-images.githubusercontent.com/85425190/129855614-90bbde3e-d119-4f25-b91e-cb20b8cc8095.png)

Also
![image](https://user-images.githubusercontent.com/85425190/129861419-6613e611-d2d0-4684-86bd-6db6f7c3fc06.png)

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
The best I can tell, rings servers have been struggling the past few weeks. These errors indicate that they aren't replying to your requests within 20 seconds. There's nothing I can do to fix it in the plugin, so we'll just have to hope they get it figured out soon
