### ISSUE TITLE
Unable to install Ring Plugin v9.21.0

### ISSUE THREAD

**Issue by hnieder** [dgreif/ring#747]
# Bug Report

### Describe the Bug
 I'm relatively new to Hoobs and am attempting to install the Ring Plugin v9.21.0. After selecting Install to install the plugin on the Hoobs bridge an unexpected error occurs (see below). A notification pops up saying "Plugin Not Installed, unable to install homebridge-ring. View Logs". There are no log entries recorded for the event. 

### To Reproduce
 - Log into Hoobs
 - Go to the Plugin Library
 - Select Ring Plugin (certified)
 - Choose to install the plugin on the Hoobs bridge

### Expected behavior
 Plugin is installed.

### Screenshots/Logs
 
<img width="689" alt="Screen Shot 2021-08-23 at 10 24 32 AM" src="https://user-images.githubusercontent.com/89401349/130479127-063478e6-49db-420f-895f-72ad3f16b532.png">

YARN-ERROR.LOG Information:

Arguments: 
  /usr/bin/node /usr/lib/hoobsd/node_modules/yarn/bin/yarn.js add --unsafe-perm --ignore-engines homebridge-ring@latest hoobs-ring-sidecar

PATH: 
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Yarn version: 
  1.22.10

Node version: 
  14.17.5

Platform: 
  linux arm

Trace: 
  SyntaxError: /usr/local/share/.cache/yarn/v6/npm-rxjs-7.3.0-39fe4f3461dc1e50be1475b2b85a0a88c1e938c6-integrity/node_modules/rxjs/.yarn-m
etadata.json: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at /usr/lib/hoobsd/node_modules/yarn/lib/cli.js:1625:59
      at Generator.next (<anonymous>)
      at step (/usr/lib/hoobsd/node_modules/yarn/lib/cli.js:310:30)
      at /usr/lib/hoobsd/node_modules/yarn/lib/cli.js:321:13

npm manifest: 
  {
      "name": "plugins",
      "description": "HOOBS Plugins",
      "private": true,
      "dependencies": {
          "hap-nodejs": "^0.9.4",
          "homebridge-dummy": "^0.5.0",
          "homebridge-myq": "^2.6.5"
      }
  }

yarn manifest: 
  No manifest

:

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: Raspbian
 - Node.js: v14.17.5
 - NPM: v7.21.0
 - homebridge-ring: v9.21.0
 - homebridge: 1.3.4
 - hoobs: v4.0.100

**Comment by dgreif** [comment]
This is not an issue with the plugin, but with your install setup.  I suggest you install using npm instead of yarn.
