### ISSUE TITLE
Ring Mailbox Sensor

### ISSUE THREAD

**Issue by fratinize** [dgreif/ring#749]
# Feature Request
Ring Mailbox sensor
### Description
 A clear and concise description of the problem or missing capability...
Not sure if I missed the answer but does the ring mailbox sensor work with this plugin ?
### Describe the solution you'd like
 If you have a solution in mind, please describe it.
Love to see it show as of until it is triggered. Option to adjust how long it remains triggered a way to reset immediately 
### Describe alternatives you've considered
Love this work
 Have you considered any alternative solutions or workarounds?
Looking for this option 
Thank you 
### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dgreif** [comment]
Yes, the mailbox sensor is supported by the plugin.
