### ISSUE TITLE
Ring Flood Light Cam Light button toggles on and off by itself

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#751]
Hi,

I have the Ring original and latest pro flood light cams, when you turn the light off using the exposed light button in homekit after a few seconds it quickly turns on and then off again by itself (this does not happen with the our door spot cam). 

The challenge is that I am using an automation from a smart switch (Lightwaverf) to turn the flood lights on from the wall switch. When the flood lights tile in homekit "toggles" on and off by itself, this causes a continuous issue with the automation as it thinks someone is turning it on and off, so the switch changes state, then the automation kicks in as it thinks the switch has been turned on and so on....

Any chance you are able to fix the code when you turn the Ring flood light off in homekit, the tile stays off and does not do it's quick on and off (which happens a few seconds after you turn it off). To confirm this only happens on the flood light cams, the spot light cams light tile works fine in homekit.

Thanks in advance as usual

**Comment by adavison007** [comment]
@dgreif Hope all is well, please can you take a look at the above for me? I am unable to control my flood lights from my smart switch due the the automation getting confused when the floodlight cam exposed switch in homekit "Flickers"  ? 

sorry to chase, but my wife if killing me.... 

Is there anyway the when I click the on/off light tile in homekit it can keep the state of on or off without it turning itself on and off quickly after being pressed?  I've added a video, I only touch the control once in this video to turn the switch on... you'll then see it turns off and on again to correct it state after a few seconds without me touching it.... this on/off it does by itself confuses the automation.  (It also does it the other way around when turning it off)


https://user-images.githubusercontent.com/47482260/131642159-5d2ab60e-42cf-4d27-b76e-3bf6b52bb5e6.mp4

**Comment by adavison007** [comment]
@dgreif Not sure if this helps... this appears when the light toggles..   
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/47482260/131836574-e9069097-7b4a-4b12-a36a-4514ca489de1.png">

**Comment by adavison007** [comment]
@dgreif I will donate £50 if you are able to fix this issue for me....

**Comment by dgreif** [comment]
@adavison007 give it a try in `9.21.1`.  It should resolve the toggling back and forth issue.  That 422 error you are seeing is interesting as well, and isn't something i've been able to replicate.  Would you mind sharing that camera with me for a few days?

**Comment by adavison007** [comment]
So far, so good, big thanks, Do you have a donate link? and I am happy to share the camera, but I need your email address,,, also, the error does not appear in the log since I did the update that fixes the toggle...

**Comment by dgreif** [comment]
Glad to hear it's working, and thanks for the donation! If you aren't seeing that error anymore, then no need to share the camera.  Let me know if it shows up again
