### ISSUE TITLE
Plugin failing to successfully change state? (Security System Target State warning)

### ISSUE THREAD

**Issue by solarbeat** [dgreif/ring#755]
# Bug Report

### Describe the Bug
Plugin intermittently fails to change the state of the alarm.

### To Reproduce
- Set to state A
- Set automation to change state to state B
- Trigger automation

### Expected behavior
- Successful change to state B

### Screenshots/Logs
 [9/1/2021, 7:05:40 AM] [homebridge-ring] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.

### Additional context
 For example, I have an automation set so it disarms the alarm upon detecting motion upstairs in the morning (night>disarmed). About 2-3 times in the past week, it failed to change to "disarmed"

Strangely enough (?) less than 30min later, even without restarting homebridge, it worked fine on a geo-fence triggered automation, no error or warning:

[9/1/2021, 7:27:16 AM] [Ring] Disarming Alarm

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

{
            "refreshToken": "xxx",
            "hideDoorbellSwitch": true,
            "platform": "Ring"
        },

```

### Environment

 - OS: MacOS 10.15.7
 - Node.js: 14.17.5
 - NPM: 6.14.14
 - homebridge-ring: 9.21.0
 - homebridge: 1.3.4
 - hoobs: N/A

**Comment by dgreif** [comment]
From what I can tell, you are actually _triggering_ your alarm when it detects the motion, and then immediately trying to disarm it via automation.  This actually caught a small corner case in the code, which should be fixed in the latest version
