### ISSUE TITLE
Camera streaming no longer works, logs show no attempt to stream

### ISSUE THREAD

**Issue by ifeign** [dgreif/ring#756]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...
After working fine for over a year, I suddenly can’t view my camera feeds. When attempting to stream, there’s no mention of them in the logs, though I do see motion detection mentioned. Everything works fine in the Ring app and E2E encryption Is not enabled.

I’ve restarted the Homebridge server and both of my Home hubs.

### To Reproduce
Attempt to view a camera feed

### Expected behavior
 A clear and concise description of what you expected to happen.
View live stream

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

   {
            "refreshToken": "",
            "hideCameraSirenSwitch": false,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "locationModePollingSeconds": 0,
            "locationIds": [
                "e318eb0d-187b-4b10-47e3-f33bd0838832"
            ],
            "_bridge": {
                "name": "Ring",
                "username": "",
                "port":
            },
            "platform": "Ring"
        },

```

### Environment

 - OS: Homebridge official image
 - Node.js: 14.17.6
 - NPM: 7.21.1
 - homebridge-ring: 9.21.1
 - homebridge: 1.3.4

**Comment by dgreif** [comment]
Did you restart your phone as well?  If it doesn't show an attempt, then something is probably wrong on the HomeKit side

**Comment by ifeign** [comment]
Yes, I’ve tried several devices. Unfortunately I’m out of town, otherwise I
would have tried removing and re-adding the Ring child bridge but I can’t
do that remotely. Guess it’ll have to wait til I get back.

**Comment by ifeign** [comment]
It was definitely a HomeKit issue. Suddenly everything works again, but my one native HKSV camera no longer has a timeline. Clearly my HomeKit setup has deeper issues. Anyway, not relevant to this plugin so I’m closing this.
