### ISSUE TITLE
cannot log into the ring plug in

### ISSUE THREAD

**Issue by jpcowell** [dgreif/ring#757]
# Bug Report

### Describe the Bug
 A clear and concise description of what you expected to happen.

### Additional context

 - OS: Hoobs in a box version 4.0.100
 - Node.js: 14.17.6
 - NPM: 6.14.15
 - ring-client-api: 9.21.0

**Comment by dgreif** [comment]
Sorry but there is not enough info here for me to provide any help. Maybe reach out to HOOBS support?

**Comment by mkellsy** [comment]
There should be a Link Account button on the config screen.
If there isn't one, go the the plugin page, then click on the versions tab.
Click on the latest tag, and select the current bridge it's installed on.
This will trigger a re-install including the UI plugin without affecting your current config.
