### ISSUE TITLE
Request - motion detect(sensor) on press 

### ISSUE THREAD

**Issue by djsmix** [dgreif/ring#761]
# Feature Request

### Description
Possibility to have motion detect sensor on doorbell press?
So it can be used for chime's/ring on sonos etc.

### Describe the solution you'd like
So when a person press the button, when it should detect "motion" so it can be used for automatizations

**Comment by dgreif** [comment]
There is already "Stateless Programmable Switch" exposed as an additional accessory under each doorbell.  It can be found in the accessories section next to the motion sensor.  When you open it up, it should have a "Single Press" section at the bottom which allows you to add automations on doorbell press.

**Comment by djsmix** [comment]
but, that only works for motion right? not if the button on the ring device is pressed? 

it's because i dont want motion notifications, only if someone press the button.
