### ISSUE TITLE
Simulate ring button press

### ISSUE THREAD

**Issue by nikbyte** [dgreif/ring#765]
Hello, is this possible to simulate ring button press?

I'd like to have more buttons which triggers all my doorbells, ring application and triggers in home bridge.

Is this possible to make such virtual button?

**Comment by dgreif** [comment]
Sorry, this is not possible.  Ring doesn't have an API endpoint for triggering a doorbell event that I'm aware of.

**Comment by nikbyte** [comment]
Sorry for annoying. But what if do such virtual button to trigger homekit ring?

**Comment by dgreif** [comment]
Sorry, that isn't something I'm interested in adding to the plugin
