### ISSUE TITLE
Setting hideCameraMotionSensor makes motion alerts unavailable in iOS 15

### ISSUE THREAD

**Issue by weac-nreese** [dgreif/ring#766]
# Bug Report

### Describe the Bug
Using the following configuration makes motion alerts unavailable. I've noticed this over the last few weeks when no more notifications were coming in. So I checked the Home settings and I found the motion notifications toggle was off. You can toggle it back on, but it will not save and will be off again when opening the settings again. I've tested this a little and it seems like this only happens when hideCameraMotionSensor is used in the configuration. When I remove that, everything works again. I assume this has something to do with iOS 15 as it always worked before, but I'm not sure and do not have any devices with iOS 14.

### To Reproduce
 - Start Homebridge
- Add the config above to Homebridge
- Open the Home app and open the Camera settings
- Tap on Notifications and toggle "Motion Alerts" on
- Go back and return to Notifications
- The toggle is now off again

Repeat the same steps without hideCameraMotionSensor in the config and everything works as expected.

### Expected behavior
Using hideCameraMotionSensor should hide the motion sensor as a separate device from the Home app while still allowing Motion Notifications for the Ring Doorbell camera. This used to worked fine.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
{
            "refreshToken": "XXX",
            "platform": "Ring",
            "hideLightGroups": true,
            "hideDoorbellSwitch": true,
            **"hideCameraMotionSensor": true,**
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "sendCameraMotionNotificationsToTv": false,
            "sendDoorbellMotionNotificationsToTv": false,
            "hideDeviceIds": [
                "d020cbde-8146-4a1a-a665-f6a2a957f777"
            ]
        },

```

### Environment

 - OS: Synology
 - Node.js: v14.17.5
 - NPM: 6.14.14
 - homebridge-ring: v9.21.2
 - homebridge: v1.3.4
 - hoobs: N/A

**Comment by dgreif** [comment]
This is an implementation detail on the HomeKit side and not something I can change from the plugin.  I'd recommend simply not hiding the motion sensor.  As long as you keep the devices for the camera grouped, you never see it anyways.
