### ISSUE TITLE
Don’t receive notification if away from home

### ISSUE THREAD

**Issue by rpmartinez3** [dgreif/ring#768]
# Bug Report

### Describe the Bug
If I'm away from my home and someone rings my Ring door bell I do not receive a notification.
If I'm home and connected to my network i receive the notification on my cellphone.
### To Reproduce
 - Leave home WiFi network
 - Someone rings the Ring doorbell.

### Expected behavior
If I'm away from home I should receive a notification if someone rings my doorbell.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - hoobs: 4.0.100
 - ring: 9.21.2

**Comment by dgreif** [comment]
This is an issue with HomeKit, and not something that can be fixed by the plugin.  Try restarting your Home Hub, phone, etc.
