### ISSUE TITLE
70000+ calls to api.ring.com per day

### ISSUE THREAD

**Issue by redeemer666** [dgreif/ring#769]
# Bug Report

### Describe the Bug
Since the last 2 updates, Homebridge-Ring makes thousands and thousands of “pings” to api.ring.com. I discovered this because I’m using Pi-Hole on my home network. Not a big hassle, but still should be investigated

### To Reproduce
Please see attachments
![80D27C44-DF89-47C7-8CBB-10FF8B8FC676](https://user-images.githubusercontent.com/9434736/133601153-1cdab465-ec06-4da6-9002-fd577fe2029c.jpeg)
![67357918-19E3-48F6-AAB9-0E616EFEBBF3](https://user-images.githubusercontent.com/9434736/133601329-022069e9-f55b-4c47-99b7-07b6d61ab56d.jpeg)

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
It has always made these requests, but the plugin is no longer using HTTP2 because it caused to many issues.  You didn't include your config, but I'm guessing you have the polling interval set to 1 second.  That's how often it will make a request.
