### ISSUE TITLE
error upgrading to 4.3.1 or 4.3.1

### ISSUE THREAD

**Issue by jcapayne** [dgreif/ring#77]
Upgrading to 4.3.2 (from 4.3.0) gives:

`npm WARN engine rxjs@6.5.2: wanted: {"npm":">=2.0.0"} (current: {"node":"8.11.1","npm":"1.4.21"})
npm ERR! tar.unpack untar error /root/.npm/rxjs/6.5.2/package.tgz
npm ERR! tar.unpack untar error /root/.npm/sip/0.0.5/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/homebridge-ring/node_modules/axios/node_modules/follow-redirects'
npm ERR! error rolling back  homebridge-ring@4.4.0 { Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/homebridge-ring/node_modules/axios/node_modules/follow-redirects'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/homebridge-ring/node_modules/axios/node_modules/follow-redirects' }
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.79-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i" "-g" "homebridge-ring"
npm ERR! cwd /home/pi
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! tar.unpack untar error /root/.npm/is-buffer/2.0.3/package.tgz
npm ERR! tar.unpack untar error /root/.npm/debug/3.1.0/package.tgz
npm ERR! tar.unpack untar error /root/.npm/follow-redirects/1.5.10/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/homebridge-ring/node_modules/socket.io/node_modules/engine.io/node_modules/accepts/node_modules/negotiator'
npm ERR! error rolling back  engine.io@3.3.2 { Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/homebridge-ring/node_modules/socket.io/node_modules/engine.io/node_modules/accepts/node_modules/negotiator'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/homebridge-ring/node_modules/socket.io/node_modules/engine.io/node_modules/accepts/node_modules/negotiator' }
npm ERR! tar.unpack untar error /root/.npm/blob/0.0.5/package.tgz
npm ERR! tar.unpack untar error /root/.npm/base64-arraybuffer/0.1.5/package.tgz
npm ERR! tar.unpack untar error /root/.npm/arraybuffer.slice/0.0.7/package.tgz
npm ERR! tar.unpack untar error /root/.npm/mime-types/2.1.24/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/homebridge-ring/node_modules/socket.io/node_modules/engine.io/node_modules/accepts/node_modules/negotiator'
npm ERR! error rolling back  accepts@1.3.7 { Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/homebridge-ring/node_modules/socket.io/node_modules/engine.io/node_modules/accepts/node_modules/negotiator'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/homebridge-ring/node_modules/socket.io/node_modules/engine.io/node_modules/accepts/node_modules/negotiator' }
npm ERR! tar.unpack untar error /root/.npm/after/0.8.2/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/homebridge-ring/node_modules/socket.io/node_modules/socket.io-parser/node_modules/debug/node_modules/ms'
npm ERR! error rolling back  socket.io@2.2.0 { Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/homebridge-ring/node_modules/socket.io/node_modules/socket.io-parser/node_modules/debug/node_modules/ms'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/homebridge-ring/node_modules/socket.io/node_modules/socket.io-parser/node_modules/debug/node_modules/ms' }
npm ERR! tar.unpack untar error /root/.npm/negotiator/0.6.2/package.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0
`

upgrading to 4.3.1 or installing it gives:

`npm WARN engine rxjs@6.5.2: wanted: {"npm":">=2.0.0"} (current: {"node":"8.11.1","npm":"1.4.21"})
npm ERR! tar.unpack untar error /root/.npm/follow-redirects/1.5.10/package.tgz
npm ERR! tar.unpack untar error /root/.npm/is-buffer/2.0.3/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/_esm2015'
npm ERR! error rolling back  homebridge-ring@4.3.1 { Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/_esm2015'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/_esm2015' }
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.79-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i" "-g" "homebridge-ring@4.3.1"
npm ERR! cwd /home/pi
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! tar.unpack untar error /root/.npm/debug/3.1.0/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/homebridge-ring/node_modules/socket.io/node_modules/engine.io/node_modules'
npm ERR! error rolling back  engine.io@3.3.2 { Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/homebridge-ring/node_modules/socket.io/node_modules/engine.io/node_modules'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/homebridge-ring/node_modules/socket.io/node_modules/engine.io/node_modules' }
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0
`

installing 4.3.0 works though:
`
npm WARN engine rxjs@6.5.2: wanted: {"npm":">=2.0.0"} (current: {"node":"8.11.1","npm":"1.4.21"})
/usr/local/bin/ring-auth-cli -> /usr/local/lib/node_modules/homebridge-ring/ring-auth-cli.js
homebridge-ring@4.3.0 /usr/local/lib/node_modules/homebridge-ring
├── sdp@2.9.0
├── colors@1.3.3
├── getports@1.0.2 (getport@0.1.0)
├── debug@4.1.1 (ms@2.1.2)
├── axios@0.19.0 (is-buffer@2.0.3, follow-redirects@1.5.10)
├── socket.io@2.2.0 (socket.io-adapter@1.1.1, has-binary2@1.0.3, socket.io-parser@3.3.0, engine.io@3.3.2, socket.io-client@2.2.0)
├── sip@0.0.5 (ws@6.2.1)
├── stun@2.0.0 (is-stun@2.0.0, ip@1.1.5, turbo-crc32@1.0.1, ip2buf@2.0.0, buffer-xor@2.0.2, parse-url@5.0.1, meow@5.0.0, binary-data@0.6.0)
└── rxjs@6.5.2 (tslib@1.10.0)
`

**Comment by dgreif** [comment]
I added a dependency in those versions that may be causing your issue. You should update to node 10+ and the latest version of npm. Let me know if you still have issues after updating.

**Comment by jcapayne** [comment]
That did it.  I also had to then upgrade homebridge-nest as the older version was causing a segfault with the newer node and npm, but now I'm up and running!

**Comment by dgreif** [comment]
Great, glad to hear it! Enjoy 😄
