### ISSUE TITLE
Enable/Disable linked devices "Ring and Motion" via API

### ISSUE THREAD

**Issue by ahmed-shehata** [dgreif/ring#770]
# Feature Request: Enable/Disable linked devices "Ring and Motion" via API

### Description

Enable/Disable linked devices "Ring and Motion" via API.
![Screenshot 2021-09-17 at 8 26 06 pm](https://user-images.githubusercontent.com/4982099/133843241-0bc8f3b8-08d9-416d-9164-8aa3faf295b2.jpeg)

First of all, thank you @dgreif and contributors for this great and well maintained API! I found this very useful and easy to use.

Currently the API supports updating Chime Settings to [change the ringtone of Motion and Ring](https://github.com/dgreif/ring/blob/b14442f1f64b9922d84f7357f7dde8475d6bd5c6/api/ring-types.ts#L347-L351), however it does not allow disabling Motion/Ring notifications (on the Chime) individually.

This would be useful when you want to mute the Chime device for specific types of notifications, for example, just enable chime to notify me when someone clicks the doorbell (and not motion).

### Describe the solution you'd like
API to support muting the Motion/Ring notifications individually.

### Describe alternatives you've considered
No workarounds found.

### Device data
- Chime V2
- Ring Doorbell

**Comment by dgreif** [comment]
Do you know what endpoints need to be used to perform these actions?  I think this piece of configuration is a bit more complicated because it requires a link between the chime and individual cameras

**Comment by ahmed-shehata** [comment]
> Do you know what endpoints need to be used to perform these actions? I think this piece of configuration is a bit more complicated because it requires a link between the chime and individual cameras

I tried reverse engineering the API calls, I used Charles Proxy on iOS however to no avail (requests show as UNKNOWN), do you know of a more solid approach to check API calls (maybe Android apps?)

**Comment by dgreif** [comment]
Yeah, I usually use the android app with a vpn proxy app
