### ISSUE TITLE
ERROR Request to https://api.ring.com/clients_api/ring_devices failed with status 502.

### ISSUE THREAD

**Issue by databoy01** [dgreif/ring#773]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

My homebridge has been spotty lately and when looking in the log, I see this error over and over.  Then it clears and all is fine for few days.

ERRORRequest to https://api.ring.com/clients_api/ring_devices failed with status 502.

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your 

9/21/2021, 9:18:00 PMHOOBSRingERRORRequest to https://api.ring.com/clients_api/dings/active failed with status 502. Response body: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty</center>
</body>
</html>
9/21/2021, 9:18:04 PMHOOBSRingERRORRequest to https://api.ring.com/clients_api/dings/active failed with status 502. Response body: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty</center>
</body>
</html>

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: Raspbian logging in via  ipad iOS 15 safari 
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
This is likely an error from the Ring servers.  Nothing I can do to fix these 502s
