### ISSUE TITLE
No chime on HomePod on iOS15

### ISSUE THREAD

**Issue by EdwardChamberlain** [dgreif/ring#776]
# Bug Report

### Describe the Bug
 Since the iOS15 update homepods no longer chime on the doorbell being pressed. I do receive a notification on homekit (and ring) and the setting is set for them to chime. This may or may not be related to this plugin and could be a homekit issue (im not sure!) 

### To Reproduce
 - Start Homebridge
 - Ring doorbell
 - Receive ring notification
 - Receive homekit notification
 - Do not hear homepods chime

### Expected behavior
 Doorbell produces a chime on homepod.

### Screenshots/Logs
Only log entry is: 
```
[9/26/2021, 4:20:28 AM] [Ring] Front Door Doorbell Pressed
```

### Additional context
 N/A

### Homebridge Ring Config
```
        {
            "refreshToken": "totallysecrettoken",
            "platform": "Ring"
        }
```

### Environment

 - OS: Ubuntu Bionic Beaver (18.04.5 LTS)
 - Node.js: `v14.17.5`
 - NPM: `6.14.14`
 - homebridge-ring: `v9.21.2`
 - homebridge: `v1.3.4`
 - hoobs: `N/A`

**Comment by phis5533** [comment]
Hello,

same here.
Definitely an iOS 15 change.

Regards.

**Comment by dgreif** [comment]
If it broke with the iOS 15 update, then it is a HomeKit bug and not something I can fix from the plugin

**Comment by phis5533** [comment]
Ok, thx for the answer. I’ll reboot everything to see the behavior.
