### ISSUE TITLE
configuration of the ring plug inn

### ISSUE THREAD

**Issue by jpcowell** [dgreif/ring#777]
# Bug Report

### Describe the Bug
Installation went fine - Click on configuration and then link account. Entered email address and password which I know work. Then nothing happens.

### To Reproduce
Click on configuration and then link account. Entered email address and password which I know work. Then nothing happens.

### Expected behavior
Expected the plug in to ask for a 2Fa

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Environment

 - OS: Hoobs in a box with  version 4.0.104 
 - Node.js: v14.17.6
 - NPM: 6.14.15
 - ring-client-api: 9.21.2

**Comment by jpcowell** [comment]
No

I have just installed and tried to link

JC

**Comment by mkellsy** [comment]
@dgreif no changes. Same code no updates. I have been trying to reproduce this.

I need someone to post the console errors from the browser.

**Comment by dgreif** [comment]
@jpcowell are you still having this issue?  If so, can you open the developer tools in the browser and post any errors in the console?

**Comment by jgphaneuf** [comment]
I am having the same issue. 

10/6/2021, 4:21:28 AMRing BridgeConfiguration change
10/6/2021, 4:21:28 AMringbridge stopping
10/6/2021, 4:21:33 AMRing Bridge starting
10/6/2021, 4:21:35 AMRing BridgeInitializing HAP-NodeJS v0.9.4...
10/6/2021, 4:21:43 AMRing BridgeLoaded plugin 'homebridge-ring'
10/6/2021, 4:21:43 AMRing BridgeLoading 1 platforms...
10/6/2021, 4:21:43 AMRing BridgeRegistering platform 'homebridge-ring.Ring'
10/6/2021, 4:21:43 AMRing BridgePreparing Advertiser for 'Ring Bridge BD4F' using bonjour-hap backend!
10/6/2021, 4:21:43 AMRing BridgeRingERRORRequest to https://api.ring.com/devices/v1/locations failed:
10/6/2021, 4:21:43 AMRing BridgeRingERRORError: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
10/6/2021, 4:21:43 AMRing BridgeRingERRORError connecting to API
10/6/2021, 4:21:43 AMRing BridgeRingERRORError: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
10/6/2021, 4:21:43 AMRing BridgeStarting to advertise 'Ring Bridge BD4F' using bonjour-hap backend!
10/6/2021, 4:21:43 AMRing BridgeBridge is running on port 51826.

**Comment by mkellsy** [comment]
can you open the developer tools in the browser and post any errors in the console?

**Comment by dgreif** [comment]
@jgphaneuf it looks like your refresh token is no longer valid.  What platform are you using?  HOOBS or homebridge?

**Comment by mkellsy** [comment]
There’s a new version coming Tuesday
