### ISSUE TITLE
Add feature to change keypad passwords

### ISSUE THREAD

**Issue by Anthonykuzmich** [dgreif/ring#780]
# Feature Request

### Description
 Add feature to change keypad passwords

### Describe the solution you'd like
 Add feature to change keypad passwords

### Describe alternatives you've considered
 Add feature to change keypad passwords

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dgreif** [comment]
Can you elaborate? What's the use case? Do you want this in the api or in homebridge? If homebridge, how would that work within the home app?
