### ISSUE TITLE
Floodlight cam lights always on

### ISSUE THREAD

**Issue by PaulmichlJ** [dgreif/ring#786]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...
Sine 9.22.0 lights always on during daytime & night

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

Since 9.22.0 (no changes inside ring) all light returns permanent on every ~50 minutes after manual switched of

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.
No changes made inside ring device config - ONLY ring plugin update 

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian] rasbian
 - Node.js: [e.g. 12.14.1]  latest
 - NPM: [e.g 6.13.4]  latest
 - homebridge-ring: [e.g 6.0.3] latest
 - homebridge: [e.g. 0.4.50 or N/A] latest
 - hoobs: [e.g. 0.4.50 or N/A] latest

everything is running latest release version fully patched!!

**Comment by PaulmichlJ** [comment]
Help request as the only current solution is power of ring floodlight :-(

**Comment by dgreif** [comment]
I have not seen this issue at all.  Have you looked through your automations in HomeKit to see if any are turning the lights on?

**Comment by PaulmichlJ** [comment]
Hi Dusty,
thank you for your quick reply!

I just plugged in my backup RaspberryPi with your version 9.18.1 an all ring lights are working again as expected!!

Using the one with 9.22.0 brings the lights back every ~50 minutes - sorry NO OTHER CONFIG changed - neither in ring or HoneKit. It’s the plug-in ONLY.

Until you find the bug I will stay on my backup version 9.18.1 . . .



Regards,
Jürgen

Sent from my mobile, sorry for shortened statement  and please ignore any orthographic mistakes ;-)

Mit bestem Gruß,
MMst. Jürgen M. Paulmichl, BSc MA
_____________________________________________________________________________

Leutenhofen 30
A-6914 Hohenweiler
Austria/Europe

Mobile:+43/699/10017769
EMail: ***@***.***

_______________________________________________________________________________
Disclaimer:
This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views
or opinions presented are solely those of the author and do not necessarily represent those of his company.

If you are not the intended recipient, be advised that you have received this email in error and that any use, 
dissemination, forwarding, printing, or copying of this email is strictly prohibited.
Although the sender endeavours to maintain a computer virus free network, the sender does not warrant that
this transmission is virus-free and will not be liable for any damages resulting from any virus transmitted. 
Thank you.
PLEASE CONSIDER THE ENVIRONMENT BEFORE YOU PRINT THIS E-MAIL
Antes de Imprimir pense em sua responsabilidade e compromisso com o MEIO AMBIENT

**Comment by PaulmichlJ** [comment]
Dear Dusty,
I compared the versions and found that the upgrade to 9.22.0 set the “Ring Smart Lighting Timer” from initially 60 (my ring app default) to ~ 16000!
Afterwards the first “signal” turn on the lights independently from any settings in ring app.

So far my analysis . . . back on primary HW.

 


Regards,
Jürgen

Sent from my mobile, sorry for shortened statement  and please ignore any orthographic mistakes ;-)

Mit bestem Gruß,
MMst. Jürgen M. Paulmichl, BSc MA
_____________________________________________________________________________

Leutenhofen 30
A-6914 Hohenweiler
Austria/Europe

Mobile:+43/699/10017769
EMail: ***@***.***

_______________________________________________________________________________
Disclaimer:
This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views
or opinions presented are solely those of the author and do not necessarily represent those of his company.

If you are not the intended recipient, be advised that you have received this email in error and that any use, 
dissemination, forwarding, printing, or copying of this email is strictly prohibited.
Although the sender endeavours to maintain a computer virus free network, the sender does not warrant that
this transmission is virus-free and will not be liable for any damages resulting from any virus transmitted. 
Thank you.
PLEASE CONSIDER THE ENVIRONMENT BEFORE YOU PRINT THIS E-MAIL
Antes de Imprimir pense em sua responsabilidade e compromisso com o MEIO AMBIENT

**Comment by tangouniform** [comment]
@PaulmichlJ How exactly did you keep the lights from coming on by themselves?  Mine just started happening yesterday.  Would like to disable them from coming on.

**Comment by PaulmichlJ** [comment]
Would you please be so kind and remove my personal details (phone, Adresse) from the threads?

Regards,
Jürgen

Sent from my mobile, sorry for shortened statement  and please ignore any orthographic mistakes ;-)

Mit bestem Gruß,
Jürgen M. Paulmichl, BSc MA
_____________________________________________________________________________

_______________________________________________________________________________
Disclaimer:
This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views
or opinions presented are solely those of the author and do not necessarily represent those of his company.

If you are not the intended recipient, be advised that you have received this email in error and that any use, 
dissemination, forwarding, printing, or copying of this email is strictly prohibited.
Although the sender endeavours to maintain a computer virus free network, the sender does not warrant that
this transmission is virus-free and will not be liable for any damages resulting from any virus transmitted. 
Thank you.
PLEASE CONSIDER THE ENVIRONMENT BEFORE YOU PRINT THIS E-MAIL
Antes de Imprimir pense em sua responsabilidade e compromisso com o MEIO AMBIENT
