### ISSUE TITLE
Not recognizing Level Lock

### ISSUE THREAD

**Issue by rfiorentino1** [dgreif/ring#788]
# Bug Report

### Describe the Bug
If I add the Level Lock through the Ring app, it does not appear in Homebridge or in the Home app to control it, or see it's state, etc.

### To Reproduce
 - Start Homebridge
 - Attempt to find/control level lock in iOS Home app; the lock doesn't exist.

### Expected behavior
I expect the Homebridge Ring plugin to find the Level Lock, once connected to the Ring app, and display it's controls within HomeKit.

### Environment
 - OS: Mac OS Catalina (10.15.7)
 - Node.js: 16.9.1
 - NPM: 7.21.1
 - homebridge-ring: 9.22.0
 - homebridge: 1.3.4
 -

**Comment by dgreif** [comment]
See https://github.com/dgreif/ring/issues/655#issuecomment-898711361.  Unfortunately Level Lock isn't something I can support in this plugin

**Comment by rfiorentino1** [comment]
For anyone interested, I did finally get Level Lock to work with both homeBridge AND Alexa simultaneously, all be it in a slightly convoluted way. Though this has nothing to do with the homeBridge Ring plugin itself, I'll outline the steps below in case it's helpful to anyone. If there's a better place for me to put this, please feel free to let me know/repost.

## Description:

This will allow you to have full control/status of your Level Lock through both Alexa and Homekit, simultaneously.

## Dependancies:

This method relies on the following plugins/configurations:

* The Level Lock is configured in Homekit, through the level app.
* The [HomeBridge Alexa Plug-in](https://github.com/NorthernMan54/homebridge-alexa#readme) is installed and configured correctly, with the accompanying Alexa skill, etc.
* the [Homebridge Dummy Lock Plug-in](https://github.com/karlg100/homebridge-dummy-lock#readme) is installed, default configuration is fine for this purpose. If installing via [Homebridge Config UI-X](https://github.com/oznu/homebridge-config-ui-x#readme) then the you don't need to change any settings, just click Save.

## A Note about Homebridge Alexa:

For this guide, I'm only focusing on one Homebridge accessory that needs to be added to Alexa. If you have multiple devices that are linked to both homebridge and alexa, and you want to avoid creating duplicate devices, you can choose to allow only a list of pre-determined devices within the [HomeBridge Alexa](https://github.com/NorthernMan54/homebridge-alexa#readme) config/settings. If you choose to do this, just make sure that the DummyLock is in this list of allowed devices before continuing.

## Procedure:

* 1. After installing the Dummy Lock plugin, it will create an accessory called "DummyLock" by default, inside the Home app.
* 2. Open the Home app and go to the automation tab. Configure the following automations. Note that "level lock" is used as a place holder for whatever your lock is (Front Door, etc.)
 * When your level lock unlocks, unlock dummy lock.
 * When level lock locks, lock dummy lock.
 * when dummy lock locks, lock level lock
 * when dummy lock unlocks, unlock level lock
* 3. Now go back into HomeBridge, and pull up your config file, either through the UI or manually. Find the Alexa Homebridge platform, and edit the "blind" and "door" parameters to be true, instead of false. Restart Homebridge.
* 4. In the Alexa app, run device discovery, or just ask any nearby echo to discover devices. Alexa should find the Dummy Lock from earlier. If she doesn't, something is wrong with your Homebridge Alexa plugin config, or you've disabled "insecure mode" in Homebridge.
* 5. Rename the Dummy Lock, only in the Alexa App, to your desired lock name that matches the name of your actual Level Lock. Set up unlock by app or by voice if desired.
 * Note: As of this writing, the [HomeBridge Alexa Plug-in](https://github.com/NorthernMan54/homebridge-alexa#readme) claims that Amazon stops it from successfully unlocking the door, but this has worked without fail for me multiple times. You can ignore that warning for the moment, but if for some reason Alexa doesn't want to unlock your door by voice, this may be why.
* 6. At this point, you should be able to ask Alexa the following:
 * Unlock/Lock the door
 * Is my door locked/unlocked?
 * 7. Finally, go back into the Home app, and go to the dummy lock. Remove it from your favorites, and turn off status, and activity notifications.


## Caveats:
 
 The only downside to this approach is that Siri will now recognize 2 doors/locks, since it still thinks that the fake lock created for Alexa is another door within Homekit. This means if you used a general phrase, such as "lock the door" instead of "lock the front door", Siri will now respond with, "Which one? Front door or dummy lock, or all?" To avoid this, you could create a scene called "lock the door" to override the default, or if you just say the entire lock name, such as "front door" Siri will respond as normal.
 
 This seems fairly simple when you look at it, but it took me a while to realize there was a dummy lock plugin, and connect the dots. If you have any questions/corrections, please feel free to reach out to me. I write this with no guarantee of success, but in the hope that it helps someone in a similar situation.
