### ISSUE TITLE
Just installed Ring plugin on HOOBS, no User Account Prompts on Configuration Tab

### ISSUE THREAD

**Issue by markaedmondson** [dgreif/ring#789]
# Bug Report

### Describe the Bug
Fresh install of Ring plug-in, no section on Configuration Page to enter user account information.  

### Expected behavior
Ability to connect Ring Plugin to User Account. 

### Screenshots/Logs
<img width="835" alt="Screen Shot 2021-10-10 at 11 46 11 AM" src="https://user-images.githubusercontent.com/92271399/136709285-3ba06f79-f332-46d7-aa5d-85ddef6d117f.png">

### Additional context
Worked fine until about a week ago.  HOOBS v 4.0.104

**Comment by mkellsy** [comment]
Can you post the logs?

**Comment by markaedmondson** [comment]
There’s nothing else there.  I’ve factory reset twice and this is as far as anything gets.  No login prompts on Config tab.

**Comment by mkellsy** [comment]
I'm looking into it.
