### ISSUE TITLE
[Streaming]: Streaming video only - ffmpeg was not found. See https://github.com/dgreif/ring/wiki/FFmpeg for details.

### ISSUE THREAD

**Issue by shanon-p** [dgreif/ring#790]
### Streaming Issue

Hi all - novice here - I installed ffmpeg but keep getting this in my Homebridge logs
<img width="1302" alt="Screen Shot 2021-10-11 at 6 09 14 pm" src="https://user-images.githubusercontent.com/92293198/136747523-3b6fda49-e81c-4372-9082-4cf59bf3786e.png">
When running "ffmpeg" in terminal on my Mac mini, I get this
<img width="488" alt="Screen Shot 2021-10-11 at 6 11 27 pm" src="https://user-images.githubusercontent.com/92293198/136747577-41f85cf5-ad09-4d09-bc5b-0a3f0adc56b3.png">

Any help would be super appreciated

### Proposed Solution

It looks like a resource required by ffmpeg needs to be updated, but I have no idea how to do this

### Environment

Homebridge

### What operating system are you on?

Mac

### Relevant log output

```shell
From the Mac

dyld: Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
  Referenced from: /usr/local/bin/ffmpeg
  Reason: Incompatible library version: ffmpeg requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0
Abort trap: 6

From Homebridge
[10/11/2021, 6:09:06 PM] [Ring] Streaming video only - ffmpeg was not found. See https://github.com/dgreif/ring/wiki/FFmpeg for details.
```

### Honesty Time

- [X] I swear this is worth your time!

**Comment by dgreif** [comment]
Closing in favor of #925, which has a little more information on what is causing this issue
