### ISSUE TITLE
Ring alarm ready light

### ISSUE THREAD

**Issue by JeremyLaurenson** [dgreif/ring#795]
# Feature Request

### Description
Virtual light or switch that indicated whether all sensors are in ready state to have the system armed.

### Describe the solution you'd like
Since the ring plugin is keeping track of the state of the various sensors for ring alarm, I would like to suggest an optional virtual light/switch that indicates whether all alarm sensors are in a ready state for home or away modes. It may be necessary to enumerate sensors NOT to include in this if folks use different sensors for home/away.

### Describe alternatives you've considered
I have considered using the home bridge logic board but I would have to create automations for every single sensor for both open and closed state.

**Comment by dgreif** [comment]
This would be a pretty complex feature.  There can be different sensors for different modes, so knowing which to use would be tricky.  I understand why you would want this, but it's not something I'm interested in adding at this time
