### ISSUE TITLE
Cannot Click The Login Button

### ISSUE THREAD

**Issue by MichaelThomasIreland** [dgreif/ring#800]
# Bug Report

### Describe the Bug
 Login button will not click. 

### To Reproduce
Go to the plugin config, click the login button, wait for the box to popup, insert email and password, and click the login button. 

### Expected behavior
I'm trying to use the certified Ring plugin and it will not allow me to login at all. I'm inputting my user and password and the button just won't work. No error, no visual cue that the button is being pressed, etc.

I've used the official Hoobs mac app, Safari, and Brave (Chrome) and the button won't activate on any of them.

I'm on the latest version of both Hoobs and the plugin.

### Screenshots/Logs
![Screenshot](https://i.imgur.com/8W8WOch.jpg)

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: Hoobs
 - Node.js: [e.g. 12.14.1] Latest
 - NPM: [e.g 6.13.4] 
 - homebridge-ring:
![2021-10-16_12-00-41](https://user-images.githubusercontent.com/92649100/137600304-d7adaab2-2e29-4901-8f75-a3633c6f2474.jpg)
 [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
@mkellsy

**Comment by mkellsy** [comment]
There’s a new version coming Tuesday

**Comment by mkellsy** [comment]
I did make an update to the UI plugin. To get this update, re-install the plugin. This doesn't affect your config.

1. Open the Ring plugin page.
2. Click on the Versions tab
3. Click on the Latest tag
4. Select the current bridge this plugin is installed on

The plugin will re-install.

**Comment by williecha** [comment]
It reinstalled but didn’t have any noticeable effect on my ring login page when it selected the blue Login button. Or did it throw anything in the hoobs log. Sorry…

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dgreif** [comment]
Please reach out to HOOBS support directly if the issue is still happening
