### ISSUE TITLE
Hide light switch from accessories for Ring Floodlight

### ISSUE THREAD

**Issue by CodeAck** [dgreif/ring#802]
# Feature Request

### Description
To add the ability to remove/hide the light switch (accessory) from the Ring Floodlight.

### Describe the solution you'd like
Having a checkbox in HOOBS Visual Configuration just like 'Hide Camera Motion Sensor'.

### Describe alternatives you've considered
Coding to add in Advanced  configuration or in Homebridge... sorry I'm only two days into HOOBS/Homebridge and just learning.

<img width="483" alt="Screen Shot 2021-10-16 at 6 11 50 PM" src="https://user-images.githubusercontent.com/43360701/137606415-9d6c7890-4200-4d15-98a8-0894694677d3.png">
<img width="1197" alt="Screen Shot 2021-10-14 at 3 02 43 PM" src="https://user-images.githubusercontent.com/43360701/137606417-7492e610-42a5-4ac2-b22d-f8017bf987de.png">
<img width="1197" alt="Screen Shot 2021-10-14 at 3 02 59 PM" src="https://user-images.githubusercontent.com/43360701/137606418-61185177-3522-4433-afe3-2d83337adc5d.png">
<img width="1197" alt="Screen Shot 2021-10-14 at 3 03 19 PM" src="https://user-images.githubusercontent.com/43360701/137606420-0c3ce180-c674-4594-bd91-27ba43a9e333.png">

**Comment by dgreif** [comment]
@CodeAck I'd say that's a pretty good reason 😉.  Added the option in v`9.23.0`.  Let me know how it works for you!

**Comment by CodeAck** [comment]
@dgreif   you are Awesome!  I look forward to the release and trying it :-)
