### ISSUE TITLE
Ring Chime does not consistently work from a trigger

### ISSUE THREAD

**Issue by vadalus911** [dgreif/ring#803]
I cannot get a Ring Chime to consistently 'ring' from a trigger (in this case from a Unifi G4 doorbell). It will always trigger if i manually trigger it from Home app however from a doorbell press it's not being activated often (even though i'll get the 'alert' from the home app that the trigger has been fired)

Any way to debug any of this, nothing in the logs..

# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
@vadalus911 I think the only other mention of this issue was also from you earlier this year on discord: https://discord.com/channels/432663330281226270/432671438156070931/853657445695881226

I'm still not sure what would be causing the issue, but it feels like more of an issue with HomeKit than with the plugin.  The only thing I can think to add on my end would be some debug logs to indicate that a request was sent to play the sound.  Would that be helpful?

**Comment by dgreif** [comment]
@vadalus911 any updates on your end?

**Comment by vadalus911** [comment]
Hi

Thanks for following up. I’m still probably 30% failure. When it does fail
I see the native unifi notifications (eg in my phone) but no HomeKit
notifications and obviously no chime sound. I still don’t have any logging
which I can see on the Homebridge side of things from your plugin which
would allow me to see whether your plugin has received notification of a
button press. I guess that would sort out once and for all whether it’s
homebridge/ HomeKit issue vs plugin issue

Liam

**Comment by dgreif** [comment]
If you set `debug: true` in the homerbridge-ring config, you should see something like `CAMERA_NAME Doorbell Pressed. Loading snapshot before sending event to HomeKit` when the doorbell is pressed

**Comment by dgreif** [comment]
@vadalus911 I'm not sure there is anything else I can do on this one.  If you are able to dig into the code and find why it's not working, I'd happily accept a Pull Request
