### ISSUE TITLE
Disable simulated doorbell for specific Ring camera(s)

### ISSUE THREAD

**Issue by ceeeekay** [dgreif/ring#806]
# Feature Request

### Description
Simulated doorbell is a GREAT feature but it would be good to be able to disable this *per device* when you have multiple cameras, but one is in a high traffic area and is causing a lot of unwanted *\*dingdongs*\* on the Homepod

### Describe the solution you'd like
Something like the below would be good if the user knows the device ID
```
"sendCameraMotionNotificationsToTv": true,
"suppressCameraMotionNotificationsToTv": ["477e4800-fcde-4493-969b-d1a06f683102", "5aaed7a7-06df-4f18-b3af-291c89854d60"],
```
I think a deny list suppressing the `sendCameraMotionNotificationsToTv` boolean would be best, as the devices are fetched from the Ring account, and you can simply deny the specific devices you want to silence.

### Describe alternatives you've considered
I've considered totally disabling the audible doorbell on the Homepod, but for one of the cameras it's extremely useful. It would be nice to disable this just for the busy device that is driving me crazy with its dinging and donging.

**Comment by dgreif** [comment]
From what I've been told, there is now an option to show the stream when motion is detected in tvOS 15.  `sendCameraMotionNotificationsToTv` should no longer be needed and will be removed in an upcoming release

**Comment by ceeeekay** [comment]
@dgrief will this behave the same way as the motion notifications for homepod though? It's the audible alert I'm trying to suppress, not the video stream. The homepod itself only has options for "doorbell chime" on or off, per homepod. Cheers.

**Comment by ceeeekay** [comment]
@dgrief I get what you're saying now. We do get (and want) both the TV and homepod notifications with it set like this:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/12092166/151731960-c4da720e-f22b-47f6-87e9-63f03199694e.png">

The issue is that *one* of our cameras is unreasonably busy and we want a method to stop *only* that camera sending motion events, while leaving the others enabled for notifications, but still have it in homekit for everything else. Is that possible?

The only option we have inside homekit for this is to stop *all* notifications to the homepods, regardless of where they come from.
