### ISSUE TITLE
Error: Failed to retrieve public ip address

### ISSUE THREAD

**Issue by benfysh** [dgreif/ring#81]
Opening new issue as requested in https://github.com/dgreif/ring/issues/35#issuecomment-515795422 I am consistently getting the `Error: Failed to retrieve public ip address` issue when trying to start a livestream, log sample shown below.

Yesterday I removed and cleaned up the cameras, uninstalled and then reinstalled the plugins and then added the cameras back into Home and was still getting the issue. About 2 hours later the streams started to work every time. However, this morning I am getting the error again.

```
Jul 29 08:49:10 raspberrypi homebridge[9409]: [2019-7-29 08:49:10] [Ring] Snapshot Requested for Garage
Jul 29 08:49:13 raspberrypi homebridge[9409]: [2019-7-29 08:49:13] [Ring] Failed to prepare stream for Garage
Jul 29 08:49:13 raspberrypi homebridge[9409]: [2019-7-29 08:49:13] [Ring] Error: Failed to retrieve public ip address
Jul 29 08:49:13 raspberrypi homebridge[9409]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge-ring/lib/homebridge/rtp-utils.js:36:23)
Jul 29 08:49:13 raspberrypi homebridge[9409]:     at Generator.throw (<anonymous>)
Jul 29 08:49:13 raspberrypi homebridge[9409]:     at rejected (/usr/lib/node_modules/homebridge-ring/lib/homebridge/rtp-utils.js:5:65)
Jul 29 08:49:13 raspberrypi homebridge[9409]:     at <anonymous>
Jul 29 08:49:13 raspberrypi homebridge[9409]:     at process._tickCallback (internal/process/next_tick.js:189:7)
Jul 29 08:49:25 raspberrypi homebridge[9409]: [2019-7-29 08:49:25] [Ring] Preparing Live Stream for Garage
Jul 29 08:50:11 raspberrypi homebridge[9409]: [2019-7-29 08:50:11] [Ring] Snapshot Requested for Garage
```

**Comment by benfysh** [comment]
Not sure if this helps but I installed [public-ip-cli](https://github.com/sindresorhus/public-ip-cli) and that only seems to work with the -h option for using https instead of DNS
```
pi@raspberrypi:~ $ public-ip
Error: Couldn't find your IP
    at socketQuery.then (/usr/lib/node_modules/public-ip-cli/node_modules/public-ip/index.js:50:10)
    at <anonymous>
pi@raspberrypi:~ $ public-ip -h
xx.xx.xxx.xx
```

**Comment by dgreif** [comment]
@benfysh that is extremely helpful! I'll get an update out later today for you

**Comment by benfysh** [comment]
Great thanks, will test and feedback :)

**Comment by benfysh** [comment]
As it did last night around the same time streaming has started working again  ¯\_(ツ)_/¯  the public-ip cli tool is still not working. 

Not sure what is changing after 21:30? Will have to see what happens in the morning …

**Comment by dgreif** [comment]
Ok, I've added https as a fallback in v`4.5.2`.  Hopefully that get's you working in all scenarios.  Post back in 24 hours and let me know how it goes 😄

**Comment by benfysh** [comment]
Hi, can confirm that everything is now working as expected on my side. Thanks again for the plugin and for fixing my specific issue.
