### ISSUE TITLE
npx -p ring-client-api ring-auth-cli BROKEN

### ISSUE THREAD

**Issue by williecha** [dgreif/ring#810]
# Bug Report

### Describe the Bug
 The terminal command "npx -p ring-client-api ring-auth-cli" is designed to pull a RING refreshToken after entering your Ring account information. It's crashing after entering the account password throwing the attached screenshot.

### To Reproduce

From a terminal logged in as the hoobs administrator i run the supplied command, enter a valid ring email and password dor an account. 

### Expected behavior
 Expect a refreshToken to be echoed back.

### Screenshots/Logs
 
![image](https://user-images.githubusercontent.com/93397295/139511764-e04ea76f-d0c2-470a-8cd9-4e13fc0a2686.png)

### Additional context
 the password is valid

### Environment

 - OS: [e.g. Raspbian]
Hoobs 4.0.110
Node 14.18.1
Homebridge 1.3.4
Ring 9.23.0

**Comment by dgreif** [comment]
I just gave it a try and it worked for me.  It might be that Ring was having an outage, or that you have an older version of the client installed locally.  Would you mind giving it another try?

Also, HOOBS should allow you to log in via the UI. You shouldn't need to use the CLI
