### ISSUE TITLE
Ring Doorbell - manually/externally trigger „doorbell pressed“ command

### ISSUE THREAD

**Issue by Hendrik2021** [dgreif/ring#811]
# Feature Request

### Description
Setup of Ring doorbell with homebridge as such works fine. However I do have next to the Ring doorbell additionally a further button that can be used as doorbell (connected to a KNX-Bus), which is located a few meters apart from the Ring doorbell. 
Since this is only a button I would like to utilize the full features of audio & video from the Ring doorbell once that button is being pushed.
Hence I would like to have a „device“ in Homebridge which I can trigger to sent the command „doorbell pressed“ from this Ring doorbell integration. 
This „device“ would be triggered by an automation from HomeKit once the simple doorbell button gets pushed to automatically trigger this „device“ to provide a nice user experience at HomeKit devices (iPhone/iPad) by showing the Ring camera and audio when tapping on the HomeKit notification for a received „doorbell pressed“ command.

**Comment by dgreif** [comment]
@Hendrik2021 I appreciate the detail and understand what you are asking for.  Unfortunately this seems like a very rare setup, and isn't something I have time to take on/support at this time.  Maybe you could simply cover up the other button  to encourage visitors to push the Ring doorbell button?

**Comment by bananajoe86** [comment]
I'm looking for exactly the same setup. For example, to create a ring doorbell for several buttons. Maybe someone has the time and inclination to emulate it. The model could be Homebridge-FFMPEG or Homebridge-Camera-UI. ("motion": true, / "doorbell": true,)
