### ISSUE TITLE
Missing dings

### ISSUE THREAD

**Issue by djm181** [dgreif/ring#815]
# Bug Report

### Describe the Bug
I am finding that a decent fraction of my camera dings do not come to the `onNewDing` subscriber. Somewhere in the 10-20% range are being lost.

### To Reproduce
- Create an ApiClient
- Set the `cameraDingsPollingSeconds` option to 2
- Bind a handler to every camera's `onNewDing`. I currently do this by performing a `merge(...cameras.map(c => c.onNewDing)).subscribe(...)`
- Some of the dings never get this far. In fact, instrumenting the call to addSubscriptions that calls `fetchActiveDings` to log the dings as they come in to debug reveals that the missing dings are never being returned to the client at all.

### Expected behavior
Every ding is delivered to the subscriber

### Screenshots/Logs
Nothing notable in the logs - turning on debug the only thing that is logged is the extra instrumentation I added.

### Additional context
Unsure if this is notable, but this account has about 65 cameras in it, although I rarely see more than one ding at a time anyway.

### Environment

 - OS: Alpine Linux
 - Node.js: 14.18.1
 - ring-client-api: 9.18.6

**Comment by djm181** [comment]
Well, I'm happy to say I figured out the problem here - my Alpine environment was running in an ECS Fargate runtime. The `systeminformation` package is unable to get a usable system ID from this so the utils package generates a random uuid. This results in the ring account registering a new authorized device each time a new RingApi object is created and a call made to the client API. As the number of registered devices grows in the ring account, ding delivery becomes less and less reliable.

The fix is to provide a stable systemId in the RingApi options to the constructor. This keeps the number of authorized devices limited and delivery is more assured.

**Comment by dgreif** [comment]
That's great to hear! I'm curious, how did you track this down?

**Comment by djm181** [comment]
Once I noticed that there were a ton of authorized devices in the account, I cleared them all out and started debugging to see what actions specifically would cause them to reappear - a bit of bisecting the code-path with breakpoints and it became evident the 'Session hardware_id not found' debug message was correlated to the creation of a new authorized device in the Ring account. Once I noticed this _wasn't_ a problem on my local machine (it would only create one new device no matter how many times I ran it) I just had a hunch that the hardware id might be unstable in Fargate, and a few well-placed log statements confirmed as much.
