### ISSUE TITLE
Is it possible to get an explanation of the logs

### ISSUE THREAD

**Issue by Biggsylad** [dgreif/ring#817]
# Feature Request

### Description
Any chance you can tell me what configuration change is indicating, showing an awful lot of in my hoobs log

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dgreif** [comment]
Make sure you have `debug` set to `false`.  That's about it.
