### ISSUE TITLE
Live streaming from cameras with enabled Ring Edge (videos -> SD cards) with Ring Pro is broken

### ISSUE THREAD

**Issue by YPyltiai** [dgreif/ring#818]
# Bug Report

### Describe the Bug
With new Ring Pro base station comes new feature “Ring Edge”, which allows writing video recordings to SD card in base station. Once enabled - camera video streaming from Homekit through homebridge no longer works.

I tested with and without Ring Edge enabled on same environment with same configuration - only with it enabled issue reproduces. 

### To Reproduce
- Make sure you run latest Ring Pro Base station.
- In Ring Pro base station setting -> Video Storage -> Manage Cameras -> Select All -> Save
- Try live view of any enabled camera through Homekit

### Expected behavior
Camera should start live stream of video

### Screenshots/Logs
![32F62C07-4F54-4A51-8559-AA9EE21B7A35](https://user-images.githubusercontent.com/26441563/140589690-fc405239-5b4f-4012-b5ec-ad43768c372d.jpeg)

### Additional context
- Ring Pro base station required
- Ring Edge feature enabled for camera that we test

### Homebridge Ring Config
Not relevant. Didn’t change it.

### Environment
HB in Docker, using official images.
All software used is up to date including HB and Ring plugin

**Comment by dgreif** [comment]
Thanks for letting me know. I just ordered the alarm pro so I can test it out myself, but for not it's simply not going to work when Ring Edge is turned in. Same as E2E encryption feature. Will update here if I figure out a solution

**Comment by adrianguanipa** [comment]
Same problem for me, reported in this other ticket: [https://github.com/dgreif/ring/issues/830](url)

Thanks.

**Comment by madsmooth** [comment]
I encountered this issue using ring-mqtt based on this capability which uses this project. I have a ring alarm pro and would be happy to help test any dev updates. One think to note is that end to end encryption is an option with ring edge but I have not enabled it and still have issues. Also interesting that I accidentally left the stream attempt going overnight and even though it would error out on connection it initiated back to back live recording events to my sd card every 2 mins overnight.

**Comment by adrianguanipa** [comment]
> I encountered this issue using ring-mqtt based on this capability which uses this project. I have a ring alarm pro and would be happy to help test any dev updates. One thing to note is that end to end encryption is an option with ring edge but I have not enabled it and still have issues. Also interesting that I accidentally left the stream attempt going overnight and even though it would error out on connection it initiated back to back live recording events to my sd card every 2 mins overnight.

My only workaround for this is to disable the Edge feature, I haven't had any issues since, but hopefully, this will be fixed soon.

**Comment by dgreif** [comment]
I have some updates that I've been working on over the last few weeks that should get Ring Edge streaming working.  Hopefully I'll get the rough edges smoothed out and have it merged into the `beta` branch in the next few weeks.  No plans to look into end-to-end encryption at this point though

**Comment by dgreif** [comment]
For anyone wanting to try out homebridge + Ring Edge, give the latest beta version a try!  Hoping to do a real release in the next few weeks

**Comment by YPyltiai** [comment]
@dgreif doesn’t seem to work with or without Edge enabled on beta4. All cameras stopped working and refreshing HB cache to re-add those didn’t help either. Am I missing some important step?

**Comment by dgreif** [comment]
@YPyltiai can you turn in the debug setting and post the logs from a call?

**Comment by YPyltiai** [comment]
@dgreif something seems to be happening with audio processing and process gets terminated. That’s all that is in logs even with debug:

![06338DE0-734B-4B6A-A87F-E87E88BE1574](https://user-images.githubusercontent.com/26441563/161466831-3170d0ca-a0df-427d-a068-fa4d98250bea.jpeg)

**Comment by dgreif** [comment]
@YPyltiai it looks like WebRTC wasn't able to establish a connection with your Ring Edge server.  In practical terms, make sure that your homebridge server has a clear network path (ideally as a direct network child) to your Ring Alarm Pro.  Is your setup fairly complicated, such that that visibility would be blocked?

**Comment by YPyltiai** [comment]
@dgreif, yes, it is pretty locked down to allow only paths that are explicitly allowed, so I guess this may be the problem. That makes sense - I will check the firewall, likely traffic just got blocked. Didn’t think about this because originally it all worked through Ring servers, so path to actual Alarm device wasn’t required to be open. I will update you once I check logs.

**Comment by YPyltiai** [comment]
@dgreif it works now. Cams seem to load way faster which is cool! 

TCP ports 5228 and 9002 should be allowed outbound as well as UDP port 443 outbound. Beyond that there seems to be still some traffic between phone and hub on random ports but even with it being blocked setup still works.

Thanks for the fix! Is there anything specific you would want me to check additionally?

**Comment by dgreif** [comment]
Nothing else to check, glad it's working for you!!

**Comment by YPyltiai** [comment]
I think this ticket can be closed - it works reliably for a month now, no issues. Unless you keep it open for when you release stable release - this may be considered fixed.

Thanks!

**Comment by dgreif** [comment]
Thanks for the update @YPyltiai!  I'll keep this open until I get the fix in a "real" release.  Currently still requires `beta`

**Comment by dgreif** [comment]
v10 is released!  Happy streaming 😄
