### ISSUE TITLE
Bounty: Alternative to Ring servers (Camera Live Feed Proxy)

### ISSUE THREAD

**Issue by bugs181** [dgreif/ring#82]
Moving this to a new issue as #35 was closed and is a separate issue.

**Bounty Details:**

I know this is technically out of the scope of this project, however I and others have expressed interest in not using Ring's servers for varying reasons. For that reason, I have started a bounty to anyone that can implement a "proxy-like" service (getting started) or even a Ring server stub (which would be even better) for a full implementation to collect the bounty.

<br>

**Original comment:**

@dgreif excellent work! Anxiously following along on the progress. 

Correct me if I'm wrong, it sounds like you're using Homebridge to set up a SIP server and then proxying that to Ring's servers. Because I have such a low bandwidth internet connection, I'm hoping this will be the solution to avoid using Ring's servers et all. The recordings are often out of sync, very choppy and generally unintelligible. If I could use Homebridge as a direct connection to the doorbell locally, then the recordings could be saved to my NAS with near-perfect quality.

Edit: Just re-read some of the comments, it actually looks like you're just writing a SIP client for Homebridge to connect to Ring's servers. Bummer.

Edit 2: Anyone willing to pool funds toward a SIP proxy implementation that can MITM the video and store that locally? Personally willing to put $200 toward this.

_Originally posted by @bugs181 in https://github.com/dgreif/ring/issues/35#issuecomment-514065903_

**Comment by divemasterjm** [comment]
Very nice enhancement, would be nice

**Comment by dgreif** [comment]
While I would love to connect to the camera directly instead of bouncing through the servers, I don't think it's something I'm going to be able to track down.  If someone has a really good man-in-the-middle setup that they can use to monitor traffic from the camera, let me know.
