### ISSUE TITLE
[Streaming]: Ring Live Stream no Audio

### ISSUE THREAD

**Issue by mikeyvt** [dgreif/ring#822]
### Streaming Issue

Recently after a plugin update for Homebridge. I no longer get audio in any of my ring Streams.  Getting a message that only 'video' is streaming.  Any ideas?

![image](https://user-images.githubusercontent.com/33258406/141313993-bcd53bcf-73af-4990-a4d5-eb21475a1e19.png)

### Proposed Solution

Possibly build the required file into the plugin?

### Environment

Homebridge

### What operating system are you on?

Linux

### Relevant log output

```shell
[11/11/2021, 8:17:58 AM] [Ring] Preparing Live Stream for Kitchen
[11/11/2021, 8:17:58 AM] [Ring] Streaming video only - ffmpeg was not found. See https://github.com/dgreif/ring/wiki/FFmpeg for details.
[11/11/2021, 8:18:05 AM] [Ring] Hallway Detected Motion. Loading snapshot before sending event to HomeKit
```

### Honesty Time

- [X] I swear this is worth your time!

**Comment by dgreif** [comment]
This file should be automatically installed when you install the plugin.  I suggest you uninstall and re-install, watching the logs for any errors from `ffmpeg-for-homebridge`.  What version of npm and node are you using?

**Comment by mikeyvt** [comment]
![image](https://user-images.githubusercontent.com/33258406/141342824-a29c842b-f6a1-4540-b81a-1c967b2b2fe4.png)

**Comment by ronzelver** [comment]
Same here, already re-installed the plugin without change in results.
Raspberry Pi Linux 5.4.75-v7+
Node.js Version v14.15.5
Npm Version  v6.14.1

**Comment by SamirHafez** [comment]
I'm seeing the same behaviour. Tried reinstalling to no avail

**Comment by dgreif** [comment]
Closing in favor of #925, which has a little more info on _why_ this is happening.
