### ISSUE TITLE
Ring Login does nothing

### ISSUE THREAD

**Issue by williecha** [dgreif/ring#823]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
LinkAccount
email
enter password
click Login
NOTHING HAPPENS

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.
![image](https://user-images.githubusercontent.com/93397295/141511812-f1bd0b54-2469-4fce-b312-814ac2b96e4c.png)

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by williecha** [comment]
on ring bridge 9.23.0

**Comment by dgreif** [comment]
cc @mkellsy

**Comment by scmugan** [comment]
Same issue here, enter my login cress and the gear comes up spinning for a while then I get the login back again

**Comment by dgreif** [comment]
Please reach out to HOOBS for support with their UI.  It is not maintained by this plugin, so there isn't much I can do if it's broken
