### ISSUE TITLE
Video Doorbell preview no longer working

### ISSUE THREAD

**Issue by thrangster** [dgreif/ring#824]
# Bug Report

### Describe the Bug
<!Recently, I no longer see the video notification out of my Ring doorbell on any AppleTV devices (tvos15.1) nor do I recall seeing it on my iOS or iPAD os devices (also version 15.1> A clear and concise description of the problem... The Ring app sees it, and I can see the video live stream in the Home App or when popping out the sidebar manually on the AppleTV...

### To Reproduce
Ring the doorbell!

### Expected behavior
<Video notification of doorbell ring-> A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

#"refreshToken": "xxx",
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "_bridge": {
                "username": "xxxxx",
                "port": 34627
            },
            "platform": "Ring"
        },

```

### Environment
<!-- ✍️edit: -->
 - OS: [Raspbian]
 - Node.js: v16.13.0
 - NPM: v8.1.0
 - homebridge-ring: v9.23.0
 - homebridge: 1.3.6
 - hoobs: N/A


Thanks

**Comment by thrangster** [comment]
Its a Doorbell Pro v2 by the way, and notifications are on in Home

**Comment by dgreif** [comment]
Can you clarify the issue?  I don't use notifications on my AppleTV so I don't have a clear picture of what's expected and what is happening.

Do notifications show up properly on your phone?
