### ISSUE TITLE
Black thumbnail

### ISSUE THREAD

**Issue by rpmartinez3** [dgreif/ring#825]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 - Open home app and go to room that has the Ring doorbell camera.. instead of seeing a preview image, its just a black image.

### Expected behavior
 have a screenshot of the ring cameras view.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
Do your thumbnails update properly within the Ring app?  If not, try rebooting your camera (kill power, pull battery)

**Comment by rpmartinez3** [comment]
Hey, the thumbnail updates properly within the Ring app.

**Comment by dgreif** [comment]
Are there any errors in your logs?  Not much info to go off of here

**Comment by rpmartinez3** [comment]
Just a slow to respond error.
![image](https://user-images.githubusercontent.com/22985495/144455382-b6fc696a-154b-4394-be75-2f85af248a6c.jpeg)

**Comment by dgreif** [comment]
I don't see any logs in there about snapshots.  Could you set `"debug": true` in your ring plugin config, and then load up the Home app to a spot where it should be pulling the thumbnails?

**Comment by rpmartinez3** [comment]
Ok I will once I'm back home. But just want to double check we're on the same page. My black thumbnail issue occurs whenever I load the home app and go look at the camera feed.. it's black.. once I tap and open the feed it'll be black for a few seconds and then it'll show the video. Same thing happens whenever someone rings the doorbell.. the initial tvOS doorbell notification that appears is black and then a few Seconds later the stream appears.

**Comment by rpmartinez3** [comment]
![image](https://user-images.githubusercontent.com/22985495/144485189-7289e6f9-f2f1-4200-88df-f3a1e31e3d72.jpeg)

**Comment by dgreif** [comment]
![image](https://user-images.githubusercontent.com/3026298/144513986-521d9305-e447-4722-b355-92862ec9ca24.png)
This makes it look like it's caching images just fine.  Have you tried rebooting your phone/home hub?

**Comment by rpmartinez3** [comment]
I'll try rebooting everything

**Comment by rpmartinez3** [comment]
I just restarted everything and I'm still having the issue. The problem is that when I first open the home app or get a door bell press and the notification appears on the screen, the thumbnail is black and then a few seconds later the image loads. Before I used to see a thumbnail it might have been a few hours old or a day old but there was an image and then stream would take over that image. Now it's just black for a few seconds and then the stream.

**Comment by dgreif** [comment]
I'm not sure there is anything else for me to do here.  It's possible that HomeKit or the Home app updated and broke this functionality as well

**Comment by rpmartinez3** [comment]
If that's the case I'm surprised I'm the only one to have noticed so far.

**Comment by dgreif** [comment]
Do you get proper thumbnails in notifications? (before you click on them)

**Comment by rpmartinez3** [comment]
> Do you get proper thumbnails in notifications? (before you click on them)

No, I do not. I have to click on them.

**Comment by dgreif** [comment]
What type of camera is it?  Is it battery powered or hard wired?

**Comment by rpmartinez3** [comment]
Video doorbell 3 battery powered.

**Comment by dgreif** [comment]
It's likely because it's battery powered that it isn't showing thumbnails.  See https://github.com/dgreif/ring/wiki/Snapshot-Limitations.  Nothing else I can do at this point, sorry!

**Comment by hunt4868** [comment]
i have same issue to across a range of different ring cameras

**Comment by dgreif** [comment]
I'm able to recreate it as well. I think this can be explained by the fact that I return an empty image to HomeKit if there isn't a recent snapshot cached. It used to be ignored, but the Home app seems to be showing a blank image in this case now. This blank image is necessary to avoid the camera being marked as non responsive. See the wiki for more details on the timing complications with snapshots. In the end, I think this is working as expected. If you see a blank image, you should be able to wait 10 seconds and then receive a good snapshot

**Comment by rpmartinez3** [comment]
Ok thank you for looking into it.

**Comment by malmentm** [comment]
Would i not be better to return the last cached image instead of an empty one? Even if it’s very old i would look better than a black image.

**Comment by rpmartinez3** [comment]
I've heard that the latest iOS and tvOS 15.3 updates that came out today fixes the issue.> Would i not be better to return the last cached image instead of an empty one? Even if it’s very old i would look better than a black image.
