### ISSUE TITLE
Link doesn't bring up Ring login and says "Please wait for the bridge to start"

### ISSUE THREAD

**Issue by mountain2042** [dgreif/ring#826]
# Bug Report

### Describe the Bug
 When I start Homebridge and attempt to configure ring and select "Link Account" I get an error that says "Please wait for the bridge to start" and can not log in to Ring.

### To Reproduce
 - Start Homebridge
 - Attempt to configure ring and select "Link Account"
 - See error says "Please wait for the bridge to start"

### Expected behavior
 Expect to have Ring login page come up and enable me to link account and login.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.
![Screen Shot 2021-11-24 at 9 54 55 AM](https://user-images.githubusercontent.com/94707468/143281660-b4800769-1475-4f22-a485-fa9433353241.png)

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

{
    "platform": "Ring"
}

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by craftbyte** [comment]
@mountain2042 just FYI, if you haven't gotten it working yet, the `ring-auth-cli` way of getting a refresh token and the manually entering it into the config still works.

**Comment by dgreif** [comment]
cc @mkellsy

**Comment by mkellsy** [comment]
Please post your logs. The bridge isn’t starting need to find out why.

**Comment by dgreif** [comment]
Closing because the OP has not responded
