### ISSUE TITLE
Add a feature to hide chimes

### ISSUE THREAD

**Issue by craftbyte** [dgreif/ring#829]
# Feature Request

### Description
Just like we can disable unsupported device types and some other settings, users should be able to disable the Chime devices with a simple toggle switch.

### Describe the solution you'd like
Create a config setting similar to the existing ones called "hideChimes"

### Describe alternatives you've considered
Nothing at the moment.

**Comment by dgreif** [comment]
This can be done with the `hideDeviceIds` option.  I prefer not to add an option for hiding every device type, so this option allows you full control over what you would like to hide.  Let me know if that doesn't work for you.

**Comment by craftbyte** [comment]
I tried it with that, but it seems it doesn't work as chimes are a seperate array added to the devices. They also have numeric and not UUID-style IDs. Maybe we can instead make an array HideDeviceTypes where it would do the opposite of DeviceTypes? Or we can have a toggle that inverts the functionality of the deviceTypes config option?

**Comment by craftbyte** [comment]
@dgreif thoughts?

**Comment by dgreif** [comment]
I just tested hiding my chime using `hideDeviceIds` and it worked as expected.  Could you please try that approach again?  I do not want to add another option as the list has continued to grow over time.

**Comment by craftbyte** [comment]
Thanks, that was the problem. Did you think about creating a `hiddenDeviceTypes` option instead though?

**Comment by dgreif** [comment]
No, I don't want to create that option, sorry!  I'm trying to keep it to a reasonable level, and the config is already really complicated
