### ISSUE TITLE
motion / ring events stop triggering from today

### ISSUE THREAD

**Issue by 10der** [dgreif/ring#831]
# Bug Report

### Describe the Bug
motion / ring events stop triggering from today

### To Reproduce
node example.js                                                                                                                                                                                 Found 1 location(s) with 1 camera(s).
Refresh Token Updated:  [skiped]
Location [skipped] (xxxxxx-xxxx-0) has the following 1 camera(s):
- XXXXXXXX: Front Door (lpd_v1)

Location [skipped] (xxxxxx-xxxxx-0) has the following 0 device(s):
Listening for motion and doorbell presses on your cameras.

nothing happened after ring or / and motions

### Expected behavior
ring and /or motion events should be here

### Screenshots/Logs
[empty]

### Additional context
snapshot pics works properly

### Environment
 - OS: win11, (also) ```Linux debian 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64```
 - Node.js: v15.6.0 
 - NPM: 7.4.0
 - ring-client-api: latest 9.23.0

**Comment by threadhead** [comment]
I have noticed the same, ring devices do not update in HomeKit. Restarted HB and all started working again. Could this be an issue with the refresh token?

**Comment by 10der** [comment]
> I have noticed the same, ring devices do not update in HomeKit. Restarted HB and all started working again. Could this be an issue with the refresh token?

Idk. I am a developer and can debug this code, but I can’t find right now the root cause issue here.
Playing with hardware_id / create session / refresh token can’t light me on my way.
fsck ring… :(

**Comment by dgreif** [comment]
This is likely related to #815.  If your platform is preventing a consistent hardware id from being generated, then you will build up a lot of sessions on the Ring side and eventually stop receiving dings.  Can you try removing all the sessions in the Security Center in the Ring app and see if it fixes it temporarily?

**Comment by 10der** [comment]
@dgreif thank you so much for replying to me. 
on it. I'll keep you in the loop.

**Comment by 10der** [comment]
Yay! It’s works! Thank you so much!
btw, make hardware_id persistent
