### ISSUE TITLE
Error loading Ring Plugin

### ISSUE THREAD

**Issue by mikemarconi** [dgreif/ring#834]
# Bug Report

### Describe the Bug
<Recently my Ring plunging has stopped streaming my ring cameras or devices.  I have uninstalled and re-installed the ring plugin and I still is not working. 

 Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
<I should see the Ring cameras in HOOBS and in Homekit, but that is not happening.

### Screenshots/Logs
<12/6/2021, 3:13:52 PMRing Bridge starting
12/6/2021, 3:13:56 PMRing BridgeERRORError loading plugin "homebridge-ring"
12/6/2021, 3:13:56 PMRing BridgeWARNINGNo plugins installed.
12/6/2021, 3:13:56 PMRing BridgeLoading 1 platforms...
12/6/2021, 3:13:56 PMRing BridgeBridge is running on port XXX.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: 4.0.110
 - Node.js: 14.18.2
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: 9.23.0
 - homebridge: 1.3.4
 - hoobs: 4.0.110

**Comment by dgreif** [comment]
Did you recently turn on e2e encryption or bring Edge storage?

**Comment by mikemarconi** [comment]
No.  It just stopped working recently.  I then uninstalled and reinstalled the plugin.  Signed into my ring account through the plugin, but no go.  It had been working fine for months.

**Comment by mikemarconi** [comment]
I once again uninstalled the ring plugin and reinstalled it.  Logged into Ring via the plugin and it still doesn't work.  This is what it says in the log:

12/6/2021, 9:58:45 PMRing BridgeConfiguration change
12/6/2021, 9:58:45 PMringbridge stopping
12/6/2021, 9:59:14 PMRing Bridge starting
12/6/2021, 9:59:35 PMRing BridgeWARNINGNo plugins installed.
12/6/2021, 9:59:35 PMRing BridgeBridge is running on port 51836.
12/6/2021, 10:00:14 PMRing BridgeConfiguration change
12/6/2021, 10:00:14 PMringbridge stopping
12/6/2021, 10:00:19 PMRing Bridge starting
12/6/2021, 10:00:34 PMRing BridgeERRORError loading plugin "homebridge-ring"
12/6/2021, 10:00:34 PMRing BridgeWARNINGNo plugins installed.
12/6/2021, 10:00:34 PMRing BridgeLoading 1 platforms...
12/6/2021, 10:00:34 PMRing BridgeBridge is running on port 51836.
12/6/2021, 10:03:32 PMRing BridgeConfiguration change
12/6/2021, 10:03:32 PMringbridge stopping
12/6/2021, 10:03:37 PMRing Bridge starting
12/6/2021, 10:03:41 PMRing BridgeERRORError loading plugin "homebridge-ring"
12/6/2021, 10:03:41 PMRing BridgeWARNINGNo plugins installed.
12/6/2021, 10:03:41 PMRing BridgeLoading 1 platforms...
12/6/2021, 10:03:41 PMRing BridgeBridge is running on port 51836.
12/6/2021, 10:03:50 PMRing BridgeConfiguration change
12/6/2021, 10:03:50 PMringbridge stopping
12/6/2021, 10:03:55 PMRing Bridge starting
12/6/2021, 10:03:59 PMRing BridgeERRORError loading plugin "homebridge-ring"
12/6/2021, 10:03:59 PMRing BridgeWARNINGNo plugins installed.
12/6/2021, 10:03:59 PMRing BridgeLoading 1 platforms...
12/6/2021, 10:03:59 PMRing BridgeBridge is running on port 51836.

Any ideas?  Thanks for all of your help.

**Comment by dgreif** [comment]
It looks like the Ring plugin isn't properly installed.  I'd recommend you reach out to HOOBS support for help getting it installed properly

**Comment by cantchooseaname8** [comment]
I'm having a similar issue. Everything was working great until just recently. Now it is throwing a bunch of errors. Nothing works anymore (alarm, cameras, etc.). The errors keep saying that refresh token is not valid all of a sudden and it cannot authenticate.

**Comment by tsightler** [comment]
@cantchooseaname8 You know Ring is having a massive outage today, right?  Been ongoing for about 3 hours.

https://status.ring.com/

**Comment by cantchooseaname8** [comment]
> @cantchooseaname8 You know Ring is having a massive outage today, right? Been ongoing for about 3 hours.
> 
> https://status.ring.com/

Did not know that, but explains a lot. Thanks for the update!

**Comment by jonasophie** [comment]
> @cantchooseaname8 You know Ring is having a massive outage today, right? Been ongoing for about 3 hours.
> 
> https://status.ring.com/

Thanks for the link !

**Comment by dgreif** [comment]
Closing as this is not an issue with the plugin, but an improper install.  Please contact HOOBS support for more assistance
