### ISSUE TITLE
Error connecting to API

### ISSUE THREAD

**Issue by YouCanNotBeSerious** [dgreif/ring#835]
# Bug Report

### Describe the Bug
The error below has started appearing in Homebridge logs (unfortunately due to restarts i don't know when it started).  
The log indicates something going wrong with the API accessing the Ring servers, however when i refreshed the plugin's login tokens i got a notification from Ring that the account had been logged in to, so it doesn't seem to be an auth problem.

### To Reproduce
 - Start Homebridge
- See homebridge-ring logs

### Screenshots/Logs
[08/12/2021, 09:33:13] [homebridge-ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[08/12/2021, 09:33:29] [homebridge-ring] Request to https://api.ring.com/clients_api/dings/active failed with status 500. Response body: <html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>openresty</center>
</body>
</html>

[08/12/2021, 09:33:32] [homebridge-ring] Request to https://api.ring.com/clients_api/dings/active failed with status 500. Response body: <html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>openresty</center>
</body>
</html>

### Additional context
First seen on plugin version 9.23.  I reverted to plugin version 9.22.1 - same behaviour and error in the logs

### Homebridge Ring Config

```

    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config",
            "websocketCompatibilityMode": true
        },
        {
            "refreshToken": "x",
            "hideDoorbellSwitch": false,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "avoidSnapshotBatteryDrain": true,
            "sendCameraMotionNotificationsToTv": false,
            "sendDoorbellMotionNotificationsToTv": true,
            "cameraStatusPollingSeconds": 600,
            "cameraDingsPollingSeconds": 2,
            "locationModePollingSeconds": 0,
            "_bridge": {
                "username": "x",
                "port": 37615
            },
            "platform": "Ring"

```

### Environment

 - OS: Raspbian Lite (Homebridge downloaded image)
 - Node.js: 14.17.1
 - NPM: 7.17.0
 - homebridge-ring: 9.23 and 9.22.1
 - homebridge: N/A
 - hoobs: N/A

**Comment by jasonlboggs** [comment]
Amazon is experiencing a major outage today

**Comment by YouCanNotBeSerious** [comment]
Ha!  You sir, win the award for resolving this in less time than it took me to write it :-)

While we are here - THANK YOU for the plugin, it's used many times per day in my setup.
