### ISSUE TITLE
Very slow to load snapshots

### ISSUE THREAD

**Issue by Yeraze** [dgreif/ring#837]
# Bug Report

### Describe the Bug
On my iPhone or my Macbook, I launch Home and swipe to a room with a camera.. I see the camera tile with either a stale image or "No Response".  I immediately see the following on my Homebridge log:
```
[12/9/2021, 4:15:46 PM] [Ring] No snapshot cached for Living Room
[12/9/2021, 4:15:46 PM] [Ring] Loading new snapshot into cache for Living Room
[12/9/2021, 4:15:47 PM] [Ring] Snapshot cached for Living Room (1.196s)
```
However, it takes about 90s for the snapshop to appear on my device.

### Expected behavior
A relatively recent snapshot should appear in <10s.

### Screenshots/Logs
Logs in message, although there's not much info..

### Additional context
Homebridge 1.3.5, running in a docker container on a Synology NAS.
homebridge-ring v9.23.0

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
        {
            "refreshToken": "REDACTED",
            "hideDoorbellSwitch": true,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "sendCameraMotionNotificationsToTv": false,
            "sendDoorbellMotionNotificationsToTv": false,
            "debug": true,
            "hideDeviceIds": [
                "438ad5a0-522b-4997-a3fb-15b2eef09ac9",
                "90d29cf8-9a44-4804-b342-6112945e0aae"
            ],
            "platform": "Ring"
        },

```

**Comment by dgreif** [comment]
See https://github.com/dgreif/ring/wiki/Snapshot-Limitations#homebridge-limitations, which explains why the delay exists and why it cannot be improved.

**Comment by Yeraze** [comment]
That doesn't sound right... 

```handleSnapshotRequest will now return immediately with the last cached snapshot, no matter what. If there is no snapshot cached yet, it returns nothing. ```

If that's the case, then why when I open Home and wait 90s to get the screenshots.. Then close & re-open home a few minutes later, it shows all black/no-response frames for another 90s.. Shouldn't it return the previously cached snapshot?  I don't care that the snapshots are a few minutes old, they're better than Black frames.

**Comment by dgreif** [comment]
They are cached for 2 minutes, so if you leave the app and come back within 2 minutes you would not get a black frame.  There is no indication of what's stale vs current, so it's a balancing act between giving users confidence it's a valid snapshot, and working within the confines of HomeKit + Ring
