### ISSUE TITLE
Only Send Commands if Commands are different

### ISSUE THREAD

**Issue by donavanbecker** [dgreif/ring#838]
# Feature Request

### Description
 Only send commands if different.

### Describe the solution you'd like

If Alarm is disarmed don't send a disarm command, and same with any other commands.

![image](https://user-images.githubusercontent.com/9875439/145724910-44b9c947-157a-420f-af21-f37cb053953b.jpeg)

### Describe alternatives you've considered
 having command send twice when nothing has changed.

### Device data
  N/A

**Comment by dgreif** [comment]
Is this actually causing some issues, or is it just the extra logging that you would like to avoid?

**Comment by donavanbecker** [comment]
> Is this actually causing some issues, or is it just the extra logging that you would like to avoid?

It isn't causing issues, but wouldn't think we would want to send the command if it is already set at the current state. Also avoid the extra logging.

**Comment by dgreif** [comment]
I'm not too worried about extra logging 😉.  I'd prefer to keep sending the extra command in case the user is toggling back and forth quickly and the local state doesn't accurately reflect the actual state
