### ISSUE TITLE
Fixed port or port range

### ISSUE THREAD

**Issue by ChristianKlee** [dgreif/ring#84]
Hello,
my Homebridge is running on a Synology NAS with an active firewall. 
Is it possible to run a doorbell on a fixed port or a port range because I don't like to deactivate my firewall completely or to open the port on the NAS after every Homebridge restart.

**Comment by dgreif** [comment]
After some digging, it looks like there is a `ports` option that you can pass to homebridge that will fix the port range for camera accessories: https://github.com/nfarina/homebridge/blob/6d8fe2fd27ec3935346637a86465d4814099d919/config-sample.json#L10-L14.  Just make sure you give it enough ports to handle all of your cameras, maybe times 2 so in case they get blocked up for some reason.

@ black01gt this might help you out as well (#76)

**Comment by dgreif** [comment]
@ChristianKlee I'm going to assume that worked for you.  Please reopen if you need something from my end.
