### ISSUE TITLE
Ring Solar Pathlights Not Charging When Using Homebridge-Ring Plugin

### ISSUE THREAD

**Issue by afroeagle** [dgreif/ring#846]
# Bug Report

### Describe the Bug
Ring Solar Pathlights Not Charging When Using Homebridge-Ring Plugin

### To Reproduce

1. Start Homebridge with Homebridge-ring plugin
2. Configure plugin per instructions
3. Light controls work, motion detection works
4. Lights do not charge and show as "Not Chargeable" in the Homebridge UI
5. Tried removing the plugin and leaving the lights disconnected from Homebridge for a couple of days and they did not die so there must be something going on with the plugin
6. Tried making Homebridge-ring a Child Bridge with no change
7. Tried toggling Motion Detection on/off inside the Ring app for different lights and waiting a day to see if it made a difference, it did not
8. Made sure the Ring app light sensor setting was set so to the very lowest so that they turn off at the first hint of daylight, but also tried playing with different levels for different lights with no change
9. Tried on Homebridge versions 1.3.8 and 1.3.9

### Expected behavior
Solar Pathlights are chargeable and should charge and show as chargeable/charging

### Screenshots/Logs
![image](https://user-images.githubusercontent.com/46386620/147680754-6826c8bb-6146-46e8-8cf2-547c520ce551.png)

### Additional context
The lights only run for 4 hours a day at 10% brightness. The battery life drops by ~10% during this time so they should definitely be charging during the day enough to not die.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

        {
            "refreshToken": "token",
            "hideLightGroups": false,
            "beamDurationSeconds": 32767,
            "platform": "Ring",
            "_bridge": {
                "username": "MAC",
                "port": 32374
            }

```

### Environment

 - OS: macOS 12.1
 - Node.js: 16.13.1
 - NPM: 8.3.0
 - homebridge-ring: 9.23.0
 - homebridge: 1.3.9
 - hoobs: N/A

**Comment by dgreif** [comment]
Thanks for the detailed issue!  One point that I need a little clarity on - are the solar lights actually _dying_ when the plugin in active, or is it just the `Not Chargeable` that has you concerned? I can definitely look into the UI aspect of it, but I can't see a way that the plugin would actually prevent the lights from charging.  I think the UI is just showing incorrect information.

**Comment by afroeagle** [comment]
> 

Compared to when I posted the screenshot, the charge has gone up a few percentage points. So I stand corrected - they do appear to be charging, just not reporting that they are in charging mode. Anecdotally, they just seem to be charging slower with the plugin than before I had implemented it, but that could be completely wrong.

**Comment by dgreif** [comment]
Based on that update, I do not think there is any actual impact on charging the lights if they are connected to the plugin.  The "Not Chargeable" label that you see is because Ring does not appear to report any charging status for these lights.  I have a few of the solar path lights (all of which were actually fully dead when you opened the issue), and I'm double checking the data from them to confirm.  So far, I've only seen `"batteryStatus": "warn"` and `"batteryStatus": "ok"`, but nothing like `"batteryStatus": "charging"` that would indicate the lights can/are being charged.  The plugin infers what it can from the data, but in this case there is simply no indication that the solar lights even support charging.

**Comment by afroeagle** [comment]
Thank you for your efforts!

**Comment by afroeagle** [comment]
An update here, good sir. I happened to peak at my Homebridge → Accessories interface and saw this:

![homebridge ring charging indicator](https://user-images.githubusercontent.com/46386620/150215244-782216bc-b9a0-4787-9a59-b6e5190a8c23.png)
