### ISSUE TITLE
after initial install, Ring Link button is missing.

### ISSUE THREAD

**Issue by busyaZ** [dgreif/ring#849]
# Bug Report

### Describe the Bug
 
My apologies, i am a total noob. installed unraid 15 days ago. so all of this will def. take some time getting used to.
I installed hoobs container. connected my garage door. was able to add it to home app.
then decided to add ring doorbell. installed the plugin. however, i dont see a link button to start sign in process with ring to get the token. would anyone be able to help with this issue, please? i am completely lost. thanks in advance.

### To Reproduce
 - Start Homebridge
 - Attempt to ... 
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
Please reach out to HOOBS support for issues with the HOOBS UI
