### ISSUE TITLE
Can No Longer Add Camera

### ISSUE THREAD

**Issue by Sunoo** [dgreif/ring#85]
I tried removing and adding the camera to Home again, to see if I could finally get live streaming to work. However, now nothing shows up when I go to Add Accessory, so I can't readd it.

**Comment by dgreif** [comment]
Did you try this?  https://github.com/dgreif/ring/wiki/Camera-Troubleshooting#cannot-add-camera-from-home

**Comment by Sunoo** [comment]
I could have sworn I did, but maybe I had missed a step, because I just tried again and that fixed it.

**Comment by sushenmathur** [comment]
Having the same issue, I tried deleting the AccessoryInfo and IdentifierCache json files for a {uniqueId} from the persist folder and I don't see that camera in the HomeKit and when I restart homebridge the files for that {uniqueId} reappears but the camera is not displaying in the Add accessory section. Please help

**Comment by dgreif** [comment]
@sushenmathur make sure your phone is on the same network as your homebridge server while adding the camera.  I would delete those files again and restart homebridge before you try again just to make sure the old stuff is all cleared out

**Comment by sushenmathur** [comment]
@dgreif thank you, i recreated the entire docker container for homebridge and it worked.
