### ISSUE TITLE
Ring Chime stopped on all HomePods

### ISSUE THREAD

**Issue by qsgithub1** [dgreif/ring#852]
# Bug Report

### Describe the Bug
Home app notifies when someone presses the Ring Doorbell. No errors are shown on the HomeBridge Server status

### To Reproduce
- Press the door bell

### Expected behavior
 A clear and concise description of what you expected to happen.
Ring all iPhones and HomePods

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

[10/01/2022, 11:16:18] [Ring] Front Door Doorbell Pressed
[10/01/2022, 11:16:18] [Ring] Front Door Doorbell Pressed
[10/01/2022, 11:29:55] [Ring] Preparing Live Stream for Front Door
[10/01/2022, 11:29:56] [Ring] Waiting for stream data from Front Door (0.888s)
[10/01/2022, 11:29:57] [Ring] Received stream data from Front Door (1.998s)
[10/01/2022, 11:29:57] [Ring] Streaming active for Front Door
[10/01/2022, 11:30:02] [Ring] Stopped Live Stream for Front Door

-> No errors but Chime is not working on HomePod's 

### Additional context
 Add any other context about the problem here.
I have tried to remove Ring from Homebridge and reinstall same issue.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
{
    "refreshToken": "****",
    "hideCameraLight": false,
    "hideCameraMotionSensor": false,
    "sendCameraMotionNotificationsToTv": true,
    "_bridge": {
        "username": "****",
        "port": 33422
    },
    "platform": "Ring"
}
```

### Environment

- Homebridge on Pi v1.3.9

Thank you

**Comment by qsgithub1** [comment]
Just to add I've also done a restore of the HomePod and Chime is not working. Its so weird because Home App knows the doorbell rang and the Chime on HomePod is switched On!

**Comment by dgreif** [comment]
If the Home app knows the doorbell rang, then the plugin is working as expected.  It's possible your settings got changed on your HomePod, or that there is a bug in the HomePod, but nothing I can fix from the plugin side.
