### ISSUE TITLE
Still image not refreshing

### ISSUE THREAD

**Issue by jchristianj** [dgreif/ring#854]
# Bug Report

### Describe the Bug
I have been affected by this rare Apple HomeKit issue: https://www.macrumors.com/2022/01/05/homekit-camera-thumbnail-issue/
with my two Ring doorbells (Ring Pro and Ring 2 battery). Thumbnails didn't update in Apple's home app, and there was no timer in the lower right image corner, just the word "now".
So I removed the Ring bridge from home, created a new child bridge with the Ring plugin on my Pi, and re-added. Multiple times. I wanted to avoid signing out of iCloud, as I am using Apple pay with many cards and signing out/in is a real hassle and much of work for me.
Now I have it working again... at least partially. The Pro's still images do refresh after 10 seconds, but the Ring2 thumbnail does not. It remains on the last image from latest live view in the home app.

### To Reproduce
No idea.

### Expected behavior
Thumbnail shoud refresh

### Screenshots/Logs
Log:
[11/01/2022, 14:32:55] [homebridge-ring] Snapshot for Ring (cocoa_doorbell - Doorbell Gen 2) failed to refresh after 70 attempts.  This is normal behavior since this camera is unable to capture snapshots while streaming
--> Camera is NOT streaming

### Additional context
none.

### Homebridge Ring Config
{
    "refreshToken": "secret",
    "platform": "Ring",
    "_bridge": {
        "username": "0E:60:BE:38:6A:AB",
        "port": 50508
    }
}
### Environment

OS | Raspbian GNU/Linux Buster (10)
homebridge 1.3.9
node.js v16.13.1
npm v8.1.2

**Comment by dgreif** [comment]
Please read through https://github.com/dgreif/ring/wiki/Snapshot-Limitations to understand some of the limitations, especially with battery cameras.  

Given the camera is not streaming and was unable to fetch an image, I'd recommend pulling out the battery and putting it back in.  Another thing you can test is opening the Ring app to see if it can pull a snapshot from that camera.

**Comment by jchristianj** [comment]
Hi, yes fully understand that limitation. But what puzzles me is that since I re-added the Ring child bridge the behavior of the battery cam has changed. Before that homekit issue it refreshed every 10 seconds on home WiFi, now it doesn't refresh at all.

**Comment by dgreif** [comment]
The camera itself might be having issues.  Does it refresh in the Ring app?

**Comment by jchristianj** [comment]
Weird! Just reset and re-added the cam to my Ring account. During installation it updated its firmware. Now it’s updating the thumbnails in home app every 10 seconds as it should. Thanks a lot, issue can be closed!

**Comment by malmentm** [comment]
This was a general problem also affecting native HomeKit cameras.
