### ISSUE TITLE
Enable non-motion detection snapshot ("upon button-press") for Ring Door View Cam?

### ISSUE THREAD

**Issue by TheSwede86** [dgreif/ring#855]
# Feature Request

### Description
I have a "Door View Cam";
https://en-uk.ring.com/products/door-view-cam
which I've disabled motion detection on or even the "knock" function due to privacy concerns since I live on floor 2/3 and don't want notifications when my neighbors walk up or down the stairs.

I tried out "[ring-to-android-tv](https://github.com/stevenflesch/ring-to-android-tv)" and got it working after modifying the "packages.json" to the latest version of this project; https://github.com/stevenflesch/ring-to-android-tv/issues/19

However when testing it I encountered this error;
```
$ node app.js
Refresh Token Updated
Found location: <my-location>
         - Found Door View Cam named Front Door.
Sent notification successfully: ring-to-android-tv - Ring notifications started!
[Fri Jan 14 2022 21:00:39 GMT+0100 (Central European Standard Time)] Doorbell pressed on Front Door camera.
[ERROR] Unable to retrieve snapshot because:Motion detection is disabled for Front Door, which prevents snapshots from this camera.  This can be caused by Modes settings or by turning off the Record Motion setting.

Snapshot saved!
Sent notification successfully: Doorbell Ring - Doorbell rung at Front Door!
```

So I did not receive a notification on my TV which I guess is due to the fact that motion detection is off for my camera and was wondering if "ring-client-api" supports sending events when you press the actual button as opposed to motion detection?

If so I guess its up to the developer to update his project (sadly I don't know node.js otherwise I might help) otherwise it might be a feature request for this project?

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
`{"locations":[{"name":"my-location","cameras":[{"description":"Front Door","subscribed":true,"subscribed_motions":true,"battery_life":"83","external_connection":false,"firmware_version":"Up to Date","kind":"doorbell_portal","settings":{"cv_settings":{"detection_types":{"human":{"enabled":false,"mode":"none","record":null,"notification":false},"loitering":{"enabled":false,"mode":"none","record":null,"notification":false},"motion":{"enabled":true,"mode":"edge","record":null,"notification":true},"moving_vehicle":{"enabled":false,"mode":"none","record":null,"notification":false},"other_motion":{"enabled":false,"mode":"none","record":null,"notification":false},"package_delivery":{"enabled":false,"mode":"none","record":null,"notification":false},"package_pickup":{"enabled":false,"mode":"none","record":null,"notification":false}},"threshold":{"loitering":10,"package_delivery":2},"triggers":[]},"cv_paid_features":{"human":true,"loitering":true,"motion":true,"other_motion":true,"package_delivery":true,"package_pickup":true,"cv_triggers":true},"concierge_settings":{"mode":"disabled"},"other_paid_features":{"alexa_concierge":true,"sheila_cv":true,"sheila_recording":true},"sheila_settings":{"cv_processing_enabled":false,"local_storage_enabled":false},"server_settings":{"ring_media_server_enabled":true},"zone_settings":{"motion":[{"name":"Default Zone","state":"enabled","properties":{"detection_types":["motion"]},"vertices":[{"x":0,"y":0.4},{"x":0.333333,"y":0.4},{"x":0.666666,"y":0.4},{"x":1,"y":0.4},{"x":1,"y":1},{"x":0.666666,"y":1},{"x":0.333333,"y":1},{"x":0,"y":1}]}]},"offline_motion_event_settings":{"subscribed":true,"enabled":false,"max_upload_kb":5000,"resolution_p":360,"frequency_after_secs":2,"period_after_secs":30},"lite_24x7":{"subscribed":true,"enabled":true,"frequency_secs":3600,"resolution_p":360},"enable_vod":1,"exposure_control":2,"motion_zones":[1,1,1,1,1],"motion_snooze_preset_profile":"low","motion_snooze_presets":["none","low","medium","high"],"live_view_preset_profile":"middle","live_view_presets":["low","middle","high","highest"],"pir_sensitivity_1":5,"vod_suspended":0,"doorbell_volume":2,"vod_status":"enabled","chime_settings":{"type":2,"enable":true,"duration":10},"video_settings":{"encryption_enabled":false},"advanced_motion_detection_enabled":true,"advanced_motion_zones":{"zone1":{"name":"Default Zone","state":2,"vertex1":{"x":0,"y":0.4},"vertex2":{"x":0.333333,"y":0.4},"vertex3":{"x":0.666666,"y":0.4},"vertex4":{"x":1,"y":0.4},"vertex5":{"x":1,"y":1},"vertex6":{"x":0.666666,"y":1},"vertex7":{"x":0.333333,"y":1},"vertex8":{"x":0,"y":1}},"zone2":{"name":"Zone 2","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}},"zone3":{"name":"Zone 3","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}}},"advanced_motion_detection_human_only_mode":false,"enable_audio_recording":true,"people_detection_eligible":true,"live_view_disabled":false,"ignore_zones":{"zone1":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone2":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone3":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone4":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}}},"enable_rich_notifications":true,"rich_notifications_billing_eligible":true,"loitering_threshold":10,"advanced_motion_detection_types":[],"motion_detection_enabled":false,"rich_notifications_scene_source":"cloud","advanced_motion_zones_enabled":true,"advanced_motion_zones_type":"8vertices","advanced_pir_motion_zones":{"zone1_sensitivity":5,"zone2_sensitivity":5,"zone3_sensitivity":5,"zone4_sensitivity":5,"zone5_sensitivity":5,"zone6_sensitivity":5},"knock_detection_enabled":false,"knock_sensitivity":1,"enable_ir_led":true,"rich_notifica-uuid":false},"features":{"motion_zone_recommendation":false,"motions_enabled":true,"show_recordings":true,"show_vod_settings":true,"rich_notifications_eligible":true,"show_24x7_lite":true,"show_offline_motion_events":false,"cfes_eligible":false,"sheila_camera_eligible":true,"sheila_camera_processing_eligible":true},"owned":true,"alerts":{"connection":"online","outdoor_module_connected":true,"ota_status":"successful"},"motion_snooze":null,"stolen":false,"is_sidewalk_gateway":false,"created_at":"2021-12-22T11:53:35Z","shared_at":null,"active_schedule_uuid":null,"health":{"device_type":"doorbell_portal","last_update_time":1642190477,"connected":true,"rss_connected":true,"vod_enabled":true,"sidewalk_connection":false,"floodlight_on":false,"white_led_on":false,"night_mode_on":false,"hatch_open":false,"packet_loss":0,"rssi":-44,"battery_voltage":3936,"wifi_is_ring_network":false,"ota_status":"successful","ext_power_state":0,"network_connection_value":"wifi","ac_power":0,"external_connection":false,"outdoor_module_connected":1,"battery_percentage":83,"battery_percentage_category":"very_good","firmware_version":"7.0.70","rssi_category":"good","battery_voltage_category":"good","second_battery_voltage_category":"unknown","second_battery_percentage_category":"unknown","battery_save":false,"firmware_version_status":"Up to Date","stream_resolution":100,"bandwidth_last_time":1640174281,"bandwidth":4800},"deactivated_at":null}],"chimes":[],"devices":[]}],"amazonKeyLocks":[]}`

**Comment by malmentm** [comment]
I have the same wish for this functionality. Ability to receive snapshops with motions detection disabled. It might be possible because you can set the doorbell to take a snapshot every now and then with the snapshot capture feature.

**Comment by dgreif** [comment]
This limitation on snapshots is put in place by Ring, and isn't something the `ring-client-api` can work around.  Unfortunately there is nothing I can do to help here.

Regarding `ring-to-android-tv`, that is a separate project that could be updated to handle this error more gracefully.
