### ISSUE TITLE
[Feature request] changelog in Homebridge UI

### ISSUE THREAD

**Issue by ifeign** [dgreif/ring#86]
This plugin is amazing so I hate to ask more of you. I use several plugins that display the changelog within the config UI after updating. 

Since your plugin is so frequently updated it would be beneficial to see these regular changes within Homebridge, saving a visit to github. It's also an opportunity to inform people about new major changes (updating 3.x to 4.x, your new wiki etc) and possibly reduce the number of people posting issues about things you've already addressed.

A great example of this is Homebridge-Neato. This plugin also has another really cool feature, the config schema, which allows users to create a perfectly formatted config by filling in forms and multiple choice options vs doing it all by hand.. but that's something for another time.

**Comment by dgreif** [comment]
I manage all my packages directly with npm, not a GUI, so I didn't realize I was missing out on a way to communicate.  Which specific config UI are you using (I think there are a few)?  Looks like homebridge-neato puts their changelog in their GitHub releases, which is probably what the UI pulls from.  That is pretty easy for me to add and a good practice to follow anyways.  I'll try to get it done in the next week or two.  Great suggestion!

As for the config file, it looks like this might be what generates the form: https://github.com/naofireblade/homebridge-neato/blob/master/config.schema.json.  Where do you see that form show up?

**Comment by ifeign** [comment]
Thanks for looking into this. I use [Homebridge-Config-UI-X](https://github.com/oznu/homebridge-config-ui-x). Which I believe is the most widely used one. It's also packaged with HOOBS so we'll probably see a lot more of it.

This is what the schema looks like
<img width="682" alt="Screen Shot 2019-07-31 at 8 52 09 AM" src="https://user-images.githubusercontent.com/32289760/62227343-950ee080-b370-11e9-8d52-56f037b3e482.png">
<img width="577" alt="Screen Shot 2019-07-31 at 8 52 19 AM" src="https://user-images.githubusercontent.com/32289760/62227344-950ee080-b370-11e9-8448-c823b82ecbee.png">

**Comment by ifeign** [comment]
Here's a more detailed example of a config.schema.json https://github.com/oznu/homebridge-config-ui-x/blob/master/config.schema.json

**Comment by benfysh** [comment]
There is also a developer guide in the [Config UI X wiki](https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI)

**Comment by ifeign** [comment]
>There is also a developer guide in the [Config UI X wiki](https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI)

@benfysh so much more useful than what I found. Idk how I missed this wiki page.

**Comment by dgreif** [comment]
@ifeign I really appreciate you suggesting this change.  Anything that I can do to make it easier for users to get set up and update the plugin, I am happy to do!  Here are some screenshots of the new features:

## Release Notes
![image](https://user-images.githubusercontent.com/3026298/62318090-e04bf080-b44f-11e9-9160-f7d154241b58.png)

## Changelog
![image](https://user-images.githubusercontent.com/3026298/62318134-fc4f9200-b44f-11e9-897e-17258490194f.png)


## Settings UI
![image](https://user-images.githubusercontent.com/3026298/62318116-ecd04900-b44f-11e9-94aa-443825d4190c.png)

### Option Config
![image](https://user-images.githubusercontent.com/3026298/62318122-f194fd00-b44f-11e9-97e5-dd6998c413fc.png)

**Comment by ifeign** [comment]
Awesome work @dgreif. This makes it almost impossible to mess up when configuring the plugin, which is great for those newer to Homebridge (most of the Homebridge posts on Reddit are config.json formatting issues). You've created one of the most well-rounded Homebridge plugins out there!

**Comment by jamesg311** [comment]
@dgreif you are amazing. Seriously, the world will be a better place with more devs like you. I hope you have the opportunity in life to help make that a reality—either from work or by mentoring others.
