### ISSUE TITLE
My HomePods stopped chiming

### ISSUE THREAD

**Issue by Reeves808** [dgreif/ring#869]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

My HomePods stopped chiming when someone presses the doorbell. It happened also when they have been on 15.2 but it also does not work on 15.3. 
Nothing has been changed. It stopped from one hour to the other. 

This has happened before but restarting the Homebridge Server was enough to fix this. But this does not help this time. 

All HomePods are set to "on" for chiming.
I refreshed the token
I rolled back to Homebridge 1.3.9 because I thought it happened with 1.4.0 but there was no change at all. 
There is also no error Message in the console in homebridge
The Home App in iOS sends a "someone ringed the doorbell" Push notification. So this works
HomePods are a few Minis and a big one.

### To Reproduce
Ring the Doorbell

### Expected behavior
 A clear and concise description of what you expected to happen.

HomePods should chime as they have done all the time

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: Raspbian GNU/Linux Buster (10)
 - Node.js: v14.17.4
 - NPM: 6.14.14
 - homebridge-ring: latest
 - homebridge: 1.4.0
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by malmentm** [comment]
Don't know if it help you but it still works for me with Homebridge 1.4.0 and laters software on all iOS devices.

**Comment by Reeves808** [comment]
Like I‘ve written - everything is updated 

the only two thing which are not up2date are npm and node 

I haven’t heard many good things about updating them so I did not touch them for months

**Comment by dgreif** [comment]
Do you get notifications from HomeKit on your phone when the doorbell is pressed?

**Comment by Reeves808** [comment]
Hey, yes this works fine so far.

**Comment by Reeves808** [comment]
> Do you get notifications from HomeKit on your phone when the doorbell is pressed?

Hey, yes this works fine so far.

**Comment by dgreif** [comment]
If the notifications are showing from HomeKit, then homebridge is properly communicating the event.  It's likely a bug from Apple causing your issues and not something I can fix here.  Sorry!
