### ISSUE TITLE
Live Streams with Apple Airport Routers

### ISSUE THREAD

**Issue by dgreif** [dgreif/ring#87]
Per conversation in #74, it appears that Apple Airport Routers are blocking the current method for "hole-punching" through NAT.  Need to investigate alternate approaches to the problem such as port forwarding for a specific range that we can use for RTP, or figure out what configuration needs to be set on the Airport routers to allow this to work.  DMZing the homebridge server appears to fix the issue, but this is very dangerous as it opens every port on that device to the outside world.

**Comment by Sunoo** [comment]
Not an ideal solution, but what I've done currently is open ports 10001-65535 (the highest port used by the Airport itself is 10000, so including that causes problems). It's still pretty kludgy, but it's better than DMZing the entire device. The ideal solution would still be to be able to choose specific ports, as mentioned in the other thread.

<img width="483" alt="image" src="https://user-images.githubusercontent.com/11802168/62241545-5a746a80-b3a7-11e9-8f51-9fe558aa2cc9.png">

**Comment by dgreif** [comment]
I did some research and found that Apple Airports don't support the normal protocols for opening NAT ports.  They do, however, support NAT-PMP which should get us what we need.  I just release v`5.0.0` which will now attempt to negotiate with the router using NAT-PMP or whatever protocol is supported.  Can someone with an Airport try disabling the DMZ and port forwarding settings and see if it works out-of-the-box now?

**Comment by Sunoo** [comment]
Looks like you nailed it! I just disabled my port forwards, and the steaming video works perfectly. Thanks so much.

**Comment by dgreif** [comment]
![image](https://user-images.githubusercontent.com/3026298/62306761-4aa46700-b437-11e9-810f-1fee29cb09f5.png)

@onefish2 @Frederik840 @metroidmen Can you give v`5.0.0` a try with DMZ/port forwarding disabled?  I'm hoping this solves all remaining live stream issues 🤞

**Comment by onefish2** [comment]
@dgreif. Working great without the Pi running homebridge in the DMZ or having port forwarding enabled. You are a ROCK-STAR!!!

**Comment by Frederik840** [comment]
Working perfectly! 😀

**Comment by metroidmen** [comment]
@dgreif

This issue is maddening. It still doesn’t work properly for me. 

Every update, or reboot, it starts out fine. Getting snapshots, live streams, etc. But after a while it just stops working. No snapshots. Streams won’t connect. Sometimes after a few hours, snapshots start back up magically. But stop shortly after. Same with live-streams, albeit more rare. 

I’ve tried reinstalling. I’ve tried resetting up my homebridge entirely. I’ve port forwarded and DMZed it. It does the exact same thing. 

When it works, it works great. But then it just stops entirely. It’s extremely frustrating. 

I have a really solid network and have no network issues with any devices, including other HomeKit and homebridge devices. The devices pull up just fine in the ring app whenever I need them.

**Comment by dgreif** [comment]
@metroidmen I think you are the only one still having issues at this point.  Have you checked the homebridge logs when it fails?  Do other devices from Ring still work (like alarm/lights) when the camera feeds fail?

**Comment by metroidmen** [comment]
The logs usually just stick on “preparing live stream” and never do anything else.

**Comment by metroidmen** [comment]
Sometimes it says snapshot requested but the snapshot never updates in the app.

**Comment by dgreif** [comment]
Both of those things point to a situation where Ring is not responding to requests from the plugin.  I can't say for sure what would cause it, but my guess would be a poor connection between your camera and your router.  Beyond that, you would need to dive into the code and do some debugging yourself.  I really want this plugin to work for everyone, but there are some situations where I just can't help any farther.  Without more info, there is nothing for me to fix.

**Comment by metroidmen** [comment]
Well if it has that issue and I immediately open the ring app it’ll connect just fine. I have this issue with all 5 of my cameras simultaneously. 

I don’t know anything about coding so I’m completely lost.
