### ISSUE TITLE
Ring exposed battery level

### ISSUE THREAD

**Issue by fratinize** [dgreif/ring#871]
Did I just miss it? Is there a way to expose the battery level of my ring doorbell cam?
# Feature Request

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by malmentm** [comment]
Works with my Door View Cam

**Comment by fratinize** [comment]
Hmm Shows on Config Page of Cam TY
