### ISSUE TITLE
Ring Keypad Brightness

### ISSUE THREAD

**Issue by CHAMLEX** [dgreif/ring#872]
# Feature Request

### Description
Adjustment of Keypad brightness via home (Eve) app.

### Describe the solution you'd like
Currently keypad volume can be adjusted in the Eve night allowing automations to raise the keypad volume during the day and lower volume at night.  Similarly I would love to be able to adjust the brightness based on the time of day.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
Device is currently exposed to Homekit

**Comment by apexad** [comment]
Why make this exclusive to Eve?  Home app can handle brightness via light bulb

**Comment by CHAMLEX** [comment]
> Why make this exclusive to Eve?  Home app can handle brightness via light bulb

True, but the keypad is only exposed to the Eve or other third party apps and shows up unsupported in the Home app. I figured it would be less effort to add it on versus making it appear supported in the Home app.

**Comment by kjellywang** [comment]
The new release does start to support the adjustment of basestation and keypad light, but the hiding function for these two accesarries appears to be not working as expected.

**Comment by kjellywang** [comment]
@dgreif The new release does start to support the adjustment of basestation and keypad light, but the hiding function for these two accessories appears to be not working as expected.

**Comment by dgreif** [comment]
@kjellywang I removed the `hideUnsupportedDevices` option now that those devices have some _supported_ functionality in the Home app. If you would like to hide them, please use the `hideDeviceIds` option and add the id for each that you do not wish to see.

**Comment by kjellywang** [comment]
Thank you very much for the quick reponse. Where can I find the id for the devices that I don't want to see.

**Comment by dgreif** [comment]
They are in the logs when you reboot homebridge

**Comment by kjellywang** [comment]
Great! Thank you very much. Fixed it.
