### ISSUE TITLE
Add new Characteristics that Match Ring Characteristics

### ISSUE THREAD

**Issue by donavanbecker** [dgreif/ring#874]
# Feature Request

### Description
Can you add the new camera Characteristics?

### Describe the solution you'd like
 
Can you add the new camera Characteristics using the new Camera Service `CameraOperatingMode`?
- [ ] HomeKitCameraActive
- [ ] ManuallyDisabled
- [ ] NightVision
- [ ] CameraOperatingModeIndicator
- [ ] EventSnapshotsActive
- [ ] PeriodicSnapshotsActive
- [ ] DiagonalFieldOfView
- [ ] ThirdPartyCameraActive

https://developers.homebridge.io/#/service/CameraOperatingMode

### Describe alternatives you've considered
 Just use ring app, but would be nice if you could access most of it in the Home app.

**Comment by dgreif** [comment]
I gave this a shot but the new characteristics didn't appear to do anything.  Might be that they are HKSV specific

**Comment by donavanbecker** [comment]
Thanks for trying
