### ISSUE TITLE
Why does the plugin add HomeKit motion sensors to Ring A19 & BR38 bulbs? They don't exist on these bulbs.

### ISSUE THREAD

**Issue by MoTechnicalities** [dgreif/ring#877]
# Bug Report

### Describe the Bug
The plugin is adding an annoying and unnecessary motion sensor tile to Ring bulbs. Ring bulbs have no such motion sensor.

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
![image](https://user-images.githubusercontent.com/68468472/153120138-61c21cf3-b9d3-4acb-93f6-dfa355dc7c21.jpeg)

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
Thanks for letting me know! Would you mind following the steps in https://github.com/dgreif/ring/wiki/Data-Discovery and posting the results here?  That will give me a better idea of how Ring presents these specific lights, and how I can avoid adding the motion sensor.

**Comment by dgreif** [comment]
Closing because the data-discovery results have still not been posted.  Happy to get this fixed if you are able to post those results.
