### ISSUE TITLE
Add ability to create "non secure" switches for secure items

### ISSUE THREAD

**Issue by sean256** [dgreif/ring#878]
# Feature Request

### Description
Allow a smart lock device to be exposed as a non secure switch.
Why? As it stands now, it's impossible to create a "no confirm" Shortcut for any device which HomeKit considers to be "Secure".

Example shortcut:
- Scan NFC tag -> unlock door
- Connect to wifi -> unlock door

The above examples will _not_ work if `Ask Before Running` is disabled in the Shortcuts app.

### Describe the solution you'd like
Add a new JSON configuration to list device IDs you'd like non-secured switches for, perhaps:

```
{
     "createAdditionalSwitchForSecuredDevice" : ["477e4800-fcde-4493-969b-d1a06f683102", "5aaed7a7-06df-4f18-b3af-291c89854d60"]
}
```

Allowed device types could be smart locks, garage doors, or any other secure devices that can be represented as a switch. This would create _additional_ accessories, not replace them.

**Comment by cantchooseaname8** [comment]
This can be accomplished with the Dummy Switches plugin. It will do exactly what you want. I have a Dummy Switch set up to turn on my alarm, lock/unlock the doors, etc. You just need to set up HomeKit automations to go with it (i.e. scan NFC tag > turn on dummy switch; when the dummy switch is turned on > unlock door)

**Comment by sean256** [comment]
@cantchooseaname8 that sounds excellent. Do you have a link to this plugin?

**Comment by dgreif** [comment]
https://github.com/dgreif/ring/tree/master/homebridge#changes-modes-on-arriveleave-home has the details for setting it up
