### ISSUE TITLE
HomeKit Secure Video support?

### ISSUE THREAD

**Issue by AssetBurned** [dgreif/ring#879]
# Feature Request

### Description
HomeKit Secure Video support?

### Describe the solution you'd like
With the Camera UI plugin and Homebridge 1.4.0 now supported the foundation should be there to also support secure video

### Describe alternatives you've considered
using functions from the Ring app

**Comment by malmentm** [comment]
See https://github.com/dgreif/ring/issues/868

**Comment by AssetBurned** [comment]
guess duping into https://github.com/dgreif/ring/issues/860 might be better.
