### ISSUE TITLE
How do I install v9.25.0-beta.1

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#887]
How do I install v9.25.0-beta.1

**Comment by dgreif** [comment]
<img width="739" alt="image" src="https://user-images.githubusercontent.com/3026298/154198986-917c11da-d7c3-491b-a5c7-c1f40ba0bf6e.png">

Click the wrench 

<img width="270" alt="image" src="https://user-images.githubusercontent.com/3026298/154199013-b43e51cf-79a2-4623-904f-7cb00536d649.png">

<img width="517" alt="image" src="https://user-images.githubusercontent.com/3026298/154199014-8c7f5049-47d2-4646-9570-b0e0db2f95e9.png">

**Comment by adavison007** [comment]
Great, many thanks

Sent from my iPhone

On 16 Feb 2022, at 04:58, Dusty Greif ***@***.***> wrote:

﻿


Click the wrench





—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
