### ISSUE TITLE
Add Floodlight Pro to device list

### ISSUE THREAD

**Issue by tsightler** [dgreif/ring#889]
# Bug Report

### Describe the Bug
Not really a bug per-se, at least I don't think so, but I'm starting to get some queries about Floodlight Pro, which currently isn't in the device list ("kind": "floodlight_pro").  Admittedly it seems to mostly just work anyway, although a user reported that they don't get light/siren switches, which I don't understand as the device discovery data looks completely normal to me.  I'd think the only side effect of not being in the list would be the model showing as "Unknown Camera".  Am I wrong about that?

### To Reproduce
Have a Floodlight Pro, see it's not supported!  :)

### Expected behavior
Device should report correct model (Floodlight Pro)

### Screenshots/Logs
Take a look at device discovery data from a Floodlight Plus vs Floodlight Pro in this ticket:
https://github.com/tsightler/ring-mqtt/issues/319#issuecomment-1038349376

I don't see anything that should keep it from not working, only the "Unknown Model" issue, which is super minor, but I figured I'd provide the information needed to add it anyway as I'm sure your users will end up with this camera soon enough as well as I already have two reporting the issue and another with the camera on the way.

Thanks!

**Comment by tsightler** [comment]
Thanks for the quick response.  I'm currently working on a 5.0 release of ring-mqtt that has some core changes so I'll give the 10.0.0-beta a spin and see how it works.  Can I assume it's using WebRTC?  I've been poking around the Ring web app myself but understanding all the WebRTC stuff it's a little beyond my current skill level and I haven't had enough time to really spin on it.

**Comment by tsightler** [comment]
Ah, nevermind, I see the comments on the release!

**Comment by tsightler** [comment]
Initial testing with 10.0.0 beta seems good, streams work with no changes.  Unexpectedly, it did break my snapshot code though, because I was calling some backend functions directly rather than using the native retry code and it seems those function don't exist anymore.  I'll have to look at that, but my guess is it will be easy to fix.

Thanks again for maintaining ring-client-api!

**Comment by dgreif** [comment]
Yep, it's using WebRTC now and that piece seems to be working great.  I did update the snapshot functionality to use their newer endpoint, which will just wait for a snapshot to be available, rather than requiring polling.

**Comment by tsightler** [comment]
Cool, I was able to easily modify the code to use the new snapshot functions and I think with this change you can close https://github.com/dgreif/ring/issues/596 as I'm just calling getNextSnapshot() directly which seems to work perfectly for my use case and lets me remove my custom function that were doing something similar.  Overall the 10.0.0-beta branch is looking pretty good to me so far, streams seems solid and snapshots are now working great as well.
