### ISSUE TITLE
Hiding Motion Sensors

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#89]
Is it possible to choose with motion sensors to hide? rather than global on or off?

**Comment by dgreif** [comment]
I think it's getting a little nit-picky at that point. iOS 13 combines all of the services for each devices into one, so it shouldn't be a burden to have the motion sensors along side the cameras/lights.

**Comment by adavison007** [comment]
> I think it's getting a little nit-picky at that point. iOS 13 combines all of the services for each devices into one, so it shouldn't be a burden to have the motion sensors along side the cameras/lights.

Yep, I get that (hate them as one, my gang way light switch is going to be a disaster)! However, some rooms I have my alarm sensor and a ring, so I don't need two sensors per room, other rooms I don't have an alarm sensor so use ring... The Tado Thermostat plugin lets you choose per device what you do, lots of son edits, but you get it perfect, if you can it would be appreciated.. see son for per room thermoses (TLV). 

See **Exclude**

 {
            "platform": "TadoPlatform",
            "username": "X@X.com",
            "password": "XXXXX",
            "homeID": XXXXXX,
            "unit": "celsius",
            "polling": 10,
            **"exclude"**: [
                "VA0792396800-1",
                "VA1580925952-1",
                "VA1533084928-20",
                "VA1204159488-14",
                "VA2235237376-14",
                "VA3124429824-14",
                "VA1364001792-6",
                "VA3645572096-6",
                "VA1815806976-18",
                "VA1700857088-3",
                "VA2537227264-3",
                "VA2704999424-4"
            ],
            "reConfig": false,
            "occupancy": true,
            "anyone": false,
            "weather": true,
            "openWindow": true,
            "solarIntensity": false,
            "centralSwitch": true,
            "externalSensor": false,
            "deviceOptions": {
                "BU1412FT01051088094208-0": {
                    "active": true,
                    "overrideMode": "auto",
                    "autoTemp": 50,
                    "ID": 0,
                    "zoneName": "Hot Water",
                    "zoneType": "HOT_WATER",
                    "deviceType": "BU",
                    "serial": "BU1412FT01051088094208",
                    "type": "boiler",
                    "canSetTemperature": false
                },
                "RU1602FT01053171549952-1": {
                    "active": true,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 1,
                    "zoneName": "Hallway",
                    "zoneType": "HEATING",
                    "deviceType": "RU",
                    "serial": "RU1602FT01053171549952",
                    "type": "thermostat"
                },
                "VA0792396800-1": {
                    "active": false,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 1,
                    "zoneName": "Hallway",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA0792396800",
                    "type": "thermostat"
                },
                "VA1580925952-1": {
                    "active": false,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 1,
                    "zoneName": "Hallway",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA1580925952",
                    "type": "thermostat"
                },
                "RU3574662656-20": {
                    "active": true,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 20,
                    "zoneName": "Landing",
                    "zoneType": "HEATING",
                    "deviceType": "RU",
                    "serial": "RU3574662656",
                    "type": "thermostat"
                },
                "VA1533084928-20": {
                    "active": false,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 20,
                    "zoneName": "Landing",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA1533084928",
                    "type": "thermostat"
                },
                "RU3172467712-14": {
                    "active": true,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 14,
                    "zoneName": "Kitchen",
                    "zoneType": "HEATING",
                    "deviceType": "RU",
                    "serial": "RU3172467712",
                    "type": "thermostat"
                },
                "VA1204159488-14": {
                    "active": false,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 14,
                    "zoneName": "Kitchen",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA1204159488",
                    "type": "thermostat"
                },
                "VA2235237376-14": {
                    "active": false,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 14,
                    "zoneName": "Kitchen",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA2235237376",
                    "type": "thermostat"
                },
                "VA3124429824-14": {
                    "active": false,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 14,
                    "zoneName": "Kitchen",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA3124429824",
                    "type": "thermostat"
                },
                "RU0370476032-6": {
                    "active": true,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 6,
                    "zoneName": "Lounge",
                    "zoneType": "HEATING",
                    "deviceType": "RU",
                    "serial": "RU0370476032",
                    "type": "thermostat"
                },
                "VA1364001792-6": {
                    "active": false,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 6,
                    "zoneName": "Lounge",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA1364001792",
                    "type": "thermostat"
                },
                "VA3645572096-6": {
                    "active": false,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 6,
                    "zoneName": "Lounge",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA3645572096",
                    "type": "thermostat"
                },
                "RU1326515712-18": {
                    "active": true,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 18,
                    "zoneName": "Dining Room",
                    "zoneType": "HEATING",
                    "deviceType": "RU",
                    "serial": "RU1326515712",
                    "type": "thermostat"
                },
                "VA1815806976-18": {
                    "active": false,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 18,
                    "zoneName": "Dining Room",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA1815806976",
                    "type": "thermostat"
                },
                "RU1602FT01051459225088-3": {
                    "active": true,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 3,
                    "zoneName": "Den",
                    "zoneType": "HEATING",
                    "deviceType": "RU",
                    "serial": "RU1602FT01051459225088",
                    "type": "thermostat"
                },
                "VA1700857088-3": {
                    "active": false,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 3,
                    "zoneName": "Den",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA1700857088",
                    "type": "thermostat"
                },
                "VA2537227264-3": {
                    "active": false,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 3,
                    "zoneName": "Den",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA2537227264",
                    "type": "thermostat"
                },
                "VA2151351296-7": {
                    "active": true,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 7,
                    "zoneName": "Study",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA2151351296",
                    "type": "thermostat"
                },
                "VA0894108672-19": {
                    "active": true,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 19,
                    "zoneName": "Toilet",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA0894108672",
                    "type": "thermostat"
                },
                "RU1602FT01051425801728-4": {
                    "active": true,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 4,
                    "zoneName": "Bedroom",
                    "zoneType": "HEATING",
                    "deviceType": "RU",
                    "serial": "RU1602FT01051425801728",
                    "type": "thermostat"
                },
                "VA2704999424-4": {
                    "active": false,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 4,
                    "zoneName": "Bedroom",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA2704999424",
                    "type": "thermostat"
                },
                "VA3640329216-22": {
                    "active": true,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 22,
                    "zoneName": "Ellas Room",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA3640329216",
                    "type": "thermostat"
                },
                "VA3259761664-8": {
                    "active": true,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 8,
                    "zoneName": "Lilys Room",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA3259761664",
                    "type": "thermostat"
                },
                "VA1112212480-16": {
                    "active": true,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 16,
                    "zoneName": "Guest Room",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA1112212480",
                    "type": "thermostat"
                },
                "VA1733100544-15": {
                    "active": true,
                    "heatValue": 2,
                    "coolValue": 2,
                    "maxDelay": 10,
                    "overrideMode": "auto",
                    "ID": 15,
                    "zoneName": "Spare Room",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA1733100544",
                    "type": "thermostat"
                }

**Comment by dgreif** [comment]
iOS 13 does a good job of grouping everything so there shouldn't be a need to remove individual motion sensors anymore

**Comment by adavison007** [comment]
Thanks, and in 13.2 beta you can choose to consolidate or show each feature separately.. so options too now :)
