### ISSUE TITLE
Ring app issue 

### ISSUE THREAD

**Issue by Jpassar099** [dgreif/ring#894]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.
Ring app starts but then generates an error 

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.
2/23/2022, 8:35:50 PMRing Bridge starting
2/23/2022, 8:35:54 PMRing BridgeLoaded plugin 'homebridge-ring'
2/23/2022, 8:35:54 PMRing BridgeLoading 1 platforms...
2/23/2022, 8:35:54 PMRing BridgeBridge is running on port 51836.
2/23/2022, 8:35:55 PMRing BridgeRingFound the following locations:
2/23/2022, 8:35:55 PMRing BridgeRing  locationId: f25ee2-322oa-0 - My Location
2/23/2022, 8:35:56 PMRing BridgeRingERRORFailed to reach Ring server at https://app.ring.com/api/v1/mode/location/f25ee2-322oa-0.  connect ECONNREFUSED 3.227.205.55:443.  Trying again in 5 seconds...
2/23/2022, 8:35:56 PMRing BridgeRingERRORFailed to reach Ring server at https://app.ring.com/api/v1/mode/location/f25ee2-322oa-0.  connect ECONNREFUSED 3.227.205.55:443.  Trying again in 5 seconds...
2/23/2022, 8:36:01 PMRing BridgeRingERRORFailed to reach Ring server at https://app.ring.com/api/v1/mode/location/f25ee2-322oa-0.  connect ECONNREFUSED 3.227.205.55:443.  Trying again in 5 seconds...
2/23/2022, 8:36:01 PMRing BridgeRingERRORFailed to reach Ring server at https://app.ring.com/api/v1/mode/location/f25ee2-322oa-0.  connect ECONNREFUSED 3.227.173.119:443.  Trying again in 5 seconds...
2/23/2022, 8:36:06 PMRing BridgeRingERRORFailed to reach Ring server at https://app.ring.com/api/v1/mode/location/f25ee2-322oa-0.  connect ECONNREFUSED 3.211.65.58:443.  Trying again in 5 seconds...
2/23/2022, 8:36:06 PMRing BridgeRingERRORFailed to reach Ring server at https://app.ring.com/api/v1/mode/location/f25ee2-322oa-0.  connect ECONNREFUSED 3.227.205.55:443.  Trying again in 5 seconds...
### Additional context
 Add any other context about the problem here.
I uninstalled and reinstalled with no success 
### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]
<br class="Apple-interchange-newline">

Version | 4.1.22 Check for Updates
-- | --
Node Version | 16.14.0
Homebridge Version | 1.4.0
CPU | 3%
Memory | 191.4 MB (123.8 MB)
Manufacturer | HOOBS.org
Model | HSLF-2
System Version | 11
SKU | 7-45114-12418-0
Hostname | hoobs

All Bridges Running
Version	4.1.22 [Check for Updates]()
Node Version	16.14.0
Homebridge Version	1.4.0
CPU	3%
Memory	191.4 MB (123.8 MB)
Manufacturer	HOOBS.org
Model	HSLF-2
System Version	11
SKU	7-45114-12418-0
Hostname	hoobs

**Comment by dgreif** [comment]
Sounds like there were a few users experiencing this today.  My guess is that it was a bug on Ring's end.  Could you reboot and confirm if it's still happening now?

**Comment by Jpassar099** [comment]
Thanks. You were right. All good now.
