### ISSUE TITLE
Security vulnerability with ring alarm and Apple TV

### ISSUE THREAD

**Issue by amrishraje** [dgreif/ring#895]
# Bug Report

### Describe the Bug
- Ring Alarm can be disabled without requiring a passcode by simply saying ‘disable security system’ on the Apple TV Siri remote. The same command requires Face ID or password on an iPhone. Not sure if this is a security vulnerability with Apple TV or the Ring plug-in. 

### To Reproduce
 - Start Homebridge
 - Configure Ring plug-in. Ring alarm is automatically setup. In my case the alarm is called ‘alarm’ and shows up as a alarm or security system in the home app. 
 - using Apple TV Siri remote, press and hold the Siri button and say ‘disable security system'. 
 - The ring alarm is disabled from armed state without any passcode 
 - Any intruder can easily fire up Apple TV and disarm ring!

### Expected behavior
- Siri should either not disarm security system via Apple TV or at least ask for a passcode. 

### Environment
 - OS: Hoobs 4.1.22
 - Node.js: 16.14.0
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: 9.24.0
 - homebridge: 1.4.0
 - hoobs: 4.1.22

**Comment by dgreif** [comment]
This is all handled by apple. Nothing we can do from the plugin to make it more secure unfortunately.

**Comment by amrishraje** [comment]
Yeah, I thought so. Going to report this as an issue to apple. 

Regards,
Amrish

On Feb 25, 2022, at 4:06 PM, Dusty Greif ***@***.***> wrote:

﻿
This is all handled by apple. Nothing we can do from the plugin to make it more secure unfortunately.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
