### ISSUE TITLE
Option to disable logs

### ISSUE THREAD

**Issue by JacVid** [dgreif/ring#906]
# Feature Request

### Description
Propose an option in the config to disable all the logs corresponding to cameras and doorbells.

### Describe the solution you'd like
Each time my doorbell is monitored via Home app, the homebridge log gets:
[18/03/2022, 19:52:26] [Ring] Preparing Live Stream for Sonnette
[18/03/2022, 19:52:26] [Ring] Waiting for stream data from Sonnette (0.247s)
[18/03/2022, 19:52:27] [Ring] Received stream data from Sonnette (0.687s)
[18/03/2022, 19:52:27] [Ring] Streaming active for Sonnette
[18/03/2022, 19:52:33] [Ring] Stopped Live Stream for Sonnette

### Describe alternatives you've considered
Same as "Debug Logging" checkbox, it would be nice to have that option for all other functional logs which could be considered as unimportant for some of us, compared to error logs.

Thanks for your great job ;)

**Comment by dgreif** [comment]
Generally I find that it's better have _more_ in the logs than less, especially when trying to debug an issue.  Is there a specific reason you don't want this information in your logs?  I've been trying hard to not add more configuration options

**Comment by JacVid** [comment]
Hello, for me, it's a clean way to use the Log, where I'm only warned about problem.

So, like most of the plugin, I would appreciate to get this option. You do already have the "Debugging Option", why not just adding something like ("disableDeviceLogging": true), which could be added manually if it is difficult via the HomeBridge HMI ?

Thanks for your time ;)

**Comment by marksthomas** [comment]
I agree. I don't need to see logs. Option to remove logging would be great.

**Comment by taylorsatula** [comment]
+1 On this. I don't need to see "Ring connected to socket.io" every three lines of the Homebridge log.

**Comment by marksthomas** [comment]
> Is there a specific reason you don't want this information in your logs?

Yes, I'm an end user, not a dev and really don't need all this noise. At least give us the option. Not all of us care about this kind of detail. 

Cheers!

**Comment by JacVid** [comment]
Thanks for this update and your great job ;)
