### ISSUE TITLE
Beta 3 - Snapshots

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#909]
Video Snapshots in beta 1 and beta 3 (didn’t try beta 2) only collects video snap shots every 60 seconds. Not sure if it’s the beta or iOS 15.4 that’s causing the issues ?

**Comment by dgreif** [comment]
Could you try reverting to v9 and see if it behaves the same?

**Comment by adavison007** [comment]
Just done that (V9 latest), and it’s the same, takes ages for the first snapshot (60 seconds) then the timer on the screen counts to 60 seconds and then refreshes… no snaps-shot showing in the logs either, even after the 60 seconds refresh.

Adam Davison
***@***.*** ***@***.***>
01276 63145
07748 761448

On 30 Mar 2022, at 18:45, Dusty Greif ***@***.***> wrote:


Could you try reverting to v9 and see if it behaves the same?

**Comment by dgreif** [comment]
That's definitely behavior coming from the HomeKit side then.  As I mentioned, that's the normal behavior if you are on your phone on LTE instead of wifi.  If you are seeing this on WiFi, then it's possible iOS 15.4 changed the default

**Comment by adavison007** [comment]
Thanks, yep deffo seems like a homekit change… don't like that :) 


Adam Davison
***@***.*** ***@***.***>
01276 63145
07748 761448

On 30 Mar 2022, at 19:00, Dusty Greif ***@***.***> wrote:


That's definitely behavior coming from the HomeKit side then. As I mentioned, that's the normal behavior if you are on your phone on LTE instead of wifi. If you are seeing this on WiFi, then it's possible iOS 15.4 changed the default

**Comment by dgreif** [comment]
Just confirmed similar behavior on my phone on wifi with iOS 15.4 😞.  This definitely makes it less valuable to cache the snapshots if there isn't a 10 second option.  Maybe I will end up changing it to keep a snapshot in memory at all times even though it's stale.  Very unfortunate that they changes this

**Comment by Hackashaq666** [comment]
Not sure if this is relevant, but the camera-ffmpeg snapshot updates every 15 sec with latest ios

**Comment by adavison007** [comment]
It’s an iOS issue, not the plugin. iOS 15.4 made it refresh on 60 seconds and now 15.4.1 is 20 seconds and it skips the first 6 seconds.



Sent from my iPhone

On 1 Apr 2022, at 00:55, Hackashaq666 ***@***.***> wrote:

﻿
Not sure if this is relevant, but the camera-ffmpeg snapshot updates every 15 sec with latest ios

**Comment by adavison007** [comment]
Try it in 15.4.1 … it’s now crazy.. starts at 6 seconds and refreshes at 20seconds and then starts at 6 seconds again… they have issues 

Sent from my iPhone

On 30 Mar 2022, at 20:04, Dusty Greif ***@***.***> wrote:

﻿
Just confirmed similar behavior on my phone on wifi with iOS 15.4 😞. This definitely makes it less valuable to cache the snapshots if there isn't a 10 second option. Maybe I will end up changing it to keep a snapshot in memory at all times even though it's stale. Very unfortunate that they changes this
