### ISSUE TITLE
Floodlight Brightness Showing in HK When It Can't Be Adjusted

### ISSUE THREAD

**Issue by fentonmatt** [dgreif/ring#912]
I have the latest Ring floodlight wired and the brightness shows in HK at 0% when turned on but this model doesn't support brightness. Floodlight Cam is similar but does NOT show brightness in HK. Just says On/Off. I would expect the same from the floodlight wired. Ring app does not allow brightness control of either of these devices.

**Comment by dgreif** [comment]
Please follow the directions in https://github.com/dgreif/ring/wiki/Data-Discovery, which should give me at least a glimpse into how the brightness is stored.  I probably can't set up _control_ for the brightness without a device to actually test with though.

**Comment by toogle9** [comment]
Following.  Currently have 1 Floodlight Cam Wired Pro, and the lights show up in HomeKit as just an on/off toggle, just assumed that was as designed, and brightness level/adjustment was not available.  You can adjust the brightness directly in the Ring app, and it appears that HomeKit honors the brightness level that you've set in the Ring app, and then Home allows you to just toggle on/off at that state, which is better than nothing.  It would be great if brightness was adjustable directly in HomeKit.

**Comment by dgreif** [comment]
@toogle9 I'd be happy to get this fixed up if you are able to post the results from the data discovery tool linked above

**Comment by toogle9** [comment]
Hello sir, I'd be happy to, but may need a little extra instruction.  I am currently running Homebridge on my Synology as a Docker container.  The instructions for Data Discovery give different options for having homebridge-ring installed globally or not globally.  From the Homebridge terminal prompt, if I run the command for globally installed, that command is not found, and I'm not seeing an npm bin directory, I assume because I'm inside the container?  If I run the non-globally installed command from the Homebridge terminal, it wants to install the package ring-clinet-api.  I assume that is ok to do from within Homebridge itself?  I am still running Hb 1.4.0, I see 1.4.1 is out but haven't had any time yet to update the container.  I am also still running your latest 9.x plugin, I see 10.x is out, but always like to give major updates a little time to settle first.

**Comment by toogle9** [comment]
Apologies, I went ahead and installed the ring-client-api package in the Homebridge terminal, and have capture the data you requested.  I did remove a "location" from the json that is shared with me, but not owned by me, I believe I have removed that section of code cleanly, I don't believe there is anything else particularly private in it.   Please advise if you need any additional information.  BTW, I now have 2 of the Floodlight Cam Wired Pro units, the wife liked the first one so much she requested I get another!  ;-)


{"locations":[{"name":"Home","cameras":[{"description":"Front Door","subscribed":true,"subscribed_motions":true,"battery_life":null,"external_connection":false,"firmware_version":"Up to Date","kind":"lpd_v4","settings":{"cv_settings":{"detection_types":{"human":{"enabled":false,"mode":"none","record":null,"notification":false},"loitering":{"enabled":false,"mode":"none","record":null,"notification":false},"motion":{"enabled":true,"mode":"edge","record":null,"notification":true},"moving_vehicle":{"enabled":false,"mode":"none","record":null,"notification":false},"other_motion":{"enabled":false,"mode":"none","record":null,"notification":false},"package_delivery":{"enabled":false,"mode":"none","record":null,"notification":false},"package_pickup":{"enabled":false,"mode":"none","record":null,"notification":false}},"threshold":{"loitering":10,"package_delivery":2},"triggers":[]},"cv_paid_features":{"human":true,"loitering":true,"motion":true,"other_motion":true,"package_delivery":true,"package_pickup":true,"cv_triggers":true},"concierge_settings":{"mode":"autoreply"},"other_paid_features":{"alexa_concierge":true,"sheila_cv":true,"sheila_recording":true},"sheila_settings":{"cv_processing_enabled":false,"local_storage_enabled":false},"server_settings":{"ring_media_server_enabled":true},"zone_settings":{"motion":[{"name":"Zone 1","state":"enabled","properties":{"detection_types":["motion"],"style":1},"vertices":[{"x":0.213366,"y":0.62496},{"x":0.386796,"y":0.645088},{"x":0.562641,"y":0.64992},{"x":0.737037,"y":0.799195},{"x":0.972142,"y":0.992754},{"x":0.440741,"y":0.992754},{"x":0,"y":1},{"x":0.038647,"y":0.681643}]}],"aerial":[{"name":"Bird's Eye zone 1","state":"enabled","properties":{"detection_types":["motion"]},"vertices":[{"x":-5.8884,"y":1.5778},{"x":-7.919,"y":4.5721},{"x":-4.5721,"y":7.919},{"x":0,"y":9.1441},{"x":4.5721,"y":7.919},{"x":7.919,"y":4.5721},{"x":5.8884,"y":1.5778},{"x":0,"y":0}]}]},"offline_motion_event_settings":{"subscribed":true,"enabled":false,"max_upload_kb":5000,"resolution_p":360,"frequency_after_secs":1,"period_after_secs":30},"lite_24x7":{"subscribed":true,"enabled":true,"frequency_secs":60,"resolution_p":360},"enable_vod":true,"motion_zones":{"enable_audio":false,"active_motion_filter":1,"sensitivity":5,"advanced_object_settings":{"human_detection_confidence":{"day":0.8,"night":0.8},"motion_zone_overlap":{"day":0.2,"night":0.3},"object_time_overlap":{"day":0.2,"night":1.2},"object_size_minimum":{"day":0.04,"night":0.07},"object_size_maximum":{"day":0.7,"night":0.7}},"zone1":{"name":"Zone 1","state":2,"vertex1":{"x":0.213366,"y":0.62496},"vertex2":{"x":0.386796,"y":0.645088},"vertex3":{"x":0.562641,"y":0.64992},"vertex4":{"x":0.737037,"y":0.799195},"vertex5":{"x":0.972142,"y":0.992754},"vertex6":{"x":0.440741,"y":0.992754},"vertex7":{"x":0,"y":1},"vertex8":{"x":0.038647,"y":0.681643}},"zone2":{"name":"Zone 2","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}},"zone3":{"name":"Zone 3","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}}},"motion_snooze_preset_profile":"low","live_view_preset_profile":"highest","live_view_presets":["low","middle","high","highest"],"motion_snooze_presets":["none","low","medium","high"],"doorbell_volume":5,"chime_settings":{"type":2,"enable":true,"duration":10},"video_settings":{"ignore_zones":null,"birton":null,"brightness":0,"contrast":64,"saturation":64,"ae_level":0,"ae_mode":0,"ae_mask":null,"encryption_enabled":false,"encryption_method":null,"clip_length_min":null,"clip_length_max":60,"hevc_enabled":false},"motion_announcement":false,"stream_setting":0,"advanced_motion_detection_enabled":true,"advanced_motion_detection_human_only_mode":false,"luma_night_threshold":0,"enable_audio_recording":true,"people_detection_eligible":true,"live_view_disabled":false,"ignore_zones":null,"enable_rich_notifications":true,"rich_notifications_billing_eligible":true,"loitering_threshold":10,"advanced_motion_detection_types":[],"motion_detection_enabled":true,"rich_notifications_scene_source":"firmware","radar_settings":{"birds_eye_view_enabled":false,"bez_filtering_enabled":true,"bez_feature_enabled":false,"installation_height":0},"voice_volume":11,"rich_notifica-uuid":false},"features":{"motion_zone_recommendation":false,"motions_enabled":true,"show_recordings":true,"advanced_motion_enabled":false,"people_only_enabled":false,"shadow_correction_enabled":false,"motion_message_enabled":true,"night_vision_enabled":false,"rich_notifications_eligible":true,"show_24x7_lite":true,"show_offline_motion_events":false,"cfes_eligible":true,"sheila_camera_eligible":true,"sheila_camera_processing_eligible":true,"show_radar_data":true,"live_view_pip_mode":"none"},"owned":true,"alerts":{"connection":"online","ota_status":"timeout","sidewalk_connection":false},"motion_snooze":null,"stolen":false,"is_sidewalk_gateway":true,"created_at":"2022-03-01T13:31:27Z","shared_at":null,"active_schedule_uuid":null,"health":{"device_type":"lpd_v4","last_update_time":1652133143,"connected":true,"rss_connected":true,"sidewalk_connection":false,"floodlight_on":false,"white_led_on":false,"siren_on":false,"packet_loss":-1,"packet_loss_category":"NA","rssi":-46,"battery_voltage":4046,"transformer_voltage":22.742,"transformer_voltage_category":"good","ota_status":"timeout","network_connection_value":"wifi","external_connection":false,"battery_percentage_category":"unknown","firmware_version":"9.0.21","rssi_category":"good","battery_voltage_category":"very_good","second_battery_voltage_category":"unknown","second_battery_percentage_category":"unknown","firmware_version_status":"Up to Date","stream_resolution":100,"tx_rate":144,"bandwidth_last_time":1652133143,"bandwidth":14999,"transformer_status":"6"},"deactivated_at":null,"night_mode_status":"unknown"},{"description":"Back Porch","subscribed":true,"subscribed_motions":true,"battery_life":100,"external_connection":false,"firmware_version":"Up to Date","kind":"floodlight_pro","settings":{"cv_settings":{"detection_types":{"human":{"enabled":false,"mode":"none","record":null,"notification":false},"loitering":{"enabled":false,"mode":"none","record":null,"notification":false},"motion":{"enabled":true,"mode":"edge","record":null,"notification":true},"moving_vehicle":{"enabled":false,"mode":"none","record":null,"notification":false},"other_motion":{"enabled":false,"mode":"none","record":null,"notification":false},"package_delivery":{"enabled":false,"mode":"none","record":null,"notification":false},"package_pickup":{"enabled":false,"mode":"none","record":null,"notification":false}},"threshold":{"loitering":10,"package_delivery":2},"triggers":[]},"cv_paid_features":{"human":true,"loitering":true,"motion":true,"other_motion":true,"package_delivery":true,"package_pickup":true,"cv_triggers":true},"other_paid_features":{"alexa_concierge":true,"sheila_cv":true,"sheila_recording":true},"sheila_settings":{"cv_processing_enabled":false,"local_storage_enabled":false},"server_settings":{"ring_media_server_enabled":true},"zone_settings":{"motion":[{"name":"Default Zone","state":"enabled","properties":{"detection_types":["motion"],"style":1},"vertices":[{"x":0.173295,"y":0.293189},{"x":0.508523,"y":0.276034},{"x":0.711932,"y":0.363824},{"x":0.988068,"y":0.743189},{"x":0.9,"y":0.957064},{"x":0.5,"y":0.969173},{"x":0.238068,"y":0.984309},{"x":0.072159,"y":0.476791}]}],"aerial":[{"name":"Bird's Eye zone 1","state":"enabled","properties":{"detection_types":["motion"]},"vertices":[{"x":-5.8884,"y":1.5778},{"x":-7.919,"y":4.5721},{"x":-4.5721,"y":7.919},{"x":0,"y":9.1441},{"x":4.5721,"y":7.919},{"x":7.919,"y":4.5721},{"x":5.8884,"y":1.5778},{"x":0,"y":0}]}]},"offline_motion_event_settings":{"subscribed":true,"enabled":false,"max_upload_kb":5000,"resolution_p":360,"frequency_after_secs":1,"period_after_secs":30},"lite_24x7":{"subscribed":true,"enabled":true,"frequency_secs":60,"resolution_p":360},"enable_vod":true,"motion_zones":{"enable_audio":false,"active_motion_filter":1,"sensitivity":5,"advanced_object_settings":{"human_detection_confidence":{"day":0.8,"night":0.8},"motion_zone_overlap":{"day":0.2,"night":0.3},"object_time_overlap":{"day":0.2,"night":1.2},"object_size_minimum":{"day":0.04,"night":0.07},"object_size_maximum":{"day":0.7,"night":0.7}},"zone1":{"name":"Default Zone","state":2,"vertex1":{"x":0.173295,"y":0.293189},"vertex2":{"x":0.508523,"y":0.276034},"vertex3":{"x":0.711932,"y":0.363824},"vertex4":{"x":0.988068,"y":0.743189},"vertex5":{"x":0.9,"y":0.957064},"vertex6":{"x":0.5,"y":0.969173},"vertex7":{"x":0.238068,"y":0.984309},"vertex8":{"x":0.072159,"y":0.476791}},"zone2":{"name":"Zone 2","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}},"zone3":{"name":"Zone 3","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}},"pir_settings":{"sensitivity1":10,"sensitivity2":10,"sensitivity3":10,"zone_mask":7}},"motion_snooze_preset_profile":"low","live_view_preset_profile":"highest","live_view_presets":["low","middle","high","highest"],"motion_snooze_presets":["none","low","medium","high"],"doorbell_volume":11,"chime_settings":{"type":2,"enable":true,"duration":10},"video_settings":{"ignore_zones":null,"birton":null,"brightness":0,"contrast":64,"saturation":64,"ae_level":0,"ae_mode":0,"ae_mask":null,"encryption_enabled":false,"encryption_method":null,"clip_length_min":null,"clip_length_max":60,"hevc_enabled":false},"motion_announcement":false,"stream_setting":0,"advanced_motion_detection_enabled":true,"advanced_motion_detection_human_only_mode":false,"luma_night_threshold":0,"enable_audio_recording":true,"people_detection_eligible":true,"live_view_disabled":false,"ignore_zones":null,"enable_rich_notifications":true,"rich_notifications_billing_eligible":true,"loitering_threshold":10,"advanced_motion_detection_types":[],"motion_detection_enabled":true,"rich_notifications_scene_source":"firmware","pir_settings":{"sensitivity1":10,"sensitivity2":10,"sensitivity3":10,"zone_mask":7},"pir_motion_zones":[1,1,1],"floodlight_settings":{"priority":0,"duration":30,"brightness":8,"always_on":false,"always_on_duration":null},"light_schedule_settings":{"start_hour":0,"start_minute":0,"end_hour":0,"end_minute":0},"luma_light_threshold":0,"radar_settings":{"birds_eye_view_enabled":false,"bez_filtering_enabled":false,"bez_feature_enabled":false,"installation_height":3.1},"voice_volume":7,"rich_notifica-uuid":false},"features":{"motion_zone_recommendation":false,"motions_enabled":true,"show_recordings":true,"advanced_motion_enabled":false,"people_only_enabled":false,"shadow_correction_enabled":false,"motion_message_enabled":true,"night_vision_enabled":false,"rich_notifications_eligible":true,"show_24x7_lite":true,"show_offline_motion_events":false,"cfes_eligible":true,"sheila_camera_eligible":true,"sheila_camera_processing_eligible":true,"show_radar_data":false,"live_view_pip_mode":"none"},"owned":true,"alerts":{"connection":"online","ota_status":"timeout","sidewalk_connection":false},"motion_snooze":{"scheduled":true},"stolen":false,"is_sidewalk_gateway":true,"created_at":"2022-03-03T23:19:38Z","shared_at":null,"active_schedule_uuid":null,"health":{"device_type":"floodlight_pro","last_update_time":1652136440,"connected":true,"rss_connected":true,"sidewalk_connection":false,"floodlight_on":false,"white_led_on":false,"siren_on":false,"packet_loss":-1,"packet_loss_category":"NA","rssi":-47,"ota_status":"timeout","network_connection_value":"wifi","external_connection":false,"battery_percentage_category":"unknown","firmware_version":"9.0.21","rssi_category":"good","battery_voltage_category":"unknown","second_battery_voltage_category":"unknown","second_battery_percentage_category":"unknown","firmware_version_status":"Up to Date","stream_resolution":100,"tx_rate":117,"bandwidth_last_time":1652118775,"bandwidth":14999},"deactivated_at":null,"led_status":"off","night_mode_status":"unknown","ring_cam_light_installed":"true","ring_cam_setup_flow":"floodlight","siren_status":{"seconds_remaining":0}},{"description":"Driveway","subscribed":true,"subscribed_motions":true,"battery_life":100,"external_connection":false,"firmware_version":"Up to Date","kind":"floodlight_pro","settings":{"cv_settings":{"detection_types":{"human":{"enabled":false,"mode":"none","record":null,"notification":false},"loitering":{"enabled":false,"mode":"none","record":null,"notification":false},"motion":{"enabled":true,"mode":"edge","record":null,"notification":true},"moving_vehicle":{"enabled":false,"mode":"none","record":null,"notification":false},"other_motion":{"enabled":false,"mode":"none","record":null,"notification":false},"package_delivery":{"enabled":false,"mode":"none","record":null,"notification":false},"package_pickup":{"enabled":false,"mode":"none","record":null,"notification":false}},"threshold":{"loitering":10,"package_delivery":2},"triggers":[]},"cv_paid_features":{"human":true,"loitering":true,"motion":true,"other_motion":true,"package_delivery":true,"package_pickup":true,"cv_triggers":true},"other_paid_features":{"alexa_concierge":true,"sheila_cv":true,"sheila_recording":true},"sheila_settings":{"cv_processing_enabled":false,"local_storage_enabled":false},"server_settings":{"ring_media_server_enabled":true},"zone_settings":{"motion":[{"name":"Default Zone","state":"enabled","properties":{"detection_types":["motion"],"style":1},"vertices":[{"x":0.075,"y":0.363824},{"x":0.507955,"y":0.333552},{"x":0.685795,"y":0.340616},{"x":1,"y":0.699798},{"x":0.99375,"y":1},{"x":0.476705,"y":1},{"x":0.029545,"y":1},{"x":0,"y":0.615035}]}],"aerial":[{"name":"Bird's Eye zone 1","state":"enabled","properties":{"detection_types":["motion"]},"vertices":[{"x":-5.8883553,"y":1.5777801},{"x":-7.7942286,"y":4.5},{"x":-4.5,"y":7.7942286},{"x":5.5109107e-16,"y":9},{"x":4.5,"y":7.7942286},{"x":7.7942286,"y":4.5},{"x":5.8883553,"y":1.5777801},{"x":0,"y":0}]}]},"offline_motion_event_settings":{"subscribed":true,"enabled":false,"max_upload_kb":5000,"resolution_p":360,"frequency_after_secs":1,"period_after_secs":30},"lite_24x7":{"subscribed":true,"enabled":true,"frequency_secs":30,"resolution_p":360},"enable_vod":true,"motion_zones":{"enable_audio":false,"active_motion_filter":1,"sensitivity":5,"advanced_object_settings":{"human_detection_confidence":{"day":0.8,"night":0.8},"motion_zone_overlap":{"day":0.2,"night":0.3},"object_time_overlap":{"day":0.2,"night":1.2},"object_size_minimum":{"day":0.04,"night":0.07},"object_size_maximum":{"day":0.7,"night":0.7}},"zone1":{"name":"Default Zone","state":2,"vertex1":{"x":0.075,"y":0.363824},"vertex2":{"x":0.507955,"y":0.333552},"vertex3":{"x":0.685795,"y":0.340616},"vertex4":{"x":1,"y":0.699798},"vertex5":{"x":0.99375,"y":1},"vertex6":{"x":0.476705,"y":1},"vertex7":{"x":0.029545,"y":1},"vertex8":{"x":0,"y":0.615035}},"zone2":{"name":"Zone 2","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}},"zone3":{"name":"Zone 3","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}},"pir_settings":{"sensitivity1":10,"sensitivity2":10,"sensitivity3":10,"zone_mask":7}},"motion_snooze_preset_profile":"low","live_view_preset_profile":"highest","live_view_presets":["low","middle","high","highest"],"motion_snooze_presets":["none","low","medium","high"],"doorbell_volume":11,"chime_settings":{"type":2,"enable":true,"duration":10},"video_settings":{"ignore_zones":null,"birton":null,"brightness":0,"contrast":64,"saturation":64,"ae_level":0,"ae_mode":0,"ae_mask":null,"encryption_enabled":false,"encryption_method":0,"clip_length_min":null,"clip_length_max":60,"hevc_enabled":false},"motion_announcement":false,"stream_setting":0,"advanced_motion_detection_enabled":true,"advanced_motion_detection_human_only_mode":false,"luma_night_threshold":0,"enable_audio_recording":true,"people_detection_eligible":true,"live_view_disabled":false,"ignore_zones":null,"enable_rich_notifications":true,"rich_notifications_billing_eligible":true,"loitering_threshold":10,"advanced_motion_detection_types":[],"motion_detection_enabled":true,"rich_notifications_scene_source":"firmware","pir_settings":{"sensitivity1":10,"sensitivity2":10,"sensitivity3":10,"zone_mask":7},"pir_motion_zones":[1,1,1],"floodlight_settings":{"priority":0,"duration":30,"brightness":9,"always_on":false,"always_on_duration":null},"light_schedule_settings":{"start_hour":0,"start_minute":0,"end_hour":0,"end_minute":0},"luma_light_threshold":0,"radar_settings":{"birds_eye_view_enabled":true,"bez_filtering_enabled":true,"bez_feature_enabled":true,"installation_height":2.1},"voice_volume":7,"rich_notifica-uuid":false},"features":{"motion_zone_recommendation":false,"motions_enabled":true,"show_recordings":true,"advanced_motion_enabled":false,"people_only_enabled":false,"shadow_correction_enabled":false,"motion_message_enabled":true,"night_vision_enabled":false,"rich_notifications_eligible":true,"show_24x7_lite":true,"show_offline_motion_events":false,"cfes_eligible":true,"sheila_camera_eligible":true,"sheila_camera_processing_eligible":true,"show_radar_data":false,"live_view_pip_mode":"none"},"owned":true,"alerts":{"connection":"online","ota_status":"timeout","sidewalk_connection":false},"motion_snooze":null,"stolen":false,"is_sidewalk_gateway":true,"created_at":"2022-04-24T19:04:39Z","shared_at":null,"active_schedule_uuid":null,"health":{"device_type":"floodlight_pro","last_update_time":1652136045,"connected":true,"rss_connected":true,"sidewalk_connection":false,"floodlight_on":false,"white_led_on":false,"siren_on":false,"packet_loss":-1,"packet_loss_category":"NA","rssi":-65,"ota_status":"timeout","network_connection_value":"wifi","external_connection":false,"battery_percentage_category":"unknown","firmware_version":"9.0.21","rssi_category":"okay","battery_voltage_category":"unknown","second_battery_voltage_category":"unknown","second_battery_percentage_category":"unknown","firmware_version_status":"Up to Date","stream_resolution":100,"tx_rate":52,"bandwidth_last_time":1652127081,"bandwidth":14999},"deactivated_at":null,"led_status":"off","night_mode_status":"unknown","ring_cam_light_installed":"true","ring_cam_setup_flow":"floodlight","siren_status":{"seconds_remaining":0}}],"chimes":[{"description":"Living Room Chime","firmware_version":"Up to Date","kind":"chime","settings":{"volume":8,"status_led_enable":true},"features":{"ringtones_enabled":true,"cfes_eligible":null},"owned":true,"alerts":{"connection":"online","ota_status":"successful"},"do_not_disturb":{"seconds_left":0},"stolen":false,"is_sidewalk_gateway":false,"created_at":"2018-05-17T02:08:59Z","shared_at":null,"deactivated_at":null}],"devices":[]}],"amazonKeyLocks":[]}
