### ISSUE TITLE
Save snapshot

### ISSUE THREAD

**Issue by markburgessstl** [dgreif/ring#915]
# Feature Request

### Description
Allow saving most recent snapshot.   Add config option with path

### Describe the solution you'd like
I would like to be able to save the last snapshot as a jpg file

### Describe alternatives you've considered
IFFT

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dgreif** [comment]
Sorry, but I don't think this is a feature that needs to exist at the library level.  You can call `camera.getSnapshot()` which will pull a new snapshot.  That returns a `Buffer`, which you can then save to a file.  Should be simple to google for saving a Buffer to a file in nodejs.
