### ISSUE TITLE
Add option to save snapshot to file

### ISSUE THREAD

**Issue by markburgessstl** [dgreif/ring#917]
# Feature Request

### Description
Allow saving most recent snapshot. Add config option with path.  

### Describe the solution you'd like
I would like to be able to save the last snapshot as a jpg file. The snapshot would be stored when motion is detected

### Describe alternatives you've considered
IFTT, Webhooks

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by markburgessstl** [comment]
I guess I thought your objection was "at the library level".   I am asking for this to be added to the home bridge plugin which is not the same, or is it?  Please help me understand.

**Comment by dgreif** [comment]
Sorry, your description didn't mention homebridge at all.  That said, this is still not a feature that I'm interested in adding at this time.  I think some users have had success using node-red to do more complex automations like you are attempting here, but I have not experimented with it myself
