### ISSUE TITLE
Session Hardware_id not found

### ISSUE THREAD

**Issue by runeix** [dgreif/ring#92]
Hi @Dgreif,

First of all, thank you for all the work you've done on this plugin. 

I've got a gen 1 doorbell and managed to get the snapshots and the live streams works temporarily the other week, but since then it's been constantly timing out.

Now that I've updated to 5.3.0 the added logging has shown the following issue:

`[8/2/2019, 10:16:12 PM] [Ring] Adding new accessory doorbell_v3 Back Door
[8/2/2019, 10:16:12 PM] Back Door is running on port 45493.
[8/2/2019, 10:16:12 PM] Please add [Back Door] manually in Home app. Setup Code: 031-45-154
homebridge : TTY=pts/1 ; PWD=/var/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge
pam_unix(sudo:session): session opened for user root by (uid=0)
[8/2/2019, 10:27:33 PM] [Ring] Snapshot Requested for Back Door
[8/2/2019, 10:27:34 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 10:27:35 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 10:27:36 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 10:27:37 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 10:27:40 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 10:27:42 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 10:27:52 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 10:27:53 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 10:27:56 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 10:27:56 PM] [Ring] Session response rate limited. Waiting to retry for 180 seconds`

So it's finding the doorbell, and i can add it in homekit, but when it tries to retrieve the snapshot or livestream it gives me a hardware_id not found error and then times out. 

I read through the previously closed issue #78 about the same error, but i think this is something different. The only bit i'm not sure about is if you do need a paid ring subscription or not for this to work?

**Comment by dgreif** [comment]
I think you do need a subscription. Do you have one?

**Comment by d0n4v4nb3ck3r** [comment]
@runeix dgreif is unavailable until Wednesday, just so your aware.

If anyone else can help they will try.

I know they have been having issues with other plugins installed, with the latest updates. What other plugins do you have?

**Comment by runeix** [comment]
> I think you do need a subscription. Do you have one?
no i don't have one - but i'm not sure why it worked without one in the first place then?
I could always get one for a month to test it out.

> @runeix dgreif is unavailable until Wednesday, just so your aware.
thanks for the heads up (although it looks like he's replied)

> I know they have been having issues with other plugins installed, with the latest updates. What other plugins do you have?

- bomgovau v0.1.3
- config-ui-x v4.5.1
- hue v0.11.30
- ring v5.3.0
- sensibo-sky V0.4.2
- tplink-smarthome v4.0.1
- weather-plus v2.7.2
- samsung-tizen v4.0.5

**Comment by taherkaraki** [comment]
For me this happens when the doorbell loses connection with ring.com . But when that error starts occurring and accumulating, I get another error about reaching session rate limit and that I must wait for xx seconds. After that, the camera snapshots are not fetched for quite some time.

**Comment by taherkaraki** [comment]
Sometimes it works fine and sometimes:

[8/2/2019, 6:50:12 PM] [Ring] Snapshot Requested for Front Door
[8/2/2019, 6:50:13 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 6:50:13 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 6:50:14 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 6:50:15 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 6:50:16 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 6:50:16 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 6:50:17 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 6:50:18 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 6:50:20 PM] [Ring] Session hardware_id not found.  Creating a new session and trying again.
[8/2/2019, 6:50:20 PM] [Ring] Session response rate limited. Waiting to retry for 180 seconds

**Comment by LeviJSmith** [comment]
I'm seeing the same error on mine today,.  Seemed to happen after I upgraded to 5.3

**Comment by ifeign** [comment]
Same error here but it started working again later

**Comment by LeviJSmith** [comment]
Mine started working again as well.  Maybe it was a problem on Ring’s end?

**Comment by metroidmen** [comment]
Happening to me as well

**Comment by dgreif** [comment]
I appreciate the info everyone! I have a pretty good idea of what is causing this issue, and should be able to get a fix out on Wednesday or Thursday. The logs are very helpful so thanks for posting those. Sorry for the trouble!

**Comment by metroidmen** [comment]
And thank you for all your hard works!

**Comment by adavison007** [comment]
Thanks @dgreif I noticed the session issue occurring when one ring was offline (dead battery) but all had the issue, once the sign came online again the others all started working again

**Comment by jianyu-li** [comment]
Thanks @dgreif , I am experiencing this as well!

**Comment by adavison007** [comment]
@dgreif let me now if you need me to try a beta, I am home today and tomorrow then off on holidays with no access for 2 weeks, so ha[p[y to help will testing code in the next 48 hours.

**Comment by adavison007** [comment]
@dgreif Any news on a fix? I know this is project work and we all appreciate your efforts, just keen to rye the fix if you have it prior to going on holidays? I don't want to remove this plugin before I go on holiday, but with the 4g issues, I may have to as it stops homekit functioning.. Fingers crossed? happy to donate BTW...?

**Comment by jianyu-li** [comment]
He mentioned it should be out today or tomorrow

**Comment by dgreif** [comment]
Give v`5.3.1` a try.  I made a (poor) assumption that 404 (Not Found) responses would always mean your session was invalid and we needed to create a new one.  404 is totally valid in other situations, I just hadn't seen any yet and there isn't anything very distinct in the response from an invalid session (`hardware_id`).  Turns out you get a 404 when snapshots can't be found for a particular camera.  This happens when the camera is offline, and may happen if the camera just has a poor wifi connection.  My poor assumption would put the entire plugin in a holding state while it waited to create a new session and try the request again.  This basically killed the entir plugin until you fixed the camera and restarted homebridge.  Now I throw an error for actual 404s, which will immediately tell homebridge that the snapshot is not available, and avoid breaking the whole plugin.  If anyone is still seeing repeated `Session hardware_id not found` messages in their logs, please open a new issue.  Hopefully the logs will clearly communicate the offline camera now and avoid further confusion.  Thanks for your patience on this fix everyone!  Let me know how it works for you 🤞

**Comment by ifeign** [comment]
I just updated and am receiving this error:

```
[8/7/2019, 10:18:05 PM] [Ring] sip INVITE request failed with status 480
[8/7/2019, 10:18:05 PM] [Ring] Failed to prepare stream for Front Door (0.67s)
[8/7/2019, 10:18:05 PM] [Ring] Error: sip INVITE request failed with status 480
    at sipClient.send (/homebridge/node_modules/homebridge-ring/lib/api/sip-session.js:154:28)
    at searching (/homebridge/node_modules/homebridge-ring/node_modules/sip/sip.js:1313:5)
    at /homebridge/node_modules/homebridge-ring/node_modules/sip/sip.js:1294:41
    at Object.message (/homebridge/node_modules/homebridge-ring/node_modules/sip/sip.js:1113:7)
    at Object.signal (/homebridge/node_modules/homebridge-ring/node_modules/sip/sip.js:979:55)
    at /homebridge/node_modules/homebridge-ring/node_modules/sip/sip.js:1341:24
    at onMessage (/homebridge/node_modules/homebridge-ring/node_modules/sip/sip.js:555:9)
    at content (/homebridge/node_modules/homebridge-ring/node_modules/sip/sip.js:490:7)
    at headers (/homebridge/node_modules/homebridge-ring/node_modules/sip/sip.js:477:9)
    at TLSSocket.<anonymous> (/homebridge/node_modules/homebridge-ring/node_modules/sip/sip.js:501:27)

```

**Comment by dgreif** [comment]
@ifeign that can happen if you create live streams too close together, like within a few seconds of each other.  The camera takes a second to reset before it will accept another live stream.  If you stop streaming and wait 20 seconds, then try again it should work.

I also wanted to mention that you apparently **do not need a Ring subscription** for all of the homebridge functionality to work.  My subscription happened to lapse over the weekend (due to some really odd billing issue on Ring's end) and everything kept working perfectly.  Looks like recordings and alarm monitoring are the only elements that get dropped without a subscription 🎉

**Comment by ifeign** [comment]
I'm gonna chalk up my issues to my Ring having an unstable connection as
usual, will troubleshoot more later.

That's an interesting discovery regarding the subscription though!

**Comment by adavison007** [comment]
@dgreif Thanks for the work on this, appreciated... So on my local network everything works perfectly. When I switch to 4G everything in HomeKit works fine other than the ring cameras and motion sensors, they say not responding.. I revert back to wifi and they work immediately again... I have rebooted everything, Homebridge, AppleTV and phone..... have you tired the new code when on 4G?

**Comment by dgreif** [comment]
@adavison007 I just tried it and it's working for me on 4G now.  That bug was driving me crazy last week and then it just magically fixed itself after a day or two.  It's some weird combo between homebridge and all the HomeKit devices and unfortunately I don't think there is anything else I can do to debug it at this point.  Hopefully yours magically starts working too (maybe after another iOS 13 beta update) 🤞

**Comment by adavison007** [comment]
> @adavison007 I just tried it and it's working for me on 4G now. That bug was driving me crazy last week and then it just magically fixed itself after a day or two. It's some weird combo between homebridge and all the HomeKit devices and unfortunately I don't think there is anything else I can do to debug it at this point. Hopefully yours magically starts working too (maybe after another iOS 13 beta update) 🤞

@degreif ok, thanks' appreciate your work. So if it works for you and it used to work for me, I'm sure I can get it to work.... I'll remove a camera and add it and see what happens, if not I'll do a complete network reboot :) Thanks again

**Comment by EarthRise626** [comment]
@adavison I had the same exact issue when on LTE last week. My best guess is that if one of your iOS devices has not backed up to iCloud (which stores your HomeKit configuration) before you go offline, you will be unable to access the device remotely. The issue immediately stopped for me when I manually initiated an iCloud backup, let it finish, then disconnected from WiFi and tried again.

**Comment by adavison007** [comment]
> @adavison I had the same exact issue when on LTE last week. My best guess is that if one of your iOS devices has not backed up to iCloud (which stores your HomeKit configuration) before you go offline, you will be unable to access the device remotely. The issue immediately stopped for me when I manually initiated an iCloud backup, let it finish, then disconnected from WiFi and tried again.

@EarthRise626 Thanks for the tip, just did that, a few now work, others don't... I'll do it a few more times, then if not delete one of the non working ones and re add it and see what happens.

**Comment by jamesg311** [comment]
I upgraded to 5.3.2 tonight. Still getting these errors.  I also don't know why poor wifi is being reported. My doorbell (RVD2) and spotlight cam both report RSSI in the green range which means strong signal from my Eero mesh router on a 1 gig fiber ISP.

[8/7/2019, 8:09:11 PM] [Ring] 404 from endpoint https://api.ring.com/clients_api/snapshots/image/25408636
[8/7/2019, 8:09:11 PM] [Ring] Failed to retrieve snapshot for Driveway (0.304s).  Make sure the camera has power and a good wifi connection. The camera currently reports that is it online
[8/7/2019, 8:09:11 PM] [Ring] Error: Not found with response: no snapshot

    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:208:27)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[8/7/2019, 8:09:11 PM] [Ring] 404 from endpoint https://api.ring.com/clients_api/snapshots/image/6425034
[8/7/2019, 8:09:11 PM] [Ring] Failed to retrieve snapshot for Front Door (0.323s).  Make sure the camera has power and a good wifi connection. The camera currently reports that is it online
[8/7/2019, 8:09:11 PM] [Ring] Error: Not found with response: no snapshot

    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:208:27)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[8/7/2019, 8:09:20 PM] [Ring] Snapshot Requested for Backyard
[8/7/2019, 8:09:20 PM] [Ring] 404 from endpoint https://api.ring.com/clients_api/snapshots/image/11084782
[8/7/2019, 8:09:20 PM] [Ring] Failed to retrieve snapshot for Backyard (0.326s).  Make sure the camera has power and a good wifi connection. The camera currently reports that is it online
[8/7/2019, 8:09:20 PM] [Ring] Error: Not found with response: no snapshot

    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:208:27)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by dgreif** [comment]
@jamesg311 thanks for the logs! All three cameras report “online” so You can disregard the WiFi suggestion in the error. What type of cameras are each of them? Do snapshots work if you open the Ring app?

**Comment by jamesg311** [comment]
Driveway & Backyard are both Spotlight Cam Battery-powered models. The doorbell is Ring Video Doorbell 2 (note that motion notifications don't ever work for the Doorbell, despite changing the name to "Doorbell" and having motion notifications enabled).

Snapshots work in the Ring app. Sometimes they work in Home app except when I'm off network but I'm following some suggested troubleshooting on that (iCloud Backup that I read in this or another thread).

**Comment by Sunoo** [comment]
Wait, are motion notifications supposed to work? I’ve never gotten one and just assumed they weren’t implemented.

**Comment by jamesg311** [comment]
> Wait, are motion notifications supposed to work? I’ve never gotten one and just assumed they weren’t implemented.

For my Spotlight Cam's motion notifications do work. Sometimes they include snapshots too!

**Comment by Sunoo** [comment]
I just have a doorbell, but I’ve never gotten one. Huh.

**Comment by adavison007** [comment]
@dgreif Ok, so removed all camera's removed them via cli from Accessories file too.... rebooted Homebridge, deleted your plugin, rebooted home bridge... rebooted router, appleTV etc.... then reinstalled plugin and added 1 camera... BOOM! Works perfectly on the Wifi Network with snaps shot refresh every 10 seconds... went to 4G... it works... BUT the snaps shots take about 1 to 1.5 Minutes to refresh... is that normal behaviour? Do I need to change the timing settings?
<img width="690" alt="Screenshot 2019-08-08 at 08 46 17" src="https://user-images.githubusercontent.com/47482260/62684755-476e2580-b9b9-11e9-95d8-87a49483d02f.png">

**Comment by dgreif** [comment]
@adavison007 glad to hear you are making progress on the 4G issues!  Regarding the snapshots taking a while, it looks like they are being fetched nice and fast (~3s on average in your logs).  What you might be seeing that seems slow is the instances where we serve a stale image because it is less than 30 seconds old.  In your logs, the `8:42:01` and `8:42:12` lines are instances where this happened.  You can tell because it returns very quickly (.5s), which means it's just using the stale image rather than waiting for your camera to take a new image.  Hopefully that explains the behavior you are seeing, but let me know if you think there is a deeper issue.

@Sunoo motion alerts should work just fine with any of the cameras.  If it is a battery model (even if wired), you may get stale snapshots or no snapshots at all, but the motion alerts should work regardless.  Try turning the motion notifications off and back on in the Home app if they aren't working.

@jamesg311 I think I'm at the end of my ability to guess at the behavior for battery cameras and snapshots.  All of my cameras are wired so I haven't been seeing these session/404 issues that a lot of users are experiencing.  I finally broke down and ordered a battery stickup cam so that I can really test stuff out rather than crossing my fingers when I release fixes for the battery cams.  Hopefully I can get this all straightened out within the next week.  In the mean time, your cameras should correctly notify you of motion events but may not include a snapshot.

**Comment by adavison007** [comment]
> @adavison007 glad to hear you are making progress on the 4G issues! Regarding the snapshots taking a while, it looks like they are being fetched nice and fast (~3s on average in your logs). What you might be seeing that seems slow is the instances where we serve a stale image because it is less than 30 seconds old. In your logs, the `8:42:01` and `8:42:12` lines are instances where this happened. You can tell because it returns very quickly (.5s), which means it's just using the stale image rather than waiting for your camera to take a new image. Hopefully that explains the behavior you are seeing, but let me know if you think there is a deeper issue.
> 
> @Sunoo motion alerts should work just fine with any of the cameras. If it is a battery model (even if wired), you may get stale snapshots or no snapshots at all, but the motion alerts should work regardless. Try turning the motion notifications off and back on in the Home app if they aren't working.
> 
> @jamesg311 I think I'm at the end of my ability to guess at the behavior for battery cameras and snapshots. All of my cameras are wired so I haven't been seeing these session/404 issues that a lot of users are experiencing. I finally broke down and ordered a battery stickup cam so that I can really test stuff out rather than crossing my fingers when I release fixes for the battery cams. Hopefully I can get this all straightened out within the next week. In the mean time, your cameras should correctly notify you of motion events but may not include a snapshot.

@dgreif Thanks, take a look at the Kitchen Ring.... the fast kitchen updates are when it was on lan, then on 4G you see it's goes from 12 second updates to 3 minute updates for a snapshot... I'm cool with that, just sharing. if we can get the same update remote as local then awesome, if not fine, as the live video is instant on 4g... which is why i thought it strange that snapshots were not.

**Comment by Sunoo** [comment]
> @Sunoo motion alerts should work just fine with any of the cameras. If it is a battery model (even if wired), you may get stale snapshots or no snapshots at all, but the motion alerts should work regardless. Try turning the motion notifications off and back on in the Home app if they aren't working.

My doorbell is wireless, but wired to power. I tried toggling it on and off, but it's still not sending notifications.

**Comment by dgreif** [comment]
@adavison007 thanks for the clarification.  Just did a little testing and it looks like this is just a HomeKit thing.  If you are on wifi it will request snapshots every ~10 seconds, but on 4G it only requests them once a minute.  The plugin responds quickly, it's just not being asked for snapshots.  Good info to know 😄 

@Sunoo I'm not quite sure why you are not receiving the motion notifications.  Can you check the Home app to see if the camera motion sensor shows motion after you move in front of the camera? If it shows motion, then you may not have the notifications properly turned on.  Also, make sure you are on the latest version of the plugin as older version had an issue with snapshots that could break everything including notifications.

**Comment by adavison007** [comment]
@dgreif just tested the above and I am getting those exact results on all 11 cameras... 10 second snapshot on wifi and 1 minute on 4g, working flawlessly! NICE WORK.... 

The big question, do you think it will ever be possible for you to get sound and also answering and talking of a ring doorbell into this app? As I said before, I love your work and passion and would be happy to donate towards this project financially?

**Comment by dgreif** [comment]
@adavison007 thanks for confirming the snapshot timing!  Regarding audio, I am at a bit of a stand still.  It _should_ be possible, but we need to find a configuration that is supported by both HomeKit and Ring.  The main thing that I need is the SDP configuration for the audio streams, but the codec (AAC-ELD) does not appear to be widely used so I'm having trouble finding someone who can help create the proper SDP.  It's literally only 2 or 3 lines of code and then it should just work, but those lines need to be perfect.  As for 2-way, I think that should be possible once we get the configuration figured out.  I really just need some expert RTP/SDP help at this point.  Regarding donations, I am happy to accept them (especially since I just bought a stickup cam for testing).  There is a sponsor button at the top of the GitHub page that links to my paypal account.  Any amount is much appreciated ❤️

**Comment by adavison007** [comment]
@dgreif donation sent

**Comment by dgreif** [comment]
@adavison007 that was extremely generous, thank you very much!!

**Comment by adavison007** [comment]
> @adavison007 that was extremely generous, thank you very much!!

@dgreif I bought ring in 2016n for the fact they said HomeKit integration imminent... you made it happen they have not, that was worth it for me :) I am addicted to home automation with over 250 devices now... so when it works it makes me happy :)

**Comment by jamesg311** [comment]
> @dgreif I bought ring in 2016n for the fact they said HomeKit integration imminent... you made it happen they have not, that was worth it for me :) I am addicted to home automation with over 250 devices now... so when it works it makes me happy :)

Agreed. Sent you another donation @dgreif

**Comment by dgreif** [comment]
You guys are awesome.  Totally justifies my stickup cam purchase this morning, thank you!

**Comment by jamesg311** [comment]
> You guys are awesome.

No, you're awesome!

**Comment by adavison007** [comment]
> You guys are awesome. Totally justifies my stickup cam purchase this morning, thank you!

@dgreif and helps you justify it to the "other half" :)

**Comment by Sunoo** [comment]
> @Sunoo I'm not quite sure why you are not receiving the motion notifications. Can you check the Home app to see if the camera motion sensor shows motion after you move in front of the camera? If it shows motion, then you may not have the notifications properly turned on. Also, make sure you are on the latest version of the plugin as older version had an issue with snapshots that could break everything including notifications.

The Home app does not show motion being detected at all. And I am running the latest version of your plugin.

**Comment by EarthRise626** [comment]
I am on the latest version of the plugin and just updated to the latest public beta of iOS 13. Motion alerts are working very well for me.

**Comment by LeviJSmith** [comment]
Donation sent.  Thanks for all you do to make this work.  Ring promised us Homekit a long time ago and didn't deliver.  You did it with Homebridge and continue to make improvements.  Thanks for all you do.

**Comment by adavison007** [comment]
@dgreif I’m sat in Greece with 4mbps internet and everything is working perfectly, live feeds and 4G (lol) connectivity

**Comment by dgreif** [comment]
So I got my battery stickup cam and had some time to test it out with snapshots.  I think I really understand the limitations and functionality of the Ring api now, and just released some changes that should hopefully improve the snapshot experience on both wired and battery cameras.  We are still limited to 30s/10m for battery/wired cameras, but I'm being smarter about looking at when the last snapshot was taken and not fetching stale images over and over again.  I would appreciate any feedback on how snapshots work for you all on v`5.4.1`.  Assuming everything works at least as well as before, I think we can get this issue closed out as the session hardware_id issue is all fixed up.  Thanks again to everyone who donated over the last few days to help cover the cost of the camera ❤️

**Comment by jamesg311** [comment]
Whatever you did...it worked great! Just got my first doorbell motion notification!
