### ISSUE TITLE
controlCenterDisplayName no longer works

### ISSUE THREAD

**Issue by djm181** [dgreif/ring#920]
# Bug Report

### Describe the Bug
Setting `controlCenterDisplayName` in the RingAPI options no longer has the desired effect in the Ring control center.

### To Reproduce
Create an authenticated instance of the RingApi client and explicitly set `controlCenterDisplayName` to some string.
View authorized client devices in the ring web control center. Observe that the device is named `Device name not found`

### Expected behavior
Expect that the device name is shown on the authorized device

### Screenshots/Logs
<img width="523" alt="Screen Shot 2022-04-22 at 12 36 45 PM" src="https://user-images.githubusercontent.com/4303695/164765830-1290e110-3683-466c-a7cb-5a874a1c9bc5.png">

### Additional context
This appeared to work with client v9.18, so not sure if this is just a recent change on the ring side, or whether it's related to the v10 APIs

### Environment

 - OS: MacOS and Alpine Linux
 - Node.js: 16.14.2
 - ring-client-api: 10.0.0-beta5

**Comment by dgreif** [comment]
@djm181 this may be related to the push notification changes in the v10 beta.  I'll take a look when I get a chance.  Thanks for letting me know!
