### ISSUE TITLE
Call to `getLocations()` returns 404 error

### ISSUE THREAD

**Issue by raleighlittles** [dgreif/ring#921]
# Bug Report

### Describe the Bug
 

Calling `getLocations()` in the simplest manner returns a 404 error.

### To Reproduce
Execute the following code:

```javascript
import { RingApi } from 'ring-client-api'

let ringApi = new RingApi({
       // Replace with your refresh token
       "refreshToken": "blah-blah-blah"
     });

const locations = await ringApi.getLocations();
const camerasAtPrimaryLocation = await locations[0].cameras;
```

### Expected behavior

The code would successfully run.

### Screenshots/Logs
 The error output it produced was very large (5000+ lines) for some reason, so I attached it as a separate file.
[error_log.txt](https://github.com/dgreif/ring/files/8586504/error_log.txt)

Here's the first few lines of it

```
/home/raleigh/node_modules/ring-client-api/node_modules/axios/lib/core/createError.js:16
  var error = new Error(message);
              ^

Error: Request failed with status code 404
    at createError (/home/raleigh/node_modules/ring-client-api/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/raleigh/node_modules/ring-client-api/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/raleigh/node_modules/ring-client-api/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  config: {

```

### Additional context
 Add any other context about the problem here.

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1]  v16.15.0

 - NPM: [e.g 6.13.4]  8.5.5

 - ring-client-api: [e.g 6.0.3]

**Comment by dgreif** [comment]
Your logs reference `https://app.ring.com/rhq/v1/devices/v1/locations`, which is not anywhere in the code base today.  I'm guessing you are just on a super old version, though you didn't provide a version number in the issue.  Please try updating to the latest version
