### ISSUE TITLE
Same performance as rapid ring.

### ISSUE THREAD

**Issue by RaffoNin** [dgreif/ring#923]
Just a suggestion to look at what rapid ring is doing differently if anything at all. 

I noticed that my doorbell's feed is good with rapid ring but there's frame drops when i use HomeKit or the normal Ring app.

**Comment by dgreif** [comment]
I just took a look at the Rapid Ring app and it appears to be using the _old_ (SIP) connection strategy.  The Ring app and homebridge-ring (on the beta branch) are using webrtc, which is the newer connection strategy.  It's unfortunate that you are seeing dropped frames, but I suggest you let Ring customer service know that it's happening in the Ring app (no need to mention homebridge).  This is something they should fix on their end.
