### ISSUE TITLE
No Sound for Cameras on aarch64

### ISSUE THREAD

**Issue by YPyltiai** [dgreif/ring#925]
# Bug Report

### Describe the Bug
Sounds in camera/doorbell feed doesn't work with aarch64 Raspbian 11 (Debian 11 Bullseye), while Homebridge is installed in Docker. I looked at Dockerfile and it should be installing FFMPEG fine, so something else looks to be going wrong.

### To Reproduce
- Installed latest Raspbian 11 (Debian 11 Bullseye) on RPi
- Homebridge runs in Docker using https://github.com/oznu/docker-homebridge
- When trying to view camera/doorbell, getting error `[Ring] Streaming video only - ffmpeg was not found. See https://github.com/dgreif/ring/wiki/FFmpeg for details.` Sound is not working, though the camera itself does. Guide on that link mentioned supporting aarch64 but it doesn't work.
- https://github.com/oznu/docker-homebridge/blob/master/Dockerfile#L12-L20 seems to be installing FFMPEG into the image and I confirmed that `uname -m` will return `aarch64`, so I should be getting an image with FFMPEG but sounds still doesn't work

### Expected behavior
Camera feed and sound work as expected.

### Screenshots/Logs
`[Ring] Streaming video only - ffmpeg was not found. See https://github.com/dgreif/ring/wiki/FFmpeg for details.`
Nothing else in logs that is out of normal.

### Homebridge Ring Config
Vanilla config.

### Environment

 - OS: Raspbian 11, 64-bit
 - Node.js: latest
 - NPM: latest
 - homebridge-ring: 10.0.0-beta4
 - homebridge: 1.4.1

**Comment by YPyltiai** [comment]
Also just confirmed that FFMPEG is indeed in the container:
<img width="602" alt="Screen Shot 2022-05-02 at 10 42 41 PM" src="https://user-images.githubusercontent.com/26441563/166402227-a6c9763f-d592-4e5a-8361-4fdb905f1cbb.png">

**Comment by dgreif** [comment]
You should be able to manually set the `ffmpegPath` in your config to point to the ffmpeg binary.  `which ffmpeg` should give you the path

**Comment by YPyltiai** [comment]
@dgreif huge thanks - it worked. On the other note though - prior to Debian 11 64-bit it worked without requiring this config change. Not sure if the path changed but now you actually need to set it. I looked at recent image changes by @oznu , there are no changes around the way FFMPEG is pulled into the image, so not sure what caused this.

For reference - I had to add `"ffmpegPath": "/usr/local/bin/ffmpeg"` to fix the issue to homebridge-ring config. This also doesn't look to be available in UI, so has to be added to JSON directly.

**Comment by dgreif** [comment]
Thanks @oznu!  I've got the day off tomorrow so I'm hoping to get my `beta` branch into a releasable state, and will include that update in there.

**Comment by dgreif** [comment]
@YPyltiai have you tried the latest version of the plugin (11+)?

**Comment by YPyltiai** [comment]
@dgreif I am on latest now but I haven’t changed the settings since last time since it didn’t hurt to just leave that variable there.
