### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-ring:` v 10.0.0 upon starting homebridge v1.4.1

### ISSUE THREAD

**Issue by loudgazelle** [dgreif/ring#926]
# Bug Report

### Describe the Bug
`ERROR LOADING PLUGIN homebridge-ring:` upon starting homebridge v1.4.1

### To Reproduce
 - Start Homebridge

### Expected behavior
i expected homebridge to load the Ring plugin, but it didn't

### Screenshots/Logs
this error displays during homebridge startup: 
```
[5/8/2022, 10:55:39 AM] ====================
[5/8/2022, 10:55:39 AM] ERROR LOADING PLUGIN homebridge-ring:
[5/8/2022, 10:55:39 AM] /usr/local/lib/node_modules/homebridge-ring/node_modules/@koush/werift/lib/ice/src/ice.js:142
                if (exc.response?.attributes["ERROR-CODE"][0] === 487) {
                                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/@koush/ice/src/index.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/@koush/werift/src/index.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
[5/8/2022, 10:55:39 AM] ====================
[5/8/2022, 10:55:42 AM] Loaded plugin: homebridge-weather-plus@3.2.6
[5/8/2022, 10:55:47 AM] Registering platform 'homebridge-weather-plus.WeatherPlus'
[5/8/2022, 10:55:47 AM] ---
[5/8/2022, 10:55:47 AM] Loading 5 platforms...
[5/8/2022, 10:55:47 AM] [Nest] Initializing Nest platform...
[5/8/2022, 10:55:47 AM] [Config] Initializing config platform...
[5/8/2022, 10:55:47 AM] [Config] Running in Service Mode
[5/8/2022, 10:55:47 AM] No plugin was found for the platform "Ring" in your config.json. Please make sure the corresponding plugin is installed correctly.
```

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
        {
            "refreshToken": "<redacted>",
            "platform": "Ring"
        },
```

### Environment

 - OS: MacOS 10.15.7 (19H1824)]
 - Node.js: v12.19.0
 - NPM: 6.14.8
 - homebridge-ring: v10.0.0
 - homebridge: v1.4.1
 - hoobs:  N/A

**Comment by awrobinson95** [comment]
I'm getting the same error

**Comment by Manav-Seth** [comment]
I am also getting the same error. On macOS.

**Comment by dgreif** [comment]
Looks like you are on node 12, which must not support optional chaining.  I'll change the target, but the quick fix on your end is to update node, preferably to node 16.  I didn't intend to drop node 12 support, so I'll get this fixed as soon as I get a chance.

**Comment by dgreif** [comment]
Looks like `werift` does not support node 12 or 14, and `werift` is an essential part of the updates in v10.  As such, I'm bumping the minimum node version to 16.  Updating your node version is the correct solution to this error.  Sorry for the extra hassle, but staying up to date on node is a good practice regardless 😄

**Comment by theimo1221** [comment]
@dgreif Whilst I understand your point of updating beeing a good practice, there are systems with legacy requirements.

Take [Iobroker Ring](https://github.com/iobroker-community-adapters/ioBroker.ring) for example:
- We use your library (thanks for that 👍 )
- Iobroker itself allows node [12.x to 16.x](https://github.com/ioBroker/ioBroker.js-controller)
- Some adapter are not working with node 14.x and higher

So I have 2 options either I don't upgrade this library (which I might have to as soon as ring changes something) or force the users of `iobroker.ring` to upgrade their instance to node 16.x, which might result in users having problems with other adapter.

I'd highly appreciate, if you could add a legacy switch, which (while reducing some functionality) still allows node 12.x and 14.x environments.

**Comment by dgreif** [comment]
@theimo1221 I get where you are coming from!  I don't like forcing users to update to 16 either (14 is still LTS so I'd like to support it).  Unfortunately my recent changes are heavily dependent on [`werift-webrtc`](https://github.com/shinyoshiaki/werift-webrtc), which only supports `^15`. This change allowed me to use newer Ring APIs and delete a ton of really nasty SIP code.  If there were another webrtc alternative, I'd definitely consider switching, but I don't want to add the SIP code back into this repo.  For now, users should be safe to stay on v9 of the ring client api. Hopefully Ring doesn't break anything too badly, giving you time to support your users in updating to node 16.  Backward compatibility is ideal, but sometimes it's just not worth it and we need to move forward 😅

**Comment by rakgupta** [comment]
> For now, users should be safe to stay on v9 of the ring client api.

I'm sorta in the same boat. I'm using Node-RED on the Homebridge image and that is on Node v14. My understanding is that there are some issues with **a few** Node-RED nodes and Node v16 so I am a little hesitant to upgrade (Node-RED has all my home automation logic). Hopefully, it will get sorted soon 🤞

**Comment by awrobinson95** [comment]
Can I just confirm whether the updating of Node is a manual additional step on Homebridge Pi or whether this is included in the package update?

**Comment by dgreif** [comment]
@awrobinson95  it's separate from updating the plugin. How you update node will depend on your install. Should be easy to find instructions via Google

**Comment by theimo1221** [comment]
@dgreif I had some more thoughts on the v16 topic:

As this library (except Webrtc) would still work with v14, wouldn't it be possible to not enforce v16 in package.json and only mark the relevant functions and add a warning in readme?

Additionally one could think about throwing an error in those functions in case of the environment not matching the needed criteria.

**Comment by dgreif** [comment]
> Some adapter are not working with node 14.x and higher

@theimo1221 in my mind, the fact that some of the adapters are not supporting newer versions of Node is the real issue.  Node 16 has been out for a full year, and has been LTS for over 6 months.  At this point, I can't think of a good reason not to _expect_ it to be supported by any packages that are actively maintained.  I can understand the frustration and decisions this change has pushed upon some users, but I do think that moving forward and requiring the _latest_ LTS version is the right move.  We can't slow down the whole ecosystem for the sake of a few packages that aren't keeping up.

To be clear, you are welcome to stay on version 9 of the ring client, which was working well.  I don't intend to backport fixes in the future, but for now it should continue to work well unless Ring breaks something on their end.  I hear you on the "legacy" switch idea, but a large part of the changes in v11 were changes that allowed me to remove some of the most difficult-to-maintain code in the repo.  I don't want to bring all of that back and maintain it in parallel with the replacement.  I appreciate your feedback, and hope that the other packages holding you back are fixed soon.

**Comment by theimo1221** [comment]
Good Morning,

as I respect your position of going forward I totally understand this:
>  I don't want to bring all of that back and maintain it in parallel with the replacement.

With my last message I wasn't asking about bringing SIP back, I was asking to think about not strictly enforcing v16 on the user, rather warning/informing him (`To use webRtc functionality you need at least Node V16`):
https://github.com/dgreif/ring/blob/ad3ac6f21ef87dc17c5b1ebd45e16a7d4cbfbc2a/package.json#L99-L102

Correct me if I'm wrong, but Node v16 is only needed in the webrtc session context. So as long as the package using this library doesn't start/use the webrtc functions, we could continue using node v14.
In some ecosystems (e.g. ioBroker) utilizing the WebRtc function (which itself is great improvement in comparision to sip) might not be possible at all.
