### ISSUE TITLE
Error: Cannot find module 'timers/promises' on RPI 4

### ISSUE THREAD

**Issue by Rem-bo** [dgreif/ring#927]
# Bug Report

### Describe the Bug
After installing the homebridge-ring plugin on my RPI 4 and latest node/nodejs/npm versions, I get this error during startup of the plugin:

[9-5-2022 18:12:20] ====================
[9-5-2022 18:12:20] ERROR LOADING PLUGIN homebridge-ring:
[9-5-2022 18:12:20] Error: Cannot find module 'timers/promises'
Require stack:
- /usr/lib/node_modules/homebridge-ring/node_modules/@koush/werift/lib/ice/src/ice.js
- /usr/lib/node_modules/homebridge-ring/node_modules/@koush/werift/lib/ice/src/index.js
- /usr/lib/node_modules/homebridge-ring/node_modules/@koush/werift/lib/webrtc/src/index.js
- /usr/lib/node_modules/homebridge-ring/lib/api/streaming/peer-connection.js
- /usr/lib/node_modules/homebridge-ring/lib/api/streaming/streaming-connection-base.js
- /usr/lib/node_modules/homebridge-ring/lib/api/streaming/webrtc-connection.js
- /usr/lib/node_modules/homebridge-ring/lib/api/ring-camera.js
- /usr/lib/node_modules/homebridge-ring/lib/api/location.js
- /usr/lib/node_modules/homebridge-ring/lib/api/api.js
- /usr/lib/node_modules/homebridge-ring/lib/api/index.js
- /usr/lib/node_modules/homebridge-ring/lib/homebridge/ring-platform.js
- /usr/lib/node_modules/homebridge-ring/lib/homebridge/index.js
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-ring/node_modules/@koush/ice/src/ice.ts:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
[9-5-2022 18:12:20] ====================

Can you help out on what is wrong? Thanks!

### To Reproduce
 - Start Homebridge

### Expected behavior
Plugin starting up, no errors

### Screenshots/Logs
See above

### Additional context
I am not a specialist in this area, so perhaps it is something stupid. But I googled on this message/error and all I could find is to update NPM, which I did, but no result.

### Homebridge Ring Config
{
            "refreshToken": "xxxxx",
            "platform": "Ring",
            "_bridge": {
                "username": "0E:92:66:84:10:E8",
                "port": 43686
            }
        }

### Environment

 - OS: [e.g. Raspbian] Buster
 - Node.js: [e.g. 12.14.1] 14.69.2
 - NPM: [e.g 6.13.4] 6.14.17
 - homebridge-ring: [e.g 6.0.3] 11.0.0 latest
 - homebridge: [e.g. 0.4.50 or N/A] 1.4.1
 - hoobs: [e.g. 0.4.50 or N/A] N/A

**Comment by timsayshey** [comment]
Same error! Tried downgrading to 10.0.0 and it's still happening. Running on Docker.

**Comment by tsightler** [comment]
I think this is due to outdated NodeJS version, new version requires NodeJS 16 while the post above indicates only NodeJS 14 is installed.

**Comment by timsayshey** [comment]
Interesting, I guess the official Homebridge Docker image is using Node 14 then. I'm using the latest release. The plugin will be borked for everyone until that's updated, and I somehow doubt they are going to update due to the other plugins that would be effected. 🤦🏻‍♂️

**Comment by tsightler** [comment]
Looking at the repo for the official image and at the latest image on Docker Hub, it certainly appears that current images are based on NodeJS 16.15, and, looking at the change log, it appears that the images switched to NodeJS 16 some months ago.  When is the last time you pulled an updated image?

**Comment by Rem-bo** [comment]
Thanks! Indeed I see nodejs has old version and via nvm I updated nom and node, but still nodes has the old version.
Sorry to be a ... but how do I update nodes or can i simply remove it as I read everywhere it are the same things and installing via nvm should be enough?
Please help me out.... thanks

**Comment by timsayshey** [comment]
@tsightler Yep, a `docker-compose pull` grabbed the latest image and fixed the issue. Thanks!

**Comment by tsightler** [comment]
@Rem-bo I'm actually not a Homebridge user, so I'm of little help on exactly how to do it, and I believe it depends quite a bit on exactly what method you used to install Homebridge.  However, there are quite a few resources on the Homebridge site around this:
https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js

Or, if using the official Docker install method, pulling the latest image should do it (documented here):
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Docker#major-nodejs-version-updates

**Comment by Rem-bo** [comment]
Thanks @tsightler indeed I had to update homebridge via your link which also included latest nodejs.... now it works! 
Thanks a lot!
