### ISSUE TITLE
Live feed NAT Traversal - not working for some environments

### ISSUE THREAD

**Issue by taherkaraki** [dgreif/ring#93]
Hello @dgreif 

Upgraded to 5.0.0 as you recommended, however live streams still do not work in my environment.

**[8/1/2019, 9:26:21 PM] [Ring] Preparing Live Stream for Front Door
[8/1/2019, 9:26:31 PM] [Ring] Waiting for stream data from Front Door
[8/1/2019, 9:26:32 PM] [Ring] Stopped Live Stream for Front Door**

Not sure if that works with my network setup, but I can allow some inbound ports to be forwarded to the homebridge. But is port 5060 tcp/udp enough?

**Comment by taherkaraki** [comment]
Some people have had some success with SIP over NAT by disabling the SIP application layer gateway on their routers, which sometimes causes VoIP messages to be modified in a harmful way. I did disable it for my technicolor router, but that didn't resolve it for me. Maybe it works for somebody else. http://www.surevoip.co.uk/support/wiki/troubleshooting:sip_alg:technicolor

**Comment by onefish2** [comment]
Try opening tcp/udp port range 50,000 to 59,999 for the IP of your homebridge device. Then reboot your homebridge device, your iPhone and Apple TVs or iPads that you are using as your home hub(s). 

Before the latest round of updates that is how I got my Ring devices to stream with the Apple Airport Extreme as my router.

**Comment by dgreif** [comment]
@taherkaraki the plugin binds to a random port (anywhere between 30k and 65k ish range) so 5060 isn’t even used. See if your router has an option to turn on UPnP or NAT-PMP as those can be used by the plugin to negotiate opening ports with NAT

**Comment by dgreif** [comment]
@taherkaraki did you get it working?  Do you have UPnP or NAT-PMP that you can turn on?

**Comment by dgreif** [comment]
@taherkaraki see https://github.com/dgreif/ring/issues/99#issuecomment-520257219.  I'm sorry but there isn't much I can do to help in this situation.  Let me know if you get it working!
