### ISSUE TITLE
ERRORError loading plugin "homebridge-ring"

### ISSUE THREAD

**Issue by paskalicky** [dgreif/ring#935]
# Bug Report

### Describe the Bug
Hoobs ring plugin will not load
Error loading plugin "homebridge-ring"

### To Reproduce
Uninstalled and reinstalled several times same result

### Expected behavior
Available in HomeKit

### Screenshots/Logs
[log-3.txt](https://github.com/dgreif/ring/files/8681177/log-3.txt)

![Screen Shot 2022-05-12 at 9 55 47 AM](https://user-images.githubusercontent.com/58667302/168129232-07c68b6f-421b-4f4a-92b3-b10f06497baa.jpg)
![Screen Shot 2022-05-12 at 10 01 57 AM](https://user-images.githubusercontent.com/58667302/168129748-ea8aa18e-ee46-4f49-aa8a-d9cd58cba26b.jpg)

### Additional context
 Add any other context about the problem here.

### Environment
Hoobs box
Ring plugin v11.0
MacOS 12.3.1

**Comment by dgreif** [comment]
You need to update to node 16 to fix this issue
