### ISSUE TITLE
Yale conexis L1 lock no longer works in home app it works on the ring app and in Alexa and it shows In my bridge ? Please help

### ISSUE THREAD

**Issue by B4DBJ** [dgreif/ring#939]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by B4DBJ** [comment]
Running node 16.15.0
Homebridge ui x v4.44.1
Ring v11

**Comment by dgreif** [comment]
@B4DBJ sorry I didn't see this earlier. Is it still not working for you on the latest version of the plugin? Do you _see_ the lock in the Home app? If so, can you run the [data discovery](https://github.com/dgreif/ring/wiki/Data-Discovery) tool and post the results here?

**Comment by B4DBJ** [comment]
All working now thanks that was a while ago 

Thanks
