### ISSUE TITLE
[Streaming]: Apple TV 4K shows no response

### ISSUE THREAD

**Issue by ands0me** [dgreif/ring#940]
### Streaming Issue

On Apple TV 4K live Feed for Ring cameras won’t stream. „No response“. Also no snapshots.
When I start streaming on Apple TV no log of Ring in Homebridge. 

### Proposed Solution

Downgraded Ring plug-in to 9.2.4 now it’s working.

### Environment

Homebridge

### What operating system are you on?

Linux

### Honesty Time

- [X] I swear this is worth your time!

**Comment by dgreif** [comment]
Did you check your logs?  I'm guessing you are not using node 16, so your homebridge plugin probably wasn't working at atll.

**Comment by ands0me** [comment]
![585269C3-A390-4662-9982-62CE73390857](https://user-images.githubusercontent.com/74508966/169337534-c1e35f53-86c2-4697-b992-a7a0da594b06.png)

> I’ve checked the logs. No entering when I start streaming on Apple TV.

**Comment by dgreif** [comment]
Can you try v`11.0.2`?

**Comment by dgreif** [comment]
Very possible that it's an Apple TV issue.  Does it work on your phone? Are you using a beta version of tvOS?

**Comment by ands0me** [comment]
It’s working fine on iPhone and iPad.
No beta version on tvOS.

**Comment by dgreif** [comment]
In that case, I'd say this is an Apple issue.  Sorry I can't do more!

**Comment by ands0me** [comment]
But if it’s an tvOS issue why the stream of eufy cam working properly?
