### ISSUE TITLE
[Streaming]: 

### ISSUE THREAD

**Issue by ScharV** [dgreif/ring#949]
### Streaming Issue

Hey @dgreif,
just upgraded my Hoobs plugins including ring.
11.0.2 doesn’t allow me to get live feed from doorview cam. It loads and becomes unresponsive.
When stopping livestream Hoobs bridge restarts.
Downgraded to 11.0.1 and got same behavior.
Downgraded to 11.0.0 then and live came back.
Using node 16.15.0 and latest Hoobs 4.2.25

### Proposed Solution

Couldn’t get one so far.

### Environment

HOOBS

### What operating system are you on?

Linux

### Honesty Time

- [X] I swear this is worth your time!

**Comment by dgreif** [comment]
Very odd, 11.0.2 should have fixes but not break anything that worked in 11.0.0.  Would you mind updating to 11.0.2 and trying again?

**Comment by ScharV** [comment]
Yeah for sure👌🏼

**Comment by ScharV** [comment]
Did it and it's the same behavior🤷🏻‍♂️
Steps I tried:
- Upgrading exact from 11.0.0 t0 11.0.2 with automatically bridge restart

- Directly after upgrading manual bridge restart 

- Checking HomeKit --> no live feed and restarting bridge after leaving live view
Rebooting pi

- Checking HomeKit --> no live feed and restarting bridge after leaving live view

- downgrade to 11.0.0 with automatically bridge restart

- Checking HomeKit --> live feed without restarting bridge after leaving live view like expected

**Comment by ScharV** [comment]
Ah forgot about something. Everything running on a PI 4 with 4GB Ram

**Comment by dgreif** [comment]
Could you set `"debug": true` in your homerbidge-ring config and then grab the logs from a stream on `11.0.2`?

**Comment by rfiorentino1** [comment]
Having the same issue here, live stream doesn't work for me after 11.0.2 update, but 11.0.1 works :)

**Comment by thatsnasty** [comment]
Most likely same issue as [here](https://github.com/dgreif/ring/issues/950#issuecomment-1137083379)

I've supplied logs there

**Comment by ScharV** [comment]
Hey @dgreif sorry for the late reply. Upgraded to 11.0.2 and enabled debug logging. Don't know why but it's working fine.
Disabled debug logging for testing and it's still running🤷🏻‍♂️

**Comment by rfiorentino1** [comment]
Interestingly, it works just fine for me if ring has already started a motion event etc. and is streaming. But if the camera is not recording already, and the home app/home bridge wants to create a live view, this fails. Having said that, the return audio is much better in the latest version of this plug-in, so thank you, I really appreciate that :-)

**Comment by rfiorentino1** [comment]
Still not working for me after doing the latest update

Rocco Fiorentino
www.musicbyrocco.com
(609)922-3838

On May 28, 2022, at 5:52 PM, Dusty Greif ***@***.***> wrote:

﻿

Closed #949<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dgreif_ring_issues_949&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=-Wz_8AA2h0D_SNC2pXWJPZoVxx1xMF5SpNfBGway-80&m=1_by78AiNJWuACFiWzMe79fWGubxyT-NLi40j3kBjHk&s=GVApPWpd0gCS02J9mVwT2pe4ZlJ_-IOIe9Zi9aRe070&e=> as completed.
