### ISSUE TITLE
Does the Ring API include an endpoint for updating Z-Wave config parameters?

### ISSUE THREAD

**Issue by smockle** [dgreif/ring#95]
I have a GE 14294 Z-Wave Plus Dimmer Switch. The default dim rate is too slow for my taste. The device supports several Z-Wave configuration parameters: https://www.ezzwave.com/sites/jasco/uploads/documents/PDFs/part2/14294_Product_Page.pdf. I can update the values of these parameters using SmartThings or Home Assistant. Does the Ring Alarm Base Station Z-Wave Controller also support this? If so, is this functionality exposed in the API?

**Comment by dgreif** [comment]
I haven’t looked into this at all. If it isn’t possible through the Ring app then it will be hard to figure out the endpoints since they don’t have documentation. Looks like you made a fork so maybe you found something already. I would be happy to take a PR if you get it figured out

**Comment by smockle** [comment]
Thanks for the reply @dgreif! I contacted Ring support, and they confirmed the app currently does not support this. I’ll close this issue, and will perhaps revisit this if and when the app gains support, because then it will be easier to track down.

(Sidebar: My fork is for PR #94, not for this issue. I apologize for the confusion.)

**Comment by smockle** [comment]
Update: I found a workaround for this!

I added a [SmartThings Hub as a secondary controller](https://support.smartthings.com/hc/en-us/articles/204392790-Z-Wave-General-Info#h_ea1b77f8-582f-4f84-af45-ac63b4bd9668) on the Ring Alarm Z-Wave network. Using a [custom device handler](https://github.com/nuttytree/Nutty-SmartThings/blob/master/devicetypes/nuttytree/ge-jasco-zwave-plus-on-off-switch.src/ge-jasco-zwave-plus-on-off-switch.groovy), I successfully updated parameters 8, 10 & 12 on the dimmer switches on my Ring Alarm Z-Wave network.

There is a drawback—unfortunately, when new Z-Wave devices are added to the Ring Alarm Z-Wave network, SmartThings is not notified. I’ve only been able to make the SmartThings Hub aware of new devices by excluding then re-including it, but then all previous configuration (device names, etc.) must be repeated.

**Comment by rchybicki** [comment]
@smockle You might the only person on the interwebs that added another Z-wave hub as a secondary controller to Ring. Did your SmartThings hub get events from Ring sensors after you did that? Like door/windows and motion sensors.

**Comment by smockle** [comment]
From @rchybicki in https://github.com/dgreif/ring/issues/95#issuecomment-974669018
> @smockle You might the only person on the interwebs that added another Z-wave hub as a secondary controller to Ring. Did your SmartThings hub get events from Ring sensors after you did that? Like door/windows and motion sensors.

I removed the SmartThings Hub from the Ring Alarm Z-Wave network after I updated the parameters, to reduce network traffic. I didn’t test sensor events specifically, but I remember SmartThings showed light status (on/off), so I assume some status information was being sent/received.
