### ISSUE TITLE
New Device: lpd_v4

### ISSUE THREAD

**Issue by theimo1221** [dgreif/ring#951]
# Feature Request

### Description
As reported here https://github.com/iobroker-community-adapters/ioBroker.ring/issues/261 by @Vijabei there seems to be a new version of the `lpd` doorbell

I will give him an update of the iobroker adapter soon, so that he can check if everything else works as with the other doorbells.

Best Regards 

Thiemo

**Comment by dgreif** [comment]
I'm going to add this and call it a "Doorbell". Do you happen to know which model it actually is? A link to the Ring website for this model would be ideal if you have it :smile:

**Comment by theimo1221** [comment]
@dgreif as per this [statement](https://github.com/tsightler/ring-mqtt/issues/420#issuecomment-1216555248) I guess it's the [Video Doorbell Pro 2](https://eu.ring.com/products/video-doorbell-pro-2)

**Comment by dgreif** [comment]
Thanks! I'll have this updated in the next release
