### ISSUE TITLE
Errors on update attempt

### ISSUE THREAD

**Issue by johnkirkster** [dgreif/ring#954]
# Bug Report

### Describe the Bug
I get an error when trying to update the plugin to the newest.  Any idea of what to do to resolve?

### To Reproduce
 - Start Homebridge
 - Attempt to update the plugin
 - And the update ends with an error description.
 - 
### Expected behavior
I would expect it to update.

### Screenshots/Logs
CMD: sudo -E -n npm install -g homebridge-ring@latest

npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/homebridge-ring/node_modules/ffmpeg-for-homebridge
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Downloading ffmpeg from https://github.com/homebridge/ffmpeg-for-homebridge/releases/download/v0.1.0/ffmpeg-raspbian-armv6l.tar.gz
npm ERR! node:events:505
npm ERR!       throw er; // Unhandled 'error' event
npm ERR!       ^
npm ERR! 
npm ERR! Error: EACCES: permission denied, open '/home/pi/.npm/_ffmpeg_for_homebridge/.download'
npm ERR! Emitted 'error' event on WriteStream instance at:
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/home/pi/.npm/_ffmpeg_for_homebridge/.download'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-05-29T08_15_58_493Z-debug-0.log
### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
 HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

       {
            "platform": "Ring",
            "refreshToken": "XXX",
            "alarmOnEntryDelay": true,
            "hideLightGroups": true,
            "hideCameraSirenSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "showPanicButtons": false,
            "sendDoorbellMotionNotificationsToTv": false
        },

### Environment
 - OS: Raspbian GNU/Linux Buster (10)
 - Node.js: v16.15.0
 - NPM: 8.5.5
 - homebridge-ring:  v11.0.2
 - homebridge: v1.4.1
 - hoobs: NA

**Comment by dgreif** [comment]
This is an error from npm, stating that it does not have access to write the ffmpeg file to the desired directory.  I see you are using sudo, but I think you need to include `--unsafe-perm` on the npm command for this to work properly.  If you use the homerbidge-config-ui-x to update plugins, it should use the correct command for you.

**Comment by CHAMLEX** [comment]
I ran into the same issue, I'm running the update via homebridge-vm and via the homebridge-config-ui-x.  I haven't had any issues updating before but this time I get the following

USER: root
DIR: /homebridge
CMD: npm install --save homebridge-ring@latest

npm ERR! code 1
npm ERR! path /homebridge/node_modules/homebridge-ring/node_modules/ffmpeg-for-homebridge
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Downloading ffmpeg from https://github.com/homebridge/ffmpeg-for-homebridge/releases/download/v0.1.0/ffmpeg-debian-x86_64.tar.gz
npm ERR! node:events:368
npm ERR!       throw er; // Unhandled 'error' event
npm ERR!       ^
npm ERR! 
npm ERR! Error: EACCES: permission denied, open '/root/.npm/_ffmpeg_for_homebridge/.download'
npm ERR! Emitted 'error' event on WriteStream instance at:
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/root/.npm/_ffmpeg_for_homebridge/.download'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-29T23_34_54_165Z-debug.log

Operation failed. Please review log for details.

**Comment by dgreif** [comment]
@oznu do you know off hand how to fix this?

**Comment by johnkirkster** [comment]
> This is an error from npm, stating that it does not have access to write the ffmpeg file to the desired directory. I see you are using sudo, but I think you need to include `--unsafe-perm` on the npm command for this to work properly. If you use the homerbidge-config-ui-x to update plugins, it should use the correct command for you.

Hi dgreif,
This problem just occurred at the latest release, I have updated this plugin a numerous amount of times, so I guess it must be a change in the plugin causing this?

**Comment by skcuslleb** [comment]
Not sure if this is the same issue or not, but I'm getting a Permission Denied error on config.json?

Error: EACCES: permission denied, open '/homebridge/config.json'
    at Object.openSync (node:fs:585:3)
    at writeFileSync (node:fs:2170:35)
    at updateHomebridgeConfig (/homebridge/node_modules/homebridge-ring/lib/homebridge/config.js:11:32)
    at Object.next (/homebridge/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:252:49)
    at ConsumerObserver.next (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:161:25)
    at SafeSubscriber.Subscriber._next (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:119:22)
    at SafeSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at ReplaySubject._subscribe (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/ReplaySubject.ts:80:18)
    at ReplaySubject.Observable._trySubscribe (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Observable.ts:245:19)
    at ReplaySubject.Subject._trySubscribe (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subject.ts:113:31)

**Comment by johnkirkster** [comment]
> Seems there's a permission issue to that file?

pi@homebridge:/var/lib/homebridge $ rm -rf /root/.npm/_ffmpeg_for_homebridge/.download 
rm: cannot remove '/root/.npm/_ffmpeg_for_homebridge/.download': Permission denied

**Comment by johnkirkster** [comment]
> Yeah, the big change in the latest version is an updated version of the ffmpeg dependency, which is what is failing to install. Because this install happens in a postinstall script, permissions can be a bit odd. Maybe try removing the target directory by running `rm -rf /root/.npm/_ffmpeg_for_homebridge/.download` and trying again?

Seems there's a permission issue with that file?
```
pi@homebridge:/var/lib/homebridge $ rm -rf /root/.npm/_ffmpeg_for_homebridge/.download 
rm: cannot remove '/root/.npm/_ffmpeg_for_homebridge/.download': Permission denied
```

**Comment by johnkirkster** [comment]
Ok @dgreif, now I just tried updating the plugin again - and it did flawlessly - so I'm at v11.0.4 now. strange.

**Comment by CHAMLEX** [comment]
Same here.  I just tried this morning and it updated without any problems.  

> Ok @dgreif, now I just tried updating the plugin again - and it did flawlessly - so I'm at v11.0.4 now. strange.
