### ISSUE TITLE
Live streams only work temporarily after reinstalling/updating

### ISSUE THREAD

**Issue by metroidmen** [dgreif/ring#96]
So I know @dgreif has mentioned to me several times that he feels there is something on my end, but I just don’t think that’s the case. 

For starters, I have no connection issues with any products, devices, services, anything in my home. My homebridge works flawlessly with all other plugins and with the alarm system. But the cameras just don’t work right. 

My homebridge has been portforward, and DMZed, and that made no difference to the issue. I’ve completely formatted my homebridge and started from scratch and the issue persists. 

When the plugin is installed or updated, the cameras (both snapshots and live streams) work perfectly. No issues. For a temporary period of time 

Then, snapshots won’t update, streams fail to connect. No errors when looking at logs, nothing. But if I go in the ring app it works without a hitch. 

It starts working hours later sometimes sporadically, but only briefly. But the biggest thing that’s makes me feel there is something with the plugin is that if I install an update or reinstall the plugin, it starts working again just fine. 

Again, just temporarily. After a later time it just won’t work anymore, except rarely and sporadically. 

I feel there is more to this. It’s not just a connection error. The plugin is having some issue that a reinstall/update temporarily resolves. There’s no reason it can only connect after a reinstall/update.

**Comment by metroidmen** [comment]
After checking with the new logging update I see a plethora of messages stating: “Session hardware_id not found. Creating a new session and trying again”

**Comment by dgreif** [comment]
@metroidmen I’m sorry I left you hanging on previous issues. I do think there is an issue with the session hardware_ids and I think it would cause the scenarios that you have been reporting. I’m glad you were able to confirm you are seeing those logs as that really helps narrow it down. I am going to close this issue in favor of #92 since it clearly documents the same issue. Hopefully I can get this fixed for everyone this week
