### ISSUE TITLE
Error when updating from Homebridge 91A0

### ISSUE THREAD

**Issue by Encrypt512bit** [dgreif/ring#961]
# Bug Report

### Describe the Bug
When updating in Homebridge 91A0, from the plugins menu, when I hit update on Homebridge Ring:

Window pops up, showing there is a new version of Homebridge Ring. Going from V 11.0.1 to V 11.0.4., an error:
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-ring
npm ERR! dest /usr/local/lib/node_modules/.homebridge-ring-rVzgYZG4
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-ring' -> '/usr/local/lib/node_modules/.homebridge-ring-rVzgYZG4'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-06-04T12_50_11_153Z-debug.log

Operation failed. Please review log for details.

### To Reproduce
Start Homebridge
Go to Plugins
Hit update on homebridge-ring
See error above

### Expected behavior
Update successful.

### Screenshots/Logs
<img width="823" alt="image" src="https://user-images.githubusercontent.com/90489463/171999885-88594853-cd1a-49a9-a545-9025177009dc.png">

### Additional context
n/a

### Homebridge Ring Config
```
{
    "refreshToken": "xxx",
    "hideLightGroups": true,
    "hideDoorbellSwitch": true,
    "hideCameraLight": true,
    "hideCameraMotionSensor": true,
    "hideCameraSirenSwitch": true,
    "hideInHomeDoorbellSwitch": true,
    "hideAlarmSirenSwitch": true,
    "hideUnsupportedServices": true,
    "showPanicButtons": true,
    "platform": "Ring"
}

### Environment
 - OS: Raspbian GNU/Linux Bullseye (11) 
 - Node.js: v16.13.0
 - NPM: 8.1.4
 - homebridge-ring: v11.0.1 
 - homebridge: 1.4.1
 - hoobs: N/A

**Comment by sicknicholas** [comment]
Try deleting the temp directory first:
`sudo rf -rm /usr/local/lib/node_modules/.homebridge-ring-rVzgYZG4`

then try updating again.
