### ISSUE TITLE
Saying I need to update, but no aval updates

### ISSUE THREAD

**Issue by pricejordan41** [dgreif/ring#965]
# Bug Report

### Describe the Bug
 Getting an error code stating that ring requires homebridge version 1.4.0 - I am currently on 1.3.4 - but there are no available updates? Causing all ring items in HK to not appear in the hoobs interface or home app.

### To Reproduce
read logs? 

### Expected behavior
 to see and control ring devices from hoobs interface or home app

### Screenshots/Logs
 
![Screen Shot 2022-06-18 at 4 10 57 PM](https://user-images.githubusercontent.com/83792808/174457166-e9be7e45-7700-4ce9-8d1b-2088b9bf7605.png)

### Additional context
 Everything shows to be up to date?

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

{
    "platform": "Ring",
    "refreshToken": "XXXXXXXXX",
    "hideAlarmSirenSwitch": true,
    "hideUnsupportedServices": true,
    "locationIds": [
        "91eXXXXXXXXXXXXXXX"
    ],
    "hideCameraSirenSwitch": true
}

```

### Environment

 - OS: Hoobs??
 - Node.js: [e.g. 12.14.1] 14.19.0
 - NPM: [e.g 6.13.4] 6.14.16
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: 1.3.4
 - hoobs: 4.0.110

**Comment by dgreif** [comment]
This sounds like an issue with HOOBS not updating.  Please reach out to HOOBS support and hopefully they can help you get it updated.
