### ISSUE TITLE
Control over motion alerts and detection

### ISSUE THREAD

**Issue by Gitko01** [dgreif/ring#967]
# Feature Request

### Description
 A clear and concise description of the problem or missing capability...
I would love to be able to control whether the camera will send motion alerts to my phone.
I would also love to control whether the camera will detect motion in the first place.
My main objective is to control whether motion alerts will be sent to my phone or not.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
A method that allows me to enable and disable motion alerts, and a method that allows me to enable and disable motion detection.
Example: camera.motionAlertDetection(false) OR = false
Example: camera.motionDetection(false) OR = false

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
I have not thought about any workarounds.
I don't know a lot about the API, so if there already is a motion alerts setting, I would love to hear about it!

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

My testing device is a Ring Doorbell v4.
I will be using a Ring Spotlight Cam as my main device when I am finished with my website.

**Comment by dgreif** [comment]
Controlling if alerts are sent to your phone is done on a per-device basis and isn't something that can be done from a different _session_, which is the situation with `ring-client-api`. You should be able to control whether motion detection is enabled period, but I don't currently have the time to dig into that feature. Feel free to open a PR if you get it working
