### ISSUE TITLE
Can’t create bridge

### ISSUE THREAD

**Issue by derflr** [dgreif/ring#968]
# Bug Report

I can no longer add a child bridge or any cameras. Been using for many months with no issues now nothing comes up on HB or HK. Removed all cameras now nothing can be added with a child bridge. 

I’m back to square one, nothing works and a child bridge can’t be created. 

I hope to get all cameras back on HM and HK, as of now nothing is adding including A child bridge.

{
      "_bridge" : {
        "port" : 46550,
        "username" : "88:2A:5B:B2:E3:41"
      },
      "hideAlarmSirenSwitch" : true,
      "hideCameraLight" : true,
      "hideCameraMotionSensor" : true,
      "hideCameraSirenSwitch" : true,
      "hideInHomeDoorbellSwitch" : false,
      "platform" : "Ring",
      "refreshToken" : "eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiYzEyODEwMGIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2NTQ4NzM0OTksImlzcyI6IlJpbmdPYXV0aFNlcnZpY2UtcHJvZDp1cy1lYXN0LTE6MzJjNTdkMzkiLCJyZWZyZXNoX2NpZCI6InJpbmdfb2ZmaWNpYWxfYW5kcm9pZCIsInJlZnJlc2hfc2NvcGVzIjpbImNsaWVudCJdLCJyZWZyZXNoX3VzZXJfaWQiOjQxOTQxMDg1LCJybmQiOiI5bklBYUhSMGZPQzBZUSIsInNlc3Npb25faWQiOiIzMWQ3NjYzMC01MzUwLTRjYWUtOTIzYy00MDAxZjM5YjFkZDUiLCJ0eXBlIjoicmVmcmVzaC10b2tlbiJ9.a8jJ8dFPt-1UvCthv9g8crUBeMJ25P8tnkBarvXHevaToNvnWE4zgcbvT-ayeg2l25kPvG5zZTu8MJLNzpz3FA"

Have been using for many months now it’s stopped working

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

imezone	GMT-0400
OS	Raspbian GNU/Linux Buster (10)
Hostname	raspberrypi
IPv4 (eth0)	192.168.86.111
IPv6 (eth0)	fd13:55d2:ceb9:4769:b50d:75bd:6887:b56b
Node.js Version	v14.17.6
User	homebridge
Storage Path	/var/lib/homebridge
Config Path	/var/lib/homebridge/config.json
Service Mode	Yes

**Comment by tsightler** [comment]
> Node.js Version v14.17.6

Assuming you have upgraded to v11 you will need to upgrade your NodeJS version to v16.  There are plenty of issues already documenting this so searching closed issues should help you.

**Comment by derflr** [comment]
This definitely worked!  Thanks so much!
