### ISSUE TITLE
Lauchn stream with motion sensor/ button/ Contact sensor

### ISSUE THREAD

**Issue by ADCLBA** [dgreif/ring#969]
# Feature Request

### Description
 A clear and concise description of the problem or missing capability...

Is it possible to launch a stream vue for a defined time when a motion sensor switch on, or contact sensor switch on

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

Creation of a virtual button for lauching streaming vue (automatically recorded on ring server)
After, create an automatisation, when contacted switch on, live view start

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dgreif** [comment]
This is something you could build using the `ring-client-api`, but I don't think there would be a wide use case for this in `homebridge-ring`.  I'm sorry but this isn't a feature I'm interested in implementing

**Comment by ADCLBA** [comment]
Hello dgreif,

Thank you for your answer

I have to admit that for a new user, the plugin you mentioned is not so friendly in comparison with the Homebridge ring plugin

I will try to do it with this plugin

**Comment by dgreif** [comment]
Sorry for the confusion, ring-client-api is actually an npm package that can be used to interact with Ring using JavaScript/typescript and would require you to write code. It's not installable in homebridge.
