### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by dhut1832** [dgreif/ring#97]
Wanted to see if I could get some insight in the the errors I'm getting when trying to install on raspberry pi:

(node:12342) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN engine rxjs@6.5.2: wanted: {"npm":">=2.0.0"} (current: {"node":"8.11.1","npm":"1.4.21"})
npm ERR! tar.unpack untar error /root/.npm/sip/0.0.5/package.tgz
npm ERR! tar.unpack untar error /root/.npm/socket.io-parser/3.3.0/package.tgz
npm ERR! tar.unpack untar error /root/.npm/has-binary2/1.0.3/package.tgz
npm ERR! tar.unpack untar error /root/.npm/socket.io-adapter/1.1.1/package.tgz
npm ERR! tar.unpack untar error /root/.npm/engine.io/3.3.2/package.tgz
npm ERR! tar.unpack untar error /root/.npm/socket.io-client/2.2.0/package.tgz
npm ERR! tar.unpack untar error /root/.npm/rxjs/6.5.2/package.tgz
npm ERR! tar.unpack untar error /root/.npm/ipaddr.js/1.9.1/package.tgz
npm ERR! tar.unpack untar error /root/.npm/dns-packet/5.2.1/package.tgz
npm ERR! tar.unpack untar error /root/.npm/ip-regex/4.1.0/package.tgz
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.79-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i" "-g" "homebridge-ring"
npm ERR! cwd /home/pi
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! fetch failed https://registry.npmjs.org/turbo-crc32/-/turbo-crc32-1.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/redent/-/redent-2.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/yargs-parser/-/yargs-parser-10.1.0.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

**Comment by dgreif** [comment]
I would try upgrading node to 10.16.1 and npm to the latest version

**Comment by dgreif** [comment]
@dhut1832 did that work for you?

**Comment by dgreif** [comment]
I'm assuming you got it working.  Let me know if you are still having issues.

**Comment by LegendaryWiz** [comment]
Hello , is there any confirmed way to upgrade Node to 10.16.1 without the need to remove and add Homebridge again ? I've been on the web for the whole day , tried various methods to upgrade Node but mine still stays at 8.2.1 . Seems like such an easy job but its taking me forever ...
