### ISSUE TITLE
Ring api doesn,t work anymore

### ISSUE THREAD

**Issue by jellevdburg95** [dgreif/ring#970]
# Bug Report

### Describe the Bug
Nothing works anymore since of today, i did an update for homebridge and got some warnings. After the update all my ring devices were not in apple home kit anymore

### To Reproduce
 - Create an `ApiClient`
 - Attempt to ...
 - See error

### Expected behavior
Pictograms for my alarm, sensors and cameras in apple home kit

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - ring-client-api: [e.g 6.0.3]

**Comment by dgreif** [comment]
@jellevdburg95 you didn't provide any logs or environment info, so I'm going to have to guess here.  You are likely running an older version of node (12 or 14) but node 16 is required for the latest version.  See https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js for details on how to update.

**Comment by jellevdburg95** [comment]
![A40C8306-B693-499C-A3EB-57763ACA4439](https://user-images.githubusercontent.com/96651829/174838799-6b1289e8-4082-4ac1-b48c-f0d4f3363722.png)
![CE688B80-F17B-415E-AD1F-2E2BD95189C1](https://user-images.githubusercontent.com/96651829/174838802-b4e361df-e9b9-4f31-a1cc-0bd6bb3ef022.png)

this are all the warnings i get

**Comment by dgreif** [comment]
Yep, it says it requires node 16 but the current is node 14
