### ISSUE TITLE
Option to support Critical Alerts

### ISSUE THREAD

**Issue by photoneffect** [dgreif/ring#972]
# Feature Request

### Description
The Critical Alerts feature is available on the Home app to passthrough alerts despite the users Focus mode OR vibrate settings.  The Ring app itself sends alarm notifications this way so that if a user has his phone on silent and Do Not Disturb it will still play a sound.  Can this option be added so that alarm notifications from the homebridge-ring plugin sent through the Home app are also sent via Critical Alert?

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dgreif** [comment]
Unfortunately there is not any way to control critical alerts from homebridge, however I'm 99% sure that alarm triggers are already critical alerts when they come from the Home app.  Have you tried this to see if they are?

**Comment by photoneffect** [comment]
I just tried it and yes, alarm triggers are critical alerts.  Appreciate the info, though.  I will stick to using Pushover and automations to trigger critical alerts for other things.
