### ISSUE TITLE
log in issue

### ISSUE THREAD

**Issue by Scarney316** [dgreif/ring#974]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 - Create an `ApiClient`
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
6/27/2022, 5:03:20 PMRing BridgeLoaded plugin 'homebridge-ring'
6/27/2022, 5:03:20 PMRing BridgeLoading 1 platforms...
6/27/2022, 5:03:20 PMRing BridgeRingWARNINGPlugin is not configured. Visit https://github.com/dgreif/ring/tree/master/homebridge#homebridge-configuration for more information.
6/27/2022, 5:03:20 PMRing BridgeBridge is running on port 51836.
6/27/2022, 5:03:35 PMhomebridge-ringERRORring login failed
6/27/2022, 5:03:35 PMhomebridge-ringERRORgetaddrinfo EAI_AGAIN oauth.ring.com
6/27/2022, 5:04:24 PMhomebridge-ringERRORring login failed
6/27/2022, 5:04:24 PMhomebridge-ringERRORgetaddrinfo EAI_AGAIN oauth.ring.com
6/27/2022, 5:04:29 PMNest BridgeNestERRORNest API call to subscribe to device settings updates returned an error: EAI_AGAIN
6/27/2022, 5:04:29 PMNest BridgeNestRetrying in 10 seconds.
6/27/2022, 5:04:49 PMNest BridgeNestERRORNest API call to subscribe to device settings updates returned an error: EAI_AGAIN
6/27/2022, 5:04:49 PMNest BridgeNestRetrying in 10 seconds.
6/27/2022, 5:04:50 PMhomebridge-ringERRORring login failed
6/27/2022, 5:04:50 PMhomebridge-ringERRORgetaddrinfo EAI_AGAIN oauth.ring.com
6/27/2022, 5:05:27 PMhomebridge-ringERRORring login failed
6/27/2022, 5:05:27 PMhomebridge-ringERRORgetaddrinfo EAI_AGAIN oauth.ring.com
6/27/2022, 5:09:10 PMNest BridgeNestERRORNest API call to subscribe to device settings updates returned an error: EAI_AGAIN
6/27/2022, 5:09:10 PMNest BridgeNestRetrying in 10 seconds.
6/27/2022, 5:09:30 PMNest BridgeNestERRORNest API call to subscribe to device settings updates returned an error: EAI_AGAIN
6/27/2022, 5:09:30 PMNest BridgeNestRetrying in 10 seconds.
6/27/2022, 5:09:50 PMNest BridgeNestERRORNest API call to subscribe to device settings updates returned an error: EAI_AGAIN
6/27/2022, 5:09:50 PMNest BridgeNestRetrying in 10 seconds.
6/27/2022, 5:10:10 PMNest BridgeNestERRORNest API call to subscribe to device settings updates returned an error: EAI_AGAIN
6/27/2022, 5:10:10 PMNest BridgeNestRetrying in 10 seconds.
6/27/2022, 5:10:30 PMNest BridgeNestERRORNest API call to subscribe to device settings updates returned an error: EAI_AGAIN
6/27/2022, 5:10:30 PMNest BridgeNestRetrying in 10 seconds.
6/27/2022, 5:10:50 PMNest BridgeNestERRORNest API call to subscribe to device settings updates returned an error: EAI_AGAIN
6/27/2022, 5:10:50 PMNest BridgeNestRetrying in 10 seconds.
6/27/2022, 5:11:10 PMNest BridgeNestERRORNest API call to subscribe to device settings updates returned an error: EAI_AGAIN
6/27/2022, 5:11:10 PMNest BridgeNestRetrying in 10 seconds.
6/27/2022, 5:13:54 PMhomebridge-ringERRORring login failed
6/27/2022, 5:13:54 PMhomebridge-ringERRORgetaddrinfo EAI_AGAIN oauth.ring.com
6/27/2022, 5:15:19 PMNest BridgeNestERRORNest API call to subscribe to device settings updates returned an error: EAI_AGAIN
6/27/2022, 5:15:19 PMNest BridgeNestRetrying in 10 seconds.
6/27/2022, 5:15:39 PMNest BridgeNestERRORNest API call to subscribe to device settings updates returned an error: EAI_AGAIN
6/27/2022, 5:15:39 PMNest BridgeNestRetrying in 10 seconds.
6/27/2022, 5:15:59 PMNest BridgeNestERRORNest API call to subscribe to device settings updates returned an error: EAI_AGAIN
6/27/2022, 5:15:59 PMNest BridgeNestRetrying in 10 seconds.

### Additional context
 Add any other context about the problem here.

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - ring-client-api: [e.g 6.0.3]

**Comment by Scarney316** [comment]
Can not connect account.  User and password have been double checked.  I get the code and enter that.  That is when i get the message about invalid password or user

**Comment by dgreif** [comment]
I'm not able to recreate this issue. It's possible the Ring api was just having some problems.  Would you mind trying it again now?

**Comment by Scarney316** [comment]
I was able to connect and setup the bridge.  But when the API tries to connect it fails.  I am not as home to copy a part of the log but can later this afternoon and send itSent from my iPhone12 Max ProScott VarneyOn Jun 29, 2022, at 10:15, Dusty Greif ***@***.***> wrote:﻿
I'm not able to recreate this issue. It's possible the Ring api was just having some problems.  Would you mind trying it again now?

**Comment by Scarney316** [comment]
Here is a screen shot of the log. Sent from my iPhone12 Max ProScott VarneyOn Jun 29, 2022, at 10:22, Scott Varney ***@***.***> wrote:﻿I was able to connect and setup the bridge.  But when the API tries to connect it fails.  I am not as home to copy a part of the log but can later this afternoon and send itSent from my iPhone12 Max ProScott VarneyOn Jun 29, 2022, at 10:15, Dusty Greif ***@***.***> wrote:﻿
I'm not able to recreate this issue. It's possible the Ring api was just having some problems.  Would you mind trying it again now?

**Comment by dgreif** [comment]
@Scarney316 I'm not seeing a screenshot, maybe it didn't attach properly

**Comment by Scarney316** [comment]
The only other plug-in I have is Nest.  That is all.  Sent from my iPhone12 Max ProScott VarneyOn Jun 30, 2022, at 15:45, tsightler ***@***.***> wrote:﻿
EAI_AGAIN is a DNS lookup problem.  That means it can only either be a real DNS issue, or, perhaps more likely, some other plugin which is using outdated dependencies and breaking NodeJS internal http functions.  Do you have other plugins installed?  if so, what are they?

**Comment by tsightler** [comment]
In the logs above the Nest plugin was producing the same EAI_AGAIN error.  Maybe double check your DNS settings?

**Comment by Scarney316** [comment]
Ok this maybe getting a little above my head. I am running a Eero wireless setup.  Not sure on a work around. Sent from my iPhone12 Max ProScott VarneyOn Jun 30, 2022, at 16:07, tsightler ***@***.***> wrote:﻿
In the logs above the Nest plugin was producing the same EAI_AGAIN error.  Maybe double check your DNS settings?

**Comment by dgreif** [comment]
This is a network issue, and is unrelated to the plugin.  Since networks can vary so widely, this isn't something I can help debug.  I wish you luck!

**Comment by Scarney316** [comment]
Thank you.  I am going. To dump my hoobs  box into the trash.  Sent from my iPhone12 Max ProScott VarneyOn Jul 10, 2022, at 13:21, Dusty Greif ***@***.***> wrote:﻿
Closed #974 as not planned.
