### ISSUE TITLE
Unable to Login Ring Credentials under Config

### ISSUE THREAD

**Issue by Rygy12** [dgreif/ring#975]
# Bug Report

### Describe the Bug
When I go into the configuration on Ring plug-in, I scroll down and see a single blank box that says “Link Account”. That’s promising. I click the box and there’s zero instructions, just a place to type. I assume I enter in my Ring email login… I type it in and, nothing, even after saving. I’m so new and bad at this, not sure what I’m missing. 

### To Reproduce
 - go to ring plug-in I’m home manager
 - Config
 - Scroll down to Link Account
 - Enter in my email in the box and save

### Expected behavior
< nothing happens, where do you enter the password in at?

### Screenshots/Logs
![87789A15-9FA0-4B53-9D95-5B5747B80690](https://user-images.githubusercontent.com/108312513/176069517-2c2d0830-c73a-44e7-a1bd-38ae2601af72.png)
![AFE61D6A-4472-4143-8775-538B35B0E077](https://user-images.githubusercontent.com/108312513/176069520-21586e74-91d2-4816-8d1f-9a51da0ec725.png)
![3558D154-3B44-41FF-BAA1-A9D09199896C](https://user-images.githubusercontent.com/108312513/176069526-1dfda3ca-81d8-4e3b-a4b0-87ce27c15747.png)

### Additional context
N/A

### Environment
Home Manager app

**Comment by dgreif** [comment]
Is this in the HOOBS app? If so, please reach out to HOOBS support
