### ISSUE TITLE
Front Door Detected Motion. Loading snapshot before sending event to HomeKit

### ISSUE THREAD

**Issue by Kepro** [dgreif/ring#979]
# Feature Request
Option to disable snapshot taking (if possible)

### Description
it takes a couple of seconds to ring the bell or get homekit notification...

**Comment by dgreif** [comment]
While this is possible to add, it's not something I'm interested in adding at this time.  Additional configuration options mean more maintenance overhead, and the snapshot code is all very complicated as it is.
