### ISSUE TITLE
no motion sensor iOS 13 b6

### ISSUE THREAD

**Issue by paqpaqpaq** [dgreif/ring#98]
on iOS 13 beta 6, the motion sensor is not showing.
I have deleted the camera, trashed the corresponding persist file, set the config to motionhide false and buttonhide false
Then add the camera again and then it will also state it will install a separate motion sensor. So far so good.
When the camera eventually is added, the motion sensor does not show up in IOS13, but it does in iOS12

**Comment by dgreif** [comment]
iOS 13 is going to a lot of work to hide the motion sensor, but it is still there.  Go into the camera -> Settings -> Accessories.  You should see the motion sensor and the light/siren/button (depending on camera type).  Let me know if you see it there.

**Comment by paqpaqpaq** [comment]
you are right!
thanks
