### ISSUE TITLE
cameras unresponsive, but log looks normal to me

### ISSUE THREAD

**Issue by rfiorentino1** [dgreif/ring#985]
### Streaming Issue

Hi! I really hate creating yet ANOTHER streaming issue for you to deal with, but I'm mainly trying to narrow down the possibilities and explore every avenue of why this isn't working, and wanted to see if any other users are having similar issues. I'd consider myself pretty techie, but this one has me stumped. I cannot stream from any Homebridge cameras from within the Home app, (I have nest and ring), all of them say no response. Every once in a while I get a video feed, but can't hear audio or pass audio through to the camera. So far I've tried:

1. rebooting router, home hubs, home bridge etc, and all of the troubleshooting steps listed.
2. 2. Reinstalling ffmpeg
3. 3. combing through both home bridge debug logs and plugin debug logs, everything looks normal to me, no errors, except for a "operation timed out" from ffmpeg, see below.
4. 4. node is latest LTS version, everything else is up to date
I've spent about 4 hours now racking my brain/network etc trying to figure this out with no luck; long story short I can't use discord, so figured the next best thing would be posting here. The plugin also seems to be communicating with Ring itself correctly, because live views are created when I try to stream from the home app.
I've also noticed quite a bit of "unable to reach ring server..." messages in the logs, but I looked that up as well and doesn't seem to effect the operation of the plugin. All other functions, alarm, etc are working perfectly. The last  version of this plugin that streamed successfully for me was 11.0, but now that has stopped working as well. Router/hardware etc hasn't changed, so I'm a little baffled. The only thing I haven't tried yet is moving/isolating the Ring plugin to it's own child bridge, as I've seen a few prior closed issues where other plugins were effecting it, but I'm hesitant to do that because I'd have to redo all automations, which are about 30.
 Here are the relevant logs; the first log on the 8th was the only time that video appeared without a no response in HomeKit, but no audio either direction. Thank you to you and the rest of the community for any help/suggestions/guidance, it's greatly appreciated.

[ring log 07-4.log](https://github.com/dgreif/ring/files/9075910/ring.log.07-4.log)
[ring log 07-8.log](https://github.com/dgreif/ring/files/9075911/ring.log.07-8.log)

### Proposed Solution

What does "operation timed out" refer to? Could this be cause for a stream to not load/be unresponsive in the home app? ffmpeg issue (not related to plugin)?

### Environment

Homebridge

### What operating system are you on?

Mac

### Relevant log output

see files above

### Honesty Time

- [X] I swear this is worth your time!

**Comment by dgreif** [comment]
`Operation timed out` is normal during the end of a streaming session, so nothing to look into there.  The logs look like a normal working streaming session.  Given the Ring cameras _and_ Nest cameras aren't working, my guess is that your issue is network related or HomeKit related.  Are you running a beta version of iOS or tvOS?  Do you have a VPN turned on? Is your phone on the same network as your homebridge server, with no firewall blocking access between them?  Does it work on LTE vs wifi?

**Comment by rfiorentino1** [comment]
I'm currently running beta of iOS 16, but this was happening long before that. It doesn't work on cellular either, and no vpns anywhere. There's no firewall that I know of between the phone and home bridge server, I just need to figure out how to confirm that. Even if I try to pull up the feed on the homebridge server itself, through the mac home app it also doesn't work, so I would think that would also rule out the firewall issue. That's why I'm confused, because everything seems normal… Lol. I'll close this issue for now, because I don't think it's anything related directly to this plug-in, but feel free to keep the conversation going if anyone has any thoughts/suggestions

**Comment by rfiorentino1** [comment]
As noted in the garbled audio thread, the last working version for me of this plug-in is 9.24.0. I just updated to 11.1 and still no luck. I have managed to fix the nest camera issue, which seemed to be something with codecs, so now Ring is the only camera plug-in that is still giving me issues when not on 9.24.0. Any suggestions?

**Comment by dgreif** [comment]
This looks like many of the other streaming issues unfortunately. I'll continue to optimize streaming when I'm able, but I can't do anything specific for this issue.

**Comment by rfiorentino1** [comment]
I've never had any streaming issues with this plug-in at all, up until versions 10 and above. So not sure what changed between then and now but clearly something is going on there. I'll try to keep digging into things as well but I'm limited as to what I can do because I don't know enough about the plug-in's development And how the stream is created etc to really troubleshoot on my own

**Comment by dgreif** [comment]
v10/v11 was a complete re-write of the streaming setup for the plugin. It added a lot of new features, like the ability to stream from cameras using Ring Edge, but it also caused new issues for a small subset of users. I'm not sure streaming is something I can ever get "perfect". If v9 worked well for you, I suggest you revert back to that version and occasionally try the latest version to see if things are working.

**Comment by rfiorentino1** [comment]
Is there a way that I can play with/modify the codec that the plug-in is using to stream? I think that may be the main issue here, as that's what I had to change with the nest plug-in. I am now using h264_video toolbox for nest

**Comment by dgreif** [comment]
The video portion of the Ring stream is actually _not_ transcoded by the plugin like the Nest stream is. Luckily Ring sends the video in a format that is consumable directly by HomeKit. Audio is transcoded, but that shouldn't prevent streaming from working. Do you mind posting the logs from an attempted stream?

**Comment by dgreif** [comment]
Just saw you have them in your original description. Those appear to show the stream working just fine. One thing you can try is setting the new `unbridgeCameras` option that was added in `11.1.0`. You will need to re-add your cameras to HomeKit individually, but it will act as a bit of a reset on the settings on the HomeKit side and might fix things for you

**Comment by rfiorentino1** [comment]
Awesome, I'll try that, thanks so much. That's the weird thing, the logs look normal but HomeKit definitely won't stream and says camera unresponsive. I'll play around a little and report back.

**Comment by rfiorentino1** [comment]
Just updated to 11.2.1, and unabridged the camera/doorbell and re-added it. Still no luck, unresponsive. Is there a way for me to temporarily disable the audio transcoding/only send video to HomeKit, to see if that's the issue? Driving me crazy because I feel like it's so close but so far lol
