### ISSUE TITLE
Ring Plugin Not Working: 

### ISSUE THREAD

**Issue by cwintr** [dgreif/ring#986]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 - Start Homebridge
 - Nothing shows up in the Hoobs Accessories or the Homekit App
 - See error in logs

### Expected behavior
For the ring app to work so that my ring cameras appear in the homekit

### Screenshots/Logs
7/9/2022, 11:16:38 PMRing BridgeERRORError loading plugin "homebridge-ring"
7/9/2022, 11:16:38 PMRing BridgeWARNINGNo plugins installed.
7/9/2022, 11:16:38 PMRing BridgeLoading 1 platforms...
7/9/2022, 11:16:38 PMRing BridgeBridge is running on port 51826.

### Additional context
None

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
Not sure what this is

```

### Environment
 - OS: Mac Hoobs App. Version 4.2.5
 - Node: 16.16.0
 - NPM: Not sure what this means
 - homebridge-ring: 11.0.5
 - homebridge: 1.4.1
 - hoobs: 4.2.5

**Comment by dgreif** [comment]
`BridgeWARNINGNo plugins installed` - this indicates the ring plugin is not actually installed.  Please reach out to HOOBS support if you need help with getting it installed properly.
