### ISSUE TITLE
[Streaming]: 

### ISSUE THREAD

**Issue by arlieeh** [dgreif/ring#988]
### Streaming Issue

ERRORStreaming video only - found ffmpeg, but libfdk_aac is not installed. See https://github.com/dgreif/ring/wiki/FFmpeg for details.

### Proposed Solution

including libfdk_aac

### Environment

HOOBS

### What operating system are you on?

Mac

### Relevant log output

```shell
ERRORStreaming video only - found ffmpeg, but libfdk_aac is not installed. See https://github.com/dgreif/ring/wiki/FFmpeg for details.
```

### Honesty Time

- [X] I swear this is worth your time!

**Comment by dgreif** [comment]
Please search previous issue for similar errors
