### ISSUE TITLE
Apple TV issue

### ISSUE THREAD

**Issue by xkyle22x** [dgreif/ring#990]
As the title states I have an issue where with one of my Apple TV's when motion is detected the window pops up but does not display a picture. 
This is only happening on 1 ATV the other 2 work as they should and show the camera stream. 
I have reset the tv and re-linked the account in homebridge to no avail. 

# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
Can you stream the problematic camera from your phone?

**Comment by xkyle22x** [comment]
No it won't work at the moment from the home app.

**Comment by dgreif** [comment]
Ok, does it work from the Ring app?

**Comment by xkyle22x** [comment]
Yes it does.

**Comment by xkyle22x** [comment]
![image](https://user-images.githubusercontent.com/66627364/179902059-2a58791b-4f47-4594-8384-7fc4ea397f29.jpeg)

This is what it's giving me in the logs. Seems to be restarting when I try to open stream in HK

**Comment by dg-test-prod** [comment]
@xkyle22x please update to the latest version and use the `unbridgeCameras` option. You will have to re-add your cameras to the Home app individually, but it should fix apple tv streaming

**Comment by dgreif** [comment]
@xkyle22x please update to the latest version and use the `unbridgeCameras` option. You will have to re-add your cameras to the Home app individually, but it should fix apple tv streaming

**Comment by xkyle22x** [comment]
Is working now, thank you.
