### ISSUE TITLE
HK Video "No Response" on version 11+

### ISSUE THREAD

**Issue by Dima-Kal** [dgreif/ring#993]
Same issue as in https://github.com/dgreif/ring/issues/930 - was working for a while after the fix but suddenly stopped working again (I also commented on that issue that the fix has solved the issue)
downgrading back to 9.24 is currently working

HB is running on docker container :

Node.js Version	[v16.16.0](https://homebridge.io/w/JTKEF)
User	root
Storage Path	/var/lib/homebridge
Config Path	/var/lib/homebridge/config.json
Plugin Path	/var/lib/homebridge/node_modules
Docker	Yes
Service Mode	Yes

**Comment by Dima-Kal** [comment]
any update?

**Comment by dgreif** [comment]
Could you please provide some logs from a failed streaming request?

**Comment by dgreif** [comment]
There are many similar issue. Closing this one as a duplicate
