### ISSUE TITLE
Link Account button missing

### ISSUE THREAD

**Issue by evenchung** [dgreif/ring#994]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by evenchung** [comment]
Hello, 

I have been using this Ring plugin with Hoobs Box for more than 1 year with great appreciation.

I have upgraded to the newest update 11.0.7 and encountered the miss linkage with Ring devices with my Home Kit.

After reset my Hoobs Box to factory setting and download the newest Ring plugin 11.0.7, the "Link Account" button no longer appear at the Configuration page.

I tried to Google the problem, but I haven't be able to find the solution.

Please help.  Thank you!

**Comment by dgreif** [comment]
Please reach out to HOOBS support for help with this issue.  The button that is missing is part of their UI, so they should be able to help you get to the bottom of it.
