### ISSUE TITLE
[Streaming]: 

### ISSUE THREAD

**Issue by ergener** [dgreif/ring#995]
### Streaming Issue

Every since I upgraded to the latest version the snapshots seems to work sporadically, but when I try to live stream any camera from an iOS device I see below in the logs:

7/20/2022, 4:28:28 PMHOOBSRingPreparing Live Stream for Driveway
7/20/2022, 4:28:28 PMHOOBSRingPreparing Live Stream for Driveway
7/20/2022, 4:28:28 PMHOOBSRingStream Prepared for Driveway (0.315s)
7/20/2022, 4:28:28 PMHOOBSRingStream Prepared for Driveway (0.315s)
7/20/2022, 4:28:28 PMHOOBSRingActivating stream for Driveway (0.435s)
7/20/2022, 4:28:28 PMHOOBSRingActivating stream for Driveway (0.435s)
7/20/2022, 4:28:29 PMHOOBSRingiceConnectionStateChange: completed
7/20/2022, 4:28:29 PMHOOBSRingiceConnectionStateChange: completed
7/20/2022, 4:28:29 PMHOOBSRingStopped Live Stream for Driveway
7/20/2022, 4:28:29 PMHOOBSRingStopped Live Stream for Driveway
7/20/2022, 4:28:29 PMHOOBSRingconnectionStateChange: closed
7/20/2022, 4:28:29 PMHOOBSRingconnectionStateChange: closed
7/20/2022, 4:28:29 PMHOOBSRingiceConnectionStateChange: closed
7/20/2022, 4:28:29 PMHOOBSRingiceConnectionStateChange: closed

After which the bridge with ring plug-in seems to crash and restart.

This happens for all of the 11 cameras.

HOOBS version: 4.2.5
Node Version: 16.16.0
homebridge-ring version: 11.0.7

### Proposed Solution

I am not really sure if there is a debug mode for logging as I cannot see what the problem is based on below log.

### Environment

HOOBS

### What operating system are you on?

Other

### Relevant log output

```shell
7/20/2022, 4:28:28 PMHOOBSRingPreparing Live Stream for Driveway
7/20/2022, 4:28:28 PMHOOBSRingStream Prepared for Driveway (0.315s)
7/20/2022, 4:28:28 PMHOOBSRingActivating stream for Driveway (0.435s)
7/20/2022, 4:28:29 PMHOOBSRingiceConnectionStateChange: completed
7/20/2022, 4:28:29 PMHOOBSRingStopped Live Stream for Driveway
7/20/2022, 4:28:29 PMHOOBSRingconnectionStateChange: closed
7/20/2022, 4:28:29 PMHOOBSRingiceConnectionStateChange: closed
7/20/2022, 4:28:38 PMHOOBS starting
```

### Honesty Time

- [X] I swear this is worth your time!

**Comment by LeviJSmith** [comment]
I'm having the same issue.

**Comment by rnsc** [comment]
Same issue for me, it ends with an RTP error.
```
22/07/2022, 18:05:55Ring BridgeRingPreparing Live Stream for Front Door
22/07/2022, 18:05:55Ring BridgeRingStream Prepared for Front Door (0.758s)
22/07/2022, 18:05:55Ring BridgeRingActivating stream for Front Door (0.872s)
22/07/2022, 18:05:58Ring BridgeRingiceConnectionStateChange: completed
22/07/2022, 18:05:58Ring BridgeRingStopped Live Stream for Front Door
22/07/2022, 18:05:58Ring BridgeRingconnectionStateChange: closed
22/07/2022, 18:05:58Ring BridgeRingiceConnectionStateChange: closed
22/07/2022, 18:05:59Ring BridgeERROR[Ring Bridge 9E7F@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Front Door' was slow to respond!
22/07/2022, 18:06:07Ring Bridge starting
22/07/2022, 18:06:12Ring BridgeLoaded plugin 'homebridge-ring'
22/07/2022, 18:06:12Ring BridgeLoading 1 platforms...
```

**Comment by ergener** [comment]
Duplicate. See: https://github.com/dgreif/ring/issues/1005
